libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/base/sort.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/tests/PluggableBarChart.test.tsx, libs/sdk-ui-ext/src/internal/index.ts, libs/sdk-ui-ext/src/internal/interfaces/SortConfig.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts, libs/sdk-ui-ext/src/internal/utils/tests/propertiesHelper.test.ts
JIRA: TNT-449
- Handlers and communication path from pluggable visualization to the outer world to send chart config
- Implementation of sort status in Bar chart
---
--- …
=> Sort config passed from PV to the AD

tools/dashboard-plugin-template/README.template.md
=> RELATED: RAIL-4018 Add export catalog info to plugin template README

libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts, libs/sdk-backend-tiger/src/backend/workspace/permissions/test/permissions.test.ts
=> Update Tiger permission - canRefreshData base on  ANALYZE permission

examples/sdk-examples/src/constants/routes.ts, examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithAccessor.tsx, examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithAccessorSrc.tsx, examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommand.tsx, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/converters/filterConverters.ts, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/src/plugins/customizer.ts
=> RELATED: RAIL-3963 Add more docs links, add details, fix format

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommandSrc.tsx
=> RELATED: RAIL-3963 Use exported catalog instead of hard-coded URI

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
=> RELATED: RAIL-4032 Add missing translation for error message

examples/sdk-examples/src/examples/attributeFilter/AttributeFilterButtonExample.tsx, examples/sdk-examples/src/examples/attributeFilter/AttributeFilterExample.tsx
=> RELATED: RAIL-4003 Refactor attributeFilter basic examples

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommandSrc.tsx, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/filters.ts
* change API maturity level
* add more docs
* add an example
JIRA: RAIL-4042
---
--- …
=> RELATED: RAIL-4042 Make ChangeFilterContextSelection public

libs/sdk-ui-ext/src/dashboardView/DashboardViewErrorBoundary.tsx, libs/sdk-ui-ext/src/dashboardView/defaultDashboardThemeModifier.ts, libs/sdk-ui-ext/src/dashboardView/hooks/internal/useDashboardLayoutData.ts, libs/sdk-ui-ext/src/dashboardView/hooks/useDashboard.ts, libs/sdk-ui-ext/src/dashboardView/hooks/useDashboardAlerts.ts, libs/sdk-ui-ext/src/dashboardView/hooks/useDashboardPdfExporter.ts, libs/sdk-ui-ext/src/dashboardView/hooks/useDashboardWidgetExecution.ts, libs/sdk-ui-ext/src/dashboardView/mergeFiltersWithDashboard.ts, libs/sdk-ui-ext/src/dashboardView/types.ts
=> RELATED: RAIL-4046 Specify version that will remove DashboardView

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
JIRA: TNT-450
In context of KD, referencePoint is not defined
---
--- …
=> Handle undefined referencePoint

libs/sdk-ui-tests-e2e/Dockerfile
=> RELATED: FET-793 sdk-ui-tests-e2e: use node16 image

libs/sdk-ui-dashboard/src/model/events/dashboard.ts
=> RELATED: RAIL-4043 Clarify DashboardDeinitialized docs

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/PluggableColumnChart.test.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/ChartSorting/AttributeDropdown/AttributeDropdown.tsx, libs/sdk-ui-kit/src/ChartSorting/ChartSorting.tsx, libs/sdk-ui-kit/src/ChartSorting/ChartSortingDropdownBody.tsx, libs/sdk-ui-kit/src/ChartSorting/MeasureDropdown/MeasureDropdown.tsx, libs/sdk-ui-kit/src/ChartSorting/index.ts, libs/sdk-ui-tests/stories/visual-regression/kit/ChartSorting/ChartSorting.tsx
- Udpate ChartSorting dialog to match AD types
JIRA: TNT-451
---
--- …
=> Chart Sorting Dialog

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts, libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
=> BUGFIX: MSF-23081 Should update the order tab on the navigation when enable CSV Uploader

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
=> RELATED: RAIL-4044 Pass renderBody prop to render custom dropdown body

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-dashboard/package.json
The 1.8.0 version does not work with the TypeScript version we are using so we cap it at < 1.8.0 to prevent issues.
We also upgrade it to the latest supported version.
---
--- …
=> RELATED: FET-987 Cap @reduxjs/toolkit version and upgrade it

libs/sdk-ui-dashboard/package.json
Cherry pick of 80965c6 from #2270 to release.
---
--- …
=> RELATED: FET-987 Cap @reduxjs/toolkit version

libs/sdk-ui-pivot/src/impl/tableFacade.ts
=> PivotTable not propagate manually reset columns via props

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/PluggableColumnChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/__snapshots__/PluggableColumnChart.test.tsx.snap, libs/sdk-ui-kit/src/ChartSorting/AttributeDropdown/AttributeDropdown.tsx, libs/sdk-ui-kit/src/ChartSorting/ChartSorting.tsx, libs/sdk-ui-kit/src/ChartSorting/ChartSortingDropdown.tsx, libs/sdk-ui-kit/src/ChartSorting/ChartSortingDropdownBody.tsx, libs/sdk-ui-kit/src/ChartSorting/MeasureDropdown/MeasureDropdown.tsx, libs/sdk-ui-kit/src/ChartSorting/test/ChartSorting.test.tsx, libs/sdk-ui-kit/styles/scss/chartSorting.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
- Obtain default and available sorts.
---
--- …
=> Column chart sorting

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts, libs/sdk-backend-base/src/ldmFactories/dashboard/insightWidgetFactory.ts, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts, libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts, libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/analyticalWidgets.ts, libs/sdk-backend-spi/src/workspace/dashboards/tests/widgets.fixtures.ts, libs/sdk-backend-tiger/src/convertors/tests/AnalyticalDashboardConverter.test.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/fluidLayout/builder/tests/__snapshots__/layout.test.ts.snap, libs/sdk-ui-dashboard/src/converters/test/filterConverters.test.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/Layout.fixtures.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/__snapshots__/sizing.test.ts.snap, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/DashboardWidgetRenderer.tsx, libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/test/utils.test.ts, libs/sdk-ui-ext/src/dashboardView/test/converters.test.ts, libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/builder/tests/__snapshots__/layout.test.ts.snap, libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/__snapshots__/sizing.test.ts.snap
=> TNT-187: Ability to hide widget title

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/tests/PluggablePieChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/tests/__snapshots__/PluggablePieChart.test.tsx.snap
=> Pie/Donut Chart default and available sorts

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/__snapshots__/PluggableComboChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
=> Combo chart sorting

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/widgetConfiguration.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadAvailableDisplayFormRefs.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap
=> RELATED: NAS-3219 nonexisting attributes in filtercontext

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/user/userSelectors.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
=> RELATED: RAIL-4025 Make user related selectors public

libs/sdk-ui-charts/src/charts/heatmap/Heatmap.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/__snapshots__/PluggableHeatmap.test.tsx.snap
- Default and available sorts
JIRA: TNT-459
---
--- …
=> Heatmap chart sorting

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/__snapshots__/PluggableAreaChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/tests/PluggableBarChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/tests/__snapshots__/PluggableBarChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/PluggableColumnChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/__snapshots__/PluggableColumnChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/utils/sort.ts
JIRA: TNT-519, TNT-521
Better handling of some bucket items combinations
---
--- …
=> Bar, Column, Area sorting fixes

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/donutChart/PluggableDonutChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx
- Provide high-level description of the following Pluggable charts (buckets, dimesions, sorts):
* DonutChart
* PieChart
JIRA: RAIL-4052
---
--- …
=> Add PieChart and DonutChart description

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadUser.ts, libs/sdk-ui-dashboard/src/model/store/user/userReducers.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/interfaces.ts
=> RELATED: RAIL-4025 Replace deprecated IUser type with the current one

examples/sdk-examples/Dockerfile, libs/sdk-ui-tests-e2e/Dockerfile, libs/sdk-ui-tests-e2e/Dockerfile_local, libs/sdk-ui-tests-e2e/scripts/run-scenarios-local.js, libs/sdk-ui-tests/backstop/run-backstop.sh, libs/sdk-ui-tests/backstop/scenarios.config.js, libs/sdk-ui-tests/stories/serve-storybook.sh, libs/sdk-ui-tests/tests/end-to-end/_infra/testcafeUtils.js
=> Use latest alpine image

libs/sdk-ui-dashboard/src/model/store/user/userSelectors.ts
=> RELATED: RAIL-4027 Example on how to use selectCurrentUser selector

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-geo/api/sdk-ui-geo.api.md, libs/sdk-ui-geo/src/GeoChart.ts, libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx, libs/sdk-ui-geo/styles/scss/main.scss
=> Improve scrolling on Geocharts

libs/sdk-ui-dashboard/src/model/store/permissions/permissionsSelectors.ts
=> RELATED: RAIL-4028 User permissions examples

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts, libs/sdk-backend-base/src/ldmFactories/dashboard/insightWidgetFactory.ts, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts, libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts, libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/analyticalWidgets.ts, libs/sdk-backend-spi/src/workspace/dashboards/tests/widgets.fixtures.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/widgetConfiguration.ts, libs/sdk-backend-tiger/src/convertors/tests/AnalyticalDashboardConverter.test.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/fluidLayout/builder/tests/__snapshots__/layout.test.ts.snap, libs/sdk-ui-dashboard/src/converters/test/filterConverters.test.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/Layout.fixtures.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/__snapshots__/sizing.test.ts.snap, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/DashboardWidgetRenderer.tsx, libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/test/utils.test.ts, libs/sdk-ui-ext/src/dashboardView/test/converters.test.ts, libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/builder/tests/__snapshots__/layout.test.ts.snap, libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/__snapshots__/sizing.test.ts.snap
=> Revert insight title hiding

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/donutChart/DonutChart.tsx, libs/sdk-ui-charts/src/charts/pieChart/PieChart.tsx, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts, libs/sdk-ui-charts/src/highcharts/index.ts, libs/sdk-ui-charts/src/index.ts, libs/sdk-ui-charts/src/interfaces/chartConfig.ts
=> Skip default series data sort for Pie/Donut when custom sort is enabled

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Name subsection in configuration panel for Tiger

libs/sdk-ui-dashboard/src/internal.ts
=> RELATED: RAIL-4046 Add PLATFORM_DATE_FORMAT to internal exports

examples/sdk-examples/webpack.config.js
=> Remove obsolete backend client-demo-be

examples/sdk-examples/src/examples/advanced/datePicker/MonthPickerExample.tsx, examples/sdk-examples/src/examples/advanced/dynamicMeasures/DynamicMeasuresExample.tsx, examples/sdk-examples/src/examples/advanced/responsive/ResponsiveExample.tsx, examples/sdk-examples/src/examples/arithmeticMeasures/ArithmeticMeasureChangeExample.tsx, examples/sdk-examples/src/examples/basic/LineChartExample.tsx, examples/sdk-examples/src/examples/basic/StackedAreaChartExample.tsx, examples/sdk-examples/src/examples/dateFilter/DateFilterWithColumnChartExample.tsx, examples/sdk-examples/src/examples/export/PivotTableExportExample.tsx, examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_DDMMYYYY.tsx, examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_MDYY.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableExample.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableRowGroupingExample.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableSortingAggregationExample.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableSortingExample.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableSubtotalsExample.tsx, examples/sdk-examples/src/examples/pivotTable/PivotTableTotalsExample.tsx, examples/sdk-examples/src/examples/sorting/MeasureSortingExample.tsx, examples/sdk-examples/src/examples/timeOverTimeComparison/SamePeriodColumnChartExample.tsx
This replaces the deprecated form of date dataset catalog exports.
JIRA: RAIL-4047
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a …
=> RELATED: RAIL-4047 Use proper DateDatasets catalog exports

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-ext/src/dataLoaders/test/dataLoaders.mock.ts
=> Introduce methods for getting all scheduled emails

examples/sdk-examples/src/components/login/state.ts, libs/api-client-bear/src/metadata.ts, libs/sdk-backend-base/src/dummyBackend/tests/index.test.ts, libs/sdk-backend-bear/src/backend/workspace/attributes/index.ts, libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-mockingbird/src/recordedBackend/userManagement.ts, libs/sdk-backend-tiger/src/backend/workspace/permissions/test/permissions.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/resetDashboardHandler.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts, libs/sdk-ui-dashboard/src/model/utils/alertsUtils.ts, libs/sdk-ui-dashboard/src/model/utils/tests/alertsUtils.test.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranteeIcons.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranteeItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/shareDialogMappers.test.ts, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/ShareDialog.tsx, libs/sdk-ui/src/base/react/placeholders/tests/typeAliases.test.tsx, tools/applink/src/base/sourceDiscovery.ts, tools/plugin-toolkit/src/inspectCmds/inspectDashboard.ts
* remove useless awaits
* deduplicate imports
* simplify promises
---
--- …
=> RELATED: RAIL-4047 avoid some code smells

common/scripts/ci/run_dashboard_plugin_tests.sh
- Add missing build command
JIRA: RAIL-3888
---
--- …
=> Dashboard Plugin Tests - correct ci script

NOTICE
=> LR-1024: update NOTICE file

libs/sdk-ui-ext/.dependency-cruiser.js, libs/sdk-ui-ext/src/internal/translations/de-DE.json, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/src/internal/translations/es-ES.json, libs/sdk-ui-ext/src/internal/translations/fr-FR.json, libs/sdk-ui-ext/src/internal/translations/ja-JP.json, libs/sdk-ui-ext/src/internal/translations/nl-NL.json, libs/sdk-ui-ext/src/internal/translations/pt-BR.json, libs/sdk-ui-ext/src/internal/translations/pt-PT.json, libs/sdk-ui-ext/src/internal/translations/ru-RU.json, libs/sdk-ui-ext/src/internal/translations/zh-Hans.json
=> RELATED: RAIL-4046 Remove some more DashboardView mentions

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/scheduledMail/GdcScheduledMail.ts, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/scheduledMails.ts, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/scheduledMail.ts
=> Support widget attachments in scheduled email

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/common/settings.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
JIRA: TNT-187
Just keep disabled for now, we plan to test later with Tiger backend
---
--- …
=> RELATED: TNT-187 Added tiger support for enableHidingOfWidgetTitle

libs/sdk-ui/src/base/localization/bundles/de-DE.json
=> Fix translation after import from translator agency

libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/test/utils.test.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/utils.ts
=> Reverse scheduled emails list

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/common/settings.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx
=> RELATED: TNT-542 Remove FF enableSectionHeaders

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
=> Add test selectors for scheduled email management

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-loaders/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-theme-provider/package.json, libs/sdk-ui-vis-commons/package.json, skel/sdk-skel-tsx/package.json, tools/dashboard-plugin-tests/package.json
=> RELATED: FET-1001 Upgrade node-sass to fix security advisory

common/scripts/build-docs.js, libs/sdk-backend-bear/src/auth.ts, libs/sdk-backend-tiger/src/auth.ts
- remove sdk-backend-bear from ignored packages
- remove sdk-backend-tiger from ignored packages
- refactor TSDoc to align API reference with other packages
JIRA: RAIL-4022
---
--- …
=> RELATED: RAIL-4022 expose sdk-backend packages in API reference

libs/sdk-backend-bear/src/backend/index.ts
We want to keep whatever ajaxSettings the user did on the original
backend instance to be carried over to the new one when creating
it using the withTelemetry function.
The other copying function still do not keep this as they may affect
authentication and this may mean the ajaxSettings are no longer
relevant in the context of the new instance.
JIRA: RAIL-4096
---
---
-   [ ] commit …
=> RELATED: RAIL-4096 Preserve ajaxSettings when using withTelemetry on bear

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
=> Switch off comparative gestures in edit mode

libs/sdk-ui-ext/src/internal/translations/ja-JP.json
=> Wrong translation JP

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentsSelectionDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/FormatOptionsDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/ScheduleDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DeleteScheduleConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmails.tsx
=> Add scheduled email test selectors

libs/sdk-ui-kit/src/Overlay/Overlay.tsx
This reverts commit 56eb7470d587c30339512b777d27f62f0e6d4fe7.
JIRA: FET-626
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.m …
=> RELATED: FET-626 Revert "Register handlers with capture"

libs/sdk-backend-bear/src/backend/workspace/facts/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/facts.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/facts/index.ts, libs/sdk-backend-tiger/src/backend/workspace/facts/index.ts
=> RELATED: RAIL-4118 Add getFacts support to backend SPI

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmails.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
=> Responsiveness & theming for scheduled management

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/FormatOptionsDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/ScheduleDropdown.tsx
Jira: TNT-617, TNT-618
---
--- …
=> Fix schedule widgets bugs

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
=> Fix report specific translations in scheduling

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/test/ScheduledMailDialogRenderer.test.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/interfaces.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/repeat.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/scheduledMailSummary.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/test/scheduledMailSummary.test.ts
=> Use only React state in ScheduledMailDialogRenderer

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
Currently insight menu (...) icon is slightly overlapping the legend on mobile device.
JIRA: TNT-601
---
--- …
=> RELATED: TNT-601 Fixing insight menu icon (...) on mobile devices

libs/sdk-backend-bear/api/sdk-backend-bear.api.md, libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/scheduledMails.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/scheduledMail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/useScheduledEmailManagement.ts
=> Extend ScheduledMail with users

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
- replace the selector for date attributes with the query to ease the network traffic
JIRA: RAIL-4128
---
--- …
=> RELATED: RAIL-4128 Replace selectors with query

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmails.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss, libs/sdk-ui-kit/src/Icon/icons/Widget.tsx
=> Tabs for schedule management dialog

tools/dashboard-plugin-template/webpack.config.js
This prevents issues when using singletons, now we let webpack negotiate
the best version (and it chooses only one if it can so no need for
singleton). Singleton: true made the first loaded version get stuck in
so that changing to a dashboard that needs a newer version did not work
as the older one was stuck there and was not overwritten.
This solution does not work with prerelease versions because semver
does not have query meaning:
"Give me a range of versions **including prereleases**"
so we allow the user to opt out of the version checking if they want to
use prerelease versions (or more specificaly combine plugins with
different prerelease versions on the same dashboard).
JIRA: RAIL-4117
---
| …
=> RELATED: RAIL-4117 Rework how plugins define their dependencies

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx
=> Translation string id for management emails

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyInsightMenu/LegacyInsightMenuItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts
=> RELATED: FET-1004 Update type signature for menu item onClick

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentsSelectionDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/ScheduleDropdown.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
=> UI for no insights in export dialog

libs/sdk-backend-tiger/src/backend/workspace/catalog/rsqlFilter.ts, libs/sdk-backend-tiger/src/backend/workspace/catalog/test/rsqlFilter.test.ts
=> Fix unneeded double quotes on tags RSQL filter

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> Create a FF for enable / disable DSM page on Tiger

libs/sdk-ui-kit/src/Overlay/Overlay.tsx
This reverts commit fe708b093154d96d4cd7117bf970f0cbab3cd11c.
JIRA FET-185
---
--- …
=> Revert "No more default stopPropagation"

libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/LabelTypeConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts, libs/sdk-backend-tiger/tests/integrated/__snapshots__/catalog.test.ts.snap
=> RELATED:  NAS-4143 Add support for attribute labels

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> RELATED: TNT-630 Enable hiding of widget title for Tiger

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts
=> Skip elements loading for date attributes on tiger

libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts
=> Reset edited schedule when edit dialog is cancelled

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/test/ScheduledMailDialogRenderer.test.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/datetime.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
=> Scheduled dialog number of unsubscribed recipients

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/metadataUtilities.ts, libs/sdk-backend-tiger/src/backend/workspace/catalog/rsqlFilter.ts
=> Extened MetadataUtilities to be able load user related entities

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/datetime.ts
=> Remove date from default scheduled mail subject

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/widthItemsHelpers.ts
=> Filter non matching column attribute buckets identifiers

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/AttributeFilterButtonUtils.ts, libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/en-US.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> RELATED: RAIL-4103 Fix ignoring empty value in subtitle

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx, libs/sdk-ui-kit/src/EditableLabel/index.ts, libs/sdk-ui-kit/src/EditableLabel/tests/EditableLabel.test.tsx
=> Use forwardRef on EditableLabel and pass to the root element

common/changes/@gooddata/sdk-ui-all/mkn-rail-4179_2022-04-12-13-43.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/render.ts, libs/sdk-ui-dashboard/src/model/events/render.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardAsyncRender.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightWidgetDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/index.ts, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/execution/index.ts, libs/sdk-ui/src/execution/useExecutionDataView.ts, libs/sdk-ui/src/execution/useInsightDataView.ts
- Productize asynchronous rendering utilities of the Dashboard component
- Make these utilities public is necessary to ensure that PDF exports of the Kpi Dashboards extended by Dashboard Plugin(s) with custom widgets will be rendered correctly
JIRA: RAIL-4179
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/do …
=> Productize asynchronous rendering utilities

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Remove FF enableCustomMeasureFormatting

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
=> Scheduling bugfixes

libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/RelativePresetFilterItems.tsx, libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/RelativeDateFilterForm.tsx, libs/sdk-ui-filters/src/DateFilter/utils/DateConversions.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Button/Button.tsx, libs/sdk-ui-kit/src/Button/typings.ts, libs/sdk-ui-kit/src/Dropdown/DropdownButton.tsx
=> Define Button's value also as a ReactNode

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/saveScheduledEmailHandler.ts, libs/sdk-ui-dashboard/src/model/commands/scheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useSaveScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts
=> Save scheduled mail with original filter context 

examples/playground/webpack.config.js, examples/sdk-examples/webpack.config.js
=> RELATED: FET-1011 Optional chaining in examples webpack configs

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
=> TNT-730 Fix new external recipients check in scheduled mail

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> Update of translations hotfix

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> Hotfix to master

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/stripLocalIdentifierFromFilters.ts
=> Fix filterContext comparison in scheduled email

libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/results/facade.ts, libs/sdk-ui/src/base/results/internal/definitionMethods.ts, libs/sdk-ui/src/base/results/internal/resultDataMethods.ts, libs/sdk-ui/src/base/results/internal/resultMetaMethods.ts, libs/sdk-ui/src/execution/DataViewLoader.tsx, libs/sdk-ui/src/execution/index.ts
- Currently, it's not easy to use series/slices approach without GoodData.UI React components and hooks, so expose utility function for it
JIRA: RAIL-4067
---
--- …
=> Add DataViewLoader convenience API 

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts, libs/sdk-ui-tests-e2e/cypress/integration/02-sdk-ui-filters/dateFilter.spec.ts
=> Increase categories data points limit to 366

common/config/rush/pnpm-lock.yaml, libs/sdk-backend-spi/package.json, libs/sdk-backend-tiger/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-theme-provider/package.json
Some of the dependencies were no longer used, so we remove them to keep things as simple as possible.
---
--- …
=> RELATED: FET-1022 remove unused dependencies

libs/sdk-backend-tiger/src/backend/index.ts
The backend support is already deployed to Tiger stg.
JIRA: TNT-676
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do …
=> Enable generic date filters for Tiger

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/title/RenderModeAwareTitle.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/title/index.tsx
Make the title editable
---
--- …
=> RELATED: RAIL-4105 Make the title editable

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> Add enableEmbedButtonInAD FF

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Icon/Icon.tsx, libs/sdk-ui-kit/src/Icon/icons/Dataset.tsx
=> CAL-436: Add dataset icon

libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx, libs/sdk-ui-kit/styles/scss/dialog.scss
=> Revert Dialog footer css changes

libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/internal/components/dialogs/embedInsightDialog/EmbedInsightDialog.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/EmbedInsightDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/components/CodeArea.tsx, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/types.ts, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/index.ts, libs/sdk-ui-tests/stories/visual-regression/kit/EmbedInsightDialog/CodeArea.tsx
=> Add onCopy callback to codeArea

libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts
We must change the way a single display form is loaded because
loading the label directly does not contain the information whether
it is its attribute's defaultView.
Instead, we use RSQL to load the attribute and then find the requested
label in its labels. We also remove several obsolete convertors.
JIRA: RAIL-4210
---
--- …
=> RELATED: RAIL-4210  Reflect defaultView in metadata loading

libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/kd.ts
=> RELATED: RAIL-4203 Add InsightSaved event in KD event types

libs/sdk-ui/src/base/localization/bundles/en-US.json
=> Add localisations validation to SDK-UI

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/deleteDialog/DefaultDeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/deleteDialog/DeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/deleteDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/deleteDialog/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/index.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/index.ts, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/selectors.ts, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/index.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/types.ts, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/topBar/DefaultTopBar.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/topBar/index.tsx, libs/sdk-ui-dashboard/src/types.ts, libs/sdk-ui-dashboard/styles/scss/topBar.scss, libs/sdk-ui-kit/src/List/ListItem.tsx
- add delete button and delete dialog
- update menu items visibility in edit mode
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …
=> RELATED: RAIL-4106 menu button render mode

libs/sdk-ui-charts/src/charts/areaChart/AreaChart.tsx, libs/sdk-ui-charts/src/charts/barChart/BarChart.tsx, libs/sdk-ui-charts/src/charts/bulletChart/BulletChart.tsx, libs/sdk-ui-charts/src/charts/columnChart/ColumnChart.tsx, libs/sdk-ui-charts/src/charts/donutChart/DonutChart.tsx, libs/sdk-ui-charts/src/charts/lineChart/LineChart.tsx, libs/sdk-ui-charts/src/charts/pieChart/PieChart.tsx, libs/sdk-ui-charts/src/charts/scatterPlot/ScatterPlot.tsx, libs/sdk-ui/src/base/react/ErrorComponent.tsx, libs/sdk-ui/src/base/react/LoadingComponent.tsx
=> RELATED: RAIL-4213 Replace http with https in docs links

tools/dashboard-plugin-template/configTemplates/ts/tsconfig.json, tools/dashboard-plugin-template/tsconfig.json
* Remove misleading note
* Remove not needed exclude: there will never be "esm" folder there
JIRA: RAIL-4224
---
--- …
=> RELATED: RAIL-4224 Remove nonsense parts of tsconfig for plugins

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Enable FF (uiSetting) enableDataSourceManagement by default

libs/sdk-backend-tiger/src/backend/index.ts
- check user is organization admin tiger
JIRA: SD-2100
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my …
=> Add isOrganizationAdmin method to tiger specific functions

libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/EmbedInsightDialogBase.tsx
=> Align bubble in Embed dialog header

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx
=> RELATED: TNT-804 Fixing the edit of time input

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
=> Fix infinitive load of elements in AttributeFilter

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/attributes/elements/index.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/hooks/useLoadMissingData.ts, libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
=> Enable alternative display form selection feature flag for Tiger

libs/sdk-backend-bear/src/backend/workspace/catalog/factory.ts
- removes the backend call to acquire unlisted flag which is now part of the data returned within the catalog api calls to make the loading time of the dashboard component faster
JIRA: RAIL-4188
---
---
-   [ ] …
=> RELATED: RAIL-4188 Remove unnecessary backend call

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/src/model/store/dateFilterConfig/dateFilterConfigSelectors.ts, libs/sdk-ui-dashboard/src/presentation/componentDefinition/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayer.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/config.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/AttributeFilterDropZoneHint.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DefaultAttributeFilterDraggingComponent.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/main.scss, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/components/AttributeFilterButtonDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/components/AttributeFilterButtonDropdownButton.tsx, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/constants.ts
=> RELATED: RAIL-4112 Add support for filter drag and drop ordering

libs/sdk-ui-kit/styles/scss/dialogList.scss
=> Update dialogList min-height

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DashboardSidebar.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/RenderModeAwareDashboardSidebar.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/main.scss, libs/sdk-ui-dashboard/styles/scss/sidebar.scss
Add a component for the left drawer
JIRA: RAIL-4111
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pu …
=> RAIL-4111 Add a component for the left drawer

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/GeoPushpinChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/geoConfigCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/getReactEmbeddingCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/insightViewCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/insightViewConfig.ts, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/tests/__snapshots__/insightViewCodeGenerator.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/tests/insightViewCodeGenerator.test.ts
=> Missing mapboxToken and locale for codegen of insightView

common/scripts/ci/run_storybook_publish.sh, libs/sdk-ui-tests/Dockerfile, libs/sdk-ui-tests/nginx/nginx.conf
=> Introduce script that publish built static Storybook as a docker image

common/scripts/ci/run_storybook_publish.sh
=> Publish built static Storybook docker image to ECR as well

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/AttributeFilterDropZoneHint.tsx
=> Fix attribute filter dropzone visibility

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilterHandler.ts
=> RELATED: RAIL-4228 Single and MultiSelect filter

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/componentDefinition/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DeleteDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayer.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/AttributeFilterDropZoneHint.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDrop.ts, libs/sdk-ui-dashboard/src/presentation/index.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/sidebar.scss
- add attribute filter removing
- introduce useDashboardDrop hook
JIRA: RAIL-4166
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …
=> RELATED: RAIL-4166 Add support for removing attribute filters

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/AttributeFilterButtonUtils.ts, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton/AttributeFilterButtonUtils.ts
=> Attribute filter handle empty state

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/index.ts, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/InsightListNoData.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/index.ts, libs/sdk-ui-dashboard/src/presentation/insightList/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/types.ts
Add the InsightList component
JIRA: RAIL-4113 
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-re …
=> RAIL-4113 Add the InsightList component

libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
=> RELATED: TNT-825 Improved dashboard title edit

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Enable enableEmbedButtonInAD by default for tiger

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts
Theming will be enabled for all tiers by default and FF will be removed.
JIRA: TNT-692
---
--- …
=> Remove enableUiTheming FF logic

libs/api-client-bear/src/gooddata.ts, libs/api-client-tiger/README-DEV.md, libs/api-client-tiger/README.md, libs/api-client-tiger/package.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-bear/README.md, libs/sdk-backend-bear/package.json, libs/sdk-backend-bear/src/index.ts, libs/sdk-backend-mockingbird/src/index.ts, libs/sdk-backend-spi/README.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-tiger/README.md, libs/sdk-backend-tiger/package.json, libs/sdk-backend-tiger/src/index.ts, libs/sdk-ui-dashboard/src/model/store/permissions/permissionsSelectors.ts, tools/catalog-export/src/index.ts
Make sure GoodData Cloud is mentioned alongside of GoodData.CN.
Also improve the package descriptions.
---
--- …
=> RELATED: RAIL-4266 Mention GoodData Cloud

.eslintrc.js, libs/sdk-backend-base/src/decoratedBackend/attributes.ts, libs/sdk-backend-base/src/ldmFactories/catalog/attributeFactory.ts, libs/sdk-backend-bear/src/backend/user/index.ts, libs/sdk-backend-bear/src/backend/workspace/catalog/availableItemsFactory.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/tests/execution.test.ts, libs/sdk-backend-tiger/src/backend/user/index.ts, libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/fixLegacyElementUris.fixtures.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/saveScheduledEmailHandler.ts, libs/sdk-ui-dashboard/src/model/commands/insight.ts, libs/sdk-ui-dashboard/src/model/queries/insights.ts, libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/accessibleDashboardsEntityAdapter.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/CatalogAvailability.fixtures.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/scheduledMailRecipients.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/BaseChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/getInsightWithDrillDownAppliedMock.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-pivot/src/publicTypes.ts
- Update rest of the imports of the moved interfaces (that were moved from sdk-backend-spi to sdk-model)
- Now, none of these moved interfaces is imported in the whole sdk repository
- Also enable `no-duplicate-imports` eslint rule and fix found errors
JIRA: RAIL-4177
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/ …
=> RELATED: RAIL-4177 Update imports from sdk-backend-spi to sdk-model

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/client.ts, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/features/state.ts, libs/sdk-backend-tiger/src/backend/features/static.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/features/test/state.test.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
=> Add feature flags loading 

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Header/Header.tsx, libs/sdk-ui-kit/src/Header/typings.ts, libs/sdk-ui-kit/styles/scss/header.scss
=> SD-2164 Display Panther Trial Experience countdown on Header

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/index.ts
=> RELATED: RAIL-4171 Add missing DashboardRenderModeChanged export

libs/sdk-backend-tiger/src/backend/uiSettings.ts
Remove tiger's enableComboChart FF
JIRA: TNT-551
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull- …
=> RELATED: TNT-551 Remove enableComboChart FF

libs/sdk-ui-dashboard/.i18nrc.js, libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/ShowAllFiltersButton.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/InsightListNoData.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/SaveAsDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatExecuteOnSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatFrequencySelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatTypeSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/scheduledMailSummary.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatusIndicator.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/useExportHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/DashboardItemWithKpiAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialogBrokenFilters/KpiAlertDialogBrokenFilters.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialogWhenTriggeredPicker.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/utils/translationUtils.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiContent/KpiValue.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiContent/utils/translations.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/useInsightMenu.ts
=> FET-1033 - Add localisations validation to SDK-UI

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Overlay/ErrorOverlay.tsx
=> Wrap ErrorOverlay with IntlWrapper

libs/sdk-backend-tiger/src/backend/index.ts
- Get Organization expired date from Contract Entitlement
- JIRA: SD-2164
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …
=> Add organizationExpiredDate method to tiger specific functions

libs/sdk-backend-mockingbird/api/sdk-backend-mockingbird.api.md, libs/sdk-backend-mockingbird/src/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/attributes.ts, libs/sdk-backend-mockingbird/src/recordedBackend/elements.ts, libs/sdk-backend-mockingbird/src/recordedBackend/elementsUtils.ts, libs/sdk-backend-mockingbird/src/recordedBackend/tests/elementsUtils.test.ts, libs/sdk-backend-mockingbird/src/recordedBackend/types.ts, libs/sdk-backend-mockingbird/src/recordedBackend/userManagement.ts, libs/sdk-ui-filters/src/AttributeElements/AttributeElements.tsx, libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/tests/AttributeDropdown.test.tsx
Implement limiting items and selected elements options.
This allows testing of parent filters and similar things.
JIRA: RAIL-4231
---
--- …
=> RELATED: RAIL-4231 Expand elements in recordedBackend

libs/sdk-backend-mockingbird/src/recordedBackend/attributes.ts
- So we can use mockingbird for tests of the AttributeFilterHandler
JIRA: RAIL-4308
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contri …
=> Implement getAttributeByDisplayForm in mockingbird

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/index.ts, libs/sdk-backend-tiger/tsdoc.json
=> Export low level API used by NAS Home UI as TigerSpecificFunctions

libs/sdk-ui-kit/styles/scss/bubble.scss
=> Wrapped data item title single word string

libs/sdk-ui-pivot/src/CorePivotTable.tsx
=> sdk-ui-pivot: stop propagation on column resize

libs/sdk-backend-base/src/normalizingBackend/normalizer.ts, libs/sdk-backend-base/src/normalizingBackend/tests/normalizer.test.ts
=> Derived measure does not inherit the format from original measure

examples/playground/src/App.tsx, libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx, libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemContent.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss
Add selectedWidget behavior
JIRA: RAIL-4277
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reque …
=> RAIL-4277 Add selectedWidget behavior

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/state.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/features/test/state.test.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> NAS-3978 - Non-binary flags do not work on Tiger/Panther

libs/sdk-ui-kit/styles/scss/header.scss
=> Main navigation selected and hover state is not aligned on dashboard tab

libs/sdk-ui-filters/src/AttributeFilter@next/AttributeDropdown/AttributeDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeDropdown/tests/AttributeFilterItem.test.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilter.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton/AttributeFilterButtonUtils.ts, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton/hooks/useAttributeFilterButtonState.ts, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton/hooks/useFetchInitialElements.ts, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeDropdownAllFilteredOutBody.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeDropdownBody.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeDropdownButtons.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeDropdownItemsFiltered.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeDropdownList.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeFilterButton.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeFilterButtonDefaultDropdownBody.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeFilterButtonDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeFilterItem.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/types.ts, libs/sdk-ui-filters/src/AttributeFilter@next/utils/AttributeFilterUtils.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext.scss, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/Components/AttributeDropdownAllFilteredOutBody.tsx, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/Components/AttributeFilterButton.tsx, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/Components/AttributeFilterItem.tsx, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> Clean AttributeFilter NEXT  components

libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/types.ts
=> Separate current logic of AttributeFilterButton into hook

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts
=> RELATED: TNT-422 Fixing invalid configuration of value separators

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/state.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/features/test/state.test.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> BUGFIX: WS earlyAccess string is not evaluated

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/dateValueFormatter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts, libs/sdk-ui-pivot/src/impl/drilling/drilledRowFactory.ts
Also re-generate api-client-tiger with the proper nullable annotations for AttributeResultHeader and adapt the rest of the codebase to it.
---
--- …
=> RELATED: CAL-517 fix drilling on null attributes on tiger

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilterLoader/factory.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/impl/bridge/index.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/effects/index.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/effects/loadAttributeElementsFromBackend.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/effects/loadAttributeElementsFromStaticElements.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/reducers.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/sagas.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/selectors.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/types.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/main/reducers.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/state.ts, libs/sdk-ui-filters/src/AttributeFilterLoader/types/loader/index.ts
=> RELATED: RAIL-4231 Add static elements option to AttributeFilterLoader

common/config/rush/pnpm-lock.yaml, examples/playground/README.md, examples/playground/package.json
=> Upgrade `why-did-you-render`

libs/sdk-ui-dashboard/styles/scss/drillDialog.scss, libs/sdk-ui-kit/src/Overlay/OverlayController.tsx
=> Infinitely growing z-index for overlay

common/config/rush/pnpm-lock.yaml, examples/sdk-examples/package.json
=> Upgrade `react-datepicker` to v^4.8.0

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemContent.tsx
The solution was not correct, it broke other Overlays.
A better one will be created later.
JIRA: RAIL-4158
---
--- …
=> RELATED: RAIL-4158 Remove the widget deselect on click outslide

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/organizationUtilities.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
=> RELATED: TNT-858 Tiger specific functions for ldm modeler

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-filters/package.json, libs/sdk-ui-kit/package.json
- Minor upgrades.
JIRA: FET-1066, FET-1067
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reques …
=> Upgrade `react-window` and `react-textarea-autosize`

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
=> RELATED: TNT-866 Fixing Date within Scheduled Email Exporter

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadConnectingAttributesMatrix.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
=> RELATED: RAIL-4342 Optimisation of connecting attributes matrix loading

common/changes/@gooddata/sdk-ui-all/mkn-rail-4047_2022-06-30-07-44.json
=> Changelog review

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
=> Change publishLogicalModel type

tools/catalog-export/src/loaders/tiger/index.ts
=> Repair space before dot.

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
=> Upgrade `react-grid-system` to v^8.1.4

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Set enableReversedStacking FF to true by default

libs/sdk-ui-dashboard/src/internal.ts
=> RELATED: CAL-516 Add internal exports for KD

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> Tiger specific fns: Consolidate functions that return all data sources

libs/sdk-backend-bear/api/sdk-backend-bear.api.md, libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts, libs/sdk-backend-bear/src/index.ts
JIRA: CAL-531, RAIL-4359
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-b …
=> RAIL-4359 - Export converter for bucket

libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/KpiContent/KpiPop.tsx
React library has issues with chrome translate browser tooling.
There's a workaround to use wrapping in these particular situations:
https://github.com/facebook/react/issues/11538#issuecomment-390386520
---
---
- …
=> RELATED: TNT-900 Wrap Kpi percentage to avoid chrome translate issues 

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/RenderModeAwareDashboardSidebar.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/index.ts
=> RELATED: RAIL-4158 expose SidebarConfigPanel, fix naming

libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/RenderModeAwareDashboardSidebar.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfigurationItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useAttributeFilterConfigurationHandling.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useDateFilterConfigurationHandling.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditableDashboardKpi/KpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx
* make attribute filter changes optimistic
* make date filter changes optimistic
* improve naming
* fix some bugs
---
--- …
=> RELATED: RAIL-4158 fixes in KPI filter config

common/config/rush/browser-approved-packages.json, examples/playground/README.md, examples/playground/package.json, examples/playground/src/App.tsx, examples/playground/src/createBackend.ts, examples/playground/typings/globals.d.ts, examples/playground/webpack.config.js
Also update the proxy settings with current create-gooddata-react-app
values to keep up-to-date.
JIRA: FET-1102
---
--- …
=> RELATED: FET-1102 Add tiger support to playground

libs/sdk-ui-tests/scenarios/charts/areaChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/barChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/bubbleChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/bulletChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/columnChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/heatmap/base.tsx, libs/sdk-ui-tests/scenarios/charts/lineChart/base.tsx, libs/sdk-ui-tests/scenarios/charts/lineChart/responsive.tsx, libs/sdk-ui-tests/scenarios/charts/scatterPlot/base.tsx, libs/sdk-ui-tests/scenarios/charts/treemap/base.tsx, libs/sdk-ui-tests/scenarios/charts/xirr/base.tsx, libs/sdk-ui-tests/scenarios/charts/xirr/drilling.tsx, libs/sdk-ui-tests/scenarios/charts/xirr/theming.tsx, libs/sdk-ui-tests/scenarios/pivotTable/base.tsx, tools/reference-workspace/src/md/ext.ts
=> TRIVIAL: Use the modern datasets export in tests

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/metadataUtilities.ts, libs/sdk-backend-base/src/decoratedBackend/index.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/organization/index.ts, libs/sdk-backend-bear/src/backend/organization/styling.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/organization/index.ts, libs/sdk-backend-spi/src/organization/styling/index.ts, libs/sdk-backend-tiger/src/backend/organization/index.ts, libs/sdk-backend-tiger/src/backend/organization/styling.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ThemeConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/objRef/index.ts, libs/sdk-model/src/theme/index.ts
=> Introduce OrganizationStylingService

libs/sdk-ui-kit/src/Header/HeaderHelp.tsx, libs/sdk-ui-kit/styles/scss/header.scss
=> RELATED: SD-2301 Fixed dropdown help menu wrong position

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayer.tsx
- use different position for resize
JIRA: RAIL-4335
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pu …
=> RELATED:  RAIL-4335 Fix filter dragging

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> Apply selected theme in UI

tools/plugin-toolkit/src/_base/terminal/prompts.ts
=> RELATED: RAIL-4074 Add mention of GoodData Cloud to plugin toolkit

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/organization/styling.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/styling/index.ts, libs/sdk-backend-tiger/src/backend/organization/styling.ts
=> Extend OrganizationStylingService

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts, libs/sdk-ui-dashboard/src/plugins/customizer.ts, libs/sdk-ui-dashboard/src/plugins/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboardContexts/types.ts
=> Prepare customization API for filters

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> RELATED LOB-215 - Add dependencies entities api specific for Tiger/Panther

libs/sdk-ui-kit/src/Form/focus.ts
=> MED-200 - Invalid cancel frame, id -1

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
=> RAIL-4368 - Can't see the edit/share/(…) button when making the Dashboard title too long

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/scripts/ci/run_backstop_tests.sh, libs/sdk-ui-charts/package.json, libs/sdk-ui-charts/scripts/build.sh, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/scripts/build.sh, libs/sdk-ui-ext/package.json, libs/sdk-ui-ext/scripts/build.sh, libs/sdk-ui-filters/package.json, libs/sdk-ui-filters/scripts/build.sh, libs/sdk-ui-geo/package.json, libs/sdk-ui-geo/scripts/build.sh, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/scripts/build.sh, libs/sdk-ui-kit/styles/scss/variables.scss, libs/sdk-ui-pivot/package.json, libs/sdk-ui-pivot/scripts/build.sh, libs/sdk-ui-tests/backstop/run-backstop.sh, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json, libs/sdk-ui/styles/scss/_settings.scss
Also optimize the backstop tests job: build only necessary packages and use docekr --init.
JIRA: FET-1105
---
--- …
=> RELATED: FET-1105 Remove the foundation-sites dependency

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
=> TRIVIAL: Update localisations

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/src/measureNumberFormat/tests/MeasureNumberFormat.test.tsx, libs/sdk-ui-kit/src/measureNumberFormat/tests/fragments/MeasureNumberFormatFragment.ts, libs/sdk-ui-kit/src/syntaxHighlightingInput/SyntaxHighlightingInput.tsx, libs/sdk-ui-kit/src/syntaxHighlightingInput/tests/SyntaxHighlightingInput.test.tsx
=> Replace react-codemirror2

common/config/rush/pnpm-lock.yaml, examples/sdk-examples/package.json
- React 18 compatible version
JIRA: FET-1068
---
--- …
=> Upgrade `recharts`

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests/package.json, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json
=> RELATED: FET-1108 Upgrade @gooddata/numberjs 4.0.2 -> 4.0.3

libs/sdk-ui-kit/styles/scss/editableLabel.scss
=> RELATED: TNT-910 Align text to left in textarea of editableLabel

libs/sdk-ui-geo/api/sdk-ui-geo.api.md, libs/sdk-ui-geo/src/core/CoreGeoChart.tsx, libs/sdk-ui-geo/src/core/MapboxTokenProvider.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx, libs/sdk-ui-geo/src/index.ts
=> RAIL-4395 - Create a Mapbox token React provider

libs/sdk-ui-ext/src/internal/components/configurationControls/colors/colorDropdown/tests/ColorDropdown.test.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx, libs/sdk-ui-kit/src/EditableLabel/typings.ts, libs/sdk-ui-kit/styles/scss/editableLabel.scss
=> RELATED: TNT-910 Configuring editableLabel width based on property

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/metadataUtilities.ts, libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/meta/GdcMetadata.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/organization/styling.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/styling/index.ts, libs/sdk-backend-tiger/src/backend/organization/styling.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ColorPaletteConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ColorPaletteConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/colors/index.ts, libs/sdk-model/src/index.ts, libs/sdk-model/src/objRef/index.ts
=> Color Palette SPI changes

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> RELATED: SD-2314 Add msf.enableTenantCustomModel FF to IUISettings for TIger

libs/sdk-backend-tiger/src/backend/organization/styling.ts
=> Sort theme and colorPalette calls

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardList.tsx, libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardListButton.tsx, libs/sdk-ui-dashboard/src/presentation/dashboardList/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetDashboardItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx
Dashboard as target of interaction
Jira: RAIL-4403
---
--- …
=> Dashboard as target of interaction

libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ButtonWithIcon.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillOriginSelector/DrillOriginSelector.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargetType.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/getMappedConfigForWidget.ts
Selecting origin of interaction
Jira: RAIL-4413
---
--- …
=> Selecting origin of interaction

libs/sdk-ui-kit/src/StylingPicker/StylingPicker.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerBody.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerList.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerListItem.tsx
=> Fix dropdown delete logic in styling picker

libs/sdk-ui-ext/package.json, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/CheckboxControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/ConfigSection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/ConfigSubsection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/LabelSubsection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/NameSubsection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/tests/LabelFormatControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/tests/LabelRotationControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/tests/LabelSubsection.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/tests/NamePositionControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/axis/tests/NameSubsection.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/BaseChartConfigurationPanel.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/BubbleChartConfigurationPanel.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/BulletChartConfigurationPanel.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/ConfigurationPanelContent.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/GeoPushpinConfigurationPanel.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/ScatterPlotConfigurationPanel.test.tsx, libs/sdk-ui-ext/src/internal/components/tests/BaseVisualization.test.tsx, libs/sdk-ui-ext/src/internal/tests/testHelper.tsx
=> Enzyme to RTL (axis, configurationPanels, BaseVisualization) tests

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayerPreview/ContentDragPreview.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/AttributeFilterDropZoneHint.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
=> RELATED RAIL-4335: Improve placeholder indexing during attribute move

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useFilterExpansionByDragAndDrop.tsx
=> RELATED: RAIL-4415 Expand multi-row filter bar when attribute or attribute dragging

libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
=> RELATED: RAIL-4409 Fix section dropzone height

.gitlab-ci.yml, libs/sdk-ui-web-components/.gitignore, libs/sdk-ui-web-components/Dockerfile, libs/sdk-ui-web-components/nginx.conf, libs/sdk-ui-web-components/webpack.config.js
* Added Dockerfile for nginx server
* Added nginx configuration
* Adjusted build configuration to enable better caching for assets
JIRA: RAIL-4319
---
--- …
=> RELATED: RAIL-4319 Basic setup for CI pipeline

libs/sdk-ui-kit/src/StylingPicker/StylingPicker.tsx
=> Handle deleted current item

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/AttributeDisplayFormSelect/AttributeDisplayFormDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/AttributeDisplayFormSelect/AttributeDisplayFormDropdownButton.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/AttributeDisplayFormSelect/AttributeDisplayFormSelect.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/AttributeDisplayFormSelect/AttributeDisplayFormSelectItem.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterControllerData.ts, libs/sdk-ui-filters/src/internal.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> AttributeFilter DisplayForm select component

libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiAlertDialog/test/KpiAlertDialog.test.tsx
=> Remove failing test

libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
=> Discard loading once even css variables are set

libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilter.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterButton.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterDefaultComponents.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/AttributeFilterRenderer.tsx
=> Fix attributeFilter loading

libs/sdk-ui-kit/src/StylingPicker/StylingPicker.tsx
=> Dont try to find basic theme among custom themes

libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightEditMenuItems.tsx
=> RELATED: RAIL-4172 Change insight config panel interaction icon

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/SaveButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/types.ts, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/types.ts, libs/sdk-ui-dashboard/src/presentation/topBar/types.ts
We need this to better integrate into gdc-dashboards
JIRA: RAIL-4170
---
--- …
=> RELATED: RAIL-4170 Add SaveButton customization

libs/sdk-backend-tiger/src/backend/index.ts
=> Support colorPalette on Tiger now

examples/sdk-examples/src/constants/routes.ts, examples/sdk-examples/src/examples/attributeFilterNext/AttributeFilterButtonExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeFilterComponentExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeFilterExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeFilterHiddenElementsExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeFilterStaticElementsExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeParentChildFilterButtonExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeParentChildFilterButtonWithPlaceholderExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/AttributeParentChildFilterExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/UseAttributeFilterControllerExample.tsx, examples/sdk-examples/src/examples/attributeFilterNext/index.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/AttributeFilterDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Context/AttributeFilterContext.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterControllerData.ts, libs/sdk-ui-filters/src/AttributeFilter@next/index.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/common/selectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSelectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadCustomElements/loadCustomElementsReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageReducers.ts, libs/sdk-ui-filters/src/index.ts
- Add examples for new AttributeFilter components
- Add example for useAttributeFilterController hook
- Add examples for AttributeFilter static and hidden values
- Minor bug fixes
JIRA: RAIL-4217
---
---
-   [ ] …
=> Prepare examples for new AttributeFilter

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
This prevents re-renders when adding a new attribute filter.
This filter is noop, so it cannot change the effective widget filters.
JIRA: RAIL-4433
---
--- …
=> RELATED: RAIL-4433 Prevent some unnecessary re-renders

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/topBar/title/EditableTitle.tsx, libs/sdk-ui-dashboard/styles/scss/topBar.scss
* fix the font and color when editing
* autofocus it when the title is empty
* add the correct placeholder and other options
JIRA: RAIL-4431
---
--- …
=> RELATED: RAIL-4431 Fix editable dashboard title

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/src/model/commands/index.ts
=> RELATED: RAIL-4172 Add removeAttributeFilters command

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter@next/Components/DropdownButton/AttributeFilterDropdownButton.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/utils.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterComponents/AttributeFilterDropdownButton.tsx
=> Style filter button and DnD support, fix empty value

libs/sdk-ui-kit/src/Bubble/tests/Bubble.test.tsx, libs/sdk-ui-kit/src/Dialog/tests/ConfirmDialog.test.tsx, libs/sdk-ui-kit/src/Dialog/tests/ConfirmDialogBase.test.tsx, libs/sdk-ui-kit/src/Dialog/tests/ExportDialogBase.test.tsx, libs/sdk-ui-kit/src/Dialog/tests/HubspotConversionTouchPointDialogBase.test.tsx, libs/sdk-ui-kit/src/FilterLabel/FilterLabel.tsx, libs/sdk-ui-kit/src/FilterLabel/tests/FilterLabel.test.tsx, libs/sdk-ui-kit/src/Form/tests/Checkbox.test.tsx, libs/sdk-ui-kit/src/Header/WorkspacePickerHomeFooter.tsx, libs/sdk-ui-kit/src/Header/tests/HeaderAccount.test.tsx, libs/sdk-ui-kit/src/Header/tests/HeaderMenu.test.tsx, libs/sdk-ui-kit/src/Header/tests/WorkspacePickerHomeFooter.test.tsx, libs/sdk-ui-kit/src/List/LegacyListItem.tsx, libs/sdk-ui-kit/src/List/tests/LegacyList.test.tsx, libs/sdk-ui-kit/src/List/tests/LegacyListItem.test.tsx
RTL tests - 
- Bubble, ConfirmDialog, HubspotBase, FilterLabel, Checkbox, Header, List 
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/co …
=> Migrate to RTL (sdk-ui-kit)

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx, libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialogFooter.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPicker.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerBody.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerFooter.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerList.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerListItem.tsx
=> Telemetry for styling.

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/EmptyElementsSearchBar.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/AttributeFilterDropdownBody.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/types.ts, libs/sdk-ui-filters/src/AttributeFilter@next/constants.ts, libs/sdk-ui-filters/src/internal.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterAddons.scss, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownBody.scss, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilter.tsx, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterButton.tsx, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterCustomizations/DropdownBodyComponent.tsx, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterCustomizations/ElementsSearchBarComponent.tsx
=> Add support for custom dropdown width and empty search add to addons

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx
The class needs to be only applied when dragging.
JIRA: RAIL-4446
---
--- …
=> RELATED: RAIL-4446 Fix the last-drop-position s-class

libs/sdk-ui-filters/src/AttributeFilter@next/utils.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss
=> Add shadow to AttributeFilterButton and fix colour of selection and empty value

libs/sdk-ui-filters/src/AttributeFilter@next/Components/DropdownButton/AttributeFilterSimpleDropdownButton.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss
JIRA: RAIL-4444, RAIL-4445
---
--- …
=> RAIL-4444, RAIL-4445 Fix max size of Simple button and 0 selection count

libs/sdk-backend-base/src/decoratedBackend/index.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-bear/src/backend/organization/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/organization/index.ts, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/backend/organization/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts
=> RELATED: TNT-963 WhiteLabeling for Tiger backend

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
=> RELATED: TNT-965 Tiger API upgrade

.gitlab-ci.yml
=> RELATED RAIL-4319: Fixed invalid RegExp in Gitlab CI config

libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
=> Blank page after setting SPPY

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts
=> RELATED: TNT-965 ApiEntitlement export

libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss
=> RELATED: RAIL-4451 Adjust length of attributeFilter with selection

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts
=> RELATED: TNT-965 Export of ApiEntitlementEnum

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> Custom drill URL link

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/authActions.ts, libs/api-client-tiger/src/client.ts, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> FEATURE: SD-2354 Add Invitation function to specific function

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-kit/package.json
=> Update moment-timezone in SDK-UI to fix Vulnerabilities

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/errors/index.ts, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/utils/errorHandling.ts
=> Add ContractExpired error and make it possible to pass a handler for the error to the SDK

libs/sdk-backend-tiger/src/backend/organization/styling.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ColorPaletteConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/colors/index.ts, libs/sdk-model/src/index.ts
=>  Validate color palette format.  Enable theming for Tiger.

.gitlab-ci.yml
=> Fix condition for GitLab pipeline

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useRowsCalculator.ts
=> RAIL-4462: Hiding Date Filter Hides Away All Filters In The Dashboard

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> Enable theming for Tiger

libs/sdk-backend-tiger/src/utils/errorHandling.ts
=> REALTED: SD-2391 - Update the conditions for the Limit reached error

libs/sdk-backend-tiger/src/backend/organization/styling.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ColorPaletteConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/colors/index.ts, libs/sdk-model/src/index.ts
JIRA: TNT-1030
Deliver same fix as went to fix branch
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my- …
=> Validate color palette format. Enable theming for Tiger.

libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/hooks/useAutoOpenDropdownButton.ts, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Addons/hooks/useOnCloseDropdownButton.ts, libs/sdk-ui-filters/src/internal.ts
=> Create support hooks for AttributeFilter DropdownButton into SDK

libs/sdk-ui-filters/src/AttributeFilter@next/Components/ElementsSelect/AttributeFilterElementsSelectItem.tsx
=> Missing title property for attribute filter element

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss, libs/sdk-ui-kit/styles/scss/datepicker.scss
Cherry pick of f1c0a585bf9f0a69decb24e0
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-n …
=> RAIL-4460: cherry pick of CSS fix

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss, libs/sdk-ui-kit/styles/scss/datepicker.scss
Cherry pick of f1c0a585bf9f0a69decb24e07ebd8f12a10b7f0b
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-m …
=> RELATED: RAIL-4460: cherry pick of CSS fix

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts
=> Tiger OpenAPI settings resolver without workspace

libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterController.ts
=> Attribute filter ignore changes when provided filter selection changed

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/loadElementsFromBackend.ts
=> Add support of excludePrimaryLabel for AttributeFilter on Tiger

libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterController.ts
=> BUGFIX: RAIL-4450 Apply changes to the parent component state

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
=> Fix selecting single day in date range picker

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts
=> MED-209: Implement dummy backend function and factories

tools/dashboard-plugin-template/README.template.md, tools/dashboard-plugin-template/package.json, tools/plugin-toolkit/src/index.ts, tools/plugin-toolkit/src/updatePluginParamsCmd/actionConfig.ts, tools/plugin-toolkit/src/updatePluginParamsCmd/index.ts
=> RELATED: RAIL-4410 Add CLI command to update plugin params

libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts, libs/sdk-ui-ext/src/insightView/InsightView.tsx, libs/sdk-ui-geo/api/sdk-ui-geo.api.md, libs/sdk-ui-geo/src/core/MapboxTokenProvider.tsx, libs/sdk-ui-geo/src/index.ts
=> RAIL-4395 - Repair Mapbox token React provider to work with insight and dashboard

libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
=> Refresh cache if locale was changed

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
=> RELATED: RAIL-4494 Remove connecting attributes loading on dashboard init

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
- update AttributeFilter import to `/dist` (as some internals are imported from there), otherwise, React context is missing in components imported from `/dist`
JIRA: RAIL-4390
---
--- …
=> Update imports in DefaultDashboardAttributeFilter

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
We need to handle responses coming from the day picker library which are
incomplete in case of identical from/to date is selected.
JIRA: TNT-1074
---
--- …
=> RELATED: TNT-1074 Fix date filter range when from/to are identical

libs/api-client-bear/src/catalogue.ts, libs/sdk-backend-bear/tests/wiremock/recordings/mappings/gdc_internal_projects_l32xdyl4bjuzgf9kkqr2avl55gtuyjwf_catalog_items-5c5c1a69-2c2d-483f-aded-47bcd0e51e69.json, libs/sdk-ui-tests-e2e/recordings/mappings/mapping-attributeFilterConfig.spec.ts.json, libs/sdk-ui-tests-e2e/recordings/mappings/mapping-dashboard.spec.ts.json, libs/sdk-ui-tests-e2e/recordings/mappings/mapping-dashboardFiltering.spec.ts.json, tools/dashboard-plugin-tests/recordings/mappings/mapping-filterBar.spec.ts.json, tools/dashboard-plugin-tests/recordings/mappings/mapping-layout.spec.ts.json, tools/dashboard-plugin-tests/recordings/mappings/mapping-widgets.spec.ts.json
=> Increase catalog items page from 500 to 1000

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/test/RecipientsSelectRenderer.test.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterDefaultComponents.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/ElementsSelect/AttributeFilterElementsActions.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/ElementsSelect/AttributeFilterElementsSelect.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/types.ts, libs/sdk-ui-filters/src/AttributeFilter@next/Context/AttributeFilterComponentsContext.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/index.ts, libs/sdk-ui-filters/src/AttributeFilter@next/types.ts, libs/sdk-ui-filters/src/index.ts, libs/sdk-ui-filters/src/internal.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelect.tsx, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectAllCheckbox.tsx, libs/sdk-ui-kit/src/List/InvertableSelect/index.ts, libs/sdk-ui-kit/src/List/InvertableSelect/useInvertableSelect.ts, libs/sdk-ui-kit/src/List/index.ts, libs/sdk-ui-tests/stories/visual-regression/filters/AttributeFilter@next/AttributeFilterCustomizations/ElementsSelectActionsComponent.tsx
=> Make AllCheckbox in AttributeFilter customisable

.gitlab-ci.yml
=> NAS-4421: Fix ext-image updater

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/src/List/InvertableSelect/test/useInvertableSelect.test.ts, libs/sdk-ui-kit/src/List/InvertableSelect/useInvertableSelect.ts
=> Wrong icon of all checkbox when search and unselect elements

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/package.json, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/AttributeFilterDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/AttributeFilterDropdownBody.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/types.ts, libs/sdk-ui-filters/src/AttributeFilter@next/Components/Dropdown/useElementPositionChange.ts, libs/sdk-ui-filters/src/AttributeFilter@next/Components/ElementsSelect/AttributeFilterElementsSelect.tsx, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelect.tsx, libs/sdk-ui-kit/styles/scss/invertableSelect.scss
- Adapt attribute filter height according to viewport height
JIRA: RAIL-4499
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …
=> AttributeFilter - respect viewport height

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> RELATED: TNT-1085 Including applied filters should be disabled by default on tiger

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
=> RELATED: TNT-1083 Support exports for xlsx

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdownBody.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext.scss, libs/sdk-ui-kit/src/List/AsyncList.tsx, libs/sdk-ui-kit/styles/scss/dropdown.scss
- add missing imports from ui-kit
- fix async list "jumping" on resize
- minor code style imporovements
JIRA: RAIL-4522
---
--- …
=> Fix AttributeFilter CSS issues

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterBase.tsx
=> Enable telemetry for refactored AttributeFilter

libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
=> Sorting unstable Tiger date datasets

libs/sdk-backend-base/src/cachingBackend/index.ts
The element cache causes problem with some older versions of filters. Hence we need to allow the users to turn it of specifically.
JIRA: RAIL-4524
---
--- …
=> RELATED: RAIL-4524 Allow turning off elements cache only

libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdown.tsx
=> Height of dropdown body doesn't adapt with viewport

gdc_fossa.yaml
which included latest version of node/yarn
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reques …
=> DC-2428: Use dedicated fossa-scan image

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useFilterExpansionByDragAndDrop.tsx
expand filter zone for repeated dragging
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request- …
=> RELATED: JIRA: RAIL-4415 fix adding attribute filter when dropzone is on second line

libs/sdk-ui-kit/styles/scss/header.scss
=> BUGFIX: Update Upgrade Button to fit with text

libs/sdk-ui-kit/src/Header/Header.tsx
=> Fix bug that countdown is not shown correctly for the last day

.fossa.yml, common/scripts/ci/fossa_prescan.sh, gdc_fossa.yaml
=> RELATED: RAIL-4412 Provide FOSSA with correct install script

tools/dashboard-plugin-template/README.template.md, tools/dashboard-plugin-template/package.json, tools/plugin-toolkit/src/index.ts, tools/plugin-toolkit/src/removeParamsCmd/actionConfig.ts, tools/plugin-toolkit/src/removeParamsCmd/index.ts
=> RELATED: RAIL-4526 Remove plugin parameters via CLI

libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelectItem.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterElementsSelect.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> RELATED: RAIL-4276 Add styles for attribute filter empty list items

README.md
- combine identical links
- point to a specific page for Official documentation
JIRA: RAIL-4496
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master …
=> RELATED: RAIL-4496 Improve main README

common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4258-Changes_2022-10-18-12-00.json, common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4258-Changes_2022-10-18-12-01.json, common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4258-Changes_2022-10-18-12-02.json, common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4258-Changes_2022-10-18-12-03.json, common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4258-Changes_2022-10-18-12-04.json
=> Update CHANGELOG for release 8.11.0

README.md
This way there is no blue underline next to the badge on hover.
---
--- …
=> Inline badges markup in README.md

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
=> RELATED: RAIL-4552 Replace css classes for automatic tests

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> Introduce new APIs into Tiger to manage CSP directive

common/config/jest/jest.config.base.js
=> Increase jest test timeouts

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ZoomInsightConfiguration.tsx, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/AreaChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/BarChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bubbleChart/BubbleChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/BulletChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/ColumnChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/ComboChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/ComboChartDescriptorDeprecated.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/donutChart/DonutChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/funnelChart/FunnelChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/GeoPushpinChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/HeatmapDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/LineChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PieChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PivotTableDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/ScatterPlotDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/TreemapDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/XirrDescriptor.ts, libs/sdk-ui-ext/src/internal/components/tests/BaseVisualization.test.tsx, libs/sdk-ui-ext/src/internal/interfaces/VisualizationDescriptor.ts
replacement of https://github.com/gooddata/gooddata-ui-sdk/pull/2925
---
--- …
=> RELATED: RAIL-4456 Add zoomable interaction config

libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/HubspotConversionTouchPointDialogBase.tsx, libs/sdk-ui-kit/src/Messages/Messages.tsx, libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/formatTemplatesDropdown/DropdownItem.tsx
=> RELATED: FET-1141 Replace html with typography

libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/en-US.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> BUGFIX: RAIL-4543 Missing noConnection message

libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/IdentifierParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/InsightDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel.tsx
=> Improve drill settings

examples/sdk-examples/src/constants/routes.ts, examples/sdk-examples/src/examples/dashboardComponent/DrillToDashboard.tsx, examples/sdk-examples/src/examples/dashboardComponent/DrillToDashboardSrc.tsx, libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts
- Add example how to handle drill to dashboard
- Also add a note about `@alpha` stage of the drill events and commands
- Also ignore saga cancel error caused by the re-init triggered by a call from the event handlers
JIRA: RAIL-4550
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-sho …
=> RELATED:  RAIL-4550 Add example for drill to dashboard

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/test/ScheduledMailDialogRenderer.test.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmails.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/useScheduledEmailManagement.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
=> BUGFIX: TNT-1036 Schedule email handle different login/email use case

examples/sdk-examples/src/App.tsx, examples/sdk-examples/src/components/Header.tsx
=> WEB-3466 Learn nav for GD.UI

libs/sdk-ui-kit/styles/scss/header.scss
=> SD-2479 Update Upgrade Button to fit with text

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> LOB-348: Introduction of new FF enableLongitudeAndLatitudeLabels

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useFiltersWithAddedPlaceholder.tsx
=> Attribute values dropdown are not shown after attribute filter is added

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
This makes it consistent with dashboards and measures.
JIRA: RAIL-4605
---
--- …
=> RELATED: RAIL-4605 Use insight summary as description on tiger

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/validation/uniqueFiltersValidation.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useFiltersWithAddedPlaceholder.tsx
=> Avoid adding two Filters of different DF from one Attribute

libs/sdk-backend-tiger/src/backend/index.ts
=> Remove capabilities check for exports in sdk-backend-tiger

libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> FEATURE: TNT-1143 Add translations to release KD

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE MPNT-159, MPNT-169: Define feature flag enableMSSQLDataSource, Make UI SDK tiger client reflect the new MSSQL database types

libs/sdk-ui-dashboard/src/presentation/widget/kpi/CreatableKpi.tsx
=> Fix broken link

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
=> AttributeFilters dropdown alignment.

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
=> Fix AttributeFilters dropdown alignment.

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/kpi/GdcKpi.ts, libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts, libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts, libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/analyticalWidgets.ts, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts
=> Usage of MD object descriptions

libs/sdk-ui-dashboard/styles/scss/topBar.scss
=> Long title is not shorten in Mobile mode

examples/sdk-examples/src/components/Header.tsx
=> WEB-3466 Rename GD.UI to React SDK in breadcrumbs

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutItem.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/RenderModeAwareDashboardLayoutSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/RenderModeAwareDashboardLayoutSectionRenderer.tsx
- fix components used as function
- extract key getter functions
JIRA: RAIL-4169
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribut …
=> RELATED: RAIL-4169 Fix render function defaults

libs/sdk-ui-web-components/src/autoAuth.ts, libs/sdk-ui-web-components/src/index.ts
=> RELATED: JIRA-4606 Fix endless redirect loop when authentication fails

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/index.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/react/useToastMessages.tsx, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/ToastMessages.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/useExportHandler.ts, libs/sdk-ui-dashboard/src/types.ts
This enables us to show messages from sagas as well.
JIRA: RAIL-4556
---
--- …
=> RELATED: RAIL-4556 Move toast messages to redux

libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts, libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/ldm/attributeElement.ts, libs/sdk-ui-filters/src/AttributeFilter/utils.ts
=> RELATED: TNT-1107 Attribute filter formatting

libs/sdk-ui-web-components/src/autoAuth.ts
=> RELATED RAIL-4606 Updated error messages after the proofread

libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts
RSQL cannot handle prefixes, so we strip them for the RSQL filter and filter the result on client instead.
See 8d0ed453243a1ee2f74c65c9c985877a8b25fcd0 for a similar fix.
JIRA: RAIL-4618
---
--- …
=> RELATED: RAIL-4618 Fix getAttributeDisplayForm on tiger with prefixes

libs/sdk-ui-dashboard/styles/scss/filterBar.scss
=> Missing margin between filters in edit mode

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/user/GdcUser.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/DateFilter/index.ts, libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts, libs/sdk-ui-filters/src/index.ts
=> Use localised date formats in DateFilter

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/InsightDropdown.tsx, libs/sdk-ui-kit/src/ScrollablePanel/ScrollablePanel.tsx
=> BUGFIX:  RAIL-4614 improve scroll of widget configuration

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/src/ScrollablePanel/ScrollablePanel.tsx, libs/sdk-ui-kit/src/typings.d.ts, libs/sdk-ui-kit/src/utils/scroll.ts
=> BUGFIX: RAIL-4614 improve scroll of widget configuration

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> BUGFIX: RAIL-4634 Add missing FF for chart zooming

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useInsightListItemDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionInsightListItemDropHandler.ts
- fix adding first widget
- fix dropzone size for first widget
JIRA: RAIL-4639
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributin …
=> RELATED: RAIL-4639 Fix drop first widget to empty dashboard

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
JIRA: TNT-1165, TNT-1170
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-b …
=> RELATED: TNT-1165 fix date range configuration in global date filter

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx
=> RELATED: RAIL-4639 render initial texts on empty dashboard

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
When the user changes display form, the whole dropdown would close, because the whole component would remount.
Now we use the attribute as a key so the remount does not happen in this case anymore and hence the dropdown does not close.
JIRA: RAIL-4626
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …
=> RELATED: RAIL-4626 prevent attribute filter close

libs/sdk-ui-dashboard/styles/scss/export.scss
=> BUGFIX: TNT-1169 Fix export widget height

libs/sdk-ui-dashboard/styles/scss/kpi.scss
KPI should be drillable in edit mode as well, so we explicitly enable the pointer events.
JIRA: RAIL-4579
---
--- …
=> RELATED: RAIL-4579 fix KPI drill in edit mode

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1181 Set enableDateFormats FF to true by default

libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/AttributeUrlSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/AttributeUrlSectionItem.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/InsightParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx
=> RELATED: RAIL-4636 show attribute with link display form in drill url config

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useBeforeDrag.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDrag.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpiPlaceholder/DefaultDashboardKpiPlaceholderWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpiPlaceholder/KpiPlaceholderConfigurationPanel.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/index.ts, libs/sdk-ui-kit/src/utils/drag.ts
=> RELATED: RAIL-4656 close all open overlays and remove placeholders from layout when DnD start

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Bubble/Bubble.tsx
=> FEATURE: TNT-1129 Enable key presses handling on Bubble

libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/kpi.scss, libs/sdk-ui-dashboard/styles/scss/kpi_alert_dialog.scss, libs/sdk-ui-dashboard/styles/scss/resizing.scss, libs/sdk-ui-pivot/src/CorePivotTable.tsx
=> RELATED: RAIL-4652 Allow interaction with table or chart legend in edit mode

libs/sdk-ui/src/base/localization/bundles/ja-JP.json
=> FEATURE: TNT-1193 JP translation fix - sorting by

libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useIsDraggingWidget.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutItemRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableDashboardLayoutSectionRenderer.tsx, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/resizing.scss
- hide source section if has only one (dragged) item
- remove adjacent section checking (case is covered by hiding sections)
JIRA: RAIL-4660
---
--- …
=> RELATED: RAIL-4655, RAIL-4660 rework how section work when dragging

libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiDescriptionTrigger.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss
=> BUGFIX: TNT-1173 UI description tooltip for KPI

libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useAttributesWithDisplayForms.ts
- RAIL-4680 - show all labels in the custom URL editor
- RAIL-4681 - hide custom URL editor help link if white labeled 
---
--- …
=> RELATED: RAIL-4680, RAIL-4681 drill to URL fixes

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: TNT-687 Remove `enableAdFloatingDateRangeFilter`

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
Remove noop attribute filters in edit mode as they would cause a useless query when a new filter (noop by default) is added. Keep them in view mode so that switching to and from All on an ignored filter does not show loading.
This is a tradeoff so that we optimize for the view mode performance and also keep the more frequent use case in edit mode (adding a new filter) loading-free as well. Switching to and from All in edit mode will still show loading, but have no way of telling whether a noop filter is noop because it was just added or because it was set that way by the user.
JIRA: RAIL-4624
---
| …
=> RELATED: RAIL-4624 prevent widget loads in view mode

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/CreationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightList.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListCore.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListItemWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/InsightListItem.tsx, libs/sdk-ui-kit/styles/scss/insightList.scss
Add description tooltip to Insight List
Provide its prop from Dashboard component
BUGFIX: TNT-1228 Dont show placeholder in disabled text area
JIRA: TNT-1136, TNT-1228
---
--- …
=> FEATURE: TNT-1136 Add description tooltip to insight list

libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx, libs/sdk-ui-kit/styles/scss/descriptionPanel.scss
=> BUGFIX: TNT-1173 Description tooltip mobile view overflow

libs/sdk-ui-dashboard/src/presentation/constants/zIndex.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Overlay/OverlayController.tsx, libs/sdk-ui-vis-commons/src/legend/PopUpLegend/RowLegend.tsx
- set dahboard header z-index
- set OverlayController instanace for eache provider
JIRA: RAIL-4617
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/mas …
=> RELATED: RAIL-4617 z-indexes of Dashboard and Dashboard Header

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts
=> RELATED: TNT-1012 Add backend capability for non production datasets support

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/description/DescriptionClickTrigger.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/InsightDropdown.tsx
=> BUGFIX: TNT-1242 Drill insight list UI issues

libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardList.tsx
=> RELATED: RAIL-4712 sort dashboards in drill to dashboard

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Bubble/BubbleTrigger.tsx, libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx, libs/sdk-ui-kit/src/List/InsightListItem.tsx
=> FEATURE: TNT-1140 BubbleTrigger open & close actions

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatusIndicator.tsx
=> FEATURE: TNT-1185 Remove shared status from top bar in dashboards

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayer.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx
JIRA: RAIL-4705, RAIL-4707
---
--- …
=> RELATED: RAIL-4705, RAIL-4707 z-index of drag layer and CustomUrlEditor

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: TNT-1246 New FF for hiding description edit in AD

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialog.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeContent.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranteeItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranteeList.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularGranteeGroupItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularGranteeUserItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissions.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionsDropdownBody.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeContent.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/types.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useShareDialogBase.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/utils.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/index.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/shareDialogMappers.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/__snapshots__/shareDialogMappers.test.ts.snap, libs/sdk-ui-kit/styles/scss/shareDialog.scss, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/GranteeMock.ts, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> FEATURE: TNT-1185 Panther granular permissions

libs/sdk-ui-kit/src/Header/Header.tsx, libs/sdk-ui-kit/styles/scss/header.scss
feat: display the Upgrade button and Expiration date on Mobile
_ Support responsive for the Upgrade button and Expiration date
JIRA: SD-2529
---
--- …
=> FEATURE: SD-2529 - The Upgrade button should display on the mobile screen

libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/ad.ts
=> RELATED: TNT-1214 Introduce AD postMessage command and event for API token injection

libs/sdk-ui/src/execution/Execute.tsx
Reload execution also on workspace prop change.
JIRA: RAIL-4721
---
--- …
=> BUGFIX: RAIL-4721 Execute refetching

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: MPNT-192 Clean up FF enableMSSQLDataSource

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DragLayerPreview/WidthResizerDragPreview.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/Resize/WidthResizerHotspot.tsx, libs/sdk-ui-dashboard/styles/scss/resizing.scss
=> RELATED: RAIL-4708 widget width resizing

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useFilterBarState.ts
=> RELATED: JIRA-4706  can not add attribute filter when Dashboard is scrolled down.

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx, libs/sdk-ui-kit/src/Overlay/OverlayController.tsx
=> RELATED: RAIL-4723 fix calculation of max Z-Index in OverlayController

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardMainContent.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDragScroll.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useInterval.ts, libs/sdk-ui-dashboard/styles/scss/dashboard.scss
feat: scroll layout when dragging
JIRA: RAIL-4677
---
--- …
=> RELATED: RAIL-4677 scroll when dragging

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescriptionConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiConfigurationPanelCore.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiDescriptionConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiMetricDropdown/MetricDropdown.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
- fix closing overlays in KPI panel
- fix closing overlays in Widget panel
- fix adding interactions to bottom
JIRA: RAIL-4650
---
--- …
=> RELATED: RAIL-4650 closing overlays and fix scroll in widget and KPI config

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx, libs/sdk-ui-kit/src/List/InsightListItem.tsx
If there are actions in list item move tooltip to the right to not hide actions icon
JIRA: TNT-1251
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/ma …
=> BUGFIX: TNT-1251 Move tooltip to avoid hiding elements

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/Resize/HeightResizerHotspot.tsx
=> RELATED: RAIL-4731 Custom widgets and height resize

libs/sdk-embedding/src/internal/filterConvertors.ts, libs/sdk-embedding/src/internal/tests/filterConvertors.test.ts
=> RELATED: TNT-1260 Support validation for date filter from/to with time values

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: SD-2533 - Remove FF enableDataSourceManagement

libs/sdk-ui-dashboard/src/model/store/alerts/alertsSelectors.ts
We must not blow up when a related widget is missing in the layout: it can happen during edit mode interactions as we do not remove alerts from the store. This makes cancelling the edit mode faster as the alerts do not need to be loaded from the backend again.
Alternative would be to create a "persisted alerts" store in redux and use it to back up the alerts. This is, however, so much work for such an edge-case that I opted for this simpler solution instead.
JIRA: RAIL-4760
---
| `extended check …
=> RELATED: RAIL-4760 make alert selector more tolerant

libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx
In some cases, when you click the save button
(for example immediately after you insert an insight) and the dashboard is still processing some requests related to this insight, it can take few seconds,
before the CMD.SAVE starts to process
(as dashboard can process only 1 command at a time). We want to show the loading indicator immediately and avoid any double-save race conditions, so add a local state for this case.
JIRA: RAIL-4720
---
| …
=> BUGFIX: RAIL-4720 Save button behaviour

libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrills.ts
KPI drills should never be automatically removed like insight drills are
JIRA: RAIL-4748
---
--- …
=> RELATED: RAIL-4748 fix KPI drill validation

common/scripts/ci/run_cypress_tests.sh
=> RELATED: QA-17807 remove unused script file

libs/sdk-ui-dashboard/src/model/store/_infra/undoEnhancer.ts
Since immer 9.0.13, the undoEnhancer breaks when the app is built with react-scripts because the state parameter coming into the withUndo is not a proper immer draft and thus the original() returns undefined. In that case we now try to unwrap it from the proxy in an immer-independent way to prevent null references down the road.
JIRA: RAIL-4751
---
---
-   [ ] commit messages adhere to …
=> RELATED: RAIL-4751 prevent null references in undoEnhancer

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts
=> RELATED: RAIL-4761 Dashboard is block after cancelling

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/common/settings.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> FEATURE: TNT-1154 Mapbox token support

libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts, libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
JIRA: RAIL-4763, RAIL-4759
---
--- …
=> RELATED: RAIL-4763, RAIL-4759 custom widget height resizing improvements

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts
=> FEATURE: TNT-1268 Add show all attribute values backend capability

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: TNT-1265 Remove enableTheming FF

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/displayForms/AttributeDisplayFormsDropdown.tsx
JIRA: RAIL-4782
---
| Command                    | Description             |
| -------------------------- | ----------------------- |
| `ok to test`               | Re-run standard checks  |
| `extended test - backstop` | BackstopJS tests        |
| `extended check sonar`     | SonarQube tests         |
| `extended check cypress`   | Cypress E2E tests       |
| `extended check plugins`   | Dashboard plugins tests |
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appro …
=> RELATED: RAIL-4782 fix ref matching in filter config

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/InsightDrillConfigPanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts
=> RELATED: RAIL-4783 unhandled ex when interactions shown before vis loading ends

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-backend-base/src/decoratedBackend/elements.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/workspace/attributes/elements/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/elements.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/cancelation/index.ts, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/attributes/elements/index.ts, libs/sdk-backend-spi/tsconfig.json, libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts, libs/sdk-backend-tiger/src/cancelation/index.ts, libs/sdk-ui-filters/package.json, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/loadElements.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/loadElementsFromBackend.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts
Implementation of general cancellation, now without native support of AbortController (need polyfill). There is an interface that allows set cancel signal and also options type to sending signal into request.
Using this approach in filters module.
JIRA: RAIL-4733
---
| `extended check plugins` …
=> BUGFIX: RAIL-4733 cancel collectLabelElements queries

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
=> FEATURE: TNT-1269 Remove enableDateFormats FF

tools/dashboard-plugin-template/src/harness/PluginToolbar.tsx
=> RELATED: RAIL-4725 Hide overlays button still shows in view mode in Harness

libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts, libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts, libs/sdk-backend-tiger/src/backend/workspace/insights/mocks/visualizationClasses.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/LabelTypeConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts, libs/sdk-backend-tiger/src/convertors/tests/LabelTypeConverter.test.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/ldm/metadata/attributeDisplayForm/index.ts, libs/sdk-model/src/ldm/metadata/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/InsightParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/AttributeDisplayFormParameterDetail.tsx, libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/displayForms/AttributeDisplayFormDropDownItem.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/displayFormDropdown/DisplayFormItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useAttributesWithDisplayForms.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/GeoPushpinChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/geoConfigCodeGenerator.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/__snapshots__/PluggableGeoPushpinChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/index.ts, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/insightToPropsConverter/convenience.ts, libs/sdk-ui-filters/src/AttributeFilter/Components/Addons/AttributeDisplayFormSelect/AttributeDisplayFormSelectItem.tsx
=> FEATURE: TNT-1152 PV GeoChart supports Tiger

libs/sdk-ui-kit/styles/scss/header.scss
=> BUGFIX: TNT-1266 Hamburger menu z-index

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetPicker.tsx
=> RELATED: RAIL-4710 wrong size of Date dimension picker

.github/CODEOWNERS
Remove Dan Homola and Lubomír Slivka from it.
---
| **E2E …
=> TRIVIAL: update CODEOWNERS

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/utils.ts
=> FEATURE: TNT-1185 Propagate dashboard share status

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: TNT-1289 Introduce `enableKPIAttributeFilterRenaming` feature flag

libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts
=> RELATED: RAIL-4792 add better error message when loading plugin failed

libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
Legend is visible even if Segment By attribute is on first index in execution
JIRA: TNT-1301
--- …
=> BUGFIX: TNT-1301 Handle Segment attribute on first index

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/utils.ts
=> FEATURE: TNT-1185 obtain share status of newly created dashboards on tiger

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/store/entitlements/entitlementsSelectors.ts
=> RELATED: TNT-1315 Initialize entitlements state for new dashboard

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/changeSharingHandler.ts
- switch order of requests for updating the dashboard and changing user access
- use changed shared status from BE for further event operations
JIRA: TNT-1185
--- …
=> FEATURE: TNT-1185 Propagate correct share status to events

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightEditMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useEditableInsightMenu.ts
Interactions menu item should be visible
only in some cases:
- some drilling is enabled and chart has available drill targets
- zoom is enabled and chart is zoomable
JIRA: TNT-1303
---
| `extended check plugins`                              | Dashboard plugins tests …
=> BUGFIX: TNT-1303 Hide Interactions when not needed

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
Fallback to default filters in case export metadata is missing or its retrieval fails. Also prevent failure when returned export metadata is returned as an emtpy object.
---
| …
=> RELATED: TNT-1317 Show default filters when export metadata is missing

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/utils.ts
=> BUGFIX: TNT-1185 Fix granular grantees sorting

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeContent.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularGranteeUserItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/AddGranteeSelect.test.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/utils.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useShareDialogBase.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/utils.ts
- do not show email when it is the same as name
- add missing hook dependencies
- fix dirty dialog logic
- fix duplicated grantees to add
JIRA: TNT-1185
--- …
=> BUGFIX: TNT-1185 Granular permissions behaviour

libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx
Other errors then invalid mapbox token
are propagated to upper components
JIRA: TNT-1321
--- …
=> BUGFIX: TNT-1321 Propagate other errors up

libs/sdk-ui-dashboard/src/_staging/dashboard/fluidLayout/facade/layout.ts, libs/sdk-ui-dashboard/src/_staging/layout/constants.ts, libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts, libs/sdk-ui-dashboard/src/_staging/layout/test/__snapshots__/sizing.test.ts.snap, libs/sdk-ui-dashboard/src/_staging/layout/test/sizing.test.ts, libs/sdk-ui-dashboard/src/presentation/constants/layout.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/Resize/HeightResizerHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/WidgetDropZoneColumn.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDrag.ts, libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/index.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/interfaces.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/sizing.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/__snapshots__/sizing.test.ts.snap, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/sizing.test.ts
- remove row wrappers in edit mode
- split DashboardLayoutGridRow components for view and edit mode
- rework height resizer rendering and  height calculation
- fix useDashboardDrag collected props type
JIRA: RAIL-4678
---
| `extended check plugins`                              | Dashboard plugins …
=> RELATED: RAIL-4678 fix dropzone placement

libs/sdk-ui-tests-e2e/README.md
=> RELATED: QA-17807 update readme for run local uisdk isolated

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts, libs/sdk-backend-tiger/src/types/index.ts
Adapt implementation of the workspace settings in SDK to reflect changes introduced by
https://gooddata.atlassian.net/browse/NAS-4638 (adding type).
JIRA: RAIL-4809
---
| `extended …
=> FEATURE: RAIL-4809 adapt to changes in workspace settings

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiConfigurationPanelCore.tsx
fix: respect FF hideKpiDrillInEmbedded in KPI configuration
JIRA: RAIL-4807
--- …
=> RELATED: RAIL-4807 Respect FF hideKpiDrillInEmbedded in KPI configuration

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/changeSharingHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/changeSharingHandler.test.ts
=> FEATURE: TNT-1284 update dashboard permissions from backend after permissions change

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/index.ts, libs/sdk-backend-tiger/src/types/index.ts
- add new method scanSql into tigerSpecificFunctions.ts
JIRA: LOB-507
--- …
=> FEATURE: LOB-507 generate new version to support scanSql api

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/styles/scss/export.scss
This reverts commit 08478b0bf8dfba4ee2104b7471870d768f207a07.
Having display:flex leads to incorrectly printed tables in the resulting
pdf file.
JIRA: TNT-1335
---
| `extended test …
=> RELATED: TNT-1335 Revert previous kpi height in pdf exports fix

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1327 Remove ff enableAttributeAllValues

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightInteractions.tsx
=> FEATURE: RAIL-4818 drill to Dashboard selector is under Filter bar

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
- Changes of widget are not applied immediately
- Date config of widget is not preserved after editing insight
JIRA: RAIL-4820, RAIL-4821
--- …
=> BUGFIX: RAIL-4820, RAIL-4821 filtering bugs repair

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
=> RELATED: RAIL-4829 set dashboardEditModeDevRollout default to TRUE

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1142 Enable descriptions by default

common/scripts/ci/run_cypress_integrated_tests.sh
=> RELATED: TNT-1285 Add entrypoint script for integrated tests

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/types/index.ts
=> FEATURE: LOB-507 Generate new gooddata-ui-sdk version to support new API support SQL-base

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: LOB-520 introduce new feature flag enableSqlDatasets

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/permissionsLogic.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/test/permissionsLogic.test.ts
Don't update dashboard on Tiger when only share status chnged.
JIRA: TNT-1284
--- …
=> FEATURE: TNT-1284 Allow removing direct dashboard permissions when there are indirect ones

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/types/index.ts
=> RELATED: TNT-1185 Regenerate tiger api client

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightInteractions.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiConfigurationPanelCore.tsx
=> FEATURE: TNT-1142 Add cypress selectors for scrolling

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1156 enablePushpinGeoChart default true

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/changeSharingHandler.ts
=> FEATURE: TNT-1284 Handle changing share status with dashboard permissions

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/DefaultShareDialog.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/types.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialog.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AdminInformationMessage.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/useShareDialogBase.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/types.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useAdminInformationMessage.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/shareDialogMappers.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/__snapshots__/shareDialogMappers.test.ts.snap, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/testHelpers.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/types.ts, libs/sdk-ui-kit/styles/scss/shareDialog.scss, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/ShareDialog.tsx, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/ShareGranteeBase.tsx, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> FEATURE: TNT-1234 Share dialog admin message

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/events/base.ts, libs/sdk-ui-dashboard/src/model/events/index.ts, libs/sdk-ui-dashboard/src/model/events/lab.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/InsightListNoData.tsx, libs/sdk-ui-dashboard/src/presentation/insightList/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
feat: add create insight button to empty insight list
JIRA: RAIL-4834
--- …
=> RELATED: RAIL-4834 Missing "Create insight" link when wokspace has no any insight

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
=> RELATED: TNT-1307 Switch export pdf feature flag to true by default

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: LOB-510 enable Pushpin Geo Chart feature by default

libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts
=> RELATED: RAIL-4802 fix widget reducer identification by ref

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/DefaultShareDialog.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/types.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialog.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeContent.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/backend/loadGranteeOptionsPromise.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/backend/useGetAccessList.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/AddGranteeSelect.test.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/GranteeMock.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/useShareDialogBase.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/types.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useShareDialogBase.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/shareDialogMappers.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/shareDialogMappers.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/testHelpers.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/types.ts, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/AddGranteeBase.tsx, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/GranteeMock.ts, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/ShareDialog.tsx, libs/sdk-ui-tests/stories/visual-regression/kit/ShareDialog/ShareGranteeBase.tsx
=> FEATURE: TNT-1188 Propagate current user to share dialog

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/events/dashboard.ts, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/DefaultShareDialog.tsx, libs/sdk-ui-dashboard/src/presentation/shareDialog/types.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialog.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ComponentInteractionContext.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranteeItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularGranteeGroupItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularGranteeUserItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionItem.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionsDropdown.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionsDropdownBody.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/backend/loadGranteeOptionsPromise.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/utils.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useShareDialogBase.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/utils.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/index.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/shareDialogMappers.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/testHelpers.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/types.ts
=> FEATURE: TNT-1188 Share dialog interactions

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> RELATED: TNT-1189 Update localisations

common/scripts/ci/run_cypress_integrated_tests.sh, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/insightOnDashboard.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/permissions.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/02-sdk-ui-filters/dateFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/api.ts, libs/sdk-ui-tests-e2e/cypress/tools/dashboards.ts, libs/sdk-ui-tests-e2e/cypress/tools/permissions.ts, libs/sdk-ui-tests-e2e/cypress/tools/shareDialog.ts, libs/sdk-ui-tests-e2e/cypress/tools/users.ts, libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/nginx/nginx.conf, libs/sdk-ui-tests-e2e/nginx/templates/proxy-integrated-tests.conf.template, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardScenarioTigerPermissions.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx, libs/sdk-ui-tests-e2e/scenarios/webpack.config.cjs, libs/sdk-ui-tests-e2e/scripts/run_integrated.js, libs/sdk-ui-tests-e2e/scripts/run_integrated.sh
For now it supports only tiger integrated tests.
Stop baking api token to the built scenarios to be able to switch users in integrated tests.
--- …
=> RELATED: TNT-1285 Infrastructure for integrated tests & permissions tests

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardScenarioTigerPermissions.tsx
=> FEATURE: TNT-1366 Set enableAnalyticalDashboardPermissions to true

libs/sdk-ui-tests-e2e/README.md
=> TRIVIAL: QA-17908 Add dynamic import example to README.md

libs/sdk-ui-tests-e2e/cypress/integration/02-sdk-ui-filters/attributeFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/attributeFilter.ts, libs/sdk-ui-tests-e2e/cypress/tools/attributeFilterButton.ts, libs/sdk-ui-tests-e2e/cypress/tools/attributeFilterParentChild.ts, libs/sdk-ui-tests-e2e/recordings/mappings/BEAR/mapping-attributeFilter.spec.ts.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Filters/AttributeFilterParentChildExampleScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> BUGFIX: RAIL-4832 dependent filter isn't refreshed to original state tests

libs/sdk-ui-tests-e2e/README.md, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/permissions.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/dashboards.ts, libs/sdk-ui-tests-e2e/cypress/tools/permissions.ts, libs/sdk-ui-tests-e2e/cypress/tools/shareDialog.ts, libs/sdk-ui-tests-e2e/cypress/tools/utils.ts, libs/sdk-ui-tests-e2e/scripts/run_integrated.js
=> RELATED: TNT-1285 Add more integrated test-cases for permissions

common/config/rush/pnpm-lock.yaml
=> RELATED: FET-1198 fix vulnerabilities

libs/sdk-ui-tests-e2e/cypress/tools/shareDialog.ts
=> RELATED: TNT-1285 Integrated tests: robust check for missing item

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/permissions.spec.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardScenarioTigerPermissions.tsx
=> RELATED: TNT-1375 Use specific ff for activating permissions in tests

libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml
=> FEATURE: QA-17192 Add NO-COLOR to integrated checklist

libs/sdk-ui-dashboard/src/_staging/sharedHooks/useAttributes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/utils.ts
=> RELATED: RAIL-4600 Merge rc to master

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
=> RELATED: JIRA-4600 change initialRenderMode of dashbaord tag to public

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDisplayFormConfiguration.ts
=> BUGFIX: TNT-1350 Obtain attr filter display forms if not available on catalog

common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-12-54.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-12-56.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-12-57.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-12-58.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-12-59.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-13-00.json, common/changes/@gooddata/sdk-ui-all/rc_2023-03-03-13-01.json
=> RELATED: JIRA-4600 add release notes

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
=> BUGFIX: TNT-1390 Dont reload attr after DF change

.github/pull_request_template.md, common/scripts/ci/run_cypress_integrated_tests.sh, libs/sdk-ui-tests-e2e/README.md, libs/sdk-ui-tests-e2e/cypress.config.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardDateRelated.spec.ts, libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/nginx/templates/proxy-integrated-tests.conf.template
=> RELATED: QA-17366 support bear BE in cypress integrated tests

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
=> RELATED: TNT-1390 revert fix from RC

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
=> BUGFIX: TNT-1390 Dont close filter dropdown after changing display form

libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/kd.ts
=> FEATURE: TNT-1214 Post message types for token injection to dashboards application

common/changes/@gooddata/sdk-ui-all/nen-tnt-1291-change-log_2023-03-08-10-28.json
=> RELATED: TNT-1291  Add documentation change log

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useTitleConfiguration.ts
=> BUGFIX: TNT-1394 remove blank spaces

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useOriginalConfigurationState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersList.tsx
=> BUGFIX: TNT-1418 Display correct attr title on `Filter By`

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts
=> BUGFIX: TNT-1419 Share button after saving new dashboard

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-charts/src/highcharts/adapter/plugins/dataLabelsColors.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/drilldownEventing.ts, libs/sdk-ui-ext/package.json, libs/sdk-ui-ext/src/internal/components/configurationControls/colors/coloredItemsList/ColoredItemsList.tsx, libs/sdk-ui-filters/package.json, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-geo/package.json, libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/drilling.ts, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/src/Overlay/Overlay.tsx, libs/sdk-ui-kit/src/utils/drag.ts, libs/sdk-ui-kit/src/utils/scroll.ts, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests-e2e/scenarios/src/index.tsx, libs/sdk-ui/package.json, libs/sdk-ui/src/base/vis/drilling.ts, libs/sdk-ui/src/index.ts, libs/sdk-ui/src/polyfills.ts
=> RELATED: FET-772 Remove IE-specific polyfills, upgrade blocked dependencies

libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx
=> BUGFIX: FET-1054 Fix dropdown dependency array

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDropdown.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/ScrollablePanel/ScrollableItem.tsx
=> RELATED: RAIL-4840 datePicker opening first time

libs/sdk-ui-kit/src/syntaxHighlightingInput/SyntaxHighlightingInput.tsx
=> BUGFIX: FET-1054 Fix codemirror dependency array

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/filter/index.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/tests/changeFilterContextSelectionHandler.test.ts, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
Handle casting values into SSF via
drilling into dashboard.
JIRA: TNT-1409
--- …
=> FEATURE: TNT-1409 Single select filter with drilling

common/config/rush/pnpm-lock.yaml
=> RELATED: FET-772 fix pnpm-lock file remove @formatjs/intl-pluralrules

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardKPI.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
=> BUGFIX: QA-18367 Fix unstable Drilling and DashboardKPI tests

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts
=> TRIVIAL: Fix unstable drilling test

libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/tests/__snapshots__/changeRenderModeHandler.test.ts.snap
=> RELATED: JIRA-4872 serialised event in changeRenderModeHandler

libs/sdk-ui-dashboard/src/model/react/useWidgetExecutionsHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/resultUtils.ts
=> RELATED: RAIL-4871 turning off a KPI Date filter on a dashboard

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
=> FEATURE: RAIL-4836 Api call for check entities override

libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/utils.ts
fix: default state for Embed Insight Dialog
JIRA: SD-2643
--- …
=> BUGFIX: SD-2643 - update the default state for the Embed Insight Dialog

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/dashboard.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts
- Add `createdBy` to save dashboard context.
JIRA: TNT-1419
--- …
=> BUGFIX: TNT-1419 Add `createdBy` on dashboard save

libs/sdk-ui-web-components/webpack.config.js
=> RELATED: RAIL-4778 Web Components reported version

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspace/insights/mocks/visualizationClasses.ts, libs/sdk-ui-kit/styles/images/visualization-types/funnel-active.svg, libs/sdk-ui-kit/styles/images/visualization-types/funnel.svg, libs/sdk-ui-kit/styles/images/visualization-types/pyramid-active.svg, libs/sdk-ui-kit/styles/images/visualization-types/pyramid.svg, libs/sdk-ui-kit/styles/scss/insightList.scss
Add feature flags and icons and visualization classes for Funnel/Pyramid chart.
This is related to https://github.com/gooddata/gooddata-ui-sdk/pull/3588 but not blocked by that pull-request as
we are still keeping these feature flags and their defaults to `false`.
--- …
=> RELATED: TNT-1431 Funnel/Pyramid: visualization classes and feature flags

libs/sdk-embedding/src/internal/filterConvertors.ts, libs/sdk-embedding/src/internal/tests/filterConvertors.test.ts
Empty SSF is valid use case
JIRA: TNT-1410
---
| …
=> FEATURE: TNT-1410 Allow None SSF in Post Messages

libs/sdk-ui-tests-e2e/cypress/support/isolatedTest.ts
=> BUGFIX: QA-18575 Fix record isolated test failed

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersList.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/selectionMode/SelectionMode.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/selectionMode/SelectionModeButton.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/selectionMode/SelectionModeItem.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/singleSelectionFilters.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
=> FEATURE: TNT-1450 Selection mode config design changes

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json
=> BUGFIX: QA-18622 Cannot put layout workspace while running checklist on UI-SDK 

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/types/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: LOB-567 introduce enableCompositeGrain feature flag

libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/EmbedInsightDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/components/CodeOptions.tsx, libs/sdk-ui-kit/src/Dialog/EmbedInsightDialog/EmbedInsightDialogBase/components/EmbedInsightContent.tsx
fix: toggle switch buttons have wrong interactions
JIRA: SD-2666
--- …
=> BUGFIX: SD-2664 - toggle switch buttons have wrong interactions

libs/sdk-ui-tests-e2e/scripts/run_integrated.sh, libs/sdk-ui-tests-e2e/scripts/run_isolated.sh
=> BUGFIX: QA-18543 Hidden some variables value

.gitlab-ci.yml, libs/sdk-ui-web-components/Dockerfile
Dependency proxy saves valuable DockerHub rate limits by working
as transparent, pull-through container image cache.
--- …
=> CONFIG: NAS-4878: Use Gitlab dependency proxy for building web-components

libs/sdk-ui-ext/src/internal/components/configurationControls/DataLabelsControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/tests/DataLabelsControl.test.tsx
=> BUGFIX: EGL-14 - show tooltip when hover on the disabled total labels control

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/scheduledMailRecipients.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/test/__snapshots__/scheduledMailRecipients.test.ts.snap, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/test/scheduledMailRecipients.test.ts
=> FEATURE: EGL-2 Pasting list of email addresses in scheduling dialogue is poorly handled

libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/settings/index.ts, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts, libs/sdk-backend-tiger/src/types/index.ts
=> BUGFIX: RAIL-4904 repair settings keys from tiger backend

libs/sdk-ui-tests-e2e/scripts/run_integrated.sh, libs/sdk-ui-tests-e2e/scripts/run_isolated.sh
=> BUGFIX: QA-18727 export parameters when run cypress test

libs/sdk-ui-tests-e2e/scripts/run_integrated.sh, libs/sdk-ui-tests-e2e/scripts/run_isolated.sh
=> BUGFIX: QA-18727 hidden params value when run test

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/SingleSelectionAttributeFilterElementsSelectItem.tsx, libs/sdk-ui-kit/styles/scss/list.scss
=> RELATED: TNT-1414 Single selection filter default ff true

tools/dashboard-plugin-template/webpack.config.js
Node API is no longer supported with webpack > 5.
JIRA: RAIL-4927
--- …
=> BUGFIX: RAIL-4927 add fallback for util

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> BUGFIX: TNT-1475 Enable filter renaming for AIO

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
feat: add feature flags for sankey/dependency wheel/waterfall charts
JIRA: EGL-16
--- …
=> FEATURE: EGL-16 Add feature flags for Sankey, Dependency Wheel and Waterfall charts

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts
=> FEATURE: RAIL-4886 add prefix on workspace descriptor

tools/app-toolkit/src/initCmd/index.ts, tools/app-toolkit/src/initCmd/replaceInFiles.ts, tools/react-app-template/src/App.tsx
* Specified a correct extension for the App.*x file depending on selected language.
* Changed the ID of the default chart shown.
--- …
=> RELATED: RAIL-4901 Specified a correct extension for the App.*x file

libs/sdk-ui-tests-e2e/reference_workspace/lib/export_tiger_workspace_fixture.js
=> BUGFIX: FET-1212 Use proper function to get diff

libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json
=> RELATED: TNT-1432 Remove missing username from tiger fixture

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> RELATED: TNT-1157 Detach geo chart and permissions FFs from FeatureHub for Tiger

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/src/presentation/dashboard/components/useDrillValidationMessages.tsx, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx, libs/sdk-ui-kit/package.json, libs/sdk-ui-loaders/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests/package.json, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui-web-components/package.json, libs/sdk-ui/package.json, skel/sdk-skel-tsx/package.json, tools/dashboard-plugin-template/package.json
=> RELATED: FET-1064 upgrade react-intl to ^6.0.0

libs/sdk-ui-ext/src/internal/utils/sort.ts
=> RELATED: TNT-1497 Use correct default sort for funnel/pyramid

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardAttributeFilterRenaming.tsx
=> RELATED: TNT-1294 Remove attribute filter renaming FF

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
=> RELATED: RAIL-4857 fix updating dashboard tags on Panther/Tiger

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
=> BUGFIX: EGL-28 avoid npe when no data returned

libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> FEATURE: TNT-1460 Enable drill from attribute for panther

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useSelectionModeConfiguration.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/SingleSelectFilterIntegration.tsx
=> RELATED: TNT-1415 Remove single select filter FF

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/highChartsCreators.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartLimits.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/sankeyChart/sankeyChartOptions.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/sankeyChart/tests/sankeyChartOptions.test.ts, libs/sdk-ui-charts/src/highcharts/constants/limits.ts, libs/sdk-ui-charts/src/interfaces/chartConfig.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/dependencyWheelChart/DependencyWheelChartDescriptor.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/sankeyChart/SankeyChartDescriptor.tsx, libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap
=> FEATURE: EGL-40 - sankey/dependency wheel charts limit

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardTigerWithCharts.spec.ts
=> BUGFIX: TNT-1515 Revert FF connection to the hub

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: TNT-1512 introduce `enableTableTotalRows` feature flag

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/organization/styling.ts, libs/sdk-backend-tiger/src/backend/settings/settings.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
=> BUGFIX: TNT-1442 Theming and color palette ids for tiger

libs/sdk-ui-kit/src/Icon/Icon.tsx, libs/sdk-ui-kit/src/Icon/InsightIcon.tsx, libs/sdk-ui-kit/src/Icon/icons/InsightIcons/Funnel.tsx, libs/sdk-ui-kit/src/Icon/icons/InsightIcons/Pyramid.tsx
=> RELATED: TNT-1518 Add missing icons for funnel/pyramid

libs/sdk-ui-web-components/src/tests/context.test.ts
=> BUGFIX: EGL-45 - dummy change to work around release new version of web component

.gitlab-ci.yml
=> RELATED: EGL-45 Fix web components release after migration to workspace:*

libs/sdk-ui-kit/src/Icon/icons/InsightIcons/Funnel.tsx, libs/sdk-ui-kit/src/Icon/icons/InsightIcons/Pyramid.tsx, libs/sdk-ui-kit/styles/images/visualization-types/funnel-active.svg, libs/sdk-ui-kit/styles/images/visualization-types/funnel.svg, libs/sdk-ui-kit/styles/images/visualization-types/pyramid-active.svg, libs/sdk-ui-kit/styles/images/visualization-types/pyramid.svg
=> RELATED: TNT-1518 Use icons with correct size/padding

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/DefaultButtonBar.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/types.ts
=> RELATED: FET-1069 Add ButtonBar children prop

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx, libs/sdk-ui-filters/src/DateFilter/index.ts, libs/sdk-ui-filters/src/DateFilter/interfaces/index.ts, libs/sdk-ui-filters/src/index.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx, libs/sdk-ui-kit/src/Datepicker/index.ts
=> FEATURE: CAL-863, CAL-866 Add custom week start to date picker

libs/api-client-tiger/api/api-client-tiger.api.md, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx, libs/sdk-ui-filters/src/DateFilter/index.ts, libs/sdk-ui-filters/src/DateFilter/interfaces/index.ts, libs/sdk-ui-filters/src/index.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx, libs/sdk-ui-kit/src/Datepicker/index.ts
=> FEATURE: CAL-863, CAL-866 add custom week start to KD

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/export.ts, libs/sdk-ui-tests-e2e/cypress/tools/messages.ts
=> BUGFIX: QA-18768 Fix failure test pdf export

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
fix: remove default stackMeasures when
_ the primaryChartType is Area and only has one metric
JIRA: EGL-47
--- …
=> BUGFIX: EGL-47 - show the continuous line for the combo chart has one metric on the primary area chart

libs/sdk-ui-tests-e2e/README.md
=> FEATURE: QA-18566 review and update README in sdk-ui-tests-e2e

libs/sdk-backend-bear/src/convertors/toBackend/afm/ExecutionConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap, libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/toAfmResultSpec.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/TotalsConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap
**Bear**
- Handle new row native totals
**Tiger/Panther**
- Add missing total elements to calculate marginal totals and grand totals.
JIRA: TNT-1504
---
| **E2E Cypress …
=> FEATURE: TNT-1504 Extend execution payload for new rows totals/subtotals.

.github/pull_request_template.md, compTigerVersions.txt
=> FEATURE: QA-18675 update guide to run integrated test tiger BE ui-sdk

libs/sdk-ui-tests-e2e/cypress/tools/widget.ts
=> BUGFIX: QA-18867 dragDropAndMoveWidget.spec.ts alway fail when running checklist

libs/sdk-ui-pivot/src/CorePivotTable.tsx
=> RELATED: TNT-1505 Use single pushData call when sort changed

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/insight/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListCore.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/InsightDraggingComponent.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributeListItem.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/addAttributeFilterUtils.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/attributeListItemTooltip/AttributeListItemTooltip.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/tests/AttributeListItem.test.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/tests/addAttributeFilterUtils.test.ts, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/useHandlePropertiesPushData.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/InsightDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyInsightMenu/LegacyInsightMenuButton.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/insightToPropsConverter/convenience.ts
=> FEATURE: EGL-57 - show attribute/geo icon in attribute filter dropdown

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: CAL-923 introduce enablePdmRemovalDeprecationPhase feature flag

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/executeAfm/GdcExecution.ts, libs/sdk-backend-base/src/decoratedBackend/execution.ts, libs/sdk-backend-base/src/normalizingBackend/index.ts, libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/execution/index.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/GrandTotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/GrandTotalsConverter.fixture.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/GrandTotalsConverter.test.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/__snapshots__/GrandTotalsConverter.test.ts.snap, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/result.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/TotalsConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap, libs/sdk-ui-pivot/src/impl/data/rowFactory.ts, libs/sdk-ui-pivot/src/impl/tableFacade.ts, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/results/internal/resultDataMethods.ts
=> RELATED: TNT-1502 Execution result and column totals and totals of totals

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/__snapshots__/chartOptionsBuilder.test.ts.snap, libs/sdk-ui-charts/src/highcharts/chartTypes/bubbleChart/bubbleChartSeries.ts
=> BUGFIX: TNT-1541 bubble chart color assignment

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardTigerWithCharts.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/funnelChart.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pyramidChart.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_child_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/FunnelChart/FunnelChartScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/PyramidChart/PyramidChartScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-18878 Write automation ATCs for Funnel and Pyramid chart on SDK

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/Components/AttributeFilterLoading.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdown.tsx
Add isOpen prop to loading component.
This is required for customizations in Analytical Designer.
JIRA: TNT-1563
--- …
=> BUGFIX: TNT-1563 Add isOpen to loading component props

libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
=> BUGFIX: EGL-62 apply Overlay for DateRangePicker

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/workspace/accessControl/index.ts, libs/sdk-backend-tiger/src/types/index.ts
update Tiger API client and do necessary changes in sdk-backend-tiger
--- …
=> FEATURE: CAL-914 update Tiger API client

libs/sdk-ui-pivot/src/impl/structure/colDefFactory.ts, libs/sdk-ui-pivot/src/impl/structure/headers/ColumnTotalGroupHeader.tsx, libs/sdk-ui-pivot/src/impl/structure/headers/TotalHeaderCell.tsx
=> RELATED: FET-769 Circular dependency pivot-table

libs/sdk-model/src/insight/sanitization.ts, libs/sdk-model/src/insight/tests/sanitization.test.ts, libs/sdk-ui-pivot/src/impl/resizing/columnSizing.ts
=> RELATED: TNT-1584 TNT-1577 Do not sanitize column totals when sorted

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts
Mind the levels on which the total appears and use correct measure
lookups for different total levels.
--- …
=> RELATED: TNT-1585 Correctly iterate measures when processing total headers

libs/sdk-ui-dashboard/src/presentation/constants/zIndex.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiExecutor.tsx
=> BUGFIX: TNT-1586 Add overlay controller to kpi

libs/sdk-embedding/package.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/src/internal.ts, libs/sdk-ui-dashboard/src/model/events/index.ts
=> RELATED:  FET-769 fix internal exports

libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-filters/src/internal.ts
=> RELATED: FET-769 Fix internal exports

libs/sdk-backend-mockingbird/src/recordedBackend/catalog.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/tests/changeFilterContextSelectionHandler.test.ts, libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryInsightAttributesMeta.test.ts.snap, libs/sdk-ui-dashboard/src/model/tests/DashboardTester.ts
=> FEATURE: EGL-91 - don't apply elements when backend doesn't supports element uris

.github/actions/check-pull-request-title/build/index.js, renovate.json
=> CONFIG: INFRA-2019 Adjust default renovate commit/PR messages

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
Store tags on the backend when creating a dashboard.
JIRA: RAIL-4976
--- …
=> BUGFIX: RAIL-4976 Save dashboard tags

libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
Ensure more robust loading of dashboard plugins:
In case any dashboard plugin (or its engine) fails to load, fallback to default engine with static plugins.
This helps on tiger, where if you haven't set the correct CSP headers, the dashboard was not loaded at all.
Now it's loaded, just without external plugins.
JIRA: RAIL-4937
--- …
=> BUGFIX: RAIL-4937 More resilient dashboard plugins load

libs/sdk-ui-ext/src/internal/index.ts
=> RELATED: TNT-1543 Export missing internal type

renovate.json
The other FE repos use semantic commits without scope
JIRA: INFRA-2019
--- …
=> CONFIG: INFRA-2019 unify renovate commit messages across front-end repos

libs/sdk-ui-ext/src/internal/components/dialogs/embedInsightDialog/EmbedInsightDialog.tsx, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/insightViewCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/tests/__snapshots__/insightViewCodeGenerator.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/embeddingInsightViewCodeGenerator/tests/insightViewCodeGenerator.test.ts
fix: the embedded code for the insight view doesn't work correctly
_ removing the config object when generating the embedded code
JIRA: EGL-97
--- …
=> BUGFIX: EGL-97 - the embedded code for the insight view doesn't work correctly

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/pivotTableUiConfigHelper.ts
=> RELATED: TNT-1614 Use bucket subtitle only when table transposition is enabled

libs/sdk-ui-ext/src/internal/components/configurationPanels/PivotTableConfigurationPanel.tsx
=> BUGFIX: TNT-1610 Disable config panel when no metrics

examples/sdk-examples/src/index.tsx
=> RELATED: RAIL-5024 provide createRoot for examples rendering

libs/sdk-ui-filters/styles/scss/attributeFilter.scss, libs/sdk-ui-filters/styles/scss/attributeFilterNext/_attributeFilterVariables.scss, libs/sdk-ui-kit/styles/scss/list.scss
=> BUGFIX: RAIL-4992 fix fixed-data-table-2 styles import

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/getOptionalStackingConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/helpers.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/InputControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/OrientationDropdownControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/tests/OrientationDropdownControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/total/TotalSection.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/WaterfallChartConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts
fix: waterfall vertical orientation issues
_limit the total column name input
_X and Y axes should follow the orientation position _the label text should ellipsis
JIRA: EGL-121, EGL-122
--- …
=> BUGFIX: EGL-121, EGL-122 - waterfall vertical orientation issues

libs/sdk-backend-bear/scripts/remove-sensitive-data.js, libs/sdk-backend-tiger/scripts/remove-sensitive-data.js
=> BUGFIX: RAIL-5050 rewrite sensitive data scripts to esm syntax

libs/sdk-ui-ext/src/internal/components/configurationPanels/WaterfallChartConfigurationPanel.tsx
fix: the scale section is in the wrong place
_ it should be in YAxis as default and horizontal orientation
JIRA: EGL-122
--- …
=> BUGFIX: EGL-122 - the scale section is in the wrong place

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/utils/dimensions.ts, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/publicTypes.ts, libs/sdk-ui-tests/tests/_infra/renderPlugVis.tsx
=> FEATURE: TNT-1627 Disable table transposition in RC

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/GrandTotalsConverter.ts
Restoring the original version before #3880
JIRA: TNT-1592
--- …
=> RELATED: TNT-1592 Use transformed totals for zero dimension

libs/sdk-ui-dashboard/src/model/commands/executionResults.ts
Using React 18 resolves in different updates
than before. In cases of exportable error,
the execution is overwriten and export
is therefore disabled. When we do not
overwrite the existing execution,
exports may still happen for such errors.
JIRA: RAIL-5068
--- …
=> BUGFIX: RAIL-5068 do not overwrite existing execution when error occurs

libs/sdk-ui-ext/src/internal/translations/de-DE.json, libs/sdk-ui-ext/src/internal/translations/es-ES.json, libs/sdk-ui-ext/src/internal/translations/fr-FR.json, libs/sdk-ui-ext/src/internal/translations/ja-JP.json, libs/sdk-ui-ext/src/internal/translations/nl-NL.json, libs/sdk-ui-ext/src/internal/translations/pt-BR.json, libs/sdk-ui-ext/src/internal/translations/pt-PT.json, libs/sdk-ui-ext/src/internal/translations/ru-RU.json, libs/sdk-ui-ext/src/internal/translations/zh-Hans.json, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> RELATED: EGL-110, EGL-120 Update localisations

libs/sdk-ui-ext/src/internal/translations/de-DE.json, libs/sdk-ui-ext/src/internal/translations/es-ES.json, libs/sdk-ui-ext/src/internal/translations/fr-FR.json, libs/sdk-ui-ext/src/internal/translations/ja-JP.json, libs/sdk-ui-ext/src/internal/translations/nl-NL.json, libs/sdk-ui-ext/src/internal/translations/pt-BR.json, libs/sdk-ui-ext/src/internal/translations/pt-PT.json, libs/sdk-ui-ext/src/internal/translations/ru-RU.json, libs/sdk-ui-ext/src/internal/translations/zh-Hans.json, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> TRIVIAL: TNT-523 Update localisations

libs/sdk-backend-tiger/vite.integrated.config.ts
From 10s to 20s to stabilize the test for long running execution
JIRA: QA-19574
--- …
=> CONFIG: QA-19574 increase timeout for vitest

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
=> FEATURE: EGL-117 introduce feature flag enableNewHeadline

libs/sdk-ui-all/CHANGELOG.json, libs/sdk-ui-all/CHANGELOG.md
=> TRIVIAL: DC-2931 merge changelog for 8.12.2 to master

README.md
=> CONFIG: LR-1720 add Licenses for UI-SDK 9.0.0

libs/sdk-backend-tiger/vite.integrated.config.ts
=> TRIVIAL: Merge rc -> master

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardShortenMetricName.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/shortenMetricName.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/cypress/tools/table.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_child_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardShortenMetricNameScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/ShortenMetricName/ShortenMetricNameChartScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/ShortenMetricName/ShortenMetricNameTableScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19307 Migrate test MultipleAttributeFilterManipulationTest.java from graphene

libs/sdk-ui-pivot/src/impl/structure/colDefFactory.ts, libs/sdk-ui-pivot/src/impl/structure/tableDescriptor.ts
=> RELATED: TNT-1630 Show aggregations menu when no row attr & metrics in rows

.github/actions/hugo_build_action/action.yaml, .github/workflows/netlify-deploy.yaml
=> TRIVIAL: adding documentation pipelines

libs/sdk-ui-all/CHANGELOG.json, libs/sdk-ui-all/CHANGELOG.md
=> TRIVIAL: merge changelogs properly

renovate.json
=> TRIVIAL: Add TRIVIAL keyword to renovate-generated commits

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/getChartOrientationConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/getChartOrientationConfiguration.test.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/OrientationDropdownControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/tests/OrientationDropdownControl.test.tsx
fix: some issues of vertical waterfall chart
_ the name position should switch between X and Y axes 
_ should ellipsis the long label
JIRA: EGL-143, EGL-153
---
| **E2E …
=> BUGFIX: EGL-143, EGL-153 - some issues of vertical waterfall chart

libs/sdk-ui-dashboard/styles/scss/filterBar.scss
fix: attribute filter with long name is not shorten on KD
JIRA: EGL-160
--- …
=> BUGFIX: EGL-160 - attribute filter with long name is not shorten on KD

libs/sdk-ui-ext/src/internal/components/configurationControls/ColumnHeadersPositionControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/ConfigDummySection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/MetricsPositionControl.tsx, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/publicTypes.ts
=> FEATURE: TNT-1590 Add test classes and alpha tag

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/headline/CoreHeadline.tsx, libs/sdk-ui-charts/src/charts/headline/Headline.tsx, libs/sdk-ui-charts/src/charts/headline/HeadlineProvider.ts, libs/sdk-ui-charts/src/charts/headline/HeadlineProviderFactory.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/AbstractProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/ComparisonProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/LegacyProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/MultiMeasuresProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/AbstractProvider.test.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/MockProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/AbstractProvider.test.ts.snap, libs/sdk-ui-charts/src/charts/headline/internal/transformations/LegacyHeadlineTransformation.tsx, libs/sdk-ui-charts/src/charts/headline/internal/transformations/test/LegacyHeadlineTransformation.fixtures.ts, libs/sdk-ui-charts/src/charts/headline/internal/transformations/test/LegacyHeadlineTransformation.test.tsx, libs/sdk-ui-charts/src/charts/headline/tests/CoreHeadline.test.tsx, libs/sdk-ui-charts/src/charts/headline/tests/Headline.test.tsx, libs/sdk-ui-charts/src/charts/headline/tests/HeadlineProviderFactory.test.ts, libs/sdk-ui-charts/src/charts/index.tsx, libs/sdk-ui-charts/src/interfaces/chartConfig.ts, libs/sdk-ui-charts/src/interfaces/comparison.ts, libs/sdk-ui-charts/src/interfaces/index.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline.test.tsx, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/headline.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/headline.test.tsx
=> FEATURE: EGL-142 - introduce comparison interface, headline provider interface
