libs/sdk-backend-bear/src/backend/workspace/attributes/elements/index.ts, libs/sdk-backend-bear/src/convertors/dateFormatting/dateFormatter.ts, libs/sdk-backend-bear/src/convertors/dateFormatting/dateValueParser.ts, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/FilterConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/ExecutionConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/FilterConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/utils.ts, libs/sdk-backend-mockingbird/src/recordedBackend/elementsUtils.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/DimensionsConverter.ts, libs/sdk-model/src/execution/base/sort.ts, libs/sdk-model/src/execution/results/index.ts, libs/sdk-model/src/ldm/attributeElement.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightWithDrillDialog.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoChartOptionsWrapper.tsx, libs/sdk-ui-geo/src/core/geoChart/geoChartColor.ts, libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/data.ts, libs/sdk-ui-geo/src/core/geoChart/tests/GeoChartInner.test.tsx, libs/sdk-ui-pivot/src/columnWidths.ts, libs/sdk-ui-pivot/src/impl/data/rowGroupingProvider.ts, libs/sdk-ui-pivot/src/impl/structure/colDefFactory.ts, libs/sdk-ui/src/base/results/dataAccess.ts, tools/mock-handling/src/codegen/dataSample.ts
Conservatively prepare the codebase and TSDocs for nulls in
AttributeResultHeaders.
Done so to avoid hard breaking change for now, we will really change the
types in the next major, this is to prepare the users for this change
and also prevent some runtime errors.
JIRA: RAIL-4360
---
--- …
=> RELATED: RAIL-4360 Partially prepare for null AttributeResultHeaders

libs/sdk-ui-pivot/src/impl/drilling/drilledRowFactory.ts, libs/sdk-ui/src/base/vis/drilling.ts
=> RAIL-4356 - Cannot drill at empty value with JS error

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx
* Respect tag configuration
* Fix bug when enabling date filter
---
--- …
=> RELATED: RAIL-4158 minor fixes to date filter config

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ScrollContext.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ScrollablePanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetSelection.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfigurationHeader.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfigurationItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfigurationWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightFilters.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightTitleConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
Migrate parts of the Insight config panel. Missing interactions, but to keep it small.
Missing
- interaction section
- drilling
---
--- …
=> RAIL-4159 Migrate Insight configuration panel

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Header/generateHeaderStaticHelpMenuItems.ts
Update the link to docs in the Help menu
_ Correcting the documentation link
_ Allow the doc links can be changeable via the params
JIRA: SD-2321
---
--- …
=> RELATED: SD-2321 - Update the link to docs in the Help menu

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditableDashboardKpi/EditableDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/index.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/useKpiExecutionDataView.ts
This mimics what the withExecution HOC does.
JIRA: RAIL-4377
---
--- …
=> RELATED: RAIL-4377 Fix handling of KPIs with empty response format

libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/execution/Execute.tsx, libs/sdk-ui/src/execution/createExecution.ts, libs/sdk-ui/src/execution/tests/Execute.test.tsx
This aligns it to ExecuteInsight that can already process insights without measures. This is useful for example for tables that only have rows and columns defined.
JIRA: RAIL-4379
---
--- …
=> RELATED: RAIL-4379 Allow passing only slicesBy to Execute

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetPicker.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useIsSelectedDatasetHidden.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditableDashboardKpi/KpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/useKpiData.ts
* respect object visibility for date datasets
* allow changes to config that is already invalid
* fix useKpiData hook
---
--- …
=> RELATED: RAIL-4158 filter config fixes

libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts
The side effect needs to be in useEffect, not called directly
in the hook body.
JIRA: RAIL-4382
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master …
=> RELATED: RAIL-4382 Use side effects properly

libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts, libs/sdk-ui-filters/src/AttributeElements/AttributeElements.tsx
Only set the potentially unsupported option if requested.
Also improve the error messages in the related parts of tiger backend.
---
--- …
=> RELATED: RAIL-4386 fix AttributeElements on tiger backends

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/bridge.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSelectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initTotalCount.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSelectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadNextElementsPage.test.ts.snap, libs/sdk-ui-filters/src/AttributeFilterHandler/test/loadNextElementsPage.test.ts
- Correct paging logic
- Do not fire load when all elements are loaded
- Fix validation of the changed elements load options
- Fix clashing init correlations
RAIL-4231
---
--- …
=> RELATED: RAIL-4293 Fix loadNextElementsPage in AttributeFilterHandler

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetSelection.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyDashboardInsightMenu.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyDashboardInsightMenuButton.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardKpiWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/useInsightMenu.ts
* Fix how insight menu behaves in edit mode. This is just a quick fix to make it work, I will refactor this more significantly later.
* Step towards unified widget definitions.
---
--- …
=> RELATED: RAIL-4391 fix insight menu, partially refine widget definitions

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
* memoize renderers
* do not pass prop that is not used
* improve filters digests in useWidgetFilters
---
--- …
=> RELATED: RAIL-4391 prevent unnecessary re-renders and re-executions

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/moveSectionItemHandler.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/validation/layoutValidation.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/Hotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/index.ts, libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
Add support for adding existing widgets in existing sections.
Also relax placement validations to make the implementation significantly simpler.
**Caveats**
- will not show placeholders yet, so the user cannot preview what will happen to the layout, but the adding works properly: if you drop on the left side of a widget, the insight is added before it, otherwise after it.
---
---
-   [ ] …
=> RELATED: RAIL-4170 add support for adding existing widgets in existing sections

libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
New approach considers decimals that are necessary for precise creation of textarea to avoid breaking the line once the width is not precise enough.
JIRA: TNT-910
---
--- …
=> RELATED: TNT-910 Changed the width calculation of edit box.

libs/sdk-ui-dashboard/.dependency-cruiser.js, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/layout/sizing.ts, libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/placeholders/index.ts, libs/sdk-ui-dashboard/src/model/store/placeholders/placeholdersReducers.ts, libs/sdk-ui-dashboard/src/model/store/placeholders/placeholdersSelectors.ts, libs/sdk-ui-dashboard/src/model/store/placeholders/placeholdersState.ts, libs/sdk-ui-dashboard/src/model/store/types.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/Layout.fixtures.ts, libs/sdk-ui-dashboard/src/model/utils/arrayOps.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/DraggableInsightListItem.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/Hotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/SectionHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/WidgetDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/WidgetDropZoneBox.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDrop.ts, libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardWidget.tsx, libs/sdk-ui-dashboard/src/widgets/placeholders/types.ts
This adds support for adding insights to the existing sections including the placeholders (the last missing variant).
Also prevents a React key warning and makes rootReducer type-safe.
---
--- …
=> RELATED: RAIL-4170 add adding insight into existing sections

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/assets/filter-bar-background.svg, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/constants/filterBar.ts, libs/sdk-ui-dashboard/src/presentation/constants/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardMainContent.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useFilterBarState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useRowsCalculator.ts, libs/sdk-ui-dashboard/styles/scss/_variables.scss, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
Rework filter bar to be able to work with different heights of filters used in filter bar.
- Remove bar height in state and all things around (selectors, reducers, state record)
- Remove adding top margin on if filter bar is expanded, its cause space after filter bar and content
- Move state of filter bar into separate hook
=> Add class scrollable after opening animation is done
- Row calculator hook that is able to determine rows in flex box and height of each row
JIRA: RAIL-4393
---
| `extended …
=> RAIL-4393 - Prepare plugins API for filters customizations

libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardList.tsx, libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardListButton.tsx, libs/sdk-ui-dashboard/src/presentation/dashboardList/DashboardListItem.tsx, libs/sdk-ui-dashboard/src/presentation/dashboardList/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboardList/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
Add dashboardList component
JIRA: RAIL-4310
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reque …
=> RAIL-4310 Add dashboardList component

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts
=> RELATED: RAIL-4342 Expose selectors for SDK edit mode

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-spi/src/workspace/insights/index.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/StylingEditorDialog.tsx, libs/sdk-ui-kit/src/Dialog/StylingEditorDialog/index.ts, libs/sdk-ui-kit/src/Dialog/tests/StylingEditorDialog.test.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPicker.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerBody.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerHeader.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerList.tsx, libs/sdk-ui-kit/src/StylingPicker/StylingPickerListItem.tsx, libs/sdk-ui-kit/src/StylingPicker/index.ts, libs/sdk-ui-kit/src/StylingPicker/tests/StylingPicker.test.tsx, libs/sdk-ui-kit/src/StylingPicker/tests/mocks.ts, libs/sdk-ui-kit/src/StylingPicker/tests/utils.test.ts, libs/sdk-ui-kit/src/StylingPicker/utils.ts, libs/sdk-ui-tests/stories/visual-regression/kit/Dialog/Dialog.tsx, libs/sdk-ui-tests/stories/visual-regression/kit/StylingPicker/StylingPicker.tsx, libs/sdk-ui-tests/stories/visual-regression/kit/StylingPicker/itemsMock.ts
JIRA: TNT-932 TNT-933
Styling dialogs now accept also color palette
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do …
=> Unify dialog types to accept also color palette

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
=> Expose getDataSourceIdentifierById in tigerSpecificFunctions

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useInsightPlaceholderDropHandler.ts
Make the logic very similar to how KPI placeholders are handled.
This ensures any widget placeholders are properly replaced.
JIRA: RAIL-4170
---
--- …
=> RELATED: RAIL-4170 Fix handling of insight placeholder drop

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/List.tsx, libs/sdk-ui-kit/src/List/MultiSelectList.tsx, libs/sdk-ui-kit/src/List/MultiSelectListItem.tsx, libs/sdk-ui-kit/src/List/index.ts
- it's used in gdc-msf-modeler
- also revert List rowBufferCount set to 0 as it causes annoying console logs that cannot be omitted
JIRA: RAIL-4255
---
--- …
=> Revert MultiSelectList removal

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-loaders/package.json, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-theme-provider/package.json, libs/sdk-ui-web-components/package.json, skel/sdk-skel-tsx/package.json, tools/dashboard-plugin-tests/package.json
They are no longer wanted or needed, so neither allow nor install them.
JIRA: FET-1116
---
--- …
=> RELATED: FET-1116 Remove node-sass and node-sass-magic-importer

common/config/rush/pnpm-lock.yaml
Both upgrades avoid some ReDoS vulnerabilities.
---
--- …
=> RELATED: FET-1117, FET-1118 upgrade terser and moment

libs/sdk-backend-bear/src/backend/workspaces/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts
Improving the workspaces on TIGER:
_ Can set the parent workspace id
_ With the parent workspace can get its child workspaces
JIRA: SD-2350
---
--- …
=> RELATED: SD-2350 - Modify the SDK to support to get workspace hierarchy

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/DefaultEmptyLayoutDropZoneBody.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/index.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/EmptyDashboardError.tsx, libs/sdk-ui-dashboard/src/presentation/layout/EmptyDashboardLayout.ts, libs/sdk-ui-dashboard/src/presentation/layout/types.ts
Also simplify the empty layout handling.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request- …
=> RELATED: RAIL-4170 Add support for customizing empty layout dropzone

libs/sdk-ui-kit/src/Dialog/DialogList/DialogListEmpty.tsx, libs/sdk-ui-kit/src/Dialog/DialogList/DialogListHeader.tsx, libs/sdk-ui-kit/src/Dialog/DialogList/DialogListItemBasic.tsx, libs/sdk-ui-kit/src/Dialog/DialogList/tests/DialogList.test.tsx, libs/sdk-ui-kit/src/Dialog/DialogList/tests/DialogListHeader.test.tsx, libs/sdk-ui-kit/src/Dialog/DialogList/tests/DialogListItemBasic.test.tsx, libs/sdk-ui-kit/src/DocumentHeader/tests/DocumentHeader.test.tsx, libs/sdk-ui-kit/src/Dropdown/tests/Dropdown.test.tsx, libs/sdk-ui-kit/src/Dropdown/tests/DropdownList.test.tsx, libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx, libs/sdk-ui-kit/src/EditableLabel/tests/EditableLabel.test.tsx, libs/sdk-ui-kit/src/List/List.tsx, libs/sdk-ui-kit/src/Tabs/Tabs.tsx
RTL tests: dialog, documentHeader, dropdown
JIRA: FET-1113
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-i …
=> RELATED: FET-1113 skd-ui-kit 

.gitlab-ci.yml
The previous structure had invalid YAML anchors. Changing
to more modern `extends` approach.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/do …
=> BUGFIX: RAIL-4319 Fix gitlab pipeline definition

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/Layout.fixtures.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/Hotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/SectionHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/WidgetDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useInsightListItemDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useInsightPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionInsightPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useWidgetDragEndHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpiPlaceholder/DefaultDashboardKpiPlaceholderWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpiPlaceholder/KpiPlaceholderConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/widgets/placeholders/types.ts
They are not needed, we need to use the placeholders actual position
in the layout at the time of use. This makes it more robust.
JIRA: RAIL-4438
---
--- …
=> RELATED: RAIL-4438 Remove section and item indexes from placeholders

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/CreationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightList.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/types.ts, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
Latest insight in saved insights list isn't displayed
RAIL-4427
---
--- …
=> Latest insight in saved insights list isn't displayed

libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts
=> FEATURE: SD-2357 Update WorkspaceConverter in sdk-backend-tiger to use description field returned from BE

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/user/settings.ts, libs/sdk-backend-bear/src/backend/workspace/settings/settings.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-spi/src/user/settings/index.ts, libs/sdk-backend-spi/src/workspace/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts, libs/sdk-ui-ext/src/dataLoaders/test/UserWorkspaceSettingsDataLoader.test.ts
Set locale support for user, workspace and organization.
JIRA: TNT-971
---
--- …
=> RELATED: TNT-971 Added setLocale support

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/catalog.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/workspace/catalog/availableItemsFactory.ts, libs/sdk-backend-bear/src/backend/workspace/catalog/factory.ts, libs/sdk-backend-bear/tests/integrated/__snapshots__/catalog.test.ts.snap, libs/sdk-backend-mockingbird/src/recordedBackend/catalog.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/ldm/catalog.ts, libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts, libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts, libs/sdk-backend-tiger/tests/integrated/__snapshots__/catalog.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadCatalog.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useIsSelectedDatasetHidden.ts
- Make loading of the catalog groups optional
- For now, default to true (for backward compatibility)
JIRA: RAIL-4459
---
--- …
=> RELATED: RAIL-4459 Make loading of the catalog groups optional

libs/sdk-backend-bear/src/backend/workspace/catalog/factory.ts
- I removed condition for optional group call by mistake in previous PR, return it back.
JIRA: RAIL-4459
---
--- …
=> RELATED: RAIL-4459 Fix group call condition

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss, libs/sdk-ui-kit/styles/scss/datepicker.scss
Due to be able to use plugins with older version of SDK we need to keep css also for old definition of DatePicker. This is because plugins has not bundled css and uses parent css from dashboards.
This needs to be solved in future systematics way because can cause lots of problems ... :(
JIRA: RAIL-4460
---
--- …
=> RAIL-4460: Date filter calendar broken with SDK v8.10 plugin

libs/sdk-ui-kit/src/Messages/useToastMessage.ts
=> SD-2393: Allow passing dynamic value to useToastMessage in SDK

libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/utils/errorHandling.ts
=> RELATED: SD-2384 Return ContractExpired error rather than throwing it, so that the handler for the error can be invoked

tools/dashboard-plugin-template/package.json
This is needed so that sdk-ui-filters can accept singleton instance from KD and thus use the correct contexts for react-intl. This issue is very similar to the one fixed in RAIL-3937 but from the plugin's side.
JIRA: RAIL-4465
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-th …
=> RELATED: RAIL-4465 Add sdk-ui-filters to plugin peerDeps

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/state.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/resetLoadOptionsOnSearch.test.ts
=> BUGFIX: RAIL-4440 Handle offset reset to get proper searched elements

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/plugins/customizationApis/attributeFiltersCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/dateFiltersCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizer.ts
The API is hard to use correctly, we need to rethink the decorator APIs as a whole later.
JIRA: RAIL-4455
---
--- …
=> RELATED: RAIL-4455 Remove filter decorator API

libs/sdk-ui-filters/src/AttributeFilter@next/types.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/factory.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/loader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/utils/sanitizeInputFilter.ts
When a user hides an element and uses it in the input filter, it would previously throw an invariant. Thus, we sanitize the input because we know that the hidden elements will be resolved in the output filter later anyway.
Also mention `hiddenElements` correct usage.
JIRA: RAIL-4448
---
--- …
=> RELATED: RAIL-4448 Prevent invariant error in attribute filter loader

common/changes/@gooddata/sdk-ui-all/MAP-RAIL-4439-caching-backend_2022-09-22-11-54.json, examples/sdk-examples/src/context/auth/context.tsx, libs/sdk-backend-base/README.md, libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/index.ts, libs/sdk-backend-bear/src/backend/workspace/execution/test/executionFactory.test.ts
- optimize CachingConfiguration interface
- make the cachingBacken decorator and all related types public
JIRA: RAIL-4439
---
--- …
=> RELATED: RAIL-4439 - Make cachingBackend decorator public

libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatExecuteOnSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatFrequencySelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatTypeSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/repeat.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/test/repeat.test.ts
- When day of month for custom type is selected, keep these values after saving it.
- Change how localization messages are constructed, dont use dynamic variables.
JIRA: TNT-983
---
---
-   [ ] review was done by …
=> Schedule email date issue

libs/sdk-ui-dashboard/styles/scss/filterBar.scss
This caused an invisible element to overlay actual useful elements, which in turned complicated e2e tests.
JIRA: RAIL-4492
---
--- …
=> RELATED: RAIL-4492 Remove harmful z-index setting

common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
- Remove loading of the `connectingAttributeMatrix` on the dashboard component initialisation. This will cause the attribute filter configuration not to work in the new editMode currently being developed. The follow-up task will move the loading of the matrix on demand while opening the attribute filter configuration, if the data were not loaded before.
JIRA: RAIL-4494
---
---
-   [ ] …
=> RELATED: RAIL-4494 Remove connecting attributes loading on dashboard init

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useParentsConfiguration.ts
- After integration of new AttributeFilter and removing connectingAttributesMatrix in view mode (https://github.com/gooddata/gooddata-ui-sdk/pull/2991) it's touching non-existing indexes in connectingAttributesMatrix
JIRA: RAIL-4390
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-sho …
=> Temporarily fix parent filters in view mode

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/InMemoryPaging.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/loadElementsFromBackend.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/loadElementsFromStaticElements.ts
- Bear validElements API does not support loading elements by values, but it's possible to load them with execution API.
- This is necessary to load the initial selection.
JIRA: RAIL-4290
---
---
-   [ ] review …
=> Support for text values on Bear in AttributeFilterHandler

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/cachingBackend/tests/withCaching.test.ts, libs/sdk-backend-base/src/dummyBackend/index.ts
=> RELATED: RAIL-4418 Add getAttributeByDisplayForm caching

libs/sdk-ui-dashboard/src/presentation/widget/common/EditableHeadline.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiMetricDropdown/KpiMetricDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeKpiHeadline.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/useOptimisticMeasureUpdate.ts
Use optimistic updates when changing the measure of a KPI widget. This makes the switch seem instantaneous even though there are some async operations running in the background.
Also, make the KPI title editable.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look …
=> RELATED: RAIL-4488 improve the perceived KPI performance when changing measure, make KPI title editable

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/index.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useParentFilters.ts, libs/sdk-ui-filters/src/AttributeFilter@next/AttributeFilterBase.tsx, libs/sdk-ui-filters/src/AttributeFilter@next/utils.ts
- Expose useParentFilters hook, so it can be used by dashboard plugins for custom attribute filter implementations
- Parent filtering / hidden elements are not supported on tiger - provide better error messages
JIRA: RAIL-4464, RAIL-4452
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#wha …
=> Improve AttributeFilter error messages, expose useParentFilters hook

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/cachingBackend/tests/withCaching.test.ts, libs/sdk-backend-base/src/dummyBackend/index.ts
This only caches the first `query` results, the `next` and `goTo` are not cached yet. Also queries with the `filter` set are not cached either.
JIRA: RAIL-4418
---
--- …
=> RELATED: RAIL-4418 Add first version of attribute elements caching

libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/KpiContent/KpiContent.tsx
Remove check for `absoluteDateFilter` for KPI's, so is able to display previous periods comparison when static range is selected, same as with headlines.
JIRA: TNT-447
---
--- …
=> Display comparison for static range on KPI's

libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterController.ts
In case both limiting filters and the filter itself changes at the same time, we need to handle the limiting filter change first. That way the new limited elements load before the new selection is applied and the filter gets re-initialized.
JIRA: RAIL-4508
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/ …
=> RELATED: RAIL-4508 Fix attribute filter hierarchies

tools/plugin-toolkit/src/_base/terminal/prompts.ts, tools/plugin-toolkit/src/updatePluginParamsCmd/actionConfig.ts
- while updating dashboard plugin parameter and prompted to enter the new value, the original value is in the editor as well for easier handling its update or typo fixes.
JIRA: RAIL-4410
---
--- …
=> RELATED: RAIL-4410 Show original plugin parameters when prompt while updating

libs/sdk-ui-filters/src/AttributeFilter@next/hooks/useAttributeFilterController.ts
- When attribute filter initialization is not finished yet, do not load initial elements page, but trigger fresh init
JIRA: RAIL-4521
---
--- …
=> Fix attribute filter parent change during init

examples/sdk-examples/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-tests/package.json
=> Fix security advisory for moment in gooddata-ui-sdk

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> MED-209: Added feature flag to support new SQL and data explain in metric editor

libs/sdk-backend-bear/src/backend/workspace/attributes/elements/limitingAfmFactory.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/callbacks.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/index.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/types.ts
Since this is not supported on bear, we error. This PR makes sure the error is surfaced into the console to make debugging easier and improves the related error message. Also a small typo in one of the type names was fixed.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-c …
=> RELATED: RAIL-4515 handle hiddenElements by value on bear

libs/api-client-bear/src/gooddata.ts, libs/api-client-bear/src/organization.ts, libs/api-client-bear/src/project.ts, libs/api-client-bear/src/tests/project.test.ts, libs/api-client-bear/src/tests/user.test.ts, libs/api-client-bear/src/user.ts, libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/index.ts, libs/api-model-bear/src/organization/GdcOrganization.ts, libs/api-model-bear/src/project/GdcProject.ts, libs/api-model-bear/src/user/GdcUser.ts, libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-bear/src/backend/organization/index.ts, libs/sdk-backend-bear/src/backend/workspace/permissions/permissions.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/react/ClientWorkspaceContext/resolveLCMWorkspaceIdentifiers.ts, tools/applink/README.md
The BootstrapResource API no longer loads analytical dashboards list to optimize call duration.
New APIs are called instead of BootstrapResource when possible. Ideally, BootstrapResource call should not be used by any internal Bear API in the future and new API should be created when some part of its response is needed by any new or existing API.
JIRA: TNT-1065
---
---
-   [ ] commit …
=> Minimize BootstrapResource usage in Bear backend

libs/sdk-ui-dashboard/src/_staging/dashboard/legacyFilterConvertors.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
- In the past, we were relying on the fact that uris and titles are equal on panther/tiger (this is also the way, how it's stored on the backend)
- This is not true anymore, so convert filter before passing it to plugins / components
- Also convert it back to uris in onFilterChanged callback
JIRA: RAIL-4517
---
--- …
=> Fix attribute filters using non-primary labels

tools/plugin-toolkit/src/updatePluginParamsCmd/actionConfig.ts
=> RELATED: RAIL-4410 Remove unnecessary part of the error statement

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/queries/attributes.ts, libs/sdk-ui-dashboard/src/model/queries/base.ts, libs/sdk-ui-dashboard/src/model/queries/index.ts, libs/sdk-ui-dashboard/src/model/queryServices/index.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryAttributeByDisplayForm.ts, libs/sdk-ui-dashboard/src/model/types/attributeFilterTypes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useAttributes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDisplayFormConfiguration.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useOriginalConfigurationState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useParentsConfiguration.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersList.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersListItem.tsx
- refactoring of useParentsConfiguration hook
- add query to fetch attributes for given display forms
- refactor handling of changes in parent filters configuration
JIRA: RAIL-4519
---
--- …
=> BUGFIX: RAIL-4519 Attribute metadata fetching for deprecated attributes

libs/sdk-ui-kit/src/ChartSorting/MeasureDropdown/MeasureDropdown.tsx
Make sure that arithmetic measures are not incomplete when displaying them on measure dropdown.
JIRA: TNT-558
---
--- …
=> Measure dropdown has blank space if the bucket contains incomplete AM

common/config/rush/pnpm-lock.yaml
This fixes a security advisory. This package is only used in sdk-examples so it now being a pure ESM module is ok.
JIRA: FET-1136
---
--- …
=> RELATED: FET-1136 Upgrade d3-color 2.0.0 -> 3.1.0

tools/dashboard-plugin-template/.eslintrc.js, tools/dashboard-plugin-template/.gitignore, tools/dashboard-plugin-template/configTemplates/js/.eslintrc.js, tools/dashboard-plugin-template/configTemplates/js/jest.setup.js, tools/dashboard-plugin-template/configTemplates/ts/.eslintrc.js, tools/dashboard-plugin-template/configTemplates/ts/jest.setup.ts, tools/dashboard-plugin-template/jest.setup.ts, tools/dashboard-plugin-template/scripts/refresh-md.js, tools/dashboard-plugin-template/webpack.config.js
* add node_modules to gitignore
* remove eslint rule ignores from config files and exclude them from ESLint validation. This is because the rules we use to validate SDK are different than the rules used to validate the bootstrapped plugin. The ignores then made some IDEs issue warnings of unknown ESLint rules being included.
---
--- …
=> RELATED: RAIL-4528 plugin template DX improvements

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/common/selectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initTotalCount.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadInitialElementsPage.test.ts.snap, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadNextElementsPage.test.ts.snap
- When user specifies elements by primaryLabel (uris), but uses different label for the filter, do not use excludePrimaryLabel option
JIRA: RAIL-4529
---
--- …
=> Fix elements loading on tiger for primary label

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx, examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommandSrc.tsx, libs/sdk-ui-dashboard/src/model/store/user/userSelectors.ts, tools/dashboard-plugin-template/src/plugin/Plugin.tsx
=> RELATED: RAIL-4531 Remove the redundant word in plugin comments

libs/sdk-backend-tiger/src/utils/errorHandling.ts
=> Error message is wrong when license is expired

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartSeries.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/treemap/treemapChartSeries.ts
There were some more places that needed the empty headers handled.
JIRA: RAIL-4539
---
--- …
=> RELATED: RAIL-4539 Add missing empty header handling

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/test/ScheduledMailDialogRenderer.test.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/scheduledMailRecipients.ts
User can have different login and email address. Scheduled emails were sent based on user login address, which was also causing some issues on the way we display user information on UI.
Update schedule email so it takes correct user email address and displays correct value on UI.
**JIRA: TNT-1036**
---
--- …
=> Scheduled emails are sent to the login address instead of email address

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterBase.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterControllerData.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterHandler.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/rootSaga.ts
- move telemetry from react components to handler creation (elsewhere it's causing unnecessary reinits)
- handle also filtering status triggered by reinit
- remove annoying console log from the root saga
- remove redundant commented import
JIRA: RAIL-4542
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/c …
=> Fix attribute filter stuck in filtering state

libs/sdk-ui/.i18nrc.js, tools/i18n-toolkit/src/data.ts, tools/i18n-toolkit/src/utils/console.ts, tools/i18n-toolkit/src/validations/test/checkTranslations.test.ts, tools/i18n-toolkit/src/validations/usage/checkTranslations.ts
- added test to check translations method
JIRA: RAIL-4547
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if …
=> RELATED: RAIL-4547 Change toolkit to work better with ignore rule

libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
Temporary hide export feature.
- Was not fully tested for P8. Will be re-enabled after for P9
JIRA: TNT-1096
Verification done in team.
---
--- …
=> Temporary hide export feature

libs/sdk-ui-web-components/src/visualizations/CustomElementAdapter.ts, libs/sdk-ui-web-components/src/visualizations/components.shadow.css
JIRA: RAIL-4569
* Added style loading to the list of dependencies that we need to wait for before removing the Loader
* Inlined the mount point styles to prevent Loader from jumping once the styles are applied
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-li …
=> Fixed FOUC on WebComponents loading

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx
- On layout change, do not re-render all the widgets, but only widgets in changed section
- Also avoid DashboardLayoutGridRow (and nested child widgets) remounting, by switching to index keys
JIRA: RAIL-4568
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like …
=> Reduce widget re-renders

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/index.ts
JIRA LOB-318
Regenerate client
add 3 methods: setWorkspaceCustomApplicationSetting, getWorkspaceCustomApplicationSettings, and deleteWorkspaceCustomApplicationSetting
---
--- …
=> LOB-318 Generate sdk-ui library for new layout API in BEAR/TIGER

examples/sdk-examples/src/context/auth/GoodDataAuthProvider.ts
Otherwise, some calls like permissions fail.
JIRA: RAIL-4596
---
--- …
=> RELATED: RAIL-4596 Pass real userId in anonymous provider

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/handler.test.ts, libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts
The next SDK release will have this done, so we mark it as finished now to make it easier to test upstream.
JIRA: RAIL-4100
---
--- …
=> Remove dashboardEditModeDevRollout from unfinished

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-dashboard/scripts/build.sh, libs/sdk-ui-dashboard/styles/scss/main.scss, libs/sdk-ui-tests/.storybook/preview-head.html, libs/sdk-ui-tests/backstop/scenarios.config.js, libs/sdk-ui-tests/stories/_infra/webComponents.ts
It pollutes global styles which can break users' applications. Also load web-components stuff in storybook only when needed, otherwise it loads bunch of unrelated styles and makes the tests unstable (there is a delay there).
JIRA: RAIL-4661
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …
=> RELATED: RAIL-4661 Remove normalize.css from dashboard

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/saveDashboardHandler.test.ts, libs/sdk-ui-dashboard/src/model/commands/dashboard.ts, libs/sdk-ui-dashboard/src/model/commands/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx
* RAIL-4574 - We must provide the default title from outside as it needs to be localized and we can only access that information from react-land.
* RAIL-4577 - Indicate edit mode for date filter properly.
---
--- …
=> RELATED: RAIL-4574, RAIL-4577 Add support for saving untitled dashboards, add date filter message

libs/sdk-ui-web-components/src/index.ts, libs/sdk-ui-web-components/src/parseUrl.ts, libs/sdk-ui-web-components/src/tests/parseUrl.test.ts
=> Added a warning message about missing Authentication setup in web components

libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/DefaultDashboardKpiWithDrills.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/KpiRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/useKpiDrill.ts
Turns out the KPI should drill even in edit mode when selected and not embedded and default drill not disabled.
JIRA: RAIL-4579
---
--- …
=> RELATED: RAIL-4579 Fix KPI drill in edit mode

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DefaultAttributeFilterDraggingComponent.tsx
We must show the attribute name, not the display form name: we show attribute in the filter title as well -> make it consistent.
JIRA: RAIL-4607
---
--- …
=> RELATED: RAIL-4607 Show attribute name in filter drag preview

libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts
RSQL cannot handle prefixes, so we strip them for the RSQL filter and filter the result on client instead.
See 8d0ed453243a1ee2f74c65c9c985877a8b25fcd0 for a similar fix.
JIRA: RAIL-4618
---
--- …
=> RELATED: RAIL-4618 Fix getAttributeDisplayForm on tiger with prefixes

libs/sdk-ui-theme-provider/stories/tsconfig.json
This file is not used for anything and trips up SonarQube for no reason.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#h …
=> TRIVIAL: Remove useless tsconfig

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
Hide the config button if there is nothing to actually configure:
* there is only one filter -> no parent filtering possible
* filter attribute has single df -> no df config possible
JIRA: RAIL-4625
---
---
-   [ …
=> RELATED: RAIL-4625 Show attr filter config only when useful

common/scripts/install-run-rush.js, common/scripts/install-run.js, rush.json
Skipped upgrading pnpm to version 7, it does not work without also using the PNPM workspaces (we will investigate it in a separate story).
---
--- …
=> RELATED: FET-1157 upgrade rush and pnpm to latest minors

libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts
=> BUGFIX:  RAIL-4628 can not save widget layout in new edit mode

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, examples/playground/package.json, examples/playground/src/index.tsx, examples/sdk-examples/package.json, examples/sdk-examples/src/index.tsx, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests/package.json
- babel-runtime removed, it was not used anyway
- babel-polyfill replaced by @babel/polyfill
- @babel/polyfill moved to dependencies
JIRA: FET-1161
---
--- …
=> RELATED: FET-1161 Get rid of Babel 6 packages

libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightEditMenuBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx
In KD edit mode open Config panel for some Widget and go to some submenu, eg. Configuration. Arrow color needs to be different based on submenu.
JIRA: RAIL-4629
---
--- …
=> BUGFIX: RAIL-4629 wrong arrow color

libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts
fix: the workspace title should not be the workspace id if it is empty
JIRA: SD-2481
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …
=> BUGFIX: SD-2481 - Workspace list - Sort function works incorrectly

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, docs/contributing.md, libs/sdk-ui-kit/package.json, libs/sdk-ui-kit/src/Overlay/Overlay.tsx
Comparing whole props including children by lodash/isEqual may end up in infinite loop https://github.com/facebook/react/issues/19811
It happened when UI tested by Cypress tests
JIRA: TNT-1164
---
---
-   [ ] …
=> BUGFIX: TNT-1164 Dont use lodash/isEqual to compare whole props

libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts, libs/sdk-backend-tiger/tests/integrated/__snapshots__/catalog.test.ts.snap
We did not fill the `attribute` and `displayForms` fields correctly.
This was fixed and the conversion logic was unified a bit.
JIRA: RAIL-4626
---
--- …
=> RELATED: RAIL-4626 fix attribute convertors

libs/sdk-ui-kit/src/Bubble/Bubble.tsx
=> BUGFIX: TNT-1164 Omit comparing Bubble props by lodash/isEqual

libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiDescriptionTrigger.tsx
=> BUGFIX: TNT-1171 Change default behavior for widget descriptions

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
Also make sure that if the command fails, the state remains consistent.
JIRA: RAIL-4626
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/co …
=> RELATED: RAIL-4626 fix display form changing

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/useScheduledEmailManagement.ts
JIRA: TNT-1172
This brings the functionality back to the original behaviour before
changed by https://github.com/gooddata/gooddata-ui-sdk/pull/3099
where users were fetched only for the purposes of editing emails,
guarded by the necessary permission.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contri …
=> RELATED: TNT-1172 Fetch users only when permission is granted

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useConnectingAttributes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/parentFilters/ParentFiltersList.tsx
On tiger, we must not call the parent filter query, it would always end up in an error state.
Also, remove unreachable code in ParentFiltersList, the parent.length === 0 is handled in the previous if.
---
---
- …
=> RELATED: RAIL-4626 fix attribute filter configuration on tiger

libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
When dashboard and persistedDashboard would be the same, do no pass persistedDashboard to save some extra loading down the line.
JIRA: RAIL-4438
---
--- …
=> RELATED: RAIL-4438 prevent passing redundant persisted dashboard

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescriptionConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiDescriptionConfig.tsx
When description config changed to None or Inherit, the previous custom value should be discarded.
Same for KPI.
JIRA: TNT-1180
---
--- …
=> BUGFIX: TNT-1180 Discard custom description when config changed

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
We need to take insights in drill to insight into account as well.
JIRA: RAIL-4438
---
--- …
=> RELATED: RAIL-4438 fix loadInsightsForPersistedDashboard

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDisplayFormConfiguration.ts
The displayFormChanged was detected incorrectly and the logic was unnecessarily complex.
JIRA: RAIL-4626
---
--- …
=> RELATED: RAIL-4626 fix display form switching

libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/SaveAsDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/topBar/DefaultTopBar.tsx
- RAIL-4658 - fix status indicator tooltip text for new dashboards
- RAIL-4662 - fix save as using the old filters instead of the current ones
---
--- …
=> RELATED: RAIL-4658, RAIL-4662 fix save as filters and status indicator tooltip

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/dateDatasets/getRecommendedCatalogDateDataset.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useDateFilterConfigurationHandling.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx
Only automatically open the picker if a non-recommended was preselected.
JIRA: RAIL-4663
---
--- …
=> RELATED: RAIL-4663 fix KPI dataset picker

libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetAlertCount.ts
Do not call alert count query for KPIs with temporary identity. Non-persisted KPIs never have any alerts, so return 0 right away.
JIRA: RAIL-4664
---
--- …
=> RELATED: RAIL-4664 prevent Bad Request

libs/sdk-ui-dashboard/src/presentation/layout/DashboardItemOverlay/DashboardItemOverlayController.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
This would make the DashboardLayout unusable outside of Dashboard component context, which we need to do for legacy edit mode.
JIRA: RAIL-4437
---
--- …
=> RELATED: RAIL-4437 avoid redux use in DashboardLayout

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionInsightListItemDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useDateFilterConfigurationHandling.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useIsSelectedDatasetHidden.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx
* Make sure it does not crash if user enables it for insight with no related datasets
* Fix preselecting date dataset for the first insight added to an empty dashboard
* Remove commented-out code
---
---
-   [ ] …
=> RELATED: RAIL-4659 fix date dataset config

libs/sdk-ui-dashboard/src/model/commandHandlers/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetInsightHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/loadInsight.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/refreshInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/changeInsightWidgetInsightHandler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/changeInsightWidgetInsightHandler.test.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts
Implement the command to change the insight for an existing insight widget.
It replaces the insight with the freshly loaded value of the insight, changes its title if appropriate and optionally sets the visualization properties. It also forces refresh of the insight list.
JIRA: RAIL-4657
---
--- …
=> RELATED: RAIL-4657 implement change widget insight command

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel.tsx
Show a toast message when a drill is changed or created.
JIRA: RAIL-4668
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#h …
=> RELATED: RAIL-4668 confirm drill changes

libs/sdk-ui-dashboard/src/_staging/dateDatasets/getRecommendedCatalogDateDataset.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx
There was a problem with he logic (extra !) and the relevance was not passed to the recommendation logic properly.
JIRA: RAIL-4663
---
--- …
=> RELATED: RAIL-4663 fix KPI date dropdown

libs/sdk-ui-loaders/api/sdk-ui-loaders.api.md, libs/sdk-ui-loaders/src/dashboard/useDashboardLoaderWithPluginManipulation.ts, tools/dashboard-plugin-template/src/harness/PluginLoader.tsx, tools/dashboard-plugin-template/src/harness/PluginToolbar.tsx
Added toolbar button for hide all overlays for widgets and sections, that was changed or added by plugin
Functions hidePluginsOverlays for hide all overlays
JIRA: RAIL-4437
---
--- …
=> FEATURE: RAIL-4437 indicate that an items are added by a widget in edit mode

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx
Do not close the config bubble when clicking on the widget it is related to: this is how gdc-dashboards behave and its tests rely on it.
JIRA: RAIL-4653
---
--- …
=> RELATED: RAIL-4653 fix config closing

tools/dashboard-plugin-template/src/harness/PluginToolbar.tsx
Change tooltips texts for plugin toolbar
JIRA: RAIL-4437
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if- …
=> FEATURE: RAIL-4437 change tooltips in plugin toolbar

libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-dashboard/styles/scss/resizing.scss
fix: height resizer specific styles for SDK dashboard
JIRA: RAIL-4651
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how- …
=> RELATED: RAIL-4651 Missing resizer bar for widgets at the top/between position

libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
Disable both Save and Save as buttons when the dashboard is empty.
JIRA: RAIL-4684
---
--- …
=> RELATED: RAIL-4684 disable save for empty dashboard

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidgetHeader.tsx, libs/sdk-ui-dashboard/styles/scss/kpi.scss
Also remove no longer needed CSS workaround.
JIRA: RAIL-4679
---
--- …
=> RELATED: RAIL-4679 make insight widget title editable

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx
fix: don't use DND context in layout component
JIRA: RAIL-4660
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-te …
=> RELATED: RAIL-4660 don't use DND context in layout component

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/render/tests/renderingWorker.test.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CreatableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
This is enforced on both the UI and in the command handlers.
Also try to stabilize a problematic unit test.
---
--- …
=> RELATED: RAIL-4682 enforce max attribute filter count

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetPicker.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/utils.ts
Similar to what we do in the picker itself, we need to strip the "Date ()" wrapper in the warning message about the no longer related date dataset.
JIRA: RAIL-4690
---
--- …
=> RELATED: RAIL-4690 strip Date wrapper in warning

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/SettingWidget/StylingSettingWidget/StylingSettingWidget.tsx, libs/sdk-ui-kit/src/SettingWidget/tests/StylingSettingWidget.test.tsx
- Adding props to control disabled buttons color palette dialog
JIRA: SD-2507
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing …
=> FEATURE: SD-2507 - Change layout of Visualization color palette screen

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/interfaces.ts, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout.test.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayout.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutItemRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutMocks.ts, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutRowRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutSectionBorder.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutSectionBorderMarker.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutSectionHeader.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutSectionRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutTypes.ts, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/DashboardEditLayoutWidgetRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/test/useInKD/DashboardEditLayout/LayoutTypes.ts
test: check if layout haven't unwanted dependencies
- test if layout component render works without dashboard context
- should prevent problems in KD old edit mode
JIRA: RAIL-4660
---
--- …
=> RELATED: RAIL-4660 Empty section behavior when dragging

libs/sdk-ui-dashboard/styles/scss/resizing.scss
fix: resize overlay styles
RAIL-4654
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-need …
=> RELATED: RAIL-4654 Missing overlay during resize widget height/ width

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/filterContext.ts, libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/moveAttributeFilterHandler.test.ts.snap, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
- Fix indexing and manipulation of attributes filters in reducer
- Fix fromBackend conversion of date filter
JIRA: RAIL-4675
---
--- …
=> RELATED: RAIL-4675 fix indexing and manipulation of attributes filters in reducer

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/executionResults.ts, libs/sdk-ui-dashboard/src/model/react/useWidgetExecutionsHandler.ts, libs/sdk-ui-dashboard/src/model/store/executionResults/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfigurationItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useIsFilterNotApplied.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/EditModeDashboardKpi/EditModeDashboardKpi.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiExecutor.tsx
Similar to gdc-dashboards, when a widget has an execution warning for some of its filters, show an error message in the filter configuration for those filters.
JIRA: RAIL-4693
---
--- …
=> RELATED: RAIL-4693 use execution warnings in filter config

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx
Improve cache hits so that date datasets are not reloaded unnecessarily.
JIRA: RAIL-4695
---
--- …
=> RELATED: RAIL-4695 improve insight date dataset picker

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigList.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/ScrollablePanel/ScrollableItem.tsx, libs/sdk-ui-kit/src/ScrollablePanel/index.ts
- fix InsightDrillConfigList
- add ScrollableItem to sd-ui-kit
JIRA: RAIL-4683
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributin …
=> RELATED: RAIL-4650 Scroll to bottom after selecting interaction

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx
Always provide default value of hideTitle configuration as it is mandatory on Bear
JIRA: TNT-1174
---
--- …
=> BUGFIX: TNT-1174 HideTitle is mandatory on Bear

libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/SaveAsDialogRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/test/SaveAsDialogRenderer.test.tsx, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/useSaveAs.ts
In View mode, the original filter values need to be used when saving as, in Edit mode, the current filter values need to be used instead.
JIRA: RAIL-4698
---
--- …
=> RELATED: RAIL-4698 fix save as behavior

common/config/rush/pnpm-lock.yaml, examples/playground/.babelrc, examples/sdk-examples/package.json, libs/sdk-ui-tests-e2e/package.json
This is to avoid security advisory on this package. As a prerequisite, styled-jsx was upgraded as well as the old version depended on an insecure loader-utils version and could not be upgraded in-place (they did not use caret).
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-t …
=> RELATED: FET-1168 upgrade loader-utils

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useAttributesWithDisplayForms.ts
We need to only allow the attributes that can show in the drill intersection to configure the drill, not all the attributes.
JIRA: RAIL-4680
---
--- …
=> RELATED: RAIL-4680 fix available attributes in Drill to URL

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx
In new KD edit mode, open configuration of insight panel, when its content is long (e.g there are many attribute filters), will have 2 vertical scroll bar there
JIRA: RAIL-4691
---
--- …
=> BUGFIX: RAIL-4691 show 2 scroll bars in configuration of insight panel

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useInsightListItemDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionInsightListItemDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/useNewSectionKpiPlaceholderDropHandler.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useDateDatasetFilter.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx
Insights should also automatically open the dataset picker if there is no recommended dataset preselected.
Also extract common logic into a hook.
JIRA: RAIL-4697
---
--- …
=> RELATED: RAIL-4697 auto open dataset picker for insights

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx, libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
This is important for GeoChart that freezes its viewport in edit mode.
JIRA: RAIL-4699
---
--- …
=> RELATED: RAIL-4699 propagate isInEditMode to plug vis config

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDisplayFormConfiguration.ts
Show a loading spinner while switching display form, before it used to show old display form elements while switching.
JIRA: RAIL-4672
---
--- …
=> RELATED: RAIL-4672 handle df switching loading

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
Extend backend capabilities related to dashboard permissions. Move dashboard permissions FF to feature hub logic.
JIRA: TNT-1185
---
--- …
=> FEATURE: TNT-1185 Extend capabilities and FF for dashboard permissions

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts
feat: re-generate the backend api to get the user entity
JIRA: SD-2538
---
--- …
=> FEATURE: SD-2538 - Update the sdk-backend-tiger to get the user entity data

libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
fix: disable drag for custom widgets
JIRA: RAIL-4661
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-p …
=> BUGFIX: RAIL-4661 disable drag for custom widgets

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/mergeDateFilterConfigs.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/onDateFilterConfigValidationError.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DateFilterConfigWarnings.tsx
Some of the warnings are only useful when creating a new dashboard. Also fix propagation of the warnings from merging of workspace and dashboard configs (previously the store was not updated properly).
JIRA: RAIL-4676
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits …
=> RELATED: RAIL-4676 fix date filter config warnings

libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrills.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drillTargets/addDrillTargetsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts
In edit mode, when a widget changes its drill targets, we need to run the drill validation again in case some of the drills set on the widget are no longer valid and remove them.
JIRA: RAIL-4713, RAIL-4714
---
--- …
=> RELATED: RAIL-4713, RAIL-4714 validate drills in edit mode

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
When used from InsightView, the props.insight can be undefined, which then triggers an invariant in insightSetProperties.
JIRA: RAIL-4702
---
--- …
=> RELATED: RAIL-4702 prevent invariants in InsightRenderer

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetVisConfigurationHandler.ts, libs/sdk-ui-dashboard/src/model/events/insight.ts, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListCore.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListItemWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/description/DescriptionClickTrigger.tsx, libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx, libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiDescriptionTrigger.tsx
Event on tooltip open from View mode and from InsightList Events for Edit mode changes
JIRA: TNT-1140
---
--- …
=> FEATURE: TNT-1140 Telemetry for descriptions usage

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useAttributesWithDisplayForms.ts
The additional restriction by drill targets was wrong, the incoming attributes are already limited correctly.
JIRA: RAIL-4717
---
--- …
=> RELATED: RAIL-4717 fix attributes in drill to URL

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
=> RELATED: RAIL-4726 z-Index of dashboard header for old plugins

libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiDescriptionTrigger.tsx
Change default value of telemetry payload to match it with default behavior when description config is missing.
JIRA: TNT-1249
---
--- …
=> BUGFIX: TNT-1249 Swap default value to cover undefined config

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
When you change the widget ignored dashboard filters, the widget filters (and the widget) now reloads correctly.
JIRA: RAIL-4728
---
--- …
=> BUGFIX: RAIL-4728 Reload widget on ignored filters change

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/Resize/WidthResizerHotspot.tsx
fix: width resizing behavior
- prevent resizer rerender, which changes DND behavior
- move class sdk-edit-mode-on to root (now is usable in drag layer)
JIRA: RAIL-4708
---
--- …
=> RELATED: RAIL-4708 fix width resizing behavior

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrillToCustomUrlParams.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrills.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drillTargets/addDrillTargetsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillsForInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/removeDrillsForInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DrillValidationToastMessages.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/getMappedConfigForWidget.ts
Validation of Custom URL parameters needs to happen differently: invalid parameters is not grounds for removing the drill.
Also:
* indicate the wrong interaction on the UI
* re-validate the drills when drills change or are removed to hide the warnings once the are no longer relevant
---
--- …
=> RELATED: RAIL-4734 fix custom URL drill validation

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/WidgetIdParameterDetail.tsx
fix: hide temp widget id in custom URL dialog
JIRA: RAIL-4724
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tel …
=> RELATED: RAIL-4724 hide temp widget id in custom URL dialog

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts
We need to explicitly pass the id type so that even when strict ids are in effect, we can use the objRefMaps correctly.
JIRA: RAIL-4734
---
--- …
=> RELATED: RAIL-4734 fix drill validation on tiger

libs/sdk-ui-dashboard/src/model/commandHandlers/common/isDisplayFormRelevantToDrill.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrillToCustomUrlParams.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/tests/InsightDrillDefinitionUtils.test.ts
We also need to validate that the hyperlink display form is a valid drill target.
JIRA: RAIL-4713
---
--- …
=> RELATED: RAIL-4713 validate drill to attr URL properly

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts
Plugin reload can cause the insights collection to be missing some insights that were on the original dashboard. So when cancelling, we need to make sure that we have all the insights needed for the dashboard state we are resetting to.
The resolution uses the caches so for 99% of the cases it should be instantaneous.
JIRA: RAIL-4738
---
--- …
=> RELATED: RAIL-4738 fix dashboard cancel with plugin reload

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
This would open a loophole allowing users to save dashboards with empty layout which we do not allow for dashboards without plugins.
Both Save and Save as buttons were handled by the change.
Also fixed the useMemo dependencies in `useDefaultMenuItems` and improved the memoization there.
JIRA: RAIL-4737
---
--- …
=> RELATED: RAIL-4737 prevent saving dashboard with only custom widgets

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveAsButton/DefaultSaveAsNewButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
Also prevent redundant separator in the menuButton menu (on tiger view mode neither of the export, schedule email and delete buttons is visible).
JIRA: RAIL-4735
---
--- …
=> RELATED: RAIL-4735 do not show Save as button in readonly mode

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DefaultDashboardInsightMenuTitle.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/insightConfiguration.scss
* fix CSS issues with filter config, KPI config and textareas
* add original insight title to the insight menu header in edit mode (and remove irrelevant styles for it)
---
--- …
=> RELATED: RAIL-4736 minor style fixes

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/componentDefinition/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/CreationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DashboardSidebar.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightList.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListCore.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListItemWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/SidebarConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/types.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/DraggableCreatePanelItem.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/WrapCreatePanelItemWithDrag.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/WrapInsightListItemWithDrag.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilterCreatePanelItem.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/DraggableInsightListItem.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/DraggableKpiCreatePanelItem.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CreatableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/index.ts, libs/sdk-ui-dashboard/src/presentation/insightList/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/CreatableKpi.tsx
- There is a dashboard package, that is bundled with KD.
- There is a dashboard package, that is bundled with plugins.
- In KD, it's necessary to customize/override particular default dashboard components and it's importing the default components from the package, that is bundled with KD.
- This was causing issues with React contexts, because components, imported in KD have an access to the React context bundled with KD only, but they need an access to the React context bundled with plugin.
- Now all components that access the React context are passed through props so they all come from the same package. Either from the one that comes with the KD or the one that comes with the plugin.
- Problematic were react-dnd and dashboard components context.
JIRA: RAIL-4739
--- …
=> BUGFIX: RAIL-4739 React contexts in plugins

libs/sdk-ui-dashboard/src/_staging/listedDashboard/listedDashboardUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/index.ts, libs/sdk-ui-dashboard/src/model/store/listedDashboards/index.ts, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx
- set view mode after SaveAS
- add new dashboard to listedDashboards
- add new dashboard to accessibleDashboards
- fix createdBy in saveAs dashboard
JIRA: RAIL-4750
---
--- …
=> RELATED: RAIL-4750 set view mode after SaveAS

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeaderRenderer.tsx
Disable editing of the section, that was added
or modified by the plugin.
JIRA: RAIL-4732
---
--- …
=> BUGFIX: RAIL-4732 Plugin section editing

libs/sdk-ui-loaders/src/dashboard/useDashboardLoaderWithPluginManipulation.ts
Make sure the reload/loading mode switch/extra plugins setting happens even when there are no changes to the dashboard since the last of these actions happened previously.
JIRA: RAIL-4762
---
---
-   [ ] review …
=> RELATED: RAIL-4762 fix useDashboardLoaderWithPluginManipulation

libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx
=> RELATED: RAIL-4750 temporarily revert redirect to edit mode when saveAs

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/drills.ts, libs/sdk-backend-bear/src/convertors/fromBackend/ObjRefConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/ObjRefConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ObjRefConverter.ts, libs/sdk-ui-dashboard/src/model/store/drillTargets/drillTargetsEntityAdapter.ts, libs/sdk-ui-dashboard/src/model/utils/objRef.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/AttributeUrlSection.tsx, libs/sdk-ui-dashboard/src/tools/InsightWidgetBuilder.ts, tools/reference-workspace/src/md/ext.ts
In new KD edit mode, place an insight has at least 1 metric and 1 hyperlink attribute to KD. Try to set up D2U from a metric to the hyperlink attribute (don’t use custom url dialog), press save the dashboard
+ use factories where is it possible
JIRA: RAIL-4758
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/d …
=> BUGFIX: RAIL-4758 Can't save a dashboard with D2U to a hyperlink attribute

libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/drillDialog.scss, libs/sdk-ui-dashboard/styles/scss/drillSelect.scss, libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-dashboard/styles/scss/kpi_alert_dialog.scss, libs/sdk-ui-dashboard/styles/scss/layout.scss, libs/sdk-ui-dashboard/styles/scss/resizing.scss, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss, libs/sdk-ui-dashboard/styles/scss/toolbar.scss, libs/sdk-ui-dashboard/styles/scss/topBar.scss
When a dashboard has many widgets, it shows a vertical scroll bar → observe plugin toolbar in bottom-right side:
It is hidden behind dashboard widgets, we need to roll to the end of the dashboard to see it
When we hover on the icons of the toolbar, this is difficult to select, because height resizer of the widget is activated in this case
JIRA: RAIL-4719
---
--- …
=> BUGFIX: RAIL-4719 plugin toolbar is hidden behind widgets and difficult to select

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts, libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveButton/DefaultSaveButton.tsx
Makes the "save dashboard" and "switch to view mode" operations atomic: we always do those two together. Doing it like this makes reacting to the saved events easier as the dashboard is in view mode by the time the event is fired.
JIRA: RAIL-4703
Related commit in gdc-dashboards: https://github.com/no23reason/gdc-dashboards/commit/5db29c50af12f8b1be5741af3b5b5e917bbb3d4b
---
---
-   [ ] …
=> RELATED: RAIL-4703 switch to view mode on save and save as

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetInsightHandler.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutUtils.ts, libs/sdk-ui-dashboard/src/model/store/layout/tests/layoutUtils.test.ts
In new KD edit mode, after changing widget type from AD overlay → the widget height in KD canvas isn’t recalculated to adapt new chart type
JIRA: RAIL-4746
---
--- …
=> BUGFIX: RAIL-4746 widget height isn't reevaluated after changing widget

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeaderRenderer.tsx
In edit mode, disable editing title/description of the sections, that were inserted by the plugin.
JIRA: RAIL-4732
---
--- …
=> BUGFIX: RAIL-4732 Sections editing

libs/sdk-ui-loaders/src/dashboard/useDashboardLoader.ts
This will force the reload of the whole dashboard when the loadingMode is changed.
JIRA: RAIL-4771
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/mas …
=> RELATED: RAIL-4771 react to loadingMode change

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/insightReferences.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/insightReferences.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts, libs/sdk-ui-dashboard/src/model/store/layout/tests/__snapshots__/layoutReducers.test.ts.snap, libs/sdk-ui-dashboard/src/model/tests/fixtures/SimpleDashboard.fixtures.ts
Can't apply D2I after saving dashboard
Can't save dashboard after setup D2D
JIRA: RAIL-4770, RAIL-4769
---
--- …
=> BUGFIX: RAIL-4770, RAIL-4769 drill save bug repair

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/deleteDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/saveAsDashboardHandler.test.ts
Turns out the setContext effect does not overwrite the value globally, instead, it sets it only for the given saga and its children. The only way to change the value globally is to mutate the context object itself.
JIRA: RAIL-4772
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-shoul …
=> RELATED: RAIL-4772 fix saga context updating

libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/styles/scss/export.scss
Ensure that custom widgets height in export mode
is equal to the grid height and the custom widgets are properly stretched,
otherwise, they may be rendered with the wrong height, or not at all.
JIRA: RAIL-4765
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-li …
=> BUGFIX: RAIL-4765 Custom widgets export

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commands/layout.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts, libs/sdk-ui-dashboard/src/plugins/engine.ts, libs/sdk-ui-dashboard/src/presentation/layout/DashboardItemOverlay/DashboardItemOverlayController.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx, libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx, libs/sdk-ui-loaders/src/dashboard/useDashboardLoaderWithPluginManipulation.ts
In plugin harness, click “hide overlay” in each custom widget “hide overlays” button in plugin toolbar, now widgets added customized by the plugin will shown without overlay. Change anythings in the dashboard and press “reload” button in the plugin toolbar
Actual: The custom widgets are backed to overlay state 
Expected: They should keep selected state
JIRA: RAIL-4729
---
---
-   [ ] …
=> BUGFIX: RAIL-4729 Hide overlay should be kept its state

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/validation/filterDisplayFormValidation.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
Handle both types of ObjRefs in case the user uses idRef and backend uses uriRef or vice versa.
JIRA: RAIL-4774
---
--- …
=> RELATED: RAIL-4774 fix filter-related ObjRef matching

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/model/types/layoutTypes.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/Resize/HeightResizerHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutItemRenderer.tsx
fix: disable widget drop-zone for custom widget
JIRA: RAIL-4741
---
--- …
=> RELATED: RAIL-4741 - disable widget dropzones for custom widget

libs/sdk-ui-loaders/src/dashboard/useDashboardLoaderWithPluginManipulation.ts
=> BUGFIX: RAIL-4729 reset widgets overlay state on loading mode changed

libs/api-model-bear/api/api-model-bear.api.md, libs/api-model-bear/src/visualizationObject/GdcVisualizationObject.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/AttributeConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/AttributeConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/AttributeConverter.test.ts.snap, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/attribute/factory.ts, libs/sdk-model/src/execution/attribute/index.ts, libs/sdk-model/src/index.ts
Jira: TNT-1268
There is a new feature being developed on Tiger backend - showing all attribute values (elements) in the execution result even if there are no (fact) data bound to that particular value. 
This change is to allow the AD user to choose "show all values" on an attribute, persist it on Tiger backend, and to construct the execution request as defined in TNT-1268.
---
---
-   [ ] …
=>  FEATURE: TNT-1268 Allow showing all attribute values in execution and persisting in MD

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx, libs/sdk-ui-dashboard/styles/scss/export.scss
When a KPI without comparison is in one row in dashboard only with other KPIs and all have their default heights, PDF export with theming is corrupted as the height of the smaller KPI is not 100%. Overriding display block by flex fixes this case.
JIRA TNT-1175
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/d …
=> BUGFIX: TNT-1175 Fix KPI height in PDF exports

.github/pull_request_template.md
=> RELATED: RAIL-4767 update readme for e2e cypress tests

libs/sdk-ui-ext/src/internal/utils/colors.ts, libs/sdk-ui-ext/src/internal/utils/tests/colors.test.ts, libs/sdk-ui-vis-commons/src/coloring/color.ts
To support color mapping on location attribute
of Geo chart on Tiger add comparison
with identifier too
JIRA: TNT-1298
---
| `extended test - backstop`                            | …
=> BUGFIX: TNT-1298 Support attribute color mapping by identifier

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/__snapshots__/PluggableGeoPushpinChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts, libs/sdk-ui-tests/tests/api-regression/geo/geoPushpin.test.tsx
Don't generate virtual buckets if location empty
JIRA: TNT-1302
--- …
=> BUGFIX: TNT-1302 Handle empty Location

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/__snapshots__/PluggableGeoPushpinChart.test.tsx.snap
To support range filter and other features
referencing attribute item by localIdentifier
we keep original id in created bucket.
JIRA: TNT-1300
--- …
=> BUGFIX: TNT-1300 Keep original local id in Latitude bucket

libs/sdk-ui-geo/api/sdk-ui-geo.api.md, libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx
Handle internal Mapbox token error by propagating it out.
Handle it by same error msg as missing token.
Re-render map if mapbox token changed.
JIRA: TNT-1296
--- …
=> FEATURE: TNT-1296 Handle internal Mapbox error

libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
FE apps is stuck in loading when connection to FeatureHub
got timeout
JIRA: RAIL-4798
--- …
=> BUGFIX: RAIL-4798 frontend apps is stuck in loading

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/GraphConverter.ts
Graph API offers a "cheaper" option to get referencing objects. It also bypasses user object permissions so in cases where just basic object information is required it is advisable to use it.
JIRA: TNT-1186
---
| `extended check plugins`                              | Dashboard plugins tests …
=> FEATURE: TNT-1186 Use graph API to get insight referencing objects

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/GranteeMock.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/useShareDialogBase.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/useShareDialogBase.ts
When user does some permissions changes and navigates to add dialog, we need to store the previous changes and apply them if he navigates back.
JIRA: TNT-1322
--- …
=> BUGFIX: TNT-1322 Granular permissions share dialog logic

libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/settings/index.ts, libs/sdk-backend-tiger/src/backend/settings/settings.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Adapt implementation of the workspace settings in SDK to reflect changes introduced by
https://gooddata.atlassian.net/browse/NAS-4638 (adding type).
JIRA: RAIL-4809
---
| `extended …
=> FEATURE: RAIL-4809 adapt to changes in workspace settings

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightFilters.tsx
fix: disables date filter option
- disables date filter  when insight has only metric with date filter
JIRA: RAIL-4806
---
| `extended test - backstop`                            | …
=> RELATED: RAIL-4806 Disables date filter option if visualization has only metric with date filter

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
=> FEATURE: MPNT-263 Export register upload notification API

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
fix: switch of widget DateDataset to edit mode
- when dateDataset is changed widget query is executed
JIRA: RAIL-4815
---
| `extended test - backstop`                            | …
=> RELATED: RAIL-4815 Manipulation of Widget DateDataset in Edit mode

libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/AttributeUrlSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/AttributeUrlSectionItem.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useAttributesWithDisplayForms.ts
fix: drill to attribute on measure
- use proper attribute displayFormRef
- improve AttributeUrlSection API
JIRA: RAIL-4816
--- …
=> RELATED: RAIL-4816 drill to attribute on measure

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/useDrillValidationMessages.tsx
This issue come from e2e test "fails to dill and shows error message, shows warning in edit mode" in drillToCustomUrl.spec
JIRA: RAIL-4803
--- …
=> FEATURE: RAIL-4803 missing warning when Drill to custom URL

libs/sdk-ui-charts/src/highcharts/chartTypes/_util/test/color.test.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/colors/coloredItemsList/ColoredItem.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/colors/tests/ColorsSection.test.tsx, libs/sdk-ui-vis-commons/src/coloring/color.ts
=> BUGFIX: TNT-1327 Color configuration for attribute empty values in outer join

libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrills.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drillTargets/test/addDrillTargetsHandler.test.ts
fix: don't show drill warning when execution fails
JIRA: RAIL-4811
--- …
=> RELATED: RAIL-4811 When widget execution failed do not show warning about removing invalid drills

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useEditableInsightMenu.ts
fix: interactions visibility only by drill config
JIRA: RAIL-4810
--- …
=> RELATED: RAIL-4810 Hide widget interaction config menu item when Execution request error

libs/sdk-backend-tiger/src/backend/features/state.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/features/test/state.test.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts
We need to support true/false values in SDK
JIRA: NAS-4761
--- …
=> FEATURE: NAS-4761 tiger ff - enable/disable + True/False

libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
When save as new is shown as a standalone button
in top bar, we need to hide the one which might
be shown in dropdown menu.
JIRA: TNT-1351
--- …
=> BUGFIX: TNT-1351 Hide save as new button in menu

common/scripts/ci/run_unit_tests.sh, libs/sdk-ui-tests/backstop/run-backstop.sh
=> RELATED: TNT-1354 Cleanup docker network on exit in tests

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts
In view mode, change filter of A (select/unselect) → now B and C are refreshed to All value (correct behavior). Then switch to edit mode → observe attribute filters
=Actual: A, B and C are loaded All value
=Expected: Attribute filters should be refreshed to original state which persisted in MD: A is all value. B and C have value different than All
JIRA: RAIL-4832
---
| `extended check sonar` …
=> BUGFIX: RAIL-4832 dependent filter isn't refreshed to original state

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/useDateDatasetFilter.ts
Open configuration widget first time always expand Date dropdown list automatically
KD with new edit mode, In KD when opening configuration widget of some insight for the first time, it always expands Date dropdown list automatically. This is just a minor issue for user but currently it is causing an issue for the automation tests for toggling other attribute because this attribute is covered by the Date dropdown list.
JIRA: RAIL-4817
---
| `ok to test`                                          | Re-run standard checks …
=> BUGFIX: RAIL-4817 always expand Date dropdown list automatically

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, tools/dashboard-plugin-template/package.json, tools/plugin-toolkit/src/initCmd/index.ts
- Make selectIsExport selector public
- Add override for reselect version in the plugin template to fix selector typing errors
JIRA: RAIL-4837
--- …
=> BUGFIX: RAIL-4837 Allow export handling in the dashboard plugins

libs/sdk-ui-tests-e2e/cypress/support/commands/login.ts
Now when api token is not hardcoded in the docker image with scenarios,
pass it from the test runner correctly.
---
| `extended test - backstop`                            | …
=> RELATED: TNT-1369 e2e tests: login with api token for recordings

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDropdown.tsx
In new KD edit mode, after drop an insight to KD canvas,
then open insight configuration
=Actual: in the first time, date dropdown list is
automatically opened, but the insight configuration panel isn’t rolled to the date dropdown button,
therefore the date dropdown list is separated from the panel. The issue just happens in the first time after opening the insight configuration
JIRA: RAIL-4840
---
| `extended …
=> BUGFIX: RAIL-4840 date picker dropdown is ugly when opening first time

common/scripts/ci/run_cypress_integrated_tests.sh, common/scripts/ci/run_cypress_isolated_tests.sh, common/scripts/ci/run_cypress_recording.sh
=> RELATED: QA-17917 build docker for isolated/integrated with --no-cache

libs/sdk-ui-dashboard/src/_staging/sharedHooks/useAttributes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/utils.ts
Attributes marked as deprecated are not part of the catalog. Need to also obtain this deprecated objects to make right comparison.
JIRA: TNT-1350
--- …
=> BUGFIX: TNT-1350 Allow to find deprecated attributes

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/selectors.ts
=> BUGFIX: TNT-1385 Fix Edit button of dashboard with dashboard permissions disabled, TNT-1384 Preserve sharing status when a dashboard is updated

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/filters.ts, libs/sdk-ui-dashboard/src/model/events/index.ts, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useTitleConfiguration.ts
Setup Attribute Filter renaming telemetry tracking events, which will be used on https://github.com/gooddata/gdc-dashboards/pull/5560
JIRA: TNT-1292
--- …
=> FEATURE: TNT-1292 Attr filter renaming telemetry

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/DefaultButtonBar.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/types.ts
feat: add one more property for the ButtonBar component
one property was added to position the children's content for the ButtonBar component
JIRA: SD-2625
---
| `extended …
=> FEATURE: SD-2625 - update the SDK Dashboard to add the embed button on KD

libs/sdk-ui-ext/src/internal/components/dialogs/embedInsightDialog/EmbedInsightDialog.tsx, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/getWebComponentsCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/tests/__snapshots__/getWebComponentsCodeGenerator.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/tests/getWebComponentsCodeGenerator.test.ts
fix: some issues in the Embed Insight Dialog
_ update the web components code snippet
_ always have default height for the web components
_ disable code area for the definition code snippet
JIRA: SD-2639, SD-2641
---
| `extended check plugins`                                | Dashboard …
=> BUGFIX: SD-2639, SD-2641 - fix some issues in the Embed Insight Dialog

libs/sdk-backend-base/src/normalizingBackend/normalizer.ts, libs/sdk-backend-bear/src/backend/workspace/execution/preparedExecution.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/FilterConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/FilterConverter.test.ts, libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap, libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/toAfmResultSpec.test.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/toAfmResultSpec.test.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts
Dont remove None (positive with empty selection) filter from execution definition.
Dont send it to execution but instead throw No data error
--- …
=> FEATURE: TNT-1406 None filter handling

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh
=> FEATURE: QA-14916 PoC add rush command into run script

libs/sdk-backend-bear/src/backend/workspace/measures/measureExpressionTokens.ts, libs/sdk-backend-bear/src/backend/workspace/measures/test/measureExpressionTokens.test.ts, libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts, libs/sdk-backend-tiger/src/backend/workspace/measures/test/measureExpressionTokens.test.ts
the quoted_text pattern just support double-quoted after the backslash, but the MAQL have a case to support single-quoted after backslash, so we need add more condition to the pattern to support this case
JIRA: TNT-1227
---
| `extended test - backstop`                              | …
=> BUGFIX: MPNT-329 - support single quoted after backslash for quoted_text

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultKpiConfigurationPanel/KpiWidgetDateDatasetFilter.tsx
When date filter checkbox in KPI is clicked
right after initialization, it is not persisted.
This fix avoids calling "enableCheckbox"
right after "disableCheckbox" in such cases.
JIRA: RAIL-4894
--- …
=> BUGFIX: RAIL-4894 KPI date filter initial checkbox behaviour

common/changes/@gooddata/sdk-ui-all/dedo-sd-2656_2023-04-06-14-31.json, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts
Also, we should add the type of settings to filter data, because some settings has dynamic id
JIRA: SD-2656
--- …
=> FEATURE: SD-2656 adding apis to config date format, timezone for Org.

common/changes/@gooddata/sdk-ui-all/IMJ-RAIL-4930_2023-04-25-10-25.json, common/scripts/ci/docker_apidocs_build.sh, common/scripts/ci/docker_examples.sh, common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh, common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh, rush.json
=> RELATED: RAIL-4930 update docker images to respect node version 16.20.0

libs/sdk-ui-pivot/src/impl/structure/headers/ColumnHeader.tsx
When table is sorted, grid is reinitialized
and ag-grid expects dom elements to be in place.
This is not the case unless we refresh headers
before sorting.
JIRA: FET-1056
--- …
=> BUGFIX: FET-1056 Fix ag-grid sorting

common/scripts/ci/run_cypress_integrated_tests.sh, common/scripts/ci/run_cypress_isolated_tests.sh, common/scripts/ci/run_cypress_recording.sh
=> RELATED: FET-1219 set unique project name for docker compose run

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx, libs/sdk-ui-ext/src/internal/components/DisabledBubbleMessage.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/CheckboxControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/DataLabelsControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/tests/CheckboxControl.test.tsx, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/src/locales.ts
Skip leading zeros and invalid values for funnel chart.
Also show enhanced tooltip messages for Percentage setting
and rename it.
--- …
=> RELATED: TNT-1491 TNT-1493 Fix funnel bugs

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
fix: remove default the stackMeasures when
_ the primaryChartType is Area and only has one metric
JIRA: EGL-47
--- …
=> BUGFIX: EGL-47 - show the continuous line for the combo chart has one metric on the primary area chart

libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
They're used for debugging purpose but causing conflict in ci
JIRA: FET-1235
--- …
=> RELATED: FET-1235 remove unused mapping port in docker-compose e2e

libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/components/ToastMessages.tsx
With React 18, toast message ui actions
dispatched by components were racing
with sagas which caused some problems
in tests. After moving these actions
to the sagas, the problem seems fixed.
JIRA: RAIL-4969
--- …
=> BUGFIX: RAIL-4969 Move toast message reset actions to saga

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
- allow to set weekStart setting on tiger metadata on an organization level
- add DefaultWeekStart setting as an default when the setting is not configured
JIRA: CAL-871
=> FEATURE: CAL-871 Support configuration of weekStart on tiger organization

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/features/test/static.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/headerSection.spec.ts, libs/sdk-ui-tests-e2e/cypress/support/featureHub.ts
=> RELATED: RAIL-4970 dashboard does not show edit button when integrated with plugin

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
fix: missing continuous lines for combo chart
should update the stackMeasures in case the continuous line enabled
JIRA: EGL-61
--- …
=> BUGFIX: EGL-61 - missing continuous lines for combo chart on KD and InsightView

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
fix: missing continuous lines for combo chart
should update the stackMeasures in case the continuous line enabled
JIRA: EGL-61
--- …
=> BUGFIX: EGL-61 missing continuous lines for combo chart on KD and InsightView

libs/sdk-ui-tests-e2e/reference_workspace/export_catalog.js
=> RELATED: RAIL-4973 fix e2e tests

common/changes/@gooddata/sdk-ui-all/ach-catalog-export_2023-05-29-15-36.json, examples/playground/scripts/refresh-md.sh, examples/sdk-examples/scripts/refresh-md.sh, libs/sdk-backend-tiger/scripts/refresh-md.sh, libs/sdk-ui-tests-e2e/reference_workspace/export_catalog.js, tools/app-toolkit/scripts/preparePackageJson.ts, tools/catalog-export/src/base/config.ts, tools/catalog-export/src/base/constants.ts, tools/catalog-export/src/base/tests/__mocks__/fs/promises.ts, tools/catalog-export/src/base/tests/__snapshots__/config.test.ts.snap, tools/catalog-export/src/base/tests/config.test.ts, tools/catalog-export/src/base/types.ts, tools/catalog-export/src/index.ts, tools/catalog-export/src/loaders/tiger/index.ts, tools/dashboard-plugin-template/scripts/refresh-md.js, tools/experimental-workspace/bin/refresh-md.sh, tools/live-examples-workspace/bin/refresh-md.sh, tools/react-app-template/.gitignore, tools/react-app-template/README.template.md, tools/react-app-template/configTemplates/js/.env, tools/react-app-template/configTemplates/js/.gdcatalogrc, tools/react-app-template/configTemplates/ts/.env, tools/react-app-template/configTemplates/ts/.gdcatalogrc, tools/react-app-template/package.json, tools/react-app-template/src/App.tsx, tools/react-app-template/src/backend.ts, tools/react-app-template/src/typings.d.ts, tools/react-app-template/webpack.config.js, tools/reference-workspace-mgmt/bin/refresh-md.sh
* Tiger token is now treated same way as bear credentials - it used to be read from .env ad-hoc, right before usage.
* User can't save credentials in config file anymore. Thus, we'll promote saving `.gdcatalogrc` in Git, as it's no longer unsafe.
* All credentials are now loaded from `.env` for both bear and tiger. This is the file that should not go to Git.
* User can now store configs in package.json, under `gooddata` key. This is a convenience feature for boilerplate app setup.
* `--output` is now `--catalog-output` to avoid confusion, since config is used for both catalog export and webpack config in boilerplate app.
---
| …
=> RELATED: RAIL-4900 Config loading breaking changes

libs/sdk-ui-tests-e2e/cypress.config.ts, libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/scripts/run_integrated.js
=> FEATURE: QA-18895 support multiple browsers for daily checklist

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartCapabilities.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartTooltips.ts, libs/sdk-ui-ext/src/internal/components/configurationPanels/WaterfallChartConfigurationPanel.tsx
fix: some issues of the Waterfall chart
_ should have the separate format for each metric
_ the total column tooltip should not have the attribute name _ should enable the label section on Axes configuration when multi metrics
JIRA: EGL-70, EGL-72, EGL-73
--- …
=> BUGFIX: EGL-70, EGL-72, EGL-73 - fix some issues of the waterfall chart

libs/sdk-ui-ext/src/internal/utils/colors.ts, libs/sdk-ui-ext/src/internal/utils/tests/colors.test.ts, libs/sdk-ui-kit/src/Icon/icons/InsightIcons/Waterfall.tsx, libs/sdk-ui-vis-commons/src/coloring/color.ts
fix: can't save the insight when changed the color
update the waterfall icon on Schedule Email dialog
JIRA: EGL-75, EGL-77
--- …
=> BUGFIX: EGL-75, EGL-77 - can't save the insight when changed the color

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/TotalsConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap
=> RELATED: TNT-1537 Fix order of totals and their naming for bear/tiger

libs/sdk-ui-pivot/src/impl/cell/cellClass.ts, libs/sdk-ui-pivot/src/impl/data/dataSource.ts, libs/sdk-ui-pivot/src/impl/gridOptions.ts, libs/sdk-ui-pivot/src/impl/structure/colDefFactory.ts, libs/sdk-ui-pivot/src/impl/structure/colDefHeaderClass.ts, libs/sdk-ui-pivot/src/impl/structure/colDefTemplates.ts, libs/sdk-ui-pivot/src/impl/structure/colLocatorFactory.ts, libs/sdk-ui-pivot/src/impl/structure/headers/ColumnTotalGroupHeader.tsx, libs/sdk-ui-pivot/src/impl/structure/headers/ColumnTotalHeader.tsx, libs/sdk-ui-pivot/src/impl/structure/tableDescriptor.ts, libs/sdk-ui-pivot/src/impl/structure/tableDescriptorFactory.ts, libs/sdk-ui-pivot/src/impl/structure/tableDescriptorTypes.ts, libs/sdk-ui-pivot/src/impl/tableFacade.ts, libs/sdk-ui-pivot/styles/scss/pivotTable.scss, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/index.tsx, libs/sdk-ui/src/base/results/dataAccess.ts, libs/sdk-ui/src/base/results/internal/dataAccessImpl.ts, libs/sdk-ui/src/base/results/internal/utils.ts
=> RELATED: TNT-1506 Pivot Table column totals definition

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/publicTypes.ts
=> BUGFIX: TNT-1550 Menu config submenu option when no column totals

libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideColumnLabels.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/dataLabelsHelpers.ts
When implementing the waterfall chart, I converted the negative values to positive [here](https://github.com/gooddata/gooddata-ui-sdk/commit/75342129e8d63e569a9a0be507b835753c6b01ca#diff-b23585b3caa9ff74b1155ab5dac766fd84228587cca924f7652dfe0d7b6bf435R110): 
It will affect to other charts, this fix is only convert the negative value for waterfall chart.
JIRA: EGL-82
---
| `extended check sonar` …
=> BUGFIX: EGL-82 - Data label of negative value is missed on Column/Combo charts

libs/sdk-ui-pivot/src/impl/structure/colDefTemplates.ts
=> RELATED: TNT-1556 Introduce formatter for total/subtotal cols

libs/sdk-backend-base/src/normalizingBackend/normalizer.ts, libs/sdk-backend-base/src/normalizingBackend/tests/__snapshots__/normalizer.test.ts.snap, libs/sdk-backend-base/src/normalizingBackend/tests/normalizer.test.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
Notify sortItems and totals in one pushData call when sorting changes.
Also, switch tableSortingCheckDisabled to true for tiger
as this is true by default on bear as well.
--- …
=> RELATED: TNT-1560 Notify about sort&totals at once and fix setting

libs/sdk-ui-pivot/src/impl/cell/cellClass.ts, libs/sdk-ui-pivot/src/impl/structure/colDefHeaderClass.ts, libs/sdk-ui-pivot/styles/scss/pivotTable.scss
=> BUGFIX: TNT-1555 Column totals/subtotals styles

libs/sdk-ui-ext/src/internal/components/configurationControls/total/TotalSection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/total/tests/TotalSection.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/WaterfallChartConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/src/locales.ts
feat: update waterfall total section
add the disable tooltip if any total measures
JIRA: EGL-55
--- …
=> FEATURE: EGL-55 - add the disable tooltip message for waterfall total section

libs/sdk-ui-pivot/src/impl/cell/cellClass.ts, libs/sdk-ui-pivot/src/impl/structure/colDefHeaderClass.ts
=> RELATED: TNT-1565 Column totals cypress selectors

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/waterfallChart/PluggableWaterfallChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/waterfallChart/tests/PluggableWaterfallChart.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/waterfallChart/tests/__snapshots__/PluggableWaterfallChart.test.tsx.snap
fix: clear total measures array if only one metric
JIRA: EGL-88
--- …
=> BUGFIX: EGL-88 - clear total measures array if only one metric

libs/sdk-ui-pivot/src/impl/data/rowFactory.ts
it won't cause the error + blank page, otherwise it will just skip the totals information, when there's >1000
JIRA: TNT-1568
--- …
=> BUGFIX: TNT-1568 Grand totals columns big data

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts
Map new totalHeaderItems from columns with correct measureIndex, to display correct title.
Adjust new totals definitions according with measures bucket order.
JIRA: TNT-1570
--- …
=> BUGFIX: TNT-1570 Map new column total headers to correct measure

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartTooltips.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/__snapshots__/chartTooltips.test.ts.snap, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartTooltips.test.ts
fix: waterfall tooltip displays wrong text
JIRA: EGL-103
--- …
=> BUGFIX: EGL-103 - waterfall tooltip displays wrong text

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts
generateLogicalModel now accepts "tables" in "pdm" property
--- …
=> RELATED: CAL-949 update Tiger API client

libs/sdk-ui-pivot/src/impl/base/agUtils.ts, libs/sdk-ui-pivot/src/impl/resizing/columnSizing.ts, libs/sdk-ui-pivot/src/impl/tableFacade.ts
Treat new column totals/subtotals same way as measures when manual resizing.
--- …
=> BUGFIX: TNT-1580 new total columns group resizing

libs/sdk-ui-tests-e2e/reference_workspace/export_catalog.js, libs/sdk-ui-tests-e2e/reference_workspace/lib/create_bear_workspace.js
=> BUGFIX: QA-19096 fixing credentials info shown when export fixture failed

libs/sdk-ui-tests-e2e/reference_workspace/export_catalog.js, libs/sdk-ui-tests-e2e/reference_workspace/lib/create_bear_workspace.js
Passed on my branch: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_bear/353/console
--- …
=> BUGFIX: QA-19096 export catalog reads pass from env variable

libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideColumnLabels.ts
fix: data label auto hide waterfall chart
the dataLabel auto hide when the chart starts with negative value
JIRA: EGL-106
--- …
=> BUGFIX: EGL-106 - the dataLabel auto hide when the chart starts with the negative values

tools/dashboard-plugin-template/.eslintrc.cjs, tools/dashboard-plugin-template/package.json, tools/dashboard-plugin-template/scripts/refresh-md.js, tools/dashboard-plugin-template/webpack.config.cjs, tools/plugin-toolkit/src/initCmd/index.ts
JIRA: RAIL-5022, RAIL-5023
--- …
=> RELATED: RAIL-5022, RAIL-5023 fix build plugin and refresh-md

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts, libs/sdk-backend-tiger/src/index.ts, libs/sdk-backend-tiger/src/utils/jwt.ts, libs/sdk-backend-tiger/src/utils/tests/__snapshots__/jwt.test.ts.snap, libs/sdk-backend-tiger/src/utils/tests/jwt.test.ts, libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/EmbeddedAnalyticalDesigner.ts, libs/sdk-embedding/src/iframe/EmbeddedKpiDashboard.ts
=> FEATURE: TNT-1438 Add JWT authentication support

examples/playground/webpack.config.cjs, examples/sdk-examples/webpack.config.js, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests-e2e/scenarios/webpack.config.cjs, libs/sdk-ui-tests/.storybook/main.cjs, libs/sdk-ui-web-components/webpack.config.cjs, tools/dashboard-plugin-template/webpack.config.cjs, tools/react-app-template/webpack.config.cjs
Add fonts and other assets imported across the packages in css to `package.json` `"exports"` field, so most bundlers are able to handle them out of the box, without additional setup.
Also remove aliases workaround for this,
which is not needed anymore.
JIRA: RAIL-5026
--- …
=> BUGFIX: RAIL-5026 Add assets to exports field

libs/sdk-ui-pivot/src/impl/cell/onCellClick.ts
When metrics are in rows, check whether any of the clicked cells are part of this new table descriptor types.
JIRA: TNT-1609
--- …
=> BUGFIX: TNT-1609 Avoid click method on new measure descriptors.

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-dashboard/src/internal.ts, tools/app-toolkit/package.json, tools/app-toolkit/src/_base/inputHandling/validators.ts, tools/app-toolkit/src/typings.d.ts, tools/plugin-toolkit/package.json, tools/plugin-toolkit/src/_base/inputHandling/validators.ts, tools/plugin-toolkit/src/typings.d.ts, tools/react-app-template/README.template.md, tools/react-app-template/src/index.css, tools/react-app-template/src/index.tsx
A batch of minor fixes for the react-app-template and app-toolkit.
- Add `overflow: auto` to the content of the application, so when the user replaces insight with the dashboard, it still looks ok. (RAIL-4989)
- Add `sdk-ui-kit` styles as they are required by the dashboard. (RAIL-5004)
- Replace hardcoded `npm` in readme with used package manager. (RAIL-4990)
- Improve validation of the npm package name in `plugin-toolkit` and `app-toolkit` with more helpful error messages. (RAIL-5002)
- Reexport also `dashboardFilterConverter` as it
is used in professional services app. (RAIL-5028)
JIRA: RAIL-4989, RAIL-5004, RAIL-4990, RAIL-5002, RAIL-5028
---
| …
=> BUGFIX: RAIL-4989, RAIL-5004, RAIL-4990, RAIL-5002, RAIL-5028 Fix react-app-template

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/utils/dimensions.ts
=> BUGFIX: TNT-1619 Insight view accepts new transposed metrics

examples/playground/src/index.tsx, libs/sdk-ui-charts/src/highcharts/ChartTransformation.tsx, libs/sdk-ui-ext/.dependency-cruiser.cjs, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/index.ts, libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/PluggableUnknownChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx, libs/sdk-ui-ext/src/internal/createRootProvider.ts, libs/sdk-ui-ext/src/internal/index.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-ext/src/internal/utils/domHelper.ts, libs/sdk-ui-pivot/src/CorePivotTable.tsx, libs/sdk-ui-tests-e2e/scenarios/src/App.tsx, libs/sdk-ui-tests-e2e/scenarios/src/index.tsx, libs/sdk-ui-tests/backstop/story-extractor.test.ts, libs/sdk-ui-tests/src/scenario.tsx, libs/sdk-ui-tests/stories/visual-regression/web-components/insightStories.tsx, tools/dashboard-plugin-template/src/harness/index.tsx, tools/react-app-template/src/index.tsx
When createRoot is provided, its API is used for rendering instead of older react render.
JIRA: RAIL-5024
--- …
=> FEATURE: RAIL-5024 Introduce createRoot provider for react 18

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> BUGFIX: SD-2845 - Home UI is loading too slowly for the Workspace that connected with the large LDM

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, tools/catalog-export/package.json, tools/catalog-export/src/exports/metaToJavascript.ts
=> BUGFIX: RAIL-5041 replace require by import in catalog-export

tools/catalog-export/src/base/constants.ts, tools/catalog-export/src/cli/prompts.ts, tools/catalog-export/src/index.ts, tools/catalog-export/src/loaders/bear/index.ts
=> BUGFIX: RAIL-4999 prompt hostname in export catalog

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts
If a new token is set before the previous one expired, another expiration reminder will be started. If the embedding app sends new token automatically based on expiration reminder, token would be set more often then necessary as the previous reminder would ask for token at the time of the previous token expiration while the currently set token is still valid (and its expiration reminder is still waiting to fire).
It must be also possible to set token into the provider without using expiration reminder handler. New public method is available on the auth provider now.
JIRA: TNT-1438
---
| ------------------------------------------------------- | …
=> BUGFIX: TNT-1438 Cancel the previous expiration reminder in JWT auth provider

libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx, libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts, tools/dashboard-plugin-template/README.template.md, tools/dashboard-plugin-template/webpack.config.cjs, tools/plugin-toolkit/src/_base/utils.ts, tools/plugin-toolkit/src/addPluginCmd/actionConfig.ts
SDK v9 builds plugin as ECMAScript module, it needs to be loaded with `type="module"` script attribute. Use `.mjs` extension to distinguish type of the dashboard plugin build.
Reflect these changes in webpack config and plugin-toolkit.
Update dashboard plugin readme, because with `type="module"`, you need to allow CORS from GoodData domain on plugin hosting.
Also improve error reporting when plugin,
engine or entry point load fails.
JIRA: RAIL-5042
---
| `ok to test`                                            | Re-run standard …
=> BUGFIX: RAIL-5042 Dashboard plugins built as ESM

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh
=> RELATED: QA-19500 extracting logs from AIO container in matrix tests

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts
TigerBackend has factory methods that will return new instance of itself recreated with provided parameters. AuthProvider instance is forwarded to the new instance but client is
recreated. Various components keep reference to previous instances of TigerBackend that uses the previous clients instances to make Axios calls. This could be probably bug in some cases.
These clients would not get token updated and if token has expiration, the next API call would fail and application would logout the user from the session. The token auth provider must keep the reference to all these clients to update their tokens if needed.
JIRA: TNT-1438
---
| …
=> BUGFIX: TNT-1438 Keep track of axios instances for JWT auth provider

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, common/scripts/ci/utils.sh, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/boilerapp.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/navigation.ts, libs/sdk-ui-tests-e2e/scripts/backend_bear.template, libs/sdk-ui-tests-e2e/scripts/run_boiler_app.sh
=> FEATURE: QA-18623 PoC automation for new boiler app

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/GrandTotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap
Applies for tiger backend:
- send totals ordered by total function
- skip grand total transformation when measures in rows
--- …
=> RELATED: TNT-1633 Avoid js error with grand totals and measures in rows in tiger

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts
* updateJwt method receives expiration param from AD/KD but did not use it to reconfigure the reminder timeout.
* standard tiger API token auth provider should allow to update token as AD/KD listens for token updates forever now.
JIRA: TNT-1644
--- …
=> BUGFIX: TNT-1644 Add missing param to JWT auth provider, expose API token update function

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh
for backward compatibility tests for tiger BE
JIRA: QA-19574
--- …
=> RELATED: QA-19574 use docker image ECR instead of dockerhub

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/pivotTableAdditionalFactories.ts, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/columnWidths.ts
Applies for table insights without measures where columns still can
be resized.
--- …
=> RELATED: TNT-1664 Do not require measure locators for column widths

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/widthItemsHelpers.ts, libs/sdk-ui-pivot/src/impl/structure/colLocatorFactory.ts, libs/sdk-ui-pivot/src/impl/structure/colLocatorMatching.ts, libs/sdk-ui-pivot/src/impl/structure/tableDescriptorFactory.ts, libs/sdk-ui-pivot/src/impl/structure/tableDescriptorTypes.ts
=> BUGFIX: TNT-1665 Metrics in rows manual resizing column attributes

libs/sdk-backend-bear/src/backend/user/settings.ts, libs/sdk-backend-bear/src/backend/workspace/settings/settings.ts, libs/sdk-backend-bear/src/uiSettings.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/InsightListItem.tsx
Bear has always metadata stored in Prague time zone. Tiger has them 
always stored in UTC. The current insight list code counts with Prague
timezone, i.e., insight creation/update date for Tiger is shifted by
two hours. New hardcoded setting is introduced for both backends to
provide information about metadata timezone. The commit fixes insight
list for KD. The settings must be also applied to the component in AD
to fix it there. 
---
| `ok to test`                                            | Re-run standard checks …
=> BUGFIX: TNT-1667 Display time of insight creation/update in local time on Tiger

docs/content/en/latest/references/visual_components/pivot_table.md, examples/sdk-examples/src/examples/pivotTable/PivotTableManualResizingExample.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/pivotTableAdditionalFactories.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/pivotTableAdditionalFactories.test.ts.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/pivotTableAdditionalFactories.test.ts, libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/columnWidths.ts, libs/sdk-ui-pivot/src/impl/resizing/tests/columnSizing.test.ts, libs/sdk-ui-pivot/src/impl/resizing/tests/updateColDefs.test.ts, libs/sdk-ui-pivot/src/index.ts, libs/sdk-ui-pivot/src/tests/__snapshots__/columnWidths.test.ts.snap, libs/sdk-ui-pivot/src/tests/columnWidths.test.ts, libs/sdk-ui-tests/scenarios/pivotTable/manualSizing.tsx
Update `newWidhtForSelectedColumns` to accept an array of measure so columnmanual resizing works properly on new table transposition.
Also add missing `newTotalColumnLocator` to pivot table factories.
JIRA: TNT-1665
---
| `extended test - backstop`                              | BackstopJS …
=> BUGFIX: TNT-1665 New width selected columns

libs/sdk-ui-pivot/src/impl/data/dataSource.ts
When table only contains column attributes displays one rows which should not be there and it remains on infinite loading state.
JIRA: TNT-1669
--- …
=> BUGFIX: TNT-1669 Dont display rows when there are no measures

libs/sdk-ui-pivot/src/impl/data/dataSource.ts
When table only contains column attributes displays one rows which should not be there and it remains on infinite loading state.
JIRA: TNT-1669
--- …
=> BUGFIX: TNT-1669 Don't display rows when no measures or row attributes present

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts
Regenerate api client and fetch workspace parent
prefixes using this new api.
--- …
=> RELATED: TNT-1670 Generate api client and fetch prefixes

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
- Fix `columnHeadersPosition` property to be updated only after it was changed via config panel.
JIRA: TNT-1685
--- …
=> BUGFIX: TNT-1685 Update columnHeadersPosition only when was updated on config panel

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts, libs/sdk-backend-tiger/src/types/refTypeMapping.ts
=> FEATURE: RAIL-5029 related to add PDM->LDM fields that are planned to be deprecated

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts, libs/sdk-backend-tiger/src/types/refTypeMapping.ts
=> FEATURE: RAIL-5029 related to add PDM->LDM fields

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline2.test.tsx, libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts, libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts
=> BUGFIX: EGL-232 keep dependencies of arithmetic metric in primary bucket

libs/sdk-backend-tiger/tests/integrated/__snapshots__/catalog.test.ts.snap, libs/sdk-backend-tiger/tests/integrated/__snapshots__/insights.test.ts.snap, libs/sdk-backend-tiger/tests/integrated/backend.ts, libs/sdk-backend-tiger/tests/integrated/catalog.test.ts, libs/sdk-backend-tiger/tests/integrated/insights.test.ts
=> FEATURE: QA-19951 UI-SDK tiger-backend sanitize field created

docs/config/public/params.toml, docs/layouts/index.redir
=> CONFIG: bump documentation version to 9.1

libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiExecutor.tsx
Execution done just for Alert is exactly the same as for KPI itself, only omits secondary metric.
It was probably meant as optimization,
but it caused cache miss and
one redundant execution for every KPI.
Even for ones which dont have alert at all.
For evaluation of new/updated alert KPI's execution is enough as they share filters and secondary metric is ignored anyway. JIRA: TNT-1716
---
| `extended check …
=> BUGFIX: TNT-1716 Reuse KPI execution for new alerts

libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideBarLabels.ts, libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideColumnLabels.ts
When filtering by legend values if the bar chart is only stacked by one value it makes whole totals labels disappear.
JIRA: TNT-1738
--- …
=> BUGFIX: TNT-1738 Bar chart totals labels when stacked by one value

libs/sdk-ui-pivot/src/CorePivotTable.tsx, libs/sdk-ui-pivot/src/tableState.ts
=> BUGFIX: TNT-1747 Allow table to render after loading

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/shareDashboardToEveryone.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/permissions.ts
_ add new cypress test for share dashboard to everyone
JIRA: EGL-225
--- …
=> FEATURE: EGL-225 - add cypress test for the share dashboard to everyone

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AccessControlConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts
fix: share everyone should prevent limiting inherited permission
_ regenerate the tiger client API to update the rule permission types 
_ update the inherit permission for the rule
JIRA: EGL-272
--- …
=> FEATURE: EGL-272 - share everyone should prevent limiting inherited permission

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AccessControlConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts
fix: share everyone should prevent limiting inherited permission
_ regenerate the tiger client api to update the rule permission types
_ update the inherit permission for the rule
JIRA: EGL-272
--- …
=> BUGFIX: EGL-272 - share everyone should prevent limiting inherited permission

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/user/index.ts
feat: re-generate api client for the user permission
- adding the permissions for the user profile
JIRA: EGL-274
--- …
=> FEATURE: EGL-274 - re-generate api client for the user permission

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh
=> CONFIG: QA-20089 apply aio license for matrix test

libs/sdk-ui-pivot/src/PivotTable.tsx
=> BUGFIX: TNT-1757 PivotTable - set column headers position to left only when is allowed

common/config/rush/.npmrc-publish, common/scripts/ci/do_publish.sh
=> RELATED: RAIL-5146 Do not expose npm publish token

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/filterValidation.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetPicker.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateFilterCheckbox.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/utils.ts, libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss
feat: allow to show unrelated date items on KD
JIRA: EGL-247
--- …
=> FEATURE: EGL-247 - allow to show unrelated date items on KD

common/scripts/ci/run_cypress_integrated_tests.sh
=> CONFIG: QA-20092 add delete mode for cypress daily checklist

libs/sdk-ui-tests-e2e/cypress.config.ts, libs/sdk-ui-tests-e2e/scripts/lib/test_results.js
=> FEATURE: QA-19538 Cypress: report file should be included test name

common/scripts/ci/run_cypress_integrated_tests.sh
Passed on my branch:
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist-worker/1428/console
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist-worker/1430/console
--- …
=> CONFIG: QA-20092 fix delete mode for cypress checklist

libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/styles/scss/fast_track.scss
=> fix: Apply toast when OpenAI-generated description is applied to widget

libs/sdk-ui-tests-e2e/cypress/tools/messages.ts
=> BUGFIX: QA-20159 Increase waiting time export pdf

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/removeAttributeFiltersHandler.ts, libs/sdk-ui-dashboard/src/model/store/attributeFilterConfigs/attributeFilterConfigsReducers.ts
=> FEATURE: EGL-339 - remove attribute filter config when attribute filter has removed

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/permissionsLogic.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/test/permissionsLogic.test.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/test/GranteeMock.ts, libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/permissions.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/shareDialog.ts
fix: should not allow to remove the inherit permission
JIRA: EGL-312
--- …
=> BUGFIX: EGL-312 - should not allow to remove the inherit permission

libs/sdk-backend-bear/src/backend/index.ts
Removing related code no longer used after getting rid of domain admin plugins limitation.
JIRA: RAIL-5155
--- …
=> FEATURE: RAIL-5155 Remove legacy function to identify domain admin

libs/sdk-backend-bear/api/sdk-backend-bear.api.md, libs/sdk-backend-bear/src/convertors/toBackend/FilterConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/MeasureConverter.ts, libs/sdk-backend-bear/src/index.ts
=> BUGFIX: TNT-1815 allow null in insight filters

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, common/scripts/ci/run_cypress_recording.sh, libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
=> FEATURE: QA-20316 Change Cypress image to run e2e with latest browser

docs/content/en/latest/learn/visualize_data/export_catalog.md
=> RELATED: DP-2551 updating export_catalog protocols

common/scripts/ci/docker_apidocs_build.sh, common/scripts/ci/docker_examples.sh, common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh, libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
=> FEATURE: QA-17949 Replace public image by internal ecr image

libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/pivotTableUiConfigHelper.ts
Use INCREASE_MAX_TABLE_MEASURE_ITEMS_LIMIT when limiting metrics as
to be aligned with uiconfig itemsLimit.
Also increase pivot table base (non-ff) measures limit so that it's
aligned with column/line/area where it was also increased when
we now count derived measures to the limit.
---
| …
=> RELATED: TNT-1874 Fix pivot table limits

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, common/scripts/ci/run_cypress_recording.sh, libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml, libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml, libs/sdk-ui-tests-e2e/scripts/run_boiler_app.sh
=> BUGFIX: QA-20725 Missing require tools in cypress image

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/permissions/index.ts, libs/sdk-backend-tiger/src/backend/organization/permissions.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/EditUserDetails.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/detailsHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserGroupEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/dialogHooks.ts
- Introduce SPI to get org permissions for user and group
- Remove admin group when user is demoted to member from admin (removal of org permission is not enough)
JIRA: TNT-1877
--- …
=> BUGFIX: TNT-1877 Remove admin group when user is demoted to member

libs/sdk-backend-bear/api/sdk-backend-bear.api.md, libs/sdk-backend-bear/src/convertors/toBackend/FilterConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/MeasureConverter.ts, libs/sdk-backend-bear/src/index.ts
This is a backport of TNT-1815 fix to older
revision for the hotfix, see TNT-1893.
--- …
=> RELATED: TNT-1815 Allow null in insight filters

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh
=> BUGFIX: QA-20725 execute container with host user

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, libs/sdk-ui-tests-e2e/scripts/run_boiler_app.sh
=> BUGFIX: QA-20725 use ecr 3rdparty cypress image

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSaga.ts
=> BUGFIX: TNT-1818 Do not load irrelevant elements with empty selection

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
=> BUGFIX: TNT-1847 Revert removed LDM related tiger specific function

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh
=> BUGFIX: QA-20725 replace cypress image version

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/pivotTableUiConfigHelper.ts
Update pivot table warning message for different measures
and attributes count.
Also hide redundant message in rows/measures bucket
when columns bucket is empty.
---
| …
=> RELATED: TNT-1886 Unify pivot table warning messages

libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/MeasureConverter.ts
=> RELATED: TNT-1815 Extend notNull check options also for measure filters

libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts, libs/sdk-backend-bear/src/convertors/toBackend/MeasureConverter.ts
Completes the fix in TNT-1815.
---
| `extended …
=> RELATED: TNT-1906 Extend notNull check options also for measure filters

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: CAL-1187 add enableClickHouseDataSource feature flag 

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/drill.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/addDrillDownForInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts, libs/sdk-ui-dashboard/src/model/store/layout/tests/__snapshots__/layoutReducers.test.ts.snap, libs/sdk-ui-dashboard/src/model/store/layout/tests/layoutReducers.test.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/tests/widgetDrillSelectors.fixture.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts, libs/sdk-ui-dashboard/src/model/tests/fixtures/Dashboard.fixtures.ts, libs/sdk-ui-dashboard/src/model/utils/attributeHierarchyUtils.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetAttributeHierarchyItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts
=> BUGFIX: EGL-420, EGL-428 use attribute id instead of label id in blacklist hierarchies

docs/config/public/params.toml, docs/layouts/index.redir
=> TRIVIAL: doc bump to 9.4.0

libs/sdk-backend-tiger/src/convertors/shared/layoutConverter.ts, libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
=> BUGFIX: EGL-437 set correct type for date hierarchy when converting from backend

libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
- revert the PR https://github.com/gooddata/gooddata-ui-sdk/pull/4400. It causes failures in cypress tests for Bear
JIRA: EGL-429
--- …
=> BUGFIX: EGL-429 Revert filter out the deleted attributes in hierarchies

tools/dashboard-plugin-template/src/plugin_entry/index.ts
Correct compatibility in the template,
so it covers only minor version upgrades.
JIRA: RAIL-5178
--- …
=> fix(dashboard-plugin-template): compatibility

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
Also fix a bug in enableClickHouseDataSource definition.
--- …
=> RELATED: UNI-692 add enableCsvAnalytics feature flag

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
JIRA: SD-3066
Introduce APIs for CSV analytics into tigerSpecificFunctions
--- …
=> RELATED: SD-3066 add CSV APIs into tigerSpecificFunctions

common/scripts/ci/docker_apidocs_build.sh, common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh
Freeze node version used on ci builds to 18.17.0 since there are some breaking changes on [18.19.0](https://github.com/nodejs/node/issues/51098) 
--- …
=> chore: freeze node version

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts
=> FEATURE: SD-3024 export CSV types to be used in tigerSpecificFunctions

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/removeAttributeFiltersHandler.ts, libs/sdk-ui-dashboard/src/model/commands/drill.ts, libs/sdk-ui-dashboard/src/model/events/drill.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
- change public interface types
- do not remove global ignored filter on reset
- include all predicates for cross drilling
JIRA: TNT-1936
--- …
=> RELATED: TNT-1936 Fix cross drilling issues

common/changes/@gooddata/sdk-ui-all/mkn-tnt-1805_2023-12-13-22-01.json, libs/sdk-model/src/dashboard/drillUrl.ts, libs/sdk-model/src/internal.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParameters.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DashboardParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DisplayFormParam.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/InsightParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetUrlItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx, libs/sdk-ui-dashboard/styles/scss/drillConfigPanel.scss
Add support for attribute filter selection in drill to custom url.
Filter is serialized as `IN${JSON.stringify(value[] | uri[])}` or `NOT_IN${JSON.stringify(value[] | uri[])}`,
depending on the filter type and target platform.
New placeholder for global attribute filters:
{dash_attribute_filter_selection(displayFormId)}
New placeholder for insight attribute filters:
{attribute_filter_selection(displayFormId)}
JIRA: TNT-1805
---
| `ok to test`                                            | Re-run standard checks …
=> FEATURE: TNT-1805 Filter selection in drill to custom url

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DashboardParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DisplayFormParam.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/InsightParametersSection.tsx
Avoid duplicating filters in insight parameters section, when the same filter is both on insight and dashboard.
If the filter is renamed, show filter context title instead of attribute filter title in the parameters section.
Always use encodeURIComponent for stringified filters.
JIRA: TNT-1959
--- …
=> BUGFIX: TNT-1959 Filters in drill to custom url

libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
This guards the most expensive part with capability so that it is not called on bear backend
where it causes performance issues on projects with larger catalog.
For the future, we need to revisit how the creation is done and
guard even the creation of the hierarchies and optimize
`getAttributesWithHierarchyDescendants` fn.
--- …
=> RELATED: STL-38 Guard attribute hierarchy creation with capability

libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
When there are no ignores, compute attribute descendants only once
per whole dashboard, as it was before ignores were introduced.
When ignores are present, compute the targets on the fly instead of
computing the descendant map with ignores for all catalog attributes for
each widget.
---
| …
=> RELATED: STL-38 Do not compute drills with ignores per widget

common/git-hooks/pre-commit
=> fix: fix lint without node

libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrillToCustomUrlParams.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/modifyDrillsForInsightWidgetHandler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/removeDrillsForInsightWidgetHandler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useInvalidFilteringParametersIdentifiers.ts
Fix drill to custom url parameters validation
so it displays correct warnings and error messages for filtering parameters.
JIRA: TNT-1967
--- …
=> BUGFIX: TNT-1967 Fix drill to custom url validation

libs/sdk-ui-tests-e2e/cypress/support/index.ts, libs/sdk-ui-tests-e2e/cypress/support/session.ts, libs/sdk-ui-tests-e2e/scenarios/webpack.config.cjs
=> RELATED: STL-55 fix establishSession on localhost e2e test

.github/actions/check-pull-request-commits/src/action.js, libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/getChartHighlightingConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartHighlighting/highlightPoints.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/donutChart/donutConfiguration.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/pieChart/pieConfiguration.ts, libs/sdk-ui-charts/src/interfaces/chartConfig.ts, libs/sdk-ui-charts/styles/scss/highlighting.scss, libs/sdk-ui-charts/styles/scss/main.scss, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/store/drill/drillSelectors.ts, libs/sdk-ui-dashboard/src/model/store/drill/types.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
Selected points created by cross-filtering are passed to the charts. Each chart matches the point and adds classes for highlighting. These selected points are defined by drill intersection from the cross-filtering drill event.
JIRA: F1-2
--- …
=> FEATURE: F1-2 Cross-filtering highlighting

tools/app-toolkit/package.json, tools/plugin-toolkit/package.json
=> RELATED: STL-61 fix npm publish app-toolkit and plugin-toolkit

tools/applink/src/devConsole/action.ts, tools/applink/src/devConsole/pipeline/changeDetector.ts
Avoid infinite rebuilds caused by generated
`__version.ts` files created during the build.
Include only packages that are published to npm,
avoid rebuild of the packages that are not necessary during the dev workflow (tests, examples, etc).
JIRA: RAIL-5218
--- …
=> BUGFIX: RAIL-5218 Fix applink infinite rebuild

docs/config/public/params.toml, docs/layouts/index.redir
=> documentation bump

docs/config/public/params.toml, docs/layouts/index.redir
=> documentation bump 9.5

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/base.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/base.ts, libs/sdk-backend-tiger/src/backend/organization/permissions.ts
Also renames WorkspacePermissionAssignment to UserManagementWorkspacePermissionAssignment
and introduces new WorkspacePermissionAssignment which has similar structure to OrganizationPermissionAssignment and DataSourcePermissionAssignment
--- …
=> RELATED: F1-17 add workspace managePermissions endpoint

.github/workflows/test-master-commit.yaml
=> RELATED: STL-71 add test workflow to commit to the master

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts
Date datasets used for DFs validation were not provided when switching between view/edit mode
JIRA: LX-47
--- …
=> BUGFIX: LX-47 Provide date datasets during mode change

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
Passed on my branch:
https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/499/console
https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/500/console
--- …
=> BUGFIX: QA-21170 stabilize dependent filter tests

.github/workflows/publish-alpha.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-107 add publish workflows

.github/workflows/code-drop.yml, .github/workflows/publish-alpha.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-107 rush publish and code drop workflows

.github/workflows/publish-alpha.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-107 combine bump version and npm publish for alpha release

libs/sdk-ui-tests-e2e/cypress/tools/navigation.ts
The test was passed on my branch: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-boiler-app-bear-integrated-tests/174/
--- …
=> BUGFIX: QA-21262 remove login requirement for bear boiler app test

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
=> BUGFIX: F1-39 Sanitize dateDataSet from alert dateFilter

libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts, libs/sdk-ui-ext/src/internal/utils/bucketRules.ts, libs/sdk-ui-ext/src/internal/utils/tests/bucketRules.test.ts
=> FEATURE: LX-3 Recommendation rules work only with first DF

tools/app-toolkit/package.json, tools/plugin-toolkit/package.json
=> RELATED: STL-109 add prepublish build to app-toolkit and plugin-toolkit

.github/workflows/publish-alpha.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-107 manual triggered alpha release

.github/workflows/publish-alpha.yml, .github/workflows/pull-request-prerelease.yml, .github/workflows/rw-publish-prerelase.yml
=> RELATED: STL-118 add publish pre-release from PR

.github/workflows/pull-request-prerelease.yml, .github/workflows/rw-publish-prerelase.yml
=> RELATED: STL-118 fix input params in prepublish workflow

.github/workflows/pull-request-prerelease.yml, .github/workflows/rw-bump-version.yml
=> RELATED: STL-118 permissions in Pull request ~ Prerelease

libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx, libs/sdk-ui-dashboard/styles/scss/richText.scss
Show footer when the rich text widget height is small. Before the fix it was hidden by overflow.
JIRA: F1-9
--- …
=> BUGFIX: F1-9 Rich text footer

.github/workflows/pull-request-prerelease.yml
=> RELATED: STL-118 permissions in pull-request-prerelease WF

.github/workflows/pull-request-prerelease.yml
=> RELATED: STL-118 test get PR form push and permissions 

.github/workflows/pull-request-prerelease.yml
The output was taken from the wrong step, thus the follow-up was always skipped.
--- …
=> TRIVIAL: fix build script

.github/workflows/pull-request-prerelease.yml
=> RELATED: STL-118 fix: workflow

libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/AddLimitingItem.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/AddLimitingItemDialog.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitValuesConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitingItem.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/limitingItemsHook.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/tests/__snapshots__/limitingItemsHook.test.ts.snap, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss, libs/sdk-ui-kit/src/Dropdown/DropdownList.tsx
=> FEATURE: LX-23 Introduce ability to configure attribute filter elements limits, support parent filters

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: F1-58 Add enableMySqlDataSource feature flag

.github/workflows/post-merge-pipeline.yml
Reason - we can't use reusable workflow from private repository
This reverts commit fd717a60e20e3ab29004e74c7be6441af058b03f.
--- …
=> TRIVIAL: Revert "feat(ext-update): update ext-image files in gdc-nas"

docs/config/public/params.toml, docs/layouts/index.redir
=> RELATED: STL-81 docs: set 9.6 documentation

libs/sdk-backend-tiger/src/backend/organization/styling.ts
=> BUGFIX: F1-64 Move settings service init to constructor

.github/workflows/code-drop.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-prerelase.yml
=> RELATED: STL-140 add publish betas and alphas to code-drop

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/users/index.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/organization/users.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-model/src/user/index.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Form/InputPure.tsx
Add method for user creation to sdk-backend-tiger. Add feature flag to enable/disable the feature in home-ui.
JIRA: F1-67
--- …
=> FEATURE: F1-67 Add method to create user

.github/workflows/code-drop.yml, .github/workflows/pull-request-prerelease.yml, .github/workflows/rw-publish-prerelase.yml, .github/workflows/slack-post-merge-notification.yml
=> RELATED: STL-127 update action to run on node 20

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/drillDownUtil.test.ts
There used to be situations where after the drilldown, there were sort items left over using the removed attribute. This would later bomb if executed on tiger, because the normalizer hard fails on sorts that are missing "their" attributes. Changed the modifyBucketsAttributesForDrillDown function to prevent this.
--- …
=> RELATED: CQ-83 remove invalid sorts on drill down

.github/workflows/examples-deploy.yml
=> RELATED: STL-121 UI Examples heroku publish

.github/workflows/rw-publish-prerelease.yml, .github/workflows/rw-publish-release.yml
=> RELATED: STL-152 add github user to notification

.github/workflows/publish-alpha.yml, .github/workflows/publish-beta.yml, .github/workflows/pull-request-prerelease.yml, .github/workflows/rw-publish-prerelease.yml
=> RELATED: STL-152 fix author notification 

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
Passed on my branch: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/585/
--- …
=> BUGFIX: QA-21320 update dependent filter test to adapt new change

.github/workflows/git-backmerge.yml, .github/workflows/rw-git-backmerge.yml
=> RELATED: STL-120 chore: add backmerge workflows

.github/workflows/rw-git-create-tag.yml, .github/workflows/rw-publish-release.yml
=> RELATED: STL-120 add creating tag and branching into publish release process

.github/workflows/doc-test-apidocs.yml, .github/workflows/rw-doc-release-apidocs.yml
=> RELATED: STL-154 Prepare api docs version workflow

.github/actions/get-version-action/action.yml, .github/workflows/release-code-drop.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-doc-netlify-deploy.yml, .github/workflows/rw-doc-update-hugo-version.yml, .github/workflows/rw-git-backmerge.yml, .github/workflows/rw-perform-release-major-minor.yml, .github/workflows/rw-publish-prerelease.yml, .github/workflows/rw-publish-release.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-176 Unify get version and uses of local actions

libs/sdk-ui-tests-e2e/README.md
=> TRIVIAL: update documentation for running scenarios

.github/workflows/release-code-drop.yml, .github/workflows/release-postrelease.yml, .github/workflows/release-release-minor.yml, .github/workflows/rw-publish-prerelease.yml
=> RELATED: STL-155 Add environments for manual triggers

.github/actions/get-version-action/action.yml
=> fix: output current version also to stdout

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
Solution: Should keep "Insight has..." here, because it's showing visualization name, not
a term of "Insight"
Passed on my branch:
- bear: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_bear-worker/1935/
- panther: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/622/
---
> [!IMPORTANT]
---
```
```
``` …
```
=> BUGFIX: QA-21418 keep visualization name for invalid interaction warning

common/config/rush/pnpm-lock.yaml, libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/package.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
Cache calls to Feature Hub as it is quite static source
On Tiger there is no difference between visible 
and accessible dashboards, so avoid second call
JIRA: LX-133, LX-134
---
> [!IMPORTANT]
---
```
```
```
```
```
extended …
```
=> feat: optimize FH and dash. list API calls

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
Set `enableCreateUser` to true by default.
Also remove `enableManageDataSourcePermissions`,
as it does not make sense.
JIRA: F1-51
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: feature flags for user management

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, libs/sdk-ui-tests-e2e/scripts/run_boiler_app.sh
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> QA-21429: switch to use internal cypress container image

libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts, libs/sdk-ui-dashboard/src/model/commands/render.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardAsyncRender.ts, libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutUtils.ts
=> RELATED: STL-138 Relax 2s timeout for async registrations

libs/sdk-backend-tiger/tests/integrated/__snapshots__/elements.test.ts.snap, libs/sdk-backend-tiger/tests/integrated/elements.test.ts
This should fix the tests.
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> RELATED: CQ-266 cherry-pick cacheId fixes

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap, libs/sdk-ui-dashboard/src/model/store/backendCapabilities/backendCapabilitiesSelectors.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts
The selectors were previously removed as always true,
but old non-autoupgrade plugins could depend on them.
See #4617
JIRA: STL-293
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: bring back selectors as always true

libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/dependentDateFilters.ts, libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/filterContext.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/removeDateFiltersHandler.ts, libs/sdk-ui-dashboard/src/model/types/dateFilterTypes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFilterConfigurationState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFiltersConfiguration.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitValuesConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/AddLimitingItemDialog.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/DateFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/ParentFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/limitingItemsHook.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useDependentDateFilters.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-filters/src/AttributeFilter/hooks/useResolveDependentDateFiltersInput.ts
- Allow to filter attribute elements by common date filter (datasets)
JIRA: LX-157
- Allow to remove selected dependent date filters (specific, common)
JIRA: LX-158
---
> [!IMPORTANT]
---
```
```
```
```
``` …
```
=> FEATURE: LX-157, LX-158 Filter elements by common date + removal

libs/sdk-backend-tiger/src/backend/workspace/attributeHierarchies/index.ts, libs/sdk-backend-tiger/src/convertors/shared/layoutConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/drill.ts, libs/sdk-model/src/index.ts, libs/sdk-model/src/ldm/catalog/attributeHierarchy/index.ts, libs/sdk-model/src/ldm/catalog/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/addDrillDownForInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillDownForInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts, libs/sdk-ui-dashboard/src/model/store/catalog/tests/__snapshots__/catalogSelectors.test.ts.snap, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts, libs/sdk-ui-dashboard/src/model/utils/attributeHierarchyUtils.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyListItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetAttributeHierarchyItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts
When date attribute based hierarchy
is added to ignore list we need to store
correct hierarchy template id
DateHierarchyTemplate is not valid MD type yet
so we can not store full objRef but just id string JIRA: LX-145
---
> [!IMPORTANT]
---
```
```
```
```
``` …
```
=> fix: store proper template id to DD ignore list

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useDependentDateFilters.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts
- Fix proper granularity "to".
JIRA: LX-178
- Update filter when dependent date filter value changes.
JIRA:LX-179
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: LX-178, LX-179 Common date filter proper granularity, recover from error when changing dependent date filter.

docs/content/en/latest/learn/visualize_data/export_catalog.md
Originally removed in #4837 but for some reason
it was re-added in #4853. Removing again.
JIRA: STL-382
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove bear docs after it was previously re-added

common/changes/@gooddata/sdk-ui-all/stl-270-export-definitions-service_2024-04-09-12-14.json, libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/metadataUtilities.ts, libs/api-client-tiger/src/organizationUtilities.ts, libs/sdk-backend-base/src/customBackend/workspace.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/exportDefinitions/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/workspace/exportDefinitions/comparator.ts, libs/sdk-backend-tiger/src/backend/workspace/exportDefinitions/exportDefinitionsQuery.ts, libs/sdk-backend-tiger/src/backend/workspace/exportDefinitions/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/exportDefinitions/index.ts, libs/sdk-model/src/index.ts, libs/sdk-model/src/objRef/index.ts
[STL-270](https://gooddata.atlassian.net/browse/STL-270)
On the Export Definitions:
The tiger backend now supports a new type of metadata object called exportDefinitions. The use case for the EDs is to enable saving export configuration & metadata(such as title, and description..) for particular insights, based on which users will be able to create reports (a tabular representation of any insight, that will be later exported to PDF either ad hoc or as a scheduled email).
The service contains similar methods for CRUD operations on EDs as the insights service. For now, it's marked as @alpha since the API may still go through some changes while being integrated in real-world scenarios.
---
> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new …
=> feat: export definitions service

libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
placeholder icon didn't show in Repeater when image link is not found or not image format
JIRA: F1-192
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-192 placeholder icon didn't show in Repeater

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Do not remove simple measure titles for repeater,
as they can be transformed to inline measures for the execution, and then we don't have access to the original measure descriptor and title.
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show repeater column titles for measures

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
Also deprecate the getStagingUploadLocation function that is superseded by stagingUpload.
JIRA: CQ-279
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add the stagingUpload tiger specific function

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
This is to allow it being used in the applications without direct api-client-tiger imports.
JIRA: CQ-279
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: re-export UploadFileResponse from sdk-backend-tiger

libs/sdk-backend-base/src/customBackend/workspace.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/decoratedBackend/organization.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/organization/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/organization/index.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/convertors/toBackend/WorkspaceConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/organization/index.ts
Generic way to update attributes of ws/org, to use instead of tiger specific functions.
Not included:
Changing parent workspace - can be added to updateDescriptor, but PATCH currently does not work for relationships, so we would need to conditionally call GET+PUT when parentWorkspace update is requested. 
Allowed origins are also in organization attributes, however not in the descriptor yet. If they are added we can deprecate two more tiger specific functions, but this is out of scope now
---
> [!IMPORTANT]
---
Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the …
=> FEATURE: add updateDescriptor methods to ws and org

common/changes/@gooddata/sdk-ui-all/pji-lx-217-workspace-hierarchy-data_2024-04-23-16-41.json, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts
JIRA: LX-217
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: include hierarchy data in workspace descriptor

common/changes/@gooddata/sdk-ui-all/pji-lx-217-workspace-hierarchy-data_2024-04-24-16-11.json, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts
JIRA: LX-217
Added a new filter option to the workspaces query to be able to filter out only root workspaces without a parent workspace.
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add filter for root workspaces only to workspaces query

libs/sdk-backend-tiger/src/backend/workspaces/index.ts
This was the default behaviour of the FE sorting
JIRA: F1-294
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: sort workspaces by name in WorkspacesQuery

libs/sdk-ui-ext/src/internal/components/configurationControls/forecast/ForecastSection.tsx, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts, libs/sdk-ui-ext/src/internal/translations/en-US.json
JIRA: F1-322
JIRA: F1-316
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: forecast is disable when selecting "show on right axis" item

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-backend-tiger/package.json, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
This handles temporary traffic spikes on the upload API: if there are
too many requests happening, automatically retry after a backoff.
JIRA: CQ-378
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add retries to staging file uploads

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/result.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
The corresponding API was removed from the backend already. No client app should be using this anymore, so let's just remove this.
JIRA: CQ-383
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: remove the getStagingUploadLocation function

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/bucketHelper.ts
Scatter plot: remove items from the viewBy and segmentBy bucket that do not belong there (both can contain a maximum of 1 item).
This fix ensures that switching from different visualization to scatter plot in AD will not cause the scatter plot to contain invalid items in the viewBy and segmentBy bucket.
JIRA: F1-346
---
> [!IMPORTANT]
---
```
```
``` …
```
=> fix: scatter plot bucket helper

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
Enable forecasting and segmentation feature flags
by default for GoodData.CN all in one image.
JIRA: F1-345, F1-156
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: enable forecasting and segmentation in AIO

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts
Fix heatmap coloring issue.
Max value was out of the range specified for coloring, because the applied number precision cut off the last few digits.
It seems that the number precision is not needed anymore, Highcharts seems to handle the coloring correctly without it, so remove it.
risk: low
JIRA: F1-344
---
> [!IMPORTANT]
---
```
```
```
extended test - tiger-cypress - …
```
=> fix: heatmap coloring

libs/sdk-ui-ext/src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts
Add the ability to configure the legend
in the scatter plot configuration panel.
JIRA: F1-379
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: scatter plot legend configuration

libs/sdk-ui-charts/src/highcharts/chartTypes/bubbleChart/bubbleConfiguration.ts
Fix strange behavior of the bubble chart, by updating the configuration to avoid usage of the undocumented Highcharts API.
Issue and solution was exactly the same as this one on GitHub: https://github.com/highcharts/highcharts/issues/17555
JIRA: F1-304
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: bubble chart

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-charts/src/charts/scatterPlot/CoreScatterPlot.tsx
Propagate missing clustering configuration
in standalone ScatterPlot component.
Also enable `enableScutterPlotClustering`` feature flag by default.
risk: low
JIRA: F1-390
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: standalone ScatterPlot clsutering

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/exportDefinitions/index.ts
The export definition entity has changed from a free-form JSON to more strictly defnied entity, as it gained new uses on the backend side. These changes do the bare minimum to restore compatibility.
JIRA: F1-360
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: use the generated interface for export definitions

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/elements.ts
It fails time to time when loading attribute filter after apply cross filtering
risk: low
JIRA: F1-433
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: it fails time to time when loading attribute filter

libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss
Tooltip missing in Chart Drill-down dialog
Tooltip shown below filter bar
risk: low
JIRA: F1-250
JIRA: F1-251
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: dashboard component fixes

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
This allows us to test the rollup totals on the UI without enabling the canCalculateNativeTotals capability on tiger backends yet.
risk: low
JIRA: CQ-603
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow rollup totals if enableRollupTotals is true

libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss
Tooltip missing in Chart Drill-down dialog
Tooltip missing in Chart Drill-down dialog
risk: low
JIRA: F1-250
JIRA: F1-251
---
> [!IMPORTANT]
---
```
```
```
```
=> fix_ dashboard component fixes

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/dimensions.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/__snapshots__/dimensions.test.ts.snap, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/results/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/intersectionUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
- propagate primaryLabel from execution to the drill
- create new virtual filter from primary label and primary values
- displayAsLabel for virtual filter is defined automatically
JIRA: LX-318
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: secondary label during cross filtering

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/filterContext.ts, libs/sdk-model/src/exportDefinitions/index.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/sharedHooks/useCommonDateFilterTitle.ts, libs/sdk-ui-dashboard/src/_staging/sharedHooks/useDateFiltersTitles.ts, libs/sdk-ui-dashboard/src/model/commands/scheduledEmail.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitValuesConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentFilters.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentFiltersList.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/constants.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useCreateScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useUpdateScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/getAutomationFilters.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/hooks/useResolveAttributeFilterSubtitle.ts, libs/sdk-ui-filters/src/AttributeFilter/index.ts, libs/sdk-ui-filters/src/AttributeFilter/utils.ts, libs/sdk-ui-filters/src/index.ts
- export definition for dashboard uses FilterContextItem in opposed to export definition for visualization objects due to differences in BE consumption
- do not store cross-filtering in export definition
- do not show hidden filters in the list of edited filters
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: store dashboard filters with export definition

libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/bridge.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/loader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/types/attributeFilterLoader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/types/elementsLoader.ts
- handler.getFilterToDisplay() always returns something even displayAsLabel is not defined
- it caused endless loop when comparing filter based on attribute with single label
- user real displayAsLabel value from state instead
JIRA: LX-368
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: use proper ref from state

libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
Change how multiple earlyAccess flags are provided to FeatureHub, to keep it more backward compatible.
risk: low
JIRA: F1-491
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: earlyAccess flags

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/GrandTotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap, libs/sdk-ui-pivot/src/locales.ts
To keep things consistent, we changed the TotalFunction enum value for native totals from NATIVE to NAT on the backend. This is the adaptation to that.
JIRA: CQ-652
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> refactor: adapt to the change of NATIVE -> NAT on backend

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/drill.ts, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/intersectionUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToInsightHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributes.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributesSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargets.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/drillConfigMapper.ts, libs/sdk-ui-dashboard/styles/scss/drillConfigPanel.scss, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectItem.tsx, libs/sdk-ui-kit/src/List/InvertableSelect/index.ts, libs/sdk-ui-kit/src/List/index.ts
This features enables possibility to ignore specified attributes in the drill intersection for selected drill definitions. Ignored attributes are not transferred as filters during the drill.
Only drill to insight and drill to dashboards are supported.
- Add new feature flag `enableDrillIntersectionIgnoredAttributes` to enable/disable drill intersection filtering configuration
- Add new components for drill intersection filtering configuration
- Apply new configuration in relevant command handlers
- Validate that ignored attributes are still present in target insight, if not, remove the drill and show warning toast message
- Update some ui-kit components to support more customizations
risk: low
JIRA: F1-521
---
> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits …
=> feat: drill intersection filtering configuration

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx
There already was logic to remove row rollup totals when there is a ranking or measure value filter. We need the same logic for column totals, too.
JIRA: CQ-675
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove column rollup totals as well

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/automations/index.ts, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts
Add support for alerting rollout feature flag,
that will be used to enable it in experimenbtal features.
Also add minimal support for alerting in sdk-model - it will be extended later.
risk: low
JIRA: F1-543
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: alerting feature flags and base in sdk-model

libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DashboardParametersSection.tsx
When filter has primary label used also for UI do
not offer it twice in custom uri params
JIRA: LX-399
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: do not offer displayAsLabel when same

libs/sdk-embedding/src/internal/filterConvertors.ts
The type used for refs in postMessages is missing type of object and thus can not be directly saved in MD.
JIRA: LX-430
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: convert displayAsLabel from IdentifierRef to idRef

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts
During migration of filter to new format using primary label it may happen that the number of elements in the selection will overflow the limit. API request needs to handle this. UI will force user to reduce selection to be able to save it
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: handle selection over limit

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardAlerts.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
[Alerting M1] When automation reach limit , should disable button "Create" on Schedule Export Dialog
JIRA: F1-598
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: reach limit must include also emails

libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/store/automations/automationsSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightEditMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useEditableInsightMenu.ts, libs/sdk-ui-dashboard/src/presentation/widgetDeleteDialog/DefaultWidgetDeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widgetDeleteDialog/WidgetDeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widgetDeleteDialog/index.tsx, libs/sdk-ui-dashboard/src/presentation/widgetDeleteDialog/types.ts
when user tries to remove some widget, new delete dialog is shown based on whether some automation objects are tied to the widget
JIRA: F1-535
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add widget delete dialog with context

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillDownHandler.ts, libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/drill/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/drill/utils/drillDownUtils.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/DashboardInsightWithDrillDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/drillConfigMapper.ts
Fix issue with date hierarchies matching - now, configured intersection ignored attributes should be correctly applied for date drill downs.
Display drill title (or label title) in the drill dialog instead of the attribute element title in case the attribute is ignored, as it was leading to confusing user experience.
JIRA: F1-591
---
> [!IMPORTANT]
---
```
```
```
extended …
```
=> fix: drill down intersection ignored attributes

libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
Fix a bug when search drop-down closing for __blank but not for __self links.
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 search closing bugfix

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/NoAvailableAlerts.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx, libs/sdk-ui-dashboard/styles/scss/alerting.scss
[Alerting M2] Get blank page when set an Alert on Widget Repeater not using Metric [Alerting M1] Alerting section does not display in Experimental Feature
JIRA: F1-628, F1-649
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: bug repairs

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
Show correct name for measures that were renamed in analytical designer. Alias now takes precedence over measure title.
risk: low
JIRA: F1-627
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show correct measure title in alert config

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/index.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts, libs/sdk-ui-ext/src/internal/interfaces/VisualizationDescriptor.ts
BE now supports headline exports,
so we want to allow it in the UI.
Feature is behind enableHeadlineExport FF.
JIRA: F1-680
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow manual exports for headlines

libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/calculation/tests/CalculationListItemInfo.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/__snapshots__/PluggableAreaChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/tests/__snapshots__/PluggableBaseChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bubbleChart/tests/__snapshots__/PluggableBubbleChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/__snapshots__/PluggableBulletChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/dependencyWheelChart/tests/__snapshots__/PluggableDependencyWheelChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/donutChart/tests/__snapshots__/PluggableDonutChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/funnelChart/tests/__snapshots__/PluggableFunnelChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/tests/__snapshots__/PluggableGeoPushpinChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline2.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/__snapshots__/PluggableHeadline.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/__snapshots__/PluggableHeadline2.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/__snapshots__/PluggableHeatmap.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/__snapshots__/PluggableLineChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/tests/__snapshots__/PluggablePieChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/sankeyChart/tests/__snapshots__/PluggableSankeyChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/tests/__snapshots__/PluggableScatterPlot.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/__snapshots__/PluggableColumnBarCharts.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/tests/__snapshots__/PluggableTreemap.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/waterfallChart/tests/__snapshots__/PluggableWaterfallChart.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/tests/__snapshots__/PluggableXirr.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/tests/bucketHelper.test.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/__snapshots__/bulletChartUiConfigHelper.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/comboChartUiConfigHelper.test.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/comboChartUiConfigHelperDeprecated.test.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/headlineUiConfigHelper.test.ts, libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts
default enableRenamingMeasureToMetric was not true in some cases after reload
this might be related to latest React 18 upgrade in AD where it was spotted first
JIRA: F1-684
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: make sure to use metric instead of measure

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
Repeater does not support drill down, so hide the drill down detail section with info about attribute hierarchies.
JIRA: F1-671
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: hide drill down detail section in Repeater

examples/playground/src/App.tsx
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: keep dashboard component in playground by default

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/filterViews.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/__snapshots__/filterViews.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/filterViews.mock.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/filterViews.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts
The current naive implementation removed filters from dashboard's filter context when they were missing in the filter view (when filter was added to dashboard later after the view was saved).
Also, the default view was not applied when user saved some changes in dashboard edit mode and render mode was switched from edit to view.
JIRA: LX-422
risk: low
---
> [!IMPORTANT]
---
```
```
``` …
```
=> fix(dashboards): merge default filter view with dashboard correctly

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
[Scheduling M3] schedule widget not selecting attachment, reopening it displays attachment PDF
JIRA: F1-571
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: schedule widget not selecting attachment

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
Ignore filterViews from parents, as these can not be deleted nor set as default from child WS.
JIRA: LX-514
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: fetch only filterView from current WS

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
This makes it so that the existing feature flag is actually propagated to the UI.
JIRA: CQ-727
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add enableFlightRpcDataSource feature

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsData.ts
Export permission is not required to schedule exports in dashboard, so remove the check for export permission.
risk: low
JIRA: F1-710
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show scheduled exports in dashboard

libs/sdk-backend-tiger/src/backend/features/index.ts
Alerting and scheduling is currently disabled in release branch, we can re-enable it after release of 10.11.0.
risk: low
JIRA: F1-753
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: re-enable alerting / scheduling

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/loadAutomations.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/refreshAutomationsHandlers.ts, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/DeleteAlertConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/DeleteScheduleConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
For users with workspace management permissions:
1. Retrieve all alerts and schedules associated with the dashboard, including those created by other users or where the current user is not a recipient
2. Grant the ability to delete any alert or schedule, regardless of its creator
risk: low
JIRA: F1-710
---
> [!IMPORTANT]
---
```
```
```
extended test - tiger-cypress - …
```
=> fix: alerts and scheduled exports permissions

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
- unified the naming of the feature flags used with early access
- marked old enableAIFunctions flag as deprecated to get removed once UI apps are updated
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 early access feature flags

libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/onUserMessage.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/threadPolling.ts
Fix the issue with polling after changes on server
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 fix the polling

libs/sdk-ui-pivot/src/impl/data/rowFactory.ts
Name from measureHeaderItem.name was used to render the metric name when metrics are placed in rows dimension. The object contained the original metric name for metrics created via Metric editor. When user renamed the metric in AD bucket, the name alias was not used. The reason for the original metric being there is due to some complex logic in dataView facade mapper. The name is being resolved because Tiger backend returns only order index of the metric but for custom metrics, it returns also its name. This name then bubbled to the table row.
Instead, the name from tableDescriptor measure is used instead now. Descriptor contains the currently applicable name for the measure, either the one returned by backend or one resolved from buckets (title, then alias if set by user). The same …
=> fix(pivot): render renamed row metric current name

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/DefaultAlertingManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx
If value of the alert represents percents,
show % in the description of the alert.
Do not show links in alerting / scheduling dialogs for white labeled domains.
risk: low
JIRA: F1-739
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show % in alerts description

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/DashboardAttachments.tsx
Do not override dashboard filters
in scheduled export with `undefined` value.
Remove unnecessary code.
risk: low
JIRA: F1-802
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: save filters in scheduled exports

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherHeader.scss, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherToolbar.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: switcher bugs vol.2

libs/sdk-backend-base/src/decoratedBackend/organization.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/organization/index.ts, libs/sdk-backend-spi/src/organization/llmEndpoints/index.ts, libs/sdk-backend-tiger/src/backend/organization/index.ts, libs/sdk-backend-tiger/src/backend/organization/llmEndpoints.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/llmEndpointConvertor.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/llmEndpoints/index.ts, libs/sdk-ui-gen-ai/styles/scss/main.scss
- Added support for the new md object.
- Fixed a bug when react-loading-skeleton was missing styles if not included by the host app.
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 LLM Endpoints metadata object support in sdk-backend-tiger

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Propagate GoodData.UI SDK version to FeatureHub, so we can use it as a split rule.
JIRA: F1-815
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: propagate SDK version to FeatureHub

libs/sdk-ui-kit/src/Overlay/Overlay.tsx
JIRA: F1-837
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: do not use resize observer when threshold not specified

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertAttributeSelecxt.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
- Alert form didn't show the custom name of the attribute
- NULL value didn't show text "empty value" in Alert form
- Alert form didn't show name of second label if attribute has many labels
JIRA: F1-847, F1-846, F1-848
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: bug repairs

libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
Creating alert failed after changing name of attribute in visualization
JIRA: F1-878
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: alert afm contains alias field that is not allowed

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts
Remove check for status as it skipped fast changing filter prop. In AD metric filter is taken from extended ref. point. So it is out of sync for short time when filter is changed (waiting for PV loop). This fast changing filter prop was ignored because status check.
JIRA: LX-615
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: better handling of fast changing filter prop

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertAttributeSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts, libs/sdk-ui-dashboard/styles/scss/alerting.scss
Regression - Action buttons of alert form get hidden when added more than 3 lines of recipients Alert one value of attribute was skipped when attribute has many labels
JIRA: F1-883, F1-864
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: bugs repairs related to attribute labels

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
Remove enableGranularPermissions feature flag,
as it is already enabled by default and not necessary anymore.
risk: low
JIRA: F1-837
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: remove feature flag

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataSources/index.ts
Brings the FLEXCONNECT datasource type that will replace the FLIGHTRPC type once we adapt the backend and everything.
JIRA: CQ-893
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: regenerate client

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/intersectionUtils.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
Cross filtering has been removed when clicking on the first column after some filters applied
risk: low
JIRA: F1-919
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: cross filtering has been removed

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/sdk-backend-base/src/dummyBackend/DummyGenAIChatThread.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/genAI/index.ts, libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md, libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatOverlay.tsx, libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx, libs/sdk-ui-gen-ai/src/hooks/useGenAIStore.ts, libs/sdk-ui-gen-ai/src/index.ts, libs/sdk-ui-gen-ai/src/store/chatWindow/chatWindowSelectors.ts, libs/sdk-ui-gen-ai/src/store/chatWindow/chatWindowSlice.ts, libs/sdk-ui-gen-ai/src/store/events.ts, libs/sdk-ui-gen-ai/src/store/index.ts, libs/sdk-ui-gen-ai/src/store/messages/messagesSelectors.ts, libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/index.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/onEvent.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/onThreadLoad.ts, libs/sdk-ui-gen-ai/src/store/store.ts, libs/sdk-ui-gen-ai/src/store/types.ts, libs/sdk-ui-gen-ai/styles/scss/messages.scss, libs/sdk-ui-tests/stories/visual-regression/genAI/Chat.tsx
Chat now exposes events necessary for telemetry.
The public API made consistent with Dashboard component events, thus the somewhat weird `eventHandlers` property.
---
```
```
```
```
=> RELATED: F1-645 chat telemetry

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json
Do not reverse thousand separator string in the formatted result.
Empty strings should be considered as empty separators, and not fallback to default separators.
Default separators still should be used
in case of undefined/null separators.
risk: low
JIRA: F1-862
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: separators

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts
Some comparative alert on Visualizations  can not trigger
risk: low
JIRA: F1-931
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: comparative alert on vis can not trigger

libs/api-client-bear/src/__version.ts, libs/api-client-tiger/.gitignore, libs/api-client-tiger/scripts/build.sh, libs/api-client-tiger/src/__version.ts, libs/sdk-backend-bear/src/__version.ts, libs/sdk-backend-tiger/.gitignore, libs/sdk-backend-tiger/scripts/build.sh, libs/sdk-backend-tiger/src/__version.ts, libs/sdk-ui-dashboard/.gitignore, libs/sdk-ui-dashboard/scripts/build.sh, libs/sdk-ui-dashboard/src/__version.ts, libs/sdk-ui-gen-ai/.gitignore, tools/app-toolkit/.gitignore, tools/app-toolkit/scripts/build.sh, tools/app-toolkit/src/__version.ts, tools/catalog-export/.gitignore, tools/catalog-export/scripts/build.sh, tools/catalog-export/src/__version.ts, tools/mock-handling/.gitignore, tools/mock-handling/scripts/build.sh, tools/mock-handling/src/__version.ts, tools/plugin-toolkit/.gitignore, tools/plugin-toolkit/scripts/build.sh, tools/plugin-toolkit/src/__version.ts
The presence of placeholdered __version.ts files will make sure that these are correctly cached in rush cache.
The version will get updated in post-build
risk: low
JIRA: STL-931
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: adjust build scripts to be compatible with rush cache

libs/sdk-ui-web-components/Dockerfile
* use pulltrhough cache ECR repo
risk: low
JIRA: INFRA-3760
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: upgrade base docker image

.github/workflows/pull-request-prerelease.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-prerelease.yml, .github/workflows/rw-publish-version.yml
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: add rush cache support for publish

.github/actions/node/check-node-version/action.yml, .github/actions/node/set-up-node/action.yml, .github/actions/node/warm-up-node/action.yml
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: backport node setup actions to rel branch

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
This flag is no longer used by the apps, so let's get rid of it.
JIRA: CQ-953
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: remove the enableFlexConnectNaming FF

common/scripts/ci/run_cypress_recording.sh
risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: correct script call after PUSHD in previous step

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/genAI/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/genAI/chat.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/converters/interactionsToMessages.ts
Add error response type for the chatbot
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 error reporting

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ExportMetadataConverter.ts
If filters are missing in export definition,
use the default dashboard filters.
If filters are provided (even empty ones),
use these to override default dashboard filters.
Before, it worked because export metadata endpoint always failed with empty filters.
JIRA: F1-975
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: dashboard export filter context

libs/sdk-backend-tiger/src/convertors/fromBackend/DateFilterConfigurationConverter.ts
risk: low
JIRA: LX-706
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: validate custom date filter config granularities

.github/workflows/pull-request-comment.yaml
risk: nonprod
---
> [!IMPORTANT]
---
```
```
-   `--filter` (Optional) A comma-separated list of test files …
=> chore: fix isolated command comment check

.github/workflows/checklist-cypress-ui-test.yaml, .github/workflows/checklist-integrated-staging.yaml, .github/workflows/checklist-run-boiler-app.yaml, .github/workflows/rw-rush-build-e2e-tests-integrated.yml, common/scripts/ci/run_cypress_integrated_tests.sh
switching a few commits to release branch:
- https://github.com/gooddata/gooddata-ui-sdk/pull/5716/files
- https://github.com/gooddata/gooddata-ui-sdk/pull/5701/files
- https://github.com/gooddata/gooddata-ui-sdk/pull/5715/files
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The …
=> ci: switching a few commits to release branch

.github/workflows/rw-rush-build-e2e-tests-backstop.yml, libs/sdk-ui-tests/backstop/backstop-cleanup-artifacts.cjs, libs/sdk-ui-tests/backstop/run-backstop-compose.sh
After test is finished with failure, postprocess the results to include
only failed test screenshots in the report to decrease artifact size.
Also include reference images in the output for visibility in the html
report.
risk: low
JIRA: STL-1006
---
> [!IMPORTANT]
---
```
```
- …
=> feat: cleanup backstopjs artifacts

.github/workflows/checklist-integrated-staging.yaml
JIRA: QA-23600
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> QA-23600: fix slack notification when failing

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
risk: low
JIRA: F1-1037
---
> [!IMPORTANT]
---
```
``` …
=> fix: miss tooltip when hover the guest card

libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts, libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
- move registration to earlier stage (useEffect)
- fix async expected count for vis switcher widget
risk: low
JIRA: STL-982
---
> [!IMPORTANT]
---
```
``` …
=> fix: register for async render as early as possible

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/interfaces.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/item.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/layout.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/section.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/tests/__snapshots__/layout.test.ts.snap, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/tests/layout.test.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/builder/tests/utils.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/facade/interfaces.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/facade/layout.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/fluidLayoutCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/fluidLayoutCustomizer.test.ts, libs/sdk-ui-dashboard/src/plugins/customizer.ts, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutViewSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
Dashboard customizer now allows to add section or item to nested layout Layout builders now allow to manipulate nested layouts
JIRA: LX-603
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat: extend Plugins API by support of nested layouts

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/layout/coordinates.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutItem.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/interfaces.ts, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/DragLayerPreview/WidthResizerDragPreview.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/types.ts, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/resizing.scss
The first widget of the container is higher than the subsequent widgets. We need to detect the row index of the widgets and gave the widgets on the first row the same class and style them the same way. The current code styled only the first widget of the first row differently, counting with the fact that containers will have just a single widget per row which was later changed.
JIRA: LX-736
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific text on the pull request. It is possible to …
=> fix: widgets on the first row of container are not aligned

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
[External recipient] Button "Save" editing schedule/alert is disabled after switching destination from EXTERNAL to CREATOR
risk: low
JIRA: F1-1043
---
> [!IMPORTANT]
---
```
``` …
=> fix: bug with invalid state of recipients

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/EmptyNestedLayoutDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
Initial drop zone now has new text for active state.
JIRA: LX-749
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: new text for active state and styles unification for drop zone

libs/sdk-ui-dashboard/styles/scss/export.scss
Includes temporary debugging style.
JIRA: LX-696
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: do not cut widgets at the end of nested layout during export

libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemHeadline.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardNestedLayoutWidget/Toolbar.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss
---
> [!IMPORTANT]
---
```
``` …
=> fix: hide Title cfg for empty container and handle slow css-grid sizing in LinesEllipsis

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/ResizeOverlay.tsx, libs/sdk-ui-dashboard/styles/scss/resizing.scss
Size of overlay changed so it matches exactly the size of widget with selected border. For both regular widgets and nested containers
JIRA: LX-754
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: make resize overlay match the size of widget

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/EmptyDashboardDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/EmptyNestedLayoutDropZone.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/WidgetDropZoneColumn.tsx, libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss
Dropzone in existing row now fills just row's height, same in nested container. Dropznone on empty dashboard is full width and 300px height now.
JIRA: LX-751
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to …
=> feat: dropzones do not reflect widgets default size anymore

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-ui-dashboard/src/model/store/executionResults/executionResultsSelectors.ts
Get rid of attributesWithReferences cache and map results from more granular caches to it properly.
Also fix selectHasSomeExecutionResult selector, as empty results are resolved as error.
risk: low
JIRA: F1-1052
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run …
=> fix: caching

libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/DateFilterConfigurationConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts
Avoid duplicate `/resolveSettings` call for date filter configuration.
risk: low
JIRA: F1-1051
---
> [!IMPORTANT]
---
```
``` …
=> fix: optimize date filter config requests

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/user/index.ts
add entitlements and info about deployment, for which it's no longer to call specific api
in tiger specific fn (await sdk.entities.getAllEntitiesWorkspaces) later in 
https://github.com/gooddata/gooddata-ui-sdk/blob/master/libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts#L658
risk: low
JIRA: STL-1058
---
> [!IMPORTANT]
---
```
extended-test --backstop | --integrated | …
```
=> feat: add additional info to user profile

libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
use correct part of the pair structure (dateDataset, dateDatasetLink) feature flag is true/false
risk: low
JIRA: STL-1073
---
> [!IMPORTANT]
---
```
``` …
=> fix: fix date filter resolution and ignore

libs/sdk-ui-dashboard/src/_staging/sharedHooks/useAttributes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useAttributeDataSet.ts
Do not wait for preloaded attributes/datasets if creating new dashboard, as they are available only for existing dashboards.
risk: low
JIRA: STL-1097
---
> [!IMPORTANT]
---
```
``` …
=> fix: preloading attributes / datasets

libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx
Fixed a bug where visualization could not be saved if has filters
---
> [!IMPORTANT]
---
```
``` …
=> RELATED: GDAI-61 save vis filters

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
palette is not dependent on user settings; load it in parallel
and not inside of the `resolveDashboardConfig`.
risk: low
JIRA: STL-1105
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to run integrated tests against the …
=> feat: reorder palette calls

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
This reverts commit 84a4a72eaa0a4b6aac1ea3a5e425970abdd7f908.
Breaks dashboard plugins as some of them cannot deal with empty palette and palette refresh.
risk: low
JIRA: STL-1110
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The …
=> feat: revert "feat: reorder palette calls"

libs/sdk-ui-gen-ai/src/components/messages/contents/SearchContents.tsx, libs/sdk-ui-gen-ai/src/components/messages/contents/replaceLinks.ts, libs/sdk-ui-gen-ai/src/components/messages/contents/test/parseText.test.ts
Fixed a bug when links within chat always lead to native ws of the object
---
> [!IMPORTANT]
---
```
``` …
=> RELATED: GDAI-13 chat links

libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx
Fix a bug when chat used attribute instead of label for filters
---
> [!IMPORTANT]
---
```
``` …
=> RELATED: GDAI-30 use display form in filters

libs/sdk-ui-dashboard/src/plugins/customizationApis/filterBarCustomizer.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/layoutCustomizer.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/loadingCustomizer.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/layoutCustomizer.test.tsx.snap, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/loadingCustomizer.test.tsx.snap, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/titleCustomizer.test.tsx.snap, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/topBarCustomizer.test.tsx.snap, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/filterBarCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/layoutCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/loadingCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/titleCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/topBarCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/titleCustomizer.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/topBarCustomizer.tsx
Param embedded dashboard hideControl=[filterBar] didn't work after Tiger 3.27.0
risk: low
JIRA: F1-1076
---
> [!IMPORTANT]
---
```
```
-   `--isolated` …
=> fix: embedded dashboard hideControl=[filterBar] didn't work

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadAccessibleDashboardList.ts
hidden under the same feature flag as previous deferred actions
risk: low
JIRA: STL-1104
---
> [!IMPORTANT]
---
```
``` …
=> feat: defer loading of dashboards list

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/utils/date.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/utils/tests/utils.test.ts
Show wrong startOn and Repeats when using timezone Africa/Abidjan
risk: low
JIRA: F1-1092
---
> [!IMPORTANT]
---
```
``` …
=> fix: show wrong startOn and repeats for specific timezone

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
new dashboard is defacto edit mode, load dashboards similarly as catalog
risk: low
JIRA: STL-1119
---
> [!IMPORTANT]
---
```
``` …
=> fix: new dashboard needs dashboardslist loaded

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/customBackend/execution.ts, libs/sdk-backend-base/src/decoratedBackend/execution.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-base/src/normalizingBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/execution/index.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/AbstractProvider.test.ts.snap, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/ComparisonProvider.test.ts.snap
Add support for execution cancelling in `sdk-backend-spi` and relevant backend implementations.
risk: low
JIRA: F1-1096
---
> [!IMPORTANT]
---
```
```
- …
=> feat: add core support for execution cancelling

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/accessibleDashboardsSelectors.ts, libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/index.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/types.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
This will prevent showing incomplete drill options
when clicked before dashboardslist finished loading.
risk: low
JIRA: STL-1122
---
> [!IMPORTANT]
---
```
``` …
=> fix: activate drilling after dashboardslist is loaded

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/useDashboardInsightDrills.ts
This condition was forgotten in #5944.
risk: low
JIRA: STL-1122
---
> [!IMPORTANT]
---
```
``` …
=> fix: correctly enable drilling when dashboards list is loaded

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/dashboardInitialize.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/__snapshots__/adhocDashboard.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/__snapshots__/dashboardInitialize.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/tests/dashboardInitialize.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/deleteDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/model/react/types.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaReducers.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaState.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-loaders/api/sdk-ui-loaders.api.md, libs/sdk-ui-loaders/src/dashboard/types.ts
Implementation for support adhoc items on dashboard in SDK now
risk: low
JIRA: F1-1107
---
> [!IMPORTANT]
---
```
``` …
=> fix: adhoc dashboard for export

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/utils/tests/utils.test.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-pivot/src/CorePivotTable.tsx, libs/sdk-ui-pivot/src/impl/data/dataSource.ts, libs/sdk-ui-pivot/src/impl/tableFacade.ts, libs/sdk-ui-pivot/src/impl/tableFacadeInitializer.ts, libs/sdk-ui-pivot/src/publicTypes.ts, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/repeater.test.tsx.snap, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/react/CancelablePromise.ts, libs/sdk-ui/src/base/react/PromiseCache.ts, libs/sdk-ui/src/base/react/tests/CancelablePromise.test.ts, libs/sdk-ui/src/base/react/useCancelablePromise.ts, libs/sdk-ui/src/execution/withExecutionLoading.tsx
Add support for execution cancellation in PivotTable and Repeater.
risk: low
JIRA: F1-1109
---
> [!IMPORTANT]
---
```
```
-   `--isolated` The command …
=> feat: cancel executions in PivotTable/Repeater

common/changes/@gooddata/sdk-ui-all/mkn-f1-1112_2025-02-25-09-21.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/execution/DataViewLoader.tsx, libs/sdk-ui/src/execution/Execute.tsx, libs/sdk-ui/src/execution/ExecuteInsight.tsx, libs/sdk-ui/src/execution/RawExecute.tsx, libs/sdk-ui/src/execution/useExecutionDataView.ts, libs/sdk-ui/src/execution/useInsightDataView.ts, libs/sdk-ui/src/execution/withExecution.ts, libs/sdk-ui/src/execution/withExecutionLoading.tsx
Add support for execution cancelling to all execution public APIs:
- React hooks
- React higher order components
- React execute components
- DataViewLoader
risk: low
JIRA: F1-1112
---
> [!IMPORTANT]
---
```
```
-   `--integrated` …
=> feat: execution cancelling in public API

libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts
Replace wrong `useSelector` with correct `useDashboardSelector`.
risk: low
JIRA: F1-1118
---
> [!IMPORTANT]
---
```
``` …
=> fix: use proper selector function

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillModalRawExportOptions.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx
- Fix issue when export RAW data with Ranking Filter.
- Always allow to export RAW data.
JIRA: LX-826, LX-829
---
> [!IMPORTANT]
---
```
```
- …
=> fix: raw export fixes

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: move recording-unstable depfilters tests to checklist

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts
If a filter was created before the introduction of the ‘support duplicated label values’ feature, it is migrated to the new configuration ad hoc during initialization. Previously, the new configuration was only propagated to the filter’s parent application when the user opened the filter, made changes, and applied them.
After the change, the migration is now detected during filter initialization and reported immediately.
There are some consequences:
- If dashboard component starts in edit mode, Save button is enabled if filter was migrated. This does not happen in view mode.
- Filters can be stored in filter view in the old format when user save view quicker than all filters load values and mark themselves as "initialized: success"
JIRA: LX-824
risk: low
---
> [!IMPORTANT]
> Please, …
=> fix: propagate ad hoc displayAsLabel migrated attr filter immediately

libs/sdk-backend-base/src/normalizingBackend/normalizer.ts, libs/sdk-backend-base/src/normalizingBackend/tests/__snapshots__/withNormalization.test.ts.snap, libs/sdk-backend-base/src/normalizingBackend/tests/withNormalization.test.ts
risk: low
JIRA: F1-1131
---
> [!IMPORTANT]
---
```
``` …
=> fix: normalizing backend execution break definition of filters

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
Configs (Map, Group) always be disabled if it opens before GEO loaded
risk: low
JIRA: F1-1135
---
> [!IMPORTANT]
---
```
``` …
=> fix: configs always be disabled if it opens before GEO loaded

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/migratedAttributeFilters.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts
Ad-hoc updated attribute filters were saved only when dashboard changes were saved from edit mode. When dashboard copy was created via Save as function, the changes to filter context were lost. Attribute filter configs were kept. The fix allows the migrated filters to be saved even from view mode.
JIRA: LX-845
risk: low
---
> [!IMPORTANT]
---
```
extended-test --backstop | …
```
=> fix: save ad-hoc migrated attribute filters via Save as dashboard

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/migratedAttributeFilters.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts
The fix that allows saving of ad-hoc migrated filters in view mode when user enters the edit mode enables Save button also when user applied cross filter for an attribute with non-primary label. The fix skips such filters to be considered as migrated.
This means that if filter is migrated in view mode and then cross filter is applied on it, the filter will not be part of saved set that can be saved in edit mode. However, this is not a problem as user can migrate this filter the next time he will enter the edit mode when the cross filter was not used.
JIRA: LX-846
risk: low
---
> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** or **significant changes** 🙏 This information is used to generate the [change …
=> fix: do not enable Save button in edit mode for cross filters

common/config/rush/command-line.json, common/scripts/publish-local.js
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> chore: add script to local publish

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/src/model/commands/index.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts
Additionally, reset filter context button is not enabled when ad-hoc migration happen.
To achieve this behavior, the apply payload from attribute filter, that is used to propagate the migrated filter data, is marked as emitted via migration process. Not only the current state is changed in reducer but also something called originalFilterContext. This state is used to compare filters by reset button, by automation dialog code, and by last filter state in KD. For some reason, when dashboard is being saved, filter context from persisted dashboard state is used, therefore migrated filters are still detected as "changed" and Save button is enabled. Effectively, persisted state of filter context was at two places for some reason, and each place has never been updated, until know. It's weird but …
=> fix: reset filter button do not reset before ad-hoc migration state

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/dashboards.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
when try searching or checking somethings on attribute filter, the filter often works unstable because dashboard hasn't done loading yet or widget is still loading
=Solution: wait for the dashboard and widget loading done before doing actions of attribute filter
---
> [!IMPORTANT]
---
``` …
```
=> test: stabilize dependent filter tests

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts
The reset function used when existing dashboard changed a render mode used original filter context that contained migrated filters in every switch of said render mode. This caused loss of freshly persisted edit state when dashboard returned to view mode. The state was not lost per se but wrong state was shown (the one having migrated filters but not the changes from edit mode). When user saves changes, the new state is correct and there is no reason to pass these between modes any longer. Original reset handler functionality may be used now. The new condition ensures that filter context snapshot is used only when there are some filters that were migrated.
JIRA: LX-947
risk: low
---
> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new …
=> fix: keep filters added in edit mode when getting back to view mode

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
This allows the users to override the column names in the raw exports.
JIRA: CQ-1139
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat: allow passing customOverrides to raw export

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/insights/insightsSelectors.ts
Ensure the raw exports have the column names set to what the user actually sees in the UI.
JIRA: CQ-1139
risk: low
---
> [!IMPORTANT]
---
```
```
- …
=> feat: provide custom overrides in dashboard raw exports

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/CreationPanel.tsx
The new feature flag is necessary to roll out the current flexible layout renderer without fixing all the nesting issues. The containers can be created only when the new ff is enabled.
JIRA: LX-770
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen …
=> feat: hide flexible layout New container link behind a new ff

libs/sdk-ui-dashboard/src/presentation/widget/description/DescriptionClickTrigger.tsx, libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss, libs/sdk-ui-dashboard/styles/scss/descriptionPanel.scss, libs/sdk-ui-dashboard/styles/scss/kpi_alert_dialog.scss, libs/sdk-ui-dashboard/styles/scss/main.scss
Allow truncated tooltips be higher then dashboard header
JIRA: LX-789
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: override zindex when truncated

libs/sdk-ui-charts/src/highcharts/ChartTransformation.tsx, libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
* Wrapped the side effects into useEffect in sdk-ui-charts
* Reverted the hackish fix in sdk-ui-gen-ai
---
```
```
-   `--filter` (Optional) A comma-separated list of test files to run. This parameter is valid only for the `--integrated`, `--isolated`, and `--record` …
=> RELATED: GDAI-108 Handle side effects in visualization wrapper

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
Fixed a bug when UI throws an error when visualization definition does not exist
---
```
```
-   `--filter` (Optional) A comma-separated list of test files to run. This parameter is valid only for the `--integrated`, `--isolated`, and `--record` commands.
```
extended-test …
```
=> RELATED: GDAI-131 uncaught error

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
```
```
-   `--filter` (Optional) A comma-separated list of test files to run. This parameter is valid only for the `--integrated`, `--isolated`, and `--record` commands.
```
extended-test --backstop
extended-test --integrated
extended-test --integrated --filter …
```
=> RELATED: GDAI-108 Allow user to save visualizations that triggered NO_DATA error

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/slideshow/layoutTransformer.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/layoutCustomizer.tsx, libs/sdk-ui-dashboard/src/presentation/widget/richText/ExportModeDashboardRichText.tsx, libs/sdk-ui-dashboard/styles/scss/richTextWidget.scss
[Export mode] Rich text height should be full height of the dedicated space [Export mode] Do not apply transformations when single widget export
Access publicly getFilterContextByExportId
risk: low
JIRA: F1-1199
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run …
=> fix: multiple bug fixes

libs/sdk-ui-dashboard/src/_staging/dashboard/dashboardFilterContext.ts, libs/sdk-ui-dashboard/src/_staging/dashboard/defaultFilterContext.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/dashboardInitialize.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-loaders/src/dashboard/useDashboardLoader.ts
This is implementation of support using exportid also in case that we are empty dashboard. This is combined with initial content where some visualisation are loaded to dashboard on start, and also we need to load filters on start.
risk: low
JIRA: GDP-2903
---
> [!IMPORTANT]
---
``` …
```
=> fix: support exportid also on new dashboard

.github/pull_request_template.md, .github/workflows/pull-request-comment.yaml, .github/workflows/rw-rush-build-e2e-tests-backstop.yml, .github/workflows/test-backstop.yml, libs/sdk-ui-tests/backstop/backstop-cleanup-artifacts.cjs
JIRA: STL-1259
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat: allow running full backstop

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/render/types.ts, libs/sdk-ui-dashboard/src/model/events/render.ts, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/model/tests/DashboardTester.ts
So we can subtract `asyncRenderResolvedTimeout`
from performance metrics.
risk: low
JIRA: STL-1064
---
> [!IMPORTANT]
---
```
``` …
=> feat: send also configuration with rendered event

.github/workflows/pull-request-comment.yaml
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> chore: enable legacy PR command for BEAR

libs/sdk-ui-tests-e2e/.env.template, libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> chore: change backend for isolated records

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/export/types.ts, libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutExportSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutViewSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutExportSectionHeaderRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeader.tsx, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
lost data references in section descriptions when exporting slides dashboard to PPTX/PDF
risk: low
JIRA: F1-1253
---
> [!IMPORTANT]
---
```
``` …
=> fix: lost data references in section descriptions

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/automations/index.ts, libs/sdk-model/src/execution/filter/index.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/dashboard/dashboardFilterConverter.ts, libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultLoadingScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/DashboardAttachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/WidgetAttachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/styles/scss/automationFilters.scss, libs/sdk-ui-dashboard/styles/scss/main.scss, libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
- feature is behind enableAutomationFilterContext FF
- all dashboard filters are cloned in scheduling dialog
- filters can be changed or removed
- visible filters are stored in automation metadata
- visible filters describe localId and title used on server
JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
``` …
```
=> feat: use automation filter context in scheduling dialog

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/errors/index.ts, libs/sdk-backend-tiger/src/utils/errorHandling.ts
* Handle the DataTooLargeError in errorHandling.ts so that it is created when an appropriate error flies from the backend.
* Boy-scout rule: improve getTraceId function. Simplify it and declare its return type properly. The old way would fail once we move to TypeScript >= 5.8.
* Boy-scout rule: unify convertApiError. This is always used in a throw statement, so the `return` is the correct statement here.
JIRA: CQ-1151
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific text on the pull …
=> feat: allow passing raw data to DataTooLargeError

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
This is to make the rollout of rich too many datapoints errors safer.
JIRA: CQ-1151
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to run integrated tests against …
=> feat: add enableRichTooManyDatapointsErrors feature flag

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertTitle.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dropdown/DropdownList.tsx, libs/sdk-ui-kit/src/Form/InputPure.tsx, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectSearchBar.tsx, libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
Remove `ariaLabel` prop and use generic interface `AccessibilityConfig`.
risk: low
JIRA: LX-1058
---
> [!IMPORTANT]
---
```
``` …
=> feat: use generic accessibility interface

libs/sdk-ui-dashboard/src/_staging/dashboard/dashboardFilterContextValidation.ts
When attribute filter in filter context
provided to overrideDefaultFilters contains multiple values, but configuration for this filter in saved dashboard is single select, keep the filter as single select and do not convert it to multi select.
risk: low
JIRA: F1-1198
---
> [!IMPORTANT]
---
``` …
```
=> fix: dashboard overrideDefaultFilters

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
JIRA: F1-1291
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: omit date filter local identifiers when undefined

libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilterContext.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
Avoid full re-init of the attribute filter on each change.
Propagate additional data to attribute filter sub-components via context, rather than via useMemo.
risk: low
JIRA: F1-1249
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with …
=> fix: automation attribute filters reloading

libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
Correct header name for cancel token,
so it can be properly propagated to the result retrieval request.
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: cancel token propagation

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
- use initial automation filters in all necessary hooks as these filters store the main filter information in schedule
- consider hidden filters when checking if any filter is missing on dashboard
- respect ignored widget filters by default
- add all time date filter when it is not present
- filter out all-valued widget filters when FF is on
JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific text on the pull request. It is possible to trigger multiple commands …
=> fix: rework automation filters logic

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartThresholds.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/__snapshots__/chartThresholds.test.ts.snap, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartThresholds.test.ts
When zone changed from dashed to solid, the threshold point
was placed correctly. When zone changed from solid to dashed,
the threshold point was on index+1 than it should be. Technically,
the placement was correct but it was misleading.
Also, fix issue when threshold measure was rendered when
no zone was generated.
JIRA: LX-1072
risk: low
---
> [!IMPORTANT]
---
```
extended-test …
```
=> fix: place threshold zones at correct index

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
Multiple date filter didn't change when accessing DB with automationId
risk: low
JIRA: F1-1292
---
> [!IMPORTANT]
---
```
``` …
=> fix: multiple date filters with automationId

examples/sdk-interactive-examples/examples-template/vite.config.js, examples/sdk-interactive-examples/examples/example-attributefilter/vite.config.js, examples/sdk-interactive-examples/examples/example-chartconfig/vite.config.js, examples/sdk-interactive-examples/examples/example-columnchart/vite.config.js, examples/sdk-interactive-examples/examples/example-combochart/vite.config.js, examples/sdk-interactive-examples/examples/example-dashboard/vite.config.js, examples/sdk-interactive-examples/examples/example-datefilter/vite.config.js, examples/sdk-interactive-examples/examples/example-dependentfilters/vite.config.js, examples/sdk-interactive-examples/examples/example-execute/vite.config.js, examples/sdk-interactive-examples/examples/example-granularity/vite.config.js, examples/sdk-interactive-examples/examples/example-headline/vite.config.js, examples/sdk-interactive-examples/examples/example-pivottable/vite.config.js, examples/sdk-interactive-examples/examples/example-relativedatefilter/vite.config.js, examples/sdk-interactive-examples/examples/example-repeater/vite.config.js
This would allow running examples in csb
risk: low
JIRA: STL-1305
---
> [!IMPORTANT]
---
```
```
- …
=> fix: add codesandbox to examples allowed hosts

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: convert filters ids to afm obj ids in visual automation

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
This reverts commit eda4973c74433a6732bd134511aba9ac299a5b82.
---
> [!IMPORTANT]
---
```
```
- …
=> Revert "fix: convert filters ids to afm obj ids in visual automation"

common/changes/@gooddata/sdk-ui-all/ovel-drill-ctx-insight-body_2025-04-28-16-02.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/drill/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/DashboardInsightWithDrillDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
- so dashboard InsightBody customizations can behave based on drill context
JIRA: MC-3609
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat(sdk-ui-dashboard): pass drillStep into InsightBody

libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/@ui/UiListbox/UiListbox.tsx, libs/sdk-ui-kit/src/@ui/UiListbox/tests/UiListbox.test.tsx, libs/sdk-ui-kit/src/@ui/UiListbox/types.ts
risk: low
JIRA: LX-1038
---
> [!IMPORTANT]
---
```
``` …
=> fix: add s-classes to the visualization switcher

libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-backend-tiger/src/backend/workspace/automations/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/exportDefinitions/exportDefinitionsQuery.ts, libs/sdk-backend-tiger/src/backend/workspace/exportDefinitions/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ExportMetadataConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
---
> [!IMPORTANT]
---
```
```
- …
=> automation filter ids conversion (SDK -> AFM)

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
- cross filtering should be removed when filter context changes
- the same already happens in specific attr and date filter handlers
JIRA: F1-1083
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: reset cross filtering when filter context changes

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md, libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatOverlay.tsx, libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx, libs/sdk-ui-gen-ai/src/components/messages/MessageContents.tsx, libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx, libs/sdk-ui-gen-ai/src/hooks/useGenAIStore.ts, libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json, libs/sdk-ui-gen-ai/src/store/chatWindow/chatWindowSelectors.ts, libs/sdk-ui-gen-ai/src/store/chatWindow/chatWindowSlice.ts, libs/sdk-ui-gen-ai/src/store/index.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/index.ts, libs/sdk-ui-gen-ai/src/store/sideEffects/loadColorPalette.ts, libs/sdk-ui-gen-ai/src/store/store.ts, libs/sdk-ui-gen-ai/styles/scss/agentIcon.scss, libs/sdk-ui-gen-ai/styles/scss/messages.scss, libs/sdk-ui-gen-ai/styles/scss/window.scss, libs/sdk-ui-kit/src/Header/Header.tsx, libs/sdk-ui-kit/src/Header/HeaderChatButton.tsx, libs/sdk-ui/src/base/localization/bundles/en-US.json
Chatbot does not respect color palette when rendering charts Some other theming issues
risk: low
JIRA: GDAI-197
---
> [!IMPORTANT]
---
```
``` …
=> fix: chatbot does not respect color palette

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/DialogBase.tsx, libs/sdk-ui-kit/src/Dialog/DialogCloseButton.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareGranteeBase.tsx, libs/sdk-ui-kit/src/Dialog/typings.ts
---
> [!IMPORTANT]
---
```
```
- …
=> fix: dialog close button label + dialog returns focus on close

libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts, libs/sdk-backend-tiger/src/cancelation/index.ts
- propagate cancel token header only if abort signal is provided
- remove axios cancel token, keep only abort signal
risk: low
JIRA: F1-1321
---
> [!IMPORTANT]
---
```
```
- …
=> fix: execution cancelling

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartThresholds.ts
The fix of legend was applied only when zones were generated. When threshold series was hidden, and index was broken, it was not fixed in this case.
Also, "fix" for zones were removed from stacked chart where it did not make sense as there are no series omitted from rendering (just odd or even numbers from each series and instead categories are filtered out). Legend contains attribute segments, not metrics names anyway.
JIRA: LX-1090
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific …
=> fix: fix legend index even when no threshold zones are generated

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/customBackend/execution.ts, libs/sdk-backend-base/src/decoratedBackend/execution.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-base/src/eventingBackend/index.ts, libs/sdk-backend-base/src/normalizingBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/execution/index.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts, libs/sdk-ui-pivot/src/CorePivotTable.tsx, libs/sdk-ui-pivot/src/impl/data/dataSource.ts, libs/sdk-ui-pivot/src/impl/tableFacade.ts, libs/sdk-ui-pivot/src/impl/tableFacadeInitializer.ts, libs/sdk-ui-pivot/src/impl/tests/tableFacade.fixture.ts
fix: execution canceling
- Allow override signal of the execution result if needed
- If the execution result is cached, replace its signal
with the current one, so abort signal is always up to date,
even for cached results
- If the signal was aborted, do not use cached result and fetch again
- Always use up to date abort signal in PivotTable
- Correct `.equals()` execution method to use fingerprint
risk: low
JIRA: F1-1319
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific text on the pull …
=> fix: execution canceling

libs/sdk-ui-dashboard/src/model/store/automations/automationsSelectors.ts
Fixed an issue where alerts were incorrectly displaying in the scheduled exports dialog. The issue was caused by alerts having both the schedule and alert properties.
- Updated selectors to properly filter alerts vs scheduled exports
risk: low
JIRA: F1-1344
---
> [!IMPORTANT]
---
``` …
```
=> fix: remove schedule property from alerts

common/changes/@gooddata/sdk-ui-all/ovel-fix-dependent-filter-in-apply-all_2025-05-13-13-21.json, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/AttributeFilterStatusBar.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/SingleSelectionAttributeFilterStatusBar.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/types.ts, libs/sdk-ui-filters/src/AttributeFilter/Components/index.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterHandler.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/factory.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/common/selectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadIrrelevantElements/loadIrrelevantElementsSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/state.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/types.ts
- in attribute filters
JIRA: MC-3609
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--isolated` The command …
=> fix(sdk-ui-filters): irrelevant values when apply all at once

libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationFiltersSelect.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts
- find the correct display forms for filters
JIRA: F1-1376
risk: low
---
> [!IMPORTANT]
---
```
```
- …
=> fix: add automation filter with correct display form

libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
JIRA: F1-1364
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: do not show hidden filters in automation filters select

libs/sdk-backend-base/src/normalizingBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/cancelation/index.ts, libs/sdk-ui-dashboard/src/model/react/useWidgetFilters.ts
Use proper equality check for widget ref.
Make export work with execution cancellation.
risk: low
JIRA: F1-1343
---
> [!IMPORTANT]
---
```
``` …
=> fix: automation filters

common/changes/@gooddata/sdk-ui-all/ovel-fix-reload-filter-after-search_2025-05-19-10-14.json, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts
- attribute filter
- it will maybe load twice in some cases, but Im not able to improve without huge refactoring
JIRA: MC-3698
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` …
=> fix(sdk-ui-filters): reload filter when closing with search

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useExecutionTimestampMessage.ts
- rely only on BE settings when formatting timestamp message
JIRA: F1-1229
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: ignore browser timezone

common/changes/@gooddata/sdk-ui-all/ovel-fix-storybook-StatusBar_2025-05-20-09-37.json, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdownActions.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdownBody.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelect.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/AttributeFilterStatusBar.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/types.ts, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/types.ts
- AttributeFilterStatusBar is not expected to use context
JIRA: LX-935
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix(sdk-ui-filters): failing storybook tests

libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/@ui/UiChip/UiChip.tsx
JIRA: F1-1380
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: do not propagate delete action to parent in automation filters

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartThresholds.ts
The code could get into a cycle of failing re-renders when reference point is invalid at some point when removed segmented threshold metric is being undo/redo in AD.
JIRA: LX-991
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally …
=> fix: add guard against invalid reference point in segmented threshold

libs/sdk-ui-kit/src/@ui/UiMenu/hooks.tsx, libs/sdk-ui-kit/src/@ui/UiMenu/tests/UiMenu.test.tsx
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: Handle UiMenu submenu wrapped in a group

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
- this shows new alert dialog even when date filters do not have local ids
- filters are not rendered in such case
JIRA: F1-1351
risk: low
---
> [!IMPORTANT]
---
```
```
- …
=> fix: use less strict automation context feature flag

common/scripts/ci/run_cypress_integrated_tests.sh
JIRA: QA-24815
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> test: enable COLOR for cypress test console log

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/loader.ts
JIRA: LX-1123
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: handle reset of filter by parent during init load phase

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToExcelHandler.ts, libs/sdk-ui-dashboard/src/model/commands/dashboard.ts, libs/sdk-ui-dashboard/src/model/commands/index.ts, libs/sdk-ui-dashboard/src/presentation/dialogs/ExportDialogProvider.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Dialog/ExportDialogBase.tsx, libs/sdk-ui-kit/src/Dialog/typings.ts
- Added `mergeHeaders` and `exportInfo` options to the `IDashboardExportTabularOptions` interface.
- Updated the export functionality to include these new options in the Excel export request.
- Enhanced the export dialog to allow users to select these options when exporting dashboards.
- Create new selector to check if filters are changed. The logic was moved from useResetButton hook.
JIRA: F1-1439
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a comment with specific text on the pull request. It is …
=> feat: enhance dashboard xlsx export

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsData.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardAlerting/useDashboardAlertsData.ts
Do not check for alert or schedules count to display "Show alerts" or "Show schedules" in dashboard menu items.
Other validations are still in place.
risk: low
JIRA: F1-1354
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with keeping …
=> fix: schedule/alert menu items visibility

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/hooks/useSaveAlertToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts
- Keep all-time date sanitization when enableAutomationFilterContext is not enabled.
risk: low
JIRA: F1-1444
---
> [!IMPORTANT]
---
```
``` …
=> fix: sanitize all-time date filters

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToExcelHandler.ts, libs/sdk-ui-dashboard/src/model/commands/dashboard.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useExportDashboardToExcel.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
- Introduced `widgetIds` parameter to the `IDashboardExportTabularOptions` interface for more granular control over exported widgets.
- Updated the Excel export function to accept `widgetIds`, allowing users to specify which widgets to include in the export.
JIRA: F1-1439
risk: low
---
> [!IMPORTANT]
---
``` …
```
=> feat: enhance widget xlsx export

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/filter/filterMerge.ts, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/hooks/test/validateExistingAutomationFilters.test.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/hooks/useValidateExistingAutomationFilters.ts, libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
- Fix case with second date filter with the same date dataset as the one set on the widget (common date filter).
risk: low
JIRA: F1-1446
---
> [!IMPORTANT]
---
```
```
-   `--integrated` …
=> fix: widget automation filters

libs/sdk-ui-dashboard/setupTests.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/AddFilterView.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-filters/setupTests.ts, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterHeader.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/setupTests.ts, libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx, libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.tsx, libs/sdk-ui-kit/src/utils/domUtilities.ts, libs/sdk-ui-kit/src/utils/useAutofocusOnMount.tsx, libs/sdk-ui-vis-commons/src/legend/PopUpLegend/LegendDialog.tsx, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/index.tsx, libs/sdk-ui/src/base/react/useCombineRefs.ts
risk: low
JIRA: LX-1034
---
> [!IMPORTANT]
---
```
``` …
=> feat: Allow focusing back button when creating a saved view

libs/sdk-ui-gen-ai/src/components/ConfigContext.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx, libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
Fixed a bug when user with ANALYZE
permission could not save visualization
in AI Assistant
risk: nonprod
jira: GDAI-288
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to …
=> RELATED: GDAI-288 analyzer can save vis

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json
JIRA: QA-24922
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> fix: wrong assertion in export pdf test when upgrading highchart

libs/sdk-ui-vis-commons/styles/scss/legend.scss
The issue can be replicated only when page is being exported and page scale is 0.85.
JIRA: LX-837
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: prevent chart legend overflowing during export

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPdfPresentationHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPptPresentationHandler.ts, libs/sdk-ui-dashboard/src/model/commands/dashboard.ts, libs/sdk-ui-dashboard/src/model/commands/index.ts
Allow extra options / overrides
in the export dashboard to presentation commands.
risk: low
JIRA: F1-1477
---
> [!IMPORTANT]
---
```
``` …
=> feat: export dashboard to presentation commands

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/useInsightPositionStyle.ts
Switching between relative and absolute positioning of headline causes text flickering (infinite render loop where relative position changes font size that changes insight dimension, causing it change to absolute, which changes font size that changes insight dimension, and repeat...) when viewport width is changed to mobile size. It looks like absolute positioning works in all cases in flexible layouts, therefore this logic is disabled when new layout engine is enabled.
JIRA: LX-1144
risk: low
---
> [!IMPORTANT]
---
Commands …
=> fix: use absolute position of headline in flexible layout

libs/sdk-ui-pivot/src/impl/structure/headers/ColumnHeader.tsx
Otherwise menu blinks which is breaking AD tests
JIRA: LX-1036
risk: low
---
> [!IMPORTANT]
---
```
```
- …
=> fix: handle onBlur only when there is no menu

common/changes/@gooddata/sdk-ui-all/pji-metadata-locale_2025-06-09-13-19.json, libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-spi/src/user/settings/index.ts, libs/sdk-backend-spi/src/workspace/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-backend-tiger/src/backend/settings/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat: add method to set metadata locale to settings services

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertAttributeSelectOld.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
- this brings back historical version of AlertAttributeSelect
- edit alert is used when old automation filters is not turned on and uses all necessary
test selectors
- can be removed on enableAutomationFilterContext is on
JIRA: F1-1381
risk: low
---
> [!IMPORTANT]
---
```
```
- …
=> fix: use old alert attribute select in old edit alert dialog

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/automations.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/automations/index.ts, libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/_staging/automation/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/loadAutomations.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/refreshAutomationsHandlers.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialogNew.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
- when external recipient is provided to dashboard, we filter automations by the recipient
- recipient is pre filled in automation dialogs
- recipients dropdown is empty is such case
JIRA: F1-1316
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen …
=> feat: filter automations by external recipient

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/richTextMenu/DefaultDashboardRichTextMenu/DashboardRichTextMenu/DashboardRichTextMenuContainer.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/insightConfiguration.scss, libs/sdk-ui-dashboard/styles/scss/layout.scss, libs/sdk-ui-dashboard/styles/scss/richTextWidget.scss
- widget option btn does not overlap section description in view mode
- widget option btn does not overlap insight title in edit mode
- widget option button is better aligned in both modes
- widget option menu is aligned to the button in both modes
- rich text widget menu style is aligned with insight widget one
JIRA: LX-780
risk: low
---
> [!IMPORTANT]
---
```
extended-test …
```
=> fix: widget options button and menu position

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/useItemWidthValidation.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx, libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss, libs/sdk-ui-dashboard/styles/scss/layout.scss
JIRA: LX-780
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: overflowing insight title of widget in edit mode

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, docs/config/_default/config.toml, docs/content/en/latest/CodeMirror6_GenAI_Integration.md, examples/playground/vite.config.ts, tools/react-app-template/package.json, tools/react-app-template/src/index.tsx, tools/react-app-template/webpack.config.cjs
- Add new documentation for CodeMirror 6 integration with GenAI Chat component
- Update Vite configuration to properly handle CodeMirror dependencies:
- Add @codemirror/state and @codemirror/view to exclude list
- Add deduplication for CodeMirror packages to prevent duplicate instances
- Update playground example to demonstrate GenAI Chat component:
- Replace Playground component with GenAI Chat component
- Add necessary imports for GenAI Chat
- Update documentation navigation to include link to new CodeMirror integration guide
- Update webpack configurations in template for proper CodeMirror support
This change ensures proper functionality of code editing capabilities within the GenAI chat interface by preventing duplicate package instances of CodeMirror.
JIRA: GDAI-357
risk: low
---
> …
=> fix: autocomplete is not working in UI SDK.

libs/sdk-ui-gen-ai/styles/scss/messages.scss, libs/sdk-ui-gen-ai/styles/scss/window.scss, libs/sdk-ui-kit/styles/scss/syntaxHighlightingInput.scss
Custom theme - Dark themes affect the border and query text of AI Chatbot
JIRA: GDAI-384
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: dark themes affect the border and query text of chatbot

.github/workflows/checklist-integrated-staging.yaml
Moving sdk checklist that basic checking for sdk release to team-qa channel instead of panther-checklist-testing (where includes info of daily panther release)
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with keeping passing …
=> test: move sdk checklist to team qa channel

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts
- in individual apply mode when only working filter is changed
JIRA: LX-1061
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to run integrated tests against the …
=> fix(sdk-ui-dashboard): showing reset button when no change

libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
JIRA: F1-1521
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: correctly use onChange in automation attribute filter

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts
JIRA: F1-1521
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: do not reinit attribute filter when without apply mode is on

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/@ui/@utils/tests/keyboardNavigationTarget.test.tsx, libs/sdk-ui-kit/src/@ui/UiNavigationBypass/UiNavigationBypass.tsx, libs/sdk-ui-kit/src/@ui/UiNavigationBypass/tests/UiNavigationBypass.test.tsx, libs/sdk-ui-tests/stories/visual-regression/ui/UiNavigationBypass.tsx
Add a skip link to skip the chatbot history
risk: low
JIRA: GDAI-376
---
> [!IMPORTANT]
---
```
```
- …
=> fix: ai assistant not read correctly by screen readers

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerWidthSanitization.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveSectionItemHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveSectionItemToNewSectionHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/rowContainerSanitization.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardNestedLayoutWidget/Toolbar.tsx
JIRA: LX-1205
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> feat: change nested containers' direction and width when moved

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss
Issue is caused by re-render of charts during switching between loading animation and chart itself. Size of chart is changing rapidly between its min-height and size derived from height of whole slide. Sometimes this size change ends even in infinite loop.
I did not found root cause of this re-render - react-measure measures its container repeatedly with these two different heights. May be related to https://github.com/souporserious/react-measure/issues/150. This is triggered in moment when Loading animation should be hidden and visualization content shown.
So I decided to hide Loading animation in export mode not be not rendering it but just hiding it.
JIRA: LX-1165
risk: low
---
> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new …
=> fix: change hiding of loading animation in export mode

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/automation-json-api/api.ts, libs/api-client-tiger/src/generated/automation-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/FilterConverter.ts
- relative date filter bounds are now nullable
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--isolated` …
=> chore: regenerate api client

common/changes/@gooddata/sdk-ui-all/pdo-lx-1283-heigh-dropzone_2025-07-07-14-12.json, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/GridLayoutElement.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/WidgetDropZoneColumn.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/rowEndHotspotHelper.ts, libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss, libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss, libs/sdk-ui-tests-e2e/cypress/tools/enum/DropZone.ts
JIRA: LX-1283
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: make the last column drop zone take all the remaining space

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerWidthSanitization.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/toggleLayoutDirectionHandler.ts
JIRA: LX-1292
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: consider also parent when evaluating minimal width of children

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/headerSection.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/widget.ts
JIRA: QA-25211
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …
=> fix: update locator and scroll element into view before interacting

common/changes/@gooddata/sdk-ui-all/pdo-lx-1251-allow-resize-of-row-container_2025-07-10-13-14.json, common/changes/@gooddata/sdk-ui-all/pdo-lx-1251-allow-resize-of-row-container_2025-07-10-13-19.json, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/AddDashboardLayoutWidgetButton.tsx, libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx
JIRA: DP-3197
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: render row end hotspot only when a widget is dragged to fix the row height resizer offset

common/changes/@gooddata/sdk-ui-all/ine-lx-1328_2025-07-11-10-48.json, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.scss, libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.tsx, libs/sdk-ui-kit/src/@ui/UiMenu/hooks.tsx, libs/sdk-ui-kit/src/@ui/UiMenu/tests/UiMenu.test.tsx, libs/sdk-ui-kit/src/@ui/UiMenu/types.ts
Introduce new prop for menu max heigh and bottom padding
JIRA: LX-1328
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: remove obsolete UiMenu props

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/@ui/UiIconButton/UiIconButtonRenderer.tsx, libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx, libs/sdk-ui-kit/src/Form/InputPure.tsx
JIRA:F1-1565
risk:low
---
> [!IMPORTANT]
---
```
``` …
=> fix: aria attributes in Input, DropdownButton

common/changes/@gooddata/sdk-ui-all/ine-lx-prop-cleanup_2025-07-16-09-47.json, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts, libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
Props enableDashboardFiltersApplyModes and withoutApply where use both to manage the same feature. Keep only withoutApply.
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The …
=> feat: use only one prop instead of using two props meaning the same

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useFilterBarState.ts
Wrong react-measure props initialization caused its infinite onResize calling.
JIRA: LX-1352
risk: low
---
> [!IMPORTANT]
---
```
``` …
=> fix: prevent infinite re-render of filter bar

libs/sdk-ui-kit/src/DocumentHeader/DocumentHeader.tsx
risk: low
JIRA: STL-1572
---
> [!IMPORTANT]
---
```
``` …
=> fix: do not render favicon when null/empty

common/changes/@gooddata/sdk-ui-all/ine-clear-fix_2025-07-18-11-58.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextState.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/types.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts
---
> [!IMPORTANT]
---
```
```
- …
=> fix: handle switch to single mode, allow invalid selectin propagation and its handling
