libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
=> BUGFIX: TNT-1618 geo chart viewport not used in KD

libs/sdk-ui-pivot/src/impl/cell/cellRenderer.tsx
=> BUGFIX: TNT-1646 Fix rendering in dashboard

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/AttributeDisplayFormParameterDetail.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/ParameterDetail.tsx
=> BUGFIX: TNT-1587 custom url drill datetime enumerating

common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/boilerapp.spec.ts
=> FEATURE: QA-18623 update tag for test case boiler app

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
=> BUGFIX: TNT-1655 Update column headers position properly

libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx
=> BUGFIX: TNT-1489 Fix insight list tabs on bear after the recent refactor

libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/react/usePagedResource.ts, libs/sdk-ui/src/base/react/usePromiseCache.ts
_ cancel previous request result
_ increasing the debounce time out on the search field
JIRA: EGL-125
--- …
=> FEATURE: EGL-125 - improve search insight fields

libs/sdk-ui/src/base/react/usePromiseCache.ts
fix: improve search insight
_ reset the prventResetPromisesRef after receiving the search result
JIRA: EGL-125
--- …
=> BUGFIX: EGL-125 - improve search insight

libs/sdk-ui/src/base/localization/bundles/en-US.json
fix: update the error message on attribute filter dropdown
JIRA: EGL-171
--- …
=> BUGFIX: EGL-171 - update the error message on attribute filter dropdown

libs/sdk-ui-all/CHANGELOG.json, libs/sdk-ui-all/CHANGELOG.md
=> TRIVIAL: Fix typo in changelog

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardDateRelated.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardDependentFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/kpiConfiguration.ts, libs/sdk-ui-tests-e2e/cypress/tools/widget.ts
=> BUGFIX: QA-19770, QA-19776, QA-19774 Fix flaky tests

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dateFiltering.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/dateFilter.ts, libs/sdk-ui-tests-e2e/cypress/tools/enum/DateFilterValue.ts, libs/sdk-ui-tests-e2e/cypress/tools/kpi.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardForDateFilterScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19791 migrate G2C for DateFilteringTest.java

docs/content/en/latest/learn/integrate_and_authenticate/CN_and_cloud_authentication.md, docs/content/en/latest/learn/integrate_and_authenticate/_index.md
=> FEATURE: DC-2529 Add documentation for JWT authentication 

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1676 Enable transposition by default

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListCore.tsx, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/DraggableInsightList/DraggableInsightListItemWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/types.ts
=> BUGFIX: TNT-1667 Fix insight creation/update in local time on tiger dashboard

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/headlineBucketConversion.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/headlineConfigFromInsight.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline2.test.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/__snapshots__/PluggableHeadline2.test.tsx.snap, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/insightToPropsConverter/convertor.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/headlineUiConfigHelper.ts
=> FEATURE: EGL-133 Support generated code for multiple metrics and comparison config 

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1597 Set table total rows FF to true

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/sortItemsHelpers.ts, libs/sdk-ui-pivot/src/PivotTable.tsx
=> BUGFIX: TNT-1673 Ignore measure sort on transposed table

libs/sdk-ui-charts/src/charts/headline/internal/utils/BaseHeadlineTransformationUtils.ts
=> BUGFIX: EGL-190 correct order for drilling on secondary metrics

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/headline/headlineHelper.ts, libs/sdk-ui-charts/src/charts/headline/internal/utils/BaseHeadlineTransformationUtils.ts, libs/sdk-ui-charts/src/charts/headline/tests/headlineHelper.test.ts, libs/sdk-ui-charts/src/charts/index.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/ComparisonSection.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/values/numberFormat/NumberFormatControl.tsx, libs/sdk-ui-ext/src/internal/utils/comparisonHelper.ts
=> FEATURE: EGL-145 - comparison number format, support inherit

libs/sdk-ui-charts/src/highcharts/ChartTransformation.tsx, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartLimits.ts, libs/sdk-ui-geo/src/core/geoChart/GeoChartOptionsWrapper.tsx, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx
=> FEATURE: TNT-578 telemetry too many data points

.gitlab-ci.yml
=> BUGFIX: INFRA-2616 Update tools image to fix merge-back issue

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterControllerData.ts, libs/sdk-ui-filters/src/AttributeFilter/utils.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/index.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadAttribute/loadAttributeSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSelectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/utils.ts
=> FEATURE: TNT-1679 Load totalCount only for filters with parent

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/interfaces/comparison.ts, libs/sdk-ui-charts/src/interfaces/index.ts
=> BUGFIX: EGL-209 - support type is null for comparison format property

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartLimits.ts
=> BUGFIX: TNT-578 telemetry too many data points

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/headline/CoreHeadline.tsx, libs/sdk-ui-charts/src/charts/headline/headlineHelper.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/ComparisonProvider.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/ComparisonProvider.test.ts, libs/sdk-ui-charts/src/charts/headline/internal/providers/tests/__snapshots__/ComparisonProvider.test.ts.snap, libs/sdk-ui-charts/src/charts/headline/internal/tests/TestData.fixtures.ts, libs/sdk-ui-charts/src/charts/headline/internal/utils/ComparisonTransformationUtils.ts, libs/sdk-ui-charts/src/charts/headline/tests/headlineHelper.test.ts, libs/sdk-ui-charts/src/interfaces/comparison.ts, libs/sdk-ui-charts/src/interfaces/index.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/calculation/tests/CalculationControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/calculation/tests/CalculationListItemInfo.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/tests/ComparisonSection.test.tsx, libs/sdk-ui-ext/src/internal/constants/dropdowns.ts, libs/sdk-ui-ext/src/internal/utils/tests/comparisonHelper.test.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/headlineUiConfigHelper.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/headlineUiConfigHelper.test.ts, libs/sdk-ui-tests/scenarios/charts/headline/comparison.tsx
=> BUGFIX: EGL-212 - support calculation type as string

examples/sdk-examples/src/backend.ts, examples/sdk-examples/src/examples/basic/HeadlineExample.tsx, examples/sdk-examples/src/examples/chartResponsiveness/HeadlineResponsiveExample.tsx, examples/sdk-examples/src/examples/export/HeadlineExportExample.tsx, examples/sdk-examples/src/examples/timeOverTimeComparison/PreviousPeriodHeadlineExample.tsx
=> FEATURE: EGL-141 - update headline examples

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
- include GoodData.UI 9.1.0 and GoodData.CN 2.5.0 in the compatibility matrix table
JIRA: RAIL-5118
--- …
=> RELATED: RAIL-5118 Update GoodData.CN compatibility matrix

common/config/rush/pnpm-lock.yaml, libs/sdk-backend-base/package.json, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-pivot/src/impl/cell/tests/tableCell.test.tsx, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json
=> RELATED: RAIL-5116 update @gooddata/number-formatter and lru-cache

libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/ComparisonDataItem.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/colors/coloredItemsList/ColoredItemContent.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/calculation/CalculationListItem.tsx
=> FEATURE: EGL-136 - support automation test classes

libs/sdk-ui-charts/src/charts/headline/internal/utils/ComparisonTransformationUtils.ts
=> BUGFIX: EGL-231 - does not convert value to string for null/undefined values

.gitlab-ci.yml
=> CONFIG: NAS-5344 Bump image version to process also fast_track branch

libs/sdk-ui-charts/src/charts/headline/HeadlineProviderFactory.ts, libs/sdk-ui-charts/src/charts/headline/tests/HeadlineProviderFactory.test.ts, libs/sdk-ui-charts/src/interfaces/comparison.ts, libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline2.test.tsx, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-ext/src/internal/tests/mocks/testMocks.ts
=> FEATURE: EGL-131 migrate old headline to new comparison config

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
feat: adding the enableUnavailableItemsVisible configuration
JIRA: EGL-221
--- …
=> FEATURE: EGL-221 - adding the enableUnavailableItemsVisible configuration

common/config/rush/pnpm-lock.yaml, tools/react-app-template/package.json, tools/react-app-template/src/tests/smoke.test.ts
=> RELATED: RAIL-5119 merge rc to master

libs/sdk-ui-tests-e2e/cypress/tools/dashboards.ts
=> BUGFIX: QA-19775 Stablize dashboardDnD.spec.ts

common/changes/@gooddata/sdk-ui-all/ch1_2023-09-06-13-15.json, common/changes/@gooddata/sdk-ui-all/ch2_2023-09-06-13-16.json, common/changes/@gooddata/sdk-ui-all/ch3_2023-09-06-13-17.json, common/changes/@gooddata/sdk-ui-all/ch4_2023-09-06-13-22.json, common/changes/@gooddata/sdk-ui-all/ch5_2023-09-06-13-23.json, common/changes/@gooddata/sdk-ui-all/ch7_2023-09-06-13-27.json
=> RELATED:  RAIL-5119 add change logs

libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/calculation/tests/CalculationListItemInfoSection.test.tsx, libs/sdk-ui-ext/src/internal/translations/en-US.json
=> FEATURE: EGL-254 - update example for difference calculation

common/changes/@gooddata/sdk-ui-all/EGL-107_2023-09-07-05-55.json, common/changes/@gooddata/sdk-ui-all/EGL-107_2023-09-07-05-58.json, libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/headline/Headline.tsx, libs/sdk-ui-charts/src/interfaces/comparison.ts
=> FEATURE: EGL-135, EGL-245 - update comparison api-docs and add changelog for Headline improvements

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
=> FEATURE: EGL-250 update comparison properties only when FF is ON

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
JIRA: EGL-250
(cherry picked from commit c76dc0c26abc7b04a35bfa15fd9f8e6943190792)
--- …
=> BUGFIX: EGL-250 update comparison properties only when FF is ON

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/insightOnDashboard.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/widgetConfiguration.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardDateFilteringOnInsightScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19130 Migrate G2C DateFilteringOnInsightTest

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts
- status and filters were out of sync for some time, which affected fired execution
- change status in same step as setting query result
- two dependent queries need to be in a series
- only the last one triggers correct global status and render JIRA: TNT-1714
--- …
=> BUGFIX: TNT-1714 Fix execution by proper handling of dependent queries

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardKPI.spec.ts
=> BUGFIX: QA-19770 Stablize dashboardKPI test

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-bear/src/backend/workspace/accessControl/index.ts, libs/sdk-backend-bear/src/convertors/fromBackend/AccessControlConverter.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/backend/workspace/accessControl/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AccessControlConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/accessControl/index.ts, libs/sdk-model/src/index.ts
feat: re-generate the api client tiger
_ update the tiger and bear backend to support new types
JIRA: EGL-215
--- …
=> FEATURE: EGL-215 - re-generate the API client tiger

libs/sdk-ui-pivot/src/impl/data/dataSource.ts
=> BUGFIX: TNT-1632, TNT-1638 Update proper buckets totals if exist

libs/sdk-ui-pivot/src/CorePivotTable.tsx
=> BUGFIX: TNT-1632 Allow table to recover from error

libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/internal/components/dialogs/embedInsightDialog/EmbedInsightDialog.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/headlineConfigFromInsight.ts, libs/sdk-ui-ext/src/internal/interfaces/VisualizationDescriptor.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/headlineUiConfigHelper.ts, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/__snapshots__/headlineUiConfigHelper.test.ts.snap, libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/headlineUiConfigHelper.test.ts
=> FEATURE: EGL-206 - support theme for Headline color palette

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: EGL-271 enable new headline by default

libs/sdk-backend-tiger/src/backend/organization/styling.ts
=> FEATURE: SD-2929 Add optional id when create theme and colorPalette object

docs/go.mod, docs/go.sum
=> RELATED: WEB-3902 Bump dependencies

libs/sdk-ui-tests/scenarios/charts/headline/base.tsx, libs/sdk-ui-tests/scenarios/charts/headline/drilling.tsx, libs/sdk-ui-tests/scenarios/charts/headline/theming.tsx, libs/sdk-ui-tests/stories/visual-regression/visualizations/headline/index.tsx
=> TRIVIAL: EGL-271 - fix tests for legacy headline

libs/sdk-ui-ext/src/internal/translations/en-US.json
=> BUGFIX: TNT-1704 Column header translation typo

libs/sdk-ui-geo/styles/scss/main.scss, libs/sdk-ui-vis-commons/styles/scss/legend.scss
=> BUGFIX: TNT-1753 geo chart legend vertical separator

libs/sdk-backend-tiger/README.md
=> FEATURE: QA-19499 update documentation link sdk-backend-tiger

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drillDown.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/api.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/cypress/tools/drillToModal.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardTableDrillDownScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19905 migrate G2C KPIDashboardsDrillDownTest phase 1

docs/content/en/latest/_index.md, libs/sdk-ui-kit/src/Header/generateHeaderStaticHelpMenuItems.ts
=> BUGFIX: SD-2937 broken link to GoodData university

README.md, dev_docs/documentation.md
=> CONFIG: update readme

libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-left.svg, libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-right.svg, libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-top.svg, libs/sdk-ui-ext/src/internal/components/configurationControls/comparison/values/tests/ComparisonPositionControl.test.tsx, libs/sdk-ui-ext/src/internal/constants/dropdowns.ts, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/styles/internal/scss/dropdown_icons.scss
=> FEATURE: EGL-285 - support comparison position item icon

libs/sdk-ui-charts/src/charts/headline/internal/utils/ComparisonTransformationUtils.ts
=> BUGFIX: EGL-286 - prevent quaternary item is null

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drillDown.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/drillToModal.ts, libs/sdk-ui-tests-e2e/cypress/tools/table.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/ImplicitDrillScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19980 migrate G2C drilldown on table

libs/sdk-ui-pivot/src/impl/tableFacadeInitializer.ts
=> BUGFIX: TNT-1758 allow table to re-init when error

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pivotTableTransposed.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/table.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Insight/InsightTransposeScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/PivotTable/PivotTableTransposeScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-20139 write auto for Table Transpose - Insight View and Table Component

common/config/rush/.npmrc-publish
=> TRIVIAL: RAIL-5146 Use correct env variable in rush config

common/config/rush/.npmrc-publish
=> TRIVIAL: RAIL-5146 Set registry in rush config

common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh
=> RELATED: RAIL-5146 Propagate env variable with npm token

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> BUGFIX: EGL-305 - turn off FF enableNewHeadline

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> BUGFIX: EGL-305 - turn of ff enableNewHeadline

common/config/rush/.npmrc-publish, common/scripts/ci/do_publish.sh, common/scripts/ci/docker_rush.sh, common/scripts/ci/docker_rushx.sh
=> RELATED: RAIL-5146 Do not expose npm publish token

docs/config/_default/config.toml
=> TRIVIAL: fixing hugo compatibility

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, examples/sdk-examples/package.json
=> RELATED: RAIL-5133 fix release gooddata-ui-sdk-live-examples job

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
=> TRIVIAL: fixing table alignment

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
=> FEATURE: RAIL-5140 update compatibility table to 3.0

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
=> TRIVIAL: cherry-pick rc

common/changes/@gooddata/sdk-ui-all/EGL-189_2023-10-05-15-20.json
doc: add the changelog
_ dashboard share with all workspace users
JIRA: EGL-189
--- …
=> FEATURE: EGL-189 - add the changelog

libs/sdk-ui-all/CHANGELOG.json, libs/sdk-ui-all/CHANGELOG.md
=> Merge rc_8_12_3 into master

common/config/rush/pnpm-lock.yaml, libs/api-client-bear/package.json, libs/api-client-bear/src/caching/cachingClient.ts, libs/api-client-bear/src/caching/index.ts, libs/api-client-bear/src/caching/project.ts, libs/api-client-bear/src/caching/types.ts, libs/api-client-bear/src/caching/user.ts, libs/api-client-bear/src/caching/utils.ts, libs/api-client-bear/src/decoratedModules/index.ts, libs/api-client-bear/src/decoratedModules/project.ts, libs/api-client-bear/src/decoratedModules/types.ts, libs/api-client-bear/src/decoratedModules/user.ts, libs/api-client-bear/src/gooddata-browser.ts, libs/api-client-bear/src/gooddata-node.ts, libs/api-client-bear/src/gooddata.ts, libs/api-client-bear/src/project.ts, libs/api-client-bear/src/user.ts, libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/decoratedBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/organization.ts, libs/sdk-backend-base/src/decoratedBackend/organizations.ts, libs/sdk-backend-base/src/decoratedBackend/types.ts, libs/sdk-backend-bear/src/backend/index.ts
=> FEATURE: TNT-1700 Caching on bear client level

common/changes/@gooddata/sdk-ui-all/ine-tnt-1700_2023-10-05-12-30.json
=> RELATED: TNT-1700 Changelog

libs/sdk-ui-pivot/src/impl/drilling/drillIntersectionFactory.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json
=> BUGFIX: TNT-1767 Drilling when column headers on left

docs/config/public/params.toml, docs/layouts/index.redir, docs/layouts/partials/navbar.html
=> TRIVIAL: fixing versions to 9.2 + navbar

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline2.test.tsx, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts, libs/sdk-ui-ext/src/internal/tests/mocks/testMocks.ts
=> BUGFIX: EGL-301 migrate old headline in InsightOverlay

libs/sdk-ui-kit/src/ColorPicker/utils.ts
=> BUGFIX: TNT-1492 color picker drag javascript error

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drillDown.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/cypress/tools/drillToModal.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/HeatmapChartScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19982 migrate G2C drilldown on heatmap

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pivotTableTransposed.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/transposedPivotTableSizingAndReset.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/table.ts
=> FEATURE: QA-20138 write auto for Table Transpose - UI-SDK table resizing

libs/sdk-ui-loaders/package.json, tools/app-toolkit/package.json, tools/plugin-toolkit/package.json
=> RELATED: RAIL-5154 fix notice in files package.json

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> CONFIG: EGL-315 - turn on FF enableNewHeadline

libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-left.svg, libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-right.svg, libs/sdk-ui-ext/src/internal/assets/comparison/icon-position-top.svg
=> FEATURE: EGL-308 - update comparison position dropdown item icons

libs/sdk-backend-bear/src/uiSettings.ts
=> FEATURE: EGL-318 enable new headline by default in Bear

common/changes/@gooddata/sdk-ui-all/EGL-107_2023-10-12-16-01 .json, common/changes/@gooddata/sdk-ui-all/EGL-107_2023-10-12-16-02 .json
=> FEATURE: EGL-323 - add change-logs for headline improvement

.github/workflows/get-ecr-credentials.yml, .github/workflows/post-merge-pipeline.yml, .github/workflows/slack-post-merge-notification.yml
=> RELATED: FET-1242 github workflow for web components build

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/tableTranspose.spec.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardTableTransposeScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Insight/InsightTransposeScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-20140 write auto for Table Transpose - UI-SDK dashboard

libs/api-client-bear/src/caching/user.ts
Missing return statement.
JIRA: TNT-1794
---
| …
=> BUGFIX: TNT-1794 Fix logout on AD/KD

.github/workflows/post-merge-pipeline.yml
=> RELATED: FET-1242 setup group concurrency for workflow

libs/sdk-ui-tests-e2e/cypress.config.ts, libs/sdk-ui-tests-e2e/scripts/lib/test_results.js
Reverts gooddata/gooddata-ui-sdk#4234
=> Revert "FEATURE: QA-19538 Cypress: report file should be included test name"

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/sdk-ui-tests-e2e/cypress.config.ts, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests-e2e/scripts/lib/test_results.js
=> FEATURE: QA-19538 Cypress: report file should be included test name

common/config/rush/pnpm-lock.yaml, libs/sdk-backend-tiger/package.json, libs/sdk-ui-tests-e2e/package.json
=> BUGFIX: QA-20335 Bump version fixture

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/attributeFilterConfigs/attributeFilterConfigsSelectors.ts, libs/sdk-ui-dashboard/src/model/store/attributeFilterConfigs/tests/attributeFilterConfigsSelectors.test.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdown.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/DropdownButton/AttributeFilterDropdownButton.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/DropdownButton/tests/AttributeFilterDropdownButton.test.tsx, libs/sdk-ui-filters/src/AttributeFilter/Context/AttributeFilterContext.tsx, libs/sdk-ui-filters/src/AttributeFilter/types.ts, libs/sdk-ui-filters/src/DateFilter/DateFilterButton/tests/DateFilterButton.test.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss, libs/sdk-ui-filters/styles/scss/components/FilterButtonCustomIcon.scss
=> FEATURE: EGL-294 - disabled/hidden dashboard attribute filter

libs/sdk-ui-dashboard/styles/scss/dateFilterConfig.scss, libs/sdk-ui-dashboard/styles/scss/main.scss
=> FEATURE: EGL-290 add css for configuration panel

.gitlab-ci.yml
=> CONFIG: INFRA-1275 Update Tiger-dev ECR to Infra1

libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx, libs/sdk-ui/src/base/react/usePromiseCache.ts
fix: can not load the insight list
JIRA: EGL-200
--- …
=> BUGFIX: EGL-200 - can not load the insight list when scrolling up and down the insight list

docs/layouts/partials/navbar-breadcrumb.html
=> BUGFIX: DP-2690 update breadcrumbs

libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/EmbeddedGdc.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/addAttributeFilterHandler.test.ts, libs/sdk-ui-dashboard/src/model/commands/filters.ts, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
=> FEATURE: EGL-297 - support set attribute filter mode in post message

libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss
=> FEATURE: EGL-345 - readonly filter does not show navigate button in view mode

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/tests/filterBar.fixture.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/tests/utils.test.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/utils.ts
=> FEATURE: EGL-295 - hide the filter bar when all filters are hidden

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: TNT-1798 set enablePivotTableIncreaseBucketSize value to true

libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-filters/src/AttributeFilter/Components/DropdownButton/AttributeFilterDropdownButton.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterButton/DateFilterButton.tsx, libs/sdk-ui-filters/src/shared/components/internal/FilterButtonCustomIcon.tsx, libs/sdk-ui-filters/src/shared/components/internal/tests/FilterbuttonCustomIcon.test.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss, libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss, libs/sdk-ui-filters/styles/scss/components/FilterButtonCustomIcon.scss
=> FEATURE: EGL-349 - using default cursor for readonly filter in view mode

libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
=> FEATURE: EGL-352 - close the configuration when close dropdown

.gitlab-ci.yml
=> CONFIG: INFRA-1275 Update Tiger-dev endpoints

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/store/dateFilterConfig/dateFilterConfigReducers.ts
feat: reset the filters configs when discarding changes dashboard
JIRA: EGL-351
--- …
=> FEATURE: EGL-351 - reset the filters configs when discarding changes dashboard

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/ru-RU.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json, libs/sdk-ui/src/base/localization/bundles/de-DE.json, libs/sdk-ui/src/base/localization/bundles/en-US.json, libs/sdk-ui/src/base/localization/bundles/es-ES.json, libs/sdk-ui/src/base/localization/bundles/fr-FR.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/nl-NL.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json, libs/sdk-ui/src/base/localization/bundles/ru-RU.json, libs/sdk-ui/src/base/localization/bundles/zh-Hans.json
=> BUGFIX: EGL-350 - move dateFilterDropdown.configuration to sdk ui instead

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/uiSettings.ts
=> RELATED: TNT-1677 disconnect ffs from feature hub

common/changes/@gooddata/sdk-ui-all/RAIL-5155_2023-10-30-15-03.json
=> RELATED: RAIL-5155 Add change log for isAdminDomain removal

examples/sdk-interactive-examples/examples-template/src/catalog.ts, examples/sdk-interactive-examples/examples/example-attributefilter/src/catalog.ts, examples/sdk-interactive-examples/examples/example-chartconfig/src/catalog.ts, examples/sdk-interactive-examples/examples/example-columnchart/src/catalog.ts, examples/sdk-interactive-examples/examples/example-combochart/src/catalog.ts, examples/sdk-interactive-examples/examples/example-dashboard/src/catalog.ts, examples/sdk-interactive-examples/examples/example-dashboard/src/example/Example.tsx, examples/sdk-interactive-examples/examples/example-datefilter/src/catalog.ts, examples/sdk-interactive-examples/examples/example-execute/src/catalog.ts, examples/sdk-interactive-examples/examples/example-granularity/src/catalog.ts, examples/sdk-interactive-examples/examples/example-headline/src/catalog.ts, examples/sdk-interactive-examples/examples/example-pivottable/src/catalog.ts, examples/sdk-interactive-examples/examples/example-relativedatefilter/src/catalog.ts
=> RELATED: RAIL-5122 change dashboard in example

docs/content/en/latest/references/filters/attribute_filter_button_component.md, docs/content/en/latest/references/filters/date_filter.md
=> FEATURE: EGL-300 - update docs for hide/lock filters

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
fix: attribute filter mode breaks in two lines
_ increasing the attribute dropdown body width to 260px
JIRA: EGL-359
--- …
=> BUGFIX: EGL-359 - attribute filter mode breaks in two lines

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drillDown.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/cypress/tools/drillToModal.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Dashboard/DashboardDrilldownonChartScenario.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
=> FEATURE: QA-19981 Migrate G2C drill down on chart

common/changes/@gooddata/sdk-ui-all/EGL-275_2023-11-02-15-01.json
=> FEATURE: EGL-288 - hidden/locked filter changelog

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
fix: attribute mode config section breaks into two lines
_ expand the max-width for the attribute dropdown body
JIRA: EGL-359
--- …
=> BUGFIX: EGL-359 - attribute mode config section breaks into two lines

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
fix: revert the code changes for ticket EGL-359
JIRA: EGL-359
--- …
=> BUGFIX: EGL-359 - revert the code changes for ticket EGL-359

common/config/rush/pnpm-lock.yaml, libs/sdk-backend-tiger/package.json, libs/sdk-backend-tiger/tests/reference_workspace/create_test_workspaces.cjs, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests-e2e/reference_workspace/lib/create_tiger_workspace.js
=> FEATURE: QA-20329 feat : upgrade fixture version

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts
=> FEATURE: EGL-363 - attribute hierarachies featureflag and capability

docs/go.mod, docs/go.sum
=> CONFIG: update hugo module

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drillDown.spec.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/bear_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_bear.ts
=> FEATURE: QA-20182 write auto for Table Transpose - drill down

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts
=> FEATURE: EGL-400 - remove enableAttributeHierarchies in disabled unfinished feature

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/snapshotFiltering.spec.ts
=> FEATURE: QA-20482 separate e2e test for CAL into new job

libs/sdk-backend-tiger/package.json
=> FEATURE: QA-19824 new script allow to update snapshot

docs/content/en/latest/references/visual_components/chart_config.md
=> CONFIG: add chart configuration `enableChartSorting`

README.md, docs/content/en/latest/Quick_start.md, docs/content/en/latest/architecture/architecture_overview/_index.md, docs/content/en/latest/architecture/supported_frameworks/nextjs.md, docs/content/en/latest/introduction.md, docs/content/en/latest/learn/apply_theming/_index.md, docs/content/en/latest/learn/embed_dashboards/web_components/_index.md, docs/content/en/latest/learn/get_raw_data/_index.md, docs/content/en/latest/learn/get_raw_data/data_sampling.md, docs/content/en/latest/learn/integrate_and_authenticate/CN_and_cloud_authentication.md, docs/content/en/latest/learn/integrate_and_authenticate/_index.md, docs/content/en/latest/learn/visualize_data/_index.md, docs/content/en/latest/learn/visualize_data/export_catalog.md, docs/content/en/latest/references/visual_components/chart_config.md
=> TRIVIAL: cherry-pick rel/9.3

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetAttributeHierarchyItem.tsx
=> FEATURE: EGL-363 - correct the automation test class name

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardShortenMetricName.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts, libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/shortenMetricName.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts, libs/sdk-ui-tests-e2e/cypress/tools/sectionHeader.ts, libs/sdk-ui-tests-e2e/cypress/tools/table.ts
=> BUGFIX: QA-19749 fix some ui-sdk-test on firefox browser

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/analyticalWidgets.ts, libs/sdk-model/src/dashboard/baseWidget.ts, libs/sdk-model/src/dashboard/common.ts, libs/sdk-model/src/dashboard/drill.ts, libs/sdk-model/src/dashboard/filterContext.ts, libs/sdk-model/src/dashboard/kpi.ts, libs/sdk-model/src/dashboard/layout.ts, libs/sdk-model/src/dashboard/widget.ts, libs/sdk-model/src/insight/index.ts, libs/sdk-model/src/objRef/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/insight.ts, libs/sdk-ui-dashboard/src/model/commands/layout.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts, libs/sdk-ui-dashboard/src/model/store/renderMode/renderModeSelectors.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/vis/drilling.ts
Mark alpha/beta interfaces used on plugins as public.
Mark internal interfaces/apis used on plugins as public.
JIRA: RAIL-5195
--- …
=> FEATURE: RAIL-5195 Mark apis used on plugins as public

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/client.ts, libs/api-client-tiger/src/validDescendants.ts, libs/sdk-backend-base/src/customBackend/workspace.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-bear/src/backend/workspace/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/attributeHierarchies/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspace/attributeHierarchies/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/HierarchyConverter.ts
=> FEATURE: EGL-365 - introduce attribute hierarchies service

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useTitleConfiguration.ts
=> FEATURE: TNT-1823 Add dependent filters interaction events

common/changes/@gooddata/sdk-ui-all/nen-rail-5208_2023-11-21-13-16.json, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/plugins/customizationApis/attributeFiltersCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/dateFiltersCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/filtersCustomizer.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/attributeFilterCustomizer.test.tsx.snap, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/attributeFilterCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/fluidLayoutCustomizer.test.ts, libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/insightCustomizer.test.tsx, libs/sdk-ui-dashboard/src/plugins/customizationApis/types.ts, libs/sdk-ui-dashboard/src/plugins/customizer.ts
=> FEATURE: RAIL-5208 Extend Attribute Filter customization API with decorator

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/permissions/index.ts, libs/sdk-backend-tiger/src/backend/organization/permissions.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/EditUserDetails.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/detailsHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserGroupEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/dialogHooks.ts
- Introduce SPI to get org permissions for user and group
- Remove admin group when user is demoted to member from admin (removal of org permission is not enough)
JIRA: TNT-1877
--- …
=> BUGFIX: TNT-1877 Fix issues in user management

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/SettingsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
feat: add a setting to enable showing hidden items
JIRA: EGL-324
--- …
=> FEATURE: EGL-324 - add a setting to enable showing hidden items

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx
=> FEATURE: EGL-364 fix NPE when missing drill down item in Bear

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/title/AttributeTitleRenaming.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts
=> RELATED: TNT-1818 Fix dependent filters issues

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap, libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts
=> FEATURE: EGL-400 - disabled attribute hierarchy in sdk 9.4.0

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts
=> FEATURE: QA-20555 Split export checklist panther

libs/sdk-backend-bear/src/backend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/capabilities.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/backendCapabilities/backendCapabilitiesSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/AttributeFilterIrrelevantSelectionStatus.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/AttributeFilterShowFilteredElements.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/StatusBar/SingleSelectionAttributeFilterStatusBar.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/utils.ts, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterStatusBar.scss
=> FEATURE: TNT-1819 Support single-select filter in dependent filters

docs/layouts/partials/navbar.html
=> TRIVIAL: updating logo link

libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts
To improve orientation in devTools
TRIVIAL
---
| …
=> TRIVIAL: Add stores names

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
=> RELATED: RAIL-5212 updating compatibility matrix

docs/content/en/latest/learn/embed_dashboards/_index.md, docs/content/en/latest/references/dashboard_component/dashboard_plugins.md, docs/content/en/latest/references/dashboard_component/dashboard_plugins_api.md, docs/content/en/latest/references/dashboard_component/detailed_description.md, docs/package-lock.json
- Align docs with the latest changes in dashboard plugins
- Mention SDK dependencies injection
- Remove obsolete statements that dashboard edit mode is not supported
JIRA: RAIL-5177
--- …
=> docs: dashboard plugins SDK auto upgrades

libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
=> BUGFIX: EGL-429 filter out the deleted attributes in hierarchies

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: EGL-373 enable attribute hierarchies by default

common/changes/@gooddata/sdk-ui-all/EGL-362_2023-11-30-10-06.json, common/changes/@gooddata/sdk-ui-all/EGL-362_2023-11-30-10-07.json
=> FEATURE: EGL-386 - drill-down in global hierarchy changelogs

docs/content/en/latest/references/dashboard_component/dashboard_plugins.md
Plugin changes will be released in 9.5.0, not 9.4.0.
JIRA: RAIL-5177
--- …
=> BUGFIX: RAIL-5177 Correct version in dashboard plugins docs

libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts
=> BUGFIX: TNT-1912 Avoid sending empty parent filters

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
=> BUGFIX: QA-20736 drilling.spec.ts test failed because drill down

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/widgetConfiguration.ts
=> BUGFIX: QA-20736 Stablize drilling.spec

common/changes/@gooddata/sdk-ui-all/jsc-tnt-1936_2023-12-13-16-22.json
=> RELATED: TNT-1936 Add cross-filtering changelog

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dateFiltering.spec.ts
Passed on my branch: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/284/
--- …
=> BUGFIX: QA-20731 stablize dateFiltering test

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx, libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx, libs/sdk-ui-ext/src/internal/utils/domHelper.ts, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-geo/api/sdk-ui-geo.api.md, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Overlay/tests/Overlay.test.tsx, libs/sdk-ui-kit/src/test/utils.tsx, libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md, libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md, libs/sdk-ui/api/sdk-ui.api.md, skel/sdk-skel-tsx/api/sdk-skel-tsx.api.md
=> RELATED: STL-15  rush full update

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsForSettings.test.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/store/drill/drillReducers.ts, libs/sdk-ui-dashboard/src/presentation/drill/utils/test/drillDownUtils.test.ts
=> RELATED: TNT-1936, TNT-1954 Updates and fixes

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json
* contains updated annotations
* has minor sonar fix
--- …
=> RELATED: RAIL-5204 Upgrade number formatter library

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillOriginSelector/DrillOriginSelector.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/DrillTargetAttributeHierarchyItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/EmptyAttributeHierarchyInfo.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightEditMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useEditableInsightMenu.ts, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/internal/components/attributeHierarchies/attributeHierarchyDialog/AttributeHierarchyDialog.tsx, libs/sdk-ui-ext/src/internal/components/attributeHierarchies/attributeHierarchyDialog/AttributeHierarchyDialogProvider.tsx, libs/sdk-ui-ext/src/internal/components/attributeHierarchies/attributeHierarchyDialog/useBackendProvider.ts
=> FEATURE: TNT-1928 Drilldown telemetry

libs/sdk-backend-tiger/src/backend/organization/users.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/AddUserGroupsToUsersDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/AddUsersToUserGroupsDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/AddWorkspaceToSubjects.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/CreateUserGroupDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DeleteUserDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DeleteUserGroupDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DeleteUserGroupsDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DeleteUsersDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/UserDetailsView.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Details/detailsHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/TelemetryContext.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserGroupEditDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserGroups/userGroupHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Users/AddUserContent.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Users/UserItem.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Users/UsersList.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Users/usersHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/HierarchicalPermissionsDropdown.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/PermissionsDropdown.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/WorkspaceItem.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/workspaceHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/dialogHooks.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/index.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/locales.ts, libs/sdk-ui/src/base/localization/bundles/en-US.json
=> FEATURE: TNT-1910 Enable user management feature flag by default, various user management fixes, telemetry

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/pivotTableHasTotalAndSubtotalsOnDashboard.spec.ts
=> BUGFIX: QA-19471 Enable XLSX export for Table (Row Totals , Column Totals) on SDK

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
fix no remove year closed on bear
JIRA: QA-21094
--- …
=> TRIVIAL: QA-21094 fix failed drilling on bear by remove date

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/attributeHierarchyModifiedHandler.ts, libs/sdk-ui-dashboard/src/model/events/insight.ts, libs/sdk-ui-ext/src/internal/components/attributeHierarchies/attributeHierarchyDialog/AttributeHierarchyDialogProvider.tsx, libs/sdk-ui-ext/src/internal/components/attributeHierarchies/attributeHierarchyDialog/useBackendProvider.ts
=> BUGFIX: TNT-1934 Drilldown telemetry events, attr hierarchy modify handler

libs/sdk-ui-dashboard/src/model/store/catalog/catalogSelectors.ts
This reverts commit 37acfca92d45a57c61403f1ec53c01350d98272c.
--- …
=> Revert "fix: guard attribute hierarchy creation with capability"

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json
=> FEATURE: QA-20524 auto advanced cases for dependent filters

.lintstagedrc, common/autoinstallers/lint-staged/.npmrc, common/autoinstallers/lint-staged/package.json, common/autoinstallers/lint-staged/pnpm-lock.yaml, common/config/rush/command-line.json, common/config/rush/common-versions.json, common/config/rush/repo-state.json, common/git-hooks/pre-commit
=> TRIVIAL: Setup prettier pre-commit hook and copyright header fix

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/insightOnDashboard.spec.ts
=> FEATURE: QA-21166 Optimize insightOnDashboard test

common/changes/@gooddata/sdk-ui-all/ine-lx-6_2024-01-08-13-26.json, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
=> BUGFIX: LX-6 Handle common DF comming in from D2D

libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetDuplicityWarning.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateDatasetFilter.tsx
=> FEATURE: LX-4 Multiple DF when drilling to dashboard + others

libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
=> BUGFIX: LX-28 Validate hierarchy dropdowns against valid attributes on model

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadCatalog.ts
=> RELATED: TNT-1968 Do not load metrics during dashboard load when not needed

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/gd-tiger-model/AnalyticalDashboardModelV2.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/dashboard.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaReducers.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaState.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/FiltersConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuBubble.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss
Allow disabling of the cross-filtering for a particular dashboard.
Extend dashboard metadata with a new property `disableCrossFiltering`.
Implement new configuration panel for enabling or disabling of the cross-filtering to the filter bar (only in edit mode).
JIRA: F-2
--- …
=> FEATURE: F-2 Allow disabling of the cross-filtering

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/drill/drillSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/Components/DropdownButton/AttributeFilterDropdownButton.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownButton.scss
=> RELATED: F1-2 Distinguish virtual attribute filter button

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/crossFiltering.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/chart.ts
=> FEATURE: F1-2 Extend cross-filtering test by highlighting check

.github/actions/check-pull-request-commits/src/action.js, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/__snapshots__/changeDateFilterSelectionHandler.test.ts.snap, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts, libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
=> BUGFIX: LX-32 LX-33LX-34 Fix several issues related to Multiple DFs

common/changes/@gooddata/sdk-ui-all/jsc-f1-ff_2024-01-10-09-39.json, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: F1-2 Enable cross filtering by default

rush.json
=> RELATED: STL-69 chore: update rush to 5.112.2

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> RELATED: FF-94 enableKDSavedFilters set to true

libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrillToCustomUrlParams.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/removeAttributeFiltersHandler.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DashboardParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/InsightParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useInvalidFilteringParametersIdentifiers.ts
- Handle removed display forms correctly in the validation.
- Update wording of the toast message about invalid parameters.
- Hide dashboard / insight parameters sections when they are empty.
- Trigger validation also on removal / addition of the filter.
JIRA: TNT-1967
--- …
=> BUGFIX: TNT-1967 Drill to custom url validation

tools/react-app-template/webpack.config.cjs
=> RELATED: STL-66 fix build js version app-template

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
=> BUGFIX: LX-35 Custom DF name is handled in lower components

.github/workflows/code-drop.yml, .github/workflows/rw-bump-version.yml
- fix error "fatal: detected dubious ownership"
- update slack notification
--- …
=> RELATED: STL-71 Fix codedrop workflow

.github/workflows/netlify-deploy.yaml
=> CONFIG: INFRA-3308 Consolidate netlify site-id and token

libs/sdk-ui-dashboard/src/_staging/dateFilterConfig/dateFilterOptionMapping.ts, libs/sdk-ui-dashboard/src/_staging/exportUtils/filterUtils.ts, libs/sdk-ui-dashboard/src/model/utils/alertsUtils.ts, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/ViewModeDashboardKpi/KpiAlerts/KpiAlertDialog/utils/filterUtils.ts
Plus explicitly check for
common date filter on multiple places
JIRA: LX-40
--- …
=> BUGFIX: LX-40 Handle All time DF from all places

.github/workflows/code-drop.yml, .github/workflows/rw-bump-version.yml
Finalize branch names for master/release.
---
| …
=> RELATED: STL-71 Use proper image and enrich slack and finalize

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-tests-e2e/cypress/tools/navigation.ts, libs/sdk-ui-tests-e2e/package.json, libs/sdk-ui-tests-e2e/scripts/run_boiler_app.sh
=> RELATED: QA-21090 fix cypress version for sdk e2e test

libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts, libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableDateFilter/DraggableDateFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/configuration/DateFilterConfigurationBody.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/DateFilterCheckbox.tsx, libs/sdk-ui-dashboard/styles/scss/filterBar.scss, libs/sdk-ui-filters/src/DateFilter/DateFilterButtonLocalized/DateFilterButtonLocalized.tsx, libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss
LX-35 Dont allow empty DF title
LX-39 Shorten long DF title in config panel and filter bar
LX-41 Use std. AllTime representation 
--- …
=> BUGFIX: LX-35 LX-39 LX-41 Multi DFs fixes

examples/sdk-examples/tsconfig.json, libs/sdk-backend-bear/tsconfig.json, libs/sdk-ui-dashboard/tsconfig.json, libs/sdk-ui-filters/tsconfig.json, libs/sdk-ui-kit/tsconfig.json, libs/sdk-ui-pivot/tsconfig.json, tools/dashboard-plugin-template/configTemplates/ts/tsconfig.json, tools/react-app-template/configTemplates/ts/tsconfig.json
=> RELATED: STL-82 disable composite build in all packages

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts
Dont keep only AF ignores but all DF ignores too
JIRA: LX-34
--- …
=> BUGFIX: LX-34 Keep all ignores when ignoring common DF

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardShortenMetricName.spec.ts
Passed on my branch: https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/474/console
--- …
=> BUGFIX: QA-21237 fix unstable dashboardShortenMetricName

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
=> BUGFIX: LX-43 Sanitize DFs with nonexisting dataSet

libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
=> BUGFIX: F1-2 Disable cross-filtering when drillableItems are present

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/EmbeddedGdc.ts, libs/sdk-embedding/src/internal/filterConvertors.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts
=> FEATURE: LX-5 Multiple DFs in AD related changes

.github/workflows/rw-publish-version.yml
=> RELATED: STL-107 fix getting token from valut in publish wf

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/catalog/tests/catalogSelectors.test.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/tests/widgetDrillSelectors.test.ts, libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/useDrillTargetTypeItems.ts, libs/sdk-ui-ext/src/internal/components/configurationPanels/ConfigurationPanelContent.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/PivotTableConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/BaseChartConfigurationPanel.test.tsx
=> RELATED: LX-30 Remove FF enableAttributeHierarchies

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardDependentFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
=> RELATED: QA-21297 stabilize test dashboardDependentFilter.spec.ts

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
=> FEATURE: LX-55 Switch enableMultipleDateFilters to true

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
=> FEATURE: LX-45 LX-55 Handle cross filters with multiple DFs and switch FF

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDateDataSetFilter.tsx
=> BUGFIX: LX-53 Dont disable config filter on KD

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/AddRichTextWidgetButton.tsx, libs/sdk-ui-dashboard/styles/scss/richText.scss
=> BUGFIX: F1-56 Update rich text styles

.github/workflows/rw-publish-prerelase.yml
=> RELATED: STL-118 fix runner definition

.github/workflows/post-merge-pipeline.yml
Use new ext-image update implementation which is based on Github actions
JIRA: INFRA-3327
--- …
=> FEATURE: INFRA-3327 update ext-image files in gdc-nas

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json
=> FEATURE: F1-58 Regenerate tiger api client for mysql support

.github/workflows/slack-post-merge-notification.yml
=> TRIVIAL: test post merge workflow

common/changes/@gooddata/sdk-ui-all/f1-rich-text_2024-01-19-13-37.json
=> BUGFIX: F1-9 Correct changelog for rich text

.github/workflows/rw-publish-prerelase.yml
=> RELATED: STL-118 improve slack notification

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/WidgetDropZoneColumn.tsx
=> RELATED: STL-126 handle null exception triggered by DnD automation tests from time to time

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
Setup visualization set loading even when not needed. In combination with react issue that render(null) sometimes does not unmount child caused loading started but because execution is not needed no one will set it back to false.
Replace render(null) by root.unmount() caused different issues. JIRA: LX-57
--- …
=> BUGFIX: LX-57 Prevent infinite loading

.github/workflows/code-drop.yml, .github/workflows/publish-alpha.yml, .github/workflows/publish-beta.yml, .github/workflows/pull-request-prerelease.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-publish-prerelase.yml, .github/workflows/rw-publish-version.yml
=> RELATED: STL-124 change WF to public runners and dockers 

common/config/rush/command-line.json, examples/playground/scripts/build-playground.sh, examples/playground/scripts/run-playground.sh, examples/sdk-examples/scripts/build-examples.sh, examples/sdk-examples/scripts/run-examples.sh, libs/api-client-bear/scripts/build.sh, libs/api-client-tiger/scripts/build.sh, libs/sdk-backend-bear/scripts/build.sh, libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/layout.ts, libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts, libs/sdk-backend-tiger/scripts/build.sh, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-ui-charts/scripts/build.sh, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/scripts/build.sh, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrills.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardWidget.tsx, libs/sdk-ui-ext/scripts/build.sh, libs/sdk-ui-filters/scripts/build.sh, libs/sdk-ui-geo/scripts/build.sh, libs/sdk-ui-kit/scripts/build.sh, libs/sdk-ui-pivot/scripts/build.sh, libs/sdk-ui-tests-e2e/scripts/build.sh, tools/app-toolkit/scripts/build.sh, tools/catalog-export/scripts/build.sh, tools/mock-handling/scripts/build.sh, tools/plugin-toolkit/scripts/build.sh
=> RELATED: STL-141 fix all build scripts and rush build false negative

docs/content/en/latest/references/dashboard_component/improve_performance.md
=> RELATED: DP-2752 adding improve_performance.md

docs/content/en/latest/learn/embed_dashboards/web_components/angular.md, docs/content/en/latest/learn/embed_dashboards/web_components/vue.md, docs/content/en/latest/references/visual_components/bullet_chart.md, docs/content/en/latest/references/visual_components/geo_pushpin_chart.md
=> RELATED: DP-2746 fixing links

libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts, libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap
=> BUGFIX: LX-70 Apply KD filter with local date filter

libs/sdk-ui-filters/src/DateFilter/DateFilterButton/DateFilterButton.tsx
=> RELATED: QA-21273, QA-21361 Add classname for date filters tests

common/changes/@gooddata/sdk-ui-all/nen-lx-74_2024-02-01-11-03.json, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
=> FEATURE: LX-74 Set multiple date filters FF to true, add changelog

.github/workflows/examples-deploy.yml
=> RELATED: STL-121 Publish heroku examples finalize

.github/workflows/post-merge-pipeline.yml
=> RELATED: STL-161 fix deploy webcomponent trigger

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/limitingItemsHook.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/loader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/loadInitialElementsPage.test.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/loadNextElementsPage.test.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/staticElements.test.ts
=> BUGFIX: LX-60, LX-69, LX-82 Available filter values bugfixes

libs/sdk-ui-filters/src/DateFilter/DateFilterButton/DateFilterButton.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterButtonLocalized/DateFilterButtonLocalized.tsx
=> RELATED: QA-21273 Add selector for e2e tests

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/api-client-tiger/package.json, libs/api-client-tiger/src/axios.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadInaccessibleDashboards.ts
=> FEATURE: LX-86 Axios cache + optimizations

.github/actions/check-npm-version/action.yml
=> RELATED: STL-120 Add action to check npm package existence

.github/workflows/doc-test-apidocs.yml
=> RELATED: STL-154 Run apidocs in series

common/config/rush/browser-approved-packages.json, common/config/rush/pnpm-lock.yaml, libs/api-client-tiger/package.json, libs/api-client-tiger/src/axios.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadInaccessibleDashboards.ts
=> FEATURE: LX-86 Deliver axios cache to hotfix

libs/sdk-ui-dashboard/src/converters/filterConverters.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
=> BUGFIX: LX-88, LX-90 Dont skip all time date filter when exploring

.github/actions/check-npm-version/action.yml, .github/actions/hugo-update-param-action/action-build/index.js, .github/actions/hugo-update-param-action/package-lock.json, .github/actions/hugo-update-param-action/src/index.js, .github/workflows/release-release-minor.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-doc-update-hugo-version.yml, .github/workflows/rw-git-backmerge.yml, .github/workflows/rw-git-create-tag.yml, .github/workflows/rw-perform-release-major-minor.yml, .github/workflows/rw-publish-prerelease.yml, .github/workflows/rw-publish-release.yml
=> RELATED: STL-120 integrate whole release minor pipeline

.github/workflows/doc-examples-deploy.yml, .github/workflows/doc-netlify-deploy.yaml, .github/workflows/release-postrelease.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-doc-examples-deploy.yml, .github/workflows/rw-doc-netlify-deploy.yml, .github/workflows/rw-doc-release-apidocs.yml, .github/workflows/rw-publish-documentation.yml, .github/workflows/rw-publish-prerelease.yml
This is a draft version, work in progress.
JIRA: STL-121
--- …
=> RELATED: STL-121 Release documentation workflow

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/hideFilters.spec.ts
=> fix: comment out flaky test

.github/workflows/release-bump-master-to-major.yml, .github/workflows/rw-bump-version-major.yml, .github/workflows/rw-publish-prerelease.yml, .github/workflows/rw-publish-release.yml
JIRA: STL-178
---
> [!IMPORTANT]
---
Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:
```
```
```
```
```
```
=> chore: bump major version on master workflow

.github/pull_request_template.md
---
> [!IMPORTANT]
---
Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:
```
```
```
```
```
```
=> trivial: fix the documentation link PR template

.github/workflows/rw-bump-version-major.yml, .github/workflows/rw-publish-version.yml
JIRA: STL-180
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: run rw-publish-version on public runner

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/client.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/userManagement.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/organization/fromBackend/userConvertor.ts, libs/sdk-backend-tiger/src/backend/organization/permissions.ts, libs/sdk-backend-tiger/src/backend/organization/users.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/user/index.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/hooks/usePermissions.ts
- Reflect backend API breaking changes in the SDK
- Reload users and groups on workspace hierarchy permission change
JIRA: F1-51
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: user management

common/changes/@gooddata/sdk-ui-all/jsc-f1-95-queries_2024-02-16-09-52.json, common/changes/@gooddata/sdk-ui-all/jsc-f1-95-queries_2024-02-16-09-53.json, libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-bear/src/backend/workspace/insights/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts, libs/sdk-backend-mockingbird/src/recordedBackend/insights.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-spi/src/workspace/insights/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/dashboardsQuery.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts, libs/sdk-backend-tiger/src/backend/workspace/insights/insightsQuery.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts, libs/sdk-ui-ext/src/dataLoaders/test/dataLoaders.mock.ts
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> Add services for listing insights and dashboards

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/organization/fromBackend/userConvertor.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/user/index.ts
Reflect change of the user groups output in the user management API.
JIRA: F1-51
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: user management api changes

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataSources/index.ts
JIRA: F1-137
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: regenerate api-client for mariadb support

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> RELATED: QA-19631 Use ecr image for tests

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
JIRA: F1-137
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: introduce enableMariaDbDataSource FF

libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
Add the missing value passing in the dataSourceResponseAsDataSourceConnectionInfo function
JIRA: CQ-195
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: fix cacheStrategy handling

.github/workflows/rw-bump-version-major.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-doc-release-apidocs.yml, .github/workflows/rw-doc-update-hugo-version.yml, .github/workflows/rw-git-backmerge.yml
JIRAL STL-199
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: change commits to conventional

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
JIRA: STL-159
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> docs: get rid of compatibility matrix

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/attributeFilterLimit.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts, libs/sdk-ui-tests-e2e/cypress/tools/headline.ts
update some test available value filter
JIRA: QA-21050
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> TRIVIAL: QA-21050 implement available value filter

NOTICE
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> LR-1917: NOTICE update

.github/workflows/rw-publish-version.yml
JIRA: STL-202
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: add retry publish NPM

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/types/drillTypes.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/getWebComponentsCodeGenerator.ts, libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/tests/__snapshots__/getWebComponentsCodeGenerator.test.ts.snap
JIRA: F1-114
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: rename remaining insight to visualization

.github/workflows/post-merge-pipeline.yml, .github/workflows/slack-post-merge-notification.yml
JIRA: STL-119
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: fix build of webcomponents

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md
JIRA: STL-159
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> docs: fix compatibility doc

.github/workflows/release-postrelease.yml
JIRA: STL-105
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: use permissions for doc job

.github/workflows/release-postrelease.yml
JIRA: STL-105
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: propagate secrets for post-remelase jobs

.github/workflows/release-postrelease.yml
JIRA: STL-105
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: remove one of secrets for post-remelase jobs

.github/workflows/doc-netlify-deploy.yaml
JIRA: STL-105
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: fix manual netlify deploy

.github/actions/hugo-update-param-action/action-build/index.js, .github/actions/hugo-update-param-action/action.yml, .github/actions/hugo-update-param-action/src/index.js, .github/workflows/rw-doc-update-hugo-version.yml, .github/workflows/rw-perform-release.yml
JIRA: STL-105
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: fix hugo version and redir

.github/workflows/post-merge-pipeline.yml
Asynchronously update ext-image file in gdc-nas
JIRA: INFRA-3327
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat(ext-image-update): update gdc-nas reference

libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx, libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts, libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
JIRA: LX-108
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> FEATURE: LX-108 Add italian to date format locale

libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/CreateUserGroupDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DataSources/backend/loadUserDataSourceOptionsPromise.ts, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/DeleteLink.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/ViewDialog.tsx, libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/HierarchicalPermissionsDropdown.tsx
JIRA: F1-51
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: F1-51 Add missing selectors for e2e tests

docs/content/en/latest/references/API_references.md
Use version-agnostic link to avoid updating with each version
JIRA: STL-224
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: fix latest apidocs link

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: QA-21506 Update message of invalid insight in exportToPDF.spec

libs/sdk-backend-tiger/vite.integrated.config.ts
JIRA: STL-238
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: increase test timeout for sdk-backend-tiger

.github/workflows/doc-examples-deploy.yml, .github/workflows/push-webcomponents-deploy.yml
JIRA: STL-248
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: fix deploy web components

.github/workflows/doc-examples-deploy.yml, .github/workflows/doc-strorybook-deploy.yml, .github/workflows/rw-doc-storybook-deploy.yml
JIRA: STL-177
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: storybook deploy

libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/tests/DateFilterBody.test.tsx, libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss
JIRA: LX-79
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: LX-79 Date filter config overlay small screens

.github/workflows/post-merge-pipeline.yml
JIRA: STL-248
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: fix webcomponents on release

common/scripts/ci/utils.sh
JIRA: LX-144
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: generalize the script to be able to get also newer releases to patch

libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx, libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx, libs/sdk-ui-geo/src/core/geoChart/constants/geoChart.ts, libs/sdk-ui-geo/src/core/geoChart/geoChartDataLayers.ts, libs/sdk-ui-geo/src/core/geoChart/geoChartTooltip.ts, libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/viewport.ts
JIRA: LX-147
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: lazy load of MapboxGl

common/changes/@gooddata/sdk-ui-all/ine-lx-94_2024-03-08-07-58.json, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useRowsCalculator.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/areaChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/barChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bubbleChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bulletChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/columnChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/comboChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/dependencyWheelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/donutChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/funnelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/heatmap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/lineChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/pieChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/sankeyChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/scatterPlot.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/treemap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/geo/__snapshots__/geoPushpin.test.tsx.snap, libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md, libs/sdk-ui-theme-provider/src/ThemeProvider/Context.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx, libs/sdk-ui-theme-provider/src/index.ts, libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
JIRA: LX-94
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: theme loading status, filter bar fix

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/tests/__snapshots__/PluggableRepeater.test.tsx.snap, libs/sdk-ui-ext/src/internal/constants/uiConfig.ts, libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: extend ui config with empty canvas drag types

.github/workflows/push-fossa-update-attribution-file.yml, .github/workflows/rw-fossa-update-attribution-file.yml
JIRA: STL-193
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: implement automated fossa report WF

common/config/rush/pnpm-lock.yaml, examples/playground/package.json, examples/sdk-examples/package.json, libs/api-client-bear/package.json, libs/sdk-backend-base/package.json, libs/sdk-backend-bear/package.json, libs/sdk-backend-mockingbird/package.json, libs/sdk-backend-spi/package.json, libs/sdk-backend-tiger/package.json, libs/sdk-embedding/package.json, libs/sdk-model/package.json, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-loaders/package.json, libs/sdk-ui-pivot/package.json, libs/sdk-ui-tests/package.json, libs/sdk-ui-theme-provider/package.json, libs/sdk-ui-web-components/package.json, libs/sdk-ui/package.json, libs/util/package.json
JIRA: STL-278
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> ci: test fossa push-fossa-update-attribution-file

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/index.tsx, libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/repeaterAgGridDataSource.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: render execution errors in repeater

.github/workflows/push-fossa-update-attribution-file.yml, .github/workflows/rw-fossa-update-attribution-file.yml
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> port fossa from master to release

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/tests/__snapshots__/PluggableRepeater.test.tsx.snap
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: sanitize repeater extended reference point filters

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/model/queries/availableDatasetsForItems.ts, libs/sdk-ui-dashboard/src/model/queries/base.ts, libs/sdk-ui-dashboard/src/model/queries/index.ts, libs/sdk-ui-dashboard/src/model/queryServices/index.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryAvailableDatasetsForItems.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/types/dateFilterTypes.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/AttributeFilterParentFilteringContext.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/AttributeFilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useAvailableDatasetsForItems.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFilterConfigurationState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFiltersConfiguration.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitValuesConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/AddLimitingItemDialog.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/DateFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/ParentFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/LimitingItem.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/limitingItemsHook.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss
JIRA: LX-153
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> FEATURE: LX-153 Extend Attribute filter values by with Date filters

libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: handle repeater empty values

common/changes/@gooddata/sdk-ui-all/ine-lx-94_2024-03-08-07-58.json, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useRowsCalculator.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/areaChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/barChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bubbleChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bulletChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/columnChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/comboChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/dependencyWheelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/donutChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/funnelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/heatmap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/lineChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/pieChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/sankeyChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/scatterPlot.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/treemap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/geo/__snapshots__/geoPushpin.test.tsx.snap, libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md, libs/sdk-ui-theme-provider/src/ThemeProvider/Context.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx, libs/sdk-ui-theme-provider/src/index.ts, libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: theme status

libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/tests/__snapshots__/PluggableRepeater.test.tsx.snap, libs/sdk-ui-ext/src/internal/constants/uiConfig.ts
JIRA: F1-186
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: repeater wrapper props

libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
JIRA: F1-178
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: use proper header names in repeater

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardRichText.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/layoutRow.ts
passed on my branch:
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/668/
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/669/console
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/670/console
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/671/console
- https://checklist.intgdc.com/job/cypress-tests/job/gooddata-ui-sdk-cypress-checklist_integrated_tiger-worker/672/console
---
> [!IMPORTANT]
---
Refer to …
=> QA-21585: stabilize dashboard rich text

.github/workflows/push-fossa-update-attribution-file.yml, .github/workflows/rw-git-backmerge.yml
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> port fossa fix and pr fix to release 

libs/sdk-backend-tiger/src/backend/workspace/index.ts
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: F1-188 revert parentPrefixes removal, make them optional instead

libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts
JIRA: F1-188
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: propagate new spi method param

libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts, libs/sdk-ui-dashboard/src/model/commands/render.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardAsyncRender.ts, libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts, libs/sdk-ui-dashboard/src/model/store/layout/layoutUtils.ts
JIRA: STL-138
JIRA: STL-289
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: relax 2s timeout for async registrations

common/changes/@gooddata/sdk-ui-all/ine-lx-94_2024-03-08-07-58.json, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useRowsCalculator.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/areaChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/barChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bubbleChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bulletChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/columnChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/comboChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/dependencyWheelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/donutChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/funnelChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/heatmap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/lineChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/pieChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/sankeyChart.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/scatterPlot.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/treemap.test.tsx.snap, libs/sdk-ui-tests/tests/api-regression/geo/__snapshots__/geoPushpin.test.tsx.snap, libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md, libs/sdk-ui-theme-provider/src/ThemeProvider/Context.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx, libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx, libs/sdk-ui-theme-provider/src/index.ts, libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
JIRA: LX-94
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: theme loading status

docs/content/en/latest/Quick_start.md, docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md, docs/content/en/latest/architecture/migration_guide.md, docs/content/en/latest/architecture/whats_new.md
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> DP-2817 adding version warnings

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/LimitValuesConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/AddLimitingItemDialog.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/DateFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/ParentFiltersPage.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/WithDisabledParentFilterTooltip.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/limitingItemsHook.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/useCommonDateFilterTitle.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
- Disable selected date filters with proper explanation tooltip.
JIRA: LX-160
- Telemetry
JIRA: LX-163
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> FEATURE: LX-160, LX-163 Disable selected date filters and telemetry

libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
JIRA: STL-290
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: add warning for missing locale

libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> RELATED: STL-290 Add warning for missing locale

libs/sdk-ui-tests-e2e/reference_workspace/lib/create_tiger_workspace.js, libs/sdk-ui-tests-e2e/reference_workspace/lib/delete_tiger_workspace.js, libs/sdk-ui-tests-e2e/reference_workspace/lib/utils.js
Else it can happen, that changes written to Pg master is not yet replicated to Pg slave and following operations would fail.
JIRA: STL-302
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> test: add retries to wait for replication

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataSources/index.ts
JIRA: F1-205
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: regenerate tiger api client

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/AttributeHierarchyDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigPanel/useInsightDrillConfigPanel.ts
JIRA: LX-145
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: correct blacklist detection and reference creation

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
JIRA: LX-176
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: new FF for multiple CSVs milestone

libs/sdk-ui-loaders/src/dashboard/loadingStrategies/determineDashboardEngine.ts
JIRA: STL-331
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> fix: allow loading 9.x autoupgrade plugins with sdk version 10

common/config/rush/pnpm-lock.yaml, examples/sdk-interactive-examples/examples-template/package.json, examples/sdk-interactive-examples/examples/example-attributefilter/package.json, examples/sdk-interactive-examples/examples/example-chartconfig/package.json, examples/sdk-interactive-examples/examples/example-columnchart/package.json, examples/sdk-interactive-examples/examples/example-combochart/package.json, examples/sdk-interactive-examples/examples/example-dashboard/package.json, examples/sdk-interactive-examples/examples/example-datefilter/package.json, examples/sdk-interactive-examples/examples/example-dependentfilters/package.json, examples/sdk-interactive-examples/examples/example-execute/package.json, examples/sdk-interactive-examples/examples/example-granularity/package.json, examples/sdk-interactive-examples/examples/example-headline/package.json, examples/sdk-interactive-examples/examples/example-pivottable/package.json, examples/sdk-interactive-examples/examples/example-relativedatefilter/package.json
JIRA: STL-339
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: remove bear from sdk-interactive-examples

libs/sdk-ui-tests-e2e/reference_workspace/lib/create_tiger_workspace.js, libs/sdk-ui-tests-e2e/reference_workspace/lib/delete_tiger_workspace.js
JIRA: QA-21821
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> FEATURE: QA-21821 add retries to wait for child WS creation

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> feat: add FF for Oracle

examples/sdk-examples/src/examples/attributeFilter/attributeFilter/AttributeFilterWithHiddenElements.tsx
JIRA: LX-185
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> BUGFIX: LX-185 Fix live examples Attr. Filter after FF removal.

common/config/rush/pnpm-lock.yaml, libs/sdk-backend-mockingbird/package.json, libs/sdk-backend-mockingbird/src/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/legacyBackendTypes.ts, libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts
JIRA: STL-351
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: remove bear from mockingbird

common/config/rush/pnpm-lock.yaml, examples/playground/README.md, examples/playground/package.json, examples/playground/src/App.tsx, examples/playground/src/createBackend.ts, examples/playground/tsconfig.json, examples/playground/typings/globals.d.ts, examples/playground/webpack.config.cjs
JIRA: STL-352
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: remove bear from playground

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/index.tsx, libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/columnWidths.ts, libs/sdk-ui-charts/src/charts/repeater/hooks/useResizing.ts, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/columnSizing.ts, libs/sdk-ui-charts/src/charts/repeater/internal/privateTypes.ts, libs/sdk-ui-charts/src/charts/repeater/publicTypes.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> FEATURE: F1-148 column width support

common/config/rush/pnpm-lock.yaml, libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/package.json, libs/sdk-embedding/src/iframe/EmbeddedAnalyticalDesigner.ts, libs/sdk-embedding/src/iframe/EmbeddedGdc.ts, libs/sdk-embedding/src/iframe/EmbeddedKpiDashboard.ts, libs/sdk-embedding/src/iframe/index.ts, libs/sdk-embedding/src/iframe/legacyTypes.ts, libs/sdk-embedding/src/internal/filterConvertors.ts, libs/sdk-embedding/src/internal/tests/filterConvertors.test.ts
JIRA: STL-355
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> chore: remove bear from sdk-embedding

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/InlineColumnChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/InlineLineChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/repeaterExecution.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/colorFactory.ts, libs/sdk-ui-charts/src/highcharts/index.ts, libs/sdk-ui-charts/src/interfaces/chartConfig.ts, libs/sdk-ui-ext/src/internal/components/configurationPanels/RepeaterConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/RepeaterDescriptor.ts
Add support for coloring of the inline visualizations. Correct alignment of the inline visualizations so they fit to row. Reflect full repeater configuration in the embedding button. Mark repeater interfaces as @beta for now.
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
``` …
```
=> feat: repeater

docs/config/public/params.toml, docs/layouts/partials/navbar.html
JIRA: DP-2801
---
> [!IMPORTANT]
---
```
```
```
```
```
```
=> docs: change examples link to github

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartColoring/measure.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-227, F1-242
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-227, F1-242 colors, empty rows

libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
JIRA: F1-237
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-237 vertical alignment doesn't support metric displayed as number

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-148 column width support

common/changes/@gooddata/sdk-ui-all/IMJ-STL-370-drop-bear_2024-04-05-10-00.json, common/changes/@gooddata/sdk-ui-all/IMJ-STL-370-drop-bear_2024-04-05-10-10.json, common/changes/@gooddata/sdk-ui-all/IMJ-STL-370-drop-bear_2024-04-05-10-20.json, common/changes/@gooddata/sdk-ui-all/IMJ-STL-370-drop-bear_2024-04-05-10-30.json, common/changes/@gooddata/sdk-ui-all/IMJ-STL-370-drop-bear_2024-04-05-10-5.json
JIRA: STL-370
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: add drop bear changes

examples/playground/README.md, tools/mock-handling/src/backend.ts, tools/mock-handling/src/base/config.ts, tools/mock-handling/src/base/constants.ts, tools/mock-handling/src/base/types.ts, tools/mock-handling/src/index.ts
JIRA: STL-306
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove bear playground & mock-handling leftovers

docs/content/en/latest/learn/visualize_data/export_catalog.md, libs/api-client-tiger/README.md, libs/sdk-backend-tiger/src/index.ts, libs/sdk-model/src/insight/index.ts, libs/sdk-ui-ext/README.md, libs/sdk-ui/src/base/errors/GoodDataSdkError.ts, tools/catalog-export/src/cli/prompts.ts, tools/catalog-export/src/index.ts, tools/mock-handling/README.md, tools/mock-handling/src/index.ts
Remove unused options from catalog export
Remove mentions of platfrom from various places
JIRA: STL-382
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove info about platfrom

.github/workflows/push-fossa-update-attribution-file.yml, .github/workflows/rw-fossa-update-attribution-file.yml
JIRA: STL-375
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix Fossa att file generation

libs/sdk-ui-charts/src/charts/repeater/internal/dataViewToRepeaterData.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repeater inner charts

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts, libs/sdk-ui-kit/src/Header/tests/__snapshots__/generateHeaderMenuItemsGroups.test.ts.snap, libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
JIRA: LX-146
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: sanitize header menu item links to work on CDN hosted app

libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx
JIRA: F1-254
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-254 repeater can't render in UISDK with error from colorPalette

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/dateFilter.ts, libs/sdk-ui-tests-e2e/cypress/tools/filterBar.ts
JIRA: QA-21481
---
> [!IMPORTANT]
---
```
```
```
```
=> TRIVIAL: QA-21481 implement test available date filter

libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/repeaterAgGridDataSource.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repeater execution fixes

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/ShowAllFiltersButton.tsx
JIRA: STL-395
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show all filters button does not have type button attribute

docs/content/en/latest/Quick_start.md, tools/dashboard-plugin-template/README.template.md, tools/dashboard-plugin-template/src/harness/Root.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> fix bootstrapping new plugin and doc

common/changes/@gooddata/sdk-ui-all/jsc-f1-148_2024-04-09-11-27.json
JIRA: F1-148
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repeater changelog

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/repeater.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/repeater.ts, libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_child_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/reference_workspace/workspace_objects/goodsales/current_reference_workspace_objects_tiger.ts, libs/sdk-ui-tests-e2e/scenarios/src/components/Scenarios/Visualizations/Repeater/RepeaterFullConfigs.tsx, libs/sdk-ui-tests-e2e/scenarios/src/routes/ComponentResolver.tsx
JIRA: QA-21620
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-21620 Write E2E integrated Repeater

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts
The purpose is to add the new entitlement EXPERIMENTAL_FEATURES, but there are a lot of extra additions because of the port of some features from the Labs environment.
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: F1-247 regenerate API client with new entitlement

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-206
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: F1-206 can't overwrite new config of Repeater

docs/config/_default/config.toml, docs/content/en/latest/Quick_start.md, docs/content/en/latest/_index.md, docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md, docs/content/en/latest/introduction.md, docs/content/en/latest/learn/embed_dashboards/web_components/angular.md, docs/content/en/latest/learn/embed_dashboards/web_components/authentication.md, docs/content/en/latest/learn/integrate_and_authenticate/_index.md, docs/content/en/latest/learn/visualize_data/charts_and_plots.md, docs/content/en/latest/learn/visualize_data/create_custom_visualizations/_index.md, docs/content/en/latest/references/dashboard_component/dashboard_plugins.md, docs/content/en/latest/references/filters/_index.md, docs/content/en/latest/references/visual_components/bullet_chart.md, docs/content/en/latest/references/visual_components/sankey_chart.md, docs/package.json, scripts/htmltest.sh
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: DP-2801 doc handover

docs/content/en/latest/Quick_start.md, docs/content/en/latest/references/dashboard_component/dashboard_plugins_upgrade.md, tools/catalog-export/src/index.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> fix catalog-export and add doc 

docs/config/_default/params.toml
TRIVIAL
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: fix hugo local router

libs/sdk-ui-charts/src/charts/repeater/hooks/useResizing.ts, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/styles/scss/repeater.scss
JIRA: F1-209
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: F1-209 text wasn't truncated when resizing width of column

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/metadata-json-api/base.ts, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/base.ts, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/result.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts, libs/sdk-backend-tiger/src/index.ts
JIRA: LX-192
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add listing csv files to spec functions

libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/repeaterExecution.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
JIRA: F1-236
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: inline measures and repeater core chart

libs/sdk-backend-tiger/tests/README.md
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: add basic readme for tiger client integrated tests

libs/sdk-ui-dashboard/src/presentation/localization/IntlWrapper.tsx, libs/sdk-ui-dashboard/src/presentation/localization/createInternalIntl.ts, libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/index.tsx, libs/sdk-ui/src/base/localization/IntlWrapper.tsx, libs/sdk-ui/src/base/localization/intlUtils.tsx
JIRA: STL-165
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: add fallback to default when invalid locale provided

libs/sdk-ui-charts/src/charts/repeater/internal/repeaterExecution.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/PluggableRepeater.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repeater execution config

docs/content/en/latest/Quick_start.md
JIRA: STL-339
---
> [!IMPORTANT]
---
```
```
```
```
=> docs: update toolkit doc

docs/content/en/latest/references/visual_components/repeater_chart.md, libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx, libs/sdk-ui-charts/src/charts/repeater/Repeater.tsx, libs/sdk-ui-charts/src/charts/repeater/hooks/useDrilling.ts, libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx, libs/sdk-ui-charts/src/charts/repeater/internal/privateTypes.ts, libs/sdk-ui-charts/src/charts/repeater/publicTypes.ts, libs/sdk-ui-charts/styles/scss/repeater.scss
JIRA: F1-266
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: F1-266 support drilling

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/organization/index.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/organization/index.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelect.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: InvertableSelect fixes, earlyAccess attributes for ws and org

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/repeater.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/repeater.ts
JIRA: QA-21924
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-21924 fFix fail test because of bug F1-275

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts
The entitlement was removed on the backend.
JIRA: F1-247
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: remove ExperimentalFeatures entitlement name

libs/sdk-backend-base/src/customBackend/workspace.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/dataFilter/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-spi/src/workspace/ldm/model.ts, libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspace/ldm/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataFilter/index.ts, libs/sdk-model/src/index.ts
JIRA: LX-146
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: new SPI to replace direct API client usage in modeler and meditor

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/api-client-tiger/src/result.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
- deleteFiles
- readFileManifests JIRA: LX-208
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: propagate new CSV files APIs

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/repeater.spec.ts
JIRA: QA-21924
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-21924: Fix fail test because of bug f1-275

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/index.ts
JIRA: LX-208
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: reexport result type

libs/sdk-backend-tiger/src/backend/workspaces/index.ts
Fixes searche strings which contain spaces
JIRA: F1-282
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: use quotes for search string

.github/workflows/release-code-drop.yml, .github/workflows/release-postrelease.yml
JIRA: STL-436
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix slack notification

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: send organizationId for user feature flags, add FlexAI flag

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts
JIRA: F1-258
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: add OpenAI config org setting

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: QA-22026 Skip test export PDF with many data

libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterBody/tests/DateFilterBody.test.tsx, libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx, libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss
JIRA: LX-79
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: LX-79 Adjust embedded date filter height to screen viewport

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/result-json-api/api.ts, libs/api-client-tiger/src/generated/result-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataSources/index.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> Add support for Singlestore

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspaces/index.ts
withOptions({ includeChildWorkspacesCount: true })
JIRA: LX-217
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: make children count optional in workspaces query

common/changes/@gooddata/sdk-ui-all/ine-lx-214_2024-04-29-19-48.json, libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
JIRA: LX-214
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: import api now returns info about file

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/types/elementsLoader.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: LX-215, LX-183 feature flags for attribute filter fixes

libs/sdk-ui-kit/styles/scss/invertableSelect.scss
Fix flex wrap.
JIRA: F1-259
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: invertable select

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts
JIRA: QA-22000
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-22000 Fix failed test because SDK limit

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFilterConfigurationState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/hooks/useDependentDateFiltersConfiguration.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/shared/limitingItemsHook.ts
JIRA: LX-233
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: show default name of common date filter even for empty string

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
JIRA: LX-217
New feature flag to control enabling of new workspaces hierarchy view in Home UI.
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: introduce workspace hierarchy view feature flag

libs/sdk-backend-base/src/decoratedBackend/execution.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-base/src/normalizingBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/execution/index.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/afm/forecast.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/dateValueFormatter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/execution/results/index.ts, libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartForecast.ts, libs/sdk-ui-charts/src/highcharts/typings/unsafe.ts, libs/sdk-ui-charts/styles/scss/charts.scss, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx, libs/sdk-ui/api/sdk-ui.api.md, libs/sdk-ui/src/base/errors/GoodDataSdkError.ts, libs/sdk-ui/src/base/index.tsx, libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx, libs/sdk-ui/src/base/results/facade.ts, libs/sdk-ui/src/base/results/internal/resultDataMethods.ts
JIRA: F1-277
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: F1-277 loading and error state for forecasting

common/changes/@gooddata/sdk-ui-all/master_2024-05-06-14-05.json
JIRA: F1-277
---
> [!IMPORTANT]
---
```
```
```
```
=> TRIVIAL: F1-277 change log

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelectItem.tsx, libs/sdk-ui-filters/src/AttributeFilter/Context/AttributeFilterContext.tsx, libs/sdk-ui-filters/src/AttributeFilter/hooks/types.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterHandler.ts, libs/sdk-ui-filters/src/AttributeFilter/types.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/factory.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initTotalCount.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadIrrelevantElements/loadIrrelevantElementsSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/types.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/utils.ts
JIRA: LX-183
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow duplicated secondary label values in attribute filter (selection and insight filtering is not handled yet)

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartForecast.ts, libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartForecast.test.ts, libs/sdk-ui-charts/src/tests/forecast.test.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/forecast/tests/ForecastConfidenceControl.test.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/forecast/tests/ForecastSection.test.tsx
JIRA: F1-277
---
> [!IMPORTANT]
---
```
```
```
```
=> TRIVIAL: F1-277 added new tests

libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx, libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts, libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
JIRA: LX-203
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: LX-203 Add es-419,fr-CA,en-GB format locale

libs/sdk-ui-kit/styles/scss/header.scss
JIRA: F1-313
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: header button margin

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts
JIRA: F1-320
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: config of forecast in embedded if is in default state

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/useDrillDialogInsightDrills.ts
JIRA: F1-323
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: make drill dialog respect drilldown disable option and FF

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
JIRA: LX-258
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: introduce new feature flag for multiple data sources in workspace

libs/sdk-ui-charts/styles/scss/tooltip.scss, libs/sdk-ui-dashboard/styles/scss/drillSelect.scss, libs/sdk-ui-geo/styles/scss/tooltip.scss, libs/sdk-ui/src/base/localization/bundles/it-IT.json, libs/sdk-ui/src/base/localization/bundles/ja-JP.json, libs/sdk-ui/src/base/localization/bundles/pt-BR.json, libs/sdk-ui/src/base/localization/bundles/pt-PT.json
- Update interaction selector popup width to 230px - still works on smallest screen possible.
JIRA: LX-278
- Break viz. tooltip on small screens + reduce translated strings length.
JIRA: LX-279
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: LX-278, LX-279 Css fixes

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
Update extended reference point logic in heatmap to avoid duplicate bucket items.
JIRA: F1-366
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: heatmap

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-base/src/dummyBackend/tests/index.test.ts, libs/sdk-backend-mockingbird/src/recordedBackend/tests/index.test.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
Tests for new added org SPI
JIRA: F1-349
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: webhooks management for alerts and schedules

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx, libs/sdk-ui-kit/src/RichText/RichText.tsx, libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx
JIRA: F1-369
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: correctly wrap rich text with intl

libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx
JIRA: F1-369
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove rich text tooltip delay

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
JIRA: F1-369
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: change section description rich text rows

common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json
JIRA: STL-594
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix build warnings caniuse-lite is outdated

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx, libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/headerSection.spec.ts, libs/sdk-ui-tests-e2e/cypress/tools/sectionHeader.ts
JIRA: F1-369
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: flip enable rich text descriptions FF

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
JIRA: F1-408
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: feature flag for mother duck

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
JIRA: LX-268
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: introduce option to disable search autofocus for a legacy list

libs/sdk-ui-dashboard/styles/scss/layout.scss
JIRA: F1-423
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: rich text layout description styling

.github/workflows/rw-bump-version-major.yml, .github/workflows/rw-bump-version.yml, .github/workflows/rw-doc-release-apidocs.yml, .github/workflows/rw-doc-update-hugo-version.yml, .github/workflows/rw-fossa-update-attribution-file.yml, .github/workflows/rw-git-backmerge.yml
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix GA auto commits to meet new lint

.github/workflows/check-extended.yaml, .github/workflows/check.yaml, .github/workflows/gate.yaml, .github/workflows/post.yaml
=> feat(zuul-deprecation): Add workflows

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/gd-tiger-model/AnalyticalDashboardModelV2.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/dashboard.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/locales.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaReducers.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts, libs/sdk-ui-dashboard/src/model/store/meta/metaState.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/FiltersConfigurationPanel.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/ResetFiltersButton.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/styles/scss/_variables.scss, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
risk: low
JIRA: F1-427
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow to disable local saving and reset filter

libs/sdk-ui-charts/src/charts/repeater/CoreRepeater.tsx
risk: low
JIRA: F1-413
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: switching from a repeater with custom config freezes the UI

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadCustomElements/loadCustomElementsReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadCustomElements/loadCustomElementsSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadCustomElements.test.ts.snap, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadInitialElementsPage.test.ts.snap, libs/sdk-ui-filters/src/AttributeFilterHandler/test/__snapshots__/loadNextElementsPage.test.ts.snap
JIRA: LX-323
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove non-serializable value from payload

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
JIRA: LX-312
risk:low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add enableSnowflakeKeyPairAuthentication feature flag

.github/workflows/check-extended.yaml, .github/workflows/check.yaml, .github/workflows/gate.yaml, .github/workflows/post.yaml
JIRA: INFRA-3527
---
> [!IMPORTANT]
---
```
```
```
```
=> feat(zuul-deprecation): Use envs instead of secrets

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
risk: low
JIRA: LX-313
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: LX-313 SF key-pair auth generate client-tiger

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx, libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx, libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx, libs/sdk-ui-kit/src/RecurrenceForm/constants.ts, libs/sdk-ui-kit/src/RecurrenceForm/index.ts, libs/sdk-ui-kit/src/RecurrenceForm/locales.ts, libs/sdk-ui-kit/src/RecurrenceForm/types.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.ts, libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx, libs/sdk-ui-kit/src/Timepicker/utils/timeUtilities.ts, libs/sdk-ui-kit/src/index.ts, libs/sdk-ui-kit/styles/scss/main.scss, libs/sdk-ui-kit/styles/scss/recurrenceForm.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
risk: low
JIRA: F1-437
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: introduce recurrence form component for scheduling

common/config/rush/pnpm-lock.yaml, libs/sdk-ui-ext/package.json
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: remove unnecessary dep sdk-ui-filters from sdk-ui-ext

.github/workflows/rw-git-backmerge.yml
risk: nonprod
JIRA: STL-640
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix release backmage user token

libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
risk: low
JIRA: LX-313
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: LX-313 add missing properties to datasource

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
JIRA: F1-437
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add enableSchedulingRollout FF

libs/sdk-ui-dashboard/styles/scss/layout.scss
JIRA: F1-423
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: rich text layout desc styling

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSaga.ts
JIRA: LX-336
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: proper query options when searching

.github/workflows/push-webcomponents-deploy.yml, .github/workflows/slack-post-merge-notification.yml
risk: nonprod
JIRA: STL-645
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix runners definition for post merge pipelines

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx, libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx
- description was cut off after 1024 chars
- missing translation when passed as a react component
JIRA: F1-423
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: additional rich text issues

.github/workflows/push-jenkins-e2e-jobs.yaml
riks: nonprod
JIRA: STL-646
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: remove storybook build from jenkins postmerge flow

.github/workflows/push-jenkins-e2e-jobs.yaml
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: skip postmerge e2e when commit is just version bump

libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts
risk: low
JIRA: F1-427
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: FF for disable reset filter button

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
risk: low
JIRA: F1-427
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: feature flag for disable reset filter button

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
Generate api-client with new authenticationType for data sources.
risk: low
JIRA: LX-335
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: LX-335 Add authenticationType info

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: handle missing schedule destinations

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/index.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/react/useOrganizationWebhooks.ts, libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/types.ts, libs/sdk-ui-dashboard/src/model/store/webhooks/index.ts, libs/sdk-ui-dashboard/src/model/store/webhooks/webhooksReducers.ts, libs/sdk-ui-dashboard/src/model/store/webhooks/webhooksSelectors.ts, libs/sdk-ui-dashboard/src/model/store/webhooks/webhooksState.ts, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/types.ts, libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx
- introduce webhooks dashboard state slice
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: show scheduling conditionally

libs/sdk-ui-web-components/Dockerfile
* remove crontabs
* set CREATE_HOME=yes in login.defs
* do NOT add custom paths to PATH
risk: low
JIRA: INFRA-3687
---
> [!IMPORTANT]
---
```
```
```
```
=> feat(docker): address mastercard security objections

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/dashboard.ts, libs/sdk-ui-filters/api/sdk-ui-filters.api.md, libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/bridge.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/loader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/displayForms/displayFormsReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/filter/filterSelectors.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadCustomElements/loadCustomElementsReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/state.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/types/attributeFilterLoader.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/types/elementsLoader.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repare some AF use cases + KD config preparation

common/changes/@gooddata/sdk-ui-all/pb-deauth-returnurl_2024-07-02-12-13.json, libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/index.ts, libs/sdk-backend-base/src/toolkit/auth.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/backend/index.ts, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/auth.ts, libs/sdk-backend-tiger/src/backend/index.ts, libs/sdk-backend-tiger/src/tests/auth.test.ts
JIRA: STL-458
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: support returnTo with deauthenticate

libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-ui-dashboard/src/model/react/useWorkspaceAutomations.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Textarea.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
- responsiveness
- automation object saving
- automation loading
- initial cron value fix
- textarea updates
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: multiple scheduling enhancements

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/entitlements/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts, libs/sdk-ui-dashboard/src/model/store/entitlements/entitlementsSelectors.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: connect scheduling entitlements

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/automations/index.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/utils.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> scheduling form fixes

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useCreateScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useUpdateScheduledEmail.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: propagate error response to scheduling form

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: enable repeater by default

libs/sdk-embedding/api/sdk-embedding.api.md, libs/sdk-embedding/src/iframe/EmbeddedGdc.ts
JIRA: LX-347
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: extend postMessage by AF config

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
Actually define the feature, without it the SDK will not propagate it to the UI apps.
risk: low
JIRA: CQ-603
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add the enableRollupTotals feature

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/DeleteScheduleConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: enable schedule delete from edit mode

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/GrandTotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/TotalsConverter.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/TotalsConverter.test.ts.snap, libs/sdk-ui-pivot/src/locales.ts
Also add the localization mapping for pivot table.
risk: low
JIRA: CQ-603
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: add native total handling to tiger converters

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts
Update data source patch request interface authentication parameters type, to allow `null`.
- token
- privateKey
- password
- privateKeyPassphrase
risk: low
JIRA: LX-359
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: LX359 update DS patch interface

common/scripts/ci/run-sdk-backend-tiger-integration-tests-with-live-backend.sh, libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/v2/VisualizationObjectConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/InsightConverter.ts, libs/sdk-embedding/src/internal/filterConvertors.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add displayAsLabel to postMessage converter + ref converter fix

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataSources/index.ts
- added metadataSync and semanticSearch feeds
- added flightrpc datasource
JIRA: CQ-582
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: api client update

common/changes/@gooddata/sdk-ui-all/jsc-patch-10.5_2024-07-12-09-57.json
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: add fix changelog

common/changes/@gooddata/sdk-ui-all/ach-gen-ai-backend_2024-07-12-09-29.json, libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/execution.ts, libs/sdk-backend-base/src/customBackend/workspace.ts, libs/sdk-backend-base/src/decoratedBackend/analyticalWorkspace.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/index.ts, libs/sdk-backend-spi/src/workspace/genAI/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-backend-tiger/src/backend/workspace/genAI/index.ts, libs/sdk-backend-tiger/src/backend/workspace/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/genAI/index.ts, libs/sdk-model/src/index.ts
- added genAI service to the backend
JIRA: CQ-582
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: tiger backend for semantic search

libs/sdk-backend-tiger/src/backend/uiSettings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add used Tiger feature flags to ISettings interface

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/SettingItem/typings.ts
JIRA: LX-372
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow react element in setting item component

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/SettingItem/SettingItem.tsx, libs/sdk-ui-kit/src/SettingItem/typings.ts
JIRA: LX-372
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow to define hide delay for setting item tooltip

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx, libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss, libs/sdk-ui-dashboard/styles/scss/layout.scss, libs/sdk-ui-kit/styles/scss/richText.scss
Correct the design of the rich text descriptions
according to figma files.
risk: low
JIRA: F1-475
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: rich text descriptions design corrections

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/notificationChannels/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/types.ts
risk: low
JIRA: F1-437, F1-482
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: propagate hasToken info + repair of payload data

libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
risk: low
JIRA: F1-482
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: use patch method

libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/constants.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectionSaga.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadCustomElements/loadCustomElementsReducers.ts, libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: avoid API request-response mismatch

libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/exportDefinitions/index.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts, libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/types.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/types.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss
- when scheduling dialog is opened with widget context, we use tabular attachments and create appropriate export definitions for particular widget
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: allow scheduling of widgets

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
JIRA: F1-505
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: hide scheduling in insight menu behind FF

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillDownHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToInsightHandler.ts, libs/sdk-ui-ext/api/sdk-ui-ext.api.md, libs/sdk-ui-ext/src/index.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/PluggableColumnBarCharts.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/UnknownVisualizationDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/AreaChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/BarChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/BaseChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/BulletChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/ColumnChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/HeatmapDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/LineChartDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PivotTableDescriptor.ts, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/PluggableTreemap.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/TreemapDescriptor.ts, libs/sdk-ui-ext/src/internal/interfaces/VisualizationDescriptor.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: secondary label in D2I and DD + CF fix

libs/sdk-ui-dashboard/src/model/store/insights/insightsSelectors.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentFilters.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss, libs/sdk-ui-kit/styles/scss/recurrenceForm.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> scheduling styling and design fixes

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
Filters were outdated because bad deps in hook
JIRA: LX-382, LX-383
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: proper deps to have up to date filters

libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelectItemTooltip.tsx, libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/SingleSelectionAttributeFilterElementsSelectItem.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterElementsSelect.scss
JIRA: LX-387
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add item tooltip to single select filters

libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
Make code around earlyAccessValues more reliable.
JIRA: F1-507
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: early access flags

libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelectItemTooltip.tsx, libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterElementsSelect.scss
+ do not show label title when no value available
JIRA: LX-387
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: avoid collision with tick icon on mobile

libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/execution/index.ts, libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts, libs/sdk-ui-charts/api/sdk-ui-charts.api.md, libs/sdk-ui-charts/src/interfaces/chartConfig.ts, libs/sdk-ui-ext/src/internal/components/configurationControls/InputControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationControls/clustering/ClusteringThresholdControl.tsx, libs/sdk-ui-ext/src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx, libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx, libs/sdk-ui-ext/src/internal/constants/scatter.ts, libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts, libs/sdk-ui-ext/src/internal/translations/en-US.json, libs/sdk-ui-ext/src/locales.ts
Extend clustering configuration with threshold option.
risk: low
JIRA: F1-515
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: support for clustering threshold config

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/export-json-api/api.ts, libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/scan-json-api/api.ts, libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-backend-tiger/src/backend/workspace/automations/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/entitlements/index.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> regenerate client and fix automations call

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
This flag was enabled by default for quite some time so let's simplify things and remove it.
risk: low
JIRA: CQ-647
---
> [!IMPORTANT]
---
```
```
```
```
=> chore: remove the enableDirectQuery feature flag

libs/sdk-model/src/internal.ts, libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts, libs/sdk-ui-dashboard/src/converters/filterConverters.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/common/validateDrillToCustomUrlParams.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/getElementTitle.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParameters.tsx, libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/DashboardParametersSection.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillTargets/useInvalidFilteringParametersIdentifiers.ts
- dash AF secondary labels are offered in Custom Url editor
- secondary label values are resolved during drill
JIRA: LX-318
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: secondary labels in drill to uri

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts, libs/sdk-ui-dashboard/src/model/eventHandlers/drillToSameDashboardHandlerFactory.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: secondary label filters fixes

libs/sdk-ui-web-components/Dockerfile
sys_default_acc-1: System Default Non-Root User Default Shell Check
non-root users must have /sbin/nologin as login shell
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat(docker): more mastercard container hardening

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dashboard/baseWidget.ts, libs/sdk-model/src/settings/index.ts
JIRA: F1-523
risk: medium
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: store widget localIdentifier in dashboard layout

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/exportDefinitions/index.ts, libs/sdk-model/src/index.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: retype export definitions

libs/sdk-ui-tests-e2e/cypress/tools/export.ts, libs/sdk-ui-tests-e2e/cypress/tools/exportOption.ts
JIRA: QA-22707
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-22707 Remove uneccessary css of export option menu

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useFiltersWithAddedPlaceholder.tsx
risk: low
JIRA: LX-395
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: LX-395 Handle attr autopen with duplicate labesl

libs/sdk-ui-kit/styles/scss/richText.scss
JIRA: F1-526
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: rich text bold styling

libs/sdk-ui-kit/styles/scss/richText.scss
JIRA: F1-526
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: rich text hyperlink style

libs/sdk-backend-tiger/src/utils/widgetLocalIdentifier.ts
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: use safe optional chaining on window

libs/sdk-ui-all/CHANGELOG.json, libs/sdk-ui-all/CHANGELOG.md
risk: nonprod
JIRA: STL-718
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: fix SDK change log and remove duplicities

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/exportDefinitions/index.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: store widget and dashboard identifiers in visualization automation

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> widget automation edit mode and list icon

docs/content/en/latest/references/visual_components/scatter_plot.md
Mention clustering and segmentation in the scatter plot docs. Add clustering example.
risk: low
JIRA: F1-533
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: scatter plot clustering docs

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/DrillIntersectionIgnoredAttributes.tsx
Do not show configuration for insights without attributes.
risk: low
JIRA: F1-521
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: drill intersection filtering configuration

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
risk: low
JIRA: F1-538
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: disable schedule if no local identifier on widget

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
JIRA: F1-437
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: store widget filters in export definition

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts
JIRA: F1-501
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: always show common date filter in list of schedule filters

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
JIRA: F1-544
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: send organization tier to feature hub

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/profile.ts, libs/sdk-backend-tiger/src/backend/features/hub.ts, libs/sdk-backend-tiger/src/backend/features/index.ts, libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts, libs/sdk-backend-tiger/src/backend/user/settings.ts, libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
This reverts commit b7db797e2251e32d929884f8b2f5232c9ad00f58.
---
> [!IMPORTANT]
---
```
```
```
```
=> Revert "feat: send organization tier to feature hub"

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/automations/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commands/scheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useCreateScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useUpdateScheduledEmail.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> scheduling filters cleanup and dashboard relationship

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts
JIRA: F1-545
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: do not allow date filters without dataset to be stored in exportDef

libs/sdk-ui-tests-e2e/cypress/tools/export.ts, libs/sdk-ui-tests-e2e/cypress/tools/exportOption.ts
JIRA: QA-22707
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: QA-22780 Cherry pick Remove uneccessary css of export option menu to release branch

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
Enable `enableDrillIntersectionIgnoredAttributes`
feature flag by default.
risk: low
JIRA: F1-548
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: enable drill filtering by default

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
JIRA: F1-540, F1-545
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> scheduling fixes for dashboard relationship and filters

libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx, libs/sdk-ui-semantic-search/styles/scss/internal.scss, libs/sdk-ui-semantic-search/styles/scss/main.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
- Updated error message to fit design
- Enforce link styling (was overriden by KD)
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 minor fixes for semantic search

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/client.ts, libs/api-client-tiger/src/export.ts, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/auth-json-api/api.ts, libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
risk: low
JIRA: F1-531
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: refactor NotificationChannel

common/config/rush/pnpm-lock.yaml, examples/sdk-interactive-examples/examples/example-execute/package.json, libs/sdk-ui-charts/package.json, libs/sdk-ui-dashboard/package.json, libs/sdk-ui-ext/package.json, libs/sdk-ui-filters/package.json, libs/sdk-ui-geo/package.json, libs/sdk-ui-kit/package.json, libs/sdk-ui-vis-commons/package.json, libs/sdk-ui/package.json
risk: low
JIRA: STL-742
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: fix version of default-import and node min version 20

libs/util/src/tests/translationUtils.test.ts
risk: low
JIRA: LX-411
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: UT with new chinese locales

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
JIRA: LX-431
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: use proper FF selector

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts
JIRA: LX-389
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: improve matching filters via secondary label

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
JIRA: F1-540, F1-545
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: sanitize export definition filter ids in converters

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
JIRA: F1-569
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: enable widget identifiers by default

.github/workflows/push-webcomponents-deploy.yml
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: build webcomponents only from master

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/settings/index.ts, libs/sdk-backend-tiger/src/backend/organization/settings.ts, libs/sdk-backend-tiger/src/backend/settings/mapping.ts, libs/sdk-backend-tiger/src/backend/settings/settings.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx, libs/sdk-ui-kit/src/RecurrenceForm/constants.ts, libs/sdk-ui-kit/src/RecurrenceForm/index.ts, libs/sdk-ui-kit/src/RecurrenceForm/locales.ts, libs/sdk-ui-kit/src/RecurrenceForm/types.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.ts, libs/sdk-ui/src/base/localization/bundles/en-US.json
Load setting from server
Added into spi + all necessary places
Recurrence form update to be able to work without Date
risk: low
JIRA: F1-534
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: setting for default alert

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts
JIRA: LX-393
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: handle ignored filters when DF changed

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeDescription.tsx, libs/sdk-ui-kit/src/RecurrenceForm/locales.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts, libs/sdk-ui-kit/src/RecurrenceForm/utils.ts, libs/sdk-ui-kit/styles/scss/recurrenceForm.scss, libs/sdk-ui/src/base/localization/bundles/en-US.json
Match to design specs
risk: low
JIRA: F1-534
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: setting for default alert

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/constants/index.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertActionsDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonOperatorSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertMeasureSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertTriggerModeSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlertConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/constants.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/messages.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuItemButton.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts, libs/sdk-ui-dashboard/styles/scss/alerting.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> Alerting enhancements

libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts, libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx, libs/sdk-ui-filters/src/DateFilter/utils/FormattingUtils.ts, libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
risk: low
JIRA: LX-415
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: LX-415 Add new languages date format granularities

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx, libs/sdk-ui-dashboard/styles/scss/alerting.scss
JIRA: F1-535
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: alerting copywrite and entitlement logic

libs/sdk-ui-dashboard/styles/scss/configurationPanel.scss
JIRA: LX-421
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: make icon margin in dashboard config panel consistent in SDK/KD

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/tests/index.test.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/organization/notificationChannels/index.ts, libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/notificationChannels/index.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/types/commonTypes.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
- Webhooks
- Emails
- All
JIRA: F1-535
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: rework of notification channels factory

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/messages.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
JIRA: F1-535
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: include widget filters in alert definition

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/styles/scss/scheduled_mail.scss, libs/sdk-ui-kit/styles/scss/dialogList.scss
JIRA: F1-462, F1-468
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: scheduling styling

common/changes/@gooddata/sdk-ui-all/jsc-f1_2024-08-19-11-35.json
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: add changelog for drill down intersection

.github/actions/branch-cutoff-action/action.yml, .github/workflows/release-code-drop.yml, .github/workflows/rw-perform-release-major-minor.yml, .github/workflows/rw-perform-release.yml
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: align SDK release on protected branches

docs/content/en/latest/learn/add_interactivity/_index.md, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/genAI/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/genAI/index.ts, libs/sdk-ui-semantic-search/api/sdk-ui-semantic-search.api.md, libs/sdk-ui-semantic-search/src/SemanticSearch.tsx, libs/sdk-ui-semantic-search/src/hooks/useSemanticSearch.ts, libs/sdk-ui-semantic-search/src/index.ts
- Promoted @alpha to @beta for semantic search
- Added a short docs
---
> [!IMPORTANT]
---
```
```
```
```
=> Semantic search as beta

docs/content/en/latest/learn/add_interactivity/_index.md, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/genAI/index.ts, libs/sdk-backend-spi/src/workspace/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/genAI/index.ts, libs/sdk-ui-semantic-search/api/sdk-ui-semantic-search.api.md, libs/sdk-ui-semantic-search/src/SemanticSearch.tsx, libs/sdk-ui-semantic-search/src/hooks/useSemanticSearch.ts, libs/sdk-ui-semantic-search/src/index.ts
- Bumped semantic search APIs to beta
- Added docs
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 Semantic search bump to beta

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/PauseAlertRunner.tsx
- Remove unwanted dependency
JIRA: F1-535
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: implementation of management alerts

libs/api-client-tiger/scripts/generate.js
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: make api generate script executable again

.github/actions/branch-cutoff-action/action.yml
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> ci: fix branch cutoff action

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts
JIRA: F1-586
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: introduce FF for insight changed post event event change

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/afm-rest-api/api.ts, libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/api-client-tiger/src/index.ts, libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/DefaultAlertingManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/AlertDropdown.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/AlertsList.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/DeleteAlertConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/PauseAlertRunner.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/Attachments.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/DeleteScheduleConfirmDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx, libs/sdk-ui-dashboard/styles/scss/dashboard.scss, libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
- Refactor of alerts and schedules dialogs to common notifications dialog
- Added FF for smtp enablement
- Allerts pause / unpause implmenetation
---
> [!IMPORTANT]
---
```
```
```
```
=> feature: some updates related to alerts and schedules

libs/sdk-backend-base/api/sdk-backend-base.api.md, libs/sdk-backend-base/src/decoratedBackend/dashboards.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dashboards/widgetFilters.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/layout/validation/itemValidation.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetFilterSettingsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeKpiWidgetFilterSettingsHandler.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/filterValidation.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetBrokenAlerts.ts, libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts, libs/sdk-ui-dashboard/src/model/utils/alertsUtils.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/AttributeFilterConfigurationItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/FilterConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/kpi/common/filterUtils.ts
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: widget ignored filters with displayAsLabel

libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/notificationChannels/index.ts
JIRA: F1-535
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: support for default smtp

libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
risk: low
JIRA: LX-468
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: wrong translation

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
JIRA: F1-535
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: support setting alerts for more types of vis

libs/sdk-backend-mockingbird/src/recordedBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/styling/index.ts, libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts, libs/sdk-backend-tiger/src/backend/workspace/styling/index.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/dataFilter/index.ts
JIRA: LX-463
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat(spi): introduce workspace SPI for clearing of theme and palette

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
JIRA: F1-612
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: refresh automations on alert pause and resume

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
[Alerting M1] Update alert description based on language settings
JIRA: F1-611
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: update alert description based on language settings

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
JIRA: F1-596
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: remove all time date filter from alert filters

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
JIRA: F1-535
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: repair of destination select

libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
JIRA: F1-595
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: cron frequency validation

libs/sdk-ui-dashboard/src/presentation/deleteDialog/DefaultDeleteDialog.tsx, libs/sdk-ui-dashboard/src/presentation/deleteDialog/types.ts
JIRA: F1-535
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: extend dashboard delete dialog with objects conditions

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/FilterConverter.ts
JIRA: F1-535
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: automation filters converter breaking state

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
Show and propagate proper title for arithmetic measures in alerting.
risk: low
JIRA: F1-627
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: arithmetic measure title in alerting

libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
Added a threshold option to not show less relevant results
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 result threshold

libs/sdk-ui-pivot/src/impl/data/dataSource.ts
JIRA: STL-726
risk: high
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: add timeout to fix sort+undo in react 18

libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx, libs/sdk-ui-dashboard/src/presentation/constants/colors.ts, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useScheduleValidation.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useAlertValidation.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx, libs/sdk-ui-dashboard/styles/scss/alerting.scss, libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> existing automations validation

libs/sdk-backend-tiger/src/backend/features/feature.ts, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/settings/index.ts
Added enableSemanticSearch flag for the UI, to make it configurable through experimental features.
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 new feature flag

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/convertors/toBackend/afm/toAfmResultSpec.ts, libs/sdk-backend-tiger/src/index.ts
JIRA: F1-643
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: expose toAfmExecution method

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/constants.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
JIRA: F1-462
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: scheduling dialog mobile view

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
JIRA: F1-529
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: tests for alert transformations and utils

libs/sdk-ui-dashboard/src/_staging/sharedHooks/useFiltersNamings.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentFilters.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useAttachmentDashboardFilters.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
- skip stored filter when it is missing on dashboard
- fix scheduling dialog scroll
JIRA: F1-593, F1-498
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: multiple scheduling bugs

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts
JIRA: QA-22915
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: add wait to make sure dashboard edit mode has been loaded before editing

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
JIRA: F1-529
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: comparison only for headline

libs/sdk-backend-base/src/cachingBackend/index.ts, libs/sdk-backend-base/src/decoratedBackend/automations.ts, libs/sdk-backend-base/src/dummyBackend/index.ts, libs/sdk-backend-spi/api/sdk-backend-spi.api.md, libs/sdk-backend-spi/src/workspace/automations/index.ts, libs/sdk-backend-tiger/src/backend/workspace/automations/automationsQuery.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadWorkspaceAutomations.ts
JIRA: F1-593
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: automations query paging

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
JIRA: F1-658
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: disable alert creation when widget has no local identifier

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonOperatorSelect.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
[Alerting M3] Does not send email on Widget contains Comparison with previous period
JIRA: F1-666
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: wrong alert definition transform repair

examples/playground/.env.template, examples/playground/README.md, examples/playground/src/App.tsx, examples/playground/typings/vite-env.d.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts, libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsReducers.ts, libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsReducersSelectors.ts, libs/sdk-ui-dashboard/src/model/store/filterViews/filterViewsState.ts, libs/sdk-ui-dashboard/src/model/store/filterViews/index.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/AddFilterView.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx, libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViewsList.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> Various saved filter views bug fixes

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/MeasureConverter.ts
JIRA: F1-685
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: automation with change/different got error when edit

libs/sdk-ui-semantic-search/src/hooks/tests/useSearchMetrics.test.ts, libs/sdk-ui-semantic-search/src/hooks/useSearchMetrics.ts, libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
log additional properties for metrics hook
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: CQ-582 metrics improvements

libs/sdk-ui-dashboard/.dependency-cruiser.cjs, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/automationHelpers.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
JIRA: F1-696
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: default automation recipients

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
[Alerting M3] Does not send email on Widget contains Comparison with previous period
JIRA: F1-666
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: does not send email on Widget contains PP

libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightEditMenuBubble.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/ToolbarBottom.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/ToolbarTop.tsx, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherToolbar.scss, libs/sdk-ui-kit/styles/scss/bubble.scss
Revert changes in global styles to prevent issues in other apps. Replace by local styling of Toolbar
JIRA: LX-493
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: revert style changes

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts, libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts, libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/index.ts, libs/sdk-model/src/notificationChannels/index.ts
JIRA: F1-698
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: add custom dashboard url in notification channel

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
JIRA: F1-701
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: use relative only on change type

libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
JIRA: F1-662
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: repair of password patch

docs/content/en/latest/references/filters/attribute_filter.md
JIRA: DP-1
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: docs fix for broken article title

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts, libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
JIRA: F1-696
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: reset recipients only when allowed recipients change to creator

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/utils/fixNumber.ts
JIRA: F1-704
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: floating point numbers precision in alerts

libs/api-client-tiger/api/api-client-tiger.api.md, libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json, libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md, libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/ObjectInheritance.ts, libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts, libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts, libs/sdk-model/api/sdk-model.api.md, libs/sdk-model/src/automations/index.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
JIRA: F1-694
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: formats metrics in email

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/Toolbar.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/EditableDashboardVisualizationSwitcherWidget.tsx
JIRA: LX-524
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: close switcher toolbar

common/changes/@gooddata/sdk-ui-all/ine-lx-423_2024-09-24-07-03.json, libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
JIRA: LX-423
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: release saved filter views for public

libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts, libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/insightReferences.ts, libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts, libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts, libs/sdk-ui-dashboard/src/model/store/executed/executedReducers.ts, libs/sdk-ui-dashboard/src/model/store/executed/executedSelectors.ts, libs/sdk-ui-dashboard/src/model/store/executed/executedState.ts, libs/sdk-ui-dashboard/src/model/store/executed/index.ts, libs/sdk-ui-dashboard/src/model/store/index.ts, libs/sdk-ui-dashboard/src/model/store/types.ts, libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/AllVisualizationsDashInsights.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/EditModeDashboardVisualizationSwitcher.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/useExecutionProgress.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useAlertingAndScheduling.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx, libs/sdk-ui-dashboard/styles/scss/insightConfiguration.scss, libs/sdk-ui-dashboard/styles/scss/main.scss, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherHeader.scss, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherWidget.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: Switcher in View mode + exec optimization

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
Fix nonsensical mixing of isLoading states.
Risk: Low
JIRA: F1-727
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: infinite setState issue in useInsightAlerting

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightConfiguration.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/VisualizationConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/useVisualizationSwitcherEditableInsightMenu.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: hide title config in switcher toolbar + fixes 

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/constants.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
JIRA: F1-725
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: get alert measure format from catalog

libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
JIRA: F1-696
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: persist allowed recipients in notification channel

libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/VisualizationsList.tsx, libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherHeader.scss, libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherToolbar.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: Switcher list and title fixes

libs/sdk-ui-gen-ai/src/components/EmptyState.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatOverlay.tsx, libs/sdk-ui-gen-ai/src/components/Input.tsx, libs/sdk-ui-gen-ai/src/components/Messages.tsx, libs/sdk-ui-gen-ai/src/components/messages/FoundObjects.tsx, libs/sdk-ui-gen-ai/src/store/messages/tests/messagesSelectors.test.ts
Use `connect` API instead of hooks to get chatbot working in AD 🗿
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 downgrade redux api

libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuItemButton.tsx
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: allow bubble events in insight menu buttons

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> trivial: store widget name in alert details

libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx, libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx, libs/sdk-ui-gen-ai/src/hooks/useGenAIStore.ts, libs/sdk-ui-gen-ai/styles/scss/messages.scss, libs/sdk-ui-gen-ai/styles/scss/window.scss
- Wrapped component into backend and workspace provider, so that charts are rendered when backend is passed explicitly
- Fixed minor styling issues
---
> [!IMPORTANT]
---
```
```
```
```
=> RELATED: F1-645 backend provider

libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/EditableDashboardVisualizationSwitcherWidget.tsx
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: DDS handling and Save As New

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx
JIRA: LX-491
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: LX-491 Vis. Switcher telemetry

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/FilterConverter.ts
JIRA: F1-743
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: handle localIdentifier in automation filters converter

libs/sdk-backend-tiger/src/backend/uiFeatures.ts, libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
JIRA: LX-423
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: enable saved filter views on production

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/FilterConverter.ts
JIRA: F1-743
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: enforce attribute filter identifiers in alert filter convertor

libs/sdk-ui-kit/api/sdk-ui-kit.api.md, libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx, libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx
JIRA: F1-745
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: add recurrence dropdown open callback for telemetry

libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherWidget.scss
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: switcher style overrides

libs/sdk-ui-dashboard/styles/scss/alerting.scss
JIRA: F1-740
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: alert trigger text theming

libs/sdk-backend-tiger/src/backend/features/index.ts
Override feature hub to disable alerting and scheduling features for release 10.11.0.
JIRA: F1-753
---
> [!IMPORTANT]
---
```
```
```
```
=> fix: disable alerting / scheduling

libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/ToolbarBottom.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/VisualizationConfig.tsx, libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/useVisualizationSwitcherEditableInsightMenu.tsx, libs/sdk-ui-geo/src/GeoChart.ts
- Allow to remove insight inside Vis. Switcher from it's config panel.
risk: low
JIRA: LX-533
---
> [!IMPORTANT]
---
```
```
```
```
=> BUGFIX: LX-533 Remove vis config panel

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md, libs/sdk-ui-dashboard/src/model/events/userInteraction.ts, libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsCommands.tsx, libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsDialog.ts, libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useSaveScheduledEmailToBackend.ts, libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts, libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useSaveAlertToBackend.ts
JIRA: F1-745
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: propagate user interaction events in scheduling and alerting

libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-419.json, libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-CA.json
risk: low
JIRA: LX-504
---
> [!IMPORTANT]
---
```
```
```
```
=> FEATURE: LX-504 update strings requested by RC

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsDialog.ts
JIRA: F1-745
risk: low
---
> [!IMPORTANT]
---
```
```
```
```
=> feat: extend schedule telemetry payload
