.github/pull_request_template.md
docs/contributing.md

RELATED: RAIL-1815 add commit and PR message guide, extend PR checklist

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/tests/CorePivotTable.test.tsx

---
---
TBD
-   [ ]
SD-1026: https://jira.intgdc.com/browse/SD-1026

FEATURE: SD-1026 Merge modifications made by SD-995 to SDK8

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx

---
---
TBD
-   [ ]
SD-1026: https://jira.intgdc.com/browse/SD-1026

FEATURE: SD-1026 Merge modifications made by SD-1014 to SDK8

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts

Reflect the fact the date datasets' availability is dictated
by their attribute availability in tiger. This means that
the relevantRestrictingTypes will now never be empty,
so the branch handling that was also removed.
Finally, one now unnecessary cast to any was removed
and an appropriate Error type was used.
JIRA: RAIL-2509
---
--- …

RELATED: RAIL-2509 fix date dataset availability in tiger

---

libs/sdk-model/__mocks__/model.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/buckets/bucketArray.ts
libs/sdk-model/src/execution/buckets/index.ts
libs/sdk-model/src/execution/buckets/tests/bucket.test.ts
libs/sdk-model/src/execution/buckets/tests/bucketArray.test.ts
libs/sdk-model/src/execution/measure/index.ts
libs/sdk-model/src/execution/measure/tests/typeGuards.test.ts
libs/sdk-model/src/index.ts
libs/sdk-model/src/insight/index.ts
libs/sdk-model/src/insight/tests/insight.test.ts
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui/__mocks__/fixtures.ts
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/measureTitles/ignoreTitlesForSimpleMeasures.ts
libs/sdk-ui/src/base/measureTitles/tests/ignoreTitlesForSimpleMeasures.test.ts

---
---
TBD
-   [ ]
SD-1026: https://jira.intgdc.com/browse/SD-1026

FEATURE: SD-1026 Merge modifications made by SD-1012 to SDK8

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/drills.ts

RAIL-2093 Add support for drill to url

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/drills.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/drills.ts

RAIL-2093 Add support for drill to url in sdk-backend-bear

---

examples/sdk-examples/src/examples/insightView/index.tsx
libs/sdk-ui-charts/src/charts/_base/BaseChart.tsx
libs/sdk-ui-ext/scripts/build.sh
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/styles/scss/insightView.scss
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

---
---
-   [x] commit messages adhere to the [commit message guidelines](docs/contributing.md#what-should-the-commits-look-like)

BUGFIX: RAIL-2563, RAIL-2564, RAIL-2566, RAIL-2556 Fix empty value handling for charts, styling issues, and label drill mode

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx

BUGFIX: RAIL-2569 Add Xirr insight into BaseVisualization list of supported insights

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

RAIL-2093 Fix availableDrillTargets in pushData

---

libs/sdk-backend-bear/src/backend/workspace/metadata/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/MetaConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/ldm/metadata/attribute/factory.ts
libs/sdk-model/src/ldm/metadata/attribute/index.ts

RAIL-2093: Include display forms in attribute metadata object

---

libs/sdk-backend-bear/src/backend/workspace/metadata/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/MetaConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/ldm/metadata/attributeDisplayForm/factory.ts
libs/sdk-model/src/ldm/metadata/attributeDisplayForm/index.ts

RAIL-2093 Add support for display form type

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts

RELATED: ONE-4584 - Fix drillableItems props typings in BaseVisualization and PluggablePivotTable

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

BUGFIX: RAIL-2575 Add localised error messages and descriptions handling for InsightView

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts

RAIL-2093: Temp filter context error is propagated correctly

---

examples/sdk-examples/src/constants/fixtures.ts
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-pivot/src/CorePivotTable.tsx

RELATED: RAIL-2575 Fix error handling for insightView

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts
libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx

- Add width prop to BaseVisualization
- Add properties and references to IVisualizationWidget
---
---

TRIVIAL: Add width prop to BaseVisualization, add properties and references to visualizationWidget

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/plugins/dataLabelsColors.ts

Re-color data labels in column charts to fix label color when drill is active.
Use the intersection of the label with the column to set proper color.
Also contains the fix for combo charts (fixed separately in 7.x)
Ref: https://github.com/gooddata/gooddata-react-components/pull/1724, https://github.com/gooddata/gooddata-react-components/pull/1745
---
---
-   [ …

RELATED: ONE-4459 ONE-4593 sdk-ui: fix data labels coloring

---

libs/sdk-backend-bear/api/sdk-backend-bear.api.md
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/widget.ts

RAIL-2093: Add properties to IWidget

---

libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

Uniq available drill target attributes by display form

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/ad.ts

JIRA: SD-1050
---
---
-   [x] (not applicable) `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

RELATED: SD-1050 Add new ad event type visualizationCancelled to sdk-embedding

---

libs/sdk-ui-pivot/src/impl/agGridApiWrapper.ts

TRIVIAL: Fix edge case for uninitialized ag-grid

---

libs/sdk-backend-bear/src/backend/index.ts

Both are needed for certain embedding scenarios.
JIRA: RAIL-2107
---
---

RELATED: RAIL-2107 add two bear legacy functions

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

BUGFIX: ONE-4613 Fix pushData for the PluggableGeoPushpinChart.tsx

---

libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

To avoid handling of default value in analytical-designer or dashboards codebase.
--
---

tiger: Move specific FFs in SDK

---

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts
libs/sdk-backend-bear/src/convertors/fromBackend/ExecutionResultConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/execution/index.ts
libs/sdk-backend-spi/src/workspace/execution/results.ts
libs/sdk-ui/src/base/results/facade.ts

RELATED: RAIL-2524 Add support for execution warnings

---

libs/api-client-bear/src/gooddata.ts
libs/api-client-bear/src/ldm.ts
libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/executeAfm/GdcExecuteAFM.ts
libs/api-model-bear/src/executeAfm/tests/GdcExecuteAFM.fixtures.ts
libs/api-model-bear/src/filterContext/GdcFilterContext.ts
libs/sdk-backend-bear/src/backend/workspace/elements/elements.ts
libs/sdk-backend-bear/src/backend/workspace/metadata/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/filterContext.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/utils/api.ts
libs/sdk-backend-mockingbird/src/recordedBackend/elements.ts
libs/sdk-backend-mockingbird/src/recordedBackend/metadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/filterContext.ts
libs/sdk-backend-spi/src/workspace/elements/index.ts
libs/sdk-backend-spi/src/workspace/metadata/index.ts
libs/sdk-backend-tiger/src/backend/workspace/elements/index.ts
libs/sdk-backend-tiger/src/backend/workspace/metadata/index.ts

RELATED: BB-2434 Add interface for common attributes API

---

libs/sdk-ui-charts/src/highcharts/chart/ChartTransformation.tsx
libs/sdk-ui-charts/src/highcharts/chart/highChartsCreators.ts
libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chart/test/ChartTransformation.test.tsx
libs/sdk-ui-charts/styles/scss/tooltip.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

FEATURE: ONE-4564 Display tooltips for drill down in charts

---

examples/sdk-examples/Procfile
examples/sdk-examples/package.json
examples/sdk-examples/webpack.config.js

FEATURE: QA-11458 Deploy Live Example SDK8 on Heroku

---

libs/sdk-ui-ext/src/internal/translations/es-ES.json

TRIVIAL: Update localizations

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap

RELATED: RAIL-2093 Add missing properties to widget convertor

---

libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/workspace/index.ts

RELATED: CAT-144 Update WorkspacePermission interface

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx

Also the variable was moved closer to use site
JIRA: RAIL-2649
---
---

RELATED: RAIL-2649 prevent null reference in PluggableBaseChart

---

libs/api-client-bear/src/dashboard/dashboard.ts
libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/filterContext/tests/utils.fixtures.ts
libs/api-model-bear/src/filterContext/tests/utils.test.ts
libs/api-model-bear/src/filterContext/utils.ts
libs/api-model-bear/src/index.ts

Sanitize dependent filters for PDF export JIRA: BB-2563

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

FEATURE: ONE-4636 Disable drilling from geo pushpin attributes

---

examples/sdk-examples/src/components/login/LoginForm.tsx

It previously took over the whole screen in Chrome
---
---

RELATED: RAIL-1815 fix loading style in login

---

libs/sdk-backend-bear/src/backend/workspace/elements/limitingAfmFactory.ts

Fix display form to attribute URI conversion

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/execution/results.ts
libs/sdk-model/src/execution/filter/factory.ts
libs/sdk-model/src/execution/filter/index.ts

RELATED: ONE-4621 - Improve code documentation for attribute element types

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/dashboard.ts

BUGFIX: RAIL-2669 Add missing isLocked flag for the dashboard

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

Custom formatting and week filtering should work properly with Tiger backend.
---
---

Enable additional FFs for tiger

---

examples/sdk-examples/src/examples/rankingFilter/RankingFilterExample.tsx

Fix ranking filter example

---

libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-model/src/execution/filter/factory.ts
libs/sdk-model/src/execution/filter/tests/__snapshots__/factory.test.ts.snap
libs/sdk-model/src/execution/filter/tests/factory.test.ts
libs/sdk-ui-tests/scenarios/pivotTable/experimental.tsx
tools/experimental-workspace/src/recordings/dataSample.ts
tools/experimental-workspace/src/recordings/index.ts

Remove empty attributes in newRankingFilter

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

- update goodstrap to 68.20.4
- remove stop propagation in handleMapClick in GeoChartRenderer
JIRA: ONE-4637
---
---

RELATED: ONE-4637 Update goodstrap 68.20.4 and small fix in GeoChart

---

libs/sdk-ui-geo/api/sdk-ui-geo.api.md
libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/geoChartTooltip.ts
libs/sdk-ui-geo/styles/scss/tooltip.scss

ONE-4630 Tooltip "Click the chart to drill" isn't shown in Geo

---

README.md
docs/contributing.md
docs/decisions.md
docs/sdk-dev.md

This is to make this information more discoverable.
Also, reading the contribution guide added to Getting started
Finally, some typos were fixed.
---
---

RELATED: RAIL-1815 move the testing in my app section to contributing.md

---

docs/contributing.md

RELATED: RAIL-1815 add documentation about rsync flow and parallelism

---

docs/contributing.md
docs/setupIntellij.md

RELATED: RAIL-1815 - Docs for intellij setup

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/ad.ts
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

FEATURE: SD-1078 Keep filter context in explore mode

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/common.ts
libs/sdk-embedding/src/iframe/kd.ts

Include global date filter to Drill to URL post message

---

tools/applink/README.md
tools/applink/src/base/sdkDependencyGraph.ts
tools/applink/src/base/sdkPackages.ts
tools/applink/src/base/test/__snapshots__/sdkDepedencyGraph.test.ts.snap
tools/applink/src/base/test/sdkDepedencyGraph.test.ts
tools/applink/src/base/test/sdkDependencyGraph.fixture.ts
tools/applink/src/base/types.ts
tools/applink/src/devTo/action.ts
tools/applink/src/devTo/dependencyDiscovery.ts
tools/applink/src/devTo/incrementalBuilder.ts
tools/applink/src/devTo/packageBuilder.ts
tools/applink/src/devTo/publisher.ts

-  Builds all required packages on startup to be sure all is green
-  Incremental builds correctly identify depending packages and build them as well
---
---

RELATED: RAIL-1815 - Enhance applink with initial build & proper incremental build capabilities

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/kd.ts

Remove filters from IDrillToUrlStartedDataBody

---

libs/sdk-ui-ext/src/internal/utils/bucketRules.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketRules.test.ts

Hide percentage recommendation for insights with ranking filter

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/RankingFilter/ValueDropdown/ValueDropdown.tsx
libs/sdk-ui-filters/src/RankingFilter/ValueDropdown/utils.ts
libs/sdk-ui-filters/src/RankingFilter/tests/RankingFilterDropdown.test.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/fragments/RankingFilterDropdown.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

Ranking filter accepts value onBlur

---

docs/contributing.md
docs/setupIntellij.md

- fix links to developer guide
- fix name and path in IntelliJ setup
---
---

Improve dev documentation

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts
libs/sdk-ui-charts/styles/scss/tooltip.scss
libs/sdk-ui-ext/src/internal/components/configurationPanels/LineChartBasedConfigurationPanel.tsx

Fix drilling tooltips when datapoints are turned off

---

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts

Implement easy delete method by id.
JIRA: ONE-6423
---
---

ONE-6423: Delete dashboard (Tiger)

---

libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

TRIVIAL: Update translations

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/RankingFilter/ValueDropdown/ValueDropdown.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/RankingFilterDropdown.test.tsx

Accept custom ranking value on input change

---

libs/sdk-backend-bear/src/backend/workspace/metadata/index.ts
libs/sdk-backend-bear/src/utils/api.ts
libs/sdk-backend-mockingbird/src/recordedBackend/metadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/metadata/index.ts
libs/sdk-backend-tiger/src/backend/workspace/metadata/index.ts
libs/sdk-embedding/src/iframe/kd.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/ldm/metadata/attributeDisplayForm/factory.ts
libs/sdk-model/src/ldm/metadata/attributeDisplayForm/index.ts

RELATED: SD-1108 Add new apis to get list of attributeDisplayForms and attributes

---

docs/contributing.md
docs/setupVsCode.md

Add documentation for VS Code setup

---

libs/api-client-bear/src/metadataExt.ts

-  Code to also transfer summary from original dashboard
---
---

RELATED: RAIL-1815 - Sourcing from gooddata-js

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
rush.json

RELATED: RAIL-2460 - Upgrade infrastructure & bump locked dependencies

---

libs/sdk-ui-kit/scripts/build.sh
libs/sdk-ui-kit/styles/scss/Button/_mixins.scss
libs/sdk-ui-kit/styles/scss/Button/_variables.scss
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/main.scss

Fix sdk-ui-kit scss imports

---

libs/sdk-model/src/execution/filter/filterMerge.ts

TRIVIAL: Correct filter merging

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

Fix filling of workspace settings into setupVisualization in InsightView

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/RankingFilterDropdown.test.tsx

Do not reset custom ranking value on blur

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx

Handle undefined value in DynamicSelect

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/RankingFilterDropdown.test.tsx

Close ranking whisper menu on custom value blur

---

docs/contributing.md

RELATED: RAIL-2460 Expand rush change how to

---

libs/sdk-ui-charts/src/highcharts/chart/chartOptionsBuilder.ts

Show single point in series despite dataPoints.visible set to false

---

libs/sdk-embedding/src/internal/filterConvertors.ts
libs/sdk-embedding/src/internal/tests/filterConvertors.test.ts

Validate decimal numbers in ranking filter

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts

RELATED: ONE-4681 Fix hovers on combo charts containing area charts

---

libs/sdk-ui-ext/src/internal/components/configurationPanels/LineChartBasedConfigurationPanel.tsx
libs/sdk-ui-ext/styles/internal/scss/config_panel.scss

RELATED: ONE-4676 Fix SCSS in configuration panel canvas section

---

libs/sdk-ui-kit/styles/scss/Button/_variables.scss

JIRA: ONE-4685
Fixed invalid default value
---
---

RELATED: ONE-4685 Fixes default value of Button text-transform in ui-kit

---

tools/applink/src/devConsole/events.ts
tools/applink/src/devConsole/pipeline/changeDetector.ts
tools/applink/src/devConsole/ui/appLog.ts
tools/applink/src/devConsole/ui/appMenu.ts
tools/applink/src/devConsole/ui/ui.ts
tools/applink/tsconfig.json

-  Fixed bad build of the app (resolveJsonModules messed up dist)
-  Added build-all command
-  Added toggle to pause/resume automatic builds
-  Make logs more colorful & fix shrunk log auto-scroll
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-th …

RELATED: RAIL-1815 - Fixes & small QoL improvements for devConsole

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/scheduledMails.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/scheduledMail.ts

BUGFIX: RAIL-2726 Add unlisted prop to scheduled email

---

README.md

RELATED: RAIL-2711 - Fixup readme links to reflect 8.0.0 release

---

examples/sdk-examples/src/constants/routes.ts

Enable ranking filter live example on platform

---

common/changes/@gooddata/sdk-ui-all/anvuong-sd1107_2020-10-08-11-57.json
libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/ldmFactories/catalog/attributeFactory.ts
libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/fromModel/ldm/catalog/attribute/index.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts

RELATED: SD-1107 Fix geo chart on Master project get error after synchronize LCM

---

libs/api-client-bear/src/metadataExt.ts
libs/api-client-bear/src/tests/metadata.test.ts
libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-bear/src/backend/workspace/attributes/index.ts
libs/sdk-backend-bear/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-bear/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/alerts.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/filterContext.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/scheduledMails.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DateFilterConfigConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/MetaConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationClassConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
tools/catalog-export/src/loaders/bear/bearDataDatasets.ts

Correct IObjectMeta typing according to bear .res specification.
JIRA: RAIL-2401
---
---

RELATED: RAIL-1815 Correct IObjectMeta typings

---

libs/sdk-backend-bear/src/backend/workspace/attributes/index.ts
libs/sdk-backend-bear/src/utils/api.ts

RELATED: SD-1108 Handle exception error if refObj is invalid

---

libs/sdk-ui-filters/styles/scss/attributeFilter.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-pivot/styles/scss/pivotTable.scss
libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/Context.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts

Fix custom font font-face generator; fix withTheme return types

---

common/scripts/ci/run_prerelease_fix.sh

Also add explicit NPM tag for these releases.
---
---

RELATED: RAIL-1815 Add run_prerelease_fix script

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts

Add "dateFormat" to IBaseVisualizationProps and IVisProps interfaces

---

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts

css properties reset; enabling ThemeProvider by ff

---

libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

RELATED: ONE-4645 Custom elements in KD - KPI Dashboards

---

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

Added theme css properties

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/List/MenuList.tsx

JIRA: ONE-4642
Improve the prop types base on the usage in KD
---
---

Improves prop types of Menu items

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/agGridColumnSizing.ts

- refactor of autoresizeAllColumns in agGridColumnSizing
- call getAutoResizedColumns during columns reset
BUGFIX: ONE-4693
---
---

RELATED: ONE-4693 Reset correctly all columns in Pivot Table

---

examples/sdk-examples/src/index.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts

And switch order of style inputs in examples to allow customization
---
---

RELATED: ONE-4712 IE Compatible node removal in theme-provider

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/kd.ts
libs/sdk-embedding/src/internal/index.ts
libs/sdk-embedding/src/internal/tests/validators.test.ts
libs/sdk-embedding/src/internal/validators.ts

- New postmessage API command and event types
JIRA: BB-2436
---
---

Add SetFilterParents post message

---

docs/contributing.md

RELATED: RAIL-1815 add note about developing on Windows

---

docs/contributing.md

TRIVIAL: Update rsync example to reflect tree shaking changes

---

libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

Change zh-Hans text related to ranking filter

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts
libs/sdk-ui-kit/styles/scss/Dialog/_mixins.scss
libs/sdk-ui-kit/styles/scss/mixins.scss

- change handle of keyDown in Dialog
- remove duplicate typo mixins
JIRA: ONE-4640
---
---

Use arrow function in handler in Dialog component

---

common/changes/@gooddata/sdk-ui-all/lhq-sd-1179_2020-10-23-10-23.json
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/src/insightView/dataLoaders.ts
libs/sdk-ui-ext/src/insightView/tests/dataLoaders.test.ts

Load dateformat for InsightView component

---

libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/tests/DateFilterBody.test.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePickerInputField.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/tests/DateRangePicker.test.tsx
libs/sdk-ui-filters/src/DateFilter/constants/Platform.ts
libs/sdk-ui-filters/src/DateFilter/tests/DateFilter.test.tsx
libs/sdk-ui-filters/src/DateFilter/tests/extendedDateFilters_helpers.tsx
libs/sdk-ui-filters/src/DateFilter/utils/Translations/DateFilterTitle.ts
libs/sdk-ui-filters/src/DateFilter/utils/Translations/tests/DateFilterTitle.test.ts
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/Datepicker/tests/Datepicker.test.tsx
libs/sdk-ui-tests/stories/visual-regression/kit/Datepicker/Datepicker.tsx

JIRA: https://jira.intgdc.com/browse/SD-1180
---
---

FEATURE: SD-1180 Handle DatePicker component to display dates in desired format

---

libs/sdk-ui-theme-provider/src/cssProperties.ts

Customization of KPI widget and removal of unwanted shadow
JIRA: ONE-4646 ONE-4744
---
---

RELATED: ONE-4646 KPI customization in theme-provider

---

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePickerError.tsx

JIRA: [SD-1209](https://jira.intgdc.com/browse/SD-1209)
---
---

FEATURE: SD-1209 Allow user to type in DatePicker in the desired format

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

Improve dashboard Zooming feature:
_ Adding the Reset zoom button tooltip
JIRA: SD-1214
---
---

BUGFIX: SD-1214 - Should have a tooltip for Reset zoom icon on KD page

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/styling/index.ts
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/tests/cssProperties.test.ts

Sync structures with changes from MDC-306
kpiDashboards -> dashboards
headline -> kpiWidget
encapsulate headline internal specific keys into `kpi` structure
JIRA: ONE-4746
---
---

RELATED: ONE-4746 Sync structures with changes from MDC-306

---

libs/sdk-ui-kit/styles/scss/dialog.scss

Dropdown styling not overlaps with Dialog

---

libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss
libs/sdk-ui-kit/styles/scss/Button/_variables.scss
libs/sdk-ui-kit/styles/scss/Form/_variables.scss
libs/sdk-ui-kit/styles/scss/Messages/_variables.scss
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/dialog.scss
libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-kit/styles/scss/messages.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

Customizable error color

---

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-filters/styles/scss/measureValueFilter.scss
libs/sdk-ui-kit/styles/scss/Form/_variables.scss
libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-kit/styles/scss/messages.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

Customizable color warning

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-kit/styles/scss/Messages/_variables.scss
libs/sdk-ui-kit/styles/scss/messages.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

Customizable info message

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts

RELATED: RAIL-2736 Implement dashboards functions in sdk-backend-tiger

---

libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss

- Custom color/bgColor on tooltip
JIRA: ONE-4710
---
---

Tooltip customization

---

examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterComponentExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterComponentExample_MDYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_MDYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/index.tsx
examples/sdk-examples/src/examples/internationalDateFormat/datePicker/DatePickerExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/datePicker/DatePickerExample_MDYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/datePicker/index.tsx

RELATED: SD-1173 Add example of changing date format to SDK example

---

libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

If processed data is not valid anymore due to newer execution, stop loading.
JIRA: BB-2492
---
---

RELATED: BB-2492 Stop chart data loading if data is no longer valid

---

libs/sdk-ui-kit/styles/scss/Button/_variables.scss
libs/sdk-ui-kit/styles/scss/Messages/_variables.scss
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/messages.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts

Customizable success color

---

libs/sdk-ui-kit/styles/scss/main.scss
libs/sdk-ui-kit/styles/scss/remove.scss

Remove custom browser border

---

libs/sdk-ui-kit/styles/scss/Dialog/_variables.scss

Fix default dialog border radius

---

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts
libs/sdk-backend-bear/src/convertors/dateFormatting/dateFormatter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/afm/result.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/AfmResultConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/AfmResultConverter.test.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/execution/results.ts

Improve performance of transformation of header items in an AFM execution result

---

libs/sdk-ui-filters/src/DateFilter/ListItem/ListItem.tsx
libs/sdk-ui-filters/styles/scss/components/ListItem.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/CustomizableCheckmark/CustomizableCheckmark.tsx
libs/sdk-ui-kit/src/CustomizableCheckmark/index.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/styles/scss/customizableCheckmark.scss
libs/sdk-ui-kit/styles/scss/list.scss
libs/sdk-ui-kit/styles/scss/main.scss

- Allow the customization of theme primary color
JIRA: ONE-4736
---
---

Replace checkmark svg with customizable component

---

libs/sdk-ui-filters/src/DateFilter/ListItem/ListItem.tsx

- Add `MediaQuery` to check if is mobile device and display the checkmark
JIRA: ONE-4735
---
---

Date Filter customizable checkmark - Display only on mobile device

---

libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
libs/sdk-ui-filters/src/DateFilter/tests/DateFilter.test.tsx
libs/sdk-ui-filters/src/DateFilter/utils/Translations/DateFilterTitle.ts

Handle unsupported date formats for DateFilter

---

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

Fetching theme with invalid identifier catch

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/CustomizableCheckmark/CustomizableCheckmark.tsx
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/colors.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/utils/constants.ts

- Custom theme styling will take priority over whitelabeling one
JIRA: ONE-4771
---
---

Allow styling to override whitelabeling setting

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

- Bump goodstrap verison to adapt navigation for freemium user
---
---

RELATED: SD-1233 Bump version goodstrap for navigation for freemium user

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

RELATED: SD-1261 InsightView can not render and display message error, JS error

---

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts

Fixes handling of the FFs in getTheme

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/AfmFiltersConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/MeasureConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/AfmFilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/AfmFilterConverter.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/toAfmResultSpec.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/filter/index.ts
libs/sdk-model/src/execution/filter/tests/filter.test.ts
libs/sdk-model/src/execution/filter/tests/typeGuards.test.ts
libs/sdk-model/src/execution/measure/index.ts
libs/sdk-model/src/index.ts

RELATED: RAIL-2793 Move the MVF-on-ratio-measure custom logic from AFM backend to SDK

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

There are just simple console logs we can inspect on
staging environment, where the bug is observable
JIRA: ONE-4747
---
---
- …

RELATED: ONE-4747 Add logs to Pivot Table

---

libs/sdk-ui/src/base/localization/bundles/en-US.json

Merge release -> master

---

libs/sdk-ui-charts/styles/scss/headline.scss

RELATED: ONE-4790 Improves theming of Headline empty values

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutRowRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutRowRenderer.tsx

RELATED: RAIL-2753 Fix props propagation in dashboard/fluid layout

---

common/scripts/ci/docker_testcafe.sh
common/scripts/ci/run_testcafe_tests.sh
examples/sdk-examples/scripts/run-testcafe.sh
examples/sdk-examples/test/utils/config.ts
examples/sdk-examples/test/utils/helpers.ts

Add Dockerfile and basic scripts to  run testcafe test on docker

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutColumnRenderer.tsx

- By default, Col is rendered as a div
- Remove unknown html properties from spreaded props
JIRA: RAIL-2753
---
---
-   [ ] …

RELATED: RAIL-2753 Fix properties propagation

---

skel/sdk-skel-tsx/scripts/build.sh

-  was attempting to create `dist` all the time. error during build interfered
with rush incremental build runs
JIRA: RAIL-2752
---
--- …

RELATED: RAIL-2752 - Fix tsx skeleton build script

---

examples/sdk-examples/webpack.config.js

RELATED: WEB-1719 fix initial sdk-examples page title

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/tests/widgetFilters.test.ts
libs/sdk-backend-bear/src/backend/workspace/dashboards/widgetFilters.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/utils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/converters.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/test/__snapshots__/converters.test.ts.snap
libs/sdk-ui-ext/src/internal/dashboardEmbedding/test/converters.test.ts
libs/sdk-ui-ext/styles/internal/scss/variables.scss
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
skel/sdk-skel-tsx/package.json

* fix CSS variable default, so that widget titles are centered
* add simplistic Headline approximation in KpiRenderer so that it looks more like a KPI is used
* fix a bug in widgetFilters in Bear in case ignoredFilters are empty
* propagate filters from dashboard.filterContext to individual widgets
* add missing api-extractor invocations to pacakges that had it in the past and had it removed by mistake
---
---
- …

RELATED: RAIL-2755, RAIL-2819 several DashbaordView improvements

---

libs/sdk-ui-kit/src/Dialog/DialogBase.tsx

RELATED: CAT-336 Extend DialogBase onKeyDown submit disable

---

examples/sdk-examples/src/components/ExampleWithSource.tsx
examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithFilters.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/SimpleDashboardView.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/index.tsx
examples/sdk-examples/src/index.tsx
libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-bear/src/utils/api.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/convertors.ts

* fix widget alerts on anonymous Bear backends
* fix drill targets in InsightRenderer
* improve performance of ExampleWithSource component
* add a few DashbaordView examples in `/hidden/dashboard-view`
---
--- …

RELATED: RAIL-2755 add hidden DashboardView examples, fix bugs

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

- Bump Goodstrap
- expose "disableHelpDropdown" and "onHelpClicked" in Header API
JIRA: CAT-329
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
- …

Bump Goodstrap and update Header

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/styling/theme.ts

Customize title and filterbar border
JIRA: ONE-4802
Missing function call in condition during theming fetch
JIRA: ONE-4791
---
--- …

FEATURE: ONE-3802 Customize title and filterbar border BUGFIX: ONE-4791 missing fce call

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/ad.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/DialogBase.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts
libs/sdk-ui-kit/src/Overlay/Overlay.tsx

Dialog refactoring; new ad post message

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/interfaces/dashboardLayout.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/ColorPaletteContext.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/UserWorkspaceSettingsContext.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/defaultThemeModifier.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/utils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useColorPalette.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardViewLayout.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-ext/styles/internal/scss/layout.scss
libs/sdk-ui-ext/styles/internal/scss/variables.scss

* fix theming issues with backgroundColor, fonts, and Headline styles
* use InsightRenderer to use already loaded insights to improve performance by avoiding duplicate API calls
* introduce contexts for UserWorkspaceConfig and ColorPalette in DashboardView
* remove obsolete Goodstrap styles import in DashboardView
* move locale to the config prop to make work with it easier
---
--- …

RELATED: RAIL-2844 fix theming issues, improve perf

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardLayoutObtainer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx

RELATED: RAIL-2844 inject gd-dashboards-root only in DashboardView

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts

---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [x] `rush change` [was run if …

RELATED: SD-1289 Display tooltip text for Submit button in ConfirmDialogBase

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/utils.ts

* RAIL-2848 - respect widget.properties in DashboardView
* RAIL-2852 - prevent BadRequest (bear enforces pure refs, we cannot send the whole attribute there).
---
--- …

RELATED: RAIL-2848, RAIL-2852 minor fixes in DashboardView

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/HeaderDataMenu.tsx
libs/sdk-ui-kit/src/Header/index.ts

FEATURE: SD-1292 Add submenu component into sdk-ui-kit

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/scripts/build.sh
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

Use Goodstrap icon in workspace picker footer for freemium

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/EmptyDashboardError.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardViewLayout.ts
libs/sdk-ui-ext/src/internal/translations/en-US.json

Show a user friendly message. Also upgrades react-router in examples to avoid several react deprecation warnings.
---
---
-   [ …

RELATED: RAIL-2857 handle empty dashboards in DashboardView 

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx

RELATED: RAIL-2820 respect enableKDZooming feature flag in DashboardView

---

libs/api-client-bear/src/metadataExt.ts

This allows the users without admin privileges to duplicate locked items.
Implemented as opt-in to maintain backwards compatibility.
Also, the saved objects were properly typed.
Port of https://github.com/gooddata/gooddata-js/pull/421
JIRA: RAIL-2860
---
--- …

Add clearLockedFlag option to saveDashboardAs

---

libs/sdk-ui-kit/styles/scss/header.scss

Changing styles of new component and we don't change logic code. So we dont need Code owners (Rail team) to review this PR.
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a …

FEATURE: SD-1292 Adding styles for submenu component

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RepeatSelect/RepeatExecuteOnSelect.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RepeatSelect/RepeatFrequencySelect.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RepeatSelect/RepeatTypeSelect.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RepeatSelect/test/testUtils.ts

Replace goodstrap components in DashboardView with sdk-ui-kit components

---

libs/sdk-ui-charts/styles/scss/tooltip.scss
libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss

JIRA: RAIL-2872, CAT-350
---
--- …

Fix tooltips styling issue that caused warning in KD and theming for bubble component

---

libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss

Edit Bubble component color palette theming

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts

Fix empty-string tag conversion from [""] to []

---

tools/catalog-export/__mocks__/@gooddata/api-client-bear.ts
tools/catalog-export/__mocks__/@gooddata/getAnalyticalDashboards.json
tools/catalog-export/src/base/types.ts
tools/catalog-export/src/loaders/bear/bearAnalyticalDashboard.ts
tools/catalog-export/src/loaders/bear/bearLoad.ts
tools/catalog-export/src/loaders/bear/tests/__snapshots__/bearLoad.test.ts.snap
tools/catalog-export/src/loaders/bear/tests/bearLoad.test.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerLoad.ts
tools/catalog-export/src/transform/tests/__snapshots__/toCatalog.test.ts.snap
tools/catalog-export/src/transform/tests/__snapshots__/toTypescript.test.ts.snap
tools/catalog-export/src/transform/tests/toCatalog.test.ts
tools/catalog-export/src/transform/toCatalog.ts
tools/catalog-export/src/transform/toTypescript.ts

Add support for analyticalDashboards to catalog-export

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

- Change navigation naming in Header component when enableNewNavigationForResponsiveUi feature flag is enabled ( https://github.com/gooddata/gdc-goodstrap/pull/1133 )
- Change KPIs > Dashboards, Analyze > Insights
JIRA: SD-1329
Changes: Update the goodstrap version only. No need review from Code owner
---
--- …

FEATURE: SD-1329 Change KPIs > Dashboards, Analyze > Insights in UI SDK

---

libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/permissions/index.ts
libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts

JIRA: BB-2765
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment) …

Add user access right for user invitation

---

.github/pull_request_template.md
libs/sdk-ui-tests/README.md

Add documentation for testcafe in sdk-ui-tests, add SonarQube check info

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

BUGFIX: BB-2774 Fix tables with horizontal scrollbar

---

libs/sdk-ui-kit/styles/scss/header.scss

Just change the css of new component dont need component owner to review it 
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning …

FEATURE: SD-1363 Update HeaderDataMenu styles

---

libs/sdk-ui-kit/scripts/build.sh

Previously, the output was copied to ./esm/assets/assets/...
JIRA: RAIL-2752
---
--- …

RELATED: RAIL-2752 fix sdk-ui-kit build

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/index.ts

-  Couple of forgotten functions; already marked as @public but not included in the barrel
---
--- …

RELATED: RAIL-2905 - Expose model functions on public API

---

libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/permissions/index.ts
libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Header/generateHeaderAccountMenuItems.ts
libs/sdk-ui-kit/src/Header/generateHeaderHelpMenuItems.ts
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/index.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderAccountMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderHelpMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
libs/sdk-ui-kit/src/Header/tests/mock.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/utils/featureFlags.ts
libs/sdk-ui-kit/src/utils/tests/featureFlags.test.ts

---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [x] `rush change` [was run if …

BUGFIX: SD-1300 Add generating header data function and hide data tab for explorer role

---

libs/sdk-backend-tiger/src/backend/user/settings.ts

Add enableNewNavigationForResponsiveUi FF to tiger setting mock

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

Relocate enableNewNavigationForResponsiveUi FF to tiger setting mock

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/WorkspacePickerHomeFooter.tsx
libs/sdk-ui-kit/src/Header/tests/WorkspacePickerHomeFooter.test.tsx

Add onClick prop to WorkspacePickerHomeFooter

---

libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/HeaderHelp.tsx
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
libs/sdk-ui-kit/src/Header/tests/mock.ts
libs/sdk-ui-kit/styles/scss/header.scss

Add HeaderHelp component from goodstrap

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

Chane the url of modeler dont conflict any other component so we can merge it to use it (this function is not used) to AD and KD
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if …

RELATED: SD-1300 Change modeler url

---

libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap

RELATED: RAIL-2905 - Fix invariant error when converting legacy dashboard drill

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

Add flag enableMultipleDates to settings

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderAccountMenuItems.ts
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderAccountMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

Adjust header component for tiger

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/styles/scss/header.scss

Adjust header "analyze" tab, data link, and help button link

---

libs/sdk-backend-bear/src/backend/workspace/execution/executionResult.ts
libs/sdk-backend-bear/src/convertors/dateFormatting/dateFormatter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/afm/result.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/AfmResultConverter.test.ts
libs/sdk-ui-pivot/src/CorePivotTable.tsx

Fix formatting with multiple dates and fix measure column header classes

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketConfig.test.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketHelper.test.ts

Change of date dataset structure from dateDataset to dateDateseRef in buckets

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts

Add support for disabling dashboard header tab

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/ad.ts
libs/sdk-embedding/src/iframe/common.ts
libs/sdk-embedding/src/iframe/kd.ts

RELATED: RAIL-2956 fix typos in sdk-embedding

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

- Revert Insights > Analyze
JIRA: SD-1432
Update Goodstrap's version only. 
No need the review from code owner 
---
---
-   [x] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is …

Update goodstrap in sdk-ui-kit

---

libs/sdk-backend-tiger/src/backend/index.ts

The validation check is used by AD/KD for every incoming control message. Secure, insecure, drill enabling, etc. Without actual whitelist implementation all of these functionalities would stop working when apps are executed against Tiger backend. The default real bear backend implementation returns true when whitelist is disabled on server via rollout feature flag, i.e., returning true by Tiger backend API mirrors this behavior.
JIRA: BB-2795
---
---
-   [x] commit messages adhere to the [commit message …

Consider all Tiger whitelist requests as valid

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts

RELATED: RAIL-2956 add missing export

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardExport.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithDrilling.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithFilters.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithMergedFilters.tsx

Add links between the different examples where it makes sense
JIRA: RAIL-2960
---
--- …

RELATED: RAIL-2960 Link DashboardView examples together

---

libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx

Avoid undefined insight prop

---

examples/sdk-examples/src/index.tsx
libs/sdk-ui-ext/scripts/build.sh
libs/sdk-ui-ext/styles/scss/main.scss

Also fix build script in sdk-ui-ext
JIRA: RAIL-2956
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in …

RELATED: RAIL-2956 expose DashboardView styles properly

---

common/changes/@gooddata/sdk-ui-all/dho-rail-2956-changelog_2021-03-01-09-36.json

RELATED: RAIL-2956 Add changelog entry for DashboardView

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-bear/src/backend/workspace/insights/insightReferences.ts
libs/sdk-backend-bear/tsconfig.json
libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts
libs/sdk-backend-mockingbird/src/recordedBackend/insights.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/types/refTypeMapping.ts
libs/sdk-backend-tiger/tsconfig.json
libs/sdk-model/src/execution/filter/filterMerge.ts
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/tableFacadeInitializer.ts
libs/sdk-ui-tests/stories/visual-regression/visualizations/insightStories.tsx
libs/sdk-ui-tests/stories/visual-regression/visualizations/scenarioStories.tsx
libs/sdk-ui/src/base/results/internal/test/dataAccessDigest.test.ts
tools/applink/src/base/targetDiscovery.ts
tools/applink/src/devConsole/pipeline/buildScheduler.ts
tools/applink/src/devConsole/pipeline/changeDetector.ts
tools/applink/src/devConsole/pipeline/packageBuilder.ts
tools/catalog-export/src/loaders/tiger/tigerDateDatasets.ts

RELATED: FET-533, FET-608 - Bump locked dependencies & pivot table fix

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithCustomChartsSrc.tsx

Make custom examples more copy-paste ready

---

libs/sdk-ui-ext/styles/internal/scss/config_panel.scss
libs/sdk-ui-ext/styles/internal/scss/kpi.scss
libs/sdk-ui-ext/styles/internal/scss/scheduled_mail_recipients.scss
libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss
libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss
libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss
libs/sdk-ui-kit/styles/scss/Button/_variables.scss
libs/sdk-ui-kit/styles/scss/Dialog/_variables.scss
libs/sdk-ui-kit/styles/scss/Form/_mixins.scss
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/dialog.scss
libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui-kit/styles/scss/list.scss
libs/sdk-ui-kit/styles/scss/overlay.scss
libs/sdk-ui-kit/styles/scss/syntaxHighlightingInput.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

Complementary palette in basic components

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

There is sometimes exactly 2px discrepancy between the height of
gd-table-dashboard-wrapper (set to 100%)
and gd-table-component that gets its height from its parent's maxHeight.
These 2px create a positive feedback loop which causes the table to
grow in height in 2px increments until it reaches its full height.
To fix this, changes to desiredHeight smaller than 2 pixels
are ignored which breaks the loop.
This is as a symptomatic fix as they come, but I was unable to find
the reason why it is always exactly 2 pixels and what causes them.
This fix is located in CorePivotTable so that all the magic
with desired height is collocated to one place.
JIRA: RAIL-2993
--- …

RELATED: RAIL-2993 prevent pivot table growing in height on its own

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx

_ Move the zooming button in Geo chart to the top right position
---
--- …

RELATED: SD-1452 - Moving the Zooming button in Geo Chart to the top right position

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithCustomChartsSrc.tsx

Add text-overflow: ellipsis for custom kpi in examples

---

libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/VisualizationObjectConverter.ts

RELATED: RAIL-2697 - Implement tiger backend services

---

libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss
libs/sdk-ui-filters/styles/scss/components/DateFilterButton.scss
libs/sdk-ui-filters/styles/scss/components/DateFilterFormWrapper.scss
libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-filters/styles/scss/components/ListItem.scss
libs/sdk-ui-filters/styles/scss/components/SelectMenu.scss
libs/sdk-ui-kit/styles/scss/datepicker.scss
libs/sdk-ui-kit/styles/scss/dropdown.scss
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui-kit/styles/scss/tabs.scss

- introduce complementary palette to date and attribute filters
JIRA: BB-2818
---
--- …

Complementary palette in filters

---

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts

RAIL-2697: Add support for dashboard update

---

libs/sdk-backend-tiger/src/auth.ts
libs/sdk-backend-tiger/src/backend/index.ts

Add logout functionality

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/dashboard/GdcDashboardLayout.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/layout.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DashboardConverter.test.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout.ts
libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutItemRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/constants.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/__snapshots__/sizing.test.ts.snap
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/sizing.test.ts

UI resizes height of widget according data

---

.github/CODEOWNERS

New localization code owner

---

libs/sdk-backend-mockingbird/src/recordedBackend/attributes.ts

Add support for bulk load of attributes and displayForms in mockingbird

---

README.md
examples/sdk-examples/README.md
libs/api-client-bear/README.md
libs/api-client-tiger/README.md
libs/api-model-bear/README.md
libs/sdk-backend-base/README.md
libs/sdk-backend-bear/README.md
libs/sdk-backend-mockingbird/README.md
libs/sdk-backend-spi/README.md
libs/sdk-backend-tiger/README.md
libs/sdk-embedding/README.md
libs/sdk-model/README.md
libs/sdk-ui-all/README.md
libs/sdk-ui-charts/README.md
libs/sdk-ui-ext/README.md
libs/sdk-ui-filters/README.md
libs/sdk-ui-geo/README.md
libs/sdk-ui-kit/README.md
libs/sdk-ui-pivot/README.md
libs/sdk-ui-tests/README.md
libs/sdk-ui-vis-commons/README.md
libs/sdk-ui/README.md
libs/util/README.md
tools/applink/README.md
tools/catalog-export/README.md
tools/experimental-workspace/README.md
tools/live-examples-workspace/README.md
tools/mock-handling/README.md
tools/reference-workspace-mgmt/README.md
tools/reference-workspace/README.md

RELATED: LR-382 Update README copyright years

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/scripts/generate.js
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/dateGranularityConversions.ts

Tiger APIs went through a major refactor, the client had to be
regenerated from the OAPI specs.
GitLab: gdc-nas#1043
---
--- …

TIGER: Upgrade client to latest OAPI spec

---

libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/cssProperty.ts
libs/sdk-ui-theme-provider/src/derivedColors.ts
libs/sdk-ui-theme-provider/src/tests/__snapshots__/derivedColors.test.ts.snap
libs/sdk-ui-theme-provider/src/tests/complementaryPalette.test.ts
libs/sdk-ui-theme-provider/src/tests/cssProperties.test.ts
libs/sdk-ui-theme-provider/src/tests/derivedColors.test.ts

- derived colors are rendered based on the complementary palette if provided
JIRA: BB-2814
---
--- …

Derived colors for dark themes

---

examples/sdk-examples/README.md
libs/api-client-bear/README.md
libs/api-client-tiger/README.md
libs/api-model-bear/README.md
libs/sdk-backend-base/README.md
libs/sdk-backend-bear/README.md
libs/sdk-backend-mockingbird/README.md
libs/sdk-backend-spi/README.md
libs/sdk-backend-tiger/README.md
libs/sdk-embedding/README.md
libs/sdk-model/README.md
libs/sdk-ui-all/README.md
libs/sdk-ui-charts/README.md
libs/sdk-ui-ext/README.md
libs/sdk-ui-filters/README.md
libs/sdk-ui-geo/README.md
libs/sdk-ui-kit/README.md
libs/sdk-ui-pivot/README.md
libs/sdk-ui-tests/README.md
libs/sdk-ui-theme-provider/README.md
libs/sdk-ui-vis-commons/README.md
libs/sdk-ui/README.md
libs/util/README.md
tools/applink/README.md
tools/catalog-export/README.md
tools/experimental-workspace/README.md
tools/live-examples-workspace/README.md
tools/mock-handling/README.md
tools/reference-workspace-mgmt/README.md
tools/reference-workspace/README.md

We need to use full URL so that the links also work on npm package pages.
Also add README to theme provider.
JIRA: LR-382
---
--- …

RELATED: LR-382 Fix links to LICENSEs in READMEs

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/areaChart/areaConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bubbleChart/bubbleConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/columnChart/columnConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/comboChart/comboConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/lineChart/lineConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/scatterPlot/scatterConfiguration.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx
libs/sdk-ui-theme-provider/src/complementaryPalette.ts
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/derivedColors.ts
libs/sdk-ui-theme-provider/src/tests/__snapshots__/complementaryPalette.test.ts.snap
libs/sdk-ui-theme-provider/src/tests/complementaryPalette.test.ts
libs/sdk-ui-theme-provider/src/tests/cssProperties.test.ts
libs/sdk-ui-theme-provider/src/tests/derivedColors.test.ts
libs/sdk-ui-vis-commons/src/legend/LegendItem.tsx

Renamed complementary palette keys prefix

---

libs/sdk-backend-tiger/src/auth.ts

TIGER: Fix call which is not using OAPI generated client

---

libs/sdk-ui-ext/styles/internal/scss/scheduled_mail.scss
libs/sdk-ui-ext/styles/internal/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/styles/scss/datepicker.scss

Fix complementary colors in datepicker

---

libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/prepareTheme.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/__snapshots__/prepareTheme.test.ts.snap
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/prepareTheme.test.ts

Fix complementary palette not generated

---

libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
libs/sdk-backend-tiger/src/auth.ts
libs/sdk-backend-tiger/src/backend/user/index.ts
libs/sdk-backend-tiger/src/backend/workspace/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts
libs/sdk-backend-tiger/src/index.ts
libs/sdk-backend-tiger/src/utils/api.ts

JIRA: RAIL-3039
JIRA: RAIL-3016
---
---
-   [x] …

Extend Tiger user and workspace functionality

---

libs/sdk-ui-charts/styles/scss/headline.scss
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-ext/styles/internal/scss/kpi.scss
libs/sdk-ui-kit/styles/scss/button.scss

- add complementary palette to KPI
- fix style issues in headline
JIRA: BB-2823
---
--- …

Complementary palette in KPI

---

libs/sdk-backend-base/src/customBackend/index.ts
libs/sdk-backend-base/src/decoratedBackend/index.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-bear/src/backend/organization/index.ts
libs/sdk-backend-mockingbird/src/compositeBackend/index.ts
libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/index.ts
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/organization/index.ts
libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-backend-tiger/src/backend/organization/index.ts
libs/sdk-backend-tiger/src/backend/organization/securitySettings.ts
libs/sdk-backend-tiger/src/index.ts
libs/sdk-backend-tiger/src/utils/api.ts

Remove out of place function in tiger that was implementing this
JIRA: RAIL-3039
---
--- …

RELATED: RAIL-3039 add SPIs for organization and organization descriptor

---

libs/sdk-backend-tiger/src/backend/workspaces/index.ts

- This is default behavior of gdc-bear
- Unify the tiger behavior with it
JIRA: RAIL-3036
---
--- …

Sort workspaces alphabetically in the tiger

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts

Fix header menu item naming

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts

Revert AD header naming to old naming

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/client.ts
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/layout.ts
libs/api-client-tiger/src/organizationUtilities.ts
libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/toolkit/paging.ts
libs/sdk-backend-tiger/src/backend/workspaces/index.ts

- Expose declarativeLayout api
- Fix workspaces search
- Fix workspaces pagination
JIRA: RAIL-3015, RAIL-2966, RAIL-3037
---
--- …

Tiger client - expose declarativeLayout api, fix workspaces fetching

---

docs/contributing.md

-  OSX filesystem & changing file name case does not play well
JIRA: RAIL-2999
---
--- …

TRIVIAL: Clarify caveats of the `rsync` method

---

libs/sdk-backend-bear/src/convertors/fromBackend/UsersConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/user/index.ts
libs/sdk-backend-spi/src/workspace/users/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RecipientsSelect/test/RecipientsSelectRenderer.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/utils/scheduledMailRecipients.ts

- Tiger backend supports only fullName.
- Added otional fullName prop to avoid assigning fullName as a user firstName in tiger.
JIRA: RAIL-3068
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-co …

Add support for fullName to sdk-backend-spi

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/sortItemsHelpers.test.ts
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts

Add displayFormRef to attribute filter used in reference point loop

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartColoring/measure.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartColoring/test/measure.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/bulletChartColoring.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/test/bulletChart.test.ts
libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
libs/sdk-ui-vis-commons/src/index.ts

Derived colors in HighCharts fix

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/KpiAlertDialog/KpiAlertDialogDateRange.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/Attachment.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/test/Attachment.test.tsx
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-ext/styles/internal/scss/kpi_alert_dialog.scss
libs/sdk-ui-ext/styles/internal/scss/scheduled_mail.scss
libs/sdk-ui-ext/styles/internal/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/styles/scss/Bubble/_variables.scss
libs/sdk-ui-kit/styles/scss/datepicker.scss
libs/sdk-ui-kit/styles/scss/dropdown.scss
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui-kit/styles/scss/list.scss
libs/sdk-ui-kit/styles/scss/loadingDots.scss
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/tests/cssProperties.test.ts

- replace some ::before icons with Icon component
- update shadow color
- update KPI styles
- style mobile vertical menu, lists and dropdowns
JIRA: BB-2819
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appr …

Complementary palette in KD view mode

---

common/config/rush/browser-approved-packages.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/package.json
libs/api-model-bear/package.json
libs/sdk-backend-base/package.json
libs/sdk-backend-bear/package.json
libs/sdk-backend-mockingbird/package.json
libs/sdk-backend-spi/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-embedding/package.json
libs/sdk-model/package.json
libs/sdk-ui-all/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-theme-provider/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json
libs/util/package.json
skel/sdk-skel-ts/package.json
skel/sdk-skel-tsx/package.json

-  Bump locked dependencies
-  Add api-documenter to all packages and skels
---
--- …

RELATED: RAIL-3086 - Add api-documenter

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts

Revert changes that disabeled KD tab in header

---

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

As tiger cannot sort by "updated", fall back to sorting by "title"
in a future-compatible way.
JIRA: RAIL-3087
---
--- …

RELATED: RAIL-3087 fallback to title ordering in tiger

---

libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

Needed for verification as Tiger uses only hardcoded FFs
---
--- …

Turn on FF enableKDWidgetCustomHeight for Tiger

---

libs/sdk-backend-tiger/src/backend/user/settings.ts

Turn on FF enableKDWidgetCustomHeight for Tiger on user level

---

libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/prepareTheme.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/prepareTheme.test.ts

and new table and chart theme properties
JIRA: BB-2820
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or …

Added ability to disable complementary palette

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

Set feature flags to allow AD embedding in KD

---

libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

This makes tiger aligned with bear defaults for these flags.
JIRA: RAIL-3130
---
--- …

RELATED: RAIL-3130 Enable pivot table flags on tiger

---

libs/sdk-ui-ext/styles/internal/scss/kpi_alert_dialog.scss
libs/sdk-ui-kit/styles/scss/button.scss

Fix link colors

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

-  All hardcoded settings, locale, separators are in one place and are used
from both workspace settings & user settings
JIRA: RAIL-3096
---
--- …

RELATED: RAIL-3096 - Deduplicate hardcoded settings

---

libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/bulletChartColoring.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/test/bulletChart.test.ts
libs/sdk-ui-theme-provider/src/complementaryPalette.ts
libs/sdk-ui-theme-provider/src/tests/__snapshots__/complementaryPalette.test.ts.snap
libs/sdk-ui-theme-provider/src/tests/complementaryPalette.test.ts

in dark-based themes
JIRA: BB-2850
---
---
-   [ …

Bullet chart target measure color fix

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemBase.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContentWrapper.tsx

RELATED: ONE-4937 Add client height measurement to dashboard embedding 

---

libs/sdk-ui-charts/styles/scss/headline.scss
libs/sdk-ui-ext/styles/internal/scss/kpi.scss

Fix dash color in KPI & Headline

---

libs/sdk-ui-theme-provider/src/ThemeProvider/prepareTheme.ts

when no theme is provided
JIRA: BB-2820
---
--- …

Disable complementary palette fix

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

There is no reason not to enable this on tiger.
JIRA: RAIL-3154
---
--- …

RELATED: RAIL-3154 Set enableSectionHeaders to true in tiger

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/styling/index.ts
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-pivot/api/sdk-ui-pivot.api.md
libs/sdk-ui-pivot/package.json
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/cell/cellUtils.ts
libs/sdk-ui-pivot/src/impl/cell/tests/tableCell.test.ts
libs/sdk-ui-pivot/src/impl/data/RowLoadingElement.tsx
libs/sdk-ui-pivot/src/impl/data/tests/RowLoadingElement.test.tsx
libs/sdk-ui-pivot/src/publicTypes.ts
libs/sdk-ui-pivot/styles/scss/pivotTable.scss
libs/sdk-ui-theme-provider/src/ThemeProvider/prepareTheme.ts

Pivot table theming

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

Fix default ui settings for tiger

---

libs/sdk-backend-base/src/customBackend/workspace.ts
libs/sdk-backend-base/src/decoratedBackend/index.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-bear/src/backend/workspace/index.ts
libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/index.ts
libs/sdk-backend-tiger/src/backend/workspace/index.ts
libs/sdk-backend-tiger/src/backend/workspaces/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts

Add support for workspace parenting in sdk-backend-spi

---

libs/sdk-backend-mockingbird/src/recordedBackend/index.ts

Update mockingbird capabilities to support csv uploader

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Icon/Icon.tsx
libs/sdk-ui-kit/src/Icon/iconNames.ts
libs/sdk-ui-kit/src/Icon/icons/BurgerMenu.tsx
libs/sdk-ui-kit/src/Icon/icons/Rows.tsx
libs/sdk-ui-kit/src/Icon/icons/index.ts
libs/sdk-ui-kit/src/Icon/typings.ts
libs/sdk-ui-pivot/src/impl/structure/headers/AggregationsMenu.tsx
libs/sdk-ui-pivot/src/impl/structure/headers/AggregationsSubMenu.tsx
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

aggregation menu icons, grid color
JIRA: BB-2816
---
--- …

Pivot table theming fixes

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts

Tiger - add default drill feature flags to enable drilling in KD.

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts

- Load only necessary catalog item types
- Fix tags propagation
JIRA: RAIL-3168
---
--- …

Tiger - load correct catalog item types

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/gd-tiger-model/VisualizationObjectModelV1.ts
libs/api-client-tiger/src/gd-tiger-model/VisualizationObjectModelV2.ts

Now they reflect reality more
JIRA: RAIL-3176
---
--- …

RELATED: RAIL-3176 Fix tiger types

---

libs/sdk-ui-charts/src/charts/_base/withChart.tsx
libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/areaChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/barChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bubbleChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/bulletChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/columnChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/comboChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/donutChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/funnelChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/heatmap.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/lineChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/pieChart.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/scatterPlot.test.tsx.snap
libs/sdk-ui-tests/tests/api-regression/charts/__snapshots__/treemap.test.tsx.snap

InsightView support for themes

---

libs/sdk-backend-tiger/src/backend/index.ts

Tiger: intercept backend errors to console

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Feature is not done yet, so it needs to be turned off for Tiger users
---
--- …

Turn off developer FF before Tiger release

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts

RAIL-3180: correctly choose primary label in catalog

---

libs/sdk-ui-kit/styles/scss/list.scss

Fix missing goodstrap icons in sdk-ui-kit

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-geo/styles/scss/tooltip.scss
libs/sdk-ui/src/base/react/ErrorComponent.tsx
libs/sdk-ui/src/base/react/LoadingComponent.tsx

- wrap InsightRenderer
- style Loading and Error component
- update geochart styles
JIRA: BB-2889
---
--- …

Fix comp palette in InsightView and DashboardView

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/dimensions.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/dimensions.fixture.ts

Sync tiger API changes

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/DateDatasets/dateDatasets.ts

Fix date dataset typings to support extended types

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Disable drills for tiger dashboards

---

libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts

color-scheme CSS property based on the theme

---

libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-geo/styles/scss/tooltip.scss

Fix comp colors in InsightView and DashboardView

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/constants.ts
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerCatalog.ts
tools/catalog-export/src/loaders/tiger/tigerInsights.ts

filter out JSON API entities with broken relations

---

libs/sdk-ui-ext/styles/internal/scss/scheduled_mail_recipients.scss

For some insane reason the previous version made CRA builds fail.
This removes some duplicities and works in CRA.
JIRA: RAIL-3191
---
--- …

RELATED: RAIL-3191 Simplify CSS

---

libs/sdk-ui-charts/styles/scss/tooltip.scss
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
libs/sdk-ui-geo/api/sdk-ui-geo.api.md
libs/sdk-ui-geo/package.json
libs/sdk-ui-geo/src/GeoPushpinChart.tsx
libs/sdk-ui-geo/src/core/CoreGeoChart.tsx
libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
libs/sdk-ui-geo/styles/scss/main.scss
libs/sdk-ui-geo/styles/scss/tooltip.scss
libs/sdk-ui-tests/tests/api-regression/geo/__snapshots__/geoPushpin.test.tsx.snap

- inject theme to GeoChart
- update necessary colors
JIRA: BB-2842
---
--- …

Fix comp colors in GeoChart

---

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/tests/widgetFilters.test.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/widgetFilters.ts
libs/sdk-backend-tiger/src/utils/api.ts
libs/sdk-ui-ext/src/dataLoaders/DashboardAlertsDataLoader.ts
libs/sdk-ui-ext/src/dataLoaders/test/DashboardAlertsDataLoader.test.ts

* prevent call to unsupported endpoint
* implement missing necessary endpoint
* improve error messages
JIRA: RAIL-3237
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think …

RELATED: RAIL-3237 Fix DashboardView on tiger

---

libs/sdk-ui-kit/styles/scss/syntaxHighlightingInput.scss

Fix syntax highlighting input color

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts

- Enable it in Tiger hardcoded FF
---
---
-   [ …

Add ADCatalogGroupsExpanded FF to sdk-backend-spi

---

common/changes/@gooddata/sdk-ui-all/dho-rail-2775-tiger-changelog_2021-04-13-13-20.json
common/changes/@gooddata/sdk-ui-all/ine-one-4890_2021-02-25-16-35.json
common/changes/@gooddata/sdk-ui-all/release_2021-04-13-11-56.json

RELATED: RAIL-2775 add and review changelog entries

---

NOTICE
libs/api-client-bear/README.md
libs/api-client-tiger/README.md
libs/api-model-bear/README.md
libs/sdk-backend-base/README.md
libs/sdk-backend-bear/README.md
libs/sdk-backend-mockingbird/README.md
libs/sdk-backend-spi/README.md
libs/sdk-backend-tiger/README.md
libs/sdk-embedding/README.md
libs/sdk-model/README.md
libs/sdk-ui-charts/.gitignore
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/.gitignore
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/README.md
libs/sdk-ui-geo/README.md
libs/sdk-ui-kit/README.md
libs/sdk-ui-pivot/README.md
libs/sdk-ui-theme-provider/README.md
libs/sdk-ui-vis-commons/README.md
libs/sdk-ui/README.md
libs/util/README.md
tools/applink/README.md
tools/catalog-export/README.md
tools/experimental-workspace/README.md
tools/live-examples-workspace/README.md
tools/mock-handling/README.md
tools/reference-workspace-mgmt/README.md
tools/reference-workspace/README.md

As NOTICE file must be included in dist, we copy it just before publish.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in …

RELATED: LR-453 Update copyright years and NOTICE file, include NOTICE in dist

---

libs/sdk-ui-ext/src/internal/components/configurationControls/DropdownControl.tsx
libs/sdk-ui-ext/src/internal/components/configurationControls/tests/DropdownControl.test.tsx

Forward icon prop in DropdownControl to list item

---

common/changes/@gooddata/sdk-ui-all/RAIL-3263_2021-04-14-11-02.json
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/builder/interfaces.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/builder/layout.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/builder/section.ts

- Add uri and identifier props in tiger convertors to the widget (as we require them here, to ensure that predicates are working for uncontrolled user inputs (we have no guarantee that user is using uriRef/idRef): https://github.com/gooddata/gooddata-ui-sdk/blob/master/libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx#L85 )
- Limit toIndex in moveSection/moveItem methods in dashboard layout builder to prevent non-existing section reference
JIRA: RAIL-3263
---
--- …

Tiger: fix layout customizations

---

libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

Fix theme passing in ThemeProvider

---

libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-ui-all/.gitignore
libs/sdk-ui-all/package.json

Also make sure the NOTICE file is included in sdk-ui-all as it also has highcharts in them
---
--- …

TRIVIAL: fix SonarQube issue

---

libs/sdk-ui-pivot/package.json
libs/sdk-ui-pivot/src/CorePivotTable.tsx

Add pivot table warning if its wrapper has no or small height

---

examples/sdk-examples/src/examples/theming/ThemedComponentsExample.tsx

Show raw theme in theming example

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json

This will hopefully fix the examples deployment
JIRA: RAIL-2775
---
--- …

RELATED: RAIL-2775 Upgrade heroku to latest version

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json

RELATED: RAIL-2775 Pin heroku to the last version known to work

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml

Pin heroku dependencies to versions known to work

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/KpiAlertDialog/KpiAlertDialogDateRange.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/Attachment.tsx
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-ext/styles/internal/scss/kpi_alert_dialog.scss
libs/sdk-ui-ext/styles/internal/scss/scheduled_mail.scss
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/WorkspacePickerHomeFooter.tsx
libs/sdk-ui-kit/styles/scss/header.scss

- remove unnecessary icon wrappers
- use width and height props
JIRA: BB-2900
---
--- …

Use Icon props correctly

---

libs/sdk-ui-kit/styles/scss/header.scss

Fix water mark styling

---

libs/sdk-ui-charts/src/charts/headline/internal/Headline.tsx
libs/sdk-ui-charts/src/charts/headline/internal/utils/calculateCustomHeight.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemHeadlineContainer.tsx

Headline content is overlapped its border

---

examples/sdk-examples/src/App.tsx

Fix examples on older MacOs/Safari versions

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-kit/src/List/LegacyList.tsx

* 1 bug in LegacyList (synced with goodstrap version)
* 1 critical code smell - moved the default case at the end
---
--- …

TRIVIAL: Fix sonar-reported issues

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

This is the default on bear, no reason not to enable it on tiger, too.
JIRA: RAIL-3286
---
--- …

RELATED: RAIL-3286 Enable custom color picker on tiger

---

libs/sdk-ui-charts/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-vis-commons/package.json
skel/sdk-skel-tsx/package.json

Fix clean package.json scripts

---

common/changes/@gooddata/sdk-ui-all/RAIL-2041_2021-04-22-16-35.json
examples/sdk-examples/src/examples/execution/ExecuteAttributeValuesExample.tsx
examples/sdk-examples/src/examples/execution/ExecuteExample.tsx
examples/sdk-examples/src/examples/execution/ExecuteWithCustomVisualizationExample.tsx
examples/sdk-examples/src/examples/execution/ExecuteWithSlicesExample.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/execution/Execute.tsx
libs/sdk-ui/src/execution/RawExecute.tsx
libs/sdk-ui/src/execution/index.ts
libs/sdk-ui/src/execution/interfaces.ts
libs/sdk-ui/src/execution/tests/Execute.test.tsx
libs/sdk-ui/src/execution/tests/RawExecute.test.tsx

- Add support for error & loading components
- Update examples
JIRA: RAIL-2041
---
--- …

RELATED: RAIL 2041 Make Execute component more convenient to use

---

libs/sdk-ui-charts/styles/scss/headline.scss
libs/sdk-ui-vis-commons/styles/scss/headlinePagination.scss

- Move styles for pagination to new file.
JIRA: ONE-4980
---
--- …

Headline Pagination takes correct styles.

---

libs/sdk-ui-kit/styles/scss/header.scss

center watermark button title

---

common/changes/@gooddata/sdk-ui-all/map-rail-2929-tooltip-visibility-configuration_2021-04-27-14-49.json
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-charts/src/interfaces/index.ts

Description of changes.
- introduce ITooltipConfig interface with enabled property
- introduce tooltip configuration into chart logic
---
--- …

RAIL-2929 Configure tooltip visibility

---

libs/sdk-ui-ext/src/internal/translations/ja-JP.json

Fix typo in ja-JP localization

---

libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/ListItemTooltip/ListItemTooltip.tsx

Changed position of tooltip bubble

---

libs/sdk-ui/src/base/localization/bundles/en-US.json

Fix ICU plural group in EN

---

examples/sdk-examples/src/examples/dateFilter/DateFilterComponentExample.tsx
examples/sdk-examples/src/examples/dateFilter/DateFilterWithColumnChartExample.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterComponentExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterComponentExample_MDYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_MDYY.tsx
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/RelativePresetFilterItems.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/tests/RelativeDateFilterForm.test.tsx
libs/sdk-ui-filters/src/DateFilter/constants/config.tsx
libs/sdk-ui-filters/src/DateFilter/index.ts
libs/sdk-ui-filters/src/DateFilter/interfaces/index.ts
libs/sdk-ui-filters/src/DateFilter/tests/DateFilter.test.tsx
libs/sdk-ui-filters/src/DateFilter/tests/extendedDateFilters_helpers.tsx
libs/sdk-ui-filters/src/DateFilter/utils/OptionUtils.ts
libs/sdk-ui-filters/src/DateFilter/utils/Translations/tests/DateFilterTitle.test.ts
libs/sdk-ui-filters/src/DateFilter/utils/tests/AFMConversions.test.ts
libs/sdk-ui-filters/src/DateFilter/utils/tests/PeriodExlusion.test.ts
libs/sdk-ui-filters/src/DateFilter/validation/tests/OptionValidation.test.ts
libs/sdk-ui-filters/src/index.ts

- marked availableGranularities for filterForm as optional
JIRA: RAIL-1842
---
--- …

FilterForm availableGranularities optional

---

libs/sdk-ui-tests/README.md
libs/sdk-ui-tests/backstop/run-backstop.sh
libs/sdk-ui-tests/package.json
libs/sdk-ui-tests/stories/serve-storybook.sh

RELATED: FET-726 - Improve backstop experience

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
examples/sdk-examples/src/App.tsx
examples/sdk-examples/src/index.tsx

FET-677: Remove goodstrap from examples

---

examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/chartResponsiveness/BarChartResponsiveExample.tsx
examples/sdk-examples/src/examples/chartResponsiveness/HeadlineResponsiveExample.tsx
examples/sdk-examples/src/examples/chartResponsiveness/index.tsx

- Show few examples for Headline and Visual Components (bar chart)
JIRA: ONE-5005
---
--- …

Add chart responsiveness to Live Examples

---

libs/sdk-ui-kit/src/ResponsiveText/ResponsiveText.tsx

Better handling of props changes during component lifetime
JIRA: XSH-429
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in …

Adapt fix of ResponsiveText from master to fix version

---

common/scripts/build-docs.sh
libs/api-client-tiger/src/index.ts
libs/api-model-bear/src/index.ts
libs/sdk-backend-base/src/index.ts
libs/sdk-backend-bear/src/index.ts
libs/sdk-backend-mockingbird/src/index.ts
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-tiger/src/index.ts
libs/sdk-embedding/src/index.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-all/src/index.ts
libs/sdk-ui-charts/src/index.ts
libs/sdk-ui-ext/src/index.ts
libs/sdk-ui-filters/src/index.ts
libs/sdk-ui-geo/src/index.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-pivot/src/index.ts
libs/sdk-ui-theme-provider/src/index.ts
libs/sdk-ui-vis-commons/src/index.ts
libs/sdk-ui/src/index.ts

Adjust build-docs script to sanitize packages at the beginning

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
examples/sdk-examples/src/components/login/LoginForm.tsx

RELATED: FET-733 Upgrade yup package

---

common/changes/@gooddata/sdk-ui-all/dho-rail-3047-date-filter-public_2021-05-10-09-38.json

RELATED: RAIL-3047 Add changelog entry for public DateFilter

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/responsive.ts

Use correct Pie/Donut responsive chart width

---

libs/sdk-ui-charts/src/charts/headline/internal/Headline.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/__snapshots__/sizing.test.ts.snap
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiContent/KpiValue.tsx
libs/sdk-ui-ext/styles/internal/scss/layout.scss
libs/sdk-ui-vis-commons/src/utils/calculateCustomHeight.ts

Update headline/kpi min height limit by 1GR up

---

libs/sdk-ui-tests/README.md
libs/sdk-ui-tests/backstop/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
libs/sdk-ui-tests/backstop/run-backstop.sh

See commit descriptions
---
---
-   [ ] `check` …

RELATED: FET-743 - Stabilize backstop

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-tiger/package.json
libs/sdk-backend-tiger/src/auth.ts

This is done with backwards compatibility in mind.
JIRA: RAIL-3354
---
--- …

RELATED: RAIL-3354 Adapt to the new logout flow in Tiger 1.1

---

common/scripts/ci/init_hotfix_branch.sh

RELATED: RAIL-3393 Fix Slack integration of hotfix init job

---

common/scripts/ci/run_patch_release.sh
libs/sdk-ui-all/CHANGELOG.json
libs/sdk-ui-all/CHANGELOG.md

Merge 831-fix -> master

---

libs/sdk-ui-vis-commons/styles/scss/legend.scss

RELATED: ONE-5023 Remove margin for one column popup legend

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
libs/sdk-ui-geo/src/core/geoChart/GeoChartLegendRenderer.tsx

Fix geo chart legend title

---

libs/sdk-ui-vis-commons/src/legend/StaticLegend.tsx
libs/sdk-ui-vis-commons/src/legend/test/StaticLegend.test.tsx

Fix attribute PopUp legend paging

---

libs/sdk-ui-charts/src/charts/headline/Headline.tsx

- check if primary measure is specified
JIRA: RAIL-2030
---
--- …

RAIL-2030 Primary measure check

---

examples/sdk-examples/src/App.tsx
examples/sdk-examples/src/examples/chartResponsiveness/BarChartResponsiveExample.tsx
examples/sdk-examples/src/examples/chartResponsiveness/ColumnChartResponsiveLegendExample.tsx
examples/sdk-examples/src/examples/chartResponsiveness/HeadlineResponsiveExample.tsx
examples/sdk-examples/src/examples/chartResponsiveness/index.tsx
examples/sdk-examples/test/utils/helpers.ts

- Add examples for responsive legend with pre-defined and custom
(draggable) size
- Unify bar chart and headline chart responsive examples with responsive
legend examples.
JIRA: ONE-5027
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tel …

RELATED: ONE-5027 Add responsive legend examples

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Enable generic date attributes ff on Tiger

---

libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/sizing.test.ts

Extend size validation to kpi

---

libs/sdk-backend-tiger/src/auth.ts

This aligns it with the login already in place.
JIRA: RAIL-3401
---
--- …

RELATED: RAIL-3401 Make tiger logout cross-origin

---

libs/sdk-ui-charts/src/highcharts/chartTypes/barChart/barConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/bulletConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/columnChart/columnConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/lineChart/lineConfiguration.ts

Disable responsive rules when zooming is turned on

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-dashboard/src/_infra/filterContextSlice.ts
libs/sdk-ui-dashboard/src/_infra/layoutSlice.ts
libs/sdk-ui-dashboard/src/_infra/store.ts
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/filterBar/DashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/filterBar/DashboardDateFilter.tsx
libs/sdk-ui-dashboard/src/filterBar/FilterBar.tsx
libs/sdk-ui-dashboard/src/filterBar/index.ts
libs/sdk-ui-dashboard/src/index.ts
libs/sdk-ui-dashboard/src/topBar/DashboardMenuButton.tsx
libs/sdk-ui-dashboard/src/topBar/DashboardTitle.tsx
libs/sdk-ui-dashboard/src/topBar/TopBar.tsx
libs/sdk-ui-dashboard/src/topBar/index.ts
libs/sdk-ui-dashboard/tsconfig.json

-  Imports
-  Api-extractor errors
-  Store creation
JIRA: RAIL-3383
---
--- …

RELATED: RAIL-3383 - Clean up dashboard sketches

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts

Sort alphabetically items in the catalog

---

libs/api-client-bear/tsconfig.dev.json
libs/api-client-tiger/tsconfig.dev.json
libs/api-model-bear/tsconfig.dev.json
libs/sdk-backend-base/tsconfig.dev.json
libs/sdk-backend-bear/tsconfig.dev.json
libs/sdk-backend-mockingbird/tsconfig.dev.json
libs/sdk-backend-spi/tsconfig.dev.json
libs/sdk-backend-tiger/tsconfig.dev.json
libs/sdk-embedding/tsconfig.dev.json
libs/sdk-model/tsconfig.dev.json
libs/sdk-ui-all/tsconfig.dev.json
libs/sdk-ui-charts/tsconfig.dev.json
libs/sdk-ui-dashboard/tsconfig.dev.json
libs/sdk-ui-ext/tsconfig.dev.json
libs/sdk-ui-filters/tsconfig.dev.json
libs/sdk-ui-geo/tsconfig.dev.json
libs/sdk-ui-kit/tsconfig.dev.json
libs/sdk-ui-pivot/tsconfig.dev.json
libs/sdk-ui-tests/tsconfig.dev.json
libs/sdk-ui-theme-provider/tsconfig.dev.json
libs/sdk-ui-vis-commons/tsconfig.dev.json
libs/sdk-ui/tsconfig.dev.json
libs/util/tsconfig.dev.json
skel/sdk-skel-ts/tsconfig.dev.json
skel/sdk-skel-tsx/tsconfig.dev.json
tools/dashboard-plugin-template/tsconfig.dev.json
tools/plugin-toolkit/tsconfig.dev.json

Also remove some redundant/duplicate configs inherited from parent
configuration files.
JIRA: RAIL-3384
---
--- …

RELATED: RAIL-3384 Make the dev scripts produce esm, not dist

---

examples/playground/README.md
tools/applink/README.md
tools/applink/src/devConsole/action.ts
tools/applink/src/devConsole/pipeline/noopPublisher.ts
tools/applink/src/index.ts

-  This takes all libs and tools, watches for changes, rebuilds according to dependencies.
JIRA: RAIL-3383
---
--- …

RELATED: RAIL-3383 - Enhance applink with autoBuild mode

---

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

Use RSQL in functions that get filtered data from tiger api

---

examples/sdk-examples/src/examples/theming/ThemedComponentsExample.tsx
libs/api-model-bear/__mocks__/typeGuards.ts
libs/sdk-backend-mockingbird/src/recordedBackend/facts.ts
libs/sdk-backend-mockingbird/src/recordedBackend/measures.ts
libs/sdk-backend-spi/__mocks__/typeGuards.ts
libs/sdk-backend-tiger/src/backend/workspace/dateFilterConfigs/index.ts
libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Bubble/Bubble.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/Header/tests/HeaderAccount.test.tsx
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
libs/sdk-ui-kit/src/List/LegacyList.tsx
libs/sdk-ui-kit/src/List/LegacyMultiSelectList.tsx
libs/sdk-ui-kit/src/List/LegacyMultiSelectListItem.tsx
libs/sdk-ui-kit/src/List/LegacySingleSelectList.tsx
libs/sdk-ui-kit/src/List/LegacySingleSelectListItem.tsx
libs/sdk-ui-kit/src/List/tests/LegacyInvertableList.test.tsx
libs/sdk-ui-kit/src/Tabs/Tabs.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-pivot/src/impl/data/rowGroupingProvider.ts
libs/sdk-ui-tests/stories/visual-regression/kit/List/LegacyLists.tsx
libs/sdk-ui-vis-commons/src/legend/StaticLegend.tsx
libs/sdk-ui/__mocks__/typeGuards.ts
tools/dashboard-plugin-template/src/harness/public/index.html

* prevent/remove empty functions
* improve the dashboard-template HTML template
---
--- …

RELATED: RAIL-3384 fix some SonarQube issues

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/_staging/dateFilterConfig/validation.ts
libs/sdk-ui-dashboard/src/model/_staging/settings/conversion.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/handler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/loadDashboardConfig.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/config/configReducers.ts
libs/sdk-ui-dashboard/src/model/state/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/state/config/configState.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts

RELATED: RAIL-3383 - Add locale and number separators to config & state

---

libs/sdk-backend-bear/src/backend/workspace/attributes/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/attributes.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/attributes/index.ts
libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts

sdk-backend-spi: Add API to fetch attribute dataset

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
examples/sdk-examples/webpack.config.js
libs/sdk-ui-charts/package.json
libs/sdk-ui-charts/src/highcharts/adapter/plugins/dataLabelsColors.ts

* add missing SVG classlist polyfill in sdk-ui-charts
* transpile some recently upgraded libs to keep them working in IE11
JIRA: FET-754
---
--- …

RELATED: FET-754 Make examples work in IE11

---

libs/sdk-backend-base/src/cachingBackend/tests/withCaching.test.ts
libs/sdk-ui-kit/src/Header/tests/HeaderAccount.test.tsx
libs/sdk-ui-kit/src/Header/tests/HeaderMenu.test.tsx

TRIVIAL: Use example.com instead of real domain in tests

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/index.ts
libs/sdk-ui-dashboard/src/layout/Layout.tsx
libs/sdk-ui-dashboard/src/layout/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/handler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/loadCatalog.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/loadDashboardAlerts.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/alerts/alertsEntityAdapter.ts
libs/sdk-ui-dashboard/src/model/state/alerts/alertsSelectors.ts
libs/sdk-ui-dashboard/src/model/state/alerts/index.ts
libs/sdk-ui-dashboard/src/model/state/catalog/catalogReducers.ts
libs/sdk-ui-dashboard/src/model/state/catalog/catalogSelectors.ts
libs/sdk-ui-dashboard/src/model/state/catalog/catalogState.ts
libs/sdk-ui-dashboard/src/model/state/catalog/index.ts
libs/sdk-ui-dashboard/src/model/state/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-ext/src/dashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/dashboardView/DashboardViewProvider.tsx

- Add ControlledDashboardView component as a starting point to make DashboardView component pure/controllable
JIRA: RAIL-3430
---
--- …

Connect DashboardView to Dashboard component

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts

Update tiger catalog sorting items by title

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commands/base.ts
libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/eventEmitter/eventDispatcher.ts
libs/sdk-ui-dashboard/src/model/eventEmitter/rootEventEmitter.ts
libs/sdk-ui-dashboard/src/model/events/base.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/eventHandler.ts
libs/sdk-ui-dashboard/src/model/events/general.ts
libs/sdk-ui-dashboard/src/model/events/index.ts
libs/sdk-ui-dashboard/src/model/index.ts

RELATED: RAIL-3383 - Sketch additional commands and events for the dashboard component

---

examples/sdk-examples/src/examples/placeholders/MultiValuePlaceholderSrc.tsx

Placeholders examples - show friendly message when no measure is selected

---

libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/MetaConverter.ts
libs/sdk-backend-bear/tests/integrated/__snapshots__/catalog.test.ts.snap

sdk-backend-bear: Propagate display form type

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Turn on Height customization on Tiger

---

NOTICE
README.md

RELATED: LR-543 Update NOTICE and fix main README

---

common/changes/@gooddata/sdk-ui-all/RAIL-2041_2021-04-22-16-35.json
common/changes/@gooddata/sdk-ui-all/RAIL-3263_2021-04-14-11-02.json
common/changes/@gooddata/sdk-ui-all/RAIL-3307_2021-04-23-09-21.json
common/changes/@gooddata/sdk-ui-all/dho-rail-3047-date-filter-public_2021-05-10-09-38.json
common/changes/@gooddata/sdk-ui-all/map-rail-1842-deprecate-available-granularities_2021-04-15-13-15.json
common/changes/@gooddata/sdk-ui-all/map-rail-2929-tooltip-visibility-configuration_2021-04-27-14-49.json
common/changes/@gooddata/sdk-ui-all/map-rail-3274-insight-view-title-component_2021-04-27-09-01.json
common/changes/@gooddata/sdk-ui-all/mkn-rail-2800_2021-05-18-15-34.json
common/changes/@gooddata/sdk-ui-all/pb-legend-wip_2021-05-07-08-12.json
common/changes/@gooddata/sdk-ui-all/pdo-bb-2865-load-date-dataset-extension_2021-04-22-10-15.json

RELATED: RAIL-3047 Use proofread versions of the changelog items

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/setupDrilldownToParentAttribute.ts

 Avoid mutation of original bullet points

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/decoratedBackend/index.ts
libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-base/src/index.ts
libs/sdk-backend-base/src/workspaceSettingsBackend/index.ts
libs/sdk-backend-base/src/workspaceSettingsBackend/tests/withCustomWorkspaceSettings.test.ts

FET-690 Workspace settings backend decorator

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts

sdk-backend-spi: Register feature flag as setting

---

common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-ui-dashboard/src/model/state/filterContext/filterContextSelectors.ts
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
libs/sdk-ui-kit/src/Timepicker/tests/Timepicker.test.tsx

This fixes some of the advisories.
Also run prettier again as it had bugfixes that affect a few of our files.
JIRA: RAIL-3048
---
--- …

RELATED: RAIL-3048 Run rush update --full

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/index.ts
libs/sdk-backend-spi/src/workspace/attributes/elements/index.ts
libs/sdk-backend-spi/src/workspace/execution/index.ts
libs/sdk-backend-spi/src/workspace/execution/results.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/measure.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/types.ts
libs/sdk-backend-spi/src/workspace/insights/index.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/constants/colorPalette.ts
libs/sdk-ui/src/base/headerMatching/HeaderPredicate.ts
libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/localization/Locale.ts
libs/sdk-ui/src/base/react/BackendContext.tsx
libs/sdk-ui/src/base/react/ErrorComponent.tsx
libs/sdk-ui/src/base/react/LoadingComponent.tsx
libs/sdk-ui/src/base/react/WorkspaceContext.tsx
libs/sdk-ui/src/base/react/placeholders/base.ts
libs/sdk-ui/src/base/react/placeholders/context.tsx
libs/sdk-ui/src/base/react/safeSerialize.ts
libs/sdk-ui/src/base/react/useCancelablePromise.ts
libs/sdk-ui/src/base/react/useCancelablePromiseUtils.ts
libs/sdk-ui/src/base/results/dataAccess.ts
libs/sdk-ui/src/execution/Execute.tsx
libs/sdk-ui/src/execution/ExecuteInsight.tsx
libs/sdk-ui/src/execution/RawExecute.tsx
libs/sdk-ui/src/execution/withExecutionLoading.tsx
libs/sdk-ui/src/kpi/Kpi.tsx

Add links, add some "easy" missing docs, fix some typos, fix examples formatting.
---
--- …

RELATED: RAIL-3086 improve sdk-ui and sdk-backend-spi TSDocs

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/model/state/filterContext/filterContextSelectors.ts
libs/sdk-ui-dashboard/src/model/types/topBarTypes.ts
libs/sdk-ui-dashboard/src/topBar/DashboardButtonBar.tsx
libs/sdk-ui-dashboard/src/topBar/DashboardMenuButton.tsx
libs/sdk-ui-dashboard/src/topBar/DashboardTitle.tsx
libs/sdk-ui-dashboard/src/topBar/TopBar.tsx
libs/sdk-ui-dashboard/src/topBar/index.ts
libs/sdk-ui-dashboard/styles/scss/_variables.scss
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/styles/scss/topBar.scss

- DashboardTitle default component
- DashboardMenuButton default component
- integration into Dashboard component
JIRA: RAIL-3381
---
--- …

RAIL-3381 TopBar dashboard component

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

It is not ready for production use on Tiger yet.
JIRA: NAS-142
---
--- …

RELATED: NAS-142 Disable drilling in tiger

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Add multiple dates dev feature flag to tiger backend

---

common/changes/@gooddata/sdk-ui-all/map-rail-3455-attribute-filter-refactoring_2021-06-16-07-34.json
common/changes/@gooddata/sdk-ui-all/map-rail-3455-attribute-filter-refactoring_2021-06-16-07-35.json
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonExample.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonWithPlaceholderExample.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterExample.tsx
examples/sdk-examples/src/examples/attributeFilter/index.tsx
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilter.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- AttributeFilter component refactoring to functional component
- AttributeFilter placeholders support
- AttributeFilter parent-child filtering bug fixes
- AttributeFilterButton parent-child filtering bug fixes
- live examples update for parent-child filtering
- bug fixes for RAIL-3477, RAIL-3478, RAIL-3482, RAIL-3483, RAIL-3484
JIRA: RAIL-3455
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-com …

RAIL-3455 attribute filter refactoring

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/RecipientsSelect/RecipientsSelectRenderer.tsx

Add s-class for recipient warning message

---

libs/sdk-ui-dashboard/jest.setup.ts
libs/sdk-ui-dashboard/src/model/_staging/dashboard/dashboardFilterContext.ts
libs/sdk-ui-dashboard/src/model/_staging/dashboard/dashboardLayout.ts
libs/sdk-ui-dashboard/src/model/_staging/dashboard/tests/dashboardFilterContext.fixture.ts
libs/sdk-ui-dashboard/src/model/_staging/dashboard/tests/dashboardFilterContext.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/index.ts
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts

RELATED: RAIL-3492 - Move more code from KD

---

tools/catalog-export/src/loaders/tiger/index.ts

Catalog export: correct tiger documentation link

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.test.tsx
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts

RELATED: ONE-5081, ONE-5085 Fix line chart switching bugs

---

libs/sdk-ui-ext/src/internal/utils/bucketRules.ts

RELATED: ONE-5083 Disable recommendation when stack contains date

---

libs/sdk-ui-ext/src/internal/utils/bucketRules.ts

RELATED: ONE-5094 Include dates in stacks when counting categories

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.test.tsx

Fix line chart duplicate item in segment by

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx

- refresh child filter selected values after parent filter changed
JIRA: RAIL-3515
---
--- …

RAIL-3515 Attribute filtering

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/model/events/alerts.ts
libs/sdk-ui-dashboard/src/scheduledEmail/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/scheduledEmail/types.ts
libs/sdk-ui-dashboard/src/topBar/DashboardMenuButton.tsx
libs/sdk-ui-dashboard/src/topBar/DashboardTitle.tsx
libs/sdk-ui-dashboard/src/topBar/TopBar.tsx
libs/sdk-ui-dashboard/src/topBar/index.ts
libs/sdk-ui-dashboard/styles/scss/topBar.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Messages/ToastMessageContext.tsx
libs/sdk-ui-kit/src/Messages/ToastMessages.tsx
libs/sdk-ui-kit/src/Messages/index.ts
libs/sdk-ui-kit/src/Messages/useToastMessage.ts

- modified MenuButton logic
- schedule emailing feature
---
--- …

RAIL-3381 button bar component

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/dashboard/internal/useExportDashboardToPdf.ts
libs/sdk-ui-dashboard/src/dashboard/useDashboardPdfExporter.ts
libs/sdk-ui-dashboard/src/examples.tsx
libs/sdk-ui-dashboard/src/layout/DefaultDashboardLayout.tsx
libs/sdk-ui-dashboard/src/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/topBar/DashboardMenuButton.tsx
libs/sdk-ui-dashboard/src/topBar/DashboardTitle.tsx
libs/sdk-ui-dashboard/src/topBar/TopBar.tsx
libs/sdk-ui-dashboard/styles/scss/_globals.scss
libs/sdk-ui-dashboard/styles/scss/_variables.scss
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/tsconfig.json
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/List/ListItem.tsx

* Add the ability to export dashboard to pdf (adapted from sdk-ui-ext).
* Make the styles closer visually to gdc-dashboards
* Tweak the TopBar API a bit and fix TSDoc comments.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pu …

RELATED: RAIL-3381 add pdfExport, improve TopBar styles

---

common/changes/@gooddata/sdk-ui-all/dho-rail-3048-changes_2021-06-28-11-11.json
common/changes/@gooddata/sdk-ui-all/dho-rail-3048-changes_2021-06-28-11-12.json

RELATED: RAIL-3048 Add changelog entries for Tiger features

---

libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdownAllFilteredOutBody.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilter.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
libs/sdk-ui-filters/styles/scss/attributeFilter.scss
libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

- Show All filtered message if options reduced to zero
- AttributeDropdownAllDilteredOutBody component with stylings
JIRA: RAIL-3516
---
--- …

RAIL-3516 Attribute parent child filtering all filtered out

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/tests/PluggableTreemap.test.tsx

Remove dev feature flag

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts
libs/api-model-bear/src/visualizationWidget/tests/GdcVisualizationWidget.fixtures.ts
libs/api-model-bear/src/visualizationWidget/tests/GdcVisualizationWidget.test.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/drills.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DrillConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DrillConverter.test.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DrillConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/drills.ts
libs/sdk-backend-spi/src/workspace/dashboards/tests/drills.fixtures.ts
libs/sdk-backend-spi/src/workspace/dashboards/tests/drills.test.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-dashboard/src/model/_staging/drills/drillingUtils.ts
libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/drillingUtils.ts

Drill to insight/dashboard from attribute

---

NOTICE

RELATED: LR-600 update NOTICE

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartTooltips.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts

Fix missing date dimension information on chart tooltip

---

libs/sdk-backend-base/src/ldmFactories/dashboard/insightWidgetFactory.ts
libs/sdk-backend-base/src/ldmFactories/dashboard/kpiWidgetFactory.ts
libs/sdk-backend-bear/api/sdk-backend-bear.api.md
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/drills.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/widget.ts

Dashboard widgets - narrow widget drill typings

---

common/changes/@gooddata/sdk-ui-all/dho-rail-3048-changes_2021-06-28-11-12.json
common/changes/@gooddata/sdk-ui-all/map-rail-3455-attribute-filter-refactoring_2021-06-16-07-34.json
common/changes/@gooddata/sdk-ui-all/map-rail-3455-attribute-filter-refactoring_2021-06-16-07-35.json

Improve phrasing, fix typos
JIRA: RAIL-3048
---
--- …

RELATED: RAIL-3048 Fix changelog entries

---

tools/catalog-export/src/transform/titles.ts
tools/catalog-export/src/transform/toTypescript.ts

RELATED: RAIL-3550 Fix catalog export for numeric display forms

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts

Use standard display form for for geo chart tooltip

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsightWithDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/useDashboardDrillTargets.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/useDashboardInsightDrills.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts

Handling of onAvailableDrillTargetsReceived 

---

libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetHeaderHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/changeInsightWidgetHeaderHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/changeInsightWidgetHeaderHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/widgetValidations.ts
libs/sdk-ui-dashboard/src/model/state/layout/layoutReducers.ts
libs/sdk-ui-dashboard/src/model/tests/Dashboard.fixtures.ts

RELATED: RAIL-3492 - Add handler for change insight header command

---

libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

TRIVIAL: Import localizations

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/MenuButtonPropsContext.tsx
libs/sdk-ui-dashboard/styles/scss/_globals.scss
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/styles/scss/topBar.scss

- MenuButtonPropsContext - Propagate proper default value
- add gdc-dashboards missing DOM elements
- correct global css
---
--- …

DashboardComponent: Add missing gdc-dashboards DOM elements

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts

Dashboard: fix missing correlationId in drillToDashboardHandler

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/moveAttributeFilterHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/setAttributeFilterParentHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/__snapshots__/changeDateFilterSelectionHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/addLayoutSectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/addSectionItemsHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/moveLayoutSectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/moveSectionItemHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/removeLayoutSectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/removeSectionItemHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/replaceSectionItemHandler.test.ts
libs/sdk-ui-dashboard/src/model/state/layout/tests/__snapshots__/layoutReducers.test.ts.snap
libs/sdk-ui-dashboard/src/model/state/layout/tests/layoutReducers.test.ts
tools/reference-workspace/src/ldm/full.ts
tools/reference-workspace/src/recordings/dataSample.ts
tools/reference-workspace/src/recordings/index.ts
tools/reference-workspace/src/recordings/metadata/dashboards/aaRaEZRWdRpQ/obj.json

RELATED: RAIL-3560 Update workspace recordings

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/__snapshots__/changeDateFilterSelectionHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/changeDateFilterSelectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/state/filterContext/filterContextReducers.ts

RELATED: RAIL-3584 Fix upsertDateFilter method of filterContextReducers

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/drills/InsightDrillDefinitionUtils.ts
libs/sdk-ui-dashboard/src/_staging/drills/test/InsightDrillDefinitionUtils.test.ts
libs/sdk-ui-dashboard/src/_staging/drills/test/__snapshots__/InsightDrillDefinitionUtils.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/alerts/createAlertHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/alerts/removeAlertHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/alerts/updateAlertHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drillTargets/addDrillTargetsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drillTargets/test/addDrillTargetsHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillsForInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/modifyDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/modifyDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts
libs/sdk-ui-dashboard/src/model/commands/drillTargets.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/commands/insight.ts
libs/sdk-ui-dashboard/src/model/events/drillTargets.ts
libs/sdk-ui-dashboard/src/model/state/drillTargets/index.ts
libs/sdk-ui-dashboard/src/model/state/layout/layoutReducers.ts
libs/sdk-ui-dashboard/src/model/state/layout/tests/__snapshots__/layoutReducers.test.ts.snap
libs/sdk-ui-dashboard/src/model/state/layout/tests/layoutReducers.test.ts
libs/sdk-ui-dashboard/src/model/tests/Dashboard.fixtures.ts

Handle create and modify widget drill definition

---

common/config/rush/pnpm-lock.yaml
libs/sdk-model/src/execution/buckets/index.ts
libs/sdk-model/src/execution/buckets/tests/__snapshots__/bucket.test.ts.snap
libs/sdk-model/src/execution/buckets/tests/bucket.test.ts

- add specific helpful error messages to help with using SDK
JIRA: RAIL-3467
---
--- …

RAIL-3467 improve dx for bucket creation

---

libs/sdk-ui-dashboard/src/model/state/drillTargets/drillTargetsEntityAdapter.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/useDashboardDrillTargets.ts
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx

RELATED: RAIL-3593 PivotTable ended-up in infinite loading loop, plug viz callback are not updated

---

libs/sdk-ui-kit/src/Overlay/Overlay.tsx

RELATED: TNT-5 Stop event propagation on onDocumentMouseDown in Overlay

---

libs/sdk-ui-dashboard/styles/scss/drillDialog.scss

Drill dialog footer styles

---

libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/WithDrillSelect.tsx
libs/sdk-ui-dashboard/src/presentation/drill/utils/drillDownUtils.ts

RELATED: RAIL-3597 Handle multiple drills on attribute

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectListItem.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/types.ts
libs/sdk-ui-dashboard/src/presentation/drill/utils/drillDownUtils.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsightWithDrillDialog.tsx
libs/sdk-ui-dashboard/styles/scss/drillSelect.scss

- Port TNT-83 Extend D2Uri picker item
JIRA: RAIL-3597
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or …

Add attribute value next DrillToURL label 

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts

Disabled export of drilled insight in Tiger

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/layout/layoutSelectors.ts

These select all the KPI and Insight widgets in the dashboard.
---
--- …

RELATED: RAIL-3385 Add widget selectors

---

libs/sdk-ui-kit/src/Overlay/Overlay.tsx

JIRA: TNT-137
Related to #1600
---
---
-   [ ] …

RELATED: TNT-137 Perform stopPropagation in overlay only when click inside

---

examples/sdk-examples/src/components/AboutThisWorkspace.tsx
examples/sdk-examples/src/components/Header.tsx
examples/sdk-examples/src/constants/routes.ts

- All the occurrences of the text "project" (see attached images) should be changed to "workspace" in GD.UI Examples
JIRA: SD-1687
---
--- …

Rename project to workspace on GD.UI Examples

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

Rewrite InsightView to a Functional component, so that we can approach
the component in a more standard way.
It also made it easy to fix these:
* the backendWithTelemetry is now properly memoized
* visualizationError is cleared when visualization starts loading
These two fixes should prevent inconsistent states when obsolete errors
were shown or the visualization was rendered twice.
JIRA: RAIL-3600
---
--- …

RELATED: RAIL-3600 Rewrite InsightView, fix bugs

---

libs/sdk-ui-geo/styles/scss/main.scss

Fix gdcustomfont in geochart legend

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/alerts.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/drill.ts
libs/sdk-ui-dashboard/src/model/events/drillTargets.ts
libs/sdk-ui-dashboard/src/model/events/filters.ts
libs/sdk-ui-dashboard/src/model/events/general.ts
libs/sdk-ui-dashboard/src/model/events/index.ts
libs/sdk-ui-dashboard/src/model/events/insight.ts
libs/sdk-ui-dashboard/src/model/events/kpi.ts
libs/sdk-ui-dashboard/src/model/events/layout.ts
libs/sdk-ui-dashboard/src/model/events/render.ts
libs/sdk-ui-dashboard/src/model/events/scheduledEmail.ts
libs/sdk-ui-dashboard/src/model/events/userInteraction.ts
libs/sdk-ui-dashboard/src/model/events/util.ts

RELATED: RAIL-3385 Add type guards for all dashboard events

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

Repair of invalid URL in measures path.
Added leading / into url 
JIRA: NAS-229
---
--- …

TRIVIAL: NAS-229 Repair of url in measures link

---

libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml

RELATED: SETI-6112 Use latest frontend cypress image

---

.github/pull_request_template.md

RAIL-3613 update PR template with cypress

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/layout/layoutSelectors.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/DefaultButtonBar.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/types.ts
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/types.ts
libs/sdk-ui-dashboard/src/presentation/topBar/title/DefaultTitle.tsx

Improve TopBar so that it is fully compatible with KD:
* add proper ButtonBar implementation
* rationalize the MenuButtonItem API
* add disabled and tooltip properties for MenuButton buttons
* add missing wrapper to DefaultTitle
* add a missing selector determining if the layout is empty
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …

RELATED: RAIL-3385 make TopBar on par with KD

---

libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss

Add hover styles to zoom out button

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/eventHandler.ts
libs/sdk-ui-dashboard/src/model/index.ts

RELATED: RAIL-3385 Add eventHandler convenience functions

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboard.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/02-sdk-ui-filters/dateFilter.spec.ts
libs/sdk-ui-tests-e2e/cypress/tools/dashboards.ts
libs/sdk-ui-tests-e2e/cypress/tools/dateFilter.ts
libs/sdk-ui-tests-e2e/cypress/tools/dateFilterAbsoluteForm.ts
libs/sdk-ui-tests-e2e/cypress/tools/dateFilterRelativeForm.ts

RAIL-3609 Cypress page fragments to fluid API

---

common/config/rush/pnpm-lock.yaml
libs/sdk-embedding/package.json
libs/sdk-embedding/src/internal/filterValuesResolver.ts
libs/sdk-embedding/src/internal/tests/__snapshots__/filterValuesResolver.test.ts.snap
libs/sdk-embedding/src/internal/tests/filterValuesResolver.test.ts

JIRA: TNT-150
Implement resolution of absolute date interval limits. Other filter types will folllow
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-n …

Implement absolute date filter resolution

---

libs/sdk-backend-bear/src/backend/index.ts

Add getUISettings to Bear legacy function to get uiSetting of domain

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/sortItemsHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/sortItemsHelpers.test.ts

TNT-166 Disable table sorting check with feature flag

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addSectionItemsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/addLayoutSectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/addSectionItemsHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/validation/itemValidation.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/validation/stashValidation.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/filterValidation.ts
libs/sdk-ui-dashboard/src/model/commands/layout.ts
libs/sdk-ui-dashboard/src/model/queries/index.ts
libs/sdk-ui-dashboard/src/model/queries/insights.ts
libs/sdk-ui-dashboard/src/model/queryServices/queryInsightAttributesMeta.ts
libs/sdk-ui-dashboard/src/model/queryServices/queryInsightDateDatasets.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/Layout.fixtures.ts

RELATED: RAIL-3492 - Validate & optionally auto-resolve filter settings for new insight and KPI widgets

---

libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx

RAIL-3653 consider date format project setting

---

.envrc
README.md
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/resolveDashboardConfig.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/replaceSectionItemHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/replaceSectionItemHandler.test.ts
libs/sdk-ui-dashboard/src/model/commands/filters.ts
libs/sdk-ui-dashboard/src/model/commands/layout.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/types.ts

RELATED: RAIL-3492 - Further sanitization and fixes

---

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/useBrokenAlertFiltersMeta.ts

Fix attribute title instead displayFrom title in broken alert dialog

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartLegendRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/responsive.ts
libs/sdk-ui-geo/src/core/geoChart/legends/PushpinSizeLegend.tsx
libs/sdk-ui-geo/src/core/geoChart/legends/test/PushpinSizeLegend.test.tsx

Fix geo chart circle legend responsiveness

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/converters/filterConverters.ts
libs/sdk-ui-dashboard/src/index.ts
libs/sdk-ui-dashboard/src/model/events/index.ts

Dashboard component - expose api required for post messages

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/src/presentation/constants/index.ts
libs/sdk-ui-dashboard/src/presentation/constants/layout.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/FluidLayoutDescriptor.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/facade/items.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/index.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/legacy.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/sizing.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/sizing.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx

RAIL-3659 headline height fix

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/getDrillToUrlFilters.ts

Call values resolver with backend and workspace params

---

libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemContentWrapper.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemHeadlineContainer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/DashboardItemWithKpiAlert.tsx

RAIL-3660 Broken widget title due to incorrect clientHeight

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

Bugfix Apply alert filters to dashboard link did not work

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts

JIRA: TNT-197
Minimize number of requests by enlarging pageSize according selected elements count
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-need …

Optimize number of API calls

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/getDrillToUrlFilters.ts

Override insight filters in drillToUrl filters payload

---

libs/sdk-ui-kit/src/Overlay/Overlay.tsx

Make modal visibility hidden until its position is calculated.
---
--- …

NAS-288 A modal appears lightning fast in the left corner

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/gridOptions.ts
libs/sdk-ui-pivot/src/impl/tableFacade.ts

Tooltip on cells for Pivot Table

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

RAIL-3674 AttributeFilterButton filtered selection fix

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/CustomError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

RELATED: RAIL-3654 Force full error content in drill dialog

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts

Fix filter values resolver paging index

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

JIRA: NAS-201
Rename measure to metrics in
- metrics editor url
- translation key in header menu
- testing class in header menu
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do- …

Rename measures to metrics in menu and URL

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts

Update paging index calculation in resolver

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

RAIL-3675 AttributeFilterButton search feature behaviour fix

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartLegendRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/legends/PushpinCategoryLegend.tsx

Fix floating legend name

---

libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/styles/scss/_variables.scss
libs/sdk-ui-dashboard/styles/scss/filterBar.scss

RAIL-3667 Add styles to fix filterBar incorrect behavior

---

libs/api-client-bear/src/metadataExt.ts

Allows the callers of saveDashboardAs to override the tags
(along with name and summary taht were available for override already).
The code was cleaned up a bit and simplified.
JIRA: RAIL-3623
---
--- …

RELATED: RAIL-3623 Add option to override tags in saveDashboardAs

---

common/changes/@gooddata/sdk-ui-all/release_2021-09-17-08-32.json

Add additional release note to sdk release

---

common/changes/@gooddata/sdk-ui-all/release_2021-09-17-08-32.json

Edit release note for data sampling

---

examples/sdk-examples/src/examples/theming/ThemedComponentsExample.tsx

Better approach to use theme object in examples

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Dialog/HubspotConversionTouchPointDialog.tsx
libs/sdk-ui-kit/src/Dialog/HubspotConversionTouchPointDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/index.ts
libs/sdk-ui-kit/src/Dialog/tests/HubspotConversionTouchPointDialog.test.tsx
libs/sdk-ui-kit/src/Dialog/tests/HubspotConversionTouchPointDialogBase.test.tsx
libs/sdk-ui-kit/styles/scss/dialog.scss

RELATED: SD-1809 Adding the conversion touch point dialog to support for multi apps

---

libs/sdk-ui-kit/styles/scss/list.scss

Fix filter preview when attribute filter name long

---

libs/sdk-ui-kit/styles/scss/list.scss

Fix filter preview when selection list too long

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/__snapshots__/resetDashboardHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/resetDashboardHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/SimpleDashboard.fixtures.ts

RELATED: RAIL-3492 - Add reset dashboard handler

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/CustomError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/tests/CustomError.test.tsx

Handle correctly Too large data to compute

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-ui-dashboard/src/presentation/localization/IntlWrapper.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/createInternalIntl.ts
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/IntlWrapper.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/Context.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/TranslationsCustomizationProvider.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/index.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/TranslationsCustomizationProvider.test.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/__snapshots__/utils.test.ts.snap
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/utils.test.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/util/src/translationUtils.ts

New provider to load flag enableInsightToReport

---

libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/TranslationsCustomizationProvider.tsx

Fix memoized value in TranslationsCustomizationProvider

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
libs/sdk-ui-kit/src/List/tests/LegacyInvertableList.test.tsx

JIRA: RAIL-3751, RAIL-3752, RAIL-3753
---
--- …

Fix AttributeFilterButton behavior

---

libs/sdk-ui-ext/src/dashboardView/DashboardViewProvider.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx

DashboardView - fix of IntlProvider

---

common/config/rush/browser-approved-packages.json
libs/sdk-backend-spi/src/workspace/insights/index.ts

- Modify missleading documentation for IInsightQueryOptions
JIRA: RAIL-3754
---
--- …

RAIL-3754 InsightQueryOptions interface docs

---

libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts

Fix measure expression token validation

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- Backup and restore selection to handle Cancel button click 
JIRA: RAIL-3753
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code …

RAIL-3753 cancel selection fix

---

common/changes/@gooddata/sdk-ui-all/release_2021-09-17-08-32.json
common/config/rush/browser-approved-packages.json
examples/sdk-examples/src/examples/attributeFilter/AttributeFilterButtonExample.tsx
libs/sdk-backend-spi/src/workspace/insights/index.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdownList.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
libs/sdk-ui-kit/src/List/tests/LegacyInvertableList.test.tsx

Merge release to master

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/PluggablePivotTable.test.tsx.snap
libs/sdk-ui-ext/src/internal/constants/properties.ts
libs/sdk-ui-pivot/src/impl/tableFacade.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/vis/visualizationTypes.ts

- Check if growToFit is set to true on resizing configuration.
JIRA: TNT-21
---
--- …

Grow to fit should not apply on AD

---

libs/sdk-ui-dashboard/styles/scss/filterBar.scss

- Add styles to make filterBar sticky
JIRA: RAIL-3735
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think …

RAIL-3735 FilterBar is not sticky while scrolling

---

libs/sdk-ui-dashboard/src/presentation/presentationComponents/LoadingEqualizer.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/styles/scss/layout.scss
libs/sdk-ui-dashboard/styles/scss/loadingEqualizer.scss
libs/sdk-ui-dashboard/styles/scss/main.scss

- introduced Running wheel loading component
- default drill loading component
JIRA: RAIL-3685
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-a …

RAIL-3685 Change default drill dialog loading component

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- Wrap AttributeFilterButton title with ShortenedText component
JIRA: RAIL-3734
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-co …

RAIL-3734 AttributeFilterButton title lenght

---

libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx

RELATED: RAIL-3627 Fix DashboardComponentsContext merging

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
examples/playground/README.md
examples/playground/package.json
examples/playground/scripts/run-playground.sh
examples/playground/src/index.tsx
examples/playground/tsconfig.json
examples/playground/webpack.config.js

RELATED: FET-828 Introduce why-did-you-render into playground

---

libs/sdk-ui-kit/styles/scss/header.scss

- Add the upsell button to app header component
JIRA: SD-1808
---
--- …

Update the upsell button css on SDK UI Kit AppHeader component

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/DataTooLargeError.tsx

Update icon classname to use sdk-ui-kit indigoFont

---

libs/sdk-ui-dashboard/.eslintrc.js
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/ConfigurationParentItems.tsx

RELATED: RAIL-3473 - Hook usage corrections

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/bulletChartUiConfigHelper.test.ts

Unmount bullet chart after error

---

tools/plugin-toolkit/src/_base/cli/prompts.ts
tools/plugin-toolkit/src/_base/cli/validators.ts
tools/plugin-toolkit/src/initCmd/actionConfig.ts
tools/plugin-toolkit/src/initCmd/index.ts
tools/plugin-toolkit/src/initCmd/replaceInFiles.ts
tools/plugin-toolkit/src/initCmd/test/replaceInFiles.test.ts

- port template replacements from boilerplate
- ensure dev proxy proxies to correct /api endpoints when on tiger
- remove unnecessary backend from package.json dependencies
---
--- …

RELATED: RAIL-3428 - Plugin Dev Toolkit part 3

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/base.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/labelElements.ts
libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/MetricConverter.ts

Also adapt to the newly generated tiger client.
JIRA: RAIL-3757
---
--- …

RELATED: RAIL-3757 Switch computeLabelElements to POST

---

common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-ui-tests-e2e/package.json

This resolves a security advisory.
JIRA: FET-868
---
--- …

RELATED: FET-868 Upgrade axios 0.21.1 -> 0.21.4

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
tools/dashboard-plugin-template/src/plugin/Plugin.tsx
tools/dashboard-plugin-template/src/plugin_entry/index.ts
tools/dashboard-plugin-template/webpack.config.js
tools/plugin-toolkit/.babelrc-js
tools/plugin-toolkit/package.json
tools/plugin-toolkit/scripts/build.sh
tools/plugin-toolkit/src/initCmd/index.ts

* Make JS version work
* properly remove TS files
* make sure harness can be run
* rename React files to .jsx
* Use babel preset instead of isolated plugin, add missing dependency
* Use data from package.json where possible and fix the imports from there
---
---
-   [ ] …

RELATED: RAIL-3428 tweak plugin toolkit

---

rush.json
tools/dashboard-plugin-template/README.md
tools/dashboard-plugin-template/README.template.md
tools/dashboard-plugin-template/webpack.config.js
tools/plugin-toolkit/package.json
tools/plugin-toolkit/scripts/build.sh
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/initCmd/index.ts

-  added readme template with some initial quick docs
-  made plugin-toolkit public package
-  added 'bin' entry (gdc-plugins)
---
--- …

RELATED: RAIL-3428 - Plugin CLI enhancements

---

tools/plugin-toolkit/package.json

The package is ok to be released in alpha versions.
JIRA: RAIL-3428
---
--- …

RELATED: RAIL-3428 Remove private flag from plugin-toolkit

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts

- fix & simplify drillToDashboardHandler by reusing queryWidgetFilters logic
JIRA: RAIL-3636
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-app …

Dashboard component: fix drill to dashboard filters resolution

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap

Fix conversion of empty flags

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-bear/src/backend/workspace/index.ts
libs/sdk-backend-tiger/src/backend/index.ts
tools/dashboard-plugin-template/.env.secrets.template
tools/dashboard-plugin-template/.env.template
tools/dashboard-plugin-template/.gitignore
tools/dashboard-plugin-template/webpack.config.js
tools/plugin-toolkit/README.md
tools/plugin-toolkit/package.json
tools/plugin-toolkit/scripts/build.sh
tools/plugin-toolkit/src/_base/backend.ts
tools/plugin-toolkit/src/_base/cli/validators.ts
tools/plugin-toolkit/src/_base/utils.ts
tools/plugin-toolkit/src/addPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/addPluginCmd/index.ts
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/initCmd/actionConfig.ts
tools/plugin-toolkit/tsconfig.build.esm.json
tools/plugin-toolkit/tsconfig.dev.json
tools/plugin-toolkit/tsconfig.json

RELATED: RAIL-3428 - First working version of the add command

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts

Fix drill to attribute url validation

---

libs/sdk-backend-bear/src/utils/errorHandling.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts

- include also all time date filter, when necessary
- also fix export protected data error propagation
JIRA: RAIL-3820, RAIL-3692
---
--- …

Dashboard - fix drill to dashboard filters

---

libs/sdk-ui-loaders/src/dashboard/beforeLoadPluginValidation.ts

RELATED: RAIL-3473 Fix validatePluginsBeforeLoading

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

RELATED: RAIL-3473 Enable sdk-ui-dashboard in tiger

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
tools/plugin-toolkit/package.json
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/listCmds/actionConfig.ts
tools/plugin-toolkit/src/listCmds/listCmdAction.ts
tools/plugin-toolkit/src/listCmds/listDashboardPlugins.ts
tools/plugin-toolkit/src/listCmds/listDashboards.ts
tools/plugin-toolkit/src/listCmds/types.ts

RELATED: RAIL-3428 - Add commands to list dashboards and dashboardPlugins

---

libs/sdk-ui-dashboard/src/plugins/customizer.ts

RELATED: RAIL-3801 Add description on sizing custom component

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json

RELATED: RAIL-3833 Add missing localization for empty dashboard error

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveDashboardHandler.ts

RELATED: RAIL-3846 - Fix bug where plugins were not propagated into the dashboard to save

---

libs/sdk-backend-tiger/src/backend/organization/securitySettings.ts
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/DefaultButtonBar.tsx

RELATED: RAIL-3844, RAIL-3845 - Plugins fix & tiger relax of plugin source validation

---

tools/dashboard-plugin-template/webpack.config.js
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/initCmd/index.ts

RELATED: RAIL-3852, RAIL-3844 - Plugin template build change & CLI fix

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap

RELATED: NAS 133 Add supportsWidgetEntity capability

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

RELATED: NAS 139 Enable renaming project to workspace flag

---

libs/sdk-ui-loaders/src/dashboard/useDashboardLoader.ts

We need to compare serialized value of the ref, not the reference.
JIRA: RAIL-3876
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a …

RELATED: RAIL-3876 Prevent infinite reloads of useDashboardLoader

---

libs/sdk-ui-dashboard/src/plugins/customizationApis/layoutCustomizer.ts

- Avoid runtime error, log error to console only
JIRA: RAIL-3870
---
--- …

Skip invalid layout transformations

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap

RELATED: NAS-131 Add supportsOwners capability

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Enable drill to dashboard, insight and url

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/src/_staging/exportUtils/filterUtils.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPdfHandler.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useCreateScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts

* make sure the current filter context is passed to the create function
* ensure All time filter is created if needed
* small refactoring of the All time filter logic already used in exports
JIRA: RAIL-3843
---
--- …

RELATED: RAIL-3843 Fix scheduled emails filters

---

libs/sdk-ui-dashboard/.gitignore
libs/sdk-ui-dashboard/scripts/build.sh
libs/sdk-ui-dashboard/src/plugins/engine.ts
libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
libs/sdk-ui-loaders/src/dashboard/useDashboardLoader.ts

* fill the engine version properly
* add debug logs
---
--- …

RELATED: RAIL-3878 engine and loader improvements

---

examples/sdk-examples/src/App.tsx
examples/sdk-examples/src/components/Header.tsx
examples/sdk-examples/src/index.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

* add missing localization string
* use correct IntlProvider
* fix live-examples styles
---
--- …

RELATED: RAIL-3883 small live examples and dashboard fixes

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/styles/scss/attributeFilter.scss

- added filter background while filtering by parent
- update all descendants of the parent attribute filter
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-te …

RELATED: RAIL-3849 - Fix parent-child filtering issues

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- handle element filtering after parent attribute filter changed
- add all possible errors to onError callback
---
--- …

RELATED: RAIL-3849 Resolve filtering by parents in child attribute filter

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/styles/scss/_variables.scss
libs/sdk-ui-dashboard/styles/scss/visualization.scss

Fix zoom area styles

---

libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

RELATED: RAIL-3849 attribute filter initialization fix

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts
libs/sdk-ui-dashboard/src/model/store/permissions/permissionsSelectors.ts
libs/sdk-ui-dashboard/src/presentation/constants/colors.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/index.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/index.ts
libs/sdk-ui-dashboard/src/presentation/topBar/shareButton/DefaultShareButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/index.ts
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/DefaultLockedStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/LockedStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/LockedStatusIndicator.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/types.ts
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/DefaultShareStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatusIndicator.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/types.ts
libs/sdk-ui-dashboard/src/presentation/topBar/topBar/DefaultTopBar.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/topBar/types.ts
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/styles/scss/shareIndicators.scss
libs/sdk-ui-dashboard/styles/scss/topBar.scss

JIRA: TNT-277
Locked and Share indicators in Dashboard's top bar.
Components can not be customized for now
---
--- …

Locked and Share indicators

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
libs/sdk-ui-filters/styles/scss/attributeFilter.scss

RELATED: RAIL-3849 revert

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- hide all filtered info message while all items are filtered by the parent attribute filter
---
--- …

RELATED: RAIL-3890 Hide Items filtered message

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/test/testHelpers.tsx

Update ShareDialog test

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/rsqlFilter.ts

RELATED: NAS-109 Use RSQL filter for included/excluded tags query

---

NOTICE

RELATED: LR-865 upgrade NOTICE file

---

NOTICE

LR-865 upgrade NOTICE file

---

libs/sdk-ui-dashboard/src/presentation/topBar/shareButton/DefaultShareButton.tsx

Hide share button when Dashboard is in readonly mode

---

libs/sdk-backend-base/src/toolkit/paging.ts

RELATED: FET-847 Fix ServerPaging totalCount invariant

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json

Trivial change of creator tooltip text in ShareDialog

---

common/changes/@gooddata/sdk-ui-all/list_2021-12-06-11-43.json
libs/sdk-backend-bear/src/backend/organization/securitySettings.ts
libs/sdk-backend-bear/src/backend/organization/tests/securitySettings.test.ts

RELATED: RAIL-3896 - Fix plugin hosts validation

---

common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/package.json
libs/sdk-backend-bear/package.json
libs/sdk-ui-tests-e2e/package.json
tools/catalog-export/README.md
tools/catalog-export/package.json
tools/catalog-export/src/loaders/tiger/index.ts
tools/dashboard-plugin-template/package.json
tools/plugin-toolkit/package.json

- support to read TIGER_API_TOKEN through .env file
- documentation for the auth through the .env file
JIRA: FET-888
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-m …

RELATED: FET-888 catalog export env file support

---

libs/api-client-bear/src/metadata.ts
libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/dashboard.ts
libs/sdk-backend-spi/src/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/AnalyticalDashboardConverter.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadAccessibleDashboardList.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts
libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/accessibleDashboardsEntityAdapter.ts
libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/accessibleDashboardsSelectors.ts
libs/sdk-ui-dashboard/src/model/store/accessibleDashboards/index.ts
libs/sdk-ui-dashboard/src/model/store/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/types.ts
libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/ComplexDashboard.fixtures.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/SimpleDashboard.fixtures.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/test/shareDialogMappers.test.ts

Do not remove drills to dashboards that were not explicitly shared with the current user

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json

RELATED: RAIL-3900 Add missing alert_not_supported string

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

- proper functionality of drill to url is blocked by https://jira.intgdc.com/browse/GDP-1989
JIRA: NAS-137
---
--- …

Disable Dashboard drill to URL

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeFilterBody.tsx
libs/sdk-ui-dashboard/styles/scss/filterBar.scss
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- Add mobile device support for AttributeFilterButton component
JIRA: FET-927
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code …

RELATED: FET-927 Add styles to display dropdown correctly

---

common/changes/@gooddata/sdk-ui-all/IMJ-TNT-382_2021-12-08-14-14.json
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx

Fix user search control in ShareDialog where SPACE key select first option    

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/createInternalIntl.ts
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/IntlWrapper.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/TranslationsCustomizationProvider.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/index.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

Renaming measure to metric

---

libs/sdk-ui-filters/src/DateFilter/DateFilterBody/EditModeMessage.tsx

We need to provide nbsp formatter, not br.
JIRA: FET-529
---
--- …

RELATED: FET-529 Fix intl formatting

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx

Fix Disable white space characters in AddGranteeSelect in ShareDialog

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx

Make the polluteWidgetRefsWithBothIdAndUri defensive to prevent
occasional hard to reproduce invariant errors.
Also, optimize computation of transformedLayout in export mode
by preventing the non-export branch from being executed wastefully,
and use appropriate dependencies in its memo.
JIRA: RAIL-3916
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.m …

RELATED: RAIL-3916 Prevent invariant errors in DefaultDashboardLayout

---

libs/sdk-ui-all/CHANGELOG.json
libs/sdk-ui-all/CHANGELOG.md

Merge hotfix-8.7.1 -> master

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/DefaultShareStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatusIndicator.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/types.ts

Hide share status indicator for viewer user

---

libs/api-client-bear/package.json
libs/api-client-tiger/package.json
libs/api-model-bear/package.json
libs/sdk-backend-base/package.json
libs/sdk-backend-bear/package.json
libs/sdk-backend-mockingbird/package.json
libs/sdk-backend-spi/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-embedding/package.json
libs/sdk-model/package.json
libs/sdk-ui-all/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-loaders/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-theme-provider/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json
libs/util/package.json
skel/sdk-skel-ts/package.json
skel/sdk-skel-tsx/package.json

- add es2015 entry in every package.json where applicable to make our packages work with the newest angular js applications
JIRA: RAIL-3911
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributin …

RELATED: RAIL-3911 Add es2015 entry in package.jsons

---

libs/sdk-ui-filters/styles/scss/attributeFilter.scss

RELATED: FET-927 Add padding and margin to dropdown controls

---

libs/sdk-ui-all/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-ext/package.json

- Include NOTICE file into sdk-ui-charts dependent packages
JIRA: RAIL-3894
---
--- …

RELATED: RAIL-3894 Include NOTICE files into packages

---

libs/sdk-backend-tiger/src/convertors/fromBackend/UsersConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/user/index.ts

Extend IUser interface by organization name for tiger BE

---

tools/dashboard-plugin-template/README.template.md
tools/dashboard-plugin-template/webpack.config.js

- change localhost to 127.0.0.1
- enable https
JIRA: RAIL-3924
---
--- …

Make plugin boilerplate work in Safari

---

libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectList.tsx

This should fix some tests upstream.
JIRA: RAIL-3932
---
--- …

RELATED: RAIL-3932 Add missing span

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
examples/sdk-examples/src/index.tsx
examples/sdk-examples/src/react-ga.ts

This is the first version compatible with React 17.
Also add missing config and actually import the GA code.
JIRA: FET-529
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tel …

RELATED: FET-529 Upgrade react-ga and make it work

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-filters/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-tests/package.json

This is the first version compatible with React 17.
JIRA: FET-529
---
--- …

RELATED: FET-529 Upgrade react-responsive 8.0.1 -> 8.2.0

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-tests/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

The @gooddata/numberjs@4.0.0 strips [excel] and whatever follows from
metric format.
JIRA: TNT-341
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-nee …

Use latest @gooddata/numberjs library

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Enable FF "enableRenamingMeasureToMetric" in tiger

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-tests/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

Contains a fix for potential null format passed to the library
---
--- …

RELATED: TNT-341 Use latest @gooddata/numberjs library

---

libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx

RELATED: RAIL-3945 Respect the enableSaveAsNewButton

---

libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts

We must apply the plugins in order specified in the plugins
field of dashboards, not in order that they are in the references
(which can be different).
JIRA: RAIL-3949
---
--- …

RELATED: RAIL-3949 Respect order of plugin links when loading them

---

libs/sdk-ui-loaders/src/dashboard/loadingStrategies/determineDashboardEngine.ts

- To make it QA easier (currently, if the engine has alpha version, comparison fails)
- https://github.com/npm/node-semver#prerelease-tags
JIRA: RAIL-3910
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/d …

Plugins versioning - allow alphas in comparison

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

sdk-backend-tiger: enable new KD navigation ff

---

tools/dashboard-plugin-template/README.template.md

Update dashboard plugin template readme about dashboardPluginHosts setup

---

examples/sdk-examples/src/index.tsx
libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/toolkit/paging.ts
libs/sdk-backend-bear/tests/integrated/__snapshots__/dateFilterConfigs.test.ts.snap
libs/sdk-backend-bear/tests/integrated/__snapshots__/elements.test.ts.snap
libs/sdk-backend-bear/tests/integrated/__snapshots__/insights.test.ts.snap
libs/sdk-backend-tiger/tests/integrated/__snapshots__/elements.test.ts.snap
libs/sdk-ui-filters/src/AttributeElements/AttributeElements.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- handle updating selection with data fix
- make paging prototype functions instance functions
JIRA: RAIL-3964, RAIL-3965
---
--- …

RELATED: RAIL-3964 attribute filter issues fix

---

libs/sdk-backend-base/src/customBackend/execution.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-base/src/dummyBackend/tests/index.test.ts
libs/sdk-backend-bear/src/backend/workspace/execution/preparedExecution.ts
libs/sdk-backend-bear/src/backend/workspace/execution/preparedExecutionByRef.ts
libs/sdk-backend-mockingbird/src/legacyRecordedBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/execution.ts
libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
libs/sdk-ui-dashboard/jest.setup.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/removeSectionItemHandler.test.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
tools/catalog-export/__mocks__/@gooddata/api-client-bear.ts

* remove useless awaits
* use Promise shorhands where possible
* properly mark intentionally empty functions or use lodash/noop
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do- …

TRIVIAL: fix some code smells

---

tools/dashboard-plugin-template/README.template.md

Add note about plugin compatibility to plugin boilerplate

---

libs/sdk-ui-dashboard/src/presentation/shareDialog/DefaultShareDialog.tsx

Fix Share Dialog localizations (locale)

---

common/scripts/ci/run_unit_tests.sh
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

FEATURE: MSF-22761 Enable the navigation to Data Section for all tiers

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- refactor prepareElementsQuery function
- add  needsReloadAfterSearch flag to force elements reloading
The `needsReloadAfterSearch` flag simulates the previous value for the `searchString` value. If the search string changes, it will force elements to reload. Implementation of this flag covers some edge case scenarios which resulted in fetching incorrect elements for the current searched value.
JIRA: RAIL-3980
---
--- …

RELATED: RAIL-3980 Fix AttributeFilterButton search issues

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/backend/loadGranteeOptionsPromise.ts
libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

Hotfix missing localized texts

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/backend/loadGranteeOptionsPromise.ts
libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

Fix missing localized texts (master)

---

libs/sdk-ui-filters/src/MeasureValueFilter/DropdownBody.tsx
libs/sdk-ui-filters/src/MeasureValueFilter/tests/MeasureValueFilterDropdown.test.tsx

Apply button in MVF was not disabled correctly for percentage mode.

---

common/scripts/ci/run_unit_tests.sh

The file in common/changes can change often, but they should not
cause the incremental tests to bail out to testing everaything.
Also fix issues reported by shellcheck.
JIRA: FET-955
---
--- …

RELATED: FET-955 Ignore changes files for incremental tests

---

NOTICE
README.md

LR-913: update NOTICE and README

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx

- DashboardComponentsContext ErrorComponent and LoadingComponent props made mandatory
- update components with IDashboardInsightProps
JIRA: RAIL-3979
---
--- …

RELATED: RAIL-3979 Make ErrorComponent and LoadingComponent mandatory

---

libs/sdk-ui-kit/styles/scss/bubble.scss

Date filter help text quick vanish

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/.stylelintrc
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-dashboard/styles/scss/_globals.scss
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-dashboard/styles/scss/filterBar.scss
libs/sdk-ui-dashboard/styles/scss/layout.scss
libs/sdk-ui-dashboard/styles/scss/visualization.scss

The config is the same as in the other packages.
The animations were sourced from gdc-dashboards (same as most of the styles there).
JIRA: FET-964
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/cont …

RELATED: FET-964 Add stylelint to sdk-ui-dashboard

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/accessControl/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/dashboard.ts

Extend their documentation and make it more understandable
---
--- …

RELATED: RAIL-3953 mark some general events as public

---

libs/sdk-backend-tiger/src/backend/organization/index.ts

Fix invalid endpoints after permissions update

---

common/scripts/ci/run_unit_tests.sh

RELATED: FET-955 Enable incremental unit test optimization

---

common/changes/@gooddata/sdk-ui-all/IMJ-TNT-382_2021-12-08-14-14.json
common/changes/@gooddata/sdk-ui-all/list_2021-12-06-11-43.json
common/changes/@gooddata/sdk-ui-all/mkn-rail-3910-validation_2021-12-20-13-57.json
common/changes/@gooddata/sdk-ui-all/mkn-rail-3935-readme_2022-01-19-08-36.json

RELATED: RAIL-3906 Review of the changelog items

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Icon/Icon.tsx
libs/sdk-ui-kit/src/Icon/icons/Minimize.tsx

Will be used inside tab component in metric editor
JIRA: NAS-2986
---
--- …

NAS-2986 - Added minimize icon

---

libs/sdk-backend-spi/src/workspace/dashboards/drillUrls.ts
libs/sdk-backend-spi/src/workspace/dashboards/drills.ts
libs/sdk-backend-spi/src/workspace/dashboards/tests/__snapshots__/drillUrls.test.ts.snap
libs/sdk-backend-spi/src/workspace/dashboards/tests/drillUrls.test.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/DrillToCustomUrlConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v1/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/tests/AnalyticalDashboardConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts
libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts

- allow drills to url
JIRA: NAS-138
---
--- …

RELATED: NAS-138 Split drill url to text and identifier parts

---

examples/sdk-examples/src/App.tsx

Background style of html and body should not respect themes colors

---

libs/api-client-bear/src/user.ts

Fix user module when due to CORS returned error not contain response

---

libs/sdk-backend-tiger/src/backend/organization/index.ts

NAS-2770 - Fix of "Fix invalid endpoints after permissions update"

---

libs/sdk-ui-kit/src/ScrollGradient/hooks/useContentHeight.ts
libs/sdk-ui-kit/src/ScrollGradient/hooks/useScrollEvent.ts
libs/sdk-ui-kit/src/ScrollGradient/tests/ScrollGradient.test.tsx

Repair of scroll gradient, check content scroll height to determine if can render shadow or not
JIRA: NAS-2849
---
--- …

NAS-2849 - Repair of scroll gradient, check content scroll height

---

libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx

- add memo to dashboard component when dashboard prop is string
- separate hooks in Dashboard component
JIRA: RAIL-3978
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-i …

Memo dashboard string id

---

libs/sdk-ui-dashboard/src/presentation/localization/translations.ts

Add Russian to sdk-ui-dashboard intl localizations

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts

JIRA: TNT-403
Change resetZoomButton styling to work with new HCH version. Typings not helpful in this case
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-re …

Update chart config to newer structure after HCH upgrade

---

libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss

Remove line-height: 0 in dashboard widget dash-item-content

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

NAS-3005 - Enable Tiger Workspace Permissions in Meditor, part 1 in sdk

---

common/config/rush/pnpm-lock.yaml

RELATED: FET-974 Upgrade follow-redirects to fix security advisory

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-tests/package.json

RELATED: FET-976 Upgrade testcafe to fix advisory in nanoid

---

common/changes/@gooddata/sdk-ui-all/MAP-RAIL-3989-productize-state-accessing_2022-02-03-07-51.json
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/SingleDashboardStoreAccessor.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/index.ts

RELATED: RAIL-3989 Store accessor for a single dashboard usage

---

libs/sdk-ui-ext/src/internal/translations/ru-RU.json

Use shorter version for russian string

---

libs/sdk-ui-dashboard/src/model/store/storeAccessors/DashboardStoreAccessorRepository.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/SingleDashboardStoreAccessor.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/tests/DashboardStoreAccessorRepository.test.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/tests/SingleDashboardStoreAccessor.test.ts

RELATED: RAIL-3989 Dashboard store accessors fix and tests

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithAccessorSrc.tsx
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/storeAccessors/DashboardStoreAccessorRepository.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/SingleDashboardStoreAccessor.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/tests/DashboardStoreAccessorRepository.test.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/tests/SingleDashboardStoreAccessor.test.ts

RELATED: RAIL-3989 Make accessors all static

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightWidgetDataView.ts

RELATED: RAIL-3987 Update useInsightWidgetDataView TSDoc

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/index.ts

RELATED: RAIL-3986 Export useInsightWidgetDataView hook from sdk-ui-dashboard

---

libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/DrillToCustomUrlConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts

Use immutable functions for drill url transformations

---

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/alignPoints.ts
libs/sdk-ui-dashboard/styles/scss/kpi_alert_dialog.scss

KPI alert close button is hidden with small screen

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithAccessorSrc.tsx
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/storeAccessors/DashboardStoreAccessor.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/DashboardStoreAccessorRepository.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/SingleDashboardStoreAccessor.ts
libs/sdk-ui-dashboard/src/model/store/storeAccessors/tests/DashboardStoreAccessorRepository.test.ts

RELATED: RAIL-3989 Unify accessor api to match the codebase

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

In tiger there is no manage link, instead of manage tiger use metrics link
JIRA: NAS-3008
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approv …

NAS-3008 - Add possibility to turn off manage link event if manage metric is true

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPlugin.tsx
examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx

Add instructions on how to ignore some of the filters.
JIRA: RAIL-3963
---
--- …

RELATED: RAIL-3963 Improve DashboardLocalPluginExample

---

examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommand.tsx
examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithUseDispatchDashboardCommandSrc.tsx
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commands/filters.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/react/useDispatchDashboardCommand.ts

- explain on how to use useDispatchDashboardCommand hook
- make relevant commands public
- update api doc
JIRA: RAIL-3954
---
--- …

RELATED: RAIL-3954 Expose filter changing commands as public

---

libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts

RELATED: NAS-140 Turn off relation validation for dashboards

---

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx

RELATED: RAIL-4017 Handle dateFilterMode: hidden in Dashboard

---

tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts

RELATED: NAS-140 Turn off relation validation for dashboards in catalog export
