gooddata/gooddata-ui-sdk

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-charts/package.json

This version fixes a regression in 1.1.5 of the package
which broke the charts in certain situations.
The reason the SDK7 version worked is that it used version 1.1.3
without the bug.
JIRA: RAIL-2522
---
---
-   [x] commit messages adhere to the [commit message guidelines](docs/contributing.md#what-should-the-commits-look-like)

RELATED: RAIL-2522 upgrade highcharts-grouped-categories to 1.1.6

---

libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/result.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/dateValueFormatter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/dateValueParser.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/tests/dateValueFormatter.test.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/types.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateGranularityConversions.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/base/dateGranularities.ts
libs/sdk-model/src/execution/filter/factory.ts
libs/sdk-model/src/execution/filter/index.ts
libs/sdk-model/src/execution/filter/tests/__snapshots__/factory.test.ts.snap
libs/sdk-model/src/execution/filter/tests/factory.test.ts
libs/sdk-model/src/execution/filter/tests/typeGuards.test.ts
libs/sdk-model/src/index.ts
libs/sdk-model/src/ldm/catalog/dateDataset/factory.ts
libs/sdk-model/src/ldm/catalog/dateDataset/index.ts
libs/sdk-model/src/ldm/catalog/index.ts

Establish DateAttributeGranularity type with all possible granularities. Use this in relative attribute filter.
---
---

RELATED: RAIL-1815 - Refine relative date attribute type

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

Make sure that the initialization continues with the received data
only if the data is still valid, i.e. for the same execution definition
the initialize was last called with.
JIRA: RAIL-2562
---
---

RELATED: RAIL-2562 stop pivot table initialize if data is no longer valid

---

.github/pull_request_template.md
docs/sdk-dev.md

This provides an alternative to yarn link for local testing of the SDK.
---
---

TRIVIAL: fix PR template links, add rsync docs to sdk-dev

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/common.ts
libs/sdk-embedding/src/index.ts
libs/sdk-embedding/src/internal.ts
libs/sdk-embedding/src/internal/filterConvertors.ts
libs/sdk-embedding/src/internal/messagingUtils.ts
libs/sdk-embedding/src/internal/tests/filterUtils.test.ts
libs/sdk-embedding/src/internal/tests/messagingUtils.test.ts
libs/sdk-embedding/tsconfig.build.json
libs/sdk-embedding/tsconfig.dev.json

Filter definitions were wrong
Also need to move filter conversion logic from js-utils to here
---
---

RELATED: RAIL-2107 - Fix up sdk-embedding

---

libs/sdk-ui-ext/src/internal/components/VisualizationCatalog.ts
libs/sdk-ui-ext/src/internal/components/tests/VisualizationCatalog.test.ts

These functions return a boolean flag indicating
that a given visualiuzation class is supported.
JIRA: RAIL-2569
---
---

RELATED: RAIL-2569 add support indicating functions to IVisualizationCatalog

---

libs/sdk-backend-bear/src/backend/workspace/metadata/index.ts
libs/sdk-backend-bear/src/backend/workspace/metadata/measureExpressionTokens.ts
libs/sdk-backend-bear/src/backend/workspace/metadata/test/measureExpressionTokens.test.ts
libs/sdk-backend-tiger/src/backend/workspace/metadata/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/ldm/measure.ts

* RAIL-2107: Include refs in IObjectExpressionToken This allows the users to refer to the token objects from their apps.
* RAIL-2577: Fix too greedy identifier RegExp in bear MAQL tokenizer
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-change …

RELATED: RAIL-2107,RAIL-2577 include refs in IObjectExpressionToken, fix bear tokenizer

---

libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/CustomFormatDialog.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/formatTemplatesDropdown/DropdownItem.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/formatTemplatesDropdown/FormatTemplatesDropdown.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/previewSection/Preview.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/shared/FormattedPreview.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/shared/PreviewRows.tsx
libs/sdk-ui-kit/src/measureNumberFormat/customFormatDialog/shared/tests/FormattedPreview.test.tsx
libs/sdk-ui-kit/src/measureNumberFormat/presetsDropdown/PresetsDropdown.tsx
libs/sdk-ui-kit/styles/scss/measureNumberFormat.scss

- no cross icon for closing the dialog - it is closed on outside click
- fixed alignment of templates dropdown and information bubbles
Co-authored-by: Jan Strouhal <strouhaljan@users.noreply.github.com>
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-f …

RELATED: BB-2304 upgrade GoodStrap, style fixes

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx

-  Code did not reflect a fix from some time back which removed the double-wrap of properties
---
---

BUGFIX: RAIL-2605 - Fix column width sanitization

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts

BUGFIX: SD-582 Child label is disappeared when change rotation Y-axis to 90° on Bar chart

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/insight/index.ts
libs/sdk-model/src/insight/tests/insight.test.ts
libs/sdk-ui/src/base/measureTitles/ignoreTitlesForSimpleMeasures.ts

BUGFIX: SD-1045 Metric name is shown as localIdentifier in KD if insight has local date filter

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/base/sort.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-pivot/src/impl/agGridDataSource.ts
libs/sdk-ui/src/base/results/internal/resultMetaMethods.ts
libs/sdk-ui/src/base/results/internal/test/__snapshots__/resultMetaMethods.test.ts.snap
libs/sdk-ui/src/base/results/internal/test/resultMetaMethods.test.ts

-  Measure sorts with attribute locators may end-up ineffective if
the table is filtered to not show the attribute element which is
used in the attribute locator
-  No problem for the backend & the rest of pivot table impl
-  However datasource checks (during reload) whether current sorts match the
sorts on the backend;
-  This is problematic, because table knows that it is not sorted by the
missing column, yet the data source looks at the definition sorts that
contain the sort items - it determines that result transformation and
redrive of execution is needed.
-  This is both unnecessary & leads to problems with resizing which is
prone to racy behavior
-  Note: tried quick fix to trigger resizing after onModelUpdated - but this
does not solve the problem 100%. some tables get good, but …

RELATED: RAIL-2579 - Fix ag-grid data source to correctly recognize effective sorts

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

Makes sure applyColumnSizes does not crash when called with no visible data.
Also, the typings in CorePivotTable were made more precise
to indicate fields that can be null explicitly.
JIRA: RAIL-2610
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for- …

RELATED: RAIL-2610 make applyColumnSizes robust, improve typings

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
libs/sdk-backend-base/package.json
libs/sdk-ui-ext/package.json

lru-cache > 4 is not compatible with IE 11 (it uses yallist > 2 which uses generators).
JIRA: RAIL-2608
---
---

RELATED: RAIL-2608 downgrade lru-cache to restore IE 11 compatibility

---

libs/sdk-backend-bear/src/backend/workspace/insights/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/insights.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/insights/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
libs/sdk-backend-tiger/src/convertors/toBackend/ObjRefConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/objRef/index.ts
libs/sdk-ui-ext/src/insightView/tests/dataLoaders.test.ts

Add new API for getting insight used on dashboards
JIRA: [SD-1054](https://jira.intgdc.com/browse/SD-1054)
---
---

RELATED: SD-1054 add API for getting used analytical dashboard by useBy2

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/tests/CorePivotTable.test.tsx
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx
libs/sdk-ui/src/base/vis/Events.ts

Similarly as with pivot table, charts report attributes in available drill targets.
Dimension is no longer provided with the attribute as it is already filtered on sdk side.
JIRA: ONE-4598
Related: https://github.com/gooddata/gdc-dashboards/pull/3138
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/doc …

RELATED: ONE-4598 sdk-ui: charts report drillable attributes

---

libs/sdk-backend-bear/src/backend/index.ts

This is to support embedding in Bear.
JIRA: RAIL-2620
---
---

RELATED RAIL-2620 add getVisualizationObject legacy function

---

libs/sdk-ui-charts/src/charts/xirr/internal/XirrTransformation.tsx

https://jira.intgdc.com/browse/RAIL-2596
---
---

BUGFIX: RAIL-2596 - Fix `this` binding in XirrTransformation

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

Bumps goodstrap and fixed-data-table-2 so that only one version of fixed-data-table-2 is used.
JIRA: RAIL-2107
---
---

RELATED: RAIL-2107 bump fixed-data-table-2 and goodstrap

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/agGridDataSource.ts
libs/sdk-ui-pivot/src/impl/agGridTypes.ts

The fixEmptyHeaderItems was only called on init but not
on subsequent loads. The dataViewTransform hook was added
that allows transforming the dataView when it is loaded in datasource.
JIRA: RAIL-2623
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for …

RELATED: RAIL-2623 fix empty value handling in PivotTable

---

libs/sdk-ui-charts/src/charts/xirr/internal/utils/XirrTransformationUtils.ts
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

RAIL-2626: prevents null reference in XIRR computation
RAIL-2625: removes unnecessary if in withEntireDataView.onError
---
---

RELATED: RAIL-2625, RAIL-2625 small fixes in XIRR and withEntireDataView

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx

This is because AD cannot recover it in certain cases.
JIRA: RAIL-2625
---
---

RELATED: RAIL-2625 unmount PluggableHeadline on error

---

libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx

We need to check for strict equality in isSameData in cases
there are the same measures but in different buckets.
JIRA: RAIL-2629
---
---

RELATED: RAIL-2629 relax shouldComponentUpdate in GeoValidator

---

libs/sdk-backend-base/src/normalizingBackend/normalizer.ts
libs/sdk-backend-base/src/normalizingBackend/tests/normalizer.test.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/measure/factory.ts
libs/sdk-model/src/execution/measure/tests/__snapshots__/factory.test.ts.snap
libs/sdk-model/src/execution/measure/tests/factory.test.ts
libs/sdk-model/src/index.ts

The PR fixes the bug and adds extra modifyPreviousPeriodMeasure function to sdk-model + additional tests to sdk-model.
---
---

RELATED: RAIL-2631 - Fix normalization bug where localIds are not assigned correctly

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/execution/results.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/dimensions.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/result.ts
libs/sdk-backend-tiger/src/index.ts

This then makes denormalizer not match header item with the actual measure name to use.
---
---

RELATED: RAIL-2560 - Fix bug where tiger backend returns invalid measure descriptors and headers

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/user/GdcUser.ts

There are two new optional pieces of information in /gdc/app/account/bootstrap response: clientId and dataProductId.
---
---

RELATED: BB-2443 /gdc/app/account/bootstrap response extension

---

libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketRules.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketHelper.test.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketRules.test.ts
libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/baseChartUiConfigHelper.ts

Show in % should not be available in bucket item configuration and in recommendations when measure value filter on derived measure is present in the insight.
---
---

Restrict Show in % when MVF on derived is present

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui/src/base/errors/errorHandling.ts
tools/catalog-export/src/transform/toTypescript.ts

The problem was twofold:
* InsightView did not stop loading on error
* error mapping for DATA_TOO_LARGE_TO_COMPUTE was missing
Also, while testing, I discovered an error in catalog export where eslint would
complain about missing rule definition so I disabled the eslint
as a whole in the generated files.
JIRA: RAIL-2607
---
--- …

RELATED: RAIL-2607 fix error handling in InsightView, improve catalog export

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

We need a zIndex on it, otherwise the first cell of  the first row/column
will show over the loading overlay during resizing.
JIRA: RAIL-2641
---
---

RELATED: RAIL-2641 improve loading overlay in CorePivotTable

---

libs/sdk-backend-tiger/src/convertors/toBackend/ObjRefConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/filter/factory.ts
libs/sdk-model/src/execution/filter/index.ts

-  This was removed because of mis-understanding in Tiger behavior. idRefs on tiger
require type.
-  Before RAIL-2485: we had defaulting in place if type is not specified by user. for MVF, tiger conversion was defaulting
to 'metric'; which works ok if the id is actually for metric. But for facts, this would not work - resulting in
the QA reported 400s
-  After RAIL-2485: idRef was removed as option. even if it is supported by both bear and tiger
-  Now: idRef is restored. bear can accept it, tiger does conversion and will blow up if the type is not specified.
JIRA: BB-2494
---
---
-   [ ] …

RELATED: BB-2494 - Restore ability to specify MVF using full ObjRef

---

libs/sdk-ui/src/base/errors/errorHandling.ts

Now it returns a generic "Sorry, we can't display this insight" message
for 400 response errors.
JIRA: RAIL-2607
---
---

RELATED: RAIL-2607 improve BadRequest error handling

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/base.ts
libs/api-client-tiger/src/generated/afm-rest-api/configuration.ts
libs/api-client-tiger/src/generated/afm-rest-api/index.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/base.ts
libs/api-client-tiger/src/generated/metadata-json-api/configuration.ts
libs/api-client-tiger/src/generated/metadata-json-api/index.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AnalyticalDashboardConverter.ts

Just to validate the new backend support for analyticalDashboard objects.
Includes update of api-client-tiger from latest gdc-nas/master.
---
---

ONE-4623: Minimalistic dashboards support (get all)

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

We must not mutate the buckets as it can have unexpected consequences.
JIRA: RAIL-2647
---
---

RELATED: RAIL-2647 prevent buckets mutation in GeoChart

---

examples/sdk-examples/src/examples/advanced/parentFilter/ParentFilterExample.tsx

RAIL-2645: prevent null reference
RAIL-2653: do not show picker items when loading
---
---

RELATED: RAIL-2645, RAIL-2653 small fixes to ParentChildExample

---

libs/sdk-ui-tests/backstop/run-backstop.sh

Version 5.0.4 had a bug with missing library libXss.so.1 ([details](https://github.com/garris/BackstopJS/issues/1225))
This was fixed in 5.0.6.
---
---

RELATED: RAIL-1815 upgrade backstop docker image 5.0.4 -> 5.0.6

---

examples/sdk-examples/src/examples/arithmeticMeasures/ArithmeticMeasureDrillingExample.tsx
examples/sdk-examples/src/examples/arithmeticMeasures/ArithmeticMeasureMultiplicationExample.tsx
examples/sdk-examples/src/examples/arithmeticMeasures/ArithmeticMeasureRatioExample.tsx
examples/sdk-examples/src/examples/arithmeticMeasures/ArithmeticMeasureSumExample.tsx
examples/sdk-examples/src/examples/drill/DrillWithExternalDataExample.tsx
examples/sdk-examples/src/examples/drill/EmployeeProfile.tsx
examples/sdk-examples/src/examples/drill/PivotTableDrillExample.tsx
examples/sdk-examples/src/examples/hidden/pivotTableDynamic/PivotTableDynamicExample.tsx
examples/sdk-examples/src/examples/hidden/pivotTableSizing/PivotTableSizingComplexExample.tsx
examples/sdk-examples/src/examples/insightView/InsightViewComboChartByIdentifierExample.tsx
examples/sdk-examples/src/examples/pivotTable/PivotTableDrillExample.tsx
examples/sdk-examples/src/examples/pivotTable/PivotTableManualResizingExample.tsx
examples/sdk-examples/src/ldm/ext.ts

* RAIL-2652: Fix styles in ComboChart InsightView example
* RAIL-2655: Improve Arithmetic measure examples - inlined the defintions (so that the sample source code is useful on its own), made sure the data is meaningful with no zeroes
* RAIL-2659: Fxed DrillingWithExternalData - re-renders, broken drilling, missing style, messy code
---
---
-   [ ] `rush …

RELATED: RAIL-2652, RAIL-2655, RAIL-2659 example improvements

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/dateValueParser.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateFormatting/defaultDateFormatter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateGranularityConversions.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/base/dateGranularities.ts

Only into Tiger backend
JIRA: RAIL-2651
Add hour / minute chronological granularities
- YYYY-MM-DD HH24
- YYYY-MM-DD HH24:MI
Add hour / minute periodical granularities
- hour in day - 00-23
- minute in hour - 00-59

RELATED: RAIL-2651 add hour and minute date granularities

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/drill/index.tsx
examples/sdk-examples/src/examples/execution/ExecuteWithCustomVisualizationExample.tsx
examples/sdk-examples/src/examples/execution/index.tsx
examples/sdk-examples/src/examples/measureValueFilter/measureValueFilterComponent/MeasureValueFilterTreatNullAsZeroComponentExample.tsx
examples/sdk-examples/src/examples/measureValueFilter/measureValueFilterComponent/index.tsx
examples/sdk-examples/src/examples/sorting/DynamicSortingExample.tsx
examples/sdk-examples/src/ldm/ext.ts

There were some examples present in SDK7 examples missing here
- MeasureValueFilter with treat as zero
- Custom Visualization with recharts
Also existing examples were improved
- Missing show code button was added to GeoPushpinDrilling example
- Dynamic sorting examples' wording and UX was improved
---
--- …

RELATED: RAIL-2654, RAIL-2658 add missing examples

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/getInsightWithDrillDownAppliedMock.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/drillDownUtil.test.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/testHelpers.ts
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/utils/ImplicitDrillDownHelper.ts

- by convention, the drill types use `target` field to define the place for drilling (modal, new window, new tab...)
---
---

Rename `IImplicitDrillDown.target` to `IImplicitDrillDown.drillDownStep`

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/getInsightWithDrillDownAppliedMock.ts

- include intersection filters when applying Drill Down in the PluggablePivotTable
JIRA: ONE-4654
---
---

Fix Drill Down filters in the PluggablePivotTable

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx

We only want to change the legend position if a dimension
is specified in Dashboards.
JIRA: RAIL-2662
---
---

RELATED: RAIL-2662 fix legend positioning logic

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/PluggableColumnBarCharts.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/getInsightWithDrillDownAppliedMock.ts

- properly call the returned predicate
JIRA: ONE-4624
---
---

Fix the STACK bucket check in PluggableColumnBarCharts

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/geoChartTooltip.ts

Fix "Click the chart to drill" in GEO only when is drillable

---

libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketRules.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketRules.test.ts

Using percentage in measure config should not be allowed when ranking filter is in filter buckets.
JIRA: BB-2568
---
---

FEATURE: BB-2568 Disable show in percent when ranking filter is used

---

libs/sdk-ui-geo/api/sdk-ui-geo.api.md
libs/sdk-ui-geo/src/GeoChart.ts
libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/constants/geoChart.ts
libs/sdk-ui-tests/scenarios/geo/base.tsx
libs/sdk-ui-tests/tests/api-regression/geo/__snapshots__/geoPushpin.test.tsx.snap

Improve storybook for geo chart
- Add config showLabels with default value is true for geo chart
- ShowLabels config will be not public
- Mapbox API is unstable for sometime, almost cases is about label changes, so for storybook we will hidden the label to make it is more stable
Note:
I tested locally that stuff works as expected
Also update for SDK7 too, see at https://github.com/gooddata/gooddata-react-components/pull/1766
---
---
-   [x] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-c …

RELATED: SD-1113 add showLabels in config geo chart and use for storybook

---

libs/sdk-ui-filters/src/RankingFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/RankingFilter/MeasureDropdown/MeasureDropdown.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/RankingFilterDropdown.test.tsx
libs/sdk-ui-filters/src/RankingFilter/tests/fragments/RankingFilterDropdown.tsx

Call onDropDownItemMouseOut when Attribute/Measure dropdown item is selected.
JIRA: BB-2575
---
---

BUGFIX: BB-2575 Remove highlight on item select

---

libs/sdk-backend-bear/src/backend/workspace/insights/filterMerging.ts
libs/sdk-backend-bear/src/backend/workspace/insights/tests/filterMerging.test.ts

It is possible to append filters even if one of them is ranking filter. Previously the exception was thrown. The merge function allows to have multiple ranking filters in the insight as this is legal according to backend.
JIRA: BB-2582
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …

Add logic for ranking filter merging

---

examples/sdk-examples/README.md
examples/sdk-examples/src/examples/rankingFilter/RankingFilterCustomButtonExample.tsx
examples/sdk-examples/src/examples/rankingFilter/RankingFilterExample.tsx

- Make filter optional
- Close ranking filter when it is applied from custom button managed dropdown
- Use valid measures that can have ranking applied (Franchise fees thrown error)
- Fix wrong instructions in readme
JIRA: BB-2584
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#ho …

Update ranking filter examples

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/getInsightWithDrillDownAppliedMock.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/getInsightWithDrillDownAppliedMock.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/getInsightWithDrillDownAppliedMock.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/drillDownUtil.test.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/reverseAndTrimIntersectionMock.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/PluggableTreemap.tsx

- line chart, area chart and treemap should use the same logic when
generating filters from intersection
- for the generated drill down `IInsight` taget, only the outer attributes
should be included in filters
JIRA: ONE-4624
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i …

Cut and reverse drill down intersection

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/kd.ts

Add schedule emailing type for KD:
- When KD is currently viewing dashboard, this will trigger openScheduleEmailDialog, On success ScheduleEmailDialogOpened will be posted
- When KD is currently editing dashboard or is not currently showing any dashboard or schedule email dialog is opened, CommandFailed will be posted
---
---
-   [x] `rush change` [was run if …

FEATURE: SD-1130 add type for email schedule in sdk embedding on KD

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/scripts/generate.js
libs/api-client-tiger/src/execution.ts
libs/api-client-tiger/src/gd-tiger-model/ExecuteAFM.ts
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/validObjects.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/backend/workspace/elements/index.ts
libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/toAfmResultSpec.ts

Applies for original:
```
/api/afm
/api/result
/api/validObjects
/api/labelElements
```
See individual commits for the specific changes.
OpenAPI is updated according to latest state (with new APIs only, not keeping the backward compatible ones).
afm/result are not yet using the generated OpenAPI definitions, the other 2 yes
---
---
-   [ ] `rush change` [was …

RAIL-2691: All AFM usecases migrated to new workspaces specific API

---

examples/sdk-examples/src/examples/advanced/parentFilter/ParentFilterExample.tsx

This avoids the posibility to create a filter cobination yielding NO_DATA.
JIRA: RAIL-2653
---
---

RELATED: RAIL-2653 clear child filters on parent filters change in examples

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/executeAfm/GdcExecuteAFM.ts
libs/api-model-bear/src/executeAfm/tests/GdcExecuteAFM.fixtures.ts
libs/api-model-bear/src/executeAfm/tests/GdcExecuteAFM.test.ts
libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/package.json
libs/sdk-embedding/src/iframe/ad.ts
libs/sdk-embedding/src/iframe/common.ts
libs/sdk-embedding/src/internal/filterConvertors.ts
libs/sdk-embedding/src/internal/tests/filterConvertors.test.ts

- Added ranking filter to setFilterContext API for AD
JIRA: BB-2497
---
---

Add ranking filter to postmessages api

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts

- Fixed in sdk 7.x but missing in 8.x
https://github.com/gooddata/gooddata-react-components/pull/1412/files#diff-c82cb1765ceb81a02895181091005e69L564
---
---

RELATED: ONE-4678 Fix chart data label style when drilling is active

---

libs/sdk-ui-charts/src/highcharts/chart/chartOptionsBuilder.ts

This reverts commit ea85d2bb87b677caa75abd416e38e34c54da3357.
---
---

Revert "Show single point in series despite dataPoints.visible set to false"

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Form/InputWithNumberFormat.tsx
libs/sdk-ui-kit/styles/scss/button.scss

Fixes prop types of Input component
Disables customization for dropdown button
---
---

RELATED: ONE-4642 ONE-4639 Input props and dropdown button customization turned off

---

libs/sdk-backend-bear/src/backend/workspace/insights/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/insights/index.ts

There are cases where you need even the deprecated classes,
for example to display an insight saved before the deprecation of that class.
Also, getInsights needs to use this option in case some of the insights
use deprecated visClasses.
JIRA: RAIL-2724
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/d …

RELATED: RAIL-2724 allow to include deprecated items in getVisualizationClasses

---

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-filters/styles/scss/measureValueFilter.scss
libs/sdk-ui-filters/styles/scss/rankingFilter.scss
libs/sdk-ui-kit/styles/scss/Button/_variables.scss
libs/sdk-ui-kit/styles/scss/Datepicker/_variables.scss
libs/sdk-ui-kit/styles/scss/Form/_variables.scss
libs/sdk-ui-kit/styles/scss/MeasureNumberFormat/_variables.scss
libs/sdk-ui-kit/styles/scss/datepicker.scss
libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-kit/styles/scss/measureNumberFormat.scss
libs/sdk-ui-kit/styles/scss/syntaxHighlightingInput.scss
libs/sdk-ui-kit/styles/scss/variables.scss
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

JIRA: ONE-4642
Simplified color variable naming
Customizable primary color in al ui-sdk components (except charts)
---
---

All ui-sdk components with customizable primary color

---

common/scripts/ci/do_publish.sh
common/scripts/ci/run_major_release.sh
common/scripts/ci/run_minor_release.sh
common/scripts/ci/run_prerelease.sh
common/scripts/ci/run_prerelease_switch.sh

-  Only minor and major releases are tagged as 'latest'
-  All types of prereleases are tagged as 'prerelease'
-  Shotgun attempt to fix abrupt halt in CI release script execution
JIRA: RAIL-2711
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the- …

RELATED: RAIL-2711 - Update release scripts to correctly add NPM tags

---

libs/sdk-ui-charts/src/highcharts/chart/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chart/highcharts/test/customConfiguration.test.ts
libs/sdk-ui-charts/src/highcharts/chart/test/HighChartsRenderer.test.tsx
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts

Add a support property:
- Adding the 'chart' property into the supportedProperties file.
- It helps we keep the chart config for the HighCharts to support zooming and panning.
JIRA: SD-1100
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-change …

RELATED: SD-1100 - implementing the zooming/panning in HighCharts

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.test.tsx

This makes the detection idiomatic (similar to `PluggableBaseChart`) and removes a side effect in its `getExtendedReferencePoint`.
Also removes the `AbstractPluggableVisualization.setIsError` methond which is no longer used (and should not ever be).
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs …

RELATED: RAIL-2732 fix PluggableBulletChart primary measure detection

---

common/config/rush/pnpm-lock.yaml
libs/api-client-bear/package.json

- remove not needed @types/md5 dependency in api-client-bear
- remove obsolete mentions of prop-types and @types/prop-types
- run rush update --recheck
This had to be done so that tooling working on pnpm lock worked
(there were entries for already removed dependencies).
---
--- …

RELATED: RAIL-1815 clean up dependencies

---

common/changes/@gooddata/sdk-ui-all/anvuong-sd1107_2020-10-08-11-57.json
libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/ldm/catalog/attribute/factory.ts
libs/sdk-model/src/ldm/catalog/attribute/index.ts

Fix AD Insights are broken after change of default label

---

libs/sdk-embedding/src/internal.ts
libs/sdk-embedding/src/internal/index.ts
libs/sdk-embedding/tsconfig.build.json
libs/sdk-ui-ext/src/internal/index.ts

- make sdk-embedding use a barrel file in internal
- extends sdk-ui-ext barrel file with things needed outside
This is the first step to tree-shaking - we need to have explicit entry points:
- index
- optionally, internal/index
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …

RELATED: RAIL-1815 cleanup "internal" exports

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-kit/src/Timepicker/index.ts
libs/sdk-ui-tests/stories/visual-regression/kit/Timepicker/Timepicker.tsx

FIX: ONE-4642 Timepicker fix export naming

---

libs/sdk-ui-pivot/src/impl/agGridColumnSizing.ts

- some browsers do not return the computed style `font` field (this includes Firefox, EdgeHTML based Edge, or MSIE 11)
- when the `font` is empty, we should construct the property from individual styles
- only `weight`, `size` and `face` is combined, as more advanced properties may casue issues in Edge and MSIE
JIRA: ONE-4491
---
---
-   [ ] `rush change` [was …

BUGFIX: ONE-4491 Fix empty font style in sdk-ui-pivot

---

libs/sdk-ui-charts/src/highcharts/chart/highcharts/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chart/highcharts/test/customConfiguration.test.ts

Enable the animation for Highcharts when the zoomInsight is enabled:
_ The chart animation is disabled by default. It should be enabled when the zooming feature is enabled.
JIRA: SD-1187
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog …

RELATED: SD-1100 - enable the animation for Highcharts when the zoomInsight is enabled

---

libs/sdk-backend-bear/src/convertors/toBackend/afm/MeasureConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/MeasureConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/__snapshots__/MeasureConverter.test.ts.snap

When implementing custom measure format we found out that some measures have incorrect format saved in viz. object. As we started to respect the format saved in viz. object the measures would be formatted wrongly so we introduced this fix for them. These viz. objects have been fixed so that the override is not needed any more
---
---
-   [ ] `rush change` [was …

Remove temporary measure format override

---

libs/sdk-ui-kit/styles/scss/Button/_variables.scss

Fix button dropShadow and textCapitalization css variables to match MD theme object ones
---
---

RELATED: ONE-4711: fix dropShadow and textCapitalization css var

---

libs/sdk-ui-theme-provider/src/cssProperties.ts

JIRA: ONE-4642
Added forgotten derivation of primary color used in AD
---
---

RELATED: ONE-4642 Adds another dimmed primary color

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/agGridColumnSizing.ts

RELATED: ONE-4693 Add the missing condition when autoresizedColumns do not exist

---

common/scripts/ci/run_major_release.sh
common/scripts/ci/run_minor_release.sh
common/scripts/ci/run_prerelease.sh
common/scripts/ci/run_prerelease_fix.sh
common/scripts/ci/run_prerelease_switch.sh
common/scripts/ci/run_release_examples.sh

They need to run build-all to include both esm and cjs versions.
---
---

RELATED: RAIL-1815 fix release scripts

---

common/changes/@gooddata/sdk-ui-all/RAIL-2317_2020-10-20-10-06.json
examples/sdk-examples/src/examples/execution/UseDataViewAttributeValuesExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewWithCustomVisualizationExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewWithSlicesExample.tsx
examples/sdk-examples/src/examples/execution/index.tsx
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/CancelablePromise.ts
libs/sdk-ui/src/base/react/useCancelablePromise.ts
libs/sdk-ui/src/execution/Execute.tsx
libs/sdk-ui/src/execution/createExecution.ts
libs/sdk-ui/src/execution/index.ts
libs/sdk-ui/src/execution/tests/Execute.test.tsx
libs/sdk-ui/src/execution/useDataExport.ts
libs/sdk-ui/src/execution/useDataView.ts
libs/sdk-ui/src/execution/useExecution.ts

Goal of this PR is to provide hooks alternative for our public HOCs, which should be easier to understand and compose.
- added useCancelablePromise hook (solves Promise race conditions in useEffect and provides convenient callbacks)
- added useExecution hook to simplify execution creation and backend/workspace injecting
- added useDataView hook to make custom visualisations creation easier
- added useDataExport hook to make data export easier
Mapping for HOCs & hooks is not 1:1, because I wanted to make usage for users easier.
JIRA: RAIL-2317
---
--- …

RELATED: RAIL-1815 Add hooks alternative for public HOCs

---

docs/setupIntellij.md
docs/setupVsCode.md
examples/sdk-examples/webpack.config.js
tools/applink/src/devConsole/pipeline/publisher.ts

* Make sure examples use esm builds primarily (so rush build works)
* Fix path in applink rsync
* Update setup documentation
---
---

RELATED: RAIL-1815 improve new build process DX

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-ui-ext/package.json
libs/sdk-ui-ext/src/dashboardEmbedding/index.ts
libs/sdk-ui-ext/src/dashboardEmbedding/useDashboard.ts
libs/sdk-ui-ext/src/dashboardEmbedding/useDashboardAlerts.ts
libs/sdk-ui-ext/src/index.ts

Also, a necessary backend endpoint was added to get alerts only relevant to a given dashboard for current user.
---
---

RELATED: RAIL-2754, RAIL-2761 add hooks for getting dashboard and dashboard alerts

---

libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/tests/cssProperties.test.ts

ThemeProvider renders the children component without invariant when workspace or backend is missing.
JIRA: ONE-4732
---
---

Handling missing workspace and be in ThemeProvider

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

This makes sure we do not depend on obsolete rxjs version
and do not pollute users' bundles with it.
See https://github.com/gooddata/gdc-goodstrap/pull/1114 for details.
---
--- …

RELATED: RAIL-1815 bump goodstrap to rxjs v6 version

---

libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui-kit/styles/scss/header.scss

AppHeader navigation won't use custom fonts
Update DateRangeFilter to use custom fonts
---
---

RELATED: ONE-4714, ONE-4715: AD/KD use normal font on `Header` and update DateRangePicker to use customize font

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts

Improve the zoom level logic:
_ Should not set the minRange for X-Axis when the data categories less than 2.
JIRA: SD-1187
---
---

RELATED: SD-1187 - Should not set the minRange for X-Axis when the data categories less than 2.

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-theme-provider/src/cssProperties.ts

Custom styles for Widget in KD
- Add custom kpiDashboard keys on Theme Loader 
-  borderWidth, borderRadius, dropShadow
- Remove derived kpiDashboard color 
JIRA: ONE-4647 
Update kpiDashboards metadata theme object
- Rename MD theme object kpiDashboard to `title`
JIRA: ONE-4647
---
--- …

RELATED: ONE-4647 Custom styles for Widget in KD

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx

Now even values outside of default ranges work properly.
JIRA: RAIL-2710
---
---

RELATED: RAIL-2710 fix relative date filter handling on reopen

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartOptionsWrapper.tsx

RELATED: RAIL-2769 prevent double parens for empty values in GeoChart

---

libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/constants/platform.ts

Now that the dateFormat is optional, we need to provide a default,
otherwise the parsing produces unexpected results.
JIRA: SD-1180
---
---

RELATED: SD-1180 add missing default dateFormat to Datepicker

---

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePickerInputField.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx

Moment.js does not parse dates lower than 1900, but date-fns do.
To retain the UX we had to add an extra condition (see code).
JIRA: SD-1180
---
---

RELATED: SD-1180 fix date parsing in date pickers

---

libs/sdk-backend-mockingbird/api/sdk-backend-mockingbird.api.md
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/types.ts
libs/sdk-ui-theme-provider/package.json
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

ThemeProvider skips theme loading when workspace or backend is missing.
JIRA: ONE-4732
Already reviewed while merging to fix branch: https://github.com/gooddata/gooddata-ui-sdk/pull/764
---
--- …

RELATED: ONE-4732 Handling missing workspace and be in ThemeProvider

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/kd.ts

- Add typing for opening delete dashboard dialog on KD
---
---

RELATED: SD-1220 Add type for opening delete dashboard dialog on KD

---

libs/sdk-ui-filters/src/MeasureValueFilter/DropdownBody.tsx
libs/sdk-ui-filters/src/MeasureValueFilter/tests/MeasureValueFilterDropdown.test.tsx
libs/sdk-ui-filters/src/MeasureValueFilter/tests/fragments/MeasureValueFilterDropdown.tsx

Fixed problem when empty measure filter with percentage value displayed NaN in
input.
JIRA: BB-2649
---
---

Fix measure value filter percentage NaN

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/helpers.ts

A javascript error exception when checking autohideLabels after zooming the charts:
_ Some data points are undefined that cause of the issue. So we should filter the valid data points.
Jira: SD-1245
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-t …

BUGFIX: SD-1245 - Zooming behaves incorrectly

---

libs/sdk-ui-kit/styles/scss/dialog.scss
libs/sdk-ui-kit/styles/scss/overlay.scss

- Add style to reset dropdown overlay padding
JIRA: ONE-4760
---
---

Fix redundant padding of RF dropdown component

---

examples/sdk-examples/src/constants/customTheme.ts
examples/sdk-examples/src/constants/routes.ts
examples/sdk-examples/src/examples/rankingFilter/RankingFilterExample.tsx
examples/sdk-examples/src/examples/theming/ThemedComponentsExample.tsx
examples/sdk-examples/src/examples/theming/index.tsx
libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

JIRA: ONE-4768
Extend LiveExamples by ThemeProvider and some themed components example. Using externally provided theme instead of loading one from workspace as we don't want to use theming on whole workspace to keep current state intact
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributin …

RELATED: ONE-4768 LiveExamples extended by ThemeProvider

---

libs/sdk-embedding/package.json
libs/sdk-ui-ext/tsconfig.dev.json

* There is a top-level assignment in messagingUtils.ts so we need to mark it as having a side effect.
* FET-505: fix `rushx dev` in sdk-ui-ext
---
---

RELATED: FET-505: fix rushx dev in sdk-ui-ext, mark sideEffects in sdk-embedding

---

examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_DDMMYYYY.tsx
examples/sdk-examples/src/examples/internationalDateFormat/dateFilter/DateFilterWithColumnChartExample_MDYY.tsx

RELATED: SD-1173 Make date filter's custom filter name to be fully visible in SDK example

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/adapter/test/HighChartsRenderer.test.tsx
libs/sdk-ui-charts/styles/scss/charts.scss

Improve dashboard zooming:
_ Using GoodStrap tooltip for the reset zoom button
JIRA: SD-1214
---
---

RELATED: SD-1214 - Should have a tooltip for Reset zoom icon on KD page

---

common/config/dep-cruiser/default.config.js
examples/sdk-examples/src/examples/hidden/multipleDomains/MultipleDomainsExample.jsx
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-ui-kit/src/List/InvertableList.tsx
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts
tools/applink/src/base/dependencyGraph.ts
tools/applink/src/base/sourceDiscovery.ts
tools/applink/src/devConsole/pipeline/buildScheduler.ts
tools/applink/src/devConsole/pipeline/changeDetector.ts
tools/applink/src/devConsole/ui/packageList.ts
tools/catalog-export/package.json
tools/catalog-export/src/base/config.ts
tools/catalog-export/src/base/types.ts
tools/catalog-export/src/loaders/bear/bearCatalog.ts
tools/catalog-export/src/loaders/bear/bearDataDatasets.ts
tools/catalog-export/src/loaders/tiger/tigerCommon.ts
tools/catalog-export/src/transform/titles.ts
tools/catalog-export/src/transform/toCatalog.ts
tools/catalog-export/src/transform/toTypescript.ts
tools/mock-handling/src/base/config.ts
tools/mock-handling/src/base/types.ts
tools/mock-handling/src/base/variableNaming.ts
tools/mock-handling/src/interface.ts
tools/mock-handling/src/recordings/catalogRepository.ts
tools/mock-handling/src/recordings/displayForms.ts
tools/mock-handling/src/recordings/displayFormsRepository.ts
tools/mock-handling/src/recordings/insightsRepository.ts
tools/mock-handling/src/recordings/visClassesRepository.ts

This is to make sure the resulting bundles for our users are as small as possible.
The rule is enforced everywhere, even in `tools` where it is not so important,
but I think consistency across the whole repo is more important.
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do …

RELATED: RAIL-2792 make sure lodash is imported function-by-function

---

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePickerInputField.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/Datepicker/tests/Datepicker.test.tsx

RELATED: SD-1247 The mouse cursor auto move to last number (last of the year number) when inputting the day or month on DatePicker

---

common/scripts/ci/run_major_release.sh
common/scripts/ci/run_minor_release.sh
common/scripts/ci/run_preminor.sh

Split the creation of the next preminor alpha into a separate script.
This is needed, because on gitflow, the next alpha is created before
the minor/major is actually released (it is done on release branch creation).
JIRA: RAIL-2791
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …

RELATED: RAIL-2791 prepare CI scripts for gitflow

---

common/scripts/ci/run_preminor.sh

We want to use the template but it fails the whole build because of
missing slack file. We don't even want slack for this job,
so we mock the file to make the check happy.
JIRA: RAIL-2773
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelo …

RELATED: RAIL-2773 fix preminor CI script

---

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts

JIRA: ONE-4781
Whole feature of Theming is Project oriented and one particular customer should not be able to turn it off
---
---

Changes FF enableUiTheming from user to project scope

---

libs/sdk-backend-bear/src/backend/constants.ts
libs/sdk-backend-bear/src/backend/user/settings.ts
libs/sdk-backend-bear/src/backend/workspace/settings/settings.ts
libs/sdk-backend-bear/src/utils/api.ts

In case there is no authenticated principal, we return just empty defaults.
JIRA: RAIL-2807
---
---

RELATED: RAIL-2807 make settings APIs not fail for anonymous users

---

.github/pull_request_template.md
docs/contributing.md

* Add guide for telling if a Code Owner approval is necessary
* Improve the docs structure
JIRA: RAIL-2810
---
---

RELATED: RAIL-2810 improve contribution guidelines

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/styling/theme.ts

- Add `backgroundColor` to dashboards title
JIRA: ONE-4784
---
---
-   [ …

Add new property to styling - dashboards

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

Logs are no longer needed, reverting as originally planned.
Revert "Add logs to Pivot Table. Temporary, will be reverted"
This reverts commit 11d0718e2bd29541be540f334d0762b24bdf508e.
---
--- …

RELATED: ONE-4747 Revert pivot table enhanced logs

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/scheduledMails.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts

The spread was introducing unwanted properties,
we have to be explicit.
JIRA: XSH-301
---
---
-   [ ] …

RELATED: XSH-301 fix scheduled emails conversions in bear

---

libs/sdk-backend-spi/src/workspace/dashboards/layout/utils.ts

- Correct layout path in walkLayout util (fluidLayout is not nested under "fluidLayout" propa anymore)
JIRA: RAIL-2753
---
---
- …

RELATED: RAIL-2753 Correct layout path in walkLayout

---

libs/sdk-ui/src/base/localization/bundles/en-US.json

JIRA: SD-1264
---
---
-   [x] `rush change` [was run if …

Update the warning message when an invalid date is entered in static section of DateFilter component

---

rush.json

Turns out versionPolicyName overrides shouldPublish,
so we comment it out until we want to release the packages for real
JIRA: RAIL-2758
---
--- …

RELATED: RAIL-2758 Prevent sdk-ui-tests and mock-handling publishing

---

tools/applink/src/base/targetDiscovery.ts
tools/applink/src/base/types.ts
tools/applink/src/devConsole/ui/ui.ts

-  Applink does not do anything with 3rd party deps. If the version in the source repo has different 3rd party
dependencies compared to version in the target repo, then the app will likely stop working because
the synced code relies on 3rd party modules that are not there.
-  This is a known limitation of the file-syncing approach. Applink discovers this and reports to the user
via a message + entry in the log
---
---
-   [x] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the- …

RELATED: RAIL-21697 - Enhance applink to discover and report missing 3rd party deps

---

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

Accept header was missing to retrieve the object in the required json+api format.
Now it's possible to save, list and open insights.
JIRA: RAIL-2822
---
--- …

Update headers for insight retrieval

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/useDashboardViewLayout.ts
libs/sdk-ui/src/base/react/useCancelablePromise.ts

Add useDashboardViewLayout hook, that loads required additional data for the layouting, and transforms IDashboardLayout to IDashboardViewLayout model.
JIRA: 2818
---
--- …

RELATED: RAIL-2818 Add useDashboardViewLayout hook

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/api-client-bear/package.json
libs/sdk-backend-base/package.json
libs/sdk-backend-bear/package.json
libs/sdk-backend-bear/tests/integrated/backend.ts
libs/sdk-backend-mockingbird/package.json
libs/sdk-backend-spi/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-model/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/utils.ts
libs/sdk-ui-geo/package.json
libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx
libs/sdk-ui-pivot/package.json
libs/sdk-ui-pivot/src/PivotTable.tsx
libs/sdk-ui-tests/package.json
libs/sdk-ui-theme-provider/package.json
libs/sdk-ui/package.json
libs/sdk-ui/src/base/results/internal/dataAccessImpl.ts
libs/sdk-ui/src/execution/createExecution.ts
libs/sdk-ui/src/kpi/Kpi.tsx

-  bump to new version of ts-invariant with improved invariant() typing that integrates with TS checker
-  clean up code where we explicitly raised InvariantError
JIRA: RAIL-2752
---
--- …

RELATED: RAIL-2752 - Upgrade ts-invariant

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-ext/package.json
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItem.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemBase.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContent.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContentWrapper.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemHeadline.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemHeadlineContainer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemKpi.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemVisualization.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui-ext/styles/internal/scss/layout.scss
libs/sdk-ui-ext/styles/internal/scss/variables.scss

Adds visual components for the dashboard items along with their CSS.
The clientWidth of the DashboardItemContent is not used for now, but it will be necessary once we have the whole KPI component migrated and when we use the InsightView more directly (it may need a new prop for this to pass it to the PlugVis).
Also, KpiView and friends had the title prop removed as it is handled higher up the tree now.
---
---
- …

RELATED: RAIL-2819 add Dashboard item components 

---

libs/sdk-backend-bear/src/backend/workspace/styling/styling.ts

- Check for PlatformEdition to not use theming flag
JIRA: ONE-4791
---
---
-   [ ] `check-extended` …

Monetize Theming

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutRowHeader.tsx
libs/sdk-ui-ext/styles/internal/scss/layout.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Typography/Typography.tsx
libs/sdk-ui-kit/src/Typography/index.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/styles/scss/typo.scss

- Add Typography component
- Remove namespaced global scope css for headings and typography in gdc-dashboards
---
---
-   [ ] …

RELATED: RAIL-2789 Add Typography component, remove namespaced global scope css

---

libs/sdk-backend-bear/src/backend/workspace/datasets/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/ldm/datasets.ts
libs/sdk-backend-tiger/src/backend/workspace/datasets/index.ts

- Add new API for   (`/gdc/md/${projectId}/query/datasets`) in workspace datasets service that return IMetadataObject[] items. That API needed on AD/KD to check workspace has existed datasets or not to route Data tab for navigation of freemium users
---
---
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs …

RELATED: SD-1233 add API for get all workspace datasets

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/useLocale.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiRenderer.tsx
libs/sdk-ui-ext/src/internal/translations/de-DE.json
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui-ext/src/internal/translations/es-ES.json
libs/sdk-ui-ext/src/internal/translations/fr-FR.json
libs/sdk-ui-ext/src/internal/translations/ja-JP.json
libs/sdk-ui-ext/src/internal/translations/nl-NL.json
libs/sdk-ui-ext/src/internal/translations/pt-BR.json
libs/sdk-ui-ext/src/internal/translations/pt-PT.json
libs/sdk-ui-ext/src/internal/translations/zh-Hans.json

This is a temporary solution until we have the full-fledged KPI component.
The strings were sourced from gdc-dashboards.
We also added the missing locale prop and downloading to DashboardView.
Finally, a small bug in DashboardView was fixed for dashboardLayout errors.
JIRA: RAIL-2755
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributi …

RELATED: RAIL-2755 Fix secondary KPI item title

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiExecutor.tsx

Using the object itself can lead to infinite loops
JIRA: RAIL-2755
---
---
-   [ ] `check-extended` …

RELATED: RAIL-2755 use execution fingerprint as a dep in KpiExecutor

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/Header.tsx

Update interface for Header props for "onHelpClick" is that it is a function and not a boolean
JIRA: CAT-329
---
---
-   [ ] …

Fix Header API

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-new-json-api/api.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/__snapshots__/result.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/MeasureConverter.test.ts.snap

There is a bug in loading attributes from backend (see MDC-354)
which is possible to workaround by providing bigger size limit.
Overall paging does not work well (yet).
Besides that the Date is not a groupable item in the catalog so it has to be
filtered out in grouping function.
JIRA: RAIL-2822
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/doc …

Tiger: Load the date dataset (attribute) in catalog

---

libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.test.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Typography/Typography.tsx

- Propagate title in typography component
- Remove empty row headers in dashboard converter, when converting dashboard to api-bear-model (or backend throws error)
JIRA: RAIL-2838, RAIL-2834
---
--- …

Propagate title in typography component, remove empty row headers in dashboard converter

---

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

Previous PATCH was actually storing the whole insight so that
it's compatible with the update method on the new metadata (using PUT).
JIRA: RAIL-2822
--
--- …

Implement update insight function for new metadata

---

libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/ResponsiveText/ResponsiveText.tsx

* in Header we no longer can pass false as children to CSSTransition
* there were null references in ResponsiveText if ref was not ready for some reason
JIRA: RAIL-2758
---
--- …

RELATED: RAIL-2758 minor fixes to Header and ResponsiveText

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiContent/KpiContent.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiContent/utils/test/translations.test.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiContent/utils/translations.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiView/KpiExecutor.tsx

RELATED: RAIL-2843 fix KpiPop translation logic, prevent null reference

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/test/utils.test.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/utils.ts

This mimics the KPI dashboards behavior, that allows users to "remove"
date filters from insights connected to date dimension by using
the All time filter there.
JIRA: RAIL-2841
---
--- …

RELATED: RAIL-2841 add implicit All time filter in InsightRenderer

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithFilters.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/SimpleDashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardLayoutObtainer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardViewConfigContext.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/utils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts
libs/sdk-ui-geo/src/core/geoChart/GeoChartOptionsWrapper.tsx
libs/sdk-ui-geo/src/core/geoChart/GeoValidatorHOC.tsx

* improve error handling in DashboardView itself (e.g. nonexistent dashboard would show as loading forever)
* add a way to set mapboxToken to DashboardView - config prop (also separators and disableKpiDrillUnderline was moved there)
* minor fixes in GeoChart
* propagate missing mapbox token to the caller (previously only locationMissing was handled)
* allow to disable Error and Loading components in GeoOptionsWrapper – PluggableVisualization needs to really turn them off as it handles these concerns itself
---
--- …

RELATED: RAIL-2840 improvements to DashboardView

---

libs/sdk-backend-bear/src/backend/user/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/UsersConverter.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/user/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/scheduledMail.ts
libs/sdk-backend-spi/src/workspace/users/index.ts
libs/sdk-backend-tiger/src/backend/user/index.ts

- Add support for getting current user info to sdk-backend-spi
- This is necessary to move scheduled emails feature to gooddata-ui-sdk
JIRA: RAIL-2760
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in …

Add support for getting current user info to sdk-backend-spi

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/src/insightView/dataLoaders.ts
libs/sdk-ui-ext/src/insightView/index.ts
libs/sdk-ui-ext/src/insightView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx

Split InsightView into two parts
1. InsightRenderer which receives IInsightDefinition instance and renders it using PluggableVisualization
1. the original InsightView, that loads all the necessary data and passes them to InsightRenderer
This will allow us to use the InsightRenderer in DashboardView, where we will load the insight data differently (all at once for the whole dashboard).
Also, the InsightView data loading logic was cleaned up and better parallelized where possible.
The InsightView API was not changed in any way and neither was sdk-ui-ext API.
Finally, a minor bug in DashboardRenderer was fixed along the way.
---
| …

RELATED: RAIL-2844 split InsightView, fix DashboardRenderer

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/mockReferencePoint.ts
libs/sdk-ui-ext/src/internal/constants/uiConfig.ts
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/tests/mocks/uiConfigMocks.ts
libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/pivotTableUiConfigHelper.ts
libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/tests/__snapshots__/bulletChartUiConfigHelper.test.ts.snap

JIRA: ONE-4819
Introduces new FF enableMultipleDates for turning on the functionality
New bucket ui configs to allow multiple date items and to control its count limit
---
--- …

FEATURE: ONE-4819 Multiple dates in PluggablePivotTable

---

libs/sdk-ui-ext/src/insightView/InsightError.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiRenderer.tsx

Extract InsightView error handling logic to a separate component and use it in DashboardView as well.
Also, fix one possible null reference found along the way.
---
--- …

RELATED: RAIL-2851 handle No Data state in DashboardView

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialog.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialogRenderer.tsx

- only ScheduledMailRenderer is used in gdc-dashboards
- Move InternalIntlWrapper to ScheduledMailRenderer to ensure translations are available in KD
JIRA: RELATED: RAIL-2760 / RAIL-2831
---
--- …

RELATED: RAIL-2760 Move InternalIntlWrapper to ScheduledMailRenderer to fix translations in KD

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/PluggableColumnBarCharts.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/bucketHelper.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketHelper.test.ts

JIRA: ONE-4820
Few viz. types accept multiple Date items when switching from table, but they need to have the same dateDataset (dimension). Otherwise only first item is kept.
---
--- …

Handle Date bucket items when switching viz. types

---

libs/sdk-ui-kit/src/Header/HeaderDataMenu.tsx
libs/sdk-ui-kit/styles/scss/header.scss

We change tag name of bubble hover triger to make it cover the button. It didnt change logic code and css ( we dont have any css related to this class abbr)  and so on just change div to cover the children ( this case is button)
It's just change the css style of new component and dont need code owner to review it 
---
---
-   [x] review was done by a Code owner [if …

RELATED: SD-1292 Bubble trigger should cover children

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts

Previously, all alerts of the dashboard were deleted unexpectedly.
JIRA: RAIL-2867
---
---
-   [ ] …

RELATED: RAIL-2867 fix alert deleting for deleted widgets

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts

This makes the logic more in line with KPI Dashboards.
1. if user provided drillableItems, use only them
(analogous to KPI Dashboards and drilling specified in post message).
2. use the forceDisableDrillOnAxes setting the same way KPI Dashboards do
JIRA: RAIL-2863
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell- …

RELATED: RAIL-2863 Fix drilling configuration in DashboardView

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx

We need to allow undefined as value of drillableItems now.
JIRA: RAIL-2863
---
---
-   [ ] …

RELATED: RAIL-2863 remove wrong default value in InsightRenderer

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx

PivotTable fired pushData multiple times with the same items
however, not referentially the same. This led to infinite re-rendering.
Now, we deeply compare the results of pushData and set the state only
when there are actual changes.
Also, the logic around drilling was simplified.
JIRA: RAIL-2859
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/do …

RELATED: RAIL-2859 fix drilling in DashboardView with PivotTable

---

libs/sdk-ui-ext/styles/internal/scss/kpi.scss

Remove overflow: hidden that made the drill underline hidden in some widths.
JIRA: RAIL-2885
---
---
- …

RELATED: RAIL-2885 fix underline display in KPI

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithEmails.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContent.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-kit/src/Overlay/tests/Overlay.test.tsx

This makes sure that DashboardView is not reloaded unnecessarily
when only the isScheduledMailDialogVisible prop changes.
The DashboardRenderer was converted from arrow function to normal function
so that its displayName is set automatically (arrow functions do not do that).
This change was adopted in other existing components to reduce redundancy.
Also, an example of email scheduling for DashboardView was added.
JIRA: RAIL-2884
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-t …

RELATED: RAIL-2884 prevent DashboardView reloads

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialog.tsx

- Do not render loading or error overlay in ScheduledMailDialog, when DashboardView isScheduledMailDialogVisible property is false
JIRA: RAIL-2894
---
--- …

Fix rendering of the loading overlay in DashboardView ScheduledMailDialog

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithEmails.tsx

Now it closes the dialog on error and on success
JIRA: RAIL-2897
---
--- …

RELATED: RAIL-2897 fix scheduled email dialog example

---

libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/filterContext.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/filterContext.ts
libs/sdk-backend-spi/src/workspace/dashboards/tests/filterContext.fixtures.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/utils/filters.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/converters.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/test/converters.test.ts

The ObjRef is misleading, IAttributeElements are more appropriate.
This is technically breaking, but the API is alpha, so we are ok.
---
--- …

RELATED: RAIL-2905 simplify IDashboardAttributeFilter attributeElements

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout/facade/column.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout/facade/columns.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout/facade/layout.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout/facade/row.ts
libs/sdk-backend-spi/src/workspace/dashboards/layout/facade/rows.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutRowHeaderRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/interfaces/dashboardLayoutComponents.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/test/DashboardLayoutColumnRenderer.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/test/DashboardLayoutContentRenderer.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/test/DashboardLayoutRowRenderer.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardContentRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutColumn.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutColumnRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutRow.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/FluidLayoutRowRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/interfaces.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/test/FluidLayoutColumn.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/test/FluidLayoutColumnRenderer.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/test/FluidLayoutRow.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/FluidLayout/test/FluidLayoutRowRenderer.test.tsx

- Change FluidLayout renderers from React components to pure render props callbacks for better composability, and to avoid component remounting when injecting custom props (without usage of context)
- Optimize FluidLayoutFacade performance by adding WeakMap cache, make it more "lazy"
- Update naming for default renderers for better understandability & readability
- Minor fixes
JIRA: RAIL-2869
---
--- …

Layouting improvements & fixes

---

libs/sdk-ui/src/execution/useDataExport.ts
libs/sdk-ui/src/execution/useDataView.ts

Previously they would throw AnalyticalBackendErrors
which is not what they declare.
JIRA: RAIL-2847
---
--- …

RELATED: RAIL-2847 convert errors in useDataView and useDataExport

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/drills.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/drills.ts

-  This change reflects reality;
-  Bear can accept drill to dash without target dash = drill to self (with updated filters)
-  The SPI should reflect this as well
The client code was already dancing around this and passing down drills with target undefined. It worked by chance because the sdk-model idRef(id) function does not bomb if ID is undefined :)
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributi …

RELATED: RAIL-2905 - Make target of drill to dashboard optional - self drill

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketConfig.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketConfig.test.ts
libs/sdk-ui-ext/src/internal/utils/tests/bucketHelper.test.ts

Fix handling of referencePoint in pluggable visualizations 

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json

-  Some bad interplay between styled-jsx & babel,
-  Errors appear. Similar to this: https://github.com/vercel/styled-jsx/issues/560
-  Not critical to be on latest version so downgrading
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributin …

RELATED: RAIL-2905 - Downgrade styled-jsx to prevent example runtime errors

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/OrganizationObjects.ts
libs/api-client-tiger/src/axios.ts
libs/api-client-tiger/src/gd-tiger-model/typeGuards.ts
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/base.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts
libs/sdk-backend-tiger/src/backend/workspaces/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/WorkspaceConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/result.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/dateGranularityConversions.ts
tools/catalog-export/src/loaders/tiger/index.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerCatalog.ts
tools/catalog-export/src/loaders/tiger/tigerClient.ts
tools/catalog-export/src/loaders/tiger/tigerCommon.ts
tools/catalog-export/src/loaders/tiger/tigerDateDatasets.ts
tools/catalog-export/src/loaders/tiger/tigerInsights.ts

There is a new version of open-api for metadata service (which is generated by the library), this PR aims to replace the usage across all places.
Affected parts:
* api-client-tiger
* sdk-backend-tiger
* catalog-export
Keep in mind that this update of API also brings the support of the links in included resources (requested by dashboards).
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-l …

Tiger: Update metadata OAPI

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/workspaceObjects.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts
tools/catalog-export/README.md
tools/catalog-export/src/loaders/tiger/index.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerCatalog.ts
tools/catalog-export/src/loaders/tiger/tigerDateDatasets.ts
tools/catalog-export/src/loaders/tiger/tigerInsights.ts

One more round of the Tiger OAPI update.
Includes:
* fixed granularities (EU ones)
* removed WorkspaceModelController and switch to WorkspaceObjectController
Also updated in catalog-export and sdk-backend-tiger.
---
--- …

Tiger: Update OAPI and fix granularities

---

examples/sdk-examples/src/examples/dashboardEmbedding/CustomDashboardView.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardWidgetRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/utils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardInsightExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardKpiExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardWidgetExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts
libs/sdk-ui/src/execution/index.ts
libs/sdk-ui/src/execution/useExecution.ts

- Introduce useDashboardWidgetExecution hook, to get same execution definition as the widget on the dashboard
- Add predicates to test widgets for common conditions
- Improve IDashboardWidgetRenderer interface, make it more limited, but still flexible
- Hide sizing logic and other sizing implementation details from the widget (sizing should be solved on the layout level until we support custom widget heights)
- Minor fixes
- Add custom widget rendering example
---
--- …

Make widget rendering customization more convenient

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/execution/filter/index.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/brokenFilterUtils.ts
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss

* fix selector specificity as now it is imported before KPI Dashboards code (not after as before)
* add attributeElementsCount and use it
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-own …

RELATED: RAIL-2847 minor fixes for alerts migration

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/KpiAlertDialog/test/KpiAlertDialog.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/test/translationUtils.test.ts
libs/sdk-ui-ext/src/internal/index.ts
libs/sdk-ui-ext/src/internal/utils/internalIntlProvider.tsx
libs/sdk-ui-ext/src/internal/utils/translations.ts

We need this to be able to use these from other apps.
JIRA: RAIL-2853
---
--- …

RELATED: RAIL-2853 expose translations in sdk-ui-ext

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardExport.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/convenience/useDashboardPdfExporter.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/convenience/useExportDashboardToPdf.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useExportDashboardToPdf.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts

This hooks allows the user to export a dashboard to PDF.
A simple example was added.
JIRA: RAIL-2921
---
--- …

RELATED: RAIL-2921 add useExportDashboardToPdf hook

---

examples/sdk-examples/src/examples/dashboardEmbedding/CustomDashboardView.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithDrilling.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithEmails.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithFilters.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewWithMergedFilters.tsx
examples/sdk-examples/src/examples/dashboardEmbedding/SimpleDashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardViewIsReadOnlyContext.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/DashboardItemWithKpiAlert.tsx

Since the mechanism relies on passing a prop anyway, there
is no need to create a special build of examples (since missing
the prop would disable the readonly mode anyway).
Instead, we just use the appropriate flag in all examples.
Also, a bug in DashboardItemWithKpiAlert was fixed related to read only.
This bug does not manifest in KPI Dashboards because the readonly prop
is reflected in the canSetAlert prop as well.
JIRA: RAIL-2931
---
--- …

RELATED: RAIL-2931 add read only prop to DashboardView and use it in examples

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContentWrapper.tsx

This makes sure that DashboardLayoutItem re-renders only on width
change. This is useful for cases when the inside of the item changes
height for some reason and this would create a re-render which can
make the height change again -> infinite loop.
JIRA: RAIL-2875
---
--- …

RELATED: RAIL-2875 prevent unnecessary DashboardLayoutItem re-renders

---

libs/sdk-ui/src/base/react/safeSerialize.ts
libs/sdk-ui/src/base/react/tests/__snapshots__/safeSerialize.test.ts.snap
libs/sdk-ui/src/base/react/tests/safeSerialize.test.ts
libs/sdk-ui/src/base/react/useCancelablePromise.ts

This removes the default of the deps parameters (which makes this behave like useEffect and makes this easier to apply useEffect intution to).
JIRA: RAIL-2932
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-a …

RELATED: RAIL-2932 make useCancelablePromise consistent with useEffect

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardItem/DashboardItemContentWrapper.tsx

This reverts commit 03668edbb2cb7bbc81a2b30c363f65684c5c0eb3.
Turns out the fix would make future improvements problematic. Will look for a different fix.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appro …

Revert "Prevent unnecessary DashboardLayoutItem re-renders"

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx

This helps with performance and avoids the bug with highcharts sometimes
changing height slightly (or at least makes it so that it does not create
an infinite loop when it happens).
This also explains why this bug was only happening in the SDK and not in KPI Dashboards.
JIRA: RAIL-2875
---
--- …

RELATED: RAIL-2875 avoid unnecessary re-renders in InsightRenderer

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/brokenFilterUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/translationUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialog.tsx
libs/sdk-ui-kit/src/List/InsightListItem.tsx

This avoids unnecessary conversions and uses the translation
methods more directly.
Also, an obsolete any cast was removed and an edge case in ScheduleMailDialog was handled.
JIRA: RAIL-2847
---
--- …

RELATED RAIL-2847: clean up date filter intl in dashboard embedding

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bubbleChart/bubbleChartSeries.ts

null values are not displayed in legend
---
--- …

BUGFIX: BB-2801 bubble chart legend

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/index.ts
libs/sdk-ui-ext/src/internal/utils/translations.ts

sdk-ui-ext depends on some of the strings in sdk-ui
so we must make them available.
Also, adds a missing export
JIRA: RAIL-2853
---
--- …

RELATED: RAIL-2853 Merge sdk-ui translations in sdk-ui-ext

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/DashboardItemWithKpiAlert.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/KpiAlertDialog/KpiAlertDialogBrokenFilters/utils/filterUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/KpiAlertDialog/test/KpiAlertDialog.test.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/translationUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useAttributesWithDrillDown.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useColorPalette.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useCurrentUser.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboard.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardAlerts.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardInsightExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardKpiExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardViewLayout.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDashboardWidgetExecution.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useDeleteWidgetAlert.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useExportDashboardToPdf.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useSaveOrUpdateWidgetAlert.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useSaveScheduledMail.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useUpdateWidgetAlert.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useUserWorkspacePermissions.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useUserWorkspaceSettings.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/useWorkspaceUsers.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/hooks/utils.ts
libs/sdk-ui-ext/tsconfig.json

Assortment of small fixes/tweaks
* simplify work with invariants in dashboardEmbedding hooks
* remove obsolete code, remove `as any` casts
* fix unmounting of DashboardItemWithKpiAlert
* enable the `noImplicitThis` typescript flag
* add missing rowHeaderRenderer default
* simplify and fix a callback in InsightRenderer
---
---
-   [ ] …

RELATED: RAIL-2956 several small fixes for dashboardEmbedding

---

libs/api-client-bear/src/dashboard/tests/dashboard.test.ts
libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/filterContext/GdcFilterContext.ts
libs/api-model-bear/src/filterContext/tests/utils.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/DashboardConverter.fixtures.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/utils/filters.ts

The fix is two-fold
1. fix the api-model-bear filterContext spec to align to bear schema in [gdc-bear](https://github.com/gooddata/gdc-bear/blob/d8c30226e5470d96cc201fd0a99823ffbb4fec50/resources/specification/md/obj/kpiDashboard.res#L206-L218)
2. strip dateDataset information from date filters when creating the alert (this mimics the KD behavior)
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the- …

RELATED: RAIL-2973 fix creating alerts with relative filters

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/DashboardWidgetRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/InsightRenderer/drillingUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/KpiRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/KpiView/index.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardView/types.ts

This allows the user to access the original DrillDefinitions when
an implicit drill is triggered. Since there can be more than one
definition responsible for a given drill event, all relevant are included.
Since there is no DrillDown definition, a special DrillDefinition-like
type was defined and used.
Useless logic from KpiView was removed.
The DrillDefinitions are returned as-is (so no custom URL resolution
is done for example). This might be improved later.
JIRA: RAIL-2890
---
--- …

RELATED: RAIL-2890 Provide info about drill definitions on drill

---

CHANGELOG.md
common/changes/@gooddata/sdk-ui-all/dho-rail-2774-date-filter-theme-beta_2021-02-18-14-45.json
libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/Context.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/cssProperties.ts

Mark ThemeProvider as public as it is stable enough to be marked as such.
Fix the root changelog link to link directly to the target changelog, not the package containing it.
---
--- …

RELATED: RAIL-2774 take ThemeProvider out of beta

---

common/changes/@gooddata/sdk-ui-all/ine-one-4890_2021-02-25-16-35.json
libs/api-client-bear/src/catalogue.ts
libs/api-client-bear/src/tests/catalogue.test.ts

Now date bucket items are always removed from request loadDateDataset, but with "multiple date datasets" feature we need to keep some of them to get valid available date datasets and avoid execution error with incompatible date dimensions.
Filtering of date bucket items should be done on some of topper layers - probably AD itself
---
--- …

Date bucket items should not be always removed from the request

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/data/dataSource.ts
libs/sdk-ui-pivot/src/impl/data/rowFactory.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptor.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptorFactory.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptorTypes.ts

FIX: autoresize & grow to fit was not triggered during window/div resize since 8.1 as some code to trigger this was deleted by mistake
HOTFIX: pivot table mutates exec result descriptors, causing extra havoc when caching is turned on
---
--- …

BUGFIX: RAIL-2978, BB-2811 - Pivot fixes

---

libs/sdk-ui-pivot/src/impl/data/dataSource.ts
libs/sdk-ui-pivot/src/impl/data/rowFactory.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptor.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptorFactory.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptorTypes.ts

-  updateTotalItems was mutating attribute descriptors
-  this messes up contents of cache
-  but ultimately it is not a good thing to do as it can lead to unpredictable behavior
even without caching
JIRA:  BB-2811
---
--- …

BUGFIX: BB-2811 - Fix table descriptor to not mutate underlying descriptors

---

common/changes/@gooddata/sdk-ui-all/ine-one-4890_2021-02-25-16-35.json
libs/api-client-bear/src/catalogue.ts
libs/api-client-bear/src/tests/catalogue.test.ts

- Remove `removeDateItems` in loadDateDataSets api
- Changelog
JIRA: ONE-4890
---
--- …

RELATED: ONE-4890 - Date bucket items should not be always removed from the request

---

common/changes/@gooddata/sdk-ui-all/dho-rail-1870-date-filter-fixes_2021-03-01-09-12.json
common/changes/@gooddata/sdk-ui-all/dho-rail-1870-date-filter-fixes_2021-03-01-09-14.json
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/AllTimeFilterItem.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
libs/sdk-ui-filters/src/DateFilter/index.ts
libs/sdk-ui-filters/src/DateFilter/utils/OptionUtils.ts
libs/sdk-ui-filters/src/DateFilter/utils/tests/OptionUtils.test.ts
libs/sdk-ui-filters/src/index.ts

* RAIL-1870 Respect visible property of date filter options - visible: false options are no longer shown. The related function was exported so that other apps can use it as well.
* RAIL-1843 Respect dateFilterOption names - All time and Forms now respect their names if there is any.
* RAIL-1875 Sanitize presets in DateFilter  - This makes sure that all presets have from <= to.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/co …

Several DateFilter fixes

---

libs/sdk-ui-filters/src/DateFilter/utils/Translations/DateFilterTitle.ts
libs/sdk-ui-filters/src/DateFilter/utils/Translations/tests/DateFilterTitle.test.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

In case the from and to is the same, we can make the message shorter
and more natural.
So instead of "From 2 to 2 days ago" we now have "2 days ago".
JIRA: RAIL-1446
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request- …

RELATED: RAIL-1446 improve DateFilter wording

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/meta/GdcMetadata.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/styling/index.ts
libs/sdk-backend-spi/src/workspace/styling/theme.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/complementaryPalette.ts
libs/sdk-ui-theme-provider/src/cssProperties.ts
libs/sdk-ui-theme-provider/src/tests/__snapshots__/complementaryPalette.test.ts.snap
libs/sdk-ui-theme-provider/src/tests/complementaryPalette.test.ts

- with auto-generated missing shades
- rendered as css variables: --gd-palette-complementary-<0-9>
JIRA: BB-2813
---
--- …

Introduced complementary palette

---

libs/sdk-ui-pivot/src/impl/resizing/agGridColumnSizing.ts

Avoid null containerRef in getAutoResizedColumns

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/tableFacade.ts
libs/sdk-ui-pivot/src/tableState.ts

Upon table reinit and internal state destruction:
-  The facade needs to be destructed as well, it's gridApi instance cleared
-  The rest of the code, finding this will mute any of its work with the table
-  Without this, ag-grid errors with these symptoms appear:
https://github.com/ag-grid/ag-grid/issues/3334
JIRA: FET-608
---
---
- …

BUGFIX: FET-608 - Fix pivot table race conditions

---

libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/KpiView/KpiRenderer.tsx

To keep consistent with insights, KPI should not be underlined if they
have some drilling set, but no onDrill handler has been provided.
This prevents confusion of user clicking on it and nothing happening.
JIRA: RAIL-2994
---
--- …

RELATED: RAIL-2994 Do not underline KPIs without onDrill

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutSection.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/interfaces.ts

- Fix callback propagation
- Pass grid row items to the callback
JIRA: ONE-4910
---
--- …

Fix grid row renderer

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/dateGranularityConversions.ts

* EU granularities removed (affects both afm and metadata)
* added data distriminators (date filters)
* updated of metadata controllers
There is a manual change in the metadata json to avoid `_1` naming of methods (relates
to duplication of methods between organization-controller and organization-model-controller).
JIRA: NAS-72
---
--- …

Tiger: Update OAPI schemas

---

libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx

Follow up to #1064 that makes it consistent in insights as well
JIRA: RAIL-2994
---
--- …

RELATED: RAIL-2994 Only pass drillableItems down if there is onDrill

---

libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/InvalidInputs.fixture.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap

-  KD only supports uri-based attr filters and it is not feasible to change this now. So this is
part of the 'hack' where all uri-based filters in KD actually use values in the 'uris'.
-  The convertor code in tiger backend impl is then more lenient and will just grab the content of
'uris' and use it as values
---
---
- …

RELATED: RAIL-2697 - Make tiger filtering convertors more lenient

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dateFilterConfigs/index.ts
libs/sdk-backend-tiger/src/backend/workspace/index.ts

-  Serves single hard-coded config
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in …

RELATED: RAIL-2697 - Add date filter config service

---

common/config/rush/browser-approved-packages.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-charts/src/highcharts/adapter/Chart.tsx
libs/sdk-ui-charts/src/highcharts/adapter/chartPlugins.ts
libs/sdk-ui-charts/src/highcharts/adapter/plugins/3rdParty/grouped-categories.ts
libs/sdk-ui-charts/src/highcharts/adapter/plugins/group-categories-wrapper.ts
libs/sdk-ui-charts/src/highcharts/adapter/test/Chart.test.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/typings.d.ts

By copying and fixing Highcharts plugin grouped-categories
About the copy of grouped-categories plugin 
Kate Downing confirmed that
- this is entirely under Creative Commons Attribution 3.0. This is fine to use, and modify, in any GoodData product. As with all third party code, though, it's important that it be kept distinct and apart from GoodData-written files so that when we run OSS scanning tools to create open source disclosures, we pick it up on our scans. If you have any questions on that, I think Vojtech Luhan can give extra direction.
Vojtech Luhan confirmed that
- it's OK to have the code just in separate file
- It's enough to include URI of the CC licence
JIRA: FET-617
---
| ---------------------- | …

Fix axis label auto-rotation

---

examples/sdk-examples/src/examples/dashboardEmbedding/DashboardViewAdvancedCustomizationsSrc.tsx
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-ui-ext/src/dashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayoutSection.tsx

- Correct feature flag name
- Provide default section header renderer
- Minor fixes in sdk-examples
JIRA: RAIL-2035
---
--- …

Fix section headers rendering in DashboardView

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/ad.ts

JIRA: BB-2837
All the new stuff mimics that for the Clear command
---
--- …

Add ClearInsight command to AD post messages

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/filterContexts.ts
libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-bear/src/backend/workspace/dashboards/tests/filterContexts.test.ts

Since bear [cannot handle ids in filter context items][1], we need to convert them to URIs.
[1]: https://github.com/gooddata/gdc-bear/blob/d8c30226e5470d96cc201fd0a99823ffbb4fec50/resources/specification/md/obj/kpiDashboard.res#L177-L219
JIRA: RAIL-2995
---
--- …

RELATED: RAIL-2995 Sanitize filter contexts in bear

---

common/changes/@gooddata/sdk-ui-all/dho-rail-2774-date-filter-theme-beta_2021-02-18-14-45.json
common/changes/@gooddata/sdk-ui-all/dho-rail-2956-changelog_2021-03-01-09-36.json
common/changes/@gooddata/sdk-ui-all/pdo-bb-2795-whitelist_2021-02-22-16-57.json

* language fixes by tech writers
* fix in whitelist entry - tiger now considers all calls valid (not invalid as previously stated)
JIRA: RAIL-2774
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a …

RELATED: RAIL-2774 Fix changelog entries

---

libs/sdk-ui-charts/__mocks__/styleMock.ts
libs/sdk-ui-charts/package.json
libs/sdk-ui-charts/src/charts/headline/internal/Headline.tsx
libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/adapter/test/HighChartsRenderer.test.tsx
libs/sdk-ui-charts/styles/scss/charts.scss
libs/sdk-ui-vis-commons/package.json

These two packages were doable without any significant rewrites, just simple replacements/removals.
Other packages are blocked by:
* indigo fonts imported from goodstrap
* missing components in sdk-ui-kit
* missing svg assets
---
--- …

RELATED: FET-553 remove goodstrap from charts and vis-commons

---

libs/sdk-backend-tiger/src/backend/workspace/attributes/index.ts
libs/sdk-backend-tiger/src/backend/workspace/facts/index.ts
libs/sdk-backend-tiger/src/backend/workspace/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts

-  Load fact by ref & sideload data set
-  Convert and return dataset meta
JIRA: RAIL-2835, RAIL-2836
---
--- …

RELATED: RAIL-2835 - Implement fact service for tiger

---

tools/catalog-export/README.md
tools/catalog-export/src/base/config.ts
tools/catalog-export/src/base/constants.ts
tools/catalog-export/src/base/tests/__snapshots__/config.test.ts.snap
tools/catalog-export/src/base/tests/config.test.ts
tools/catalog-export/src/base/types.ts
tools/catalog-export/src/cli/prompts.ts
tools/catalog-export/src/exports/metaToCatalog.ts
tools/catalog-export/src/exports/metaToJavascript.ts
tools/catalog-export/src/exports/metaToTypescript.ts
tools/catalog-export/src/index.ts
tools/catalog-export/src/loaders/bear/bearAnalyticalDashboard.ts
tools/catalog-export/src/loaders/bear/bearCatalog.ts
tools/catalog-export/src/loaders/bear/bearDateDatasets.ts
tools/catalog-export/src/loaders/bear/bearInsights.ts
tools/catalog-export/src/loaders/bear/bearLoad.ts
tools/catalog-export/src/loaders/bear/index.ts
tools/catalog-export/src/loaders/bear/tests/__snapshots__/bearLoad.test.ts.snap
tools/catalog-export/src/loaders/bear/tests/bearLoad.test.ts
tools/catalog-export/src/loaders/tiger/index.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerCatalog.ts
tools/catalog-export/src/loaders/tiger/tigerDateDatasets.ts
tools/catalog-export/src/loaders/tiger/tigerInsights.ts
tools/catalog-export/src/loaders/tiger/tigerLoad.ts
tools/catalog-export/src/transform/toCatalog.ts
tools/catalog-export/src/transform/toTypescript.ts

-  Added workspace prompting and name -> id lookup for tiger
-  Prepared the entire tool for platform-wide switch from project -> workspace
-  Internals are all using 'workspace'
-  Tiger uses workspace nomenclature
-  CLI arguments and config parameterization allows use of 'workspaceId' and 'workspaceName'; this is synonym for projectId and projectName. On tiger, tool logs warning that projectId / projectName is deprecated.
-  Deprecation warnings are not in bear yet. All messaging in bear so far still uses project. This will change once we do the respective epic that deals with this change platform-wide
---
| …

RELATED: RAIL-2964 - Workspace selection in catalog export for tiger

---

libs/sdk-backend-bear/src/backend/workspace/attributes/index.ts

- use one transformation in all methods
JIRA: RAIL-3009
---
--- …

Fix display form transformation inconsistencies

---

libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/DashboardLayout.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/interfaces.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/__snapshots__/sizing.test.ts.snap
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/sizing.test.ts

- Use `min-height` when `heightAsRatio` is not defined
- Use `height` when `heighAsRatio` is defined
JIRA: ONE-4909
---
--- …

Row height works with custom widget height

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/brokenFilterUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/test/brokenFilterUtils.test.ts

Turns out noop deleted filters are also considered broken.
The code was migrated wrongly from KD originally.
JIRA: RAIL-3062
---
--- …

RELATED: RAIL-3062 Fix getBrokenAlertFiltersBasicInfo

---

docs/contributing.md
tools/applink/src/devConsole/ui/ui.ts

- Updated contributing guide
- Made applink to also support non-F-keys to start menu commands
JIRA: NAS-34
---
--- …

RELATED: NAS-34 - Mention applink in docs + small usability tweak in the tool

---

libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/brokenFilterUtils.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/KpiAlerts/utils/test/brokenFilterUtils.test.ts

Turns out noop deleted filters are also considered broken.
The code was migrated wrongly from KD originally.
JIRA: RAIL-3062
Port of #1130 to master
---
--- …

RELATED: RAIL-3062 Fix getBrokenAlertFiltersBasicInfo 

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/index.ts
libs/sdk-backend-base/src/ldmFactories/metadata/dashboardFactory.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/dashboard/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/index.ts
libs/sdk-backend-tiger/src/backend/user/settings.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/mocks/visualizationClasses.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/MetadataConverter.ts
libs/sdk-ui-geo/styles/scss/tooltip.scss

* RAIL-3079 - This is needed to display dashboards using a given insight.
* RAIL-3054 - Tiger backend is not ready to handle mapbox tokens yet
Also one small tweak of scss was done to avoid warnings.
---
--- …

RELATED: RAIL-3079, RAIL-3054 Implement getInsightReferencingObjects on tiger, disable goechart on tiger

---

.gitignore
common/config/rush/command-line.json
common/config/rush/pnpm-lock.yaml
common/scripts/build-docs.sh
examples/sdk-examples/package.json

-  Added script to build API docs using api-documenter
- Project sanity: bumped react-syntax-highlighter in examples to remove security warnings in prismjs
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appr …

RELATED: RAIL-3086 - api-documenter integration + small project sanity

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-tests/stories/end-to-end/pivotTable/PivotTableHeight.tsx
tools/reference-workspace/src/recordings/dataSample.ts
tools/reference-workspace/src/recordings/index.ts

JIRA: ONE-4935
As we implemented a manual change of widget height, we noticed that Pivot Table does not react to the heigh change. Therefore we have to add logic that will cause a change of pivot table height.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …

Pivot table reacts to change of the height

---

libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

We need to use toUpperCase, otherwise "new insight" would be after "ZZZ"
JIRA: RAIL-3087
---
--- …

RELATED: RAIL-3087 Fix tiger insights sorting

---

libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts

-  A hacky way to do this atm because there is no official way to do this
JIRA: RAIL-3091
---
--- …

RELATED: RAIL-3091 - Set insight as locked if it comes from parent workspace

---

libs/sdk-backend-tiger/src/auth.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/utils/errorHandling.ts

-  The extra call to get organization is no longer needed. Verified that /api/profile now correctly returns 401 
---
--- …

RELATED: RAIL-3091 - Flag more stuff with TIGER-HACK, remove one hack

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/convertors/toBackend/ObjRefConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/AfmFiltersConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/MeasureConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/AfmFilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/toAfmResultSpec.ts

-  This is not supported by tiger backend
-  Modified convertor code to tunnel attributes into the filter convertor
so that ranking filter convertor can do lookup
JIRA: RAIL-3131
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my- …

RELATED: RAIL-3131 - Support ranking filters that reference attributes by localId

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/gd-tiger-model/AnalyticalDashboardObjectModel.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/utils.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts

-  Tags need to come from MD object attributes.tags; they are not part of the
dashboard content that is controlled by SDK
-  The isLocked indicator is the same. It comes from the backend.. now through
the nasty tiger-hack where inherited objects in child workspace are locked and
this is determined by presence of colon char in the identifier.
JIRA: RAIL-3127
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-s …

RELATED: RAIL-3128 - Fix analytical dashboard isLocked & tags behavior

---

libs/sdk-backend-bear/src/backend/workspace/measures/test/measureExpressionTokens.test.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/test/measureExpressionTokens.test.ts

Now it can parse MAQL without whitespaces around operators.
This is done by replacing the "\S" (non-whitespace)
by "[^}]" (non-closing-bracket) which is more precise.
Checked also the bear version with a similar test, it was already correct, however.
JIRA: RAIL-3132
---
--- …

RELATED: RAIL-3132 Fix MAQL parser in tiger

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts

Tiger does not support measure value filters with ranking filters at the same time,
it only supports one or the other.
JIRA: RAIL-3138
---
--- …

RELATED: RAIL-3138 Add supportsRankingFilterWithMeasureValueFilter capability

---

libs/sdk-backend-tiger/src/auth.ts

-  Error handling was noop
-  Now is debug log and throw
NOTE: this does not fix the issue itself. it's just something i discovered while digging in the code. The root cause of the problem is likely in other systems.
JIRA: RAIL-3133
---
--- …

RELATED: RAIL-3133 - Fix logout error handling

---

libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

The values were sourced from AD where these were already defined.
JIRA: RAIL-3142
---
--- …

RELATED: RAIL-3142 Add missing localization strings for KPI alert dialog

---

libs/sdk-backend-bear/src/convertors/fromBackend/ObjRefConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts

Makes sure type is added to id refs since we know the type when converting.
This makes the covertor more usable in certain contexts.
JIRA: RAIL-3158
---
--- …

RELATED: RAIL-3158 Fix bear visualization object converter

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

We must intercept the errors coming from the InsightRenderer
so that we can display the appropriate error component (e.g. No data).
JIRA: RAIL-3161
---
--- …

RELATED: RAIL-3161 Fix InsightView error handling

---

libs/sdk-ui-kit/src/Header/Header.tsx

Removes accidental blank space caused by useless defaulting of prop.
JIRA: RAIL-3093
---
--- …

RELATED: RAIL-3093 Fix AppHeader in case there are no badges

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_util/color.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/heatmap/heatmapColoring.ts

Change of base color caused issue of heatmap color in AD. This commit fixes it.
JIRA: BB-2856
---
--- …

Fix heatmap base color

---

libs/sdk-backend-spi/src/backend/index.ts
libs/sdk-backend-tiger/src/backend/index.ts

Previously only 401 responses were handled there, but we need
to also handle NAuth errors, for example "Session expired" errors.
Also, make onNotAuthenticated contract more precise.
JIRA: RAIL-3188
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#h …

RELATED: RAIL-3188 Handle NAuth errors in tiger isAuthenticated

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/gd-tiger-model/VisualizationObjectModelV1.ts
libs/api-client-tiger/src/gd-tiger-model/VisualizationObjectModelV2.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/AttributeConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/DimensionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/MeasureConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/TotalsConverter.ts

Remove useless types for executions, we should use the types from open API.
JIRA: RAIL-3189
---
--- …

RELATED: RAIL-3189 Clean up tiger free-form types

---

libs/sdk-backend-tiger/src/backend/index.ts

-  Was doing log & sink - thus breaking a lot of stuff bound to exception handling such as login
-  In some (weird) cases, Tiger response may not be JSON object but text/html returned by axios as a string
-  DO not do anything with those
JIRA: RAIL-3163
---
--- …

RELATED: RAIL-3163 - Fix error logging interceptor

---

examples/sdk-examples/src/components/ExampleWithSource.tsx
examples/sdk-examples/src/components/SourceContainer.tsx
examples/sdk-examples/src/constants/customTheme.ts
examples/sdk-examples/src/examples/theming/ThemedComponentsExample.tsx

- add complementary palette to customTheme used by themed examples
- overwrite several css variables inside ExampleWithSource in order to avoid theming in source part
- remove themed RankingFilter example as it is not fully supported by complementary palette yet
- add themed BarChart example
JIRA: BB-2888
---
--- …

Extend Live Examples by complementary palette

---

libs/api-client-tiger/openapi-generator/api.mustache
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/sdk-backend-bear/api/sdk-backend-bear.api.md
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

Tiger no longer supports links insight -> dashboard,
so we need to go the other way around.
Also the query handling was improved so that objects use dot notation
as the backend cannot handle the [] notation apparently.
JIRA: RAIL-3220
---
--- …

RELATED: RAIL-3220 Fix tiger getInsightReferencingObjects

---

examples/sdk-examples/src/App.tsx
libs/sdk-ui-charts/styles/scss/charts.scss
libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx

- To fix sizing/overflowing issues in Safari
- Also fix examples in Safari (so they do not overflow out of the screen)
JIRA: RAIL-3214
---
--- …

Fix Highcharts and PivotTable sizing

---

examples/sdk-examples/src/App.tsx
libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-ui-charts/styles/scss/charts.scss
libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx

This uses non-exploded arrays in execute calls which are now validated.
Also reverts the previous commit by Matyáš so that we can create a new beta without it and deliver it as soon as possible with less risk.
JIRA: RAIL-3222
---
--- …

RELATED: RAIL-3222 Re-generate tiger client

---

libs/sdk-ui-kit/styles/scss/dialog.scss

In some apps the links ended up being not underlined so we force it to be sure.
JIRA: RAIL-3093
---
--- …

Make sure the CommunityDialog links are underlined

---

tools/catalog-export/src/loaders/bear/bearLoad.ts
tools/catalog-export/src/loaders/tiger/index.ts
tools/catalog-export/src/loaders/tiger/tigerLoad.ts
tools/catalog-export/src/transform/toTypescript.ts

* prevent TypeScript errors in generated files in case there are no measures in the workspace for instance
* update the guide shown when the TIGER_API_TOKEN is not set - we always need to guide the user to create a new token as retrieving the value of existing token in impossible
* handle invalid values of workspace-id more gracefully (on both tiger and bear)
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what …

RELATED: RAIL-3191 fix catalog-export on tiger

---

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/dimensions.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/__snapshots__/dimensions.test.ts.snap
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/tests/dimensions.test.ts

Make sure the totals added to the descriptor are unique.
It can happen that there is more than one total of the same type
for a given attribute, but the server will only return data for
the given total type once and there were mismatches in collection
lengths: for example two rows of totals for three total descriptors
(two of which are the same) which broke the components down the road.
So we make sure to only send unique types forward to avoid this mismatch
(effectively mimicking the backend which seems to be de-duplicating
the totals too).
JIRA: RAIL-3246
--- …

RELATED: RAIL-3246 Fix tiger totals conversion

---

examples/sdk-examples/src/examples/pivotTable/PivotTableDrillExample.tsx

- change assertion from `typeof drillColumn === 'object'` to `!isNil(drillColumn)` (because `typeof null === 'object'`)
JIRA: RAIL-3239
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner …

Update PivotTable drill example so it's able to handle null references

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts

-  Measures may reference non-existent LDM objects
-  We forgot to filter these out the last time when updating insight/dashboard/catalog-export services
JIRA: RAIL-3260
---
--- …

RELATED: RAIL-3260 - Filter invalid measures from catalog

---

libs/sdk-ui-theme-provider/src/ThemeProvider/prepareTheme.ts
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/__snapshots__/prepareTheme.test.ts.snap
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/prepareTheme.test.ts

when used in application not supporting the complementary palette
JIRA: BB-2825
---
--- …

Ensure the primary color is contrast enough

---

common/changes/@gooddata/sdk-ui-all/map-rail-1842-deprecate-available-granularities_2021-04-15-13-15.json
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/RelativePresetFilterItems.tsx
libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/RelativeDateFilterForm.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeRangePicker/RelativeRangePicker.tsx

Description of changes.
- RAIL-1842 availableGranularities in DateFilter marked as deprecated
- RAIL-1603 issue with reopening 'to' field after choosing its value in relativeFilterForm
- RAIL-1624 consider available granularities in relativeFilterForm and presets
- RAIL-1872 console warning about incorrect DateFilter setup 
---
---
- …

RAIL-1842 DateFilter Mark available granularities as deprecated

---

libs/sdk-ui-kit/src/List/InsightListItemDate.tsx
libs/sdk-ui-kit/src/List/tests/InsightListItemDate.test.ts

The date of insight update was not rendered in local time if AD/KD saved insight list is opened in a different time zone than the one metadata are saved in, i.e., in different one than Europe/Prague.
JIRA: FET-713
---
--- …

UI Kit: Render insight update time in local time

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-base/src/normalizingBackend/index.ts
libs/sdk-backend-base/src/normalizingBackend/tests/withNormalization.test.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-tests/tests/_infra/backendWithCapturing.ts
libs/sdk-ui/src/execution/tests/Execute.test.tsx
libs/sdk-ui/src/execution/tests/RawExecute.test.tsx
libs/sdk-ui/src/execution/tests/withExecutionLoading.test.tsx

Make sure the dataViews passed in the NoDataErrors are denormalized
to ensure that only denormalized data views come from the executions
To test this, dummyBackend had to be extended to allow different
NoDataErrors to be thrown (with or without dataViews).
Using this, some tests were extended to cover both cases.
JIRA: RAIL-3241
---
--- …

RELATED: RAIL-3241 Fix normalizingBackend for NoDataErrors

---

libs/sdk-backend-tiger/src/backend/index.ts

In case a request is blocked by client, we would not see the error
as in that case, the response is undefined.
JIRA: RAIL-3277
---
--- …

RELATED: RAIL-3277 Make tiger error interceptor more robust

---

libs/sdk-ui/src/base/react/ErrorComponent.tsx

- Get custom height only when `enableCompactSize` is enabled.
---
--- …

Fix error component.

---

README.md
examples/sdk-examples/README.md

* remove mention of registration for live examples
* remove necessity to install `pnpm` globally,
the official rush docs do not mention it anymore
JIRA: RAIL-3304
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-nee …

RELATED: RAIL-3304 Fix global readme and the examples readme

---

libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx
libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/KpiView/KpiExecutor.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/types.ts

This allows the users to identify the widget that triggered the drillEvent.
JIRA: RAIL-3092
---
--- …

RELATED: RAIL-3092 Add widgetRef to IDashboardDrillEvent

---

common/changes/@gooddata/sdk-ui-all/RAIL-3307_2021-04-23-09-21.json
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/BackendContext.tsx
libs/sdk-ui/src/base/react/WorkspaceContext.tsx

Add stricter variant of useBackend/useWorkspace hooks for more convenient developer experience,
so it's not necessary to check for undefined values every time.
JIRA: RAIL-3307
---
--- …

Add useBackendStrict / useWorkspaceStrict hooks

---

tools/catalog-export/src/index.ts

This is to make getting the workspace id easier for the user.
Relevant PR in create-gooddata-react-app: https://github.com/gooddata/gooddata-create-gooddata-react-app/pull/96
JIRA: RAIL-2781
---
--- …

RELATED: RAIL-2781 Print out workspace id in catalog-export

---

libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss

This makes sure the widget do not overflow their containers.
JIRA: RAIL-3181
---
--- …

RELATED: RAIL-3181 Fix DashboardView styles

---

common/config/rush/pnpm-lock.yaml
common/config/rush/pnpmfile.js

Fixes rush audit issues related to heroku and webpack. The remaining low priority issue needs more involved changes and will be tracked separately.
---
--- …

RELATED: RAIL-3268 fix some rush audit issues

---

examples/sdk-examples/src/examples/execution/UseDataViewAttributeValuesExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewWithCustomVisualizationExample.tsx
examples/sdk-examples/src/examples/execution/UseDataViewWithSlicesExample.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/BackendContext.tsx
libs/sdk-ui/src/base/react/WorkspaceContext.tsx
libs/sdk-ui/src/base/react/tests/useCancelablePromiseUtils.test.ts
libs/sdk-ui/src/base/react/useCancelablePromiseUtils.ts
libs/sdk-ui/src/execution/ExecuteInsight.tsx
libs/sdk-ui/src/execution/index.ts
libs/sdk-ui/src/execution/useExecutionDataView.ts
libs/sdk-ui/src/execution/useInsight.ts
libs/sdk-ui/src/execution/useInsightDataView.ts
libs/sdk-ui/src/execution/withExecution.ts

- Add ExecuteInsight component, which makes it easier to get data for a specific insight
- Add useInsightDataView hook as an alternative to ExecuteInsight component
- Add useExecutionDataView hook, which makes it easier to get data for a specific execution (combines useExecution & useDataView hooks and also supports an interface for execution similar to the Execution component)
- Add few utility functions for easier useCancelablePromise composition
JIRA: RAIL-2739
---
--- …

Extension of execution components and hooks

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx

* RAIL-3302 - prevent inconsistent state in certain LCM scenarios
* RAIL-3308 - improve UX of insight title when provided as a constant
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner …

RELATED: RAIL-3302, RAIL-3308 small InsightView fixes

---

libs/sdk-ui-geo/package.json
libs/sdk-ui-tests/package.json

This version fixes an issue with attribution icon missing in 1.12.0.
The 1.13.1 was already used by the SDK (so no changes to the lockfile).
We pin mapbox-gl to newer version so that our users are not affected
by the bug as well.
JIRA: RAIL-3317
---
--- …

RELATED: RAIL-3317 Pin mapbox-gl to ^1.13.1

---

libs/sdk-ui-charts/src/highcharts/ChartTransformation.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/responsive.ts

After removal of few shouldComponentUpdate checks in https://github.com/gooddata/gooddata-ui-sdk/commit/e1ce6ad65b594f275acfc1af16ad015e8ff95a2d performance during window resize dropped significantly. Tried to fix it by using memo for whole component
JIRA: ONE-4999
--- …

Improve performance of ChartTransformation component

---

libs/sdk-backend-base/src/decoratedBackend/execution.ts

Added warnings property to decorated data view.

---

libs/sdk-backend-tiger/src/convertors/toBackend/afm/DimensionsConverter.ts
libs/sdk-model/src/execution/base/dimension.ts
libs/sdk-model/src/execution/buckets/bucketArray.ts
libs/sdk-model/src/execution/buckets/index.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartAxes.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts
libs/sdk-ui-ext/src/dashboardView/contexts/DashboardAlertsContext.tsx
libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/data.ts
libs/sdk-ui-pivot/src/impl/data/rowFactory.ts
libs/sdk-ui-pivot/src/impl/structure/colDefFactory.ts
libs/sdk-ui-pivot/src/impl/structure/colSortItemMatching.ts
libs/sdk-ui-pivot/src/impl/structure/headers/aggregationsMenuHelper.ts
libs/sdk-ui-pivot/src/impl/structure/tableDescriptor.ts
libs/sdk-ui/src/base/results/internal/definitionMethods.ts
libs/sdk-ui/src/base/results/internal/resultMetaMethods.ts
libs/sdk-ui/src/base/vis/drilling.ts
tools/applink/src/devConsole/ui/packageList.ts

If a pivot table has more than one sort and their order is different
than the order of columns, the mismatch triggers an infinite loop.
This makes sure the order of sorts is the same as the order of columns
(not the order in which the col defs were created).
Also, replace all the Array.prototype.findIndex calls with lodash version to keep IE compatibility.
JIRA: RAIL-3319
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contrib …

RELATED: RAIL-3319 Fix pivot tables with multiple sorts

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/package.json
libs/api-client-bear/package.json

Makes sure that both node-fetch and isomorphic-fetch are up-to-date
in our depenendencies. This change is safe:
* breaking changes in node-fetch do not affect us
* the browser fetch used by isomorphic-fetch is the same
as in the previous version of it (3.6.2)
This will unfortunately not solve the security issue because
fixed-data-table-2 has a transitive dependency (unused)
on node-fetch 1.7.3.
However, this makes the wrong node-fetch version bound to only
fixed-data-table-2 so once it is upgraded, the security issue will be
solved automatically (there is a ticket for the upgrade already).
JIRA: RAIL-3311
---
| …

RELATED: RAIL-3311 Upgrade node-fetch and isomorphic-fetch

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts

The flag `supportsGenericDateAttributeElements` indicates whether backend supports returning of the valid elements (values) for generic date attributes (Day of Week, Month of Year, etc.) or not.
JIRA: BB-2913
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contri …

Add a new backend capability flag

---

libs/sdk-ui-pivot/styles/scss/pivotTable.scss

Fix IE11 visible pivot table sticky header when it should not be

---

libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/index.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/sizing.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/DashboardLayout/utils/tests/sizing.test.ts

Because visualization type can be changed in AD for existing widget on dashboard we need to handle invalid sizes caused by this (eg. widget of minimal size for Headline displays Headmap after change in AD) to ensure proper UX
JIRA: ONE-4916
---
--- …

Validate widget size on dashboard data load

---

libs/api-client-bear/src/xhr.ts

This is not valid anymore and causes a warning in webpack 5, see [1].
[1] https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a- …

TRIVIAL: Avoid named imports from JSON files

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts
libs/sdk-ui-vis-commons/src/legend/PopUpLegend/LegendDialog.tsx
libs/sdk-ui-vis-commons/styles/scss/legend.scss

- legend label for treemap
- legend fills whole popup
- bring popup to the front
- avoid closing parent overlay
Also includes part of the fix for RAIL-2048 related to icons
---
--- …

RELATED: ONE-5015 ONE-5017 ONE-5022 Fix pop-up legend

---

common/scripts/ci/init_hotfix_branch.sh
common/scripts/ci/utils.sh

Creates a branch for prerelease version hotfixes (prod patch release
job for this will come in a separate PR).
Tested on cing-dev for both first hotfix and subsequent hotfixes.
JIRA: RAIL-3393
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do …

RELATED: RAIL-3393 Add job for automatic creation of hotfix branches

---

common/scripts/ci/run_patch_release.sh
libs/sdk-backend-tiger/package.json
libs/sdk-backend-tiger/src/auth.ts

This is done with backwards compatibility in mind.
Also add patch release job.
JIRA: RAIL-3354
---
--- …

RELATED: RAIL-3354 Adapt to the new logout flow in Tiger 1.1

---

libs/sdk-ui-kit/src/Menu/menuOpener/MenuOpenedByClick.tsx
libs/sdk-ui-kit/src/Menu/tests/Menu.test.tsx
libs/sdk-ui-kit/src/Menu/utils/OutsideClickHandler.tsx

The original solution was easier but failed when outside click stopped click event propagation. Menu was not closed in this case.
The comment in the code described alternative solution that handle it. The new reworked click handling should work now also in this rare case. The original explanation comment was left in place (and slightly altered to match the new situation) as it adds a lot of context and information for future component maintenance.
JIRA: BB-2940
---
--- …

Close menu when outside click cancels event bubble

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/responsive.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/test/common.test.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/barChart/barConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/columnChart/columnConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/lineChart/lineConfiguration.ts

Both single and dual axes charts options use notation with array as value not an object
JIRA: ONE-5021
---
--- …

Change the way how axes options are modified to support multiple axes

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/index.ts
libs/api-model-bear/src/meta/GdcMetadataObject.ts
libs/api-model-bear/src/report/GdcReport.ts

- create report type
- create reportDefinition type
JIRA: RAIL-2974
---
--- …

RAIL-2974 Report and ReportDefinition types

---

libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx
libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/utils.ts

- ignore global date filters for insights with simple measures that have date filter(s) set
JIRA: RAIL-3339
---
--- …

DashboardView - align filtering logic with gdc-dashboards

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/setupDrilldownToParentAttribute.ts

JIRA: ONE-5030
During zooming to the chart, some of datapoints are undefined and needs to be skipped
---
--- …

Handle undefined point in Zoomed chart

---

libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx

- 2 insights rendered in 1 row caused DashboardView height to grow infinitely
JIRA: RAIL-3416
---
--- …

DashboardView - fix possible infinite height grow

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartLegendRenderer.tsx
libs/sdk-ui-geo/src/core/geoChart/legends/PushpinCategoryLegend.tsx
libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
libs/sdk-ui-vis-commons/src/legend/PopUpLegend/PopUpLegend.tsx
libs/sdk-ui-vis-commons/src/legend/StaticLegend.tsx

Popup legend shows different title for different content.
In case of geo chart with custom component, it's the size metric name.
---
--- …

RELATED: ONE-5031 Fix geo legend title and paging

---

libs/sdk-ui-charts/src/charts/xirr/Xirr.tsx
libs/sdk-ui-charts/src/charts/xirr/internal/utils/XirrTransformationUtils.ts

Also fix an eslint warning
JIRA: RAIL-3420
---
--- …

RELATED: RAIL-3420 Document XIRR Date parsing and add a TODO

---

examples/playground/webpack.config.js

-  Due to bug in webpack dev server. See https://github.com/webpack/webpack-dev-server/pull/3271
JIRA: RAIL-3383
---
--- …

RELATED: RAIL-3383 - Fix live reload issue

---

libs/sdk-ui-tests/.storybook/main.js

We do not need the deprecated feature, so we opt-out explicitly.
JIRA: FET-751
---
--- …

RELATED: FET-751 Prevent Storybook deprecation warning

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialog.tsx
libs/sdk-ui-kit/src/Dialog/Dialog.tsx
libs/sdk-ui-kit/src/Dialog/ExportDialog.tsx
libs/sdk-ui-kit/src/Dialog/tests/ConfirmDialog.test.tsx
libs/sdk-ui-kit/src/Dialog/tests/Dialog.test.tsx
libs/sdk-ui-kit/src/Dialog/tests/ExportDialog.test.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts

Allow pass containerClassName to dialogs

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/handler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/loadDashboardConfig.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/loadDashboard/loadPermissions.ts
libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/permissions/index.ts
libs/sdk-ui-dashboard/src/model/state/permissions/permissionsReducers.ts
libs/sdk-ui-dashboard/src/model/state/permissions/permissionsSelectors.ts
libs/sdk-ui-dashboard/src/model/state/permissions/permissionsState.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts

-  Permissions can be provided on input (as optimization in multi-dashboard contexts)
-  The config loading now correctly identifies if the entire config has values resolved and if not fills in the gaps. the config values take precedence and will be kept, however whatever is missing will be loaded from backend
---
--- …

RELATED: RAIL-3383 - Add permissions to state & sanitize config resolution and loading

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/measure/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

Allow to set measure id when creating.
[RAIL-3426](https://jira.intgdc.com/browse/RAIL-3426)
---
--- …

RELATED: RAIL-3426 Allow edit measure identifier

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts

Replace cloneDeep in chart config creation with spread operator
Fix types where possible
---
--- …

RELATED: ONE-5045 ONE-5046 ONE-5047 Remove cloneDeep from charts

---

libs/sdk-ui-geo/src/core/geoChart/legends/PushpinCategoryLegend.tsx
libs/sdk-ui-geo/src/core/geoChart/legends/test/PushpinCategoryLegend.test.tsx

When there is also Size legend attribute legend has to have one line less
JIRA: ONE-5033
---
--- …

Allow one line less to attributes legend

---

common/config/rush/pnpm-lock.yaml
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonExample.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonWithPlaceholder.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterExample.tsx
examples/sdk-examples/src/examples/attributeFilter/index.tsx
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/package.json
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilter.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- add attribute parent child filtering suport to AttributeFilter component
- example with parent child filtering
- add parentFilters optional property
- add parentFilterOverAttribute optional property
- add FilterError optional property
- introduced useDeepEffect hook in SDK
- modified loadAttributes functuin to consider parent filters
- introduced default FilterError property value
- example with AttributeFilterButton parent-child filtering
JIRA: RAIL-3406
---
--- …

RAIL-3406 attribute parent child filtering

---

libs/sdk-ui-kit/src/responsive/useMediaQuery.ts

Breakpoint for mobile devices should be <= breakpoints.sm it
was <= breakpoints.xs by mistake and it caused problems in KD
JIRA: FET-719
---
--- …

Change mobile device breakpoint

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss
libs/sdk-ui/src/base/react/LoadingComponent.tsx

Now there is a loading shown properly over the "old" visualization.
Also prevent unnecessary any cast in LoadingComponent.
JIRA: RAIL-3488
---
--- …

RELATED: RAIL-3488 Fix InsightView styles when switching insights

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/PluggableColumnBarCharts.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketRules.ts

RELATED: ONE-5070 Chart contains stack by should not be added 2 measures

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartDrilling.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartSeries.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/__snapshots__/chartOptionsBuilder.test.ts.snap
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bubbleChart/bubbleChartSeries.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/bulletChartSeries.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/bulletChart/test/__snapshots__/bulletChartOptions.test.ts.snap
libs/sdk-ui-charts/src/highcharts/chartTypes/heatmap/heatmapChartSeries.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/scatterPlot/scatterPlotSeries.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/treemap/treemapChartSeries.ts
libs/sdk-ui-charts/src/highcharts/typings/unsafe.ts

Make drill aware of hidden points on hidden bubble charts.
JIRA: ONE-5068
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in …

Make drill aware of hidden points on bubble charts

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx
libs/sdk-ui-ext/styles/internal/scss/dashboard_embedding.scss

Changing the div can have unforeseen consequences like the visualization
rendering multiple times. So we avoid it and implement the concern
this was introduced for in the parent component (making sure that
loading component is 100% of the height if shown).
Also, avoid passing irrelevant props to InsightRenderer from InsightView.
This makes the InsightRenderer re-render only if needed.
JIRA: RAIL-3488
---
--- …

RELATED: RAIL-3488 Avoid changing visualization-uri-root div

---

libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/lineChartUiConfigHelper.ts

- disallow adding measures when date is put in segment by
---
--- …

RELATED: ONE-5080 LineChart uiConfig: Correctly enable/disable adding of measures

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/measureNumberFormat/MeasureNumberFormat.tsx
libs/sdk-ui-kit/src/measureNumberFormat/typings.ts

Allow to customize measure number format button text by adding selected option as property to toggle button
---
--- …

RELATED: RAIL-3464 Allow to customize measure number format button text

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/tests/AttributeDropdown.test.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx

This fixes issues with missing icons and removes another goodstrap dep.
Dropdown in sdk-ui-kit was extended with a new prop with a default
that maintains the original behavior.
JIRA: RAIL-3498
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do …

RELATED: RAIL-3498 Migrate AttributeDropdown away from goodstrap

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts

Disable data labels on Heatmap charts for big series.
JIRA: ONE-5048
---
--- …

RELATED: ONE-5048 Heatmap disable data labels for large series to improve performance

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/constants/uiConfig.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts

RELATED: ONE-5076 and ONE-5077 Stack area chart bug fixes and new switch rules implemented 

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/CatalogConverter.ts

- This is causing blank screen for insights with date attribute buckets in AD as it implicitly depends on them
JIRA: NAS-149
---
--- …

Fix missing date attribute display forms on tiger

---

libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/__snapshots__/toAfmResultSpec.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/afm/tests/toAfmResultSpec.test.ts
libs/sdk-model/src/execution/executionDefinition/factory.ts
libs/sdk-model/src/execution/executionDefinition/tests/__snapshots__/validation.test.ts.snap
libs/sdk-model/src/execution/executionDefinition/tests/validation.test.ts
libs/sdk-model/src/execution/executionDefinition/validation.ts
libs/sdk-ui-charts/src/charts/comboChart/tests/ComboChart.test.tsx

Currently just validates that the localIds are unique among measures and attributes.
This is to improve the error message (before, a generic 400 would be
thrown) and to not try to execute definitions that are certain to fail.
This helped us find a few test fixtures that were invalid, so they were fixed.
JIRA: RAIL-2392
---
---
-   [ ] …

RELATED: RAIL-2392 Validate localIds in execution definitions

---

common/scripts/build-docs.sh
examples/sdk-examples/src/examples/theming/index.tsx
tools/catalog-export/package.json
tools/catalog-export/src/transform/tests/__snapshots__/toTypescript.test.ts.snap
tools/catalog-export/src/transform/toTypescript.ts
tools/experimental-workspace/src/ldm/full.ts
tools/live-examples-workspace/src/ldm/full.ts
tools/reference-workspace/src/ldm/full.ts

* RAIL-3497 - do not generate "count" aggregations for Facts in catalog-export - it never made sense and would bomb
* RAIL-3502 - improve text legibility in Theme examples
* RAIL-3511 - exclude sdk-ui-dashboard from apidocs builds
---
--- …

RELATED: RAIL-3497, RAIL-3502, RAIL-3511 small tweaks and fixes

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/PluggableColumnBarCharts.test.tsx
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts

RELATED: ONE-5099 Use dates when switching to column/bar charts

---

common/config/rush/command-line.json
common/scripts/build-docs.sh

To be able to run build-docs in a CI context, we need it to take
the version value from CLI (not interactively).
JIRA: RAIL-3511
---
--- …

RELATED: RAIL-3511 Allow build-docs to take a CLI parameter

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx

- disable date priority while switching from any chart to area chart in getExtendedReferencePoint
- bug fix create area chart with one date and one att
JIRA: ONE-5096
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request …

RELATED: ONE-5096 Stacked: Cannot add both date and attribute in View by

---

libs/api-client-bear/src/execution/experimental-executions.ts
libs/api-client-bear/src/execution/tests/experimental-executions.test.ts

- applies during "show in percent"
JIRA: ONE-4983
---
--- …

Do not generate BY ALL condition when attribute missing

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts

RELATED: ONE-5103 Prefer stacks over measures when switching to area

---

common/scripts/ci/docker_apidocs_build.sh
common/scripts/ci/run_apidocs_build.sh

The meat of the work is running in docker because we need node and yarn.
Related PR to ci-infra: https://github.com/gooddata/ci-infra/pull/7548
JIRA: RAIL-3511
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs- …

RELATED: RAIL-3511 Add CI script for api docs build

---

common/config/rush/command-line.json
common/scripts/build-docs.js

This command builds hte apidocs and runs them making previews
of the doc changes easier when developing.
JIRA: RAIL-3511
---
--- …

RELATED: RAIL-3511 Add rush start-doc command

---

examples/sdk-examples/src/examples/export/ExampleWithExport.tsx
libs/sdk-ui-filters/src/DateFilter/Select/VirtualizedSelectMenu.tsx

RAIL-3542 - prevent react-dom warning
RAIL-3543 - fix export examples
---
--- …

RELATED: RAIL-3543, RAIL-3542 minor examples fixes

---

libs/sdk-ui-ext/src/dashboardView/DashboardRenderer.tsx

Add same CSS class as in KD.
Without this class, nested CSS classes that depends on this "parent" class are not setting 100% height,
and without setting 100% height, react-measure does not work correctly - this is the root cause of the issue.
JIRA: RAIL-3531
---
--- …

Fix invisible Kpi components by adding missing CSS class

---

libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

Since tiger does not support withAttributeFilters, avoid using it
unless absolutely necessary.
JIRA: RAIL-3548
---
--- …

RELATED: RAIL-3548 Fix AttributeFilterButton on tiger

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- disable apply button logic modification
JIRA: RAIL-3549
---
--- …

RAIL-3549 Attribute filtering bugfix

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx

- We do not suppor drill from XIRR Visualization
- clear availableDrillTargets attributes in push data
JIRA: TNT-75
---
--- …

Remove availableDrillTargets attributes from XIRR visualisation

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderAccountMenuItems.ts
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderAccountMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
libs/sdk-ui-kit/src/Header/tests/mock.ts

- we will return workspace instead of project and workspaces instead of projects in uri of item if enableRenamingProjectToWorkspace
JIRA: SD-1696
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a- …

Rename project to workspace base on enableRenamingProjectToWorkspace

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/dashboard/types.ts
libs/sdk-ui-dashboard/src/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/react/DashboardStoreProvider.tsx
libs/sdk-ui-dashboard/src/model/react/index.ts
libs/sdk-ui-dashboard/src/model/react/types.ts
libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/widget/kpi/DashboardKpi.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/ClientWorkspaceContext/ClientWorkspaceContext.tsx
libs/sdk-ui/src/base/react/ClientWorkspaceContext/interfaces.ts
libs/sdk-ui/src/base/react/ClientWorkspaceContext/resolveLCMWorkspaceIdentifiers.ts
libs/sdk-ui/src/base/react/usePrevious.ts
libs/util/src/index.ts
libs/util/src/objectUtils.ts
libs/util/src/tests/objectUtils.ts

- Add ability to use dataProduct / client identifiers instead of the workspace identifier itself
- Allow parsing of the workspace identifier to dataProduct / client / segment identifiers
- Add LCMProvisionedWorkspaceProvider and relevant hooks
- Add usePrevious hook
- Fix dashboard re-initializing - cancel running sagas and recreate store with the correct context.
JIRA: RAIL-3533
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs …

Add context for workspaces provisioned via LCM

---

libs/sdk-ui-dashboard/src/filterBar/DefaultFilterBar/DefaultDashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/widget/insight/DefaultDashboardInsight/useResolveDashboardInsightFilters.ts
libs/sdk-ui-ext/src/dashboardView/DashboardWidgetRenderer/InsightRenderer/InsightRenderer.tsx

- Update insight on filters change (now, when the insight filters change, they are not updated)
JIRA: RAIL-3533
---
--- …

Fix InsightRenderer insight memoization

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/metadata/objRefMap.ts
libs/sdk-ui-dashboard/src/_staging/metadata/tests/objRefMap.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addSectionItemsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/common/loadMissingInsights.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/insights/insightsSelectors.ts

-  ObjRefMap can now handle cases when object being inserted has id, uri or both
-  the new factory function `newMapForObjectWithRef` allows simple creation of maps for arbitrary objects
that contain just `ref` property. Such map will extract the essentials from the ref and is ready for
refs that are both uriRef and identifierRef
-  Testing what insights are available was not correctly checking refs
JIRA: RAIL-3560
---
--- …

RELATED: RAIL-3560 - Expand ObjRefMap to allow storing any object that has `ref`

---

libs/sdk-ui-pivot/src/impl/drilling/drillTargets.ts
libs/sdk-ui-pivot/src/impl/drilling/tests/__snapshots__/drillTargets.test.ts.snap

JIRA: TNT-87
As tables fully support frill from attribute even on row attribute elements, drill intersection is not containing all attributes but only attribute itself and its parents
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-i …

Table's attributes offer only limited set of intersection attributes

---

libs/sdk-ui-dashboard/src/_staging/metadata/objRefMap.ts
libs/sdk-ui-dashboard/src/_staging/metadata/tests/objRefMap.test.ts

-  Its nonsense to have entries that only have uri and not id; this was a miss in the previous PR
-  All entries must contain id, uri, and ref
-  The newMapForObjectWithRef has extractors that do invariant checks
-  This way, the expectation/contracts from ObjRefMap can be stable; otherwise stuff can enter the map
but can never be looked up by both id or uri
JIRA: RAIL-3560
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …

RELATED: RAIL-3560 - Sanitize ObjRefMap to better match expectations

---

libs/sdk-ui-pivot/src/impl/drilling/drillTargets.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/legacy/availableDrillTargets.ts
libs/sdk-ui/src/base/react/legacy/tests/__snapshots__/availableDrillTargets.test.ts.snap

JIRA: TNT-87
Even that charts currently support only drill from data point which offers full intersection it could lead to the invalid drill to uri definitions in future once the drill from axis label will be supported. From this reason we decided to provide only intersection attributes working also with drill from labels - attributes from same dimension as origin and limited to the origin itself and his parents. The same is already done for pivot table
---
--- …

Chart's target attribute has just subset of attributes in intersection

---

libs/sdk-ui-pivot/src/impl/cell/cellClass.ts
libs/sdk-ui-pivot/src/impl/stickyRowHandler.ts
libs/sdk-ui-pivot/src/impl/tests/stickyRowHandler.test.ts
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

JIRA: TNT-42
When attribute is drillable only grouped element label has drill styling and is clickable. Hidden element copies beneath it are without mouse events. Drill event payload contains row corresponding to the currently first visible row (current scroll position) next to the clicked grouped element
---
--- …

Proper drill styling of stacked attribute element and sticky row

---

libs/sdk-backend-bear/src/backend/workspace/insights/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/dashboards.ts
libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/tests/__snapshots__/DashboardConverter.test.ts.snap
libs/sdk-backend-bear/src/convertors/toBackend/InsightConverter.ts
libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts
libs/sdk-backend-mockingbird/src/recordedBackend/insights.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/dashboard.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/v2/VisualizationObjectConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/InsightConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/index.ts
libs/sdk-model/src/insight/index.ts

* Add tags property to `IListedDashboard` and `IInsightDefinition` types and fill them
* Make sure that on tiger, only relevant data is passed to the free form insight content by being explicit about it
* Provide default value for the `limit` setting on bear getInsights - without it the server returns 400 errors
---
---
-   [ ] review …

RELATED: RAIL-3752, RAIL-3557 add tags to listed dashboards and insights

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/DateTime.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/datetime.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/test/repeat.test.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/DateTime.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/ScheduledMailDialog/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/utils/datetime.ts
libs/sdk-ui-ext/src/internal/dashboardEmbedding/ScheduledMail/utils/test/repeat.test.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-kit/src/Timepicker/tests/Timepicker.test.tsx

- Fix generating recurrency string for Sunday
- Fix recurrency string after changing date
- Fix dialog behaviour after changing time (time normalization)
Add `skipNormalizeTime` optional property for Timepicker component (default=false) which allows using values exactly as they were passed without using the normalization.
The state management of _ScheduledMailDialogRenderer_ component should probably be reworked so that recurrence data is not stored on `this`, separated to FET-794.
---
---
-   [ ] commit …

RELATED: TNT-74 TNT-102 TNT-105 Fix KPI dashboard schedule dialog

---

libs/sdk-ui-pivot/src/impl/data/dataSource.ts

Currently only the [first page](https://github.com/gooddata/gooddata-ui-sdk/blob/fbdd52cd3cba2fcd668cb287526b513391f3fe14/libs/sdk-ui-pivot/src/impl/data/dataSource.ts#L157) is processed, this fix applies the processing to other virtual pages as well, fixing the missing (empty value) string on these pages.
JIRA: TNT-1
---
---
-   [ ] …

RELATED: TNT-1 Transform table data also when requesting additional rows

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui/src/base/localization/bundles/de-DE.json
libs/sdk-ui/src/base/localization/bundles/en-US.json
libs/sdk-ui/src/base/localization/bundles/es-ES.json
libs/sdk-ui/src/base/localization/bundles/fr-FR.json
libs/sdk-ui/src/base/localization/bundles/ja-JP.json
libs/sdk-ui/src/base/localization/bundles/nl-NL.json
libs/sdk-ui/src/base/localization/bundles/pt-BR.json
libs/sdk-ui/src/base/localization/bundles/pt-PT.json
libs/sdk-ui/src/base/localization/bundles/zh-Hans.json

* Fix subtitle for empty attributes
* Display proper NoData message if opened
---
--- …

RELATED: RAIL-3580 Improve AttributeFilterButton empty attribute handling

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/drills/InsightDrillDefinitionUtils.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/removeDrillsForInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/removeDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/removeDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/removeDrillsSelectorValidation.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/commands/insight.ts
libs/sdk-ui-dashboard/src/model/tests/Dashboard.fixtures.ts

- add removeDrillsForInsightWidgetHandler
- fix DashboardInsightWidgetDrillsRemoved event definition
- fix RemoveDrillsForInsightWidget command definition
JIRA: RAIL-3589
---
--- …

Handle removing drill definition

---

libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/render/tests/__snapshots__/renderingWorker.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/render/tests/renderingWorker.test.ts

- Allow to fire multiple async rendering requests for the same component before the resolution
- This makes it more fault-tolerant (eg PivotTable for some reason fires onLoadingChanged with loading: true multiple times)
- Issue was when requests & resolved events count did not match
---
--- …

Dashboard component: make the rendering worker more fault tolerant

---

libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

---
we will change workspaceProjectDashboardPage instead of projectProjectDashboardPage in uri of item if enableRenamingProjectToWorkspace
JIRA: SD-1673
--- …

rename projectDashboardPage to workspaceDashboardPage

---

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

- Omit default drill when drillableItems are provided and use them instead
---
--- …

Dashboard component: fix Kpi widget with drillable items

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/eventHandler.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/_infra/rootEventEmitter.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/meta/metaSelectors.ts

This allows the callers to read data from the dashboard state
from the event handlers.
Also add selectDashboardIdRef analog for selectDashboardUriRef.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request …

RELATED: RAIL-3385 Add selector evaluator to event handlers

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

Add a missing withTelemetry call and enrich it with a way to log the type of the visualization rendered.
Memoization is not needed as the value would change on almost any change to props and state. This means this will not introduce new re-renders (they happen anyway because the props or state change).
Sample of the headers now
```
X-GDC-JS-SDK-COMP: InsightView
X-GDC-JS-SDK-COMP-PROPS: insight,showTitle,backend,workspace,intl,ErrorComponent,filters,drillableItems,LoadingComponent,TitleComponent,pushData,visualizationUrl_local:table
```
JIRA: RAIL-3599
---
| …

RELATED: RAIL-3599 Fix InsightView telemetry

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/WithDrillSelect.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightCore.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsightWithDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsightWithDrillSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsightWithDrillableItems.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/useDashboardInsightDrills.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DashboardKpi.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DashboardKpiCore.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DefaultDashboardKpi.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DefaultDashboardKpiWithDrillableItems.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DefaultDashboardKpiWithDrills.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/index.tsx
libs/sdk-ui-dashboard/src/types.ts

- Enable granular drill events only in case the drillableItems are not provided
- Unify Kpi/Insight drill events (send drill definitions to the generic drill event without relation to the input drillableItems)
- Fire generic drill event also for Kpi as the first event (to unify it with insight widget drills)
- Preserve correlationId across whole drill eventing chain
- Separate components / make them more consistent for kpi/insight widgets
---
--- …

Dashboard component - unify/improve drill eventing

---

libs/api-client-bear/src/xhr.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/changeDateFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/userInteraction/userInteractionHandler.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/commands/userInteraction.ts
libs/sdk-ui-dashboard/src/model/events/filters.ts
libs/sdk-ui-dashboard/src/model/events/userInteraction.ts
libs/sdk-ui-dashboard/src/model/react/index.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

The command and event was reworked to allow passing extra data fro them.
Also an issue with dateFilterSelectionChanged event with All time filter fixed – now the all time filter is represented as undefined (this is in line with other places in the package).
Finally, a minor warning text content was fixed.
---
--- …

RELATED: RAIL-3385 Add user interactions for kpi alert dialog

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/moveAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/removeAttributeFiltersHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/setAttributeFilterParentHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addSectionItemsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/changeLayoutSectionHeaderHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveSectionItemHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/removeLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/removeSectionItemHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/replaceSectionItemHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/undoLayoutChangesHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetFilterSettingsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillsForInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/removeDrillsForInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/modifyDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/removeDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/modifyDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/removeDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/filterValidation.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/removeDrillsSelectorValidation.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/widgetValidations.ts
libs/sdk-ui-dashboard/src/model/events/general.ts

This will help the event handlers to see what type of command failed.
That in turn makes use cases like logging errors and similar easier.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appro …

REALTED: RAIL-3385 Add failed command to DashboardCommandFailed event

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

- When an error is found that means table has been loaded, so need to update state accordingly.
JIRA: TNT-131
---
--- …

Update PivotTable loading state when an error occurs.

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/drills/InsightDrillDefinitionUtils.ts
libs/sdk-ui-dashboard/src/_staging/drills/test/InsightDrillDefinitionUtils.test.ts
libs/sdk-ui-dashboard/src/_staging/drills/test/__snapshots__/InsightDrillDefinitionUtils.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/modifyDrillsForInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/modifyDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/__snapshots__/removeDrillsForInsightWidgetHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/modifyDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/removeDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/validation/insightDrillDefinitionValidation.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/listedDashboards/listedDashboardsSelectors.ts
libs/sdk-ui-dashboard/src/model/tests/Dashboard.fixtures.ts

- modify modifyDrillsForInsightWidgetHandler
- add DrillToDashboard and DrillToInsight
RAIL: RAIL-3564
---
--- …

Validate DrillToDashboard and DrillToInsight definition items

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/activateHeaderMenuItems.ts
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/index.ts
libs/sdk-ui-kit/src/Header/tests/activateHeaderMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts

Possibility to add "Measures" link into Header bar.
Refactor of generateHeaderMenuItemsGroups due to cyclomatic complexity
Introduce constant variables for IDs
**Added method for marked items in Header as active**
_For example:_
```typescript
return activateHeaderMenuItems(groups, [HEADER_ITEM_ID_ANALYZE]);
```
---
---
-   [ ] review …

FEATURE: NAS-229 Add Measures to header bar

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/tests/__snapshots__/handler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/tests/handler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/render/tests/__snapshots__/renderingWorker.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/render/tests/renderingWorker.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/rootCommandHandler.ts
libs/sdk-ui-dashboard/src/model/events/base.ts
libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap
libs/sdk-ui-dashboard/src/model/queryServices/tests/queryWidgetFilters.test.ts
libs/sdk-ui-dashboard/src/model/state/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/dateFilterConfig/dateFilterConfigSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightCore.tsx

Also
* fix misleading invariant messages
* add correlation id to renderRequested and renderResolved events so that we can correlate those together
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a …

RELATED: RAIL-3385 add action timestamping

---

libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-base/src/dummyBackend/tests/index.test.ts
libs/sdk-backend-mockingbird/api/sdk-backend-mockingbird.api.md
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/tests/index.test.ts
libs/sdk-backend-mockingbird/src/recordedBackend/types.ts

Implementing of not supported method getDescriptor on dummyBackend and recordedBackend
Added method for generating dummy descriptor for dummy and recorded backend that returns descriptor with given workspace id and setting of workspace based on provided config.
JIRA: NAS-229
---
--- …

RELATED: NAS-229 Implementing of not supported method getDescriptor

---

libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx

Also makes the default items' ids in line with KD to maintain
the existing test selectors.
---
--- …

RELATED: RAIL-3385 Add s- classes to the menu button items

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderMenuItemsGroups.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderMenuItemsGroups.test.ts
libs/sdk-ui-kit/src/utils/featureFlags.ts
libs/sdk-ui-kit/src/utils/tests/featureFlags.test.ts

Can not call .toString() on property that is defined as optional. Remove this call because is not necessary.
Method isFreemiumEdition can have also undefined as parameter due to specification of types in featureFlags.ts
JIRA: NAS-229
---
--- …

TRIVIAL: NAS-229 Repair of optional feature flag and .toString() call

---

libs/api-client-bear/src/xhr.ts

Previously, when an unauthorized user called the logout function,
it would result in two failed /gdc/account/token requests:
1. call caused by the isLoggedIn call in the logout function
2. call caused by the first one failing and the logic that tries to refresh the token kicking in
The second one is unnecessary because if the first fails, the second
will fail as well every time. This makes network log unnecessarily fuzzy
which complicates debugging/support.
So, similarly to /gdc/account/login, we now no longer try to recover
the requests /gdc/account/token either.
JIRA: RAIL-3534
---
| `extended test` …

RELATED: RAIL-3534 Prevent duplicate token requests in bear

---

libs/sdk-ui-dashboard/src/presentation/layout/EmptyDashboardError.tsx
libs/sdk-ui-ext/src/dashboardView/DashboardView.tsx
libs/sdk-ui-ext/src/dashboardView/EmptyDashboardError.tsx
libs/sdk-ui-ext/src/internal/translations/en-US.json

- With new delete insight from AD, dashboard can now exist but without any layout.
- Adapt it so it behaves correctly when layout is empty.
JIRA: TNT-26
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approva …

DashboardView handles empty dashboard layout

---

libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/layout/types.ts

This makes the "Apply alert filters to dashboard" button work.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-cod …

RELATED: RAIL-3385 Add missing onFiltersChange prop to DashboardLayout

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

Now the correct error object is passed to the callback.
JIRA: RAIL-3621
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner …

RELATED: RAIL-3621 Fix InsightView onError handling

---

libs/sdk-backend-tiger/src/convertors/fromBackend/InsightConverter.ts
libs/sdk-backend-tiger/src/convertors/tests/ObjectConverter.test.ts
libs/sdk-backend-tiger/src/types/refTypeMapping.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/objRef/index.ts

There is insight and visualizationObject ObjectType value.
This duplicity made the Dashboard component fail on Tiger.
A ticket for removing the "visualizationObject" value in the next major
was created to track the clean up.
---
--- …

RELATED: RAIL-3385 Fix ambiguous idRef type

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToCustomUrlHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts

- thwrow error when some attributes to resolve URL are missing
JIRA: RAIL-3597
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-cod …

ResolveDrillToCustomUrl error handling

---

libs/sdk-embedding/api/sdk-embedding.api.md
libs/sdk-embedding/src/iframe/common.ts
libs/sdk-embedding/src/iframe/kd.ts
libs/sdk-embedding/src/internal/filterValuesResolver.ts
libs/sdk-embedding/src/internal/index.ts

JIRA: TNT-150
Define filterValues resolver and its in/out interfaces
Extend existing IDrillToUrlResolvedDataBody by optional resolvedFiltervalues key
---
--- …

Resolver interface and extended postMessage payload

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdownList.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

Fixes issues with the AttributeFilterButton:
* paging now works properly
* search now works properly (incl. when nothing matches search)
Also fixes paging inssue in AttributeFilter
---
--- …

RELATED: RAIL-3620 fix paging of AttributeFilterButton

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/CompactContentError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/CustomError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/DataTooLargeError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/ErrorContainer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/ExecuteProtectedError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/NoDataError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/OtherError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/sizingUtils.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/tests/sizingUtils.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightCore.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx

* RAIL-3625 - prevent stale No data errors in insighs and empty No data states in KPIs
* RAIL-3626 - migrate custom insight error components from gdc-dashboards
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/ma …

RELATED: RAIL-3625, RAIL-3626 improve error handling

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/fileUtils/downloadFile.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/hooks/useDashboardPdfExporter.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightCore.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillModalExportOptions.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillModalFooter.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/useDrillExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/useExportHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts

Ports the Export drilled insight feature from gdc-dashboards (simplifying the code in some places).
As part of the change some localization strings were aligned with gdc-dasbhoards in order to be usable for PDF and non-PDF exports (as they are in gdc-dashboards).
Finally, a missing protected data error handling in exports was added.
---
--- …

RELATED: RAIL-3627 port Export drilled insight feature

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx

This now covers more cases (e.g. non empty layout without content in columns).
JIRA: RAIL-3635
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-a …

RELATED: RAIL-3635 fix detection of empty dashboards

---

libs/sdk-ui-dashboard/src/_staging/dateFilterConfig/dateFilterOptionMapping.ts
libs/sdk-ui-dashboard/src/_staging/dateFilterConfig/tests/dateFilterOptionMapping.test.ts
libs/sdk-ui-dashboard/src/_staging/dateFilterConfig/tests/fixtures.ts

Make sure that both strings and numbers are matched.
JIRA: RAIL-3661
---
--- …

RELATED: RAIL-3661 Fix and test date filter option mapping

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DashboardKpiCore.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiRenderer.tsx

KPIs should not use the custom ErrorComponent for their execution
errors, they render them instead of the value (not with ErrorComponent).
We need to revisit this to enable customization if needed in the future.
JIRA: RAIL-3645
---
--- …

RELATED: RAIL-3645 Align KPI error behavior with gdc-dashboards

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/loadDashboardHandler/loadCatalog.ts

- fix drill down form generic date attributes
JIRA: RAIL-3640
---
--- …

Change catalog load and add includeDateGranularities definitions

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/moveAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/setAttributeFilterParentHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/state/filterContext/filterContextSelectors.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useParentFilters.ts
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilter.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

* The options to specify the parent filters in the SDK filter components was extended to allow us to specify over attribute for every parent separately while not breaking the API
* This extended API was used to make the parent filters work in Dashboard component
* A bug related to the invalidation of the loaded items in AttributeFilterButton was fixed
* Filter-related selectors were rewritten to use the "newer" memoize approach (even thou they were not needed for this bug in the end anyway)
---
| …

RELATED: RAIL-3622 Make the parent filters work in Dashboard component

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToAttributeUrlHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToCustomUrlHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/getDrillToUrlFilters.ts
libs/sdk-ui-dashboard/src/model/events/drill.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/state/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/types.ts

DrillToUrl events should be expanded by filtersInfo which consists of used filters and resolvedFilterValues when filter values resolution is enabled.
JIRA: TNT-151
---
--- …

Add filter context to drillToUrl on dashboard component

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeFilterBody.tsx
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/types.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/index.ts
libs/sdk-ui-kit/src/List/LegacyInvertableList.tsx

* RAIL-3620 - fix paging by handling empty but defined parent filters
* RAIL-3681 - fix handling of not yet loaded vs empty items
The change to the sdk-ui-filters api is safe, in SDK 8.5.0 the EmptyListItem interface was defined using the typeof and the emptyListItem object, so it was effectively the same as it is now.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/do …

RELATED: RAIL-3620, RAIL-3681 attribute filter fixes

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx

* RAIL-3665 - fix error messages in drill to insight
* RAIL-3684 - fix onError callback propagation which made export drilled insight always disabled
---
--- …

RELATED: RAIL-3665, RAIL-3684 export drilled insight fixes

---

libs/sdk-backend-bear/src/backend/workspace/attributes/elements/index.ts
libs/sdk-backend-bear/tests/integrated/__snapshots__/elements.test.ts.snap
libs/sdk-backend-bear/tests/integrated/elements.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/test/__snapshots__/filterValuesResolver.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/test/filterValuesResolver.test.ts

JIRA: TNT-191
Query for ALL attribute filter was getting all attribute elements just to not use them then. Fixed by returning empty array immediately.
---
--- …

Handle ALL filter without unused API calls

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetBrokenAlertsQuery.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

This makes sure the query is properly re-run when alert changes (for example when it is deleted).
Also adds missing shouldRefetch checks for KPI.
JIRA: RAIL-3680
---
--- …

RELATED: RAIL-3680 Fix and simplify useWidgetBrokenAlertsQuery

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/useResolveDashboardInsightProperties.ts

* RAIL-3694 - prevent render loops in DashboardInsight by proper memoization
* RAIL-3695 - fix merging logic of insight properties and widget properties
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/doc …

RELATED: RAIL-3694, RAIL-3695 fix pivot table sizing bugs

---

libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/MetricConverter.ts
libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts
libs/sdk-backend-mockingbird/src/recordedBackend/measures.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/metadata/measure/index.ts
libs/sdk-backend-spi/src/workspace/measures/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/MetricConverter.ts

New sdk-backend-spi method getMeasureReferencingObjects added and used to get the data for measure editor
---
--- …

NAS-150 measure usage

---

libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

Fix typo in metric vs metrics
---
--- …

NAS-150 Measure usage fix typo

---

.envrc
libs/api-client-bear/src/user.ts
libs/api-client-bear/src/xhr.ts

XHR module would get into a state where GET samlrequest would be preceded by POST on the token resource - which would fail and prevent the samlrequest processing from starting.
Unsure how the XHR module can get into the state (it seems intentional but i did not study further). Nevertheless, it makes no sense to try and get the token before calling the samlrequest. 
The code modification is 'surgical' and ensures initiateSamlSso tells XHR module to clear the tokenRequest.
---
| `extended check cypress` …

RELATED: RAIL-3678 - Ensure initiateSamlSso does not fail on failed token request

---

libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

Fix comments in code and return all objects not only included ones
---
--- …

NAS-150 Measure usage fix

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/filterValuesResolver.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/test/__snapshots__/filterValuesResolver.test.ts.snap
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts

JIRA: TNT-200
Granularity is now not used as a key in map and because its value is completely the same as in original filter it can be removed
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …

Remove granularity from date filter resolved values

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFiltersQuery.ts

If a filter that is ignored changes, the widget does not need to run
the filters query again, its results will be the same. To prevent these
wasteful reloads (which also make the UX worse by showing unnecessary
loading animations), the set of non-ignored filters is "cached" for each
widget and this value is then used synchronously (so no loading) to
decide if a new run of the full filters query is necessary.
To get the non-ignored filters, we use the filters query and override
the widget level filters with an empty array so that we only get
dashboard-level filters (without the potential insight-level ones).
Also, a digest of the filters is used to only reload the non-ignored
filters query only when the dashboard filters changed in a way that can
affect the non-ignored filters (the …

RELATED: RAIL-3682 Prevent widget reloads on ignored filters changes

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/Dialog.tsx
libs/sdk-ui-kit/src/Dialog/tests/Dialog.test.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts

Propagate these events
- onClick
- onMouseOver
- onMouseUp
Added these handlers to allow override default stopPropagation behaviour because of meditor monaco editor needs use mouseup handler
JIRA: NAS-328
---
--- …

FEATURE: Optionally propagate mouse events into overlay from dialog

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/useDashboardQueryProcessing.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetBrokenAlertsQuery.ts

We only want to cancel the inflight queries on component unmount to
prevent the react warning, so there is no need to expose the cancel
callback (which was used incorrectly in useWidgetBrokenAlertsQuery,
because it was called on *every* run of the query, not just on unmount).
Now the cancel is handled internally (as it is an internal implementation
detail of that hook) and correctly (only being run on unmount).
JIRA: RAIL-3680
---
---
-   [ ] …

RELATED: RAIL-3680 Fix useDashboardQueryProcessing cancelling

---

libs/sdk-ui-dashboard/src/_staging/metadata/objRefMap.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts

- add correct ObjRefMap type for dashboard dateFilters
- add events to non-serializable event list
JIRA: RAIL-3707
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my- …

RAIL-3707 ObjRefMap type for date dataset fix

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useExportHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts

The types were mismatched which hid the error.
JIRA: RAIL-3714
---
--- …

RELATED: RAIL-3714 Fix insight exports

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/filterContext.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commands/filters.ts
libs/sdk-ui-dashboard/src/model/state/filterContext/filterContextReducers.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/layout/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/types.ts
libs/sdk-ui-dashboard/src/types.ts

Makes sure that filters added since the alert was created are reset to All when the Apply alert filters to Dashboard button is clicked.
JIRA: RAIL-3713
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs …

RELATED: RAIL-3713 Fix Apply alert filters to Dashboard

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/handler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/removeAttributeFiltersHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/addAttributeFilterHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/changeAttributeFilterSelectionHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/moveAttributeFilterHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/removeAttributeFilterHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/addAttributeFilterHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/changeAttributeFilterSelectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/moveAttributeFilterHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/removeAttributeFilterHandler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/__snapshots__/changeDateFilterSelectionHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/tests/changeDateFilterSelectionHandler.test.ts
libs/sdk-ui-dashboard/src/model/state/layout/layoutReducers.ts

Removing attribute filter needs to ensure that the removed filter is no longer used on the ignore lists.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reque …

RELATED: RAIL-3492 - Remove attribute filter must cleanup ignore lists

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFiltersQuery.ts

We only need to override the filters for insights, not for KPIs.
JIRA: RAIL-3731
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-c …

RELATED: RAIL-3731 Fix ignored filters resolution for KPIs

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/mergeElementQueryResults.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/tests/mergeElementQueryResults.test.ts

Fix cases where we need to splice in a huge array which caused
a call stack size breach. More details are in a comment in the relevant
part of the code.
JIRA: RAIL-3728
---
--- …

RELATED: RAIL-3728 fix mergeElementQueryResults for large arrays

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/types.ts
libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts
libs/sdk-ui-dashboard/src/model/state/dashboardStore.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts

- The user can thus reach the latest state of the selectors
---
--- …

Dashboard component - expose onStateChange callback

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/PluggableAreaChart.test.tsx

Limit number of attributes to 1 when there are multiple measures in the
original reference point.
JIRA: TNT-169
---
--- …

RELATED: TNT-169 Fix switching to area chart

---

examples/sdk-examples/src/examples/attributeFilter/AttributeFilterButtonExample.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdownList.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- Keep attribute elements selection
- Do not show elements as selected when searching
JIRA: RAIL-3739, RAIL-3740, RAIL-3741, RAIL-3743,
---
--- …

AttributeFilter components fix

---

libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/index.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/utils.test.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts

New function to remove insight to report translations

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx

- Consider enableKDWidgetCustomHeight feature flag to get CSS position attribute correctly for small screen widths
JIRA: RAIL-3659
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how- …

RAIL-3659 Consider enableKDWidgetCustomHeight feature flag to get position

---

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiContent/KpiValue.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

- Show loading indicator inside the KPI widget instead of show loading indicator only
JIRA: RAIL-3651
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request- …

RAIL-3651 Adjust KPI loading to align with KD

---

libs/api-client-bear/src/xhr.ts

Fix validElements polling in api-bear-client

---

libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/fromModel/ldm/measure.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

Pass object id so we can use it to link to the metric in metric editor.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner …

NAS-313 Display attribute/ metric name instead of id in preview syntax

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- fix sync inconsistency between external props & internal state
JIRA: RAIL-3652
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-c …

AttributeFilterButton - fix sync issues

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeDropdownListItem.tsx

- Add s-classes to AttributeFilterButton items for graphene support
JIRA: RAIL-3792
---
--- …

RAIL-3792 CSS for attributeFilter items

---

libs/sdk-ui-dashboard/src/_staging/drills/drillingUtils.ts
libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

* RAIL-3657 - fix implicit drill down predicates - now use only localId matches (same as gdc-dashboards)
* RAIL-3693 - fix chart config selector (handle empty drillableItems, not only falsy)
---
--- …

RELATED: RAIL-3657, RAIL-3693 small drilling-related fixes

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/resolveDrillToCustomUrl.ts

- Add workspace_id placeholder resolution for drillToCustomUrl feature
JIRA: RAIL-3702
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval- …

RELATED: RAIL-3702 - Add workspace_id placeholder resolution

---

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/tests/modifyDrillsForInsightWidgetHandler.test.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/SimpleDashboard.fixtures.ts
libs/sdk-ui-tests-e2e/scripts/create_github_report.js
libs/sdk-ui-tests-e2e/scripts/run_isolated_compose.js

* prevent use of http third-party URLs in tests
* prevent free-hand command execution in e2e test scripts
---
--- …

RELATED: RAIL-3808 fix SonarQube warnings

---

libs/sdk-backend-bear/src/backend/workspace/settings/settings.ts
libs/sdk-backend-bear/src/backend/workspace/settings/tests/__snapshots__/settings.test.ts.snap
libs/sdk-backend-bear/src/backend/workspace/settings/tests/settings.test.ts

JIRA: TNT-330
For some features User level settings don't make sense and we want them to be configurable only on Project and above
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how- …

Omit settings ignored on User level

---

libs/sdk-ui-dashboard/src/plugins/customizationApis/insightCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/insightCustomizer.test.tsx
libs/sdk-ui-dashboard/src/plugins/customizer.ts

Also improve types of this-returning functions.
JIRA: RAIL-3804
---
--- …

RELATED: RAIL-3804 Handle withTag edge case and document it

---

libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/changeSharingHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/changeSharingHandler.test.ts
libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareButton/DefaultShareButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareButton/types.ts
libs/sdk-ui-dashboard/src/types.ts

JIRA: TNT-328
To share dashboard and also allow others to open it and see it isUnderStrictControl flag needs to be turned off too during process of making the dashboard public
---
--- …

Change isUnderStrictControl together with shareStatus

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
tools/dashboard-plugin-template/.env.template
tools/dashboard-plugin-template/.gitignore
tools/dashboard-plugin-template/configTemplates/ts/tsconfig.json
tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/webpack.config.js
tools/plugin-toolkit/scripts/build.sh
tools/plugin-toolkit/src/initCmd/actionConfig.ts
tools/plugin-toolkit/src/initCmd/index.ts

next round of improvements & fixes:
-  rename plugin* dirs so that they reflect plugin name
-  perform template replacements on files to fill in values passed on CLI
-  .env file now exists immediately after creation; .gitignore in place 
-  refactor/fix pluginIdentifier creation (needs snake case so that all works in webpack module federation)
-  added comments
---
--- …

RELATED: RAIL-3428 - Plugin Dev Toolkit part 4

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectListItem.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

* RAIL-3811 - We have to identify the opened/highlighted alerts by widget, not alert to handle cases when a widget has no alert yet.
* RAIL-3815 - Prevent trailing spaces in drill dialog
---
--- …

RELATED: RAIL-3811, RAIL-3815 Fix KPI alerts and drill dialog

---

common/config/rush/pnpm-lock.yaml
tools/plugin-toolkit/package.json
tools/plugin-toolkit/src/_base/cli/loggers.ts
tools/plugin-toolkit/src/_base/cli/prompts.ts
tools/plugin-toolkit/src/_base/cli/validators.ts
tools/plugin-toolkit/src/_base/types.ts
tools/plugin-toolkit/src/dashboard-plugin-template.ts
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/initCmd/actionConfig.ts
tools/plugin-toolkit/src/initCmd/index.ts

-  added workspace & dashboard parameters & prompts
-  added logic to auto-install package dependencies (or skip the install)
-  tweaked logging/messaging to use just unicode characters for info/warn/error instead of the long texts
-  added extra info messages so that ppl are not scared of some things
-  renamed 'flavor' (as used in boilerplate) to 'language' as that seems more 'standard' to me.. flavor is for icecream
---
---
-   [ ] commit …

RELATED: RAIL-3428 - Finish init plugin command

---

libs/sdk-backend-bear/src/convertors/fromBackend/VisualizationConverter.ts

Since the filters saved by Analytical designer are URI based,
we must assume that empty filters should also be treated as URI filters.
JIRA: RAIL-3805
---
--- …

RELATED: RAIL-3805 Default to URI filters on bear

---

libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-base/src/dummyBackend/tests/index.test.ts

Implementation of dummy backend for simple usage in metric editor unit tests
JIRA: NAS-2414
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-appr …

RELATED: NAS-2414 - Implement measures service on dummy backend

---

tools/plugin-toolkit/package.json
tools/plugin-toolkit/src/initCmd/actionConfig.ts

-  Archives with template were not in package json => not in published package
-  Tool asks for plugin name at the end; that looks a bit awkward
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contri …

RELATED: RAIL-3428 - Init dashboard fixes

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/widgetDrills/widgetDrillSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx

- omit drill to deleted insights
- omit drill to deleted dashboards
- omit drill to deleted attributes
JIRA: RAIL-3768
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if …

Dashboard - omit invalid drills

---

libs/sdk-backend-bear/src/convertors/fromBackend/CatalogConverter.ts
libs/sdk-backend-bear/tests/integrated/__snapshots__/catalog.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/utils/attributeResolver.ts

- Allow set filter context by the different attribute display form than the stored one in the filter context
JIRA: RAIL-3673
---
--- …

Dashboard - allow set filter context by non-default display form

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Form/focus.ts
libs/sdk-ui-kit/src/Form/tests/Input.test.tsx
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/typings/domNative.ts

Implementation of native methods from interface IDomNative on PureInput
Added IDomNativeProps to extends props on PureInput
This can be used in another native like elements
New property "nativeLikeAutofocus" that try to focus element after is visible on page (is not hidden and has some size). This optional must be enabled to start behave this new way.
Also, component PureInput clean timers and intervals to if is destroyed.
JIRA: NAS-2440
---
---
- …

RELATED: NAS-2440 - Implement native dom api functions on pure input

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/gd-tiger-model/AnalyticalDashboardModelV2.ts
libs/api-client-tiger/src/gd-tiger-model/typeGuards.ts
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AnalyticalDashboardConverter.ts
libs/sdk-backend-tiger/src/types/index.ts
libs/sdk-backend-tiger/src/types/refTypeMapping.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/objRef/index.ts

* Implement CRUD on dashboardPlugin objects
* Add support for sideloading them for dashboards
* Add support for linking them to dashboards
* Do not fail on `loadUserData` for dashboards anymore, just warn and ignore the option
---
--- …

RELATED: RAIL-3473 add support for dashboard plugins to tiger

---

libs/sdk-backend-bear/src/backend/workspace/dashboards/index.ts

Now the backend bug is fixed, we can remove the workaround
and make the network communication more effective again.
For orignial context, see #1844
JIRA: RAIL-3473
---
--- …

RELATED: RAIL-3473 Remove workaround for bear backend bug

---

libs/sdk-ui-kit/src/Bubble/BubbleTrigger.tsx
libs/sdk-ui-kit/src/Bubble/tests/BubbleTrigger.test.tsx

propagate others props to main html element
JIRA: NAS-469
---
--- …

Fix propagation of data-attributes in Bubble components

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/getTitleWithBreadcrumbs.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/test/getTitleWithBreadcrumbs.test.ts

The name of the exported file must contain the breadcrumbs as well.
As part of this the logic was extracted, simplified and tested.
JIRA: RAIL-3822
---
--- …

RELATED: RAIL-3822 Use proper title for drill exports

---

tools/plugin-toolkit/src/_base/inputHandling/validators.ts
tools/plugin-toolkit/src/_base/terminal/prompts.ts
tools/plugin-toolkit/src/_base/utils.ts
tools/plugin-toolkit/src/addPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/linkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/linkPluginCmd/index.ts
tools/plugin-toolkit/src/unlinkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/unlinkPluginCmd/index.ts
tools/plugin-toolkit/src/usePluginCmd/actionConfig.ts
tools/plugin-toolkit/src/usePluginCmd/index.ts

- The 'use' command renamed to 'link'. 
- Added 'unlink' command to reverse the operation.
- Expanded the validations done on the dashboard and dashboard plugin during link
---
--- …

RELATED: RAIL-3428 - Link and unlink dashboard plugin commands

---

tools/plugin-toolkit/package.json
tools/plugin-toolkit/src/_base/utils.ts
tools/plugin-toolkit/src/addPluginCmd/index.ts
tools/plugin-toolkit/src/initCmd/index.ts
tools/plugin-toolkit/src/linkPluginCmd/index.ts
tools/plugin-toolkit/src/unlinkPluginCmd/index.ts

-  created genericErrorReporter
-  improved the categorization
-  ported code from catalog-export that identifies that host uses self-signed certs; getting nicer error message now
---
--- …

RELATED: RAIL-3428 - Unify error reporting for commands

---

tools/dashboard-plugin-template/.env.secrets.template
tools/dashboard-plugin-template/src/harness/PluginLoader.tsx

-  MAPBOX_TOKEN is a new env variable that can be specified in .env.secrets or as session env variable
-  it will be propagated over to dashboard component with config
---
--- …

RELATED: RAIL-3428 - Add config for mapbox token to use during plugin development

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/exportDashboardToPdfHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/saveAsDashboardHandler.ts
libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts

* RAIL-3828 - Fix export to PDF: Properly override saved filter for the export if currently using All time filter. This is what gdc-dashboards do.
* RAIL-3830 - Properly clone filter contexts in saveAsCopy. Previously, when useOriginalFilterContext was set, the copied dashboard would use the same filterContext object. That is incorrect, we want to create a new object, just with the same filters as the persisted one.
---
--- …

RELATED: RAIL-3828, RAIL-3830 dashboard fixes

---

tools/plugin-toolkit/scripts/preparePackageJson.ts
tools/plugin-toolkit/src/_base/inputHandling/validators.ts
tools/plugin-toolkit/src/_base/utils.ts
tools/plugin-toolkit/src/addPluginCmd/index.ts
tools/plugin-toolkit/src/initCmd/index.ts

Proper plugin name validation; plugin name == package.json name
Ensure prompting does not accept empty plugin name
Improve naming of plugin directory (use name as is, strip org if needed)
Remove <plugin-description> and <plugin-author> from package.json; keep empty instead; encourage plugin creator to add author and description
Show plugin description before adding.
---
--- …

RELATED: RAIL-3824 - Fixes for plugin naming & validation

---

tools/plugin-toolkit/src/linkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/linkPluginCmd/index.ts

-  the idRef for link did not include 'dashboardPlugin'
-  conversion before sending data to backend failed
---
--- …

RELATED: RAIL-3428 - Fix link command when backend is tiger

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts
libs/sdk-ui-dashboard/src/plugins/customizer.ts
libs/sdk-ui-dashboard/src/plugins/exampleDashboardPlugin.tsx

-  insightRendering -> insightWidgets()
-  kpiRendering -> kpiWidgets()
-  widgets -> customWidgets()
This will grow better into the future where we may want to add additional customizations on how the insight or KPI widgets & their different sub-components get rendered (e.g. we may want to enhance insightWidgets() with funs to add custom content into button bar, customize how title is rendered. customize before/after/left/right components)
---
| `extended check cypress` | Cypress …

RELATED: RAIL-3428 - Rename refactor in plugin SPI

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/converters/filterConverters.ts
libs/sdk-ui-dashboard/src/converters/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts

Adapt the logic from gdc-dashboards, mainly the date filter disabled
logic that should prevent the date filter from being used in certain
cases. Also added some comments to clarify the code.
Partially reverts c8ee469db8b118e305b654a24e00f9346e5fdf23
JIRA: RAIL-3636, RAIL-3826, RAIL-3834
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-th …

RELATED: RAIL-3636, RAIL-3826, RAIL-3834 Fix drillToDashboardHandler

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/plugins/customizationApis/insightCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/kpiCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/insightCustomizer.test.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/kpiCustomizer.test.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/widgetCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizer.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
tools/dashboard-plugin-template/tsconfig.json

* RAIL-3428 - Target ES2017 in dashboard plugins. This is more forward compatible with gdc-dashboards dropping IE support: the current gdc-dashboards can run ES2017 plugins and gdc-dashboards without IE support can run them too. They can't run ES5 plugins, though.
* RAIL-3840 -  improve decorator typings to prevent undefined results of the providerFactory.
---
--- …

RELATED: RAIL-3428, RAIL-3840 plugin-related improvements

---

libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiRenderer.tsx

- to align with KD, where even invalid Kpis can be drillable
JIRA: RAIL-3647
---
--- …

Enable configured drills even for invalid Kpi

---

libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
tools/dashboard-plugin-template/.env.template
tools/dashboard-plugin-template/README.template.md
tools/dashboard-plugin-template/src/harness/Root.tsx
tools/dashboard-plugin-template/src/harness/backend--tiger.ts
tools/dashboard-plugin-template/src/harness/backend.ts
tools/plugin-toolkit/src/index.ts
tools/plugin-toolkit/src/inspectCmds/actionConfig.ts
tools/plugin-toolkit/src/inspectCmds/inspectCmdAction.ts
tools/plugin-toolkit/src/inspectCmds/inspectDashboard.ts
tools/plugin-toolkit/src/inspectCmds/output.ts
tools/plugin-toolkit/src/inspectCmds/types.ts

-  Fixed dashboard converter in bear to ensure that dashboard has no `plugins` instead of empty `plugins`
-  Added basic inspect dashboard command; shows info about the dashboard & the plugins used on the dashboard
---
--- …

RELATED: RAIL-3837, RAIL-3428 - Fixes & addition of inspect dashboard

---

libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/adaptiveComponentLoaders.ts
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/staticComponentLoaders.ts
libs/sdk-ui-loaders/src/dashboard/types.ts

If the onPluginLoaded call fails, the plugin is ignored.
JIRA: RAIL-3841
---
--- …

RELATED: RAIL-3841 Call onPluginLoaded on external plugins

---

libs/sdk-ui-charts/src/highcharts/chartTypes/lineChart/lineConfiguration.ts
libs/sdk-ui-ext/src/internal/components/configurationPanels/BaseChartConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/ConfigurationPanelContent.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/LineChartBasedConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/constants/axis.ts

BUGFIX: TNT-325 Combo chart display proper label properties in configuration

---

tools/plugin-toolkit/src/initCmd/index.ts

-  Dir was not shown
-  Should log as success
RELATED: RAIL-3853
---
--- …

RELATED: RAIL-3853 - Fix messaging when new plugin successfully created

---

tools/dashboard-plugin-template/webpack.config.js

-  Bad stubs for lru cache caused this
RELATED: RAIL-3854
---
--- …

RELATED: RAIL-3854 - Fix plugin template webpack config

---

libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts

- ignore attribute filters for the date filter check
JIRA: RAIL-3848
---
--- …

Fix query widget filters for dashboard with all time filter

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/types/layoutTypes.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/fluidLayoutCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/layoutCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/fluidLayoutCustomizer.test.ts
libs/sdk-ui-dashboard/src/plugins/customizer.ts
tools/dashboard-plugin-template/src/plugin/Plugin.tsx
tools/dashboard-plugin-template/webpack.config.js

-  Add section & item factories 
-  Prohibit empty sections/items during customization; 
-  Update template to contain a better example for custom widget & its placement
---
--- …

RELATED: RAIL-3847 - customizer API tweaks & template enhancement

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts

This is useful in apps that already load the Theme themselves. Also properly pass backend/workspace props to the ThemeProvider.
JIRA: RAIL-3867
---
--- …

RELATED: RAIL-3867 Add option to disable theme loading

---

libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts

-  Surgical change in selectBasicLayout - this selector is used internally now, only during save
-  The selector already removed all custom widgets (because not all backends know how to persist them)
-  It did not, however remove empty sections in case such sections were created purely out of custom widgets
-  Saving dashboard with empty sections leads to problems / unhandled corner cases
RELATED: RAIL-3865
---
---
-   [ ] commit messages adhere to …

RELATED: RAIL-3865 - Remove empty sections from layout before saving

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/types/layoutTypes.ts
libs/sdk-ui-dashboard/src/plugins/customizer.ts

* RAIL-3864 - allow OptionalProviders in withCustomProvider, remove non-sensical comment: it only makes sense for insights, not KPIs
* RAIL-3869 - allow heterogeneous items in newDashboardSection
---
--- …

RELATED: RAIL-3864, RAIL-3689 typings improvements

---

libs/sdk-ui-ext/src/insightView/InsightView.tsx

Make sure the errors going to the InsightError component
are of the correct type so that it properly maps the Unexpected error
to the Not found message.
JIRA: RAIL-3871
---
--- …

RELATED: RAIL-3871 Fix InsightView when insight not found

---

libs/sdk-ui-kit/styles/scss/loadingDots.scss

- ensure that they are rendered horizontally (for parent element with zero width, they are rendered vertically)
JIRA: RAIL-3862
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do- …

Fix appearance of the kpi loading dots

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts

Currently, these visualizations should not be available for individual
exports – this is how gdc-dashboards behave.
JIRA: RAIL-3874
---
--- …

RELATED: RAIL-3874 Prevent exporting of Headline and XIRR

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- Improve state handling to stabilize component behaviour
- Invalid attribute filter elements handling
- Improve AttributeFilterButton subtitle behaviour
- Fix selection equality check
JIRA: RAIL-3850, RAIL-3856
---
--- …

RAIL-3850 AttributeFilterButton subtitle issues fixes

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- Modify subtitle generating function to resolve negative attribute filter properly
JIRA: RAIL-3850
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-ne …

RELATED: RAIL-3850 negative attribute filter subtitle

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/insights/insightsSelectors.ts
tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/src/plugin/utils/useInsightWidgetDataView.ts

- add example hook to the plugin template, so users can see how to get data view for particular insight widget
JIRA: RAIL-3872
---
--- …

Add example hook to get data for particular insight widget

---

tools/dashboard-plugin-template/README.template.md
tools/plugin-toolkit/src/initCmd/index.ts

* add missing `run` in one of the commands
* use the same protocol as the backend for the app
JIRA: RAIL-3428
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull- …

RELATED: RAIL-3428 Small plugin toolkit tweaks

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx

Rework the Headline-export banning logic, remove obsolete selector.
JIRA: RAIL-3881
---
--- …

RELATED: RAIL-3881 Fix insight exports in drill dialog

---

common/scripts/ci/docker_rush.sh
common/scripts/ci/docker_rushx.sh

These warnings could bomb the whole build because rush treats
warnings as errors on CI.
As these warnings are not as important, it is safe to ignore them
in CI context in favor of stable, deterministic builds.
JIRA: FET-914
Tested in #1976 against release branch that had this issue.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-co …

RELATED: FET-914 Prevent caniuse-lite warnings on CI

---

libs/api-client-bear/src/project.ts
libs/sdk-backend-bear/src/backend/workspace/index.ts
libs/sdk-backend-spi/src/workspace/index.ts

- Do not fetch all workspaces if the descriptor is missing. Fetch the necessary workspace only.
JIRA: FET-902
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull- …

Improve workspace.getDescriptor() performance

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts
libs/sdk-ui-filters/styles/scss/attributeFilter.scss

- Add support to remove selection for all descending attribute filters of the changed parent
---
--- …

RELATED: RAIL-3849 Parent-child filtering for all descendants

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/accessControl/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/types.ts
libs/sdk-ui-kit/src/Dialog/ShareDialog/shareDialogMappers.ts
libs/sdk-ui-kit/src/Dialog/ShareDialog/test/ShareDialog.test.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/test/shareDialogMappers.test.ts
libs/sdk-ui-kit/src/Dialog/ShareDialog/types.ts

JIRA: TNT-268
Extend grantees by the type (user, group)
Add added/removed grantees to the event payload
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reques …

Support for sharing telemetry

---

libs/sdk-ui-dashboard/package.json

Build sdk-ui-dashboard in prepublishOnly to make sure the new package
version is used in the released package. We need to do this in this step
because it is the only time the new version is known.
JIRA: RAIL-3808
---
--- …

RELATED: RAIL-3808 Fix engine version in sdk-ui-dashboard

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DefaultDashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/DefaultDashboardKpi.tsx

-  This was a miss during the round of publication
-  Their props are public already
JIRA: RAIL-3808
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-n …

RELATED: RAIL-3808 - Mark default insight and KPI components as public

---

common/scripts/build-docs.js

* use the rm function instead of deprecated rmdir
* add the force parameter to not fail when the directory does not exist
* use native promise versions of the fs functions
JIRA: RAIL-3808
---
--- …

RELATED: RAIL-3808 Fix apidocs build on Node 16

---

libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/DefaultLockedStatus.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/DefaultShareStatus.tsx

JIRA: TNT-374
Share status indicator visible only when backend supports access management
Lock status only when new navigation is enabled
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …

Change indicators visibility logic

---

libs/sdk-backend-base/src/toolkit/paging.ts
libs/sdk-backend-bear/tests/integrated/__snapshots__/dateFilterConfigs.test.ts.snap
libs/sdk-backend-bear/tests/integrated/__snapshots__/elements.test.ts.snap
libs/sdk-backend-bear/tests/integrated/__snapshots__/insights.test.ts.snap

- Do not fire unnecessary request on .next() call, return empty result immediately if we know that it will be empty
- Do not limit offset
- This is also fix for Cypress tests in KD
JIRA: FET-847
---
--- …

Fix / optimize ServerPaging

---

common/changes/@gooddata/sdk-ui-all/list_2021-12-06-11-43.json
libs/sdk-backend-bear/src/backend/organization/securitySettings.ts
libs/sdk-backend-bear/src/backend/organization/tests/securitySettings.test.ts

RELATED: RAIL-3896 - Fix checking against plugin hosts

---

libs/sdk-ui-dashboard/src/presentation/topBar/shareButton/DefaultShareButton.tsx

JIRA: TNT-320
If user can access dashboard only via link, but cant see it in the dashboards navigation than he cant change the sharing
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …

Hides Share button for users without full access

---

common/scripts/ci/init_hotfix_branch.sh

The case when the existing branch ends with just -fix (not -fix-3)
was not properly handled.
JIRA: RAIL-3900
---
--- …

RELATED: RAIL-3900 Fix init_hotfix_branch script

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardComponentsContext.tsx
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/index.ts
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/types.ts
libs/sdk-ui-dashboard/src/presentation/index.ts
libs/sdk-ui-dashboard/src/presentation/types.ts

* Use the same pairing Provider – OptionalProvider everywhere
* Use the Provider types in the DashboardComponentsContext
* Move the types around to prevent cyclic dependencies
JIRA: RAIL-3905
---
--- …

RELATED: RAIL-3905 Unify the types related to component providers

---

libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts
libs/sdk-ui/src/base/index.tsx

- enable posibility to use generated catalog export file for drillableItems definitions through objRefMatch function. This removes the need to search for identifier in generated file or graypages.
JIRA: RAIL-3725
---
--- …

RELATED: RAIL-3728 Enable using MD for drill definitions

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

JIRA: SD-1921
Change suffix `renaming_measure` to `._measure` or `._measure` is controlled  by isRenamingMeasureToMetricEnabled FF.
---
--- …

Consistent naming for facts and metrics

---

libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts
libs/sdk-ui/src/base/index.tsx

RELATED: RAIL-3725 HeaderPredicates matching any object for attribute or measure

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/DataTooLargeError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/ExecuteProtectedError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/NoDataError.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/CustomError/OtherError.tsx
libs/sdk-ui-filters/src/RankingFilter/Preview.tsx

To make the Graphene tests upstream stable add back recently removed span elements in:
* Preview in RankingFilter
* Widget errors in Dashboard component
JIRA: RAIL-3914
---
--- …

RELATED: RAIL-3914 Add missing spans in certain localized parts

---

libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx

This is how gdc-dashboards behave, users without
the "canCreateAnalyticalDashboard" permission are not shown
the button at all.
JIRA: RAIL-3918
---
--- …

RELATED: RAIL-3918 Hide Save As button for users without permission

---

tools/dashboard-plugin-template/webpack.config.js

- avoid sharing react-intl with the dashboard plugin
- if the dashboard plugin is built with react-intl v3 and SDK contains react-intl v5, current setup can lead to runtime errors (eg FormattedHTMLMessage element does not exist in v5)
JIRA: RAIL-3915
---
---
-   [ ] review …

Do not share react-intl with the plugin

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/DisabledConfigurationParentItem.tsx

- FormattedHTMLMessage is no longer available in react-intl v5
JIRA: RAIL-3915
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-cod …

Migrate DisabledConfigurationParentItem to react-intl v5

---

common/changes/@gooddata/sdk-ui-all/mkn-rail-3910-validation_2021-12-20-13-57.json
common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/plugins/plugin.ts
libs/sdk-ui-geo/README.md
libs/sdk-ui-loaders/package.json
libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/determineDashboardEngine.ts
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts
tools/dashboard-plugin-template/src/plugin/Plugin.tsx
tools/plugin-toolkit/src/initCmd/index.ts

Handle different versions of the dashboard plugins
When the dashboard is linked with multiple plugins:
- Load the engine with the greatest version
- If some of the plugins do not match the engine version, do not initialize any at all
JIRA: RAIL-3910
---
---
-   [ ] review …

Handle different versions of the dashboard plugins

---

libs/sdk-ui-pivot/src/impl/base/agApiWrapper.ts
libs/sdk-ui-tests/stories/visual-regression/visualizations/insightStories.tsx

Since we do not have typings for the internals, assume anything
along the "happy path" can be nullish just to be safe.
JIRA: RAIL-3929
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …

RELATED: RAIL-3929 Make the ag-grid internals access robust

---

libs/sdk-ui-filters/package.json

This is the first React-17-compatible version.
The pnpm.lock was already using the new version, that is why there are no updates in it.
JIRA: FET-529
---
--- …

RELATED: FET-529 Upgrade react-window 1.8.5 -> 1.8.6

---

libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts

- objRefMatch fallback if measure has no localIdentifier 
JIRA: RAIL-3725
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-own …

RELATED: RAIL-3725 objRefMatch fallback if measure has no localId

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx

Similar to #2041 there are hard-to-reproduce situations when a code
assumes the insights are loaded even thoug for some reason they are
in fact not ready. This results in hard to reproduce issues.
As a fix, we prevent these invariants from happening and log
the occurences. This also avoids explicit not-null assertion.
Also fix two Sonar-reported code smells in the file.
JIRA: RAIL-3925
---
--- …

RELATED: RAIL-3925 Make DefaultDashboardInsightWidget more robust

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

For some reason with ag-grid 25, the current autosizing logic broke
when there were vertical scrollbars present. As a fix, we take
the clientWidth of the element that now has the scrollbars if they are
needed for a given situation (not the whole table container).
JIRA: RAIL-3940
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commit …

RELATED: RAIL-3940 Fix pivot table auto sizing

---

libs/sdk-ui-dashboard/src/model/store/_infra/queryService.ts

Turns out importing directly from src in redux toolkit breaks
create-react-app because it includes the whole package into
TypeScript compilation which then fails (redux toolkit has some
unused variables internally).
This avoids the problem and should make the build marginally faster.
JIRA: RAIL-3942
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#w …

RELATED: RAIL-3942 Fix redux/toolkit import

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/_infra/queryService.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardCustomizationsContext.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/DefaultTitle.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/EditableTitle.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/TitleWrapper.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/index.tsx

* make the default title not editable
* make the Save as new button opt-in
Currently we ignore the enableSaveAsNewButton value in order to first make gdc-dashboards aware of the new prop and then we will actually use the prop in a follow up PR.
JIRA: RAIL-3945
---
---
-   [ …

RELATED: RAIL-3945 improve default embedding experience

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/types.ts
libs/sdk-ui-dashboard/src/types.ts

This allows the same level of control for all the default items
in the menu button menu (not just save as new).
JIRA: RAIL-3945
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do- …

RELATED:  RAIL-3945 Generalize the menu button item visibility setting

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Disable feature "enableAlternativeDisplayFormSelection" fr tiger due to problems with current abstraction on client.
**Filtering on tiger needs to be done by only primaryLabels** - now in SDK is not true
**In execution filter is defined by used label (and values of that label) not by primary, same in filter context** - this is wrong and its conflict with previous statement
**Problems:**
- Abstraction for execution on SPI level allows to specified filter using non primary labels and its working
- Filter context has same behaviour
JIRA: NAS-2719
---
| …

NAS-2719 - Disable feature "enableAlternativeDisplayFormSelection"

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextState.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts

- When filters on the dashboard are not changed, do not store them in the scheduled e-mail filter context
- With this change, future filter changes stored in the original dashboard filter context are correctly propagated to these scheduled emails
JIRA: RAIL-3944
---
---
- …

Omit filter context in scheduled e-mail if it's not changed

---

examples/sdk-examples/src/examples/measureValueFilter/measureValueFilterByValue/MeasureValueFilterShownInPercentageExample.tsx
examples/sdk-examples/src/examples/measureValueFilter/measureValueFilterComponent/MeasureValueFilterComponentRatioExample.tsx

We need to add explicit defaultLocalId when modifying measures.
JIRA: RAIL-3967
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-co …

RELATED: RAIL-3967 Fix MVF examples

---

tools/applink/src/devConsole/pipeline/publisher.ts

The NOTICE is the only thing in "files" that is not a directory. We need to
exclude it from the sync because it breaks the sync and is useless
in the applink context anyway.
JIRA: RAIL-3969
---
--- …

RELATED: RAIL-3969 Fix applink for packages with NOTICE

---

examples/sdk-examples/src/examples/export/PivotTableExportExample.tsx

Pass attribute to the sort factory directly, avoiding magic constant.
JIRA: RAIL-3968
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-b …

RELATED: RAIL-3968 Fix PivotTableExportExample

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-base/package.json
libs/sdk-backend-bear/package.json
libs/sdk-backend-mockingbird/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeDropdownListItem.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeFilterBody.tsx
libs/sdk-ui-ext/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Bubble/BubbleTrigger.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx
libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/HeaderDataMenu.tsx
libs/sdk-ui-kit/src/Header/HeaderMenu.tsx
libs/sdk-ui-pivot/package.json
libs/sdk-ui-tests/package.json
libs/sdk-ui-tests/stories/visual-regression/kit/Button/Button.tsx
libs/sdk-ui-tests/stories/visual-regression/kit/Messages/Messages.tsx
libs/sdk-ui/package.json

- Replace uniqueId by lodash with uuid
- update @types/uuid version 8.3.0 -> 8.3.4
Using uniqueId by lodash is causing issues with duplicate IDs while using SDK Dashboard component with the plugins as Dashboard Plugins introduce second instance of lodash, it can cause some major issue. 
As a solution/follow-up uniqueId by lodash is replaced with uuid through out the whole SDK codebase.
JIRA: RAIL-3936
---
--- …

RELATED: RAIL-3936 Replace uniqueId by lodash with uuid

---

examples/sdk-examples/src/examples/attributeFilter/AttributeFilterButtonExample.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonExample.tsx
examples/sdk-examples/src/examples/attributeFilter/AttributeParentChildFilterButtonWithPlaceholderExample.tsx
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- compare previous and actual parent filters after placeholder resolution
- handling components depending on child filter in the parent component
- attributeFilterButton always defined by refs in examples
- conidering title prop in AttributeFilterButton subtitle resolution
There is a need to handle child-filter-dependent components in all AttributeFilterButton parent-child examples, hence the effects reflecting the parent-filter changes.
In `getItemsTitles` function in `AttributeFilterUtils` the support for using attribute element title property if the filter is defined by values instead of refs. In the same function, we accept the possibility that the element's title will be resolved as undefined, that's why resolved titles are in addition filtered to remove falsy values.
JIRA: …

RELATED: RAIL-3966 - AttributeFilterButton examples fixes

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/index.tsx

- Show toast message if saving of the scheduled email fails
JIRA: RAIL-3958
---
--- …

Fix error propagation in scheduled email dialog

---

libs/sdk-ui-dashboard/src/_staging/testUtils/getTestClassname.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectListBody.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/ConfigurationParentItem.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/EmptyDashboardError.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/DefaultTitle.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/EditableTitle.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx

- This fixes for most of the failing cypress tests in KD after enabling dashboardComponentDevRollout FF
JIRA: RAIL-3958
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-i …

Fix css selectors and bugs for KD cypress tests

---

tools/dashboard-plugin-template/webpack.config.js

Previously, each plugin used their own instance of sdk-ui-dashboard,
which caused react-redux provider contexts to fail.
Instead, we want them to share the package. This should be safe, since
we explicitly validate they are compatible with each other.
JIRA: RAIL-3951
---
--- …

RELATED: RAIL-3951 Fix issue with multiple plugins

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeDropdown/AttributeDropdown.tsx

- new property of enableEventPropagation was introduced in the Dropdown component to adjust the onMouseUp event and made it undefined. This caused in AttributeFilter that after releasing the mouse nothing happened and the scroll bar remained active.
JIRA: RAIL-3960
---
--- …

RELATED: RAIL-3960 attribute filter scrolling fix

---

tools/dashboard-plugin-template/README.template.md

- dp_ prefix is doubled in the plugin readme
TRIVIAL
---
--- …

Fix dashboard plugin readme

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

- Add support for filter with elements defined by value in AttributeFilterButton component
JIRA: RAIL-3970
---
--- …

RELATED: RAIL-3970 Filters with elements defined by value support

---

common/scripts/ci/run_unit_tests.sh

For now we will just print the optimizations we would like to run
if this was enabled to observe if the detection works well before
we actually enable the optimizations for real.
JIRA: FET-955
---
--- …

RELATED: FET-955 Add mechanisms for incremental testing

---

common/scripts/ci/run_unit_tests.sh

Handle cases when grep did not find any matches.
JIRA: FET-955
---
--- …

RELATED: FET-955 Fix the run_unit_tests script

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

Add required AttributeFilterButton css selectors for KD cypress tests

---

libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/test/measureExpressionTokens.test.ts

Comments in tooltip are incorrectly displayed as standard MAQL expression
JIRA: NAS-2875
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approva …

NAS-2875 -

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- modify prepareElementsTitleQuery to prevent unexpected state changes
JIRA: RAIL-3977
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval- …

RELATED: RAIL-3977 Post message setFilterContext fix

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton.tsx

- elements change from parent handling
- search optimization to prevent race conditions
- refactored functions dependent on state values
JIRA: RAIL-3977, RAIL-3980
---
--- …

RELATED: RAIL-3980 attribute filter button fixes

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

The useDashboardEventDispatch was not used anywhere anymore.
Also remove code smell in the file.
JIRA: RAIL-3908
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pu …

RELATED: RAIL-3908 Simplify DashboardInsight

---

common/changes/@gooddata/sdk-ui-all/master_2022-01-18-13-03.json
libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-bear/src/backend/workspace/measures/measureExpressionTokens.ts
libs/sdk-backend-bear/src/backend/workspace/measures/test/measureExpressionTokens.test.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/fromModel/ldm/measure.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/test/measureExpressionTokens.test.ts

Comments in tooltip are incorrectly displayed as standard MAQL expression
JIRA: NAS-2875
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approva …

NAS-2875 - Comments in tooltip are incorrectly displayed as standard MAQL expression

---

libs/sdk-backend-tiger/src/convertors/fromBackend/fixLegacyElementUris.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/__snapshots__/fixLegacyElementUris.test.ts.snap
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/fixLegacyElementUris.fixtures.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/fixLegacyElementUris.test.ts

The id can be null meaning (empty value) so we must be prepared for it.
JIRA: RAIL-3983
---
--- …

RELATED: RAIL-3983 Handle colorMapping items with null id on tiger

---

common/changes/@gooddata/sdk-ui-all/mkn-rail-3935-readme_2022-01-19-08-36.json
tools/dashboard-plugin-template/README.template.md

- Add note that combining multiple plugins before 8.8.0 may not work
- Also add missing changelog about minEngineVersion and maxEngineVersion properties
JIRA: RAIL-3935, RAIL-3910
---
--- …

Add note about multiple plugins before 8.8.0

---

common/scripts/ci/init_hotfix_branch.sh

* use the appropriate arithemtic for new_fix_number
* fix issues reported by shellcheck
* deduplicate the Slack integration
JIRA: FET-960
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …

RELATED: FET-960 Fix the init_hotfix_branch script

---

libs/sdk-backend-tiger/src/convertors/fromBackend/fixLegacyElementUris.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/__snapshots__/fixLegacyElementUris.test.ts.snap
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/fixLegacyElementUris.fixtures.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/visualizationObjects/tests/fixLegacyElementUris.test.ts

This reverts commit 1bae94ef8204c669e21fa2d0301ee7e7ed143c37.
JIRA: RAIL-3983
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code …

Revert "Handle colorMapping items with null id on tiger"

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/tests/AbstractPluggableVisualization.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx
libs/sdk-ui-ext/src/internal/components/tests/BaseVisualization.test.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts

In order to be able to get execution from visualizations, we need to extend all pluggable visualization with public getExecution method.
JIRA: TNT-418
---
--- …

Get execution from pluggable visualizations

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/headlessDashboard/HeadlessDashboard.ts
libs/sdk-ui-dashboard/src/model/headlessDashboard/index.ts
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/store/_infra/queryService.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/tests/DashboardTester.ts

Jira: TNT-418
The only new code in  HeadlessDashboard is the `select` function. The rest was moved there from DashboardTester which now inherits from HeadlessDasboard.
It was also necessary to export `IDashboardQueryService`
---
--- …

Add HeadlessDashboard utility class

---

libs/api-client-bear/src/tests/xhr.test.ts
libs/api-client-bear/src/xhr.ts

All ajax requests except token request call beforeSend just before firing. In order to be able to inject custom headers to the token request itself, we need to simulate beforeSend also when handling unauthorized.
JIRA: TNT-418
---
--- …

Call beforeSend in token request

---

libs/api-client-bear/src/gooddata-browser.ts
libs/api-client-bear/src/gooddata-node.ts
libs/sdk-backend-bear/src/backend/index.ts

AbstractFactory may be used in cases when fetch-cookie needs to be reinitialized while creating a new SDK instance.
JIRA: TNT-418
---
--- …

Introduce getFactory for Node.js

---

common/scripts/ci/run_unit_tests.sh

This reverts commit abef00883cd433bd1713a7769c1f94ef40e48b58.
Turns out there is a problem with the CI git version. Disabling for now.
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md# …

Revert "Enable incremental unit test optimization"

---

common/scripts/ci/docker_apidocs_build.sh
common/scripts/ci/docker_examples.sh
common/scripts/ci/docker_rush.sh
common/scripts/ci/docker_rushx.sh
common/scripts/ci/run_unit_tests.sh
libs/sdk-backend-tiger/.gitignore

Use the bullseye-based Node docker image for the Rush runs.
We need the newer Debian base to have recent-enough git needed
for the advanced Rush features (--impacted-by git:something paramter).
I stuck with Debian (not switching to Alpine for example), as the previously used image was also Debian so let's keep the changes minimal.
Also add  .wiremock_containerid to gitignore in tiger (it was already ignored in bear). 
---
---
-   [ ] commit …

RELATED: FET-955 fix and re-enable incremental tests

---

common/scripts/ci/run_unit_tests.sh

Now that the incremental tests are run for real, remove some obsolete
comments and echos.
JIRA: FET-955
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-reques …

RELATED: FET-955 Remove the testing logs in the unit tests script

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/accessControl/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/dashboard.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/changeSharingHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/tests/changeSharingHandler.test.ts
libs/sdk-ui-dashboard/src/model/commands/dashboard.ts
libs/sdk-ui-dashboard/src/model/events/base.ts
libs/sdk-ui-dashboard/src/model/events/dashboard.ts
libs/sdk-ui-dashboard/src/types.ts

* Mark all related types public as well
* Improve naming and documentation
There is a small breakage affecting gdc-dashboards, the PR there will be
created ASAP.
JIRA: RAIL-3953
---
--- …

RELATED: RAIL-3953 Mark GDC.DASH/EVT.SHARING.CHANGED public

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/general.ts
libs/sdk-ui-dashboard/src/model/headlessDashboard/HeadlessDashboard.ts
libs/sdk-ui-dashboard/src/model/queries/base.ts
libs/sdk-ui-dashboard/src/model/queries/index.ts
libs/sdk-ui-dashboard/src/model/queries/insights.ts
libs/sdk-ui-dashboard/src/model/queries/kpis.ts
libs/sdk-ui-dashboard/src/model/queries/widgets.ts
libs/sdk-ui-dashboard/src/model/react/index.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardQueryProcessing.ts
libs/sdk-ui-dashboard/src/model/store/_infra/queryAndWaitFor.ts
libs/sdk-ui-dashboard/src/model/store/_infra/queryCall.ts
libs/sdk-ui-dashboard/src/model/store/_infra/queryProcessing.ts
libs/sdk-ui-dashboard/src/model/store/_infra/queryService.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetFilters.ts

* fully type its results with discriminated unions
* remove IDashboardQueryResult: It never worked properly and always returned unknown. There is no reasonable way of fixing it, so remove it to prevent confusion. Also remove the generic parameter of the IDashboardQuery as it is unusable anyway (for the same reasons).
* avoid the need of some ! assertions by handling the types better:
destructuring apparently breaks the type narrowing, so avoid it
JIRA: RAIL-3987
---
| `extended check cypress` | …

RELATED: RAIL-3987 Improve typings around useDashboardQueryProcessing

---

tools/catalog-export/src/transform/tests/titles.test.ts
tools/catalog-export/src/transform/titles.ts

Use deburr from lodash to strip the diacritics for variable names in catalog-export

---

libs/sdk-ui-loaders/src/dashboard/loadingStrategies/dynamicComponentLoaders.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/errors/GoodDataSdkError.ts
libs/sdk-ui/src/base/index.tsx

- add DynamicScriptLoadSdkError
- define DynamicScriptLoadSdkError when script loading failed.
JIRA: RAIL-3938
---
--- …

Define SDK error for failing dynamic script load

---

libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts
libs/sdk-backend-tiger/src/backend/workspace/permissions/test/permissions.test.ts

Use call `api/entities/workspaces/${this.workspace}?metaInclude=permissions` to obtain permission for current workspace and use results to read workspace permissions
Map group permissions on current sdk spi permission structure.
> Note: From tiger backend there are permissions like MANAGE, ANALYZE, VIEW. Keep on mind that if user has MANAGE permissions, there will be also ANALYZE and VIEW in permissions array. 
JIRA: NAS-3005
---
---
-   [ ] commit …

NAS-3005 - Map Tiger Workspace Permissions to @gooddata/sdk-backend-spi

---

libs/sdk-backend-bear/src/utils/errorHandling.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/errors/index.ts
libs/sdk-backend-spi/src/index.ts

This is to allow clients to distinguish between more nuanced reasons:
* expired password
* plain wrong credentials
JIRA: RAIL-3991
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how- …

RELATED: RAIL-3991 Provide more details for NotAuthenticated

---

libs/sdk-ui-filters/styles/scss/attributeFilter.scss

- hide original attribute filter button on dropdown open
- add the button as a dropdown header
JIRA: RAIL-3990
---
--- …

RELATED: RAIL-3990 Modify attribute filter button header on mobile

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationLogging.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/filterBarCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/fluidLayoutCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/insightCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/kpiCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/layoutCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/filterBarCustomizer.test.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/fixtures/TestingDashboardCustomizationLogger.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/widgetCustomizer.tsx
libs/sdk-ui-dashboard/src/plugins/customizer.ts
libs/sdk-ui-dashboard/src/plugins/index.ts

* Add new customizer section for filterBar
* Add a function to set the rendering mode there
* Improve architecture slightly to allow easier testing of logging
---
--- …

RELATED: RAIL-3988 add option for plugins to hide the filter bar

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/convertors/toBackend/ObjRefConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/AfmFiltersConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/FilterConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/MeasureConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/AfmFilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/FilterConverter.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/afm/tests/__snapshots__/FilterConverter.test.ts.snap
libs/sdk-backend-tiger/src/convertors/toBackend/afm/toAfmResultSpec.ts

This is a partial revert of 03ce64e15195cd03. That functionality
is no longer needed in SDK as it was moved to tiger in #906.
On top of the revert there are changes in ObjRefConverter,
namely the code handling identifiers in measure and ranking
filters is now merged as it is just the same.
---
--- …

#1626: remove no longer needed code handling local identifiers

---

libs/sdk-backend-bear/src/utils/errorHandling.ts

There was unintentionally flipped conditional.
JIRA: RAIL-3991
---
--- …

RELATED: RAIL-3991 Fix the convertApiError

---

common/scripts/ci/run_cypress_tests.sh
libs/sdk-backend-bear/.gitignore
libs/sdk-backend-bear/tests/wiremock/start_wiremock.sh
libs/sdk-backend-tiger/.gitignore
libs/sdk-backend-tiger/tests/wiremock/start_wiremock.sh
libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml

* the currently used images were deprecated
* the new offical ones should work natively with M1 Macs as well
Also optimize the e2e test run on CI: only build the packages necessary, not everything. This makes the e2e build phase 40% faster (saving approx. 2 minutes).
JIRA: FET-973
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-comm …

RELATED: FET-973 Migrate to official Wiremock docker images

---

tools/plugin-toolkit/src/initCmd/index.ts

- Add --legacy-peer-deps flag to prevent user to run into an issue on newest version of NPM
JIRA: RAIL-3993
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-re …

RELATED: RAIL-3993 Add --legacy-peer-deps flag for npm

---

tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/src/plugin_entry/index.ts

Fix two minor problems in the dashboard plugin template:
* change the way the metadata.json file is imported to avoid
`Should not import the named export 'MODULE_FEDERATION_NAME' (imported as 'MODULE_FEDERATION_NAME') from default-exporting module (only default export is available soon)` warning
* remove forgotten react-intl peerDependency
JIRA: RAIL-3999
---
--- …

RELATED: RAIL-3999 Avoid webpack warning, remove non-sensical peerDep

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetExecutionDataView.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useCustomWidgetInsightDataView.ts

Also change them to functions to play nicer with api-documenter.
JIRA: RAIL-3963
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-c …

RELATED: RAIL-3963 Make the custom widget-related hooks public

---

libs/sdk-ui-dashboard/src/model/events/filters.ts

Add links to the convertors needed to use the filters in other parts
of the SDK such as visualizations or filter UI components.
JRIA: RAIL-3963
---
--- …

RELATED: RAIL-3963 Improve filter-related events TSDocs

---

libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/index.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/utils.test.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/workspaceSettingsLoader.test.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/utils.ts
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/workspaceSettingsLoader.ts

- enableRenamingMeasureToMetric FF does not work for user level.
- Refactor: removeAllInsightToReportTranslations and removeAllMeasureToMetricTranslations
JIRA: SD-1960
---
--- …

Fixed: enableRenamingMeasureToMetric FF does not work for user level.

---

tools/dashboard-plugin-template/webpack.config.js

Turns out changeOrigin: true does not work that well for POST requests,
we have to remove the origin explicitly in onProxyReq.
Also tested on bear, works there as well.
JIRA: RAIL-4014
---
--- …

RELATED: RAIL-4014 Fix plugin dev proxy on tiger

---

libs/sdk-ui-dashboard/src/plugins/customizationApis/customizationBuilder.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/filterBarCustomizer.ts
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/filterBarCustomizer.test.ts
libs/sdk-ui-dashboard/src/plugins/customizer.ts

* alow custom FilterBarComponent to be used if filterBar is not hidden
* only set the FilterBarComponent prop if necessary - this allows
the embedding code to override the FilterBarComponent itself if needed
* make the description of the "default" rendering mode more precise
JIRA: RAIL-4015
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-shoul …

RELATED: RAIL-4015 Fix hiding of the filter bar

---

tools/plugin-toolkit/src/_base/credentials.ts
tools/plugin-toolkit/src/_base/inputHandling/validators.ts
tools/plugin-toolkit/src/_base/terminal/prompts.ts
tools/plugin-toolkit/src/_base/utils.ts
tools/plugin-toolkit/src/_base/workspaceTargetConfig.ts
tools/plugin-toolkit/src/addPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/addPluginCmd/index.ts
tools/plugin-toolkit/src/initCmd/index.ts
tools/plugin-toolkit/src/inspectCmds/actionConfig.ts
tools/plugin-toolkit/src/inspectCmds/inspectCmdAction.ts
tools/plugin-toolkit/src/linkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/linkPluginCmd/index.ts
tools/plugin-toolkit/src/listCmds/actionConfig.ts
tools/plugin-toolkit/src/listCmds/listCmdAction.ts
tools/plugin-toolkit/src/unlinkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/unlinkPluginCmd/index.ts

Make the plugin-toolkit commands runnable outside of the plugin folder by:
* removing checks for pacakge.json file being present
* prompting missing options instead of failing (except for the arguments, they still fail hard by design)
Also fix some typos and remove unreachable code.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-co …

RELATED: RAIL-4010 make plugin-toolkit runnable outside of plugin folder

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/DashboardStoreProvider.tsx

We link to it from various places in the docs for public stuff, so it
itself should be public, too.
JIRA: RAIL-3963
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my …

RELATED: RAIL-3963 Mark useDashboardSelector as public

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/sortHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/tests/PluggableBarChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/tests/__snapshots__/PluggableBarChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/index.ts
libs/sdk-ui-ext/src/internal/interfaces/SortConfig.ts
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts
libs/sdk-ui-ext/src/internal/utils/sort.ts
libs/sdk-ui-ext/src/internal/utils/tests/sort.test.ts

JIRA: TNT-450
Default sorting reported from Bar chart to AD
---
--- …

Default sort for Bar chart

---

common/changes/@gooddata/sdk-ui-all/dho-rail-4030-week-filters_2022-02-23-09-36.json
common/changes/@gooddata/sdk-ui-all/dho-rail-4030-week-filters_2022-02-23-09-38.json
common/changes/@gooddata/sdk-ui-all/dho-rail-4030-week-filters_2022-02-23-09-39.json
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts

There was an "unwrap" missing which led to weeks always being broken.
Also add missing changelog entries.
---
--- …

RELATED: RAIL-4030 Fix getValidDateFilterConfig call

---

tools/plugin-toolkit/src/_base/terminal/prompts.ts
tools/plugin-toolkit/src/initCmd/actionConfig.ts
tools/plugin-toolkit/src/linkPluginCmd/actionConfig.ts
tools/plugin-toolkit/src/unlinkPluginCmd/actionConfig.ts

RELATED: RAIL-4034 Prompt dashboardId in (un)link if needed

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/common/settings.ts
libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartAxes.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsForSettings.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-ext/src/internal/components/configurationPanels/BarChartConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/BaseChartConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/BulletChartConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/tests/BulletChartConfigurationPanel.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx

JIRA TNT-188
* enableAxisNameViewByTwoAttributes - feature flag
* enableJoinedAttributeAxisName - chart config property, which propagates FF above
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/cont …

View by two attributes axis name visible with ff

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/index.ts
libs/sdk-ui-ext/src/internal/interfaces/SortConfig.ts
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/ChartSorting/AttributeDropdown/AttributeDropdown.tsx
libs/sdk-ui-kit/src/ChartSorting/ChartSorting.tsx
libs/sdk-ui-kit/src/ChartSorting/ChartSortingDropdown.tsx
libs/sdk-ui-kit/src/ChartSorting/index.ts
libs/sdk-ui-kit/src/ChartSorting/test/ChartSorting.test.tsx
libs/sdk-ui-kit/src/ChartSorting/test/mock.ts
libs/sdk-ui-kit/src/ChartSorting/types.ts
libs/sdk-ui-tests/stories/visual-regression/kit/ChartSorting/ChartSorting.tsx
libs/sdk-ui-tests/stories/visual-regression/kit/ChartSorting/ChartSortingMock.ts

JIRA: TNT-452
Move ISortConfig and related interfaces back to the sdk-ui-ext as these are used mainly for communication between PV and AD
In sdk-ui-kit we keep duplicates for now, but these can evolve as sharing dialog will need extend its props
---
--- …

Move ISortConfig interfaces back to the sdk-ui-ext

---

libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/AttributeFilterButtonUtils.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/hooks/useFetchInitialElements.ts
libs/sdk-ui-filters/src/AttributeFilter/utils/AttributeFilterUtils.ts

If the query options comes with empty uris array, the tiger backend is not able to parse the query. If the uris array is empty, query options are replaced with an empty object.
JIRA: RAIL-4049
---
--- …

RELATED: RAIL-4049 Replace options with empty object

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx
libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.fixtures.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts

Since Tiger supports two types of ids
* short, e.g. `product`
* composite, e.g. `demo_workspace:product`
and they can both link to the same object, we need to handle this in case this resolution is done only on client (because server handles this automatically). These cases are
* attribute filter ignores in query widget filters
* drilling header predicates
Unfortunately, wihout any significant breaking changes we cannot really access the backend instance in the HeaderPredicates so we try to do this match even if the backend does not support it. To be consistent we also do this in the query widget filters service. 
---
| `ok to test`             | Re-run …

RELATED: RAIL-4050, RAIL-4054 fix composite id matching

---

libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.fixtures.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts

Try converting both ids to composite and compare them. This is simpler
and actually working in all supported combinations.
Also add tests and make them data-driven and remove useless type specs.
JIRA: RAIL-4059
---
--- …

RELATED: RAIL-4059 Fix composite id handling in HeaderPredicates

---

examples/sdk-examples/src/examples/dashboardComponent/DashboardComponentWithLocalPluginSrc.tsx
libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
libs/sdk-ui/src/base/headerMatching/HeaderPredicateFactory.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.fixtures.ts
libs/sdk-ui/src/base/headerMatching/tests/HeaderPredicateFactory.test.ts
tools/catalog-export/src/loaders/tiger/tigerAnalyticalDashboards.ts
tools/catalog-export/src/loaders/tiger/tigerCatalog.ts
tools/catalog-export/src/loaders/tiger/tigerCommon.ts
tools/catalog-export/src/loaders/tiger/tigerDateDatasets.ts
tools/catalog-export/src/loaders/tiger/tigerInsights.ts
tools/catalog-export/src/loaders/tiger/tigerLoad.ts

These were only partial fixes and caused more problems than they solved. For consistency sake, we revert them for 8.9.0 and will revisit this later in a future release.
---
--- …

RELATED: RAIL-4065 revert fixes related to Tiger composite ids

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bubbleChart/PluggableBubbleChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/PluggableScatterPlot.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/PluggableTreemap.tsx
libs/sdk-ui-ext/src/internal/utils/dimensions.ts
libs/sdk-ui-ext/src/internal/utils/tests/dimensions.test.ts

Add descriptions for the following PluggableVisualizations
* Combo
* Heatmap
* Treemap
* Scatter
Also, simplify dimension tests, and simplify heatmap, combo, bullet, and scatter dimension generators.
---
--- …

RELATED: RAIL-4052 add more PlugVis descriptions

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsForSettings.test.ts
libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/insightView/InsightView.tsx

JIRA TNT-507
* **TNT-507:** Previously update config function was not considering the ability to rewrite chart config manually from InsightView property, now it will be prioritising manual input before feature flag’s value.
* **Another discovered issue:** InsightView was finishing its rendering before fetching all the data from backend, which led to incorrect view. I discovered it through feature flags, because InsightView was already rendered before receiving data about them from backend. I added one more condition before starting rendering component. 
---
| `extended test`          | BackstopJS tests …

JoinedAxisName interaction with InsightView

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/__snapshots__/PluggableBulletChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/__snapshots__/PluggableComboChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts

JIRA: TNT-457
Bullet chart supports custom sorting, reports its default and available sorts for every bucket combination
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell- …

Bullet chart custom sorting

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/__snapshots__/PluggableAreaChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/PluggableColumnChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/__snapshots__/PluggableColumnChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/__snapshots__/PluggableComboChart.test.tsx.snap

JIRA: TNT-520
Fix available sorts for Column Chart.
JIRA: TNT-525
Bar chart sorting is aware of empty measures.
---
--- …

Column, Bar, Area, Combo chart fixes.

---

libs/sdk-ui-dashboard/src/internal.ts
libs/sdk-ui-dashboard/src/model/utils/alertsUtils.ts
libs/sdk-ui-dashboard/src/presentation/constants/index.ts
libs/sdk-ui-dashboard/src/presentation/saveAs/DefaultSaveAsDialog/SaveAsDialogRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-dashboard/tsconfig.build.json

This is the first step towards getting rid of DashboardView:
gdc-dashboards depend on some internals, so we need to
export them from their new locations in sdk-ui-dashboard.
We had to add getBrokenAlertFiltersBasicInfoLegacy because
the new one would be very hard to use in gdc-dashboards as is
and it could potentially break existing stuff there.
JIRA: RAIL-4046
---
--- …

RELATED: RAIL-4046 Add internal barrel to sdk-ui-dashboard

---

common/config/rush/pnpm-lock.yaml

This fixes several npm audit advisories.
JIRA: FET-993
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think …

RELATED: FET-993 Upgrade url-parse 1.5.3 -> 1.5.10

---

tools/catalog-export/src/index.ts

- If the folder where catalog export should be saved does not exist, the script will create the folder instead of script failure.
JIRA: RAIL-3485
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …

RELATED: RAIL-3485 Create folder for catalog export if not exist

---

libs/sdk-ui-kit/src/ChartSorting/ChartSortingDropdown.tsx
libs/sdk-ui-kit/src/ChartSorting/test/ChartSorting.test.tsx

Additionally, the logic of generating available sort controls in UI was changed to be generated from available sorts array instead of current sorts array to make the code more understandable.
JIRA: TNT-514
---
--- …

Fix issue in chart sort dialog when current sort does not match available sorts length

---

libs/sdk-ui-charts/src/charts/_commons/sanitizeStacking.ts
libs/sdk-ui-charts/src/charts/donutChart/DonutChart.tsx
libs/sdk-ui-charts/src/charts/pieChart/PieChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/__snapshots__/PluggableHeatmap.test.tsx.snap

- TNT-544:  In case `enableChartSorting` is set to true and no `sortBy` was specified by user, need to make sure that insight is aware that it should get sort by default.
- TNT-543: Update custom sort order for Heatmap chart, so it matches old sort behaviour.
---
---
-   [ …

Custom Sort - sanitize insight config, update heatmap default order

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/tests/__snapshots__/PluggableAreaChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/__snapshots__/PluggableBulletChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/PluggableColumnChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/tests/__snapshots__/PluggableColumnChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/tests/__snapshots__/PluggableLineChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx
libs/sdk-ui-ext/src/internal/interfaces/SortConfig.ts
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui-ext/src/internal/utils/sort.ts

JIRA: TNT-466
PVs now explain why the sorting is disabled via tooltip text
Code unification cross all sortable PVs 
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my …

Chart Sorting disabled tooltips

---

libs/sdk-ui-ext/src/internal/utils/sort.ts
libs/sdk-ui-ext/src/internal/utils/tests/sort.test.ts

Fix reusage of sorts

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/utils/sort.ts
libs/sdk-ui-ext/src/internal/utils/tests/sort.test.ts

JIRA: TNT-548
Remember previous available sorts and use them for better handling of changed buckets.
Without this some scenarios can't be distinguished - metric sort can not be tracked to the original or new attribute
---
--- …

Track previous availableSorts to better deal with change

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/tests/__snapshots__/PluggableBulletChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx

Fix availableSorts in moment of disabled sort

---

libs/api-model-bear/api/api-model-bear.api.md
libs/api-model-bear/src/visualizationWidget/GdcVisualizationWidget.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/widget.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/dashboards/analyticalWidgets.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/analyticalDashboards/v2/AnalyticalDashboardConverter.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx

Add previously reverted support for hiding title.
Reworked, so that configuration and configuration.hideTitle is not mandatory
JIRA: TNT-187
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributi …

RELATED: TNT-187 Enable hiding widget title

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/PluggableBarChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/PluggableColumnChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx
libs/sdk-ui-ext/src/internal/interfaces/Visualization.ts

JIRA: TNT-566
Previous available sorts cant be stored in PV, it does not work with AD's Undo/Redo
So the previous available sorts are provided by AD as a part of reference point. But they not trigger changed reference point logic
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-shoul …

Previous available sorts provided by AD

---

libs/sdk-ui-kit/src/ChartSorting/AttributeDropdown/AttributeDropdown.tsx

JIRA: TNT-514
Handle the states when AD provides mismatching props after bucket content changed
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master …

Handle mismatching props

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextState.ts

- make all filterContext related selectors public
- update tsdoc for api reference
JIRA: RAIL-4091
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/mas …

RELATED: RAIL-4091 Productise filter context selectors

---

libs/sdk-backend-bear/src/backend/workspace/attributes/elements/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/attributes/elements/index.ts
libs/sdk-backend-tiger/src/backend/workspace/attributes/elements/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/getElementTitle.ts
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/useBrokenAlertFiltersMeta.ts
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterButton/hooks/useFetchInitialElements.ts

Propose a new configuration option to specify attribute elements in attribute elements query.
This allows backends that support it to specify what kind of element value they are sending.
Also deprecate the old way of doing the same thing and deprecate not well documented and seemingly unused prompt config.
---
--- …

RELATED: RAIL-4093 better API for elements specification in attribute elements query

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

Change `enableAxisNameViewByTwoAttributes` to true by default

---

libs/sdk-ui-kit/src/Overlay/Overlay.tsx

When used from react 17, these events are not triggered
Example: repeat dropdown in schedule email dialog cannot be closed on
outside click.
React 17 no longer attaches event handlers at the document level,
instead it attaches them to the root node where the React tree is rendered
[https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation]
JIRA: FET-626
---
---
- …

RELATED: FET-626 Register handlers with capture

---

libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/measures.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/measures/index.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

- add getMeasures() into workspace measure service to be able to acquire limited measure objects only
JIRA: RAIL-4066
---
--- …

RELATED: RAIL-4066 measures backend spi

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/adapter/test/HighChartsRenderer.test.tsx
libs/sdk-ui-charts/styles/scss/charts.scss
libs/sdk-ui-dashboard/styles/scss/drillSelect.scss

Position adjustment for Zoom reset icon and Context menu icon once Widget title is hidden. There is also change related to vertical alignment of reset icon to fit into middle of the given circle.
JIRA: TNT-601, TNT-604
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commit …

RELATED: TNT-187 Position adjustment for Zoom and Context menu icons

---

libs/api-client-bear/src/tests/xhr.test.ts
libs/api-client-bear/src/xhr.ts

Fail when /gdc/account/token api returns error
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-re …

RELATED: TNT-629 Correctly handle token api error

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/rsqlFilter.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/test/rsqlFilter.test.ts
libs/util/src/stringUtils.ts
libs/util/src/tests/stringUtils.test.ts

Update 'stringUtils' - 'parseStringToArray' to accept spaces.
With tags allowing spaces in DB, need to pass correct format to RSQL parser arguments to make filtering option work correctly. 
JIRA: TNT-580
---
---
- …

Allow to filter tags with spaces

---

tools/dashboard-plugin-template/webpack.config.js

The old variant did not specify versions for peerDeps properly.
That was not intentional, so fix it appropriately.
Note that this does not fix the related issue, it just prevents
uncertainty in the future.
JIRA: RAIL-4117
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-com …

RELATED: RAIL-4117 Fix the version specs in webpack config

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/adapter/test/HighChartsRenderer.test.tsx
libs/sdk-ui-charts/styles/scss/charts.scss
libs/sdk-ui-dashboard/styles/scss/drillSelect.scss

Position adjustment for Zoom reset icon and Context menu icon once Widget title is hidden.
JIRA: TNT-601, TNT-604
---
--- …

Position adjustment for Zoom reset icon and Context menu icon 

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/tests/__snapshots__/PluggableComboChart.test.tsx.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/__snapshots__/PluggableHeatmap.test.tsx.snap
libs/sdk-ui-ext/src/internal/tests/mocks/referencePointMocks.ts

JIRA: TNT-611
Dont offer sort by total in Combo and Heatmap when there is only single measure to keep it consistent with other charts
---
--- …

Dont offer area sort when there is only single measure

---

libs/sdk-ui-kit/src/Overlay/Overlay.tsx

Necessary when used from React17
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-ap …

RELATED: FET-626 No more default stopPropagation

---

libs/sdk-ui-all/api/sdk-ui-all.api.md
libs/sdk-ui-all/src/index.ts
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/index.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/AreaChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/BarChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bubbleChart/BubbleChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/BulletChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/ColumnChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/ComboChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/donutChart/DonutChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/funnelChart/FunnelChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/GeoPushpinChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/HeatmapDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/LineChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PieChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/ScatterPlotDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/TreemapDescriptor.ts
libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap
libs/sdk-ui-geo/api/sdk-ui-geo.api.md
libs/sdk-ui-geo/src/index.ts

Make the predicate available in charts and geo.
This makes it easier for the end users as they no longer need to install
sdk-ui-vis-commons explicitly to use the generated mapping code.
JIRA: RAIL-4069
---
---
- …

RELATED: RAIL-4069 Improve colorMapping codegen

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/List/ListItem.tsx

Add type for events in handlers click, mouseover and mouseout
JIRA: NAS-3405
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing. …

NAS-3405 - Update sdk version in metric editor cause event is not stop propagation

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.test.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/tests/__snapshots__/PluggableHeatmap.test.tsx.snap

JIRA: TNT-611
Exception for Heatmap, which will offer area sort even for single metric for 1M+1Cols bucket items. Other charts have in such case sorting disabled, but it is UX decision
---
--- …

Heatmap offers are sort even for single metric

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/index.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardScheduledEmails.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/test/ScheduledMailDialogRenderer.test.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/index.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/useScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/useInsightMenu.ts

Show schedule export option in insight widget menu which opens scheduling dialog with particular widget attachment set up.
JIRA: TNT-652
---
--- …

Add shortcut for scheduling widget export

---

libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyInsightMenu/LegacyInsightMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/DashboardItemWithKpiAlert.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Overlay/Overlay.tsx
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-vis-commons/src/legend/LegendItem.tsx
libs/sdk-ui-vis-commons/src/legend/Paging.tsx
libs/sdk-ui-vis-commons/src/legend/PopUpLegend/RowLegend.tsx

* keep stopPropagation in overlays (use Portal) but at the same time re-send the events to the `document` where all overlays listen for events.
* avoid stopPropagation for some events which need to get to parent apps (with possibly another different react root) so that these actions, when triggered, can cause closing of other overlays.
---
--- …

RELATED: FET-626 React 17 additional support for overlay handling

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-tiger/package.json
libs/sdk-backend-tiger/src/auth.ts

This was supported only in Tiger < 1.1 which we no longer support
in current versions of SDK so it is safe to remove.
It also removed the last use of the http-status-codes dependedncy
in sdk-backend-tiger so it was removed as a whole as well.
JIRA: RAIL-4181
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/doc …

RELATED: RAIL-4181 Remove POST to /logout

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts

- Some old plugins are dependant of this default value
JIRA: TNT-691
---
--- …

Reintroduce `enableSectionHeaders` FF

---

libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
libs/sdk-ui-kit/styles/scss/editableLabel.scss

Introduced with adding an intermediate div during ref forwarding in https://github.com/gooddata/gooddata-ui-sdk/pull/2442
JIRA: TNT-724
---
--- …

Fix EditableLabel css styles

---

libs/sdk-ui-dashboard/src/presentation/dashboard/Dashboard.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardLoading.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardMainContent.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/hooks/useDashboard.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/ClientWorkspaceContext/ClientWorkspaceContext.tsx
libs/sdk-ui/src/base/react/ClientWorkspaceContext/interfaces.ts

- added check if the clientWorkspaceContext is initialized
- if clientWorkspaceContext is initialized, Dashboard component is going to wait until workspace id is resolved
JIRA: RAIL-4085
---
--- …

RELATED: RAIL-4085 Fix for lcm workspace loading issue

---

tools/dashboard-plugin-template/src/harness/PluginLoader.tsx
tools/dashboard-plugin-template/src/harness/Root.tsx
tools/dashboard-plugin-template/src/harness/backend.ts
tools/dashboard-plugin-template/src/harness/constants.ts

- replacing nullish coalescing with OR operator to replace empty strings from env file with defaults as well
- add check if the authentication is required or not
The plugin is now running smoothly without the need to set up the backend, workspace, or dashboard id in the harness application to test the plugin locally. 
JIRA: RAIL-4190
---
--- …

RELATED: RAIL-4190 Fix default project settings in plugin template

---

libs/api-client-tiger/src/axios.ts
libs/api-client-tiger/src/typings.d.ts
libs/api-client-tiger/tsconfig.build.json
libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-bear/src/typings.d.ts
libs/sdk-backend-bear/tsconfig.build.json
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-backend-tiger/src/typings.d.ts
libs/sdk-backend-tiger/tsconfig.build.json
libs/sdk-ui-pivot/src/PivotTable.tsx

This aligns the behavior between bear and tiger and enables us
to determine how the SDK is used.
Also fix PivotTable telemetry, now it behaves like other charts.
JIRA: RAIL-4157
---
---
-   [ ] review was done by …

RELATED: RAIL-4157 Properly fill X-GDC-JS-PACKAGE{,-VERSION}

---

examples/sdk-examples/test/utils/config.ts
libs/api-client-bear/src/execution/experimental-executions.ts
libs/api-model-bear/src/visualizationObject/utils.ts
libs/sdk-backend-bear/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-bear/src/backend/workspace/insights/index.ts
libs/sdk-backend-bear/src/backend/workspace/measures/index.ts
libs/sdk-backend-bear/src/convertors/fromBackend/DashboardConverter/layout.ts
libs/sdk-backend-bear/src/convertors/toBackend/DashboardConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/WorkspaceConverter.ts
libs/sdk-backend-bear/src/convertors/toBackend/afm/ExecutionConverter.ts
libs/sdk-ui-charts/src/highcharts/adapter/legendHelpers.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/extendedStackingChartOptions.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts
libs/sdk-ui-dashboard/src/_staging/dateFilterConfig/defaultConfig.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/sizing.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/ScheduledMailDialogRenderer.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/PluggableComboChartDeprecated.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/sortItemsHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/widthItemsHelpers.ts
libs/sdk-ui-ext/src/internal/utils/bucketHelper.ts
libs/sdk-ui-ext/src/internal/utils/bucketRules.ts
libs/sdk-ui-ext/src/internal/utils/sort.ts
libs/sdk-ui-geo/src/core/geoChart/GeoChartInner.tsx
libs/sdk-ui-geo/src/core/geoChart/geoChartColor.ts
libs/sdk-ui-geo/src/core/geoChart/geoChartDataSource.ts
libs/sdk-ui-geo/src/core/geoChart/helpers/geoChart/data.ts
libs/sdk-ui-kit/src/Header/tests/activateHeaderMenuItems.test.ts
libs/sdk-ui-pivot/src/impl/resizing/columnSizing.ts
libs/sdk-ui/src/base/react/placeholders/resolve.ts

Avoid spread operator and concat on accumulators in reduce callbacks
as they both create new objects. That is wasteful and slow, we should
prefer mutating the accumulator instead.
JIRA: FET-1013
---
---
-   [ ] …

RELATED: FET-1013 Optimise uses of Array.reduce

---

libs/sdk-ui-charts/package.json
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-ext/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-geo/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-loaders/package.json
libs/sdk-ui-pivot/package.json
libs/sdk-ui-tests-e2e/package.json
libs/sdk-ui-vis-commons/package.json
libs/sdk-ui/package.json

This reverts commit 919aa0a1c21e82278a5c2d88cc756b8aecfb3b6a.
- `"sideEffects": false` in SDK libraries causes that es6 imports of the SDK styles in applications are tree shaked and removed.
JIRA: FET-1002
---
--- …

Revert "Remove svg and css files from sideEffects"

---

libs/api-client-tiger/openapi-generator/api.mustache
libs/api-client-tiger/openapi-generator/apiInner.mustache
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/api.ts

The "url" import is no longer needed, so let's get rid of it.
JIRA: RAIL-4192
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing …

RELATED: RAIL-4192 Remove useless import in template

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/componentDefinition/index.ts
libs/sdk-ui-dashboard/src/presentation/componentDefinition/renderModeAware.tsx
libs/sdk-ui-dashboard/src/presentation/componentDefinition/types.ts
libs/sdk-ui-dashboard/src/presentation/index.ts

- add helper function for switching component by render mode
- add types for defining custom attributeFilter, KpiWidget and general Widget in all modes and helper components
JIRA: RAIL-4110
---
---
-   [ ] review …

RELATED: RAIL-4110 Add generalized to define custom components with render mode support

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-base/package.json

This is to fix a security advisory in the package.
JIRA: FET-1019
---
--- …

RELATED: FET-1019 Upgrade @braintree/sanitize-url 5.0.2 -> 6.0.0

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Button/Button.tsx
libs/sdk-ui-kit/src/Button/typings.ts
libs/sdk-ui-kit/src/Dropdown/DropdownButton.tsx

The prop is necessary for definition of the relationship between the button and its label (actual HTML label element).
JIRA: TNT-679
---
--- …

Introduce id prop for Button and DropdownButton

---

libs/sdk-backend-tiger/src/backend/uiSettings.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/__snapshots__/handler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/tests/handler.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/ui/changeRenderModeHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/ui/tests/changeRenderModeHandler.test.ts
libs/sdk-ui-dashboard/src/model/disabledUnfinishedFeatureSettings.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts

Create dashboardEditModeDevRollout feature flag
---
--- …

RELATED: RAIL-4102 Create dashboardEditModeDevRollout feature flag

---

libs/api-client-bear/src/user.ts
libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-tiger/src/backend/index.ts

Go through the auth-related code in tiger and bear and simplify it/clean it up. The transformations were meant to maintain the original behaviour as much as possible. The transformations include:
* using async if it makes the code simpler
* avoiding separate error handlers that can be merged
* removing boilerplate-y code especially in api-client-ber user section
The transformations were done one-by-commit in bear and then applied in bulk to tiger so go commit by commit for some more info on a given transformation.
---
| `extended check sonar`   | …

RELATED: FET-903 simplify and clean up auth-related code

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Form/focus.ts
libs/sdk-ui-tests/stories/visual-regression/kit/Input/Input.tsx
libs/sdk-ui-tests/stories/visual-regression/kit/Input/styles.scss

Autofocus reimplementation
- run autofocus method to start request animation frame and try to focus input as soon as possible (is visible, not hidden and has size)
- clear after unmount to disable autofocus
- reset after props changed
JIRA: FET-863
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …

FET-863 - Reimplement autofocus in InputPure

---

libs/sdk-ui-tests/backstop/backstop.config.js
libs/sdk-ui-tests/backstop/run-backstop.sh

- so you can see storybook link in github comment, when tests fail
JIRA: RAIL-1027
---
--- …

Propagate failed test result to CI

---

tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/src/harness/index.tsx

- So PivotTable and GeoPushpin charts are rendered correctly when running plugin locally
JIRA: RAIL-4205
---
--- …

Plugin harness - add GeoPushpin and PivotTable css

---

common/config/rush/.pnpmfile.cjs
common/config/rush/pnpm-lock.yaml

The majority of changes in pnpm.lock is change from czech to english
ordering (H CH I to CH being sorted as C).
JIRA: FET-1034
---
--- …

RELATED: FET-1034 Fix security audit issues in urijs

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts

Make the Error and Loading component mandatory so that
the implementers do not have to check that they are there.
JIRA: RAIL-4129
---
--- …

RELATED: RAIL-4129 Improve the usability of the IInsightBodyProps

---

tools/dashboard-plugin-template/package.json
tools/plugin-toolkit/scripts/preparePackageJson.ts

Keep prettier scripts
replace config eslint directly in package.json
JIRA: RAIL-4194
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contr …

RAIL-4194 - Plugin bootstrap removes eslint config from package on init

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

Make sure the InsightBody is hidden on error so that the caller can handle the error consistently.
JIRA: RAIL-4226
---
--- …

RELATED: RAIL-4226 Unify InsightBody display logic

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveDashboardConfig.ts
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/saveAsButton/DefaultSaveAsNewButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/selectors.ts

- apply config defaults to resolved config as well
- hide save as new Button when EditModeDevRollout is disabled
JIRA: RAIL-4106
---
--- …

Fix view mode defaults and buttons visibility

---

libs/sdk-ui-dashboard/src/plugins/customizer.ts

- example was wrong, decoration must happen in the provider, not in the component render function (otherwise it can lead to infinite re-render loop)
- mention it explicitly in the comment to avoid future confusion
JIRA: RAIL-4227
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should …

Correct example of the plugin decorator

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PivotTableDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/pivotTableAdditionalFactories.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/__snapshots__/pivotTableAdditionalFactories.test.ts.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/tests/pivotTableAdditionalFactories.test.ts
libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap

This makes the codegen output much more readable and shorter when using the PivotTable column sizing features.
JIRA: RAIL-4240
---
--- …

RELATED: RAIL-4240 Add factory notation support for column sizing

---

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx

IntlWrapper must not be around this component as "locale" prop that is used here is converted to be compatible with moment.js that uses different locale name for Chinese language than used by GD. Application throws unrecoverable error when used in Chinese localization.
JIRA: TNT-792
---
--- …

Remove unnecessary IntlWrapper that triggers error

---

libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/tests/DateRangePicker.test.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/utils.ts
libs/sdk-ui-filters/src/DateFilter/tests/AbsoluteForm.tsx
libs/sdk-ui-filters/src/DateFilter/tests/DateFilter.test.tsx
libs/sdk-ui-filters/src/DateFilter/tests/utils.ts
libs/sdk-ui-filters/src/DateFilter/validation/OptionValidation.ts
libs/sdk-ui-filters/styles/scss/components/DateRangePicker.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

Removed auto correction within Absolute Date filter once Start time is after End time. It has been replaced by highlighting of incorrect value.
JIRA: TNT-793, TNT-794
---
--- …

Related: TNT-793, TNT-794 Removed auto correction of Start time based on End Time

---

libs/sdk-ui-dashboard/.dependency-cruiser.js
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeaderRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/EditableLabelWithBubble.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/sectionHeaderHelper.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/RenderModeAwareDashboardLayoutSectionHeaderRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/emptyFacade.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/styles/scss/layout.scss

- depending on the render mode, make section headers editable
JIRA: RAIL-4104
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing …

RAIL-4104 Make Section headers editable

---

libs/sdk-ui-dashboard/src/model/commandHandlers/render/renderingWorker.ts
libs/sdk-ui-dashboard/src/model/commands/render.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardAsyncRender.ts

JIRA: TNT-791
Sync SDK timeout with exporter timeout to use its full potential on extensive dashboards
---
--- …

Increase render worker timeout

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/areaChart/AreaChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/barChart/BarChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bubbleChart/BubbleChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/bulletChart/BulletChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/columnChart/ColumnChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/comboChart/ComboChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/donutChart/DonutChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/funnelChart/FunnelChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/GeoPushpinChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/geoConfigFromInsight.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/headline/HeadlineDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/heatMap/HeatmapDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/lineChart/LineChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pieChart/PieChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PivotTableDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/pivotTableConfigFromInsight.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/scatterPlot/ScatterPlotDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/treeMap/TreemapDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/xirr/XirrDescriptor.ts
libs/sdk-ui-ext/src/internal/components/tests/VisualizationCatalog.test.ts
libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap
libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/getReactEmbeddingCodeGenerator.ts
libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/index.ts
libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/insightToPropsConverter/convenience.ts

* RAIL-4249 - Provide Mapbox token placeholder
* RAIL-4251 - Propagate enableJoinedAttributeAxisName
* RAIL-4252 - Handle enableChartSorting config
* RAIL-4253 - Fix pivot config in codegen: Now the config logic is reused from PluggablePivotTable. This means the menu config is now correct on both bear and tiger.
* RAIL-4260 - Handle locale in codegen
Also fix default and named imports from the same package at the same time.
---
| `extended …

RELATED: RAIL-4249,RAIL-4251,RAIL-4252,RAIL-4253,RAIL-4260 codegen fixes

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/test/chartOptionsBuilder.test.ts

It has been decided to change the limit for all the charts using default limit since we have not experienced any performance issue.
JIRA: TNT-798
---
--- …

RELATED: TNT-798 Increased default limit for displayed datapoints

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/.i18nrc.js
libs/sdk-ui-dashboard/package.json
libs/sdk-ui/.i18nrc.js
libs/sdk-ui/package.json
tools/i18n-toolkit/.i18nrc.js
tools/i18n-toolkit/README.md
tools/i18n-toolkit/package.json
tools/i18n-toolkit/src/config.ts
tools/i18n-toolkit/src/data.ts
tools/i18n-toolkit/src/fixtures/en-US.json
tools/i18n-toolkit/src/index.ts
tools/i18n-toolkit/src/localizations.ts
tools/i18n-toolkit/src/utils/console.ts
tools/i18n-toolkit/src/utils/index.ts
tools/i18n-toolkit/src/validate.ts
tools/i18n-toolkit/src/validations/defaultLocales.ts
tools/i18n-toolkit/src/validations/htmlSyntax.ts
tools/i18n-toolkit/src/validations/insightToReport.ts
tools/i18n-toolkit/src/validations/messageFormat.ts
tools/i18n-toolkit/src/validations/messagesUsage.ts
tools/i18n-toolkit/src/validations/structure.ts
tools/i18n-toolkit/src/validations/test/insightToReport.test.ts
tools/i18n-toolkit/src/validations/test/structure.test.ts
tools/i18n-toolkit/src/validations/usage/checkTranslations.ts

Add usage check with config support
JIRA: FET-1033
---
--- …

FET-1033 - Add localisations validation to SDK-UI

---

libs/sdk-ui/src/execution/createExecution.ts
libs/sdk-ui/src/execution/tests/Execute.test.tsx
libs/sdk-ui/src/execution/tests/__snapshots__/Execute.test.tsx.snap

Previously, the MeasureGroupIdentifier was included even if the seriesBy had only attributes in it (a legit use case, like PivotTable with Rows only). This would make the backend throw a 400 complaining about it like
> "Specified 'measureGroup' but no measures found in AFM"
This makes sure the MeasureGroupIdentifier is there only if needed.
JIRA: RAIL-4265
---
--- …

RELATED: RAIL-4265 Fix executions without measures

---

libs/sdk-model/src/execution/objectFactoryNotation/index.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
libs/sdk-ui-ext/src/internal/components/tests/__snapshots__/VisualizationCatalog.test.ts.snap
libs/sdk-ui-ext/src/internal/utils/embeddingCodeGenerator/insightToPropsConverter/convenience.ts
libs/sdk-ui-ext/src/internal/utils/sort.ts
libs/sdk-ui-ext/src/internal/utils/tests/sort.test.ts

Make sure the default sorts are applied in the code gen as well.
This needed some refactoring and API rationalizations.
Also simplify the measureSort factory notation output when there are no attribute locators.
JIRA: RAIL-4250
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-t …

RELATED: RAIL-4250 Make the default sorts work in code gen

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/index.ts
libs/sdk-backend-spi/src/workspace/attributes/elements/index.ts
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/package.json
libs/sdk-ui-filters/src/AttributeFilterHandler.ts
libs/sdk-ui-filters/src/index.ts

This is the first version of the proposed API for the attribute filter
helper class. It does not yet cover all the use cases we want, but is
complete enough for us to start implementing it.
Also add a common type for ElementsQueryOptionsElementsSpecification.
JIRA: RAIL-4228
---
--- …

RELATED: RAIL-4228 Draft the API for AttributeFilterHandler

---

libs/sdk-backend-bear/src/backend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/capabilities.ts
libs/sdk-backend-tiger/src/backend/index.ts
libs/sdk-model/src/execution/objectFactoryNotation/tests/index.test.ts
libs/sdk-ui-dashboard/src/model/queryServices/tests/__snapshots__/queryWidgetFilters.test.ts.snap
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/chartCodeGenUtils.ts

For backends that do not allow custom colorPalettes it makes no sense
to include them in the generated code.
JIRA: RAIL-4268
---
--- …

RELATED: RAIL-4268 Skip color palette for some backends in code gen

---

tools/plugin-toolkit/scripts/build.sh

- Currently, only files starting with a dot are copied
- Fix this to copy also files not starting with a dot
JIRA: RAIL-4270
---
--- …

Copy all configuration files for plugin template

---

libs/sdk-backend-tiger/src/backend/workspace/measures/measureExpressionTokens.ts
libs/sdk-backend-tiger/src/backend/workspace/measures/test/measureExpressionTokens.test.ts

RAIL-4271 "Defined as" tooltip not working for metrics using new grammar

---

libs/sdk-ui-kit/src/List/LegacyList.tsx
libs/sdk-ui-kit/src/List/List.tsx

We observed an issue with large data in fixed-data-table-2 that causes the crash with virtual memory allocation (usually with data large than 80M records)
JIRA: TNT-787
---
--- …

RELATED: TNT-787 Setting max limit for fixed data table

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addLayoutSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/changeLayoutSectionHeaderHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/utils.ts
libs/sdk-ui-dashboard/src/model/commands/index.ts
libs/sdk-ui-dashboard/src/model/commands/insight.ts
libs/sdk-ui-dashboard/src/model/store/meta/metaSelectors.ts
libs/sdk-ui-dashboard/src/model/store/meta/tests/metaSelectors.test.ts
libs/sdk-ui-dashboard/src/model/tests/fixtures/ComplexDashboard.fixtures.ts

Makes use of several sub-selectors to improve performance.
Also sanitizes section headers removing unused fields.
JIRA: RAIL-4108
---
--- …

RELATED: RAIL-4108 Implement and test selectIsDashboardDirty

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutUtils.ts

Make sure the widgets are only re-rendered when they actually change.
This is done by memoizing the widget sanitization results and reusing as much as possible.
---
--- …

RELATED: RAIL-4273 prevent unnecessary re-renders in edit mode

---

examples/playground/tsconfig.json
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/DashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ShareDialogDashboardHeader.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutWidgetRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/EditableLabelWithBubble.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/DefaultDashboardInsight/DashboardInsightWithDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/useInsightMenu.ts
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/IntlStore.ts
libs/sdk-ui/src/base/localization/IntlWrapper.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/TranslationsCustomizationProvider.tsx
libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/tests/utils.test.ts
libs/sdk-ui/src/base/localization/intlUtils.tsx
libs/sdk-ui/src/base/localization/messagesMap.ts

Several smaller improvements to the performance of Dashboard component.
Also improve the code around Intl: deduplicate some code and rewrite Customizations to use cancelable promises.
Also improve type checking in playground: it now ignores unused files making the error output clearer.
---
--- …

RELATED: RAIL-4273 more dashboard perf improvements

---

common/config/rush/pnpm-lock.yaml
examples/playground/package.json
examples/playground/webpack.config.js
examples/sdk-examples/package.json
examples/sdk-examples/src/context/auth/index.ts
examples/sdk-examples/webpack.config.js
libs/api-client-bear/package.json
libs/sdk-ui-tests-e2e/package.json
libs/sdk-ui-tests-e2e/scenarios/webpack.config.js
tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/src/harness/backend--tiger.ts
tools/dashboard-plugin-template/webpack.config.js
tools/dashboard-plugin-tests/plugins-loader/webpack.config.js

Upgrade webpack-dev-server to avoid npm security audit errors on install of a new plugin.
Fix plugin template on tiger: it was missing a function export that is needed by the Root.tsx file.
---
---
-   [ ] review …

RELATED: RAIL-4275 upgrade webpack-dev-server, fix plugin template

---

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

- update ThemeProvider to remove previous theme style just before setting the new ones
- also make removal of the global styles during the unmount phase optional (and avoid it when disableThemeLoading is true in Dashboard component)
JIRA: RAIL-4246
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …

Avoid flickering of the theme in dashboard plugins

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-json-api/api.ts
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/backend/workspace/measures/index.ts

RAIL-4271 - "Defined as" tooltip not working for metrics using new grammar

---

libs/sdk-ui-loaders/api/sdk-ui-loaders.api.md
libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/adaptiveComponentLoaders.ts
libs/sdk-ui-loaders/src/dashboard/loadingStrategies/staticComponentLoaders.ts
libs/sdk-ui-loaders/src/dashboard/types.ts
libs/sdk-ui-loaders/src/dashboard/useDashboardLoader.ts

This is useful for loading an empty dashboard with some local plugins.
JIRA: RAIL-4171
---
--- …

RELATED: RAIL-4171 Allow dashboard loaders load empty dashboards

---

libs/sdk-ui/src/base/localization/TranslationsCustomizationProvider/TranslationsCustomizationProvider.tsx

This reverts commit be863c7315159d5f52c90dd9f4cc9c4655402e51.
TNT: TNT-845
---
--- …

RELATED: TNT-845 Revert "Use useCancelablePromise in TranslationsCustomization"

---

libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilterLoader/factory.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/impl/bridge/index.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/impl/loader.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/impl/multiSelectHandler.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/impl/singleSelectHandler.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/index.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/effects.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/attributeElements/sagas.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/main/reducers.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/main/sagas/init.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/main/selectors.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/internal/store/state.ts
libs/sdk-ui-filters/src/AttributeFilterLoader/types/loader/index.ts
libs/sdk-ui-filters/src/index.ts

This allows the user to deny-list certain elements from the filter.
These will not be available in the loaded elements and will also be excluded in the resulting filter.
---
--- …

RELATED: RAIL-4231 add support for hiding attribute elements from the filter

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

When adding totals in table, this is via the svg icon placed in table.
This svg does not have className as string and fails with javascript
error when trying to query this.
So be defensive when looking for table resizer (which is not an svg)
JIRA: RAIL-4299
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs …

RELATED: RAIL-4299 ui-sdk-pivot: fix js error on adding totals

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/tooltip.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts

If stackTo100 is set then it propagates only percentage and custom format (with '%' in the end of string) from bucket to insight values. In case of any other format it sets decimal points to two.
JIRA: TNT-422
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-li …

RELATED: TNT-422 Percentage format propagation into insight

---

libs/sdk-ui-kit/styles/scss/dialog.scss
libs/sdk-ui-kit/styles/scss/loadingMask.scss

FET: 932 Preparation for AD/KD
Update scss rules to fix errors/warnings for `dart-sass` migration on AD/KD
---
--- …

Fix scss rules to make it work with `dart-sass`

---

common/scripts/ci/init_hotfix_branch.sh

The regular expression must not be in quotes.
JIRA: RAIL-4328
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tel …

RELATED: RAIL-4328 Fix init_hotfix_branch

---

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
libs/sdk-ui-theme-provider/api/sdk-ui-theme-provider.api.md
libs/sdk-ui-theme-provider/src/ThemeProvider/ThemeProvider.tsx
libs/sdk-ui-theme-provider/src/ThemeProvider/tests/ThemeProvider.test.tsx

- update ThemeProvider to remove previous theme style just before setting the new ones
- also make removal of the global styles during the unmount phase optional (and avoid it when disableThemeLoading is true in Dashboard component)
JIRA: RAIL-4246
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contribu …

HOTFIX: RAIL-4274 Avoid flickering of the theme in dashboard plugins

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/features/hub.ts
libs/sdk-backend-tiger/src/backend/features/static.ts
libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts

JIRA: NAS-3998
(cherry picked from commit 6873f54a065110e4276f6b65a981f28783a4e5ac)
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contri …

NAS-3998 - server-evaluated key for FH must be used in frontend SDK

---

libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts
libs/sdk-model/src/execution/results/index.ts
libs/sdk-ui-pivot/src/impl/structure/colLocatorMatching.ts

Tiger now returns nulls for empty values (api-client-tiger will be regenerated in a separate commit, the OpenAPI spec is not ready).
Also pivot table needs to handle empty strings in its column resizing.
Finally, fixed some typos encountered along the way.
JIRA: RAIL-4330
---
--- …

RELATED: RAIL-4330 Fix column sizing for empty values on tiger

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/tooltip.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_util/common.ts
libs/sdk-ui-charts/src/highcharts/constants/format.ts

RELATED: TNT-888 Fixing default decimal separator for percentFormatter

---

libs/sdk-ui-kit/src/Header/Header.tsx

Fix header countdown render logic

---

libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts

We need to handle also the cases when the error is wrapped
in and UnexpectedResponseError object.
JIRA: SD-2249
---
--- …

RELATED: SD-2249 Handle getOrganizationPermissions errors better

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/insight/sanitization.ts
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/utils.ts

This PR make it impossible to add subtotals to a pivot table sorted by other than the first attribute.
JIRA: NAS-3939
---
--- …

BUGFIX: NAS-3939 add subtotals to a sorted pivot table

---

libs/sdk-backend-tiger/src/convertors/fromBackend/fixLegacyElementUris.ts

Currently, the OpenAPI spec is not correct for parts of Tiger so some
items can now be null even though the spec says they can't.
This is a symptomatic fix, we will revisit this once CAL-515 is done.
JIRA: CAL-512
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-loo …

RELATED:  CAL-512 Make fixLocatorItem more robust

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/AttributeDropdownListItem.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/DropdownConfiguration.tsx
libs/sdk-ui-dashboard/src/presentation/layout/EmptyDashboardError.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentNoWidgets.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/Attachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentsSelectionDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/FormatOptionsDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/ScheduleDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/test/AttachmentNoWidgets.test.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatExecuteOnSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatFrequencySelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/RepeatSelect/RepeatTypeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/LegacyDefaultDashboardInsightMenu/LegacyInsightMenu/LegacyInsightMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlertDialogWrapper.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialogDateRange.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx
tools/i18n-toolkit/src/utils/console.ts

This makes sure that useIntl is used instead of injectIntl where practically possible. This makes the React tree smaller as there are less components. This in turn makes debugging slightly easier.
Also fix one SonarQube-reported bug and remove a useless condition.
---
---
-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/mast …

RELATED: RAIL-4336 avoid some injectIntl calls

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/presentationComponents/ThemedLoadingEqualizer.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/index.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentNoWidgets.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/Attachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/AttachmentsSelectionDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/FormatOptionsDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/ScheduledMailDialogRenderer/Attachments/ScheduleDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/ScheduledEmails.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/lockedStatus/LockedStatusIndicator.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/KpiAlertDialog/KpiAlertDialogDateRange.tsx

This makes the component tree smaller and avoids connecting to
the themeIsLoading context none of the components cares about.
JIRA: RAIL-4336
---
--- …

RELATED: RAIL-4336 Use useTheme instead of withTheme

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/features/hub.ts
libs/sdk-backend-tiger/src/backend/features/index.ts
libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
libs/sdk-backend-tiger/src/backend/features/test/static.test.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

JIRA: NAS-3978, NAS-3989
---
---
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-b …

NAS-3989 - WS earlyAccess string is not evaluated

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartTooltips.ts
libs/sdk-ui-charts/styles/scss/tooltip.scss
libs/sdk-ui-geo/src/core/geoChart/geoChartTooltip.ts
libs/sdk-ui-geo/src/core/geoChart/tests/geoChartTooltip.test.ts
libs/sdk-ui-geo/styles/scss/tooltip.scss

- Remove vague named CSS classes as they are not used and could conflict with customers CSS styles
- Prefix these vague named CSS classes that are used
JIRA: RAIL-4339
---
--- …

BUGFIX: RAIL-4339 Remove/prefix vague css classnames

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemContent.tsx
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetSelection.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiAlerts/DashboardItemWithKpiAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/kpi/DefaultDashboardKpi/KpiExecutor.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardInsightWidget.tsx

* Make KPIs selectable as well
* Extract selection utils into a hook
* Deselect widget on outside click
---
--- …

RELATED: RAIL-4158 fix widget selection

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/insight/sanitization.ts
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/impl/tableFacade.ts
libs/sdk-ui-pivot/src/impl/utils.ts

Subtotals are no longer added by pivot table aggregation menu when sorted by other than the first attribute.
After clicking on a item in menu a check is first rhow the table is sorted. If the subtotals would be incompatible they are simply not added.
Side effect: Nothing happens except a reload on aggregation menu click in these cases.
JIRA: NAS-3939
---
---
-   [ ] commit messages adhere …

BUGFIX: NAS-3939 Subtotals are no longer added by pivot table aggregation menu when sorted

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/afm/DimensionHeaderConverter.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/drillToDashboardHandler.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/drillDownUtil.ts

* Partially revert 040e318ad1aa4fa24a8db43b063a735b6281c6d7
* Partially revert afa98bc98a06904d4f3e31e7ae5ad1131d9eb5f1
* Revert changes to the api-client-tiger
JIRA: CAL-519
---
--- …

RELATED: CAL-519 Partially revert changes related to null attribute headers

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts

- export selectors needed for postMessageAPI
- add new actions to set render mode without handing over the param.
JIRA: RAIL-4342
---
--- …

RELATED: RAIL-4342 Ui actions and meta selectors

---

common/config/rush/pnpm-lock.yaml
libs/api-client-bear/package.json
libs/sdk-ui/package.json

Incorporate few security advisories in the dependencies.
- fix async security advisory: https://github.com/advisories/GHSA-fwr7-v2mv-hh25
- also fix https://github.com/advisories/GHSA-pfrx-2q88-qq97 at least in the dependencies that we can affect (we cannot get rid of it completely, because it's also dependency of heroku)
JIRA: RAIL-4047
---
--- …

RELATED: RAIL-4047 fix security advisories

---

libs/sdk-backend-tiger/src/backend/tigerSpecificFunctions.ts

Without proper error conversion, auth call is not able to call not authenticated handler.
JIRA: TNT-904
---
--- …

Convert api error when scanning data source
