gooddata/gooddata-ui-sdk

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/addVisualizationToSwitcherWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/changeInsightWidgetInsightHandler.ts
libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts

risk: low
JIRA: LX-518
---
> [!IMPORTANT]
---
```
```
```
```

FEATURE: LX-518 Handle vis. switcher resize

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts

risk: low
JIRA: LX-518
---
> [!IMPORTANT]
---
```
```
```
```

fix: proper min height for vis. switcher

---

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsManagementDialog.ts

JIRA: F1-737
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: reset schedule edit after delete

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx

Enable editing of alerts and scheduled exports for users who are either the creator or have the necessary permissions
to manage workspace alerts and scheduled exports.
risk: low
JIRA: F1-710
---
> [!IMPORTANT]
---
```
```
```
```

fix: editing alerts and scheduled exports

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParameters.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditorParametersSections/IdentifierParametersSection.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/InsightIdParameterDetail.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/ParameterDetails/WidgetIdParameterDetail.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDrillConfigItem.tsx

---
> [!IMPORTANT]
---
```
```
```
```

fix: change getting of selected widget ref to support switcher

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/types.ts
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/InsightDraggingComponent.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutUtils.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuContainer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DefaultDashboardInsightMenuTitle.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightEditMenuItems.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DashboardWidgetInsightGuard.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidgetHeader.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useAlertingAndScheduling.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useEditableInsightMenu.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/alerts.ts

Visualizations created on Parent workspace and used only on Child workspace dashboards cause issues when deleted from Parent [Panther]
JIRA: F1-781
---
> [!IMPORTANT]
---
```
```
```
```

feat: dashboards cause issues when parent visualisation deleted

---

libs/sdk-backend-tiger/src/convertors/shared/layoutConverter.ts

JIRA: LX-549
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: extend layout converter to support switcher

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts

JIRA: F1-750
---
> [!IMPORTANT]
---
```
```
```
```

fix: alert decrease is not calculated correctly

---

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/AddVisualizationSwitcherWidgetButton.tsx

risk: low
JIRA: LX-562
---
> [!IMPORTANT]
---
```
```
```
```

fix: vis. switcher tooltip zindex

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/utils/constants.ts
libs/sdk-ui-kit/styles/scss/dialogList.scss

JIRA: F1-782
---
> [!IMPORTANT]
---
```
```
```
```

fix: design QA - automations / part 1

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dataFilter/index.ts
libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/dataFilter/index.ts
libs/sdk-model/src/index.ts
libs/sdk-model/src/objRef/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx

---
> [!IMPORTANT]
---
```
```
```
```

WDF SPI, Saved filter views bugfixes

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/userInteraction.ts
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/Toolbar.tsx
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/ToolbarTop.tsx
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/configuration/VisualizationsPage.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx

risk: low
JIRA: LX-491
---
> [!IMPORTANT]
---
```
```
```
```

feat: extend vis. switcher telemetry

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/userInteraction.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
libs/sdk-ui-dashboard/styles/scss/filterBar.scss

JIRA: LX-429
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: emit user interaction for opened filter views panel, add accessibility button highlight to filter views button

---

libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherToolbar.scss

JIRA: LX-566
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: apply theme on new components

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx

risk: low
JIRA: LX-565
---
> [!IMPORTANT]
---
```
```
```
```

fix: handle async section header description

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts

JIRA: F1-786
---
> [!IMPORTANT]
---
```
```
```
```

fix: s/a dialog should respect timezone set by user

---

common/changes/@gooddata/sdk-ui-all/nen-lx-569_2024-10-08-13-08.json
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts

---
> [!IMPORTANT]
---
```
```
```
```

feat: set vis. switcher FF to true

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts

The filters were removed from filter context when filter view is applied but reference to the cross-filtering attributes remained in the app state, causing the inability to apply said cross-filters again until the browser tab was reloaded.
JIRA: LX-516
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: reset cross filter views properly when filter view is applied

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/events/userInteraction.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardUserInteraction.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx

JIRA: LX-429
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: change filter view user interaction type

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/constants.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
libs/sdk-ui-dashboard/styles/scss/alerting.scss
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss

JIRA: F1-808
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: allow multiple recipients in alert dialog

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts

- Alert on "Is a total" metric get error email
- No metric found on geo chart alert setting
JIRA: F1-805, F1-804
---
> [!IMPORTANT]
---
```
```
```
```

fix: geo chart, arithmetic metric repairs

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeDescription.tsx
libs/sdk-ui-kit/styles/scss/recurrenceForm.scss

JIRA: F1-786
---
> [!IMPORTANT]
---
```
```
```
```

fix: timezone recurrence form update

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dataFilter/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts

JIRA: LX-462
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: support setting of multiple values for data workspace filter

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss

JIRA: F1-806
---
> [!IMPORTANT]
---
```
```
```
```

fix: validate recipients e-mail for smtps

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/common/intersectionUtils.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/tests/__snapshots__/addAttributeFilterHandler.test.ts.snap
libs/sdk-ui-dashboard/src/model/commands/filters.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextReducers.ts
libs/sdk-ui-dashboard/src/model/store/index.ts

---
> [!IMPORTANT]
---
```
```
```
```

use attribute alias in cross filtering titles and fix repeater column names

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

JIRA: F1-757
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: add support for enableDefaultSmtp FF

---

examples/sdk-interactive-examples/examples/example-dashboard/src/example/Example.tsx
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadNotificationChannelsCount.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadWorkspaceAutomationsCount.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadFilterViews.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/refreshAutomationsHandlers.ts
libs/sdk-ui-dashboard/src/model/react/useInitializeDashboardStore.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useAlertingAndScheduling.ts

Fix readonly mode and use it in the example.
risk: low
JIRA: F1-812
---
> [!IMPORTANT]
---
```
```
```
```

fix: dashboard interactive example

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/automations/index.ts
libs/sdk-model/src/entitlements/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts

JIRA: F1-805
---
> [!IMPORTANT]
---
```
```
```
```

fix: alert metric with dependencies repair

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts

JIRA: LX-586
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: introduce feature flag for dashboard nested layout feature

---

examples/playground/.env.template
examples/playground/README.md
examples/playground/src/App.tsx
examples/playground/src/index.tsx
examples/playground/src/playground/Playground.tsx
examples/playground/vite.config.ts

- Make vite plugin for certificates optional
- Make it easier to ignore changes in the playground
- Include internal css for semantic search package
---
> [!IMPORTANT]
---
```
```
```
```

chore(playground): Minor improvements to the playground

---

libs/sdk-ui-dashboard/src/_staging/automation/index.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts

JIRA: F1-817
---
> [!IMPORTANT]
---
```
```
```
```

fix: S/A user has email but always validate no email

---

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts

JIRA: F1-805
---
> [!IMPORTANT]
---
```
```
```
```

fix: arithmetic metric repairs

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts

risk: low
JIRA: STL-851
---
> [!IMPORTANT]
---
```
```
```
```

feat: lookup labels in map when given instead of fetching

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/resetDashboardHandler.ts

risk: low
JIRA: STL-851
---
> [!IMPORTANT]
---
```
```
```
```

feat: lookup labels in map on dashboard reset

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx

JIRA: LX-586
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: revert devel text

---

common/config/rush/command-line.json
common/scripts/install-certs.js
common/scripts/uninstall-certs.js

Added a way to uninstall certs.
---
> [!IMPORTANT]
---
```
```
```
```

chore: dev certificates management

---

libs/sdk-model/src/objRef/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertAttributeSelecxt.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useAttributeValuesFromExecResults.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/styles/scss/alerting.scss

JIRA: F1-778
---
> [!IMPORTANT]
---
```
```
```
```

feat: alerts per attribute, search + repairs

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertAttributeSelecxt.tsx
libs/sdk-ui-dashboard/styles/scss/alerting.scss

JIRA: F1-778
---
> [!IMPORTANT]
---
```
```
```
```

feat: alerts per attribute, design update

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts

JIRA: F1-778
---
> [!IMPORTANT]
---
```
```
```
```

feat: alerts per attribute, add all visualisations

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useAlertingAndScheduling.ts

JIRA: F1-803
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: properly hide alerting based on number of destinations

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts

JIRA: QA-23359
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

fix: stablize integrated tests

---

libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/AddSingleWorkspaceSelect.tsx
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/AsyncSelectComponents.tsx
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/backend/loadWorkspaceOptionsPromise.ts

JIRA: F1-837
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: paginate workspaces load in permissions

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts

---
> [!IMPORTANT]
---
```
```
```
```

enable latest FFs by default

---

libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/repeater.spec.ts

JIRA: QA-23423
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

FIX: QA-23423 Update column name repeater

---

libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/AddSingleWorkspaceSelect.tsx

JIRA: F1-845
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: do not open dropdown in disabled mode

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils.ts

JIRA: F1-853
---
> [!IMPORTANT]
---
```
```
```
```

fix: didn't remove filter when updating alert to All

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingManagementDialog/components/Alert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsListItem.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx

Threshold value on alert dialog is not applied number seperator setting
JIRA: F1-858
---
> [!IMPORTANT]
---
```
```
```
```

fix: Threshold value on alert dialog

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-charts/src/charts/repeater/internal/RepeaterChart.tsx
libs/sdk-ui-charts/src/charts/repeater/internal/dataViewToRepeaterData.ts
libs/sdk-ui-charts/src/charts/repeater/internal/repeaterAgGridDataSource.tsx

Correct number formatting in repeater.
risk: low
JIRA: F1-855
---
> [!IMPORTANT]
---
```
```
```
```

fix: number separators in repeater

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts

Propagate separators in PluggableRepeater to its chart config.
risk: low
JIRA: F1-855
---
> [!IMPORTANT]
---
```
```
```
```

fix: propagate separators in PluggableRepeater

---

libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/organization/users/index.ts
libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/organization/users.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/UserEditDialog.tsx
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/dialogHooks.ts
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/index.ts
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/types.ts

- introduce enableNewUserCreationFlow feature flag
- add organization user call for finding existing email address
- propagate selected tab to user edit dialog
JIRA: F1-876
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: new user creation flow additions

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/dashboard/baseWidget.ts
libs/sdk-model/src/dashboard/layout.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/index.ts
libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsData.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsFilters.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts
libs/sdk-ui-dashboard/src/model/react/useWidgetFilters.ts
libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts
libs/sdk-ui-dashboard/src/model/types/layoutTypes.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardSidebar/CreationPanel.tsx
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/types.ts
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/DraggableVisualizationSwitcherCreatePanelItem.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillConfigPanel/DrillToUrl/CustomUrlEditor.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts

---
> [!IMPORTANT]
---
```
```
```
```

feat: support for nested layout in types

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/items.ts

risk: low
JIRA: F1-889
---
> [!IMPORTANT]
---
```
```
```
```

fix: alert didn't work with Location attribute in GEO

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/automations/index.ts
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useAlertValidation.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/convertors.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/granularity.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/items.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
libs/sdk-ui-dashboard/styles/scss/alerting.scss

JIRA: F1-885
---
> [!IMPORTANT]
---
```
```
```
```

feat: support comparative alerts for others vis

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts

Enable enableAlertAttributes FF by default.
risk: low
JIRA: F1-894
---
> [!IMPORTANT]
---
```
```
```
```

feat: enable alert per attribute by default

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/genAI/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/genAI/chat.ts
libs/sdk-model/src/genAI/semanticSearch.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx

Support filters when building visualizations
---
```
```
```
```

RELATED: F1-645 ai chat filters support

---

libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/src/components/messages/AgentIcon.tsx
libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json

Added aria-labels to few elements
---
```
```
```
```

RELATED: F1-645 accessibility labels

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/auth-json-api/api.ts
libs/api-client-tiger/src/generated/auth-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/items.ts

JIRA: F1-906, F1-908
---
> [!IMPORTANT]
---
```
```
```
```

fix: comparative operators if no filter defined, tiger client generate

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/items.ts

risk: low
JIRA: F1-912
---
> [!IMPORTANT]
---
```
```
```
```

fix: type of comparison on alert dialog should not be fixed

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

This allows us to roll the new naming out gradually.
JIRA: CQ-893
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

chore: add enableFlexConnectNaming FF

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/items.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts

risk: low
JIRA: F1-911
---
> [!IMPORTANT]
---
```
```
```
```

fix: repairs related to operator and comparison

---

libs/sdk-ui-dashboard/src/model/store/executionResults/executionResultsSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillModalRawExportOptions.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx

JIRA: LX-629
---
> [!IMPORTANT]
---
```
```
```
```

feat: disable XLSX/CSV when partial result

---

libs/sdk-ui-dashboard/src/presentation/widget/warningPartialResult/InsightWidgetWarningPartialResult.tsx

JIRA: LX-629
---
> [!IMPORTANT]
---
```
```
```
```

fix: pass correct value to localised text

---

common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json

Update browserslist to "^4.24.2"
risk: low
TRIVIAL
---
> [!IMPORTANT]
---
```
```
```
```

fix: caniuse-lite

---

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/ExportDefinitionsConverter.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-kit/src/Timepicker/utils/timeUtilities.ts

risk: low
JIRA: F1-930, F1-922
---
> [!IMPORTANT]
---
```
```
```
```

fix: schedule list dashboard / widget name, starts field

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/genAI/chat.ts
libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx
libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts

- Make localStorage access conditional to prevent issues in NodeJS.
- Add support for null values in attribute filters.
---
> [!IMPORTANT]
---
```
```
```
```

RELATED: F1-645 GenAI Chat minor fixes

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/highcharts/ChartTransformation.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsBuilder.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/warningPartialResult/InsightWidgetWarningPartialResult.tsx
libs/sdk-ui-dashboard/src/presentation/widget/warningPartialResult/MobileWarningPartialResultOverlay.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss

JIRA: LX-659
---
> [!IMPORTANT]
---
```
```
```
```

feat: allow partial results on charts

---

libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/organization/notificationChannels/index.ts
libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts

risk: low
JIRA: F1-938
---
> [!IMPORTANT]
---
```
```
```
```

feat: destination testing ui + template

---

libs/api-client-tiger/src/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/genAI/chat.ts
libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx
libs/sdk-ui-gen-ai/src/model.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/converters/interactionsToMessages.ts
libs/sdk-ui-gen-ai/styles/scss/messages.scss

Apply user feedback loaded from server
---
```
```
```
```

RELATED: F1-645 apply user feedback from server

---

.github/workflows/gate.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: remove sdk UT from gate

---

libs/api-client-tiger/scripts/build.sh
libs/sdk-backend-tiger/scripts/build.sh
libs/sdk-ui-dashboard/scripts/build.sh
tools/app-toolkit/scripts/build.sh
tools/catalog-export/scripts/build.sh
tools/mock-handling/scripts/build.sh
tools/plugin-toolkit/scripts/build.sh

JIRA: STL-931
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

fix: make build script compatible with MacOs

---

libs/sdk-ui-dashboard/src/_staging/layout/test/sizing.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/resizeWidthHandler.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/utils/tests/sizing.test.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/tests/sizing.test.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/BigChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/baseChart/BaseChartDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/constants.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PivotTableDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/repeater/RepeaterDescriptor.ts

---
> [!IMPORTANT]
---
```
```
```
```

feat: change minimal width to 2

---

.github/actions/rush/set-up-rush/action.yml
libs/api-client-bear/src/__version.ts
libs/api-client-tiger/.gitignore
libs/api-client-tiger/scripts/build.sh
libs/api-client-tiger/src/__version.ts
libs/sdk-backend-bear/src/__version.ts
libs/sdk-backend-tiger/.gitignore
libs/sdk-backend-tiger/scripts/build.sh
libs/sdk-backend-tiger/src/__version.ts
libs/sdk-ui-dashboard/.gitignore
libs/sdk-ui-dashboard/scripts/build.sh
libs/sdk-ui-dashboard/src/__version.ts
libs/sdk-ui-gen-ai/.gitignore
tools/app-toolkit/.gitignore
tools/app-toolkit/scripts/build.sh
tools/app-toolkit/src/__version.ts
tools/catalog-export/scripts/build.sh
tools/catalog-export/src/__version.ts
tools/mock-handling/.gitignore
tools/mock-handling/scripts/build.sh
tools/mock-handling/src/__version.ts
tools/plugin-toolkit/.gitignore
tools/plugin-toolkit/scripts/build.sh
tools/plugin-toolkit/src/__version.ts

it's breaking dev use-cases
---
> [!IMPORTANT]
---
```
```
```
```

feat: revert build changes

---

libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/organization/notificationChannels/index.ts
libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts

Added possibility to test existing destination with changes (must be implemented on server)
risk: low
JIRA: F1-938
---
> [!IMPORTANT]
---
```
```
```
```

feat: destination testing ui

---

libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatOverlay.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatWrapper.tsx
libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/styles/scss/main.scss
libs/sdk-ui-gen-ai/styles/scss/messages.scss

- Styling fixes
- Autofocus on chat window open
- Make chat respect OverlayController
---
> [!IMPORTANT]
---
```
```
```
```

RELATED: F1-645 GenAI chat fixes

---

.github/workflows/rw-doc-storybook-deploy.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: deploy storybook use build cache

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/styles/scss/messages.scss

- make chart legend responsive in chat UI
---
> [!IMPORTANT]
---
```
```
```
```

RELATED: F1-645 Chart legend fix

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/dataSources/index.ts

It was removed everywhere else already, this was missed.
JIRA: CQ-893
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

chore: remove FLIGHTRPC from model type

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx

JIRA: LX-668
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: limit container min width by its children

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/warningPartialResult/InsightWidgetWarningPartialResult.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightWarning.tsx

JIRA: LX-659, LX-667
---
> [!IMPORTANT]
---
```
```
```
```

fix: export raw filters, warning overlay, percentage

---

.github/workflows/rw-rush-build-e2e-tests.yml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: build e2e tests with --to option

---

.github/workflows/rw-bump-version.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: fix bump version and npm alpha publish

---

libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx

Adjust z-index to be below chart tooltips
---
```
```
```
```

RELATED: F1-645 chat window z-index

---

.github/workflows/check.yaml
.github/workflows/rw-rush-build-basic-checks.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: detect changes in basic check as compare to base branch

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/genAI/chat.ts
libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx

Use AI-generated metric title from server when provided
---
```
```
```
```

RELATED: F1-645 metric title

---

libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts

risk: low
JIRA: F1-945
---
> [!IMPORTANT]
---
```
```
```
```

feat: scheduled exports on dashboards caused troubles loading dashboards

---

libs/sdk-ui-dashboard/styles/scss/dashboard.scss

JIRA: LX-667
---
> [!IMPORTANT]
---
```
```
```
```

fix: style issues

---

.github/actions/rush/set-up-rush/action.yml
.github/actions/rush/warm-up-rush/action.yml

risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: backport rush setup actions to rel branch

---

.github/actions/node/check-node-version/action.yml
.github/actions/node/set-up-node/action.yml
.github/actions/node/warm-up-node/action.yml
.github/actions/rush/set-up-rush/action.yml
.github/actions/rush/warm-up-rush/action.yml

---
> [!IMPORTANT]
---
```
```
```
```

chore: back port missing action release

---

.github/workflows/rw-bump-version.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: fix rw-bump-version flow

---

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/addLayoutSectionHandler.ts

JIRA: LX-674
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: use correct sections in nested layout

---

.github/pull_request_template.md
.github/workflows/pull-request-comment.yaml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: invaild workflow and unify comments

---

.github/workflows/pull-request-comment.yaml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: add missing runner and permissions for comment

---

.github/workflows/rw-bump-version-major.yml
.github/workflows/rw-doc-release-apidocs.yml
.github/workflows/rw-git-backmerge.yml
common/config/rush/command-line.json
libs/sdk-ui-tests-e2e/package.json

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: migrate WF related to release to use cache

---

.github/workflows/pull-request-comment.yaml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: remove forgotten if for comment job

---

.github/workflows/pull-request-comment.yaml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: remove guard if statement

---

libs/sdk-ui-tests-e2e/package.json

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: simple change

---

.github/workflows/pull-request-comment.yaml

risk: low
JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: use correct comment if statement

---

.github/workflows/pull-request-comment.yaml
.github/workflows/rw-rush-build-e2e-tests-record.yml
.github/workflows/rw-rush-build-e2e-tests.yml
libs/sdk-ui-tests-e2e/cypress.config.ts
libs/sdk-ui-tests-e2e/cypress/plugins/removePassingTestVideos.ts

JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

fix: e2e tests from pr improvements

---

.github/pull_request_template.md
.github/workflows/pull-request-comment.yaml
.github/workflows/rw-rush-build-e2e-tests-integrated.yml
common/scripts/ci/run_cypress_integrated_tests.sh
common/scripts/ci/run_cypress_isolated_tests.sh
common/scripts/ci/run_cypress_recording.sh
libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml

JIRA: STL-935
---
> [!IMPORTANT]
---
```
```
```
```

feat: integrated tests from pull-request comment

---

.github/actions/rush/set-up-rush/action.yml
.github/workflows/gate.yaml
.github/workflows/rw-rush-build-e2e-tests.yml
.github/workflows/rw-rush-detect-changes.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: opt e2e in gate

---

libs/sdk-ui-charts/src/highcharts/adapter/Chart.tsx

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

fix: remove highcharts reexport

---

libs/sdk-ui-geo/api/sdk-ui-geo.api.md
libs/sdk-ui-geo/src/GeoChart.ts

risk: low
JIRA: STL-960
---
> [!IMPORTANT]
---
```
```
```
```

fix: import type from mapbox gl

---

libs/sdk-ui-kit/src/Bubble/Bubble.tsx

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: test changes gate

---

.github/workflows/rw-rush-build-e2e-tests-integrated.yml
.github/workflows/rw-rush-build-e2e-tests-record.yml

risk: low
JIRA: STL-936
---
> [!IMPORTANT]
---
```
```
```
```

fix: adjust stored artifacts with e2e jobs

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
libs/sdk-ui-kit/src/EditableLabel/index.ts
libs/sdk-ui-kit/src/EditableLabel/typings.ts

- use ResizeObserver to properly measure container size during initial render
- rewrite whole component to functional
JIRA: LX-682
risk: high
---
> [!IMPORTANT]
---
```
```
```
```

fix: make EditableLabel autofocus more stable

---

.github/workflows/doc-strorybook-deploy.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

fix: adjust cron for storybook deploy

---

.github/workflows/test-backstop.yml

risk: low
JIRA: STL-962
---
> [!IMPORTANT]
---
```
```
```
```

feat: adjust messaging

---

.github/workflows/rw-publish-prerelease.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: repository-dispatch gdc-ui when alpha is published

---

libs/sdk-backend-tiger/src/backend/workspace/dataFilters/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/dataFilter/index.ts

JIRA: LX-616
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: when updating data filter delete only native workspace setting

---

common/scripts/ci/run_cypress_integrated_tests_e2e_checklist.sh

risk: nonprod
JIRA: QA-23737
---
> [!IMPORTANT]
---
```
```
```
```

QA-23737: temporarily adding script to run e2e cheklist

---

docs/content/en/latest/references/visual_components/geo_pushpin_chart.md

JIRA: DP-2566
---
> [!IMPORTANT]
---
```
```
```
```

TRIVIAL: geo pushpin token doc clarification

---

common/scripts/ci/run_cypress_isolated_tests.sh
libs/sdk-ui-tests-e2e/README.md
libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml
libs/sdk-ui-tests-e2e/scripts/lib/cypress.js

risk: low
JIRA: STL-981
---
> [!IMPORTANT]
---
```
```
```
```

feat: remove currents from the codebase

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/Hotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/WidgetDropZoneColumn.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/rowEndHotspotHelper.ts
libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss

JIRA: LX-597
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: fill rest of last row by big drop zone

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/Hotspot.tsx
libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss

JIRA: LX-690
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

feat: dropzone restyling to distinguish from resizer

---

.github/workflows/rw-publish-prerelease.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: add version to public-sdk-update event

---

.github/workflows/rw-publish-prerelease.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: fix public-sdk-update JSON payload

---

.github/workflows/checklist-cypress-ui-test.yaml
.github/workflows/checklist-integrated-staging.yaml

JIRA: QA-23600
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

QA-23600: add a new workflow for e2e checklist

---

common/config/rush/common-versions.json
common/config/rush/repo-state.json
tools/app-toolkit/.babelrc-js
tools/plugin-toolkit/.babelrc-js

risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: use fixed target to avoid outdated browserlist issues

---

.github/workflows/rw-doc-release-apidocs.yml

risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: fix path to setup rush action

---

common/scripts/build-docs.js

risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: fix path to apidocs

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/genAI/chat.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-gen-ai/src/components/Messages.tsx
libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx
libs/sdk-ui-gen-ai/src/components/messages/MessageContents.tsx
libs/sdk-ui-gen-ai/src/components/messages/UserMessage.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/useExecution.tsx
libs/sdk-ui-gen-ai/styles/scss/messages.scss

Chat now supports suggestions for the next steps when building the visualization
---
> [!IMPORTANT]
---
```
```
```
```

RELATED: GDAI-11 suggestions in chat

---

.github/workflows/checklist-cypress-ui-test.yaml
.github/workflows/checklist-integrated-staging.yaml
.github/workflows/rw-rush-build-e2e-tests-integrated.yml
common/scripts/ci/run_cypress_integrated_tests.sh

JIRA: QA-23600
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

QA-23600: input variables for e2e checklist

---

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md

risk: low
JIRA: STL-1003
---
> [!IMPORTANT]
---
```
```
```
```

fix: switch to absolute dates in compatibility docs

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/HoveredWidgetContext.tsx
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/index.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/DragLayerPreview/HeightResizerDragPreview.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/DragLayerPreview/WidthResizerDragPreview.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/HeightResizer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/HeightResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/HoverDetector.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/types.ts
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemContent.tsx
libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
libs/sdk-ui-dashboard/styles/scss/resizing.scss

---
> [!IMPORTANT]
---
```
```
```
```

feat: show resizers + new style

---

.github/workflows/push-e2e-integrated-tests.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: add post merge notification

---

libs/sdk-backend-tiger/src/convertors/fromBackend/NotificationChannelsConvertor.ts
libs/sdk-backend-tiger/src/convertors/tests/NotificationChannelsConvertor.test.ts
libs/sdk-backend-tiger/src/convertors/toBackend/NotificationChannelsConvertor.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/notificationChannels/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsData.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/notificationChannels/notificationChannelsSelectors.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/notificationsPanel/@staging/OrganizationContext/useFetchOrganization.ts
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/NotificationsPanel.tsx
libs/sdk-ui-ext/src/notificationsPanel/data/NotificationsContext.tsx
libs/sdk-ui-ext/src/notificationsPanel/data/useFetchNotifications.ts
libs/sdk-ui-ext/src/notificationsPanel/data/useNotifications.tsx

All interval for refreshing notifications.
Add support for in-platform notifications in webhook and smtp channels. Filter out in-platform notifications in scheduled exports.
risk: low
JIRA: F1-976
---
> [!IMPORTANT]
---
```
```
```
```

fix: notification panel

---

.github/workflows/push-e2e-integrated-tests.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: skip immediately post merge on not related commits

---

libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: LX-696
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: prevent page breaks to split widget

---

libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useAlertingAndScheduling.ts

Use proper selector for destinations count
in alerting.
risk: low
JIRA: F1-976
---
> [!IMPORTANT]
---
```
```
```
```

fix: notification channels

---

.github/workflows/checklist-run-boiler-app.yaml

JIRA: QA-23787
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

QA-23787: adding a new wf for boiler app test

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/DragLayerPreview/WidthResizerDragPreview.tsx
libs/sdk-ui-dashboard/styles/scss/resizing.scss

JIRA: LX-599
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: apply padding only to width resizer preview

---

.github/workflows/checklist-cypress-ui-test.yaml
.github/workflows/checklist-integrated-staging.yaml

JIRA: QA-23600
risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

QA-23600: adding slack notification after running

---

libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/facade/interfaces.ts
libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/facade/items.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultFlexibleDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/ResizeOverlay.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/rowEndHotspotHelper.ts
libs/sdk-ui-dashboard/styles/scss/resizing.scss

---
> [!IMPORTANT]
---
```
```
```
```

fix: flexible layout fixes - dropzone, height resizer, resize overlay

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/useEmptyContentHandlers.ts

JIRA: LX-711
risk: low
---
> [!IMPORTANT]
---
```
```
```
```

fix: proper typeguard in drop handler

---

.github/pull_request_template.md
.github/workflows/pull-request-comment.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
```
```
```

chore: add filters to commands

---

libs/sdk-backend-tiger/src/backend/workspace/automations/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-ext/api/sdk-ui-ext.api.md
libs/sdk-ui-ext/src/internal/translations/en-US.json
libs/sdk-ui-ext/src/notificationsPanel/Notification/AlertNotification.tsx
libs/sdk-ui-ext/src/notificationsPanel/NotificationFiltersDetail/NotificationFiltersDetail.tsx
libs/sdk-ui-ext/src/notificationsPanel/NotificationTriggersDetail/NotificationTriggersDetail.tsx
libs/sdk-ui-ext/src/notificationsPanel/NotificationsList/DefaultNotificationsList.scss
libs/sdk-ui-ext/src/notificationsPanel/NotificationsList/DefaultNotificationsList.tsx
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanel.scss
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanelHeader.scss
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/NotificationsPanel.tsx
libs/sdk-ui-ext/src/notificationsPanel/components/VirtualList.scss
libs/sdk-ui-ext/src/notificationsPanel/components/VirtualList.tsx
libs/sdk-ui-ext/src/notificationsPanel/data/useFetchNotifications.ts
libs/sdk-ui-ext/src/notificationsPanel/data/useNotificationFiltersDetail.tsx
libs/sdk-ui-ext/src/notificationsPanel/data/useNotifications.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiButton/UiButton.tsx
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/HeaderHelp.tsx
libs/sdk-ui-kit/src/Header/HeaderMenu.tsx
libs/sdk-ui-kit/src/Header/typings.ts
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

- Show notification panel in mobile view
- Comment out filtering details for now
- Close details panel when opening another one
risk: low
JIRA: F1-990
---
> [!IMPORTANT]
---
```
``` …

fix: show notification panel on mobile

---

.github/workflows/checklist-cypress-ui-test.yaml
.github/workflows/checklist-integrated-staging.yaml
.github/workflows/checklist-run-boiler-app.yaml
common/scripts/ci/run_boiler_app_integration_tests_with_live_backend.sh

JIRA: QA-23787
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

QA-23787: moving boiler app test to gh action

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json

risk: low
JIRA: LX-714
---
> [!IMPORTANT]
---
```
``` …

fix: remove translte: false from scheduling/alerting strings

---

.github/workflows/checklist-integrated-staging.yaml

JIRA: QA-23787
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

QA-23787: fix notification branch for sdk checklist

---

.github/workflows/checklist-cypress-ui-test.yaml

JIRA: QA-23600
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

ci: fix artifacts path

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultFlexibleDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/widget/dashboardLayout/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/dashboardLayout/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardNestedLayoutWidget/EditableDashboardNestedLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add test classes

---

libs/sdk-ui-charts/src/charts/headline/internal/utils/HeadlineTransformationUtils.ts

JIRA: F1-984
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: make headline show 0 value

---

libs/sdk-backend-tiger/src/backend/organization/notificationChannels.ts

risk: low
JIRA: F1-938
---
> [!IMPORTANT]
---
```
``` …

feat: update data to new client definition

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: make classes work in root layout too

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/scripts/generate.js
libs/api-client-tiger/src/gd-tiger-model/typeGuards.ts
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts

Update client definition
risk: low
JIRA: F1-985
---
> [!IMPORTANT]
---
```
```
- …

fix: notification channel did not store destination_type

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dropdown/DropdownButton.tsx

risk: low
JIRA: F1-966
---
> [!IMPORTANT]
---
```
``` …

fix: add aria label to dropdown button

---

libs/sdk-ui-web-components/nginx.conf

risk: low
JIRA: STL-1010
---
> [!IMPORTANT]
---
```
``` …

fix: set absolute redirects: off

---

libs/sdk-ui-dashboard/src/index.ts

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: test change in SDK

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx

Add description on button
risk: low
JIRA: F1-988
---
> [!IMPORTANT]
---
```
```
- …

feat: display tooltip in drilled into visualization

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/automation-json-api/api.ts
libs/api-client-tiger/src/generated/automation-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts

risk: low
JIRA: F1-987
---
> [!IMPORTANT]
---
```
``` …

feat: the redirect custom URL should not include "?automationId="

---

libs/sdk-ui-tests/backstop/backstop.config.js

see if it would help with ad-hoc termination
of the capture process
risk: low
JIRA: STL-1011
---
> [!IMPORTANT]
---
```
```
-   `--isolated` The command …

fix: lower the async capture limit

---

libs/sdk-ui-dashboard/src/_staging/layout/coordinates.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutEditSectionHeader.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableDashboardLayoutSectionRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/DragLayerPreview/WidthResizerDragPreview.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DefaultDashboardWidget.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss
libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
libs/sdk-ui-dashboard/styles/scss/layout.scss
libs/sdk-ui-dashboard/styles/scss/resizing.scss

And tune paddings
JIRA: LX-600
risk: low
---
> [!IMPORTANT]
---
```
```
- …

feat: remove new section hotspots in nested containers

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DefaultDashboardContent/DefaultDashboardMainContent.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardMainContent.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/styles/scss/layout.scss

JIRA: LX-718
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: allow section description input to be sized by its content

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx

risk: low
JIRA: F1-1027
---
> [!IMPORTANT]
---
```
``` …

fix: drilled-in visualization is showing the wrong tooltip

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/Hotspot.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

test: add test classes to the dropzones

---

libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/automations/index.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/styles/scss/variables.scss

risk: low
JIRA: F1-1030
---
> [!IMPORTANT]
---
```
``` …

feat: external recipients in dashboards support

---

.github/workflows/rw-rush-build-e2e-tests-backstop.yml
libs/sdk-ui-tests/backstop/backstop.config.js

risk: low
JIRA: STL-1011
---
> [!IMPORTANT]
---
```
``` …

fix: use larger runner to avoid backstop failures

---

docs/content/en/latest/references/filters/date_filter.md

risk: low
JIRA: LX-3053
---
> [!IMPORTANT]
---
```
``` …

feat: customize date filter config docs

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx

risk: low
JIRA: F1-1039
---
> [!IMPORTANT]
---
```
``` …

fix: miss tooltip for internal user

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertAttributeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useAttributeValuesFromExecResults.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useThresholdValue.ts
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Form/Input.tsx
libs/sdk-ui-kit/src/Form/tests/Input.test.tsx

Miss tooltip and multiline user in select
Pre-fill alert threshold with current value
JIRA: F1-1039, F1-1041
---
> [!IMPORTANT]
---
```
```
- …

bugfix, feedback implemention

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerHeightSanitization.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/resizeHeightHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/resizeWidthHandler.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/utils/sizing.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/HeightResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/utils/sizing.ts
libs/sdk-ui-dashboard/src/presentation/layout/dragAndDrop/Resize/HeightResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/layout/dragAndDrop/Resize/WidthResizerHotspot.tsx
libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss
libs/sdk-ui-dashboard/styles/scss/layout.scss
libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx

JIRA: LX-681
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: use current screen height when sanitizing container height

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useThresholdValue.ts

risk: low
JIRA: F1-1041
---
> [!IMPORTANT]
---
```
``` …

feat: pre-fill alert threshold with current value

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-ext/src/notificationsPanel/Notification/DefaultNotification.scss
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanelButton.scss
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanelButton.tsx

Design fixes.
Correct logic for setting filters by automationId.
risk: low
JIRA: F1-1024
---
> [!IMPORTANT]
---
```
``` …

fix: notifications

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/HeightResizerHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/dragAndDrop/Resize/HeightResizerHotspot.tsx

JIRA: LX-681
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: rows can't be resized to more than container height

---

libs/sdk-backend-tiger/src/backend/features/index.ts

risk: low
JIRA: ED-238
---
> [!IMPORTANT]
---
```
``` …

fix: inconsistent in Tier affecting Feature enable in FeatureHub

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/utils/users.ts

risk: low
JIRA: F1-1049
---
> [!IMPORTANT]
---
```
``` …

fix: can't search user in workspace by email in list recipients

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts

risk: low
JIRA: F1-1017
---
> [!IMPORTANT]
---
```
``` …

feat: external recipients in home ui support enabled

---

.github/workflows/push-webcomponents-deploy.yml

Older version will stop working at the end of this month
---
> [!IMPORTANT]
---
```
``` …

ci: upgrade upload/download artifact actions to v4

---

docs/content/en/latest/references/filters/date_filter.md

JIRA: LX-739
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: Correct doc example

---

libs/sdk-ui-dashboard/src/model/store/layout/layoutSelectors.ts

JIRA: LX-737
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: filter out custom widgets in nested layouts too

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx

JIRA: F1-1050
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: remove widget highlight on widget click

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutItemViewRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/GridLayoutElement.tsx
libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: LX-696
risk: low
---
> [!IMPORTANT]
---
```
``` …

Flexible layout experimental export fix

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts

risk: low
JIRA: F1-1017
---
> [!IMPORTANT]
---
```
``` …

feat: external recipients default on

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

- Introduce `enableAmplitudeTracker` feature flag.
risk: low
JIRA: LX-747
---
> [!IMPORTANT]
---
```
``` …

feat: introduce Amplitude Tracker feature flag

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx

JIRA: F1-1050
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove highlight on outside click

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetHighlighting.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/RichTextWidget/DefaultDashboardRichTextWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/DefaultDashboardVisualizationSwitcherWidget.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss

- create common highlighting hook
- also add support for rich text widget
JIRA: F1-997
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: introduce visualization switcher highlighting

---

libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: LX-696
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not cut widgets at the end of nested layout during export

---

libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: LX-696
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: revert debug export style

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadNotificationChannelsCount.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/loadWorkspaceAutomationsCount.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/loadLegacyDashboards.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardAutomations.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuItemButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/index.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiSkeleton/UiSkeleton.tsx
libs/sdk-ui-kit/src/List/ListItem.tsx
libs/sdk-ui-kit/src/List/MenuList.tsx
libs/sdk-ui-kit/styles/scss/list.scss

This reverts commit 51c0fa34e116c0949adfc9611006ad4beac263fa.
risk: low
JIRA: F1-1052
---
> [!IMPORTANT]
---
```
``` …

fix: revert automations initialization

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove commented code

---

libs/sdk-ui-ext/src/notificationsPanel/data/useNotifications.tsx

JIRA: F1-1064
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not show other notifications that are not from alerts

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/SettingWidget/StylingSettingWidget/StylingSettingWidget.tsx
libs/sdk-ui-kit/styles/scss/settingWidget.scss

JIRA: LX-772
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat(sdk-ui-kit): add action progress indicator to settings widget

---

libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/__snapshots__/titleCustomizer.test.tsx.snap
libs/sdk-ui-dashboard/src/plugins/customizationApis/tests/titleCustomizer.test.tsx
libs/sdk-ui-dashboard/src/plugins/customizationApis/titleCustomizer.tsx

risk: low
JIRA: F1-1058
---
> [!IMPORTANT]
---
```
``` …

feat: plugin api extension

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useEditAlert.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/convertors.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx

instead of fetching full catalog
risk: low
JIRA: STL-1026
---
> [!IMPORTANT]
---
```
``` …

feat: take measure formats from the execution

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts

JIRA: LX-556
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: extend dashboard component to be addressable by KD navigation

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts

JIRA: LX-556
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: change KeyboardNavigationConfig type definition

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItem.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenu/DashboardInsightMenuItemButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/styles/scss/remove.scss
libs/sdk-ui-ext/src/internal/components/configurationControls/tests/DropdownControl.test.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/WorkspacePickerHomeFooter.tsx
libs/sdk-ui-kit/src/Header/tests/WorkspacePickerHomeFooter.test.tsx
libs/sdk-ui-kit/src/Header/typings.ts
libs/sdk-ui-kit/src/Icon/icons/Home.tsx
libs/sdk-ui-kit/src/Icon/typings.ts
libs/sdk-ui-kit/src/List/ListItem.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-555
---
> [!IMPORTANT]
---
```
``` …

feat: non-text content on dashboards

---

docs/assets/scss/header.scss
docs/config/_default/config.toml
docs/go.mod
docs/go.sum

---
> [!IMPORTANT]
---
```
``` …

DP-3055 CTA button in the docs

---

.github/workflows/push-prerelease.yml
.github/workflows/rw-git-backmerge.yml

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: publish prerelease by default

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: small opt of stringify large object

---

.github/workflows/rw-git-backmerge.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix auto-merge

---

libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Icon/icons/Explore.tsx
libs/sdk-ui-kit/src/Icon/icons/Magic.tsx

risk: low
JIRA: LX-555
---
> [!IMPORTANT]
---
```
``` …

fix: display logo img alt only if exists

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/typings.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-555
---
> [!IMPORTANT]
---
```
``` …

fix: KD Accessibility logo

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx
libs/sdk-ui-dashboard/src/presentation/dashboard/types.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/GridLayoutElement.tsx

JIRA: LX-567
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: use semantic elements for dashboard main content and sections

---

libs/sdk-ui-tests-e2e/cypress/tools/widget.ts

JIRA: QA-24022
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: remove selector is no longer valid on kd

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/typings.ts

risk: low
JIRA: LX-555
---
> [!IMPORTANT]
---
```
``` …

fix: accessibility type

---

libs/sdk-ui-dashboard/src/presentation/widget/description/ExportModeInsightWidgetDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionComponentProvider.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/description/useInsightWidgetDescription.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/ExportableDashboardInsightWidget.tsx

- to avoid extending props, we provide insight description component via special provider
as it is not yet publicly customizable
JIRA: F1-1067
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: provide custom description component to exportable insight widget

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/slideshow/containerSlideTransformer.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/switcherSlideTransformer.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/tests/containerSlideTransformer.test.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/tests/layoutTransformer.test.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/tests/switcherSlideTransformer.test.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/tests/widgetSlideTransformer.test.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/widgetSlideTransformer.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/DashboardCustomizationsContext.tsx
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/index.ts
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/useSlideData.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutItem.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/ExportableDashboardLayoutSectionRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/GridLayoutElement.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/ExportableDashboardLayoutSectionRenderer.tsx

risk: low
JIRA: F1-1072
---
> [!IMPORTANT]
---
```
``` …

feat: layout transformer + plugin API

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItem.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/RichTextWidget/ExportableDashboardRichTextWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/ExportableDashboardVisualizationSwitcherWidget.tsx

JIRA: F1-1097
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: wrap widget with title and description in data attr

---

libs/sdk-ui-dashboard/styles/scss/_zIndexes.scss

JIRA: LX-788
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: update plugin overlay zindex to get it over resizer

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx

risk: low
JIRA: F1-1072
---
> [!IMPORTANT]
---
```
``` …

fix: repair dashboard resize in export mode

---

libs/sdk-ui-dashboard/src/_staging/slideshow/layoutTransformer.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/singleWidgetTransformer.ts
libs/sdk-ui-dashboard/src/_staging/slideshow/utils/index.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultFlexibleDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetHighlighting.ts
libs/sdk-ui-dashboard/src/presentation/widget/widget/RichTextWidget/ExportableDashboardRichTextWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/ExportableDashboardVisualizationSwitcherWidget.tsx

---
> [!IMPORTANT]
---
```
``` …

single-widget export transformation

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-loaders/src/dashboard/dashboardLoader.tsx

Allow to provide preloaded dashboard references to avoid additional requests to the server.
risk: low
JIRA: STL-1055
---
> [!IMPORTANT]
---
```
```
- …

fix: dashboard load optimizations

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/common.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/changeDateFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts

JIRA: F1-979
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: remove cross-filters when filter value changes

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts

JIRA: F1-979
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not reset cross filter when updating itself

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts

Alert evaluation failed when metric in Measure Value Filter is different then metric using in alert
risk: low
JIRA: F1-1079
---
> [!IMPORTANT]
---
```
``` …

fix: alert evaluation failed, metric in Measure Filter

---

libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts

- contains object availability in the cmd
risk: low
JIRA: STL-1091
---
> [!IMPORTANT]
---
```
``` …

fix: provide initialize command to load catalog

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRow.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutGridRowEdit.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/ExportableDashboardLayoutSectionRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/interfaces.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/transformation.ts

JIRA: F1-1072, F1-1079
---
> [!IMPORTANT]
---
```
``` …

fix: bugfixes related to alerts and exports

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

JIRA: LX-579, F1-565
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: remove feature flags related to workspace settings

---

libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/addAttributeFilterHandler.ts
libs/sdk-ui-dashboard/src/model/commands/filters.ts
libs/sdk-ui-dashboard/src/model/store/filterContext/filterContextSelectors.ts

Can't do cross-filtering after doing cross-filtering sam attribute several times Cross filtering shouldn't stop working due to filter count limit
risk: low
JIRA: F1-1082, F1-1084
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The …

fix: repairs related to cross filtering

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/styles/scss/messages.scss

Ensure save button is visible
Make headline container larger
---
> [!IMPORTANT]
---
```
``` …

RELEVANT: GDAI-48 styling fixes for save button

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/convertors.ts

Alert evaluation failed when metric in Measure Value Filter is different than metric using in alert
risk: low
JIRA: F1-1079
---
> [!IMPORTANT]
---
```
``` …

fix: alert evaluation failed

---

common/changes/@gooddata/sdk-ui-all/ovel-attr-filter-customization_2025-02-05-16-07.json
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts

JIRA: MC-3373
---
> [!IMPORTANT]
---
```
``` …

feat(sdk-ui-dashboard): make dash attr filter compon customizable

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/index.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/initializeDashboardHandler/resolveEntitlements.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: consume entitlements sent in config

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx

risk: low
JIRA: MC-3418
---
> [!IMPORTANT]
---
```
``` …

fix: add title to alerts

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/utils.ts

risk: low
JIRA: F1-1086
---
> [!IMPORTANT]
---
```
``` …

fix: scheduling issue with timezone

---

libs/sdk-ui-semantic-search/src/internal/SearchOverlay.tsx
libs/sdk-ui-semantic-search/src/utils/getUIPath.ts

Links to vis on dash should highlight the vis
---
> [!IMPORTANT]
---
```
```
- …

RELATED: GDAI-65 dashboard deep links

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/test/transform.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts

risk: low
JIRA: F1-1090
---
> [!IMPORTANT]
---
```
``` …

fix: should not uppercase the first character of comparison operator

---

common/changes/@gooddata/sdk-ui-all/ovel-dashboard-filters-apply-mode_2025-02-12-14-43.json
libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts

GDP-2938
---
> [!IMPORTANT]
---
```
``` …

feat: support enableDashboardFiltersApplyModes feature flag

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

Add new feature flag `enableExecutionCancelling`.
risk: low
JIRA: F1-1095
---
> [!IMPORTANT]
---
```
``` …

feat: add enableExecutionCancelling feature flag

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-tests-e2e/cypress.config.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardRichText.spec.ts
libs/sdk-ui-tests-e2e/cypress/support/index.ts
libs/sdk-ui-tests-e2e/package.json

JIRA: QA-24041
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: get cypress log from console

---

libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1072
---
> [!IMPORTANT]
---
```
``` …

fix: add data-export attributes into inner sections title and desc

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useThresholdValue.ts

risk: low
JIRA: F1-1091
---
> [!IMPORTANT]
---
```
``` …

fix: round threshold value after change it

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-kit/src/Messages/Messages.tsx
libs/sdk-ui-kit/styles/scss/messages.scss

risk: low
JIRA: LX-558
---
> [!IMPORTANT]
---
```
``` …

feat: accessibility message/labels updates

---

common/changes/@gooddata/sdk-ui-all/ovel-apply-filters-org-config_2025-02-18-14-18.json
libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/export-json-api/api.ts
libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/decoratedBackend/workspaceSettings.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/organization/settings/index.ts
libs/sdk-backend-spi/src/workspace/settings/index.ts
libs/sdk-backend-tiger/src/backend/organization/settings.ts
libs/sdk-backend-tiger/src/backend/settings/mapping.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/index.ts
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts

https://gooddata.atlassian.net/browse/GDP-2938
---
> [!IMPORTANT]
---
```
```
- …

Dashboard filters apply mode org and ws config

---

libs/sdk-ui-kit/src/Header/Header.tsx
libs/sdk-ui-kit/src/Header/HeaderMenu.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-722
---
> [!IMPORTANT]
---
```
``` …

feat: header accessibility

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useThresholdValue.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/utils/getters.ts

Also apply right formating
risk: low
JIRA: F1-1104
---
> [!IMPORTANT]
---
```
``` …

fix: get blank page when filled threshold number is too large

---

.github/workflows/doc-strorybook-deploy.yml

risk: low
JIRA: LX-818
---
> [!IMPORTANT]
---
```
``` …

feat: update Storybook deploy to daily

---

common/changes/@gooddata/sdk-ui-all/ine-lx-712_2025-02-19-15-17.json
docs/content/en/latest/learn/embed_dashboards/web_components/authentication.md
docs/content/en/latest/learn/integrate_and_authenticate/CN_and_cloud_authentication.md
docs/content/en/latest/learn/integrate_and_authenticate/_index.md
docs/content/en/latest/learn/integrate_and_authenticate/cn_and_cloud_integration.md
libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
libs/sdk-backend-tiger/src/auth.ts
libs/sdk-backend-tiger/src/index.ts

And update documentation by FIM specific usage
---
> [!IMPORTANT]
---
```
```
- …

feat: provide factory to parametrize default redirect handler

---

libs/sdk-ui-dashboard/src/presentation/dashboard/components/DashboardInner.tsx

risk: low
JIRA: STL-1122
---
> [!IMPORTANT]
---
```
``` …

fix: add css class when dashboards list loaded

---

docs/go.mod
docs/go.sum

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

WEB-4298 Search upgrade in Documentation

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts
libs/sdk-ui-dashboard/src/presentation/widget/richText/ExportModeDashboardRichText.tsx

risk: low
JIRA: F1-1108
---
> [!IMPORTANT]
---
```
``` …

fix: get formatted text from Rich Text widgets

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/GridLayoutElement.tsx

JIRA: LX-567
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove redundant role attribute

---

libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

When ID of parent workspace setting property (property set on parent) is located after native workspace setting (property set on child) in the list of properties returned by API response, the SPI backend setting service used parent value instead of the native one. The introduced change fixes the faulty behavior.
JIRA: LX-819
risk: low
---
> [!IMPORTANT]
---
```
extended-test …
```

fix: prefer native workspace setting over parent one in settings SPI

---

dev_docs/contributing.md

risk: low
---
> [!IMPORTANT]
---
```
``` …

docs: clear up contribution guide commit message footer requirements

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/export-json-api/api.ts
libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts

Update new client for slides
risk: low
JIRA: F1-1117
---
> [!IMPORTANT]
---
```
``` …

fix: ui for new exports

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboardContexts/useSlideData.ts
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutViewSectionHeaderRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSection.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeader.tsx

- section-info
- data-export-depth: number as string ("0", ...)
risk: low
JIRA: F1-1072
---
> [!IMPORTANT]
---
```
``` …

fix: Added info data attributes

---

libs/sdk-ui/src/base/react/CorrelationContext.tsx

Fix memoization.
risk: low
JIRA: STL-1062
---
> [!IMPORTANT]
---
```
```
- …

fix: enhance telemetry capabilities

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/editButton/DefaultEditButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/shareButton/DefaultShareButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/shareIndicators/shareStatus/ShareStatusIndicator.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertComparisonOperatorSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertDestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenuButton.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeRangePicker/RelativeRangePicker.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Button/Button.tsx
libs/sdk-ui-kit/src/Button/typings.ts
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/Dropdown/DropdownButton.tsx
libs/sdk-ui-kit/src/EditableLabel/EditableLabel.tsx
libs/sdk-ui-kit/src/EditableLabel/typings.ts
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Messages/Message.tsx
libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/typings/accessibility.ts
libs/sdk-ui-kit/styles/scss/invertableSelect.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-555, LX-559
---
> [!IMPORTANT]
---
```
``` …

fix: accessibility fixes

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx

risk: low
JIRA: STL-1151
---
> [!IMPORTANT]
---
```
``` …

fix: do not call afterRender repeatedly

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui-pivot/src/tableState.ts

risk: low
JIRA: F1-1126
---
> [!IMPORTANT]
---
```
``` …

fix: long table is blank on content slide

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/AbstractPluggableVisualization.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

risk: low
JIRA: F1-1126
---
> [!IMPORTANT]
---
```
``` …

fix: geo chart is not shown on export

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-gen-ai/package.json
libs/sdk-ui-gen-ai/src/components/messages/contents/Markdown.tsx

Added markdown emoji support
---
> [!IMPORTANT]
---
```
``` …

RELATED: GDAI-64 emoji support

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/decoratedBackend/dashboards.ts
libs/sdk-backend-base/src/decoratedBackend/execution.ts
libs/sdk-backend-base/src/normalizingBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/dashboards.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/index.ts
libs/sdk-backend-spi/src/workspace/execution/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/execution/executionResult.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commands/insight.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/vis/export.ts

risk: low
JIRA: LX-841
---
> [!IMPORTANT]
---
```
``` …

fix: remove execute calls from export raw

---

libs/sdk-ui-geo/src/core/geoChart/GeoChartRenderer.tsx

risk: low
JIRA: STL-1171
---
> [!IMPORTANT]
---
```
``` …

fix: avoid error when setting interactions fails

---

.github/workflows/checklist-integrated-staging.yaml

JIRA: QA-24248
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: run the checklist once more time

---

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json

JIRA: STL-1175
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: update export result after highchart

---

libs/sdk-ui-tests-e2e/cypress/tools/attributeFilterLimit.ts

JIRA: QA-24255
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: fix AvailableFilter on UI SDK

---

libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix heatmap console error

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/DynamicSelect.tsx

- Wrong aria-labelledby added by 3rd party library (downshift)
risk: low
JIRA: LX-559
---
> [!IMPORTANT]
---
```
``` …

fix: wrong aria-labelledby

---

.github/workflows/release-code-drop.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: skip release beta in code drop

---

libs/sdk-ui-all/CHANGELOG.json
libs/sdk-ui-all/CHANGELOG.md

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

Chore: add change log note

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx

Widget with `No data for your filter selection` returns `loading` status
risk: low
JIRA: F1-1143
---
> [!IMPORTANT]
---
```
``` …

fix: widget with `error` returns `loading` status

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultFlexibleDashboardLayout.tsx

risk: low
JIRA: F1-1144
---
> [!IMPORTANT]
---
```
``` …

fix: mode=export duplicates variables

---

libs/sdk-ui-kit/src/Header/HeaderAccount.tsx
libs/sdk-ui-kit/styles/scss/header.scss

JIRA: LX-727
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: distinguish focus and focus-active styles

---

.github/workflows/checklist-integrated-staging.yaml

risk:nonprod
---
> [!IMPORTANT]
---
```
``` …

test: remove sdk checklist to run on release branch

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-backend-tiger/package.json
libs/sdk-backend-tiger/src/utils/downloadFile.ts

risk: low
JIRA: EB-274
---
> [!IMPORTANT]
---
```
``` …

fix: use mime decoded parser on export filename

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/sharedHooks/useFiltersNamings.ts
libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx
libs/sdk-ui-dashboard/src/presentation/export/hooks/useDashboardRelatedFilters.ts
libs/sdk-ui-dashboard/src/presentation/export/index.ts
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1144
---
> [!IMPORTANT]
---
```
``` …

feat: mode=export add filter type

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/utils/tests/utils.test.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/getDefaultInsightMenuItems.tsx
libs/sdk-ui-dashboard/src/presentation/widget/visualizationSwitcher/ViewModeDashboardVisualizationSwitcher.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/useInsightMenu.ts

JIRA: F1-1138
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: disable presentation export for widgets without local id

---

.github/workflows/checklist-integrated-staging.yaml
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/attributeFilterConfig.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboard.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardRichText.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardShortenMetricName.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dashboardTiger.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dateFiltering.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dragDropAndMoveWidget.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/headerSection.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/insightOnDashboard.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/pivotTableHasTotalAndSubtotalsOnDashboard.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/tableTranspose.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/funnelChart.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pivotTableTransposed.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pyramidChart.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/repeater.spec.ts

JIRA: QA-24268
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: add more tag to run on releng

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx
libs/sdk-ui-dashboard/src/presentation/export/hooks/useDashboardRelatedFilters.ts
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1150
---
> [!IMPORTANT]
---
```
``` …

fix: active filters on slides do not respect UDF, WDF

---

.github/workflows/checklist-integrated-staging.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: update branch name for checklist notification

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx

- Hide export options if user does not have required permissions.
risk: low
JIRA: LX-927
---
> [!IMPORTANT]
---
```
``` …

fix: new export under permissions

---

libs/sdk-ui-dashboard/src/presentation/export/hooks/useDashboardRelatedFilters.ts

- Active filters on slides do not respect UDF, WDF
- Active Filters on Slide should respect other Attribute Label as Default
risk: low
JIRA: F1-1161, F1-1150
---
> [!IMPORTANT]
---
```
``` …

fix: bug fixes related to export filters

---

libs/sdk-ui-kit/src/RichText/plugins/rehype-references.ts
libs/sdk-ui-kit/src/RichText/plugins/types.ts
libs/sdk-ui-kit/styles/scss/richText.scss

risk: low
JIRA: F1-1160
---
> [!IMPORTANT]
---
```
``` …

feat: rich text references support for links and images

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/widgetExports/widgetExportsSelectors.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx

risk: low
JIRA: LX-927
---
> [!IMPORTANT]
---
```
``` …

fix: new widget export options permissions

---

libs/sdk-ui-tests/stories/visual-regression/kit/RichText/RichText.tsx

risk: low
JIRA: F1-1160
---
> [!IMPORTANT]
---
```
``` …

fix: repair rich text storybook

---

libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedMetrics.ts
libs/sdk-ui-kit/src/RichText/plugins/rehype-references.ts

risk: low
JIRA: F1-1160
---
> [!IMPORTANT]
---
```
``` …

feat: use metric formatted value from exec results

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/sharedHooks/useRichTextFilters.ts
libs/sdk-ui-dashboard/src/converters/filterConverters.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutViewSectionHeaderRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeader.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/ExportModeInsightWidgetDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescriptionConfig.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/ViewModeDashboardRichText.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx
libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx

risk: low
JIRA: F1-1160
---
> [!IMPORTANT]
---
```
``` …

feat: support references in rich text in other components

---

common/changes/@gooddata/sdk-ui-all/ach-chart-tooltip-classname_2025-03-13-14-12.json
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx

- Add optional class name for chart tooltips
- Specify chart-specific tooltip class
---
> [!IMPORTANT]
---
```
``` …

RELATED: GDAI-24 Chart Tooltip Class Name

---

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/src/index.ts
libs/sdk-ui-gen-ai/src/store/events.ts
libs/sdk-ui-gen-ai/src/store/index.ts
libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/onEvent.ts

Add error events for visualizations
---
> [!IMPORTANT]
---
```
```
-   `--record` …

RELATED: GDAI-30 Visualizations error handling

---

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/ConfigContext.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/CustomHyperlink.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/Markdown.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/replaceLinks.ts
libs/sdk-ui-gen-ai/src/components/messages/contents/test/parseText.test.ts
libs/sdk-ui-gen-ai/src/index.ts
libs/sdk-ui-gen-ai/styles/scss/messages.scss

Allow configuration of the links
---
> [!IMPORTANT]
---
```
```
-   `--record` …

RELATED: GDAI-127 Chat links handling

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/index.ts
libs/sdk-model/src/theme/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1150
---
> [!IMPORTANT]
---
```
``` …

feat: logo and cover-image in slides metadata

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1174
---
> [!IMPORTANT]
---
```
``` …

feat: palette data

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts

risk: low
JIRA: STL-1165
---
> [!IMPORTANT]
---
```
``` …

feat: add featureflag for AD catalog sideload

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/common/configuration/ConfigurationBubble.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/DescriptionClickTrigger.tsx
libs/sdk-ui-dashboard/styles/scss/alerting.scss
libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Bubble/Bubble.tsx
libs/sdk-ui-kit/src/Bubble/tests/Bubble.test.tsx
libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx
libs/sdk-ui-kit/src/Overlay/Overlay.tsx
libs/sdk-ui-kit/src/Overlay/ZoomAwareOverlay.tsx
libs/sdk-ui-kit/src/Overlay/index.ts
libs/sdk-ui-kit/src/Overlay/tests/Overlay.test.tsx
libs/sdk-ui-kit/src/Overlay/typings.ts
libs/sdk-ui-kit/src/ZoomContext/ZoomContext.tsx
libs/sdk-ui-kit/src/ZoomContext/index.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/typings/overlay.ts
libs/sdk-ui-kit/styles/scss/descriptionPanel.scss
libs/sdk-ui-vis-commons/src/legend/PopUpLegend/LegendDialog.tsx
libs/sdk-ui-vis-commons/styles/scss/legend.scss

---
> [!IMPORTANT]
---
```
``` …

fix: handle zoomed window on problematic places 

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/dependentFilters.spec.ts

JIRA: QA-24309-3
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: stabilize dependent filter tests

---

libs/sdk-backend-tiger/src/backend/workspace/execution/preparedExecution.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useExecutionTimestampMessage.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx

JIRA: F1-1169
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: rename snapshot related logic to execution timestamp

---

libs/sdk-ui-dashboard/src/model/store/insights/insightsSelectors.ts

We need to fill the names of derived measure that were not renamed by the user. This uses the same logic as the rest of the UI, so it should be consistent with what the user sees on the UI itself.
JIRA: CQ-1210
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to …

fix: handle derived measures in dashboard raw exports

---

libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx

risk: low
JIRA: F1-1164
---
> [!IMPORTANT]
---
```
``` …

feat: problem with Alert checkbox in Analyse

---

libs/sdk-ui-all/CHANGELOG.json
libs/sdk-ui-all/CHANGELOG.md

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: update change log after release 9.9.2

---

libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanel.tsx
libs/sdk-ui-ext/src/notificationsPanel/NotificationsPanel/DefaultNotificationsPanelButton.tsx
libs/sdk-ui-kit/src/Button/Button.tsx
libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/Header/HeaderHelp.tsx
libs/sdk-ui-kit/src/Header/HeaderSearchButton.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

JIRA: LX-727
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: add missing aria props

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx

JIRA: F1-1169
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: use executionTimestamp in drill to insight

---

libs/sdk-ui-dashboard/styles/scss/dashboard.scss

risk: low
JIRA: F1-1180
---
> [!IMPORTANT]
---
```
``` …

feat: headline in container is not boxed properly in export mode

---

libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx

risk: low
JIRA: F1-1183
---
> [!IMPORTANT]
---
```
``` …

fix: Theme images (logo, cover) kept in `loading` state

---

libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx

risk: low
JIRA: F1-934
---
> [!IMPORTANT]
---
```
``` …

fix: ad not creating events on when label of filter or props changed

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-charts/api/sdk-ui-charts.api.md
libs/sdk-ui-charts/src/highcharts/adapter/Chart.tsx
libs/sdk-ui-charts/src/highcharts/adapter/test/Chart.test.tsx
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/commonConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/highChartsCreators.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartOptions/chartOptionsForSettings.ts
libs/sdk-ui-charts/src/interfaces/chartConfig.ts
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectListItem.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItem.tsx
libs/sdk-ui-geo/src/core/geoChart/legends/test/PushpinCategoryLegend.test.tsx
libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx
libs/sdk-ui-vis-commons/src/legend/LegendItem.tsx
libs/sdk-ui-vis-commons/src/legend/Paging.tsx
libs/sdk-ui-vis-commons/src/legend/test/FluidLegend.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/LegendItem.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/LegendList.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/Paging.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/PopUpLegend.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/StaticLegend.test.tsx
libs/sdk-ui-vis-commons/src/locales.ts
libs/sdk-ui-vis-commons/styles/scss/legend.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

---
> [!IMPORTANT]
---
```
``` …

feat: accessibility turned on on charts

---

.github/workflows/checklist-cypress-ui-test.yaml

JIRA: QA-24269
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: integrate sdk test into releng

---

libs/sdk-ui-dashboard/src/locales.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialog.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/AlertsList.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlerts.tsx

---
> [!IMPORTANT]
---
```
``` …

execution timestamp interactions

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx

Handle special errors, like negative values in pie chart or "too many data points"
---
> [!IMPORTANT]
---
```
``` …

RELATED: GDAI-108 vis error handling

---

libs/sdk-ui-semantic-search/styles/scss/internal.scss

```
```
-   `--filter` (Optional) A comma-separated list of test files to run. This parameter is valid only for the `--integrated`, `--isolated`, and `--record` commands.
```
extended-test --backstop
extended-test --integrated
extended-test --integrated --filter …
```

RELATED: GDAI-130 Add padding to the "nothing found" message

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/changeRenderModeHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/renderMode/tests/__snapshots__/changeRenderModeHandler.test.ts.snap
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/editButton/DefaultEditButton.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/editButton/types.ts

JIRA: F1-1169
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: do not allow edit mode with execution timestamp

---

libs/sdk-ui-pivot/src/impl/cell/cellClass.ts

risk: low
JIRA: STL-1235
---
> [!IMPORTANT]
---
```
``` …

fix: add row subtotal value selector

---

libs/sdk-ui-dashboard/styles/scss/filterBar.scss

JIRA: LX-938
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: execution timestamp message styling

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/gd-tiger-model/index.ts
libs/api-client-tiger/src/gd-tiger-model/typeGuards.ts
libs/api-client-tiger/src/index.ts
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-backend-mockingbird/src/recordedBackend/insights.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/insights/index.ts
libs/sdk-backend-tiger/src/backend/workspace/insights/index.ts

risk: low
JIRA: STL-1165
---
> [!IMPORTANT]
---
```
``` …

feat: load catalog items related to insight

---

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
libs/sdk-ui-dashboard/styles/scss/filterBar.scss

JIRA: F1-1169
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: wider execution timestamp message

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

JIRA: F1-1169
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: introduce enableExecutionTimestamp FF

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx

JIRA: LX-791
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: disable autofocus on dialog with autofocusable input

---

libs/sdk-ui-dashboard/styles/scss/drillSelect.scss

JIRA: LX-979
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove focus effect on drill select item

---

libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-pivot/styles/scss/pivotTable.scss

JIRA: LX-769
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: create custom focus indicator for checkbox, radio, toggle

---

libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx

JIRA: LX-990
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: dialog autofocus is turned off by default

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx
libs/sdk-ui-kit/src/Header/HeaderWorkspacePicker.tsx
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/recurrenceForm.scss

---
> [!IMPORTANT]
---
```
``` …

fix: stabilize backstop tests after latest changes

---

libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayout.tsx

risk: low
JIRA: GDP-2903
---
> [!IMPORTANT]
---
```
``` …

feat: mode=export add over all dashboard status

---

.github/workflows/checklist-cypress-ui-test.yaml
.github/workflows/checklist-run-boiler-app.yaml

JIRA: QA-24446
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: edit git checkout and runner of checklist wf

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/decoratedBackend/dashboards.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportMetadataConverter.ts
libs/sdk-backend-tiger/src/types/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts

risk: low
JIRA: F1-1217
---
> [!IMPORTANT]
---
```
``` …

feat: possibility to override dashboard title and hide all widget titles

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx

JIRA: LX-795
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: RecipientsSelect accessibility fixes

---

.github/workflows/pull-request-comment.yaml

JIRA: STL-1259
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: fix pr comment workflow condition for backstop

---

libs/sdk-ui-dashboard/src/presentation/dashboard/components/useFilterContextValidationMessages.tsx

risk: low
JIRA: F1-1219
---
> [!IMPORTANT]
---
```
``` …

fix: warning in sharable link should not display in export mode

---

libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/AttributeFilterElementsSelectItem.tsx
libs/sdk-ui-filters/src/AttributeFilter/Components/ElementsSelect/SingleSelectionAttributeFilterElementsSelectItem.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectAllCheckbox.tsx
libs/sdk-ui-kit/src/utils/events.ts
libs/sdk-ui-kit/styles/scss/Button/_mixins.scss
libs/sdk-ui-kit/styles/scss/form.scss
libs/sdk-ui-kit/styles/scss/invertableSelect.scss
libs/sdk-ui-kit/styles/scss/list.scss

JIRA: LX-769
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: create custom focus indicator for attribute filter items

---

common/changes/@gooddata/sdk-ui-all/ovel-fix-search-w-apply-crash_2025-03-31-10-21.json

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix pre release

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/types/commonTypes.ts
libs/sdk-ui-dashboard/src/presentation/export/DefaultDashboardExportVariables.tsx
libs/sdk-ui-dashboard/src/presentation/export/types.ts
libs/sdk-ui-dashboard/src/presentation/export/useExportData.ts

risk: low
JIRA: F1-1215
---
> [!IMPORTANT]
---
```
``` …

feat: expose exportedBy and workspaceName variables

---

.github/workflows/test-backstop.yml

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: scheduled cron set default input to false

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/ExportModeInsightWidgetDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescriptionConfig.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/ViewModeDashboardRichText.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx
libs/sdk-ui-kit/src/List/InsightListItem.tsx
libs/sdk-ui-kit/src/RichText/RichText.tsx
libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx
libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedMetricsAndAttributes.ts
libs/sdk-ui-kit/src/RichText/plugins/rehype-references.ts
libs/sdk-ui-kit/src/RichText/plugins/tests/__snapshots__/rehype.test.ts.snap
libs/sdk-ui-kit/src/RichText/plugins/tests/rehype.test.ts
libs/sdk-ui-tests-e2e/cypress/tools/richText.ts

risk: low
JIRA: F1-1194
---
> [!IMPORTANT]
---
```
``` …

fix: can't apply metric format in rich text

---

docs/content/en/latest/references/dashboard_component/dashboard_plugins_api.md

risk: low
JIRA: EB-292
---
> [!IMPORTANT]
---
```
``` …

fix: exports documentation in SDK

---

.github/workflows/rw-publish-release.yml

---
> [!IMPORTANT]
---
```
```
- …

chore: fix checkout in local action

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts

Needed for upcoming slides exports.
JIRA: F1-1247
risk: low
---
> [!IMPORTANT]
---
```
```
- …

chore: enableDashboardAfterRenderDetection to true

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightDescriptionConfig/InsightDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/ViewModeDashboardRichText.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/DescriptionPanel/DescriptionPanel.tsx
libs/sdk-ui-kit/src/RichText/RichText.tsx
libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx
libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedMetricsAndAttributes.ts
libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedReferences.ts

risk: low
JIRA: F1-1169
---
> [!IMPORTANT]
---
```
``` …

fix: timestamp execution in rich text references

---

.github/workflows/gate.yaml
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pivotTableRemoveAllFromMutipleAggregation.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/03-sdk-ui-charts/pivotTableRemoveOneAggregation.spec.ts

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix run e2e for Bear

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/sharedHooks/useRichTextFilters.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/common/filterOperations.ts
libs/sdk-ui-dashboard/src/model/queries/insights.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeaderDescription.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/EditableHeader/SectionHeaderEditable.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/ExportModeInsightWidgetDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/EditModeDashboardRichText.tsx
libs/sdk-ui-dashboard/src/presentation/widget/richText/ViewModeDashboardRichText.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RichText/RichText.tsx
libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedMetricsAndAttributes.ts
libs/sdk-ui-kit/src/RichText/hooks/useEvaluatedReferences.ts

risk: low
JIRA: F1-1195
---
> [!IMPORTANT]
---
```
``` …

fix: didn't apply date filter to metric in rich text

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterButton/DateFilterButton.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterButtonLocalized/DateFilterButtonLocalized.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterTextLocalized/DateFilterTextLocalized.tsx
libs/sdk-ui-filters/src/DateFilter/index.ts
libs/sdk-ui-filters/src/index.ts

---
> [!IMPORTANT]
---
```
```
- …

Filters in scheduling preparation

---

.github/pull_request_template.md
.github/workflows/pull-request-comment.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: tuning of legacy commands and PR template

---

.github/workflows/pull-request-comment.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix e2e PR commands

---

libs/sdk-ui-pivot/src/CorePivotTable.tsx

risk: low
JIRA: F1-1227
---
> [!IMPORTANT]
---
```
``` …

fix: execution cancelling in pivot table

---

libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItem.tsx
libs/sdk-ui-kit/styles/scss/aria.scss
libs/sdk-ui-kit/styles/scss/main.scss
libs/sdk-ui-vis-commons/src/legend/ColorLegend.tsx
libs/sdk-ui-vis-commons/src/legend/LegendAxisIndicator.tsx
libs/sdk-ui-vis-commons/src/legend/PopUpLegend/PopUpLegend.tsx
libs/sdk-ui-vis-commons/src/legend/test/ColorLegend.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/HeatmapLegend.test.tsx
libs/sdk-ui-vis-commons/src/legend/test/Legend.test.tsx
libs/sdk-ui-vis-commons/src/locales.ts

JIRA: LX-785
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: Remove various illegal aria labels

---

.github/workflows/checklist-cypress-ui-test.yaml

JIRA: QA-24473
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: allow fetching all history to checkout from a revision or a desired branch

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-AU.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-GB.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-419.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-CA.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/it-IT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillModalRawExportOptions.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx

risk: low
JIRA: LX-1018
---
> [!IMPORTANT]
---
```
``` …

fix: add missing translations for raw exports

---

libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/toolkit/auth.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/backend/index.ts
libs/sdk-backend-tiger/api/sdk-backend-tiger.api.md
libs/sdk-backend-tiger/src/auth.ts

- and fix docs typo
JIRA: MC-3592
risk: high
---
> [!IMPORTANT]
---
```
```
-   `--isolated` The command …

fix(sdk-backend-tiger): session renewal in custom apps

---

libs/sdk-ui/src/base/localization/bundles/en-AU.json
libs/sdk-ui/src/base/localization/bundles/en-GB.json

risk: low
---
> [!IMPORTANT]
---
```
``` …

trivial: non US translations

---

libs/sdk-ui-dashboard/src/model/store/topBar/topBarSelectors.ts
libs/sdk-ui-dashboard/src/presentation/dashboardSettingsDialog/DefaultDashboardSettingsDialog.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/styles/scss/dashboardSettingsDialog.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
libs/sdk-ui-kit/src/RecurrenceForm/locales.ts
libs/sdk-ui-kit/src/RecurrenceForm/utils.test.ts
libs/sdk-ui-kit/src/RecurrenceForm/utils.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: F1-1254. F1-1257
---
> [!IMPORTANT]
---
```
``` …

feat: dashboard dialog settings with alerts

---

libs/sdk-ui-dashboard/src/presentation/insightList/InsightList.tsx
libs/sdk-ui-dashboard/src/presentation/layout/dragAndDrop/draggableWidget/useNewSectionRichTextPlaceholderDropHandler.ts
libs/sdk-ui-dashboard/src/presentation/layout/dragAndDrop/draggableWidget/useRichTextPlaceholderDropHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/description/ExportModeInsightWidgetDescription.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/InsightWidgetDescriptionTrigger.tsx
libs/sdk-ui-dashboard/src/presentation/widget/description/types.ts
libs/sdk-ui-dashboard/styles/scss/dashboardSettingsDialog.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/List/InsightListItem.tsx

- question mark icons are too close to text
- references in Rich text can't apply common date
- widget description still didn't apply asOfDate
JIRA: F1-1260, F1-1255, F1-1258
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with keeping …

fix: more bugfixes related to evaluation frequency and rich texts

---

libs/sdk-ui-kit/src/@ui/UiChip/UiChip.tsx

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: use layout effect for width computing in uichip

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-AU.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-GB.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-419.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-CA.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/it-IT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json

risk: low
JIRA: LX-1018
---
> [!IMPORTANT]
---
```
``` …

feat: add missing translations

---

libs/sdk-ui-filters/src/DateFilter/RelativeRangePicker/RelativeRangePicker.tsx

JIRA: LX-1055
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: correct handling of 0 value in relative date range

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useSaveAlertToBackend.ts

risk: low
JIRA: F1-1273
---
> [!IMPORTANT]
---
```
``` …

fix: unable to update Alert with dashboard-level frequency

---

libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: multiple automation filters fixes

---

libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/DialogBase.tsx

risk: low
JIRA: LX-870
---
> [!IMPORTANT]
---
```
``` …

fix: Fix undefined accessibilityConfig

---

libs/sdk-ui-kit/src/Dialog/DialogBase.tsx

risk: low
JIRA: LX-870
---
> [!IMPORTANT]
---
```
``` …

fix: Fix undefined handler

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/dashboardSettingsDialog/DefaultDashboardSettingsDialog.tsx

risk: low
JIRA: GDP-2960
---
> [!IMPORTANT]
---
```
``` …

feat: enable FF by default

---

libs/sdk-ui-filters/src/DateFilter/RelativeRangePicker/RelativeRangePicker.tsx

JIRA: LX-976
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: last relative period picker fixes

---

libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/automations/index.ts
libs/sdk-model/src/execution/filter/index.ts
libs/sdk-model/src/index.ts
libs/sdk-ui-dashboard/.dependency-cruiser.cjs
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/dashboard/dashboardFilterConverter.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationDashboardFilters.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFilters.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/types.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultLoadingScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/DashboardAttachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/WidgetAttachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/styles/scss/automationFilters.scss
libs/sdk-ui-dashboard/styles/scss/main.scss
libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss

---
> [!IMPORTANT]
---
```
```
- …

Schedule automation filters

---

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts

Trigger immediate filter elements reload via "init-self" change, instead of delayed elements reload upon filter dropdown opening via "init-parent" change.
JIRA: LX-991
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with keeping …

fix: reload attr filter elements when parent selection changed

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/DefaultButtonBar.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/buttonBar/button/settingButton/DefaultSettingButton.tsx
libs/sdk-ui-dashboard/styles/scss/dashboardSettingsDialog.scss
libs/sdk-ui-dashboard/styles/scss/topBar.scss
libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeDescription.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx
libs/sdk-ui-kit/src/RecurrenceForm/locales.ts
libs/sdk-ui-kit/styles/scss/recurrenceForm.scss
libs/sdk-ui-tests/stories/visual-regression/themeWrapper.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: F1-1284
---
> [!IMPORTANT]
---
```
``` …

feat: ui content improvements

---

libs/sdk-ui-dashboard/src/presentation/dashboardSettingsDialog/DefaultDashboardSettingsDialog.tsx
libs/sdk-ui-dashboard/styles/scss/dashboardSettingsDialog.scss

risk: low
JIRA: F1-1254
---
> [!IMPORTANT]
---
```
``` …

feat: small design updates related to figma

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/export/const.ts

dependency wheel is blank on slide if it is inside a container with many visualizations
risk: low
JIRA: F1-1159
---
> [!IMPORTANT]
---
```
``` …

fix: warning for really smart vis in export

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/styles/scss/automationFilters.scss
libs/sdk-ui-kit/src/Icon/icons/QuestionMark.tsx

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

Schedule automation filters improvements

---

libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx

risk: low
JIRA: LX-729
---
> [!IMPORTANT]
---
```
``` …

fix: Only generate titleElementId when needed

---

libs/sdk-ui-kit/src/@ui/UiChip/UiChip.scss
libs/sdk-ui-kit/src/@ui/UiChip/UiChip.tsx

risk: low
JIRA: F1-1249
---
> [!IMPORTANT]
---
```
``` …

fix: ui chip right width after change of label

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForDashboardScheduledExport.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts

JIRA: F1-1251
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: date filter local identifiers based on FF

---

libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardQueryProcessing.ts

risk: low
JIRA: F1-1293
---
> [!IMPORTANT]
---
```
``` …

fix: dashboard description doesn't load for viewers

---

libs/sdk-ui-kit/src/RichText/plugins/rehype-references.ts
libs/sdk-ui-kit/src/RichText/plugins/tests/__snapshots__/rehype.test.ts.snap
libs/sdk-ui-kit/src/RichText/plugins/tests/rehype.test.ts
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/results/dataAccess.ts
libs/sdk-ui/src/base/results/internal/dataAccessImpl.ts
libs/sdk-ui/src/base/results/internal/test/dataAccessImpl.test.ts

risk: low
JIRA: F1-1210
---
> [!IMPORTANT]
---
```
``` …

fix: number value of attribute reference must show as string 

---

libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiChip/UiChip.tsx
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

---
> [!IMPORTANT]
---
```
```
- …

automation filters improvements

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/DialogBase.tsx
libs/sdk-ui-kit/src/Dialog/typings.ts

---
> [!IMPORTANT]
---
```
```
- …

feat: schedule recipients validation and errors

---

libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/styles/scss/sharedFilterConfig.scss

risk: low
JIRA: F1-1162
---
> [!IMPORTANT]
---
```
``` …

fix: ui issues in export options dialog

---

libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx

JIRA: LX-1073
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: correct import to make UI SDK compatible with older React again

---

libs/sdk-ui-dashboard/src/model/queryServices/queryWidgetFilters.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx

---
> [!IMPORTANT]
---
```
```
- …

automation filters bugfixes

---

libs/sdk-ui-dashboard/.dependency-cruiser.cjs
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/useExecutionTimestampMessage.ts

risk: low
JIRA: F1-1229
---
> [!IMPORTANT]
---
```
``` …

feat: time in message snapshot didn't respect Org timezone

---

libs/sdk-ui-dashboard/src/presentation/automationFilters/AutomationFilters.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationDashboardFilters.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/AutomationFiltersSelect/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

refactor: rename automation filters props and component

---

libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilterContext.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiChip/UiChip.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

JIRA: F1-1241
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove uichip intl dependency

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightAlerting.ts

risk: low
JIRA: F1-1231
---
> [!IMPORTANT]
---
```
``` …

fix: shouldn't allow to create alert in snapshot mode

---

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts

fix: omit date local id when comparing with old filters

---

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useFiltersForWidgetScheduledExport.ts

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not alter widget scheduled filters

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx

JIRA: F1-1249
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: check date datasets in attributes dropdown on change

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts

Multiple date filter didn't change when accessing DB with automationId
risk: low
JIRA: F1-1292
---
> [!IMPORTANT]
---
```
``` …

fix: multiple date filters with automationId

---

libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeDescription.tsx
libs/sdk-ui-kit/styles/scss/recurrenceForm.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: F1-1306
---
> [!IMPORTANT]
---
```
``` …

fix: text alignment issue

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts

Attribute filter always shows "All" when accessed by automationId of schedule dashboard
risk: low
JIRA: F1-1308
---
> [!IMPORTANT]
---
```
``` …

fix: attribute filter always shows "All"

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx
libs/sdk-ui-dashboard/styles/scss/visualizationSwitcherHeader.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/setupTests.ts
libs/sdk-ui-kit/src/@ui/@utils/keyboardNavigation.ts
libs/sdk-ui-kit/src/@ui/@utils/tests/keyboardNavigation.test.ts
libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx
libs/sdk-ui-kit/src/@ui/UiListbox/UiListbox.scss
libs/sdk-ui-kit/src/@ui/UiListbox/UiListbox.tsx
libs/sdk-ui-kit/src/@ui/UiListbox/defaults/DefaultUiListboxItemComponent.tsx
libs/sdk-ui-kit/src/@ui/UiListbox/defaults/firstCharacterSearch.ts
libs/sdk-ui-kit/src/@ui/UiListbox/listboxBem.ts
libs/sdk-ui-kit/src/@ui/UiListbox/tests/UiListbox.test.tsx
libs/sdk-ui-kit/src/@ui/UiListbox/types.ts
libs/sdk-ui-kit/src/@ui/index.scss
libs/sdk-ui-kit/src/Dialog/DialogBase.tsx
libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx
libs/sdk-ui-kit/src/Dropdown/DropdownButtonKeyboardWrapper.tsx
libs/sdk-ui-kit/src/Dropdown/tests/DropdownButtonKeyboardWrapper.test.tsx
libs/sdk-ui-kit/src/List/index.ts
libs/sdk-ui-kit/src/index.ts
libs/sdk-ui-kit/src/utils/domUtilities.ts
libs/sdk-ui-kit/styles/scss/dropdown.scss
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/react/useAutoupdateRef.ts

risk: low
JIRA: LX-1038
---
> [!IMPORTANT]
---
```
``` …

feat: accessible listbox component

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-tests-e2e/cypress/support/featureHub.ts

risk: low
JIRA: STL-1210
---
> [!IMPORTANT]
---
```
``` …

feat: remove after render detection ff after rollout

---

libs/sdk-ui-kit/src/RichText/RichText.tsx
libs/sdk-ui-kit/src/RichText/RichTextWithTooltip.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: F1-1312
---
> [!IMPORTANT]
---
```
``` …

feat: update markdown hint

---

libs/sdk-ui-kit/styles/scss/dropdown.scss

risk: low
JIRA: LX-1038
---
> [!IMPORTANT]
---
```
``` …

fix: make dropdown button display: block

---

libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionsDropdown.tsx

risk: low
JIRA: LX-1031
---
> [!IMPORTANT]
---
```
``` …

feat: use custom permission button

---

libs/sdk-ui-tests-e2e/README.md

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

docs: add minimal working .env example for e2e tests app

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/converters/filterConverters.ts
libs/sdk-ui-dashboard/src/converters/index.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationWidgetFilters.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts

JIRA: F1-1302
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: properly convert all time dashboard date filter to execution filter

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dialog/ConfirmDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/DialogBase.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeBase.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/AddGranteeSelect.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/GranularPermissions/GranularPermissionsDropdownBody.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/ShareDialogBase.tsx
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/types.ts
libs/sdk-ui-kit/src/Dialog/ShareDialog/ShareDialogBase/utils.ts
libs/sdk-ui-kit/src/Dialog/typings.ts
libs/sdk-ui-kit/styles/scss/button.scss

risk: low
JIRA: LX-1031
---
> [!IMPORTANT]
---
```
``` …

fix: share dialog fixes

---

libs/sdk-ui-dashboard/src/presentation/automationFilters/useAutomationFiltersData.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx

JIRA: F1-1323
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: respect widget date filter ignore

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RecurrenceForm/CronExpression.tsx
libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
libs/sdk-ui-kit/src/RecurrenceForm/useCronValidation.ts

risk: low
JIRA: F1-1330
---
> [!IMPORTANT]
---
```
``` …

fix: cron description update

---

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts

When attribute filter is changed by set filter context command and both parent and child are changed, the child elements are not reloaded. They should and code was written with this in mind (the reload flag is set to true) but the change did not happen as the code is synchronous, the value was changed in the same render cycle and then switched to false. The fix uses mutable ref to keep the internal flag value, making the original logic work.
JIRA: LX-991
risk: low
---
> [!IMPORTANT]
---
Commands can be triggered by posting a …

fix: attribute filter elements are not reloaded even when they should

---

libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/CompareSection.tsx
libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/withDrillable.tsx
libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/tests/BaseHeadline.test.tsx
libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/tests/CompareSection.test.tsx
libs/sdk-ui-charts/src/charts/headline/internal/transformations/ComparisonTransformation.tsx
libs/sdk-ui-charts/src/charts/headline/internal/transformations/MultiMeasuresTransformation.tsx
libs/sdk-ui-charts/styles/scss/headline.scss
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItem.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemHeadline.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemHeadlineContainer.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx
libs/sdk-ui-vis-commons/api/sdk-ui-vis-commons.api.md
libs/sdk-ui-vis-commons/src/compactSize/HeadlinePagination.tsx
libs/sdk-ui-vis-commons/src/compactSize/HeadlinePaginationRenderer.tsx
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-1027
---
> [!IMPORTANT]
---
```
``` …

feat: Headline Acc. keyboard

---

libs/sdk-ui-charts/styles/scss/headline.scss

risk: low
JIRA: LX-1027
---
> [!IMPORTANT]
---
```
``` …

fix: headline item styles

---

libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/withDrillable.tsx
libs/sdk-ui-charts/styles/scss/headline.scss

risk: low
JIRA: LX-1091
---
> [!IMPORTANT]
---
```
``` …

fix: headline item content as div element

---

.cursor/rules/cursor/rules.mdc
.cursor/rules/general/general.mdc
.cursor/rules/guides/accessibility.mdc
.cursor/rules/guides/architecture.mdc
.cursor/rules/guides/commits.mdc
.cursor/rules/guides/examples.mdc
.cursor/rules/guides/folder-structure.mdc
.cursor/rules/guides/installation-and-build.mdc
.cursor/rules/guides/packages-overview.mdc
.cursor/rules/guides/public-documentation.mdc
.cursor/rules/guides/react-components.mdc
.cursor/rules/guides/rush.mdc
.cursor/rules/guides/tests.mdc
.cursor/rules/guides/typescript.mdc
.cursor/rules/packages/sdk-ui-kit-components.mdc

Added markdown documentation files in .cursor/rules directory to guide AI assistants when working with this codebase. Rules cover project architecture, coding standards, component implementation, and developer workflows.
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The …

docs: add cursor rules for AI assistance

---

libs/sdk-ui-kit/styles/scss/list.scss

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: fix backstop test

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/automation-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/scan-json-api/api.ts
libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/backend/workspace/permissions/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/dataSources/index.ts
libs/sdk-model/src/organization/index.ts
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/GranularPermissions.tsx
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/granularPermissionUtils.ts
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/locales.ts
libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/types.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: GDAI-203
---
> [!IMPORTANT]
---
```
``` …

fix: adopt new user permissions on FE

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts

JIRA: F1-1298
risk: low
---
> [!IMPORTANT]
---
```
``` …

chore: enable slideshow exports by default

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/exportDashboardToPDF.spec.ts
libs/sdk-ui-tests-e2e/cypress/tools/dashboardMenu.ts

JIRA: QA-24107
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

FEATURE: QA-24107 Update new behavior slide export

---

libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx

JIRA: LX-1025
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: make focus return working again

---

libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/tests/BaseHeadlineDataItem.test.tsx
libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/tests/withDrillable.test.tsx
libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/withDrillable.tsx
libs/sdk-ui-vis-commons/src/compactSize/HeadlinePaginationRenderer.tsx
libs/sdk-ui-vis-commons/styles/scss/headlinePagination.scss
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
JIRA: LX-1027
---
> [!IMPORTANT]
---
```
``` …

fix: headline acc. improvements

---

libs/sdk-ui-dashboard/src/model/react/useDashboardAlerting/useDashboardAlertsData.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: channels in alert dialog

---

libs/sdk-ui-charts/src/charts/headline/internal/headlines/baseHeadline/baseHeadlineDataItems/withDrillable.tsx

risk: low
JIRA: LX-1027
---
> [!IMPORTANT]
---
```
``` …

fix: position of drill hint for screen readers

---

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationSaveDialog.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/hooks/useVisualisationSaving.tsx
libs/sdk-ui-gen-ai/src/index.ts
libs/sdk-ui-gen-ai/src/store/events.ts
libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/onEvent.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/onVisualizationSave.ts
libs/sdk-ui-gen-ai/styles/scss/messages.scss

risk: low
JIRA: GDAI-204, GDAI-197
---
> [!IMPORTANT]
---
```
``` …

fix: show message when the insight is saved

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialogNew.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonOperatorSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertDestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertMeasureSelect.tsx
libs/sdk-ui-dashboard/styles/scss/alerting.scss
libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/styles/scss/Button/_mixins.scss
libs/sdk-ui-kit/styles/scss/button.scss
libs/sdk-ui-kit/styles/scss/typo-mixins.scss

risk: low
JIRA: F1-1367
---
> [!IMPORTANT]
---
```
``` …

style: alerting dialog design review

---

libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx

JIRA: LX-1025
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: move subheader out of menu container

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderAccountMenuItems.ts
libs/sdk-ui-kit/src/Header/tests/generateHeaderAccountMenuItems.test.ts
libs/sdk-ui-kit/src/Header/tests/mock.ts
libs/sdk-ui-kit/src/Header/typings.ts
libs/sdk-ui/src/base/localization/bundles/en-US.json

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add link to workspace settings to app header account menu

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts
libs/sdk-ui-dashboard/.dependency-cruiser.cjs
libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutViewSectionHeaderRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutSectionHeader.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemBase.tsx
libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemVisualization.tsx
libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: F1-1373
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: snapshot pdf export visual improvements for a11y

---

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx

jira: GDAI-217
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: the AI chatbot does not reflect the ui localization

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialogNew.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/utils.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx

---
> [!IMPORTANT]
---
```
```
- …

Automation filters fixes

---

.github/workflows/rw-rush-detect-changes.yml

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add log for detect changes revision

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/DashboardLayoutWidgetRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/layout/DefaultDashboardLayoutRenderer/DashboardLayoutWidgetRenderer.tsx
libs/sdk-ui-dashboard/styles/scss/export.scss

JIRA: F1-1373
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: snapshot pdf export layout improvements for a11y

---

libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.scss

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: Properly show UiMenu focus ring

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx

jira: GDAI-204, GDAI-197
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix(gen-ai): fix visualization save handler

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialogNew.tsx

JIRA: F1-1346
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: alert miscplaced dropdowns

---

libs/sdk-ui-tests-e2e/reference_workspace/fixtures/goodsales/tiger_metadata_extension.json
tools/reference-workspace-mgmt/fixtures/tiger_metadata_extension.json

JIRA: QA-24707
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

FEATURE: QA-24707 Update date local id

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-gen-ai/package.json
libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/styles/scss/input.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/syntaxHighlightingInput/SyntaxHighlightingInput.tsx
libs/sdk-ui-kit/src/syntaxHighlightingInput/hooks/useCodemirror.ts
libs/sdk-ui-kit/styles/scss/syntaxHighlightingInput.scss

jira: GDAI-141
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: use CodeMirror in chat input

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/DrillSelectDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/WithDrillSelect.tsx
libs/sdk-ui-dashboard/src/presentation/drill/DrillSelect/types.ts
libs/sdk-ui-dashboard/src/presentation/drill/index.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/DashboardInsightWithDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsightWithDrillSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogExportDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Dropdown/Dropdown.tsx

JIRA: LX-1028
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: Properly pass aria attributes in drill dialog

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/de-DE.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-AU.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-GB.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-419.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/es-ES.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fi-FI.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-CA.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/fr-FR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/it-IT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/ja-JP.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/nl-NL.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-BR.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/pt-PT.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-HK.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hans.json
libs/sdk-ui-dashboard/src/presentation/localization/bundles/zh-Hant.json
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/EditAlert.tsx
libs/sdk-ui-dashboard/styles/scss/alerting.scss

risk: low
JIRA: F1-1367 (issue 9)
see new comparison row on images below (discussed with Lukas Ther)
---
> [!IMPORTANT]
---
```
``` …

fix: comparison field

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/addAttributeFilter/AttributesDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/types.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/types.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx
libs/sdk-ui-filters/api/sdk-ui-filters.api.md
libs/sdk-ui-filters/src/AttributeFilter/AttributeFilterProviders.tsx
libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdown.tsx
libs/sdk-ui-filters/src/AttributeFilter/Context/AttributeFilterContext.tsx
libs/sdk-ui-filters/src/AttributeFilter/types.ts
libs/sdk-ui-filters/src/DateFilter/DateFilter.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx

JIRA: F1-1346
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: automation dropdowns on document scroll

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/useDashboardInsightDrills.ts
libs/sdk-ui-pivot/src/CorePivotTable.tsx
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

Fix double execution when drilling.
Do not cancel if previous execution is already completed.
risk: low
JIRA: F1-1377
---
> [!IMPORTANT]
---
```
``` …

fix: execution cancelling

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/CreateAlert.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertsOld.tsx

JIRA: F1-1231
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not allow to create alert in snapshot mode

---

common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/metadataUtilities.ts
libs/sdk-backend-base/api/sdk-backend-base.api.md
libs/sdk-backend-base/src/decoratedBackend/catalog.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/catalog.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/workspace/ldm/catalog.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/availableItemsFactory.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/datasetLoader.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/factory.ts
libs/sdk-backend-tiger/src/backend/workspace/catalog/rsqlFilter.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/dashboard/common/stateInitializers.ts
libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/package.json
libs/sdk-ui-gen-ai/src/components/ConfigContext.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatWrapper.tsx
libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/src/components/completion/InfoComponent.tsx
libs/sdk-ui-gen-ai/src/components/completion/index.ts
libs/sdk-ui-gen-ai/src/components/completion/useCompletion.ts
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json
libs/sdk-ui-gen-ai/styles/scss/input.scss
libs/sdk-ui-gen-ai/styles/scss/messages.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/syntaxHighlightingInput/SyntaxHighlightingInput.tsx
libs/sdk-ui-kit/src/syntaxHighlightingInput/hooks/useCodemirror.ts

JIRA: GDAI-141
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: use CodeMirror with autocomplete in chat input

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Header/generateHeaderAccountMenuItems.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: cleanup menu items hook after monorepo migrated to new signature

---

libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss
libs/sdk-ui-kit/styles/scss/header.scss
libs/sdk-ui-kit/styles/scss/shareDialogSelectControl.scss

risk: low
---
> [!IMPORTANT]
---
```
``` …

chore: remove outdated TODOs

---

common/changes/@gooddata/sdk-ui-all/pdo-lx-1057-label-rotation_2025-05-20-07-21.json

JIRA: LX-1057
risk: low
---
> [!IMPORTANT]
---
```
``` …

docs: update changelog with autorotation default value change

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts

JIRA: F1-1309
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: applying of automation filters on dashboard

---

.github/workflows/rw-rush-build-basic-checks.yml
common/config/rush/command-line.json
libs/api-client-tiger/package.json
libs/sdk-backend-base/package.json
libs/sdk-backend-spi/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-embedding/package.json
libs/sdk-model/package.json
libs/sdk-ui-filters/package.json
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/callbacks.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/elements/elementsSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/filter/filterSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/init/initSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadAttribute/loadAttributeSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadInitialElementsPage/loadInitialElementsPageSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/loadNextElementsPage/loadNextElementsPageSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/selection/selectionSelectors.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/createStore.ts
libs/sdk-ui-filters/src/AttributeFilterHandler/internal/redux/store/slice.ts
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/List/guid.ts
libs/sdk-ui-kit/src/Menu/menuOpener/MenuOpener.tsx
libs/sdk-ui-kit/src/Overlay/Overlay.tsx
libs/sdk-ui-kit/src/ZoomContext/ZoomContext.tsx
libs/sdk-ui-kit/src/responsive/useMediaQuery.ts
libs/sdk-ui-theme-provider/package.json
libs/sdk-ui/package.json
libs/sdk-ui/src/base/url/compression.ts
libs/util/package.json

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: add esm validation

---

common/config/rush/pnpm-lock.yaml

risk: low
JIRA: STL-1372
---
> [!IMPORTANT]
---
```
``` …

fix: upgrade vulnerable packages

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/DefaultAlertingDialogNew.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertAttributeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonOperatorSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertDestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertMeasureSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertTriggerModeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentFilters.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/DashboardAttachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/WidgetAttachments.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/hooks/useEditScheduledEmail.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx
libs/sdk-ui-kit/src/RecurrenceForm/Recurrence.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RecurrenceForm.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx

---
> [!IMPORTANT]
---
```
```
- …

automation fixes

---

libs/sdk-ui-gen-ai/styles/scss/main.scss

JIRA: GDAI-71
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: layout breaks when create Table viz on the Data page

---

libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx

JIRA: GDAI-245
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: multiple loading message when chatbot generate response

---

libs/sdk-ui-kit/src/@ui/UiMenu/components/defaults/DefaultUiMenuHeader.tsx

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: add close button id for test selector

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetHighlighting.ts

---
> [!IMPORTANT]
---
```
```
- …

asOfMode fixes

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
libs/sdk-ui-tests-e2e/cypress/tools/widgetConfiguration.ts

JIRA: QA-24820
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: invoke and force click on hidden elements

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/drilling.spec.ts
libs/sdk-ui-tests-e2e/cypress/tools/widgetConfiguration.ts

JIRA: QA-24820
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: avoid force true for hidden elements

---

libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/changeFilterContextSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetHighlighting.ts

---
> [!IMPORTANT]
---
```
```
- …

asOfMode filter context fixes

---

libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/RelativeDateFilterForm.tsx

risk: low
JIRA: LX-1030
---
> [!IMPORTANT]
---
```
``` …

fix: date filter props

---

libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss

JIRA: LX-1138
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: fix title for all types of items

---

libs/sdk-ui-filters/src/DateFilter/accessibility/keyboardNavigation.ts

risk: low
JIRA: LX-1030
---
> [!IMPORTANT]
---
```
``` …

fix: submit form on enter

---

libs/sdk-ui-filters/src/DateFilter/accessibility/keyboardNavigation.ts

risk: low
JIRA: LX-1030
---
> [!IMPORTANT]
---
```
``` …

fix: static period inputs keydown

---

libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/ConfigContext.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatDialog.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatWrapper.tsx
libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/src/components/completion/InfoComponent.tsx
libs/sdk-ui-gen-ai/src/components/completion/useCompletion.ts
libs/sdk-ui-gen-ai/src/components/completion/utils.ts
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json
libs/sdk-ui-gen-ai/styles/scss/input.scss

JIRA: GDAI-252
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: addtional information of Autocomplete is missing some items

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-tests-e2e/package.json
libs/sdk-ui-tests/package.json
tools/app-toolkit/package.json
tools/dashboard-plugin-template/package.json
tools/plugin-toolkit/package.json
tools/react-app-template/package.json

risk: low
JIRA: STL-1372
---
> [!IMPORTANT]
---
```
``` …

feat: upgrade vulnerable dependencies

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts

JIRA: F1-1416
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: automation context fallback common date filter

---

libs/sdk-ui-gen-ai/src/components/Messages.tsx
libs/sdk-ui-gen-ai/styles/scss/messages.scss

JIRA: GDAI-141
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: update for autocomplete tip and message

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts

JIRA: QA-24834
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: skip test esc close date dialog

---

libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterHeader.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterCore.tsx
libs/sdk-ui-filters/src/DateFilter/accessibility/keyboardNavigation.ts
libs/sdk-ui-filters/styles/scss/components/DateFilterBody.scss

risk: low
JIRA: LX-1030
---
> [!IMPORTANT]
---
```
``` …

fix: mobile navigation + close dialog esc

---

libs/sdk-ui-gen-ai/src/components/completion/InfoComponent.tsx
libs/sdk-ui-gen-ai/src/components/completion/utils.ts
libs/sdk-ui-gen-ai/src/components/highlight/useHighlight.ts
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json
libs/sdk-ui-gen-ai/styles/scss/input.scss

JIRA: GDAI-255
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add support for date into object autocompletion

---

libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx

JIRA: LX-1140
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: make selection working on dash menu again

---

libs/sdk-ui-dashboard/src/model/commandHandlers/scheduledEmail/initializeAutomationsHandler.ts

JIRA: F1-1309
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: match schedule common date filter

---

libs/sdk-ui-gen-ai/src/hooks/useGenAIStore.ts
libs/sdk-ui-gen-ai/src/store/options.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/index.ts
libs/sdk-ui-gen-ai/src/store/sideEffects/loadColorPalette.ts
libs/sdk-ui-gen-ai/src/store/store.ts

JIRA: GDAI-258
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: chatbot reloads twice

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts
libs/sdk-ui-tests-e2e/cypress/tools/dateFilterAbsoluteForm.ts

JIRA: QA-24834
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: update test esc close

---

libs/sdk-ui-charts/package.json
libs/sdk-ui-charts/scripts/validateEsmWithDom.js

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: add validation into sdk-ui-charts

---

libs/sdk-ui-kit/src/Dialog/DialogList/DialogListItemBasic.tsx
libs/sdk-ui-kit/styles/scss/dialogList.scss

JIRA: GDAI-203
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: update styles for dialog list item

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts

JIRA: QA-24853
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: skip test

---

libs/sdk-ui-dashboard/src/model/react/filtering/shared.ts

- Fix sanitization function for the widget filters
risk: low
JIRA: F1-1443
---
> [!IMPORTANT]
---
```
``` …

fix: alerting

---

libs/sdk-ui-ext/src/internal/components/dialogs/userManagementDialogs/Workspace/WorkspaceItem/granularPermissionUtils.ts

Separate AI from MANAGE
---
> [!IMPORTANT]
---
```
``` …

RELATED: GDAI-203 separate ai permission

---

.github/workflows/release-full.yml
.github/workflows/rw-doc-release-apidocs.yml
.github/workflows/rw-git-create-tag.yml
.github/workflows/rw-git-push.yml
.github/workflows/rw-publish-documentation.yml

risk: low
JIRA: STL-1385
---
> [!IMPORTANT]
---
```
``` …

feat: add full workflow for minor sdk release

---

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsData.ts
libs/sdk-ui-dashboard/src/model/react/useDashboardAlerting/useDashboardAlertsData.ts

risk: low
JIRA: F1-1354
---
> [!IMPORTANT]
---
```
``` …

fix: check also permissions for items visibility

---

libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx
libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterFormSection.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBodyContent.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBodyMobileContent.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateInput.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/EndDateInputField.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/StartDateInputField.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/TimeInput.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/types.ts
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/RelativeDateFilterFormSection.tsx
libs/sdk-ui-filters/src/DateFilter/accessibility/keyboardNavigation.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/utils/events.ts

JIRA: LX-975
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: validate absolute form on enter

---

libs/sdk-backend-tiger/src/backend/uiFeatures.ts

JIRA: LX-1124
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: enable enableLineChartTrendThreshold by default

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/accessibility/elementId.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsCommands.tsx
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsDialog.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsManagementDialog.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/automationFilters/components/AutomationFiltersSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/DeleteScheduleConfirmDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenuButton.tsx
libs/sdk-ui-dashboard/styles/scss/notifications_channels_dialog.scss
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/AddButton/AddButton.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx
libs/sdk-ui-kit/src/Timepicker/tests/Timepicker.test.tsx

risk: low
JIRA: LX-1032
---
> [!IMPORTANT]
---
```
``` …

feat: schedule dialog keyboard accessible

---

libs/sdk-ui-filters/src/DateFilter/DynamicSelect/utils.ts
libs/sdk-ui-filters/src/DateFilter/ExcludeCurrentPeriodToggle/ExcludeCurrentPeriodToggleLabel.tsx
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/GranularityTabs.tsx
libs/sdk-ui-filters/src/DateFilter/utils/Translations/DateFilterTitle.ts
libs/sdk-ui-filters/src/MeasureValueFilter/OperatorDropdown.tsx
libs/sdk-ui-filters/src/MeasureValueFilter/OperatorDropdownItem.tsx
libs/sdk-ui-filters/src/MeasureValueFilter/helpers/measureValueFilterOperator.ts

JIRA: LX-834
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not fail on react intl error for invalid filter granularity

---

libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/availableValueFilter.spec.ts

JIRA: LX-1147
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

fix: remove skip test

---

README.md

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add README change to test patch workflow

---

.github/workflows/rw-perform-release-patch.yml

risk: low
JIRA: STL-1386
---
> [!IMPORTANT]
---
```
``` …

fix: adjust patch workflow message

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/automation-json-api/api.ts
libs/api-client-tiger/src/generated/automation-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/export-json-api/api.ts
libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/scan-json-api/api.ts
libs/api-client-tiger/src/generated/scan-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-backend-base/src/dummyBackend/index.ts
libs/sdk-backend-mockingbird/src/recordedBackend/index.ts
libs/sdk-backend-spi/api/sdk-backend-spi.api.md
libs/sdk-backend-spi/src/organization/settings/index.ts
libs/sdk-backend-tiger/src/backend/organization/settings.ts
libs/sdk-backend-tiger/src/backend/settings/mapping.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: attachment settings api

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx

JIRA: GDAI-228
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: save icon overlapping with hamburger icon

---

libs/sdk-backend-mockingbird/src/recordedBackend/attributes.ts
libs/sdk-ui-kit/src/Header/tests/HeaderAccount.test.tsx
libs/sdk-ui-kit/src/Header/tests/HeaderMenu.test.tsx
libs/sdk-ui-kit/src/List/tests/LegacyInvertableList.test.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/index.tsx
libs/sdk-ui/src/base/localization/intlUtils.tsx
libs/sdk-ui/src/base/localization/test/IntlStore.test.ts

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix intl exeptions in UT

---

libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmails.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsDialog.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Attachments/AttachmentItems.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/hooks/useScheduleEmailDialogAccessibility.ts
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/hooks/useListWithActionsKeyboardNavigation.ts

- Schedule nested list
- Checkbox toggle
- Recipients select 
risk: low
JIRA: LX-1032
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to run integrated tests against the …

fix: schedule email fixes

---

.github/workflows/rw-bump-version.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: make bump version more robust

---

libs/sdk-ui-dashboard/src/presentation/presentationComponents/DashboardItems/DashboardItemVisualization.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/title/DefaultTitle.tsx
libs/sdk-ui-dashboard/src/presentation/topBar/topBar/DefaultTopBar.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx

---
> [!IMPORTANT]
---
```
```
- …

snaphost pdf export accessibility

---

libs/sdk-ui-dashboard/src/presentation/topBar/topBar/DefaultTopBar.tsx
libs/sdk-ui-dashboard/styles/scss/topBar.scss

JIRA: F1-1373
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: dashboard title styling in export mode

---

libs/sdk-backend-tiger/src/backend/organization/llmEndpoints.ts

JIRA: EB-347
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: llm provider setting not removed when saved in UI

---

libs/sdk-ui-gen-ai/src/components/messages/contents/CustomHyperlink.tsx

JIRA: GDAI-263
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: chatbot should exclude the links to metrics

---

.github/workflows/rw-doc-netlify-deploy.yml
.github/workflows/rw-git-push-rel-master-minor.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix git race condition release HUGO

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useWidgetHighlighting.ts

visualization on dashboard click in smart search doesn't scroll the dashboard page to correct visualization
JIRA: GDAI-328
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The …

fix: visualization on dashboard click in smart search doesn't scroll

---

libs/sdk-ui-gen-ai/src/components/completion/useCompletion.ts

JIRA: GDAI-335
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: autocomplete is expected to support multiple languages.

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/_staging/accessibility/elementId.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmails.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsDialog.ts
libs/sdk-ui-dashboard/src/model/react/useDasboardScheduledEmails/useDashboardScheduledEmailsManagementDialog.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiReducers.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiState.ts
libs/sdk-ui-dashboard/src/presentation/dashboard/DashboardHeader/ScheduledEmailDialogProvider.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/DefaultScheduledEmailDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/Header/ScheduleEmailDialogHeader.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/DefaultScheduledEmailManagementDialog.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmail.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailManagementDialog/components/ScheduledEmailsList.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/hooks/useScheduleEmailDialogAccessibility.ts
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/types.ts
libs/sdk-ui-dashboard/src/presentation/widget/insightMenu/DefaultDashboardInsightMenu/DashboardInsightMenuButton.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/AddButton/AddButton.tsx
libs/sdk-ui-kit/src/Datepicker/Datepicker.tsx
libs/sdk-ui-kit/src/RecurrenceForm/DateTime.tsx

risk: low
JIRA: LX-1032
---
> [!IMPORTANT]
---
```
``` …

fix: schedule dialog fixes

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/automation-json-api/api.ts
libs/api-client-tiger/src/generated/automation-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/export-json-api/api.ts
libs/api-client-tiger/src/generated/export-json-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/api-client-tiger/src/index.ts
libs/sdk-backend-tiger/src/backend/organization/llmEndpoints.ts
libs/sdk-backend-tiger/src/backend/workspace/dashboards/index.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/llmEndpointConvertor.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/llmEndpoints/index.ts

JIRA: GDAI-346
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: add new LLM provider get 400 Bad request error

---

libs/sdk-ui-tests-e2e/cypress/fixtures/dashboardInfosForExport.json

JIRA: QA-24954
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

test: correct export content

---

libs/sdk-ui-dashboard/styles/scss/filterBar.scss
libs/sdk-ui-vis-commons/styles/scss/legend.scss

risk: low
JIRA: LX-1181
---
> [!IMPORTANT]
---
```
``` …

fix: Use theme colors for various elements

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

chore: generate api

---

common/config/rush/pnpm-lock.yaml
libs/sdk-backend-tiger/package.json
libs/sdk-backend-tiger/tests/reference_workspace/create_test_workspaces.cjs
libs/sdk-backend-tiger/tests/reference_workspace/delete_test_workspaces.cjs
libs/sdk-ui-tests-e2e/package.json
libs/sdk-ui-tests-e2e/reference_workspace/lib/cleanup_tiger_workspaces.js
libs/sdk-ui-tests-e2e/reference_workspace/lib/create_tiger_workspace.js
libs/sdk-ui-tests-e2e/reference_workspace/lib/delete_helper.js
libs/sdk-ui-tests-e2e/reference_workspace/lib/delete_tiger_workspace.js
libs/sdk-ui-tests-e2e/reference_workspace/lib/export_tiger_workspace_fixture.js
libs/sdk-ui-tests-e2e/reference_workspace/lib/utils.js
libs/sdk-ui-tests-e2e/reference_workspace/prepareRecordingWorkspaceId.js
tools/reference-workspace-mgmt/bin/export_tiger_workspace_fixture.js
tools/reference-workspace-mgmt/bin/import_tiger_workspace_fixture.js
tools/reference-workspace-mgmt/package.json

Risk: low
JIRA: STL-1410
---
> [!IMPORTANT]
---
```
``` …

feat: bump fixtures to latest

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertConfig/hooks/useInsightWidgetAlerting.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/InsightAlertsOld.tsx

risk: low
JIRA: LX-1033
---
> [!IMPORTANT]
---
```
``` …

fix: Show delete alert confirmation when FF is off

---

libs/sdk-ui-pivot/src/impl/structure/colDefTemplates.ts
libs/sdk-ui-pivot/src/impl/structure/headers/ColumnHeader.tsx

---
> [!IMPORTANT]
---
```
```
- …

feat: pivot table sorting by keyboard improvements

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx

JIRA: F1-1316
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: allow to add more external recipients

---

libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/components/GenAIChatWrapper.tsx
libs/sdk-ui-gen-ai/src/components/GlobalError.tsx
libs/sdk-ui-gen-ai/src/components/Messages.tsx
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json
libs/sdk-ui-gen-ai/src/permissions/PermissionsContext.tsx
libs/sdk-ui-gen-ai/src/permissions/index.ts
libs/sdk-ui-gen-ai/src/permissions/usePermissions.ts
libs/sdk-ui-gen-ai/src/permissions/useWorkspacePermissions.ts
libs/sdk-ui-gen-ai/src/permissions/utils.ts

AI Assistant - full feature coverage in SDKs
Unclear error message happens when user don't have permission use AI chatbot in embeded mode
JIRA: GDAI-352, GDAI-313
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--backstop` The command to run screen tests (optionally with keeping …

fix: fixes related to public api

---

libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/RecipientsSelect/RecipientsSelectRenderer.tsx
libs/sdk-ui-dashboard/styles/scss/scheduled_mail_recipients.scss

risk: low
JIRA: LX-1178
---
> [!IMPORTANT]
---
```
``` …

feat: recipient input fields keyboard

---

libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss

JIRA: LX-776
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: add left padding between containers to have space for dropzone

---

libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts

JIRA: F1-1508
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: drill dialog xlsx export condition

---

libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/useDefaultMenuItems.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: do not use enableOrchestratedTabularExports FF for xlsx

---

docs/content/en/latest/references/embed_ai_assistant/_index.md
libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx

JIRA: GDAI-352, GDAI-313
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: fixes related to public api + doc

---

.github/workflows/test-backstop.yml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

feat: move backstop daily tests to earlier time

---

libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectVirtualised.tsx

risk: low
JIRA: LX-1029
---
> [!IMPORTANT]
---
```
``` …

fix: close dialog on empty search

---

libs/sdk-ui-kit/src/Dialog/Dialog.tsx

3. In modal version of the dialog, activate the keyboard trap, so the focus stays within the chatbot
JIRA: GDAI-360
risk: low
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command …

fix: updated keyboard accessibility of the chatbot

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiPagedVirtualList/UiPagedVirtualList.tsx
libs/sdk-ui-kit/src/List/InvertableSelect/InvertableSelectVirtualised.tsx

risk: low
JIRA: LX-1029
---
> [!IMPORTANT]
---
```
``` …

fix: custom keyboard over virtual list

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/insightToTable.ts
libs/sdk-ui-dashboard/styles/scss/dashboard.scss

JIRA: LX-1139
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: proper style to center icon in button when focused

---

common/config/rush/browser-approved-packages.json
common/config/rush/pnpm-lock.yaml
libs/sdk-ui-dashboard/package.json
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-dashboard/src/presentation/topBar/menuButton/DefaultMenuButton.tsx
libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/@utils/keyboardNavigation.ts
libs/sdk-ui-kit/src/@ui/UiFocusTrap/UiFocusTrap.tsx
libs/sdk-ui-kit/src/index.ts

---
> [!IMPORTANT]
---
```
```
- …

feat: improved filter bar keyboard navigation

---

libs/sdk-ui-kit/src/Messages/tests/Messages.test.tsx
libs/sdk-ui-tests/stories/visual-regression/kit/Messages/Messages.tsx

risk: low
JIRA: F1-1492
---
> [!IMPORTANT]
---
```
``` …

chore: sync copy

---

.github/workflows/check-approve.yml
.github/workflows/gate.yaml

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: fix bear approve

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/model/commands/insight.ts
libs/sdk-ui-dashboard/src/presentation/widget/common/useInsightExport.ts

risk: low
JIRA: LX-1117
---
> [!IMPORTANT]
---
```
``` …

fix: raw export dashboard filters

---

libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertAttributeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonOperatorSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertComparisonPeriodSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertDestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertMeasureSelect.tsx
libs/sdk-ui-dashboard/src/presentation/alerting/DefaultAlertingDialog/components/AlertTriggerModeSelect.tsx
libs/sdk-ui-dashboard/src/presentation/scheduledEmail/DefaultScheduledEmailDialog/components/DestinationSelect/DestinationSelect.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogExportDropdown.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/VisualizationSwitcherNavigationHeader.tsx
libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiListbox/UiListbox.tsx
libs/sdk-ui-kit/src/@ui/UiListbox/tests/UiListbox.test.tsx
libs/sdk-ui-kit/src/RecurrenceForm/RepeatTypeSelect.tsx
libs/sdk-ui-kit/src/Timepicker/Timepicker.tsx

---
> [!IMPORTANT]
---
```
```
- …

UI components cleanup

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiListbox/types.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove classnames props from UiListBox interface

---

libs/sdk-ui-ext/src/internal/components/configurationControls/interactions/InteractionsSection.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/ConfigurationPanelContent.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/PivotTableConfigurationPanel.tsx
libs/sdk-ui-ext/src/internal/components/configurationPanels/sectionName.ts

---
> [!IMPORTANT]
---
```
```
- …

feat: allow some interactions for table without metrics

---

libs/sdk-ui-filters/src/AttributeFilter/Components/Dropdown/AttributeFilterDropdownActions.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/styles/scss/attributeFilterNext/attributeFilterDropdownActions.scss

JIRA: LX-863
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat(sdk-ui-filters): distinguish classes for close and cancel btns

---

libs/sdk-ui-charts/src/highcharts/adapter/HighChartsRenderer.tsx
libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideBarLabels.ts
libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideColumnLabels.ts
libs/sdk-ui-charts/src/highcharts/adapter/plugins/autohideLabels/autohideLabelsOverlappingItsShape.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/customConfiguration.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/dataLabelsHelpers.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/helpers.ts
libs/sdk-ui-charts/src/highcharts/chartTypes/_chartCreators/test/customConfiguration.test.ts
libs/sdk-ui-tests/stories/visual-regression/visualizations/barChart/index.tsx
libs/sdk-ui-tests/stories/visual-regression/visualizations/barChart/zoomButtonFix.css

---
> [!IMPORTANT]
---
```
```
- …

feat: make zooming compatible with data label hidding 

---

libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/EditableDashboardInsightWidget.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/VisualizationSwitcherWidget/EditableDashboardVisualizationSwitcherWidget.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-tests-e2e/cypress/tools/widgetConfiguration.ts

JIRA: LX-1202
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove widget options button in Edit mode

---

libs/sdk-ui-dashboard/src/model/commandHandlers/widgets/exportRawInsightWidgetHandler.ts
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/DrillDialogInsight.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/InsightDrillDialog/InsightDrillDialog.tsx
libs/sdk-ui-dashboard/src/presentation/widget/insight/configuration/ExportOptions.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/InsightWidget/DefaultDashboardInsightWidget.tsx

risk: low
JIRA: LX-1117
---
> [!IMPORTANT]
---
```
``` …

fix: raw exports dashboard filters

---

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md

risk: low
---
> [!IMPORTANT]
---
```
``` …

docs: explicitly specify supported React versions

---

common/config/rush/pnpm-lock.yaml
libs/api-client-tiger/package.json
libs/sdk-backend-tiger/package.json
libs/sdk-ui-tests-e2e/package.json
tools/app-toolkit/package.json
tools/plugin-toolkit/package.json

Risk: low
JIRA: STL-1347
---
> [!IMPORTANT]
---
```
``` …

feat: upgrade axios to latest

---

docs/content/en/latest/references/embed_ai_assistant/_index.md

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: update doc

---

libs/sdk-ui-gen-ai/src/components/Input.tsx
libs/sdk-ui-gen-ai/src/components/messages/AssistantMessage.tsx
libs/sdk-ui-gen-ai/src/components/messages/UserMessage.tsx
libs/sdk-ui-gen-ai/src/localization/bundles/en-US.json
libs/sdk-ui-gen-ai/styles/scss/messages.scss
libs/sdk-ui-kit/src/syntaxHighlightingInput/hooks/useCodemirrorOptions.ts

risk: low
JIRA: GDAI-375
---
> [!IMPORTANT]
---
```
``` …

fix: ai assistant not read correctly by screen readers

---

libs/sdk-ui-dashboard/src/_staging/layout/coordinates.ts
libs/sdk-ui-dashboard/src/_staging/layout/test/coordinates.test.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveSectionItemHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/moveSectionItemToNewSectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/tests/moveSectionItemHandler.test.ts
libs/sdk-ui-dashboard/src/model/store/ui/uiSelectors.ts

---
> [!IMPORTANT]
---
```
```
- …

fix: handle properly move operation

---

libs/sdk-ui-dashboard/src/_staging/dashboard/flexibleLayout/layoutConfiguration.ts
libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerWidthSanitization.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/resizeWidthHandler.ts
libs/sdk-ui-dashboard/src/model/store/layout/layoutReducers.ts
libs/sdk-ui-dashboard/src/model/types/layoutTypes.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DefaultDashboardLayoutRenderer/useItemWidthValidation.tsx

JIRA: LX-1224
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: resize content when the column container width is changed

---

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerWidthSanitization.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/toggleLayoutDirectionHandler.ts

JIRA: LX-1204
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: update container content upon the container's direction change

---

libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableWidget/AddDashboardLayoutWidgetButton.tsx
libs/sdk-ui-dashboard/src/presentation/localization/bundles/en-US.json
libs/sdk-ui-kit/src/@ui/UiLink/UiLink.scss

risk: low
JIRA: LX-1236
---
> [!IMPORTANT]
---
```
``` …

fix: Improve UiLink styles and container tooltip

---

docs/content/en/latest/references/embed_semantic_search/_index.md

Add comprehensive documentation for the Semantic Search component in the GoodData UI SDK. The documentation includes:
- Introduction and feature overview
- Basic integration example with code samples
- Detailed props reference
- useSemanticSearch hook documentation with parameters and return values
- Search result item interface details
This completes the documentation for the Semantic Search functionality, following the same structure as other component documentation in the SDK.
risk: low
JIRA: GDAI-424
---
> [!IMPORTANT]
--- …

feat: add Semantic Search component documentation

---

libs/sdk-ui-kit/src/DocumentHeader/DocumentHeader.tsx

Risk: low
JIRA: STL-1516
---
> [!IMPORTANT]
---
```
``` …

feat: Replace react-helmet usages with custom implementation

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-gen-ai/package.json
libs/sdk-ui-kit/package.json
libs/sdk-ui-kit/src/Form/InputPure.tsx
libs/sdk-ui-kit/src/typings.d.ts

Risk: low
JIRA: STL-1519
---
> [!IMPORTANT]
---
```
``` …

feat: Remove react-native-listener usages

---

libs/sdk-ui-gen-ai/src/components/hooks/useThreadLoading.ts
libs/sdk-ui-gen-ai/src/store/index.ts
libs/sdk-ui-gen-ai/src/store/messages/messagesSelectors.ts
libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts

risk: low
JIRA: GDAI-421
---
> [!IMPORTANT]
---
```
``` …

fix: the AI chatbot auto reload when reopen

---

libs/sdk-ui-dashboard/src/presentation/widget/insight/ViewModeDashboardInsight/Insight/DashboardInsight.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss

JIRA: LX-1165
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: make load hiding compatible with test selectors

---

libs/sdk-ui-dashboard/src/presentation/dashboard/DefaultDashboardContent/DefaultDashboardMainContent.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/DashboardLayoutWidget.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/Hotspot.tsx
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/RowEndHotspot.tsx
libs/sdk-ui-dashboard/src/presentation/widget/widget/DashboardNestedLayoutWidget/EditableDashboardNestedLayoutWidget.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss
libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss

JIRA: LX-1235
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: reset dropzone styles between the interlaced direction

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/Hotspot.tsx

JIRA: LX-1235
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: failing e2e

---

libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/draggableWidget/EmptyNestedLayoutDropZone.tsx
libs/sdk-ui-dashboard/styles/scss/dashboard.scss
libs/sdk-ui-dashboard/styles/scss/dashboardNestedLayoutWidget.scss

risk: low
JIRA: LX-1282
---
> [!IMPORTANT]
---
```
``` …

fix: adjust flexible container empty content width

---

common/changes/@gooddata/sdk-ui-all/ine-lx-1286_2025-07-07-14-06.json
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/useDashboardDragScroll.ts

JIRA: LX-1286
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: exclude width resizer from auto scroll

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/generated/afm-rest-api/api.ts
libs/api-client-tiger/src/generated/afm-rest-api/openapi-spec.json
libs/api-client-tiger/src/generated/metadata-json-api/openapi-spec.json
libs/sdk-backend-tiger/src/convertors/fromBackend/AutomationConverter.ts
libs/sdk-backend-tiger/src/convertors/fromBackend/ExportDefinitionsConverter.ts
libs/sdk-backend-tiger/src/convertors/toBackend/AutomationConverter.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/entitlements/index.ts

JIRA: F1-1527
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: introduce new ControlledFeatureRollout entitlement

---

libs/sdk-ui-charts/src/charts/_base/BaseChart.tsx
libs/sdk-ui/api/sdk-ui.api.md
libs/sdk-ui/src/base/react/legacy/withEntireDataView.tsx

risk: low
JIRA: GDAI-439
---
> [!IMPORTANT]
---
```
``` …

fix: repair too many datapoints error message

---

common/changes/@gooddata/sdk-ui-all/pdo-lx-1283-heigh-dropzone_2025-07-08-06-52.json
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerHeightSanitization.ts

JIRA: LX-1284
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: size containers to full row height to fix the last drop zone size

---

common/config/rush/pnpm-lock.yaml
libs/sdk-ui-tests-e2e/package.json
libs/sdk-ui-tests-e2e/scenarios/webpack.config.cjs
libs/sdk-ui-web-components/package.json
tools/app-toolkit/package.json
tools/dashboard-plugin-template/package.json
tools/dashboard-plugin-template/webpack.config.cjs
tools/react-app-template/package.json
tools/react-app-template/webpack.config.cjs

---
> [!IMPORTANT]
---
```
```
- …

chore: fix toolkit and plugins template 

---

libs/sdk-ui-dashboard/src/_staging/layout/sizing.ts
libs/sdk-ui-dashboard/styles/scss/dragAndDrop.scss
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/constants.ts

risk: low
JIRA: LX-1287
---
> [!IMPORTANT]
---
```
``` …

fix: handle empty container height

---

libs/api-client-tiger/api/api-client-tiger.api.md
libs/api-client-tiger/src/profile.ts
libs/sdk-backend-tiger/src/backend/features/hub.ts
libs/sdk-backend-tiger/src/backend/features/index.ts
libs/sdk-backend-tiger/src/backend/features/test/hub.test.ts
libs/sdk-backend-tiger/src/backend/workspace/settings/index.ts

JIRA: F1-1527
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: send ControlledFeatureRollout entitlement to feture hub

---

libs/sdk-ui-dashboard/styles/scss/_variables.scss

risk: low
JIRA: LX-1310
---
> [!IMPORTANT]
---
```
``` …

fix: correct config panel height

---

libs/sdk-ui-dashboard/src/model/commandHandlers/layout/containerWidthSanitization.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/resizeWidthHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/layout/toggleLayoutDirectionHandler.ts
libs/sdk-ui-dashboard/src/presentation/flexibleLayout/dragAndDrop/Resize/WidthResizerHotspot.tsx

even column containers are now processed recursively
---
> [!IMPORTANT]
---
```
``` …

fix: make column width resizing compatible with latest changes

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/organization/index.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/organization/index.ts
libs/sdk-model/src/settings/index.ts

risk: low
JIRA: LX-1327
---
> [!IMPORTANT]
---
```
``` …

feat: introduce organization IdP type

---

libs/sdk-ui-gen-ai/src/components/messages/contents/VisualizationContents.tsx

risk: low
JIRA: GDAI-466
---
> [!IMPORTANT]
---
```
``` …

fix: update attribute data-testId for adhoc viz

---

common/changes/@gooddata/sdk-ui-all/pdo-lx-1330-ff_2025-07-11-10-27.json
libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

JIRA: LX-1330
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: introduce a new feature flag for pre-aggregated facts

---

libs/sdk-ui-dashboard/styles/scss/insightConfiguration.scss
libs/sdk-ui-kit/src/@ui/UiMenu/UiMenu.scss

JIRA: LX-1328
risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: remove unused styles and fix insight menu in edit mode

---

libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/dashboardDropdownBody/configuration/limitValues/dialog/WithDisabledParentFilterTooltip.tsx
libs/sdk-ui-dashboard/styles/scss/attributeFilterConfig.scss

risk: low
JIRA: LX-1221
---
> [!IMPORTANT]
---
```
``` …

fix: bubble takes whole div width

---

libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterForm.tsx
libs/sdk-ui-filters/src/DateFilter/AbsoluteDateFilterForm/AbsoluteDateFilterFormSection.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBody.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBodyContent.tsx
libs/sdk-ui-filters/src/DateFilter/DateFilterBody/DateFilterBodyMobileContent.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateInput.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateRangePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/DateTimePicker.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/StartDateInputField.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/TimeInput.tsx
libs/sdk-ui-filters/src/DateFilter/DateRangePicker/types.ts
libs/sdk-ui-filters/src/DateFilter/RelativeDateFilterForm/RelativeDateFilterFormSection.tsx
libs/sdk-ui-filters/src/DateFilter/accessibility/keyboardNavigation.ts

risk: low
JIRA: LX-1195
---
> [!IMPORTANT]
---
```
``` …

fix: dont submit date filter on enter key when apply all

---

docs/content/en/latest/references/embed_ai_assistant/_index.md
docs/content/en/latest/references/embed_semantic_search/_index.md
libs/sdk-ui-gen-ai/api-extractor.json
libs/sdk-ui-gen-ai/api/sdk-ui-gen-ai.api.md
libs/sdk-ui-gen-ai/src/components/GenAIChat.tsx
libs/sdk-ui-gen-ai/src/index.ts
libs/sdk-ui-gen-ai/src/model.ts
libs/sdk-ui-gen-ai/src/store/messages/messagesSlice.ts
libs/sdk-ui-semantic-search/api/sdk-ui-semantic-search.api.md
libs/sdk-ui-semantic-search/src/FooterButtonAiAssistant.tsx
libs/sdk-ui-semantic-search/src/SemanticSearch.tsx
libs/sdk-ui-semantic-search/src/index.ts
libs/sdk-ui-semantic-search/src/internal.ts
libs/sdk-ui-semantic-search/styles/scss/internal.scss
libs/sdk-ui-semantic-search/styles/scss/main.scss

risk: low
JIRA: GDAI-473
---
> [!IMPORTANT]
---
```
``` …

fix: expose API for adding footer button in public search

---

libs/sdk-ui-dashboard/api/sdk-ui-dashboard.api.md
libs/sdk-ui-dashboard/src/model/commandHandlers/drill/crossFilteringHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeDisplayFormHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/attributeFilter/changeAttributeFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/dateFilter/changeDateFilterSelectionHandler.ts
libs/sdk-ui-dashboard/src/model/commandHandlers/filterContext/filterViewHandler.ts
libs/sdk-ui-dashboard/src/model/store/config/configSelectors.ts
libs/sdk-ui-dashboard/src/model/store/index.ts
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableAttributeFilter/DraggableAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/dragAndDrop/draggableDateFilter/DraggableDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/CustomDropdownActions.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/DefaultDashboardAttributeFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useDependentDateFilters.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/attributeFilter/useParentFilters.ts
libs/sdk-ui-dashboard/src/presentation/filterBar/dateFilter/DefaultDashboardDateFilter.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBar.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/DefaultFilterBarContainer.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/filterViews/FilterViews.tsx
libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

fix: unify conditions to check both FF and setting

---

docs/content/en/latest/references/filters/attribute_filter_button_component.md

risk: nonprod
jira: DP-3203
---
> [!IMPORTANT]
---
```
``` …

fix: documenting missing attribute filter props

---

libs/sdk-ui-kit/api/sdk-ui-kit.api.md
libs/sdk-ui-kit/src/@ui/UiIcon/UiIcon.scss
libs/sdk-ui-kit/src/@ui/UiIcon/UiIcon.tsx

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: Allow UiIcon to be rendered as a block element

---

libs/sdk-ui-kit/scripts/validateUiComponents.js

risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

chore: extend forbidden prop names

---

libs/sdk-ui-web-components/README.md
libs/sdk-ui-web-components/src/index.ts
libs/sdk-ui-web-components/webpack.config.cjs

JIRA: EB-372
Enable runtime configuration of the public (assets) path for the web components package.
risk: low

feat(web-components): enable public path runtime config

---

libs/sdk-backend-tiger/src/backend/organization/index.ts

risk: low
JIRA: LX-1327
---
> [!IMPORTANT]
---
```
``` …

fix: obtain idpType from correct place

---

libs/sdk-ui-dashboard/src/presentation/filterBar/filterBar/hooks/useResetFiltersButton.ts

risk: low
JIRA: LX-958
---
> [!IMPORTANT]
---
```
``` …

fix: handle all time common filter reset button

---

libs/sdk-ui-tests-e2e/README.md
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/permissions.spec.ts
libs/sdk-ui-tests-e2e/cypress/integration/01-sdk-ui-dashboard/shareDashboardToEveryone.spec.ts

JIRA: STL-1556
risk: nonprod
---
> [!IMPORTANT]
---
```
``` …

feat: move post merge to checklist

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add new pivot table feature flag

---

libs/sdk-backend-tiger/src/backend/features/feature.ts
libs/sdk-backend-tiger/src/backend/uiFeatures.ts
libs/sdk-model/api/sdk-model.api.md
libs/sdk-model/src/settings/index.ts

risk: low
---
> [!IMPORTANT]
---
```
``` …

chore: remove enableProductionFeaturesRollout ff

---

docs/content/en/latest/references/filters/attribute_filter.md

fix: documenting missing attribute filter props v2

---

libs/sdk-ui-ext/src/insightView/InsightRenderer.tsx
libs/sdk-ui-ext/src/internal/components/BaseVisualization.tsx
libs/sdk-ui-ext/src/internal/components/VisualizationCatalog.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/PivotTableNextDescriptor.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/PluggablePivotTableNext.tsx
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/configHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/helpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/pivotTableNextConfigFromInsight.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/sortHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/totalsHelpers.ts
libs/sdk-ui-ext/src/internal/components/pluggableVisualizations/pivotTableNext/widthItemsHelpers.ts
libs/sdk-ui-ext/src/internal/constants/supportedProperties.ts
libs/sdk-ui-ext/src/internal/utils/uiConfigHelpers/pivotTableNextUiConfigHelper.ts
libs/sdk-ui-pivot/src/next/PivotTableNext.tsx
libs/sdk-ui-pivot/src/next/constants/internal.ts
libs/sdk-ui-pivot/src/next/drill/getAvailableDrillTargets.ts
libs/sdk-ui-pivot/src/next/execution/getExecution.ts
libs/sdk-ui-pivot/src/next/hooks/useInitExecution.ts
libs/sdk-ui-pivot/src/next/hooks/useServerSideRowModel.ts
libs/sdk-ui-pivot/src/next/index.ts
libs/sdk-ui-pivot/src/next/mapProps/mapSortModelToSortItems.ts
libs/sdk-ui-pivot/src/next/mapProps/tests/mapDataViewToAgGridRowData.test.ts
libs/sdk-ui-pivot/src/next/mapProps/tests/mapDimensionsToColDefs.test.ts
libs/sdk-ui-pivot/src/next/types/public.ts

JIRA: F1-1552
risk: low
---
> [!IMPORTANT]
---
```
``` …

feat: add pluggable pivot table next

---

docs/content/en/latest/references/embed_semantic_search/_index.md

This PR  enhances search query context in documentation example and fixes type errors.
---
> [!IMPORTANT]
---
```
```
-   `--integrated` The command to run integrated tests against the …

fix(docs): enhance search query context in docs example

---

libs/sdk-ui-filters/src/AttributeFilter/hooks/useAttributeFilterController.ts

risk: low
JIRA: LX-1386
---
> [!IMPORTANT]
---
```
``` …

fix: selection invalid reload only with apply all

---

docs/content/en/latest/architecture/supported_frameworks/angular.md

fix: updating react version in angular code snippet

---

common/changes/@gooddata/sdk-ui-all/ine-lx-1257_2025-07-29-11-29.json
common/config/rush/pnpm-lock.yaml

Automated sync of `sdk/` from `gdc-ui` → `gooddata-ui-sdk`\n\nSource hash: 6dc134787f1898f7e21dd207ec6c1913bef64e51

Sync from gdc-ui/sdk hash:6dc134787f1898f7e21dd207ec6c1913bef64e51

---

docs/content/en/latest/architecture/architecture_overview/compatibility/_index.md

risk: nonprod
Please submit your changes to **gdc-ui**; they will be automagically propagated here.
The only exception is PRs targeting the legacy BEAR platform, specifically the **rel/9.9** branch.
**Commands for Bear platform working on branch rel/9.9**
```
extended-test-legacy --backstop
extended-test-legacy --isolated
extended-test-legacy --record
```

chore: fix doc
